AnalysisG: <name>.h File Reference
<name>.h File Reference
#include <templates/metric_template.h>
Macros
#define name >_METRIC_H
Functions
< name > _metric * clone () override
void define_metric (metric_t *mtx) override
void define_variables () override
void event () override
void batch () override
void end () override
Variables
<#define name class< name > _metric
Macro Definition Documentation
name
#define name >_METRIC_H
Function Documentation
batch()
void batch () override
Referenced by pyc::nusol::combinatorial().
clone()
<name> _metric* clone () override
Referenced by _H_perp(), container::compile(), optimizer::import_model_sessions(), nusol_::Intersection(), and graph_::node_aggregation().
define_metric()
void define_metric (metric_t * mtx) override
define_variables()
void define_variables () override
end()
void end () override
Referenced by particle_template::__reduce__(), dataloader::build_batch(), chunking(), write_t::close(), gnn_event::CompileEvent(), dataloader::datatransfer(), analytics_t::destroy(), dataloader::dump_dataset(), metrics::dump_mass_plots(), container::fill_selections(), model_template::flush_outputs(), dataloader::generate_kfold_set(), container::get_events(), dataloader::get_inference(), topefficiency::iters(), topkinematics::merge(), merge_data(), model_report::prx(), dataloader::restore_dataset(), dataloader::restore_graphs(), particle_template::set_children(), model_template::set_output_features(), particle_template::set_parents(), pyc::std_to_dict(), sum_data(), tensor_vector(), selection_template::upcast(), topmatching::vectorize(), selection_template::vectorize(), write_t::write(), container::~container(), metric_t::~metric_t(), and particle_template::~particle_template().
event()
void event () override
Variable Documentation
_metric
< name > _metric override
Definition at line 9 of file <name>.h.