AnalysisG: edge_features.h File Reference
edge_features.h File Reference
Functions
static void m_res_edge (int *o, top *t)
static void m_res_edge (int *o, top_children *t)
static void m_res_edge (int *o, truthjet *t)
static void m_res_edge (int *o, jet *t)
static void m_res_edge (int *o, electron *t)
static void m_res_edge (int *o, muon *t)
static void res_edge (int *o, std::tuple< particle_template *, particle_template * > *pij)
static int m_top_edge (top *t)
static int m_top_edge (top_children *t)
static std::vector< int > m_top_edge (truthjet *t)
static std::vector< int > m_top_edge (jet *t)
static std::vector< int > m_top_edge (electron *t)
static std::vector< int > m_top_edge (muon *t)
static void top_edge (int *o, std::tuple< particle_template *, particle_template * > *pij)
Function Documentation
m_res_edge() [1/6]
static void m_res_edge (int * o, electron * t) static
Definition at line 9 of file bsm_4tops/include/bsm_4tops/edge_features.h.
m_res_edge() [2/6]
static void m_res_edge (int * o, jet * t) static
Definition at line 8 of file bsm_4tops/include/bsm_4tops/edge_features.h.
m_res_edge() [3/6]
static void m_res_edge (int * o, muon * t) static
Definition at line 10 of file bsm_4tops/include/bsm_4tops/edge_features.h.
m_res_edge() [4/6]
static void m_res_edge (int * o, top * t) static
Definition at line 5 of file bsm_4tops/include/bsm_4tops/edge_features.h.
Referenced by res_edge().
m_res_edge() [5/6]
static void m_res_edge (int * o, top_children * t) static
Definition at line 6 of file bsm_4tops/include/bsm_4tops/edge_features.h.
m_res_edge() [6/6]
static void m_res_edge (int * o, truthjet * t) static
Definition at line 7 of file bsm_4tops/include/bsm_4tops/edge_features.h.
m_top_edge() [1/6]
static std::vector< int > m_top_edge (electron * t) static
Definition at line 43 of file bsm_4tops/include/bsm_4tops/edge_features.h.
m_top_edge() [2/6]
static std::vector< int > m_top_edge (jet * t) static
Definition at line 42 of file bsm_4tops/include/bsm_4tops/edge_features.h.
m_top_edge() [3/6]
static std::vector< int > m_top_edge (muon * t) static
Definition at line 44 of file bsm_4tops/include/bsm_4tops/edge_features.h.
m_top_edge() [4/6]
static int m_top_edge (top * t) static
Definition at line 39 of file bsm_4tops/include/bsm_4tops/edge_features.h.
References index.
Referenced by top_edge().
m_top_edge() [5/6]
static int m_top_edge (top_children * t) static
Definition at line 40 of file bsm_4tops/include/bsm_4tops/edge_features.h.
m_top_edge() [6/6]
static std::vector< int > m_top_edge (truthjet * t) static
Definition at line 41 of file bsm_4tops/include/bsm_4tops/edge_features.h.
res_edge()
static void res_edge (int * o, std::tuple< particle_template *, particle_template * > * pij) static
Definition at line 12 of file bsm_4tops/include/bsm_4tops/edge_features.h.
References m_res_edge().
Referenced by graph_tops::CompileEvent(), graph_children::CompileEvent(), graph_truthjets::CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), graph_detector::CompileEvent(), grift::forward(), and recursivegraphneuralnetwork::forward().
top_edge()
static void top_edge (int * o, std::tuple< particle_template *, particle_template * > * pij) static
Definition at line 46 of file bsm_4tops/include/bsm_4tops/edge_features.h.
References m_top_edge().
Referenced by graph_children::CompileEvent(), graph_truthjets::CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), graph_detector::CompileEvent(), and grift::forward().