AnalysisG: graph_features.h File Reference
graph_features.h File Reference
Functions
static void signal_event (bool *o, bsm_4tops *event)
static void num_tops (int *o, bsm_4tops *event)
static void num_neutrino (int *o, bsm_4tops *event)
static void num_lepton (int *o, bsm_4tops *event)
static void missing_et (double *o, bsm_4tops *event)
static void missing_phi (double *o, bsm_4tops *event)
static void num_children_leps (double *o, bsm_4tops *event)
static void num_leps (double *o, bsm_4tops *event)
static void num_quark (double *o, bsm_4tops *event)
static void num_jets (double *o, bsm_4tops *event)
static void num_truthjets (double *o, bsm_4tops *event)
static void event_number (long *o, bsm_4tops *event)
static void event_weight (double *o, bsm_4tops *event)
Function Documentation
event_number()
static void event_number (long * o, bsm_4tops * event) static
Definition at line 74 of file bsm_4tops/include/bsm_4tops/graph_features.h.
References event_number().
Referenced by graph_tops::CompileEvent(), graph_children::CompileEvent(), graph_truthjets::CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), graph_detector::CompileEvent(), and event_number().
event_weight()
static void event_weight (double * o, bsm_4tops * event) static
Definition at line 75 of file bsm_4tops/include/bsm_4tops/graph_features.h.
References weight.
Referenced by graph_tops::CompileEvent(), graph_children::CompileEvent(), graph_truthjets::CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), graph_detector::CompileEvent(), graph_template::data_export(), dataloader::dump_graphs(), io::member(), and regions::strategy().
missing_et()
static void missing_et (double * o, bsm_4tops * event) static
Definition at line 46 of file bsm_4tops/include/bsm_4tops/graph_features.h.
Referenced by graph_tops::CompileEvent(), graph_children::CompileEvent(), graph_truthjets::CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), and graph_detector::CompileEvent().
missing_phi()
static void missing_phi (double * o, bsm_4tops * event) static
Definition at line 47 of file bsm_4tops/include/bsm_4tops/graph_features.h.
References phi.
Referenced by graph_tops::CompileEvent(), graph_children::CompileEvent(), graph_truthjets::CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), and graph_detector::CompileEvent().
num_children_leps()
static void num_children_leps (double * o, bsm_4tops * event) static
Definition at line 49 of file bsm_4tops/include/bsm_4tops/graph_features.h.
References is_lep, and is_nu.
Referenced by graph_children::CompileEvent(), graph_truthjets::CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), and graph_jets_nonu::CompileEvent().
num_jets()
static void num_jets (double * o, bsm_4tops * event) static
Definition at line 71 of file bsm_4tops/include/bsm_4tops/graph_features.h.
Referenced by graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), graph_detector::CompileEvent(), matching::current(), matching::dump(), matching::experimental(), grift::forward(), recursivegraphneuralnetwork::forward(), matching::match_obj(), and matching::reference().
num_leps()
static void num_leps (double * o, bsm_4tops * event) static
Definition at line 58 of file bsm_4tops/include/bsm_4tops/graph_features.h.
Referenced by graph_jets_detector_lep::CompileEvent(), graph_detector::CompileEvent(), grift::forward(), recursivegraphneuralnetwork::forward(), combinatorial::selection(), and validation::selection().
num_lepton()
static void num_lepton (int * o, bsm_4tops * event) static
Definition at line 33 of file bsm_4tops/include/bsm_4tops/graph_features.h.
References is_lep, and is_nu.
Referenced by graph_children::CompileEvent(), graph_truthjets::CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), and graph_detector::CompileEvent().
num_neutrino()
static void num_neutrino (int * o, bsm_4tops * event) static
Definition at line 22 of file bsm_4tops/include/bsm_4tops/graph_features.h.
References is_nu.
Referenced by graph_children::CompileEvent(), and graph_truthjets::CompileEvent().
num_quark()
static void num_quark (double * o, bsm_4tops * event) static
Definition at line 62 of file bsm_4tops/include/bsm_4tops/graph_features.h.
References is_lep, and is_nu.
Referenced by graph_children::CompileEvent().
num_tops()
static void num_tops (int * o, bsm_4tops * event) static
Definition at line 17 of file bsm_4tops/include/bsm_4tops/graph_features.h.
Referenced by graph_tops::CompileEvent(), graph_children::CompileEvent(), graph_truthjets::CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), graph_detector::CompileEvent(), and matching::dump().
num_truthjets()
static void num_truthjets (double * o, bsm_4tops * event) static
Definition at line 72 of file bsm_4tops/include/bsm_4tops/graph_features.h.
Referenced by graph_truthjets::CompileEvent(), and graph_truthjets_nonu::CompileEvent().
signal_event()
static void signal_event (bool * o, bsm_4tops * event) static
Definition at line 5 of file bsm_4tops/include/bsm_4tops/graph_features.h.
Referenced by graph_tops::CompileEvent(), graph_children::CompileEvent(), graph_truthjets::CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), and graph_detector::CompileEvent().