AnalysisG: node_features.h File Reference
node_features.h File Reference
Functions
static void res_node (int *o, particle_template *p)
static void top_node (int *o, particle_template *p)
static void pt (double *o, particle_template *p)
static void eta (double *o, particle_template *p)
static void phi (double *o, particle_template *p)
static void energy (double *o, particle_template *p)
static void charge (double *o, particle_template *p)
static void is_lepton (int *o, particle_template *p)
static void is_bquark (int *o, particle_template *p)
static void is_neutrino (int *o, particle_template *p)
Function Documentation
charge()
static void charge (double * o, particle_template * p) static
Definition at line 47 of file bsm_4tops/include/bsm_4tops/node_features.h.
References charge, and is_lep.
energy()
static void energy (double * o, particle_template * p) static
Definition at line 46 of file bsm_4tops/include/bsm_4tops/node_features.h.
eta()
static void eta (double * o, particle_template * p) static
Definition at line 44 of file bsm_4tops/include/bsm_4tops/node_features.h.
References eta.
is_bquark()
static void is_bquark (int * o, particle_template * p) static
Definition at line 50 of file bsm_4tops/include/bsm_4tops/node_features.h.
References is_b.
Referenced by graph_children::CompileEvent(), graph_truthjets::CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), and graph_detector::CompileEvent().
is_lepton()
static void is_lepton (int * o, particle_template * p) static
Definition at line 49 of file bsm_4tops/include/bsm_4tops/node_features.h.
References is_lep, and is_nu.
Referenced by graph_children::CompileEvent(), graph_truthjets::CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), graph_detector::CompileEvent(), parton::strategy(), and topmatching::strategy().
is_neutrino()
static void is_neutrino (int * o, particle_template * p) static
Definition at line 51 of file bsm_4tops/include/bsm_4tops/node_features.h.
References is_nu.
Referenced by graph_children::CompileEvent(), and graph_truthjets::CompileEvent().
phi()
static void phi (double * o, particle_template * p) static
Definition at line 45 of file bsm_4tops/include/bsm_4tops/node_features.h.
References phi.
pt()
static void pt (double * o, particle_template * p) static
Definition at line 43 of file bsm_4tops/include/bsm_4tops/node_features.h.
References pt.
res_node()
static void res_node (int * o, particle_template * p) static
Definition at line 5 of file bsm_4tops/include/bsm_4tops/node_features.h.
Referenced by graph_tops::CompileEvent(), graph_children::CompileEvent(), graph_truthjets::CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), and graph_detector::CompileEvent().
top_node()
static void top_node (int * o, particle_template * p) static
Definition at line 14 of file bsm_4tops/include/bsm_4tops/node_features.h.
References index.
Referenced by graph_tops::CompileEvent(), graph_children::CompileEvent(), graph_truthjets::CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), and graph_detector::CompileEvent().