AnalysisG: matching Class Reference
matching Class Reference
#include <matching.h>
Public Member Functions
matching ()
~matching ()
selection_template * clone () override
Creates a clone of this selection.
void reference (event_template *ev)
void experimental (event_template *ev)
void current (event_template *ev)
void dump (object_data_t *data, std::vector< particle_template * > *obj, bool is_lepx, bool is_tru, int *num_jets=nullptr, std::vector< int > *num_merged=nullptr)
bool match_obj (std::vector< particle_template * > *vx, std::vector< particle_template * > *out, std::string hash_, std::vector< int > *num_merged, int *num_jets, bool exl_lep)
std::vector< int > get_pdgid (std::vector< particle_template * > *prt)
bool strategy (event_template *ev) override
Alternative selection strategy method.
void merge (selection_template *sl) override
Merges results from another selection.
virtual bool selection (event_template *ev)
The main selection method to override.
virtual void bulk_write (const long *idx, std::string *hx)
Bulk write operation for indices and hashes.
virtual void write (std::vector< particle_template * > *particles, std::string name, particle_enum attrs)
Writes a particle collection to output.
template<typename g >
void write (g *var, std::string name)
Template method to write a variable to output.
template<typename g >
void write (g var, std::string name)
Template method to write a value to output.
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< std::vector< double > > *data)
Switch board for dispatching particle attributes.
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< int > *data)
Switch board overload for integer data.
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< double > *data)
Switch board overload for double data.
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< bool > *data)
Switch board overload for boolean data.
std::vector< std::map< std::string, float > > reverse_hash (std::vector< std::string > *hashes)
Reverses hash strings to their original weight maps.
bool CompileEvent ()
Compiles the event for this selection.
selection_template * build (event_template *ev)
Builds the selection from an event.
bool operator== (selection_template &p)
Equality comparison operator.
template<typename g , typename k >
void sum (std::vector< g * > *ch, k **out)
Sums particles into a combined particle.
template<typename g >
g * sum (std::map< std::string, g * > *ch)
Sums particles from a map and returns the combined particle.
template<typename g >
float sum (std::vector< g * > *ch)
Sums particles and returns the invariant mass in GeV.
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
template<typename g >
void safe_delete (std::vector< g * > *particles)
Safely deletes particles not marked for preservation.
template<typename g >
std::vector< g * > vectorize (std::map< std::string, g * > *in)
Converts a map to a vector.
template<typename g >
std::vector< g * > make_unique (std::vector< g * > *inpt)
Removes duplicate particles based on hash.
template<typename g >
void downcast (std::vector< g * > *inpt, std::vector< particle_template * > *out)
Downcasts particles to base particle_template type.
template<typename o , typename g >
void upcast (std::map< std::string, o * > *inpt, std::vector< g * > *out)
Upcasts particles from a map to a derived type.
template<typename o , typename g >
void upcast (std::vector< o * > *inpt, std::vector< g * > *out)
Upcasts particles from a vector to a derived type.
template<typename g >
void get_leptonics (std::map< std::string, g * > inpt, std::vector< particle_template * > *out)
Extracts leptonic particles (leptons and neutrinos) from a map.
template<typename g , typename j >
bool contains (std::vector< g * > *inpt, j *pcheck)
Checks if a particle is contained in a vector.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
Static Public Member Functions
static void set_name (std::string *, selection_template *)
Setter for name.
static void get_name (std::string *, selection_template *)
Getter for name.
static void set_hash (std::string *, selection_template *)
Setter for hash.
static void get_hash (std::string *, selection_template *)
Getter for hash.
static void get_tree (std::string *, selection_template *)
Getter for tree.
static void set_weight (double *, selection_template *)
Setter for weight.
static void get_weight (double *, selection_template *)
Getter for weight.
static void set_index (long *, selection_template *)
Setter for index.
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Public Attributes
double energy_constraint = -1
buffer_t data
cproperty< std::string, selection_template > name
Selection name property.
cproperty< std::string, selection_template > hash
Unique hash identifier.
cproperty< std::string, selection_template > tree
Source tree name.
cproperty< double, selection_template > weight
Event weight.
cproperty< long, selection_template > index
Event index.
meta * meta_data = nullptr
Pointer to metadata.
std::string filename = ""
Associated filename.
int threadIdx = -1
Thread index for parallel processing.
std::map< std::string, std::map< std::string, float > > passed_weights = {}
Weights for passed events.
std::map< std::string, meta_t > matched_meta = {}
Matched metadata.
Private Member Functions
void bulk_write_out ()
void merger (selection_template *sl2)
Private Attributes
friend container
std::unordered_map< long, std::string > sequence
bool p_bulk_write = true
write_t * handle = nullptr
event_template * m_event = nullptr
std::map< std::string, std::vector< particle_template * > > garbage = {}
Garbage collection for created particles.
Detailed Description
Definition at line 29 of file matching.h.
Constructor & Destructor Documentation
matching()
matching::matching ()
Definition at line 3 of file matching.cxx.
Referenced by clone().
~matching()
matching::~matching ()
Definition at line 9 of file matching.cxx.
Member Function Documentation
absolute_path()
std::string tools::absolute_path (std::string path) static inherited
Converts a relative path to an absolute path.
Parameters
path The path to convert.
Returns
The absolute version of the path.
Definition at line 49 of file tools/cxx/io.cxx.
Referenced by analysis::analysis(), analysis::build_events(), io::check_root_file_paths(), and io::trigger_pcm().
build()
selection_template * selection_template::build (event_template * ev) inherited
Builds the selection from an event.
Parameters
ev Pointer to the event.
Returns
Pointer to the built selection.
Definition at line 47 of file selection_core.cxx.
References selection_template::clone(), selection_template::data, selection_template::filename, selection_template::m_event, selection_template::name, and selection_template::weight.
bulk_write()
void selection_template::bulk_write (const long * idx, std::string * hx) virtual inherited
Bulk write operation for indices and hashes.
Parameters
idx Pointer to the event index.
hx Pointer to the hash string.
Definition at line 8 of file selection_template.cxx.
References selection_template::p_bulk_write.
Referenced by selection_template::bulk_write_out().
bulk_write_out()
void selection_template::bulk_write_out () private inherited
Definition at line 58 of file selection_core.cxx.
References selection_template::bulk_write(), selection_template::handle, selection_template::p_bulk_write, selection_template::sequence, and selection_template::write().
clone()
selection_template * matching::clone () override virtual
Creates a clone of this selection.
Returns
Pointer to the cloned selection.
Reimplemented from selection_template.
Definition at line 4 of file matching.cxx.
References matching(), and energy_constraint.
CompileEvent()
bool selection_template::CompileEvent () inherited
Compiles the event for this selection.
Returns
True if compilation succeeded.
Definition at line 41 of file selection_core.cxx.
References selection_template::m_event, selection_template::selection(), and selection_template::strategy().
contains()
template<typename g , typename j > bool selection_template::contains (std::vector< g * > * inpt, j * pcheck) inline inherited
Checks if a particle is contained in a vector.
Template Parameters
g The particle type in the vector.
j The particle type to check.
Parameters
inpt Pointer to the vector to search.
pcheck Pointer to the particle to find.
Returns
True if the particle is found.
Definition at line 379 of file selection_template.h.
References selection_template::hash.
Referenced by topjets::strategy(), and toptruthjets::strategy().
create_path()
void tools::create_path (std::string path) static inherited
Creates a directory path, including parent directories if needed.
Parameters
path The directory path to create.
Definition at line 6 of file tools/cxx/io.cxx.
References f, and tools::split().
Referenced by analysis::analysis(), analysis::build_inference(), plotting::build_path(), analysis::build_project(), container::compile(), metrics::dump_mass_plots(), metric_template::execute(), metrics::generic_painter(), analysis::start(), io::start(), and io::trigger_pcm().
current()
void matching::current (event_template * ev)
Definition at line 4 of file mc20_ref.cxx.
References c, data, dump(), selection_template::hash, is_lep, is_nu, mass, object_data_t::mass, merge_data(), object_data_t::num_htop, num_jets(), object_data_t::num_ltop, object_data_t::num_tops, buffer_t::top_children, buffer_t::top_jets_children, buffer_t::top_jets_leptons, buffer_t::top_partons, buffer_t::top_truthjets, and selection_template::vectorize().
Referenced by strategy().
delete_path()
void tools::delete_path (std::string path) static inherited
Deletes a directory path and its contents.
Parameters
path The directory path to delete.
Definition at line 22 of file tools/cxx/io.cxx.
downcast()
template<typename g > void selection_template::downcast (std::vector< g * > * inpt, std::vector< particle_template * > * out) inline inherited
Downcasts particles to base particle_template type.
Template Parameters
g The derived particle type.
Parameters
inpt Pointer to input vector of derived particles.
out Pointer to output vector of base particles.
Definition at line 326 of file selection_template.h.
Referenced by topjets::strategy(), toptruthjets::strategy(), and zprime::strategy().
dump()
void matching::dump (object_data_t * data, std::vector< particle_template * > * obj, bool is_lepx, bool is_tru, int * num_jets = nullptr, std::vector< int > * num_merged = nullptr)
Definition at line 76 of file matching.cxx.
References get_pdgid(), mass, num_jets(), num_tops(), pdgid, and selection_template::sum().
Referenced by current(), experimental(), and reference().
ends_with()
bool tools::ends_with (std::string * inpt, std::string val) static inherited
Checks if a string ends with a specific substring.
Parameters
inpt Pointer to the string to check.
val The substring to check for at the end.
Returns
True if the string ends with the substring, false otherwise.
Definition at line 71 of file strings.cxx.
References l.
Referenced by plotting::build_path(), io::check_root_file_paths(), dataloader::dump_graphs(), tools::ls(), meta::parse_json(), io::scan_keys(), and analysis::start().
experimental()
void matching::experimental (event_template * ev)
Definition at line 4 of file mc20_exp.cxx.
References data, dump(), selection_template::hash, is_lep, is_nu, mass, object_data_t::mass, match_obj(), merge_data(), object_data_t::num_htop, num_jets(), object_data_t::num_ltop, object_data_t::num_tops, buffer_t::top_children, buffer_t::top_jets_children, buffer_t::top_jets_leptons, buffer_t::top_partons, buffer_t::top_truthjets, and selection_template::vectorize().
Referenced by strategy().
extract()
template<typename C , typename T > static void tools::extract (std::vector< T > * prop, std::vector< C * > * src, void(*)(T *, C *) get_prop) inline static inherited
Extracts a specific property from a vector of objects into a new vector.
Template Parameters
C The type of objects in the source vector.
T The type of the property to extract.
Parameters
prop Pointer to the output vector to fill with property values.
src Pointer to the source vector of objects.
get_prop Function pointer to extract the property from an object.
< Clear the properties vector.
< Reserve space for the property values.
< Loop through each object in the source vector.
< Create a default-initialized property variable.
< Call the provided function to extract the property.
< Add the property value to the output vector.
Definition at line 216 of file tools.h.
flush()
template<typename T > static void tools::flush (std::vector< T * > * inpt) inline static inherited
Empties a vector and all objects it points to.
Template Parameters
T The type of pointers in the vector.
Parameters
inpt Pointer to the vector to empty.
< Loop through all elements in the vector.
< Delete the object the pointer points to.
< Set the pointer to nullptr to avoid dangling pointers.
< Clear the vector.
Definition at line 167 of file tools.h.
Referenced by analysis::~analysis(), dataloader::~dataloader(), sampletracer::compile_objects(), and io::root_end().
get_hash()
void selection_template::get_hash (std::string * val, selection_template * ev) static inherited
Getter for hash.
Definition at line 18 of file selection/cxx/properties.cxx.
References selection_template::data, and event_t::hash.
Referenced by selection_template::selection_template().
get_leptonics()
template<typename g > void selection_template::get_leptonics (std::map< std::string, g * > inpt, std::vector< particle_template * > * out) inline inherited
Extracts leptonic particles (leptons and neutrinos) from a map.
Template Parameters
g The particle type.
Parameters
inpt Input map of particles.
out Pointer to output vector.
Definition at line 362 of file selection_template.h.
References is_lep, and is_nu.
Referenced by topjets::strategy(), and toptruthjets::strategy().
get_name()
void selection_template::get_name (std::string * name, selection_template * ev) static inherited
Getter for name.
Definition at line 7 of file selection/cxx/properties.cxx.
References selection_template::data, and event_t::name.
Referenced by selection_template::selection_template().
get_pdgid()
std::vector< int > matching::get_pdgid (std::vector< particle_template * > * prt)
Definition at line 146 of file matching.cxx.
References pdgid.
Referenced by dump().
get_tree()
void selection_template::get_tree (std::string * name, selection_template * ev) static inherited
Getter for tree.
Definition at line 22 of file selection/cxx/properties.cxx.
References selection_template::data, and event_t::tree.
Referenced by selection_template::selection_template().
get_weight()
void selection_template::get_weight (double * inpt, selection_template * ev) static inherited
Getter for weight.
Definition at line 30 of file selection/cxx/properties.cxx.
References selection_template::data, and event_t::weight.
Referenced by selection_template::selection_template().
has_string()
bool tools::has_string (std::string * inpt, std::string trg) static inherited
Checks if a string contains a specific substring.
Parameters
inpt Pointer to the string to check.
trg The substring to search for.
Returns
True if the substring is found, false otherwise.
Definition at line 65 of file strings.cxx.
References f.
Referenced by analysis::check_cache(), meta::compiler(), metrics::generic_painter(), dataloader::restore_graphs_(), meta::scan_sow(), model_template::set_device(), and metric_template::set_run_name().
has_value()
bool tools::has_value (std::vector< std::string > * data, std::string trg) static inherited
Checks if a vector of strings contains a specific string.
Parameters
data Pointer to the vector to search.
trg The string to search for.
Returns
True if the string is found in the vector, false otherwise.
Definition at line 77 of file strings.cxx.
Referenced by io::scan_keys().
is_file()
bool tools::is_file (std::string path) static inherited
Checks if a path refers to an existing file.
Parameters
path The path to check.
Returns
True if the path is a file and exists, false otherwise.
Definition at line 30 of file tools/cxx/io.cxx.
Referenced by io::check_root_file_paths(), analysis::initialize_loop(), metric_template::set_run_name(), and io::start().
ls()
std::vector< std::string > tools::ls (std::string path, std::string ext = "") static inherited
Lists files in a directory, optionally filtered by extension.
Parameters
path The directory to search.
ext File extension filter. If empty, all files are listed.
Returns
A vector of filenames in the directory.
Definition at line 35 of file tools/cxx/io.cxx.
References tools::ends_with(), and tools::split().
Referenced by analysis::analysis(), analysis::check_cache(), io::check_root_file_paths(), dataloader::restore_graphs(), and io::trigger_pcm().
make_unique()
template<typename g > std::vector< g * > selection_template::make_unique (std::vector< g * > * inpt) inline inherited
Removes duplicate particles based on hash.
Template Parameters
g The particle type.
Parameters
inpt Pointer to input vector.
Returns
Vector with duplicates removed.
Definition at line 306 of file selection_template.h.
References selection_template::hash.
Referenced by combinatorial::reconstruction(), parton::strategy(), topjets::strategy(), toptruthjets::strategy(), and parton::top_mass_contribution().
match_obj()
bool matching::match_obj (std::vector< particle_template * > * vx, std::vector< particle_template * > * out, std::string hash_, std::vector< int > * num_merged, int * num_jets, bool exl_lep)
Definition at line 100 of file matching.cxx.
References energy_constraint, selection_template::hash, is_lep, num_jets(), tools::sum(), and selection_template::vectorize().
Referenced by experimental().
merge()
void matching::merge (selection_template * sel) override virtual
Merges results from another selection.
Parameters
sel Pointer to the selection to merge from.
Reimplemented from selection_template.
Definition at line 11 of file matching.cxx.
References data, object_data_t::is_hadronic, object_data_t::is_leptonic, object_data_t::mass, object_data_t::merged, object_data_t::num_false, object_data_t::num_htop, object_data_t::num_jets, object_data_t::num_ltop, object_data_t::num_tops, object_data_t::pdgid, buffer_t::top_children, buffer_t::top_jets_children, buffer_t::top_jets_leptons, buffer_t::top_partons, buffer_t::top_truthjets, selection_template::write(), and object_data_t::wrong_matched.
merger()
void selection_template::merger (selection_template * sl2) private inherited
Definition at line 67 of file selection_core.cxx.
References selection_template::filename, selection_template::hash, selection_template::index, selection_template::m_event, selection_template::matched_meta, selection_template::merge(), merge_data(), selection_template::meta_data, selection_template::p_bulk_write, selection_template::passed_weights, selection_template::sequence, selection_template::weight, and selection_template::write().
operator==()
bool selection_template::operator== (selection_template & p) inherited
Equality comparison operator.
Parameters
p The selection to compare against.
Returns
True if selections are equal.
Definition at line 38 of file selection_core.cxx.
References selection_template::hash.
put()
template<typename g > static void tools::put (std::vector< g * > * out, std::vector< g * > * src, std::vector< int > * trg) inline static inherited
Fills a vector with pointers from another vector based on a selection index.
Template Parameters
g The type of objects being pointed to.
Parameters
out Pointer to the output vector to fill.
src Pointer to the source vector to select from.
trg Pointer to a vector of indices for selection.
< Clear the output vector.
< Reserve space for the output elements.
< Loop through each selected index.
< Get the object at the selected index.
< Add it to the output vector.
< Mark the object as in use.
Definition at line 197 of file tools.h.
Referenced by dataloader::get_k_train_set(), dataloader::get_k_validation_set(), and dataloader::get_test_set().
reference()
void matching::reference (event_template * ev)
Definition at line 4 of file mc16_ref.cxx.
References c, data, dump(), selection_template::hash, is_lep, is_nu, mass, object_data_t::mass, merge_data(), object_data_t::num_htop, num_jets(), object_data_t::num_ltop, object_data_t::num_tops, buffer_t::top_children, buffer_t::top_jets_children, buffer_t::top_jets_leptons, buffer_t::top_partons, buffer_t::top_truthjets, and selection_template::vectorize().
Referenced by strategy().
rename()
void tools::rename (std::string start, std::string target) static inherited
Renames a file or directory.
Parameters
start The original path.
target The new path.
Definition at line 18 of file tools/cxx/io.cxx.
Referenced by dataloader::dump_graphs().
replace()
void tools::replace (std::string * in, std::string repl_str, std::string repl_with) static inherited
Replaces all occurrences of a substring in a string.
Parameters
in Pointer to the string to modify.
repl_str The substring to replace.
repl_with The replacement string.
Definition at line 5 of file strings.cxx.
Referenced by analysis::build_graphs(), analysis::check_cache(), dataloader::dump_graphs(), meta::get_campaign(), meta::parse_json(), and analysis::start().
reverse_hash()
std::vector< std::map< std::string, float > > selection_template::reverse_hash (std::vector< std::string > * hashes) inherited
Reverses hash strings to their original weight maps.
Parameters
hashes Pointer to vector of hash strings.
Returns
Vector of weight maps.
Definition at line 84 of file selection_core.cxx.
References selection_template::hash, and selection_template::passed_weights.
safe_delete()
template<typename g > void selection_template::safe_delete (std::vector< g * > * particles) inline inherited
Safely deletes particles not marked for preservation.
Template Parameters
g The particle type.
Parameters
particles Pointer to vector of particles.
Definition at line 250 of file selection_template.h.
Referenced by combinatorial::~combinatorial(), and validation::~validation().
selection()
bool selection_template::selection (event_template * ev) virtual inherited
The main selection method to override.
Parameters
ev Pointer to the event to evaluate.
Returns
True if the event passes the selection, false otherwise.
Reimplemented in regions, met, childrenkinematics, decaymodes, event, parton, topjets, topkinematics, topmatching, toptruthjets, zprime, topkinematics, topmatching, zprime, combinatorial, validation, and topefficiency.
Definition at line 4 of file selection_template.cxx.
Referenced by selection_template::CompileEvent().
set_hash()
void selection_template::set_hash (std::string * path, selection_template * ev) static inherited
Setter for hash.
Definition at line 11 of file selection/cxx/properties.cxx.
References selection_template::data, event_t::hash, selection_template::index, and tools::to_string().
Referenced by selection_template::selection_template().
set_index()
void selection_template::set_index (long * inpt, selection_template * ev) static inherited
Setter for index.
Definition at line 34 of file selection/cxx/properties.cxx.
References selection_template::data, and event_t::index.
Referenced by selection_template::selection_template().
set_name()
void selection_template::set_name (std::string * name, selection_template * ev) static inherited
Setter for name.
Definition at line 3 of file selection/cxx/properties.cxx.
References selection_template::data, selection_template::name, and event_t::name.
Referenced by selection_template::selection_template().
set_weight()
void selection_template::set_weight (double * inpt, selection_template * ev) static inherited
Setter for weight.
Definition at line 26 of file selection/cxx/properties.cxx.
References selection_template::data, and event_t::weight.
Referenced by selection_template::selection_template().
split()
std::vector< std::string > tools::split (std::string inpt, std::string del) inherited
Splits a string into a vector of substrings based on a delimiter.
Parameters
inpt The input string to split.
del The delimiter.
Returns
A vector of substrings.
Definition at line 23 of file strings.cxx.
References index.
Referenced by analysis::build_events(), analysis::build_graphs(), analysis::build_inference(), event_template::build_mapping(), analysis::check_cache(), container::compile(), sampletracer::compile_objects(), meta::compiler(), tools::create_path(), dataloader::dump_graphs(), meta::hash(), tools::ls(), graph_t::meta_deserialize(), dataloader::restore_graphs_(), io::root_begin(), model_template::set_device(), metric_template::set_run_name(), metric_template::set_variables(), and analysis::start().
strategy()
bool matching::strategy (event_template * ev) override virtual
Alternative selection strategy method.
Parameters
ev Pointer to the event to evaluate.
Returns
True if the event passes, false otherwise.
Reimplemented from selection_template.
Definition at line 153 of file matching.cxx.
References current(), experimental(), selection_template::name, and reference().
sum() [1/4]
template<typename g > g * selection_template::sum (std::map< std::string, g * > * ch) inline inherited
Sums particles from a map and returns the combined particle.
Template Parameters
g The particle type.
Parameters
ch Pointer to map of particles.
Returns
Pointer to the summed particle.
Definition at line 265 of file selection_template.h.
References selection_template::sum(), and selection_template::vectorize().
sum() [2/4]
template<typename g > float selection_template::sum (std::vector< g * > * ch) inline inherited
Sums particles and returns the invariant mass in GeV.
Template Parameters
g The particle type.
Parameters
ch Pointer to vector of particles.
Returns
Invariant mass of the combined system in GeV.
Definition at line 279 of file selection_template.h.
References mass, and selection_template::sum().
sum() [3/4]
template<typename g , typename k > void selection_template::sum (std::vector< g * > * ch, k ** out) inline inherited
Sums particles into a combined particle.
Template Parameters
g Input particle type.
k Output particle type.
Parameters
ch Pointer to vector of particles to sum.
out Pointer to output particle pointer.
Definition at line 230 of file selection_template.h.
References selection_template::garbage, and selection_template::hash.
Referenced by dump(), validation::reconstruction(), childrenkinematics::strategy(), decaymodes::strategy(), parton::strategy(), topjets::strategy(), topmatching::strategy(), toptruthjets::strategy(), zprime::strategy(), selection_template::sum(), selection_template::sum(), and parton::top_mass_contribution().
sum() [4/4]
template<typename g > g tools::sum (std::vector< g > * inpt) inline inherited
Sums the elements of a vector.
Template Parameters
g The type of elements in the vector.
Parameters
inpt Pointer to the vector to sum.
Returns
The sum of all elements.
< Initialize the output variable.
< Return the sum.
Definition at line 183 of file tools.h.
Referenced by metrics::add_th1f_accuracy(), sampletracer::compile_objects(), particle_template::DeltaR(), graph_template::double_neutrino(), grift::forward(), recursivegraphneuralnetwork::forward(), match_obj(), and grift::message().
switch_board() [1/4]
void selection_template::switch_board (particle_enum attrs, particle_template * ptr, std::vector< bool > * data) inherited
Switch board overload for boolean data.
Definition at line 122 of file selection_core.cxx.
References selection_template::data, is_add, is_b, is_lep, and is_nu.
switch_board() [2/4]
void selection_template::switch_board (particle_enum attrs, particle_template * ptr, std::vector< double > * data) inherited
Switch board overload for double data.
Definition at line 107 of file selection_core.cxx.
References charge, selection_template::data, energy, eta, mass, phi, pt, px, py, and pz.
switch_board() [3/4]
void selection_template::switch_board (particle_enum attrs, particle_template * ptr, std::vector< int > * data) inherited
Switch board overload for integer data.
Definition at line 99 of file selection_core.cxx.
References selection_template::data, selection_template::index, index, and pdgid.
switch_board() [4/4]
void selection_template::switch_board (particle_enum attrs, particle_template * ptr, std::vector< std::vector< double > > * data) inherited
Switch board for dispatching particle attributes.
Parameters
attrs The attribute type to extract.
ptr Pointer to the particle.
data Output vector for 2D double data.
Definition at line 132 of file selection_core.cxx.
References selection_template::data, energy, eta, phi, pmc, pmu, pt, px, py, pz, and selection_template::switch_board().
Referenced by selection_template::switch_board(), and selection_template::write().
to_string() [1/2]
std::string tools::to_string (double val) static inherited
Converts a double value to a string with standard precision.
Parameters
val The double value to convert.
Returns
The string representation of the value.
Definition at line 59 of file strings.cxx.
Referenced by dataloader::generate_kfold_set(), dataloader::generate_test_set(), particle_template::get_hash(), topefficiency::region(), dataloader::restore_dataset(), event_template::set_hash(), selection_template::set_hash(), parton::strategy(), topjets::strategy(), toptruthjets::strategy(), and parton::top_mass_contribution().
to_string() [2/2]
std::string tools::to_string (double val, int prec) static inherited
Converts a double value to a string with specified precision.
Parameters
val The double value to convert.
prec The number of decimal places to consider.
Returns
The string representation of the value.
Definition at line 91 of file strings.cxx.
trim()
std::string tools::trim (std::string s) inherited
Removes whitespace from the beginning and end of a string.
Parameters
s The string to trim.
Returns
The trimmed string.
type_name()
template<typename T > std::string tools::type_name () inline inherited
Gets the type name of a variable as a string (for debugging).
Template Parameters
T The type to get the name of.
Returns
The name of the type as a string.
< Gets the type name via RTTI.
< Returns the type name.
Definition at line 155 of file tools.h.
Referenced by event_template::build_mapping().
upcast() [1/2]
template<typename o , typename g > void selection_template::upcast (std::map< std::string, o * > * inpt, std::vector< g * > * out) inline inherited
Upcasts particles from a map to a derived type.
Template Parameters
o The source particle type.
g The target particle type.
Parameters
inpt Pointer to input map.
out Pointer to output vector.
Definition at line 338 of file selection_template.h.
Referenced by regions::strategy(), parton::strategy(), and parton::top_mass_contribution().
upcast() [2/2]
template<typename o , typename g > void selection_template::upcast (std::vector< o * > * inpt, std::vector< g * > * out) inline inherited
Upcasts particles from a vector to a derived type.
Template Parameters
o The source particle type.
g The target particle type.
Parameters
inpt Pointer to input vector.
out Pointer to output vector.
Definition at line 351 of file selection_template.h.
vectorize()
template<typename g > std::vector< g * > selection_template::vectorize (std::map< std::string, g * > * in) inline inherited
Converts a map to a vector.
Template Parameters
g The value type in the map.
Parameters
in Pointer to the input map.
Returns
Vector of values from the map.
Definition at line 292 of file selection_template.h.
Referenced by current(), experimental(), match_obj(), reference(), childrenkinematics::strategy(), decaymodes::strategy(), topjets::strategy(), toptruthjets::strategy(), zprime::strategy(), combinatorial::strategy(), validation::strategy(), selection_template::sum(), combinatorial::upcast(), and validation::upcast().
write() [1/3]
template<typename g > void selection_template::write (g * var, std::string name) inline inherited
Template method to write a variable to output.
Template Parameters
g The type of variable to write.
Parameters
var Pointer to the variable.
name Name for this variable in output.
Definition at line 174 of file selection_template.h.
References selection_template::handle, and selection_template::tree.
write() [2/3]
template<typename g > void selection_template::write (g var, std::string name) inline inherited
Template method to write a value to output.
Template Parameters
g The type of value to write.
Parameters
var The value to write.
name Name for this variable in output.
Definition at line 186 of file selection_template.h.
References selection_template::handle, and selection_template::tree.
write() [3/3]
void selection_template::write (std::vector< particle_template * > * particles, std::string name, particle_enum attrs) virtual inherited
Writes a particle collection to output.
Parameters
particles Pointer to vector of particles to write.
name Name for this collection in output.
attrs Particle attributes to write.
Definition at line 10 of file selection_template.cxx.
References charge, energy, eta, index, is_add, is_b, is_lep, is_nu, mass, pdgid, phi, pmc, pmu, pt, px, py, pz, selection_template::switch_board(), undef, v_b, v_d, v_i, vv_d, and selection_template::write().
Referenced by selection_template::bulk_write_out(), regions::merge(), childrenkinematics::merge(), topkinematics::merge(), topmatching::merge(), zprime::merge(), merge(), combinatorial::merge(), validation::merge(), selection_template::merger(), met::strategy(), and selection_template::write().
Member Data Documentation
container
friend selection_template::container private inherited
Definition at line 392 of file selection_template.h.
data
buffer_t matching::data
Definition at line 54 of file matching.h.
Referenced by current(), experimental(), merge(), and reference().
energy_constraint
double matching::energy_constraint = -1
Definition at line 52 of file matching.h.
Referenced by clone(), and match_obj().
filename
std::string selection_template::filename = "" inherited
Associated filename.
Definition at line 219 of file selection_template.h.
Referenced by selection_template::build(), and selection_template::merger().
garbage
std::map<std::string, std::vector<particle_template*> > selection_template::garbage = {} private inherited
Garbage collection for created particles.
Definition at line 402 of file selection_template.h.
Referenced by selection_template::~selection_template(), and selection_template::sum().
handle
write_t* selection_template::handle = nullptr private inherited
Definition at line 400 of file selection_template.h.
Referenced by selection_template::bulk_write_out(), selection_template::write(), and selection_template::write().
hash
cproperty<std::string, selection_template> selection_template::hash inherited
Unique hash identifier.
Definition at line 89 of file selection_template.h.
Referenced by selection_template::selection_template(), selection_template::contains(), current(), experimental(), selection_template::make_unique(), match_obj(), selection_template::merger(), selection_template::operator==(), combinatorial::reconstruction(), reference(), selection_template::reverse_hash(), met::strategy(), topjets::strategy(), topmatching::strategy(), toptruthjets::strategy(), combinatorial::strategy(), validation::strategy(), topefficiency::strategy(), and selection_template::sum().
index
cproperty<long, selection_template> selection_template::index inherited
Event index.
Definition at line 100 of file selection_template.h.
Referenced by selection_template::selection_template(), selection_template::merger(), selection_template::set_hash(), and selection_template::switch_board().
m_event
event_template* selection_template::m_event = nullptr private inherited
Definition at line 401 of file selection_template.h.
Referenced by selection_template::build(), selection_template::CompileEvent(), and selection_template::merger().
matched_meta
std::map<std::string, meta_t> selection_template::matched_meta = {} inherited
Matched metadata.
Definition at line 389 of file selection_template.h.
Referenced by selection_template::merger().
meta_data
meta* selection_template::meta_data = nullptr inherited
Pointer to metadata.
Definition at line 218 of file selection_template.h.
Referenced by selection_template::merger(), and regions::strategy().
name
cproperty<std::string, selection_template> selection_template::name inherited
Selection name property.
Definition at line 85 of file selection_template.h.
Referenced by selection_template::build(), combinatorial::build_packet(), validation::build_packet(), regions::merge(), selection_template::set_name(), and strategy().
p_bulk_write
bool selection_template::p_bulk_write = true private inherited
Definition at line 398 of file selection_template.h.
Referenced by selection_template::bulk_write(), selection_template::bulk_write_out(), and selection_template::merger().
passed_weights
std::map<std::string, std::map<std::string, float> > selection_template::passed_weights = {} inherited
Weights for passed events.
Definition at line 388 of file selection_template.h.
Referenced by selection_template::merger(), and selection_template::reverse_hash().
sequence
std::unordered_map<long, std::string> selection_template::sequence private inherited
Definition at line 397 of file selection_template.h.
Referenced by selection_template::bulk_write_out(), and selection_template::merger().
threadIdx
int selection_template::threadIdx = -1 inherited
Thread index for parallel processing.
Definition at line 387 of file selection_template.h.
Referenced by combinatorial::build_packet(), and validation::build_packet().
tree
cproperty<std::string, selection_template> selection_template::tree inherited
Source tree name.
Definition at line 93 of file selection_template.h.
Referenced by selection_template::selection_template(), selection_template::write(), and selection_template::write().
weight
cproperty<double, selection_template> selection_template::weight inherited
Event weight.
Definition at line 96 of file selection_template.h.
Referenced by selection_template::selection_template(), selection_template::build(), regions::merge(), and selection_template::merger().
The documentation for this class was generated from the following files:
matching.h
matching.cxx
mc16_ref.cxx
mc20_exp.cxx
mc20_ref.cxx