AnalysisG: accuracy_metric Class Reference
accuracy_metric Class Reference
#include <accuracy.h>
Public Member Functions
accuracy_metric ()
~accuracy_metric () override
accuracy_metric * clone () override
void define_metric (metric_t *mtx) override
void define_variables () override
void event () override
void batch () override
void end () override
Public Member Functions inherited from metric_template
metric_template ()
virtual ~metric_template ()
template<typename T >
void register_output (std::string tree, std::string name, T *t)
template<typename T >
void write (std::string tree, std::string name, T *t, bool fill=false)
Public Member Functions inherited from tools
tools ()
Constructor for the tools class.
~tools ()
Destructor for the tools class.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Public Member Functions inherited from notification
notification ()
Constructor for the notification class.
~notification ()
Destructor for the notification class.
void set_prefix (std::string prefix)
Sets the prefix used in log messages from this instance.
std::string get_prefix ()
Returns the prefix currently used in log messages.
void Info (std::string msg, bool newline=true)
Outputs an info message.
void Warning (std::string msg, bool newline=true)
Outputs a warning message.
void Error (std::string msg, bool newline=true)
Outputs an error message.
void Debug (std::string msg, bool newline=true)
Outputs a debug message (only in debug mode).
void Message (std::string msg, std::string tag="", bool newline=true)
Outputs a message with custom formatting.
void set_debug_mode (bool dbg)
Enables or disables debug mode.
bool get_debug_mode ()
Returns the current status of debug mode.
void set_suppress_warning (bool sw)
Sets whether warnings should be suppressed.
bool get_suppress_warning ()
Returns the current warning suppression status.
void set_suppress_info (bool si)
Sets whether info messages should be suppressed.
bool get_suppress_info ()
Returns the current info message suppression status.
Additional Inherited Members
Static Public Member Functions inherited from tools
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Public Attributes inherited from metric_template
cproperty< std::string, metric_template > name
cproperty< std::map< std::string, std::string >, metric_template > run_names
cproperty< std::vector< std::string >, metric_template > variables
meta * meta_data = nullptr
Protected Attributes inherited from notification
std::string prefix = ""
Prefix used in log messages from this instance. Initialized as empty string.
bool debug_mode = false
Flag indicating whether debug mode is enabled. Initialized as false.
bool suppress_warnings = false
Flag indicating whether warnings are suppressed. Initialized as false.
bool suppress_info = false
Flag indicating whether info messages are suppressed. Initialized as false.
Detailed Description
Definition at line 6 of file accuracy.h.
Constructor & Destructor Documentation
accuracy_metric()
accuracy_metric::accuracy_metric ()
Definition at line 5 of file accuracy.cxx.
 {this -> name = "accuracy";}
References metric_template::name.
Referenced by clone().
~accuracy_metric()
accuracy_metric::~accuracy_metric () override
Definition at line 3 of file accuracy.cxx.
 {}
Member Function Documentation
batch()
void accuracy_metric::batch () override virtual
Reimplemented from metric_template.
Definition at line 35 of file accuracy.cxx.
 {}
clone()
accuracy_metric * accuracy_metric::clone () override virtual
Reimplemented from metric_template.
Definition at line 4 of file accuracy.cxx.
 {return new accuracy_metric();}
References accuracy_metric().
define_metric()
void accuracy_metric::define_metric (metric_t * mtx) override virtual
Reimplemented from metric_template.
Definition at line 53 of file accuracy.cxx.
{
     auto acc  =[](std::map<int, int>* acx){return float((*acx)[1]) / float((*acx)[0] + (*acx)[1]);};
     auto maxv =[](std::vector<float>* acx) -> int {
         int idx = 0;
         float v = acx -> at(0);
         for (size_t x(0); x < acx -> size(); ++x){
             if (acx -> at(x) < v){continue;}
             v = acx -> at(x); idx = x;
         }
         return idx;
     };
     std::vector<long> batch_idx             = mtx -> get<std::vector<long>>( graph_enum::batch_index, "index");
     std::vector<std::vector<int>> edge_idx  = mtx -> get<std::vector<std::vector<int>>>(  graph_enum::edge_index, "index");
     std::vector<std::vector<float>> edge_sc = mtx -> get<std::vector<std::vector<float>>>(graph_enum::pred_extra, "top_edge_score");
     std::vector<std::vector<int>>   edge_tr = mtx -> get<std::vector<std::vector<int>>>(  graph_enum::truth_edge, "top_edge");
     std::vector<std::vector<int>>   graph_ntops_tru = mtx -> get<std::vector<std::vector<int>>>(  graph_enum::truth_graph, "ntops");
     std::vector<std::vector<float>> graph_ntops_prd = mtx -> get<std::vector<std::vector<float>>>(graph_enum::pred_extra , "ntops_score");
     if (!this -> mode.size()){this -> mode = mtx -> mode();}
     if (this -> mode != mtx -> mode()){this -> end();}
     this -> mode = mtx -> mode();
     for (size_t x(0); x < graph_ntops_tru.size(); ++x){
         int n_tp = maxv(&graph_ntops_prd[x]);
         int n_tt = graph_ntops_tru[x][0];
         this -> ntop_accuracy[n_tt][n_tp]++;
     }
     std::map<int, std::map<int, int>> bh_acc = {};
     for (size_t x(0); x < edge_sc.size(); ++x){
         long src = edge_idx[0][x];
         int ed_t =  edge_tr[x][0];
         int ibx = batch_idx[src];
         int c = int(int(edge_sc[x][0] <= edge_sc[x][1]) == ed_t);
         this -> _global_edge_accuracy[c]++;
         bh_acc[ibx][c]++;
     }
     this -> global_edge_accuracy = acc(&this -> _global_edge_accuracy);
     std::map<int, std::map<int, int>>::iterator itx;
     for (itx = bh_acc.begin(); itx != bh_acc.end(); ++itx){
         this -> edge_accuracy = acc(&itx -> second);
         this -> ntop_scores = graph_ntops_prd[itx -> first];
         this -> ntop_truth  = graph_ntops_tru[itx -> first][0];
         this -> event();
     }
 }
References batch_index, c, edge_index, end(), event(), simply_plot::mtx, pred_extra, truth_edge, truth_graph, and main::x.
define_variables()
void accuracy_metric::define_variables () override virtual
Reimplemented from metric_template.
Definition at line 7 of file accuracy.cxx.
{
     this -> register_output("event_accuracy_training"   , "edge", &this -> edge_accuracy);
     this -> register_output("event_accuracy_validation" , "edge", &this -> edge_accuracy);
     this -> register_output("event_accuracy_evaluation" , "edge", &this -> edge_accuracy);
     this -> register_output("event_accuracy_training"   , "ntop_scores", &this -> ntop_scores);
     this -> register_output("event_accuracy_validation" , "ntop_scores", &this -> ntop_scores);
     this -> register_output("event_accuracy_evaluation" , "ntop_scores", &this -> ntop_scores);
     this -> register_output("event_accuracy_training"   , "ntop_truth", &this -> ntop_truth);
     this -> register_output("event_accuracy_validation" , "ntop_truth", &this -> ntop_truth);
     this -> register_output("event_accuracy_evaluation" , "ntop_truth", &this -> ntop_truth);
     this -> register_output("global_accuracy_training"  , "edge", &this -> global_edge_accuracy);
     this -> register_output("global_accuracy_validation", "edge", &this -> global_edge_accuracy);
     this -> register_output("global_accuracy_evaluation", "edge", &this -> global_edge_accuracy);
     this -> register_output("global_accuracy_training"  , "ntops", &this -> ntops_accuracy);
     this -> register_output("global_accuracy_validation", "ntops", &this -> ntops_accuracy);
     this -> register_output("global_accuracy_evaluation", "ntops", &this -> ntops_accuracy);
 }
References metric_template::register_output().
end()
void accuracy_metric::end () override virtual
Reimplemented from metric_template.
Definition at line 36 of file accuracy.cxx.
{
     this -> ntops_accuracy = std::vector<float>(5, 0);
     for (int x(0); x < 5; ++x){
         int c(0); int f(0);
         for (int y(0); y < 5; ++y){
             if (x == y){c = this -> ntop_accuracy[x][y];}
             else {f += this -> ntop_accuracy[x][y];}
         }
         if ((f + c) == 0){this -> ntops_accuracy[x] = 1.0;}
         else {this -> ntops_accuracy[x] = float(c) / float(f + c);}
     }
     this -> write("global_accuracy_" + this -> mode,  "edge", &this -> global_edge_accuracy);
     this -> write("global_accuracy_" + this -> mode, "ntops", &this -> ntops_accuracy, true);
 }
References c, f, metric_template::write(), and main::x.
Referenced by define_metric().
event()
void accuracy_metric::event () override virtual
Reimplemented from metric_template.
Definition at line 29 of file accuracy.cxx.
{
     this -> write("event_accuracy_" + this -> mode, "ntop_scores", &this -> ntop_scores);
     this -> write("event_accuracy_" + this -> mode, "ntop_truth" , &this -> ntop_truth);
     this -> write("event_accuracy_" + this -> mode, "edge", &this -> edge_accuracy, true);
 }
References metric_template::write().
Referenced by define_metric().
The documentation for this class was generated from the following files:
accuracy.h
accuracy.cxx