AnalysisG: io Class Reference
io Class Reference
< Inherits from the notification class for logging capabilities.
#include <io.h>
Public Member Functions
io ()
< Public access specifier for the following members.
~io ()
Destructor for the io class.
template<typename g >
void write (std::vector< g > *inpt, std::string set_name)
Templated method to write a vector of objects to a dataset.
template<typename g >
void write (g *inpt, std::string set_name)
Templated method to write a single object to a dataset.
template<typename g >
void read (std::vector< g > *outpt, std::string set_name)
Templated method to read a vector of objects from a dataset.
template<typename g >
void read (g *out, std::string set_name)
Templated method to read a single object from a dataset.
void read (graph_hdf5_w *out, std::string set_name)
Reads graph data in HDF5 format specifically for graph_hdf5_w struct.
bool start (std::string filename, std::string read_write)
Starts an I/O session, opening a file for reading or writing.
void end ()
Ends the current I/O session, closing any open files.
std::vector< std::string > dataset_names ()
Retrieves the names of datasets available in the currently open HDF5 file.
std::map< std::string, long > root_size ()
Retrieves the sizes (number of entries) of TTrees in the open ROOT files.
void check_root_file_paths ()
Checks the validity or accessibility of ROOT file paths defined in settings or configurations.
bool scan_keys ()
Scans for keys (e.g., TTree names, TBranch names) in the open ROOT files.
void root_begin ()
Initializes ROOT file processing, potentially opening files specified in settings.
void root_end ()
Finalizes ROOT file processing, closing any ROOT files opened by root_begin.
void trigger_pcm ()
Triggers the generation of a ROOT PCM (Precompiled Module) if needed for dictionary generation.
void import_settings (settings_t *params)
Imports settings from a settings_t object to configure the io instance.
std::map< std::string, data_t * > * get_data ()
Retrieves the data read from ROOT files, likely structured as a map of data_t objects.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
void set_prefix (std::string prefix)
Sets the prefix used in log messages from this instance.
std::string get_prefix ()
Returns the prefix currently used in log messages.
void Info (std::string msg, bool newline=true)
Outputs an info message.
void Warning (std::string msg, bool newline=true)
Outputs a warning message.
void Error (std::string msg, bool newline=true)
Outputs an error message.
void Debug (std::string msg, bool newline=true)
Outputs a debug message (only in debug mode).
void Message (std::string msg, std::string tag="", bool newline=true)
Outputs a message with custom formatting.
void set_debug_mode (bool dbg)
Enables or disables debug mode.
bool get_debug_mode ()
Returns the current status of debug mode.
void set_suppress_warning (bool sw)
Sets whether warnings should be suppressed.
bool get_suppress_warning ()
Returns the current warning suppression status.
void set_suppress_info (bool si)
Sets whether info messages should be suppressed.
bool get_suppress_info ()
Returns the current info message suppression status.
Static Public Member Functions
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Public Attributes
bool enable_pyami = true
Flag to enable or disable PyAMI (ATLAS Metadata Interface) usage. Default true.
std::string metacache_path = "./"
Path to the directory for caching metadata. Default current directory.
std::string current_working_path = "."
Current working directory path. Default ".".
std::string sow_name = ""
Name for Sum-Of-Weights information, if applicable. Default empty.
std::vector< std::string > trees = {}
Vector to store names of TTrees to be processed. Initialized empty.
std::vector< std::string > branches = {}
Vector to store names of TBranches to be processed. Initialized empty.
std::vector< std::string > leaves = {}
Vector to store names of TLeaves (variables) to be processed. Initialized empty.
std::map< std::string, TFile * > files_open = {}
Map storing pointers to open TFile objects, keyed by filename. Initialized empty.
std::map< std::string, meta * > meta_data = {}
Map storing pointers to meta objects (metadata), keyed by an identifier (e.g., filename or sample label). Initialized empty.
std::map< std::string, std::map< std::string, TTree * > > tree_data = {}
Nested map storing TTree pointers: Filename -> (Tree Name -> TTree*). Initialized empty.
std::map< std::string, std::map< std::string, long > > tree_entries = {}
Nested map storing TTree entry counts: Filename -> (Tree Name -> N_Entries). Initialized empty.
std::map< std::string, std::map< std::string, TBranch * > > branch_data = {}
Nested map storing TBranch pointers: Branch Path (e.g., File/Tree) -> (Branch Name -> TBranch*). Initialized empty.
std::map< std::string, std::map< std::string, TLeaf * > > leaf_data = {}
Nested map storing TLeaf pointers: Filename -> (Leaf Name -> TLeaf*). Initialized empty.
std::map< std::string, std::map< std::string, std::string > > leaf_typed = {}
Nested map storing TLeaf type names: Filename -> (Leaf Name -> Type String). Initialized empty.
std::map< std::string, bool > root_files = {}
Map indicating if a given string (filename) corresponds to a (successfully opened) ROOT file. Initialized empty.
std::map< std::string, std::map< std::string, std::map< std::string, std::vector< std::string > > > > keys
Complex nested map for storing scanned keys from ROOT files (e.g., File -> Tree -> Branch -> Leaves).
Protected Attributes
std::string prefix = ""
Prefix used in log messages from this instance. Initialized as empty string.
bool debug_mode = false
Flag indicating whether debug mode is enabled. Initialized as false.
bool suppress_warnings = false
Flag indicating whether warnings are suppressed. Initialized as false.
bool suppress_info = false
Flag indicating whether info messages are suppressed. Initialized as false.
Private Member Functions
hid_t member (folds_t t)
< Private access specifier for the following members.
hid_t member (graph_hdf5_w t)
HDF5 member type creation for graph_hdf5_w struct.
template<typename g >
void write_event_h5 (std::vector< g > *evnt, std::string name)
Templated method to write event data (vector of objects) to HDF5.
template<typename g >
void write_event_h5 (g *evnt, std::string name)
Templated method to write single event data object to HDF5.
template<typename g >
void read_event_h5 (std::vector< g > *evnt, std::string name)
Templated method to read event data (vector of objects) from HDF5.
template<typename g >
void read_event_h5 (g *evnt, std::string name)
Templated method to read single event data object from HDF5.
template<typename g >
void H5Write (std::vector< g > *data, std::string set_name)
Generic HDF5 write operation for a vector of objects.
template<typename g >
void H5Write (g *data, std::string set_name)
Generic HDF5 write operation for a single object.
template<typename g >
void H5Read (std::vector< g > *data, std::string set_name)
Generic HDF5 read operation for a vector of objects.
template<typename g >
void H5Read (g *data, std::string set_name)
Generic HDF5 read operation for a single object.
Static Private Member Functions
static herr_t file_info (hid_t loc_id, const char *name, const H5L_info_t *linfo, void *opdata)
Static callback function for H5Literate, used to iterate over objects in an HDF5 file.
static herr_t op_func (hid_t loc_id, const char *name, const H5L_info_t *linfo, void *opdata)
Static callback function for H5Literate (alternative version or specific use case).
Private Attributes
std::string current_file = ""
Name of the currently open file. Initialized empty.
std::string reader_mode = ""
Current reader mode ("read" or "write"). Initialized empty.
std::string filename_data = ""
Filename associated with data, possibly for metadata. Initialized empty.
std::string filename_meta = ""
Filename associated with metadata. Initialized empty.
std::map< std::string, std::string > file_to_access_path = {}
Maps a file identifier to its access path. Initialized empty.
std::map< std::string, std::vector< std::string > > files_in_dir = {}
Maps directory paths to a list of files within them. Initialized empty.
std::map< std::string, std::string > files_in_dir_cache = {}
Cache for directory listings. Initialized empty.
std::map< std::string, data_t * > data = {}
Map storing data read from files, keyed by an identifier. Initialized empty.
std::map< std::string, TTreeReader * > m_readers = {}
Map storing TTreeReader objects, keyed by an identifier (e.g., tree name). Initialized empty.
H5::H5File * m_h5_file = nullptr
Pointer to an HDF5 file object. Initialized to nullptr.
hdf5 * m_h5 = nullptr
Pointer to a custom hdf5 handler class instance. Initialized to nullptr.
settings_t * m_settings = nullptr
Pointer to the settings object. Initialized to nullptr.
bool m_write = false
Flag indicating if in write mode. Initialized to false.
bool m_H5event = true
Flag related to HDF5 event processing mode. Initialized to true.
bool m_use_h5 = false
Flag indicating if HDF5 is being used. Initialized to false.
bool m_use_root = false
Flag indicating if ROOT is being used. Initialized to false.
Detailed Description
< Inherits from the notification class for logging capabilities.
Manages input and output operations for analysis data.
The io class provides an interface for reading from and writing to various data formats, with a focus on ROOT files (TTrees) and HDF5 files. It handles file opening/closing, data reading/writing for different data types (single objects, vectors of objects), and manages internal data structures for tracking file and dataset information.
Definition at line 42 of file io.h.
Constructor & Destructor Documentation
io()
io::io ()
< Public access specifier for the following members.
Constructor for the io class.
Constructor for the io class. Initializes a new io instance.
Initializes the io object with the prefix "io".
Definition at line 18 of file io/cxx/io.cxx.
References notification::prefix.
~io()
io::~io ()
Destructor for the io class.
Destructor for the io class.
Cleans up resources, such as closing open files.
Cleans up resources by closing open files and freeing memory.
Definition at line 25 of file io/cxx/io.cxx.
References end(), files_open, meta_data, and root_end().
Member Function Documentation
absolute_path()
std::string tools::absolute_path (std::string path) static inherited
Converts a relative path to an absolute path.
Parameters
path The path to convert.
Returns
The absolute version of the path.
Definition at line 49 of file tools/cxx/io.cxx.
Referenced by analysis::analysis(), analysis::build_events(), check_root_file_paths(), and trigger_pcm().
check_root_file_paths()
void io::check_root_file_paths ()
Checks the validity or accessibility of ROOT file paths defined in settings or configurations.
Definition at line 31 of file io/cxx/root.cxx.
References tools::absolute_path(), tools::ends_with(), f, tools::is_file(), l, tools::ls(), and root_files.
create_path()
void tools::create_path (std::string path) static inherited
Creates a directory path, including parent directories if needed.
Parameters
path The directory path to create.
Definition at line 6 of file tools/cxx/io.cxx.
References f, and tools::split().
Referenced by analysis::analysis(), analysis::build_inference(), plotting::build_path(), analysis::build_project(), container::compile(), metrics::dump_mass_plots(), metric_template::execute(), metrics::generic_painter(), analysis::start(), start(), and trigger_pcm().
dataset_names()
std::vector< std::string > io::dataset_names ()
Retrieves the names of datasets available in the currently open HDF5 file.
Returns
A vector of strings, where each string is a dataset name.
Definition at line 62 of file hdf5.cxx.
References file_info().
Referenced by dataloader::restore_graphs_().
Debug()
void notification::Debug (std::string msg, bool newline = true) inherited
Outputs a debug message (only in debug mode).
Parameters
msg The debug message to output.
newline Whether to append a newline (default: true).
delete_path()
void tools::delete_path (std::string path) static inherited
Deletes a directory path and its contents.
Parameters
path The directory path to delete.
Definition at line 22 of file tools/cxx/io.cxx.
end()
void io::end ()
Ends the current I/O session, closing any open files.
Definition at line 28 of file hdf5.cxx.
Referenced by ~io(), analysis::build_events(), dataloader::restore_graphs_(), root_begin(), root_end(), and scan_keys().
ends_with()
bool tools::ends_with (std::string * inpt, std::string val) static inherited
Checks if a string ends with a specific substring.
Parameters
inpt Pointer to the string to check.
val The substring to check for at the end.
Returns
True if the string ends with the substring, false otherwise.
Definition at line 71 of file strings.cxx.
References l.
Referenced by plotting::build_path(), check_root_file_paths(), dataloader::dump_graphs(), tools::ls(), meta::parse_json(), scan_keys(), and analysis::start().
Error()
void notification::Error (std::string msg, bool newline = true) inherited
Outputs an error message.
Parameters
msg The error message to output.
newline Whether to append a newline (default: true).
extract()
template<typename C , typename T > static void tools::extract (std::vector< T > * prop, std::vector< C * > * src, void(*)(T *, C *) get_prop) inline static inherited
Extracts a specific property from a vector of objects into a new vector.
Template Parameters
C The type of objects in the source vector.
T The type of the property to extract.
Parameters
prop Pointer to the output vector to fill with property values.
src Pointer to the source vector of objects.
get_prop Function pointer to extract the property from an object.
< Clear the properties vector.
< Reserve space for the property values.
< Loop through each object in the source vector.
< Create a default-initialized property variable.
< Call the provided function to extract the property.
< Add the property value to the output vector.
Definition at line 216 of file tools.h.
file_info()
herr_t io::file_info (hid_t loc_id, const char * name, const H5L_info_t * linfo, void * opdata) static private
Static callback function for H5Literate, used to iterate over objects in an HDF5 file.
Parameters
loc_id Location identifier.
name Name of the object.
linfo Pointer to H5L_info_t struct containing link information.
opdata Pointer to operator data (user-supplied).
Returns
HDF5 error status.
Definition at line 53 of file hdf5.cxx.
References data.
Referenced by dataset_names().
flush()
template<typename T > static void tools::flush (std::vector< T * > * inpt) inline static inherited
Empties a vector and all objects it points to.
Template Parameters
T The type of pointers in the vector.
Parameters
inpt Pointer to the vector to empty.
< Loop through all elements in the vector.
< Delete the object the pointer points to.
< Set the pointer to nullptr to avoid dangling pointers.
< Clear the vector.
Definition at line 167 of file tools.h.
Referenced by analysis::~analysis(), dataloader::~dataloader(), sampletracer::compile_objects(), and root_end().
get_data()
std::map< std::string, data_t * > * io::get_data ()
Retrieves the data read from ROOT files, likely structured as a map of data_t objects.
Returns
Pointer to a map where keys are data identifiers (e.g., branch names) and values are data_t pointers.
Definition at line 353 of file io/cxx/root.cxx.
References root_begin().
get_debug_mode()
bool notification::get_debug_mode () inherited
Returns the current status of debug mode.
Returns
Boolean indicating whether debug mode is enabled (true) or disabled (false).
get_prefix()
std::string notification::get_prefix () inherited
Returns the prefix currently used in log messages.
Returns
The current prefix string.
get_suppress_info()
bool notification::get_suppress_info () inherited
Returns the current info message suppression status.
Returns
Boolean indicating whether info messages are suppressed (true) or shown (false).
get_suppress_warning()
bool notification::get_suppress_warning () inherited
Returns the current warning suppression status.
Returns
Boolean indicating whether warnings are suppressed (true) or shown (false).
H5Read() [1/2]
template<typename g > void io::H5Read (g * data, std::string set_name) inline private
Generic HDF5 read operation for a single object.
Template Parameters
g Type of the object.
Parameters
data Pointer to an object of type g to store read data.
set_name Name of the dataset.
< Get HDF5 member type for the object.
< Perform HDF5 read.
< Close the HDF5 datatype.
Definition at line 322 of file io.h.
References data, m_h5, and member().
H5Read() [2/2]
template<typename g > void io::H5Read (std::vector< g > * data, std::string set_name) inline private
Generic HDF5 read operation for a vector of objects.
Template Parameters
g Type of objects in the vector.
Parameters
data Pointer to a vector of objects of type g to store read data.
set_name Name of the dataset.
< Create a default-initialized element of type g to get member type.
< Get HDF5 member type.
< Perform HDF5 read.
< Close the HDF5 datatype.
Definition at line 308 of file io.h.
References data, m_h5, and member().
Referenced by read_event_h5(), and read_event_h5().
H5Write() [1/2]
template<typename g > void io::H5Write (g * data, std::string set_name) inline private
Generic HDF5 write operation for a single object.
Template Parameters
g Type of the object.
Parameters
data Pointer to an object of type g.
set_name Name of the dataset.
< Get HDF5 member type for the object.
< Perform HDF5 write using the obtained member type.
< Close the HDF5 datatype.
Definition at line 295 of file io.h.
References data, m_h5, and member().
H5Write() [2/2]
template<typename g > void io::H5Write (std::vector< g > * data, std::string set_name) inline private
Generic HDF5 write operation for a vector of objects.
Template Parameters
g Type of objects in the vector.
Parameters
data Pointer to a vector of objects of type g.
set_name Name of the dataset.
< Get HDF5 member type for the first element.
< Perform HDF5 write using the obtained member type.
< Close the HDF5 datatype.
Definition at line 282 of file io.h.
References data, m_h5, and member().
Referenced by write_event_h5(), and write_event_h5().
has_string()
bool tools::has_string (std::string * inpt, std::string trg) static inherited
Checks if a string contains a specific substring.
Parameters
inpt Pointer to the string to check.
trg The substring to search for.
Returns
True if the substring is found, false otherwise.
Definition at line 65 of file strings.cxx.
References f.
Referenced by analysis::check_cache(), meta::compiler(), metrics::generic_painter(), dataloader::restore_graphs_(), meta::scan_sow(), model_template::set_device(), and metric_template::set_run_name().
has_value()
bool tools::has_value (std::vector< std::string > * data, std::string trg) static inherited
Checks if a vector of strings contains a specific string.
Parameters
data Pointer to the vector to search.
trg The string to search for.
Returns
True if the string is found in the vector, false otherwise.
Definition at line 77 of file strings.cxx.
Referenced by scan_keys().
import_settings()
void io::import_settings (settings_t * params)
Imports settings from a settings_t object to configure the io instance.
Imports settings into the IO module.
Parameters
params Pointer to a settings_t object.
This function configures the IO module based on the provided settings. It sets up the metacache path, sum of weights name, and other parameters.
Parameters
params Pointer to the settings structure.
Definition at line 51 of file io/cxx/io.cxx.
References enable_pyami, metacache_path, and sow_name.
Info()
void notification::Info (std::string msg, bool newline = true) inherited
Outputs an info message.
Parameters
msg The message to output.
newline Whether to append a newline (default: true).
is_file()
bool tools::is_file (std::string path) static inherited
Checks if a path refers to an existing file.
Parameters
path The path to check.
Returns
True if the path is a file and exists, false otherwise.
Definition at line 30 of file tools/cxx/io.cxx.
Referenced by check_root_file_paths(), analysis::initialize_loop(), metric_template::set_run_name(), and start().
ls()
std::vector< std::string > tools::ls (std::string path, std::string ext = "") static inherited
Lists files in a directory, optionally filtered by extension.
Parameters
path The directory to search.
ext File extension filter. If empty, all files are listed.
Returns
A vector of filenames in the directory.
Definition at line 35 of file tools/cxx/io.cxx.
References tools::ends_with(), and tools::split().
Referenced by analysis::analysis(), analysis::check_cache(), check_root_file_paths(), dataloader::restore_graphs(), and trigger_pcm().
member() [1/2]
hid_t io::member (folds_t t) private
< Private access specifier for the following members.
HDF5 member type creation for folds_t struct.
Parameters
t An instance of folds_t (used for type deduction, not value).
Returns
HDF5 data type identifier (hid_t).
Definition at line 3 of file types.cxx.
References px.
Referenced by H5Read(), H5Read(), H5Write(), H5Write(), and read().
member() [2/2]
hid_t io::member (graph_hdf5_w t) private
HDF5 member type creation for graph_hdf5_w struct.
Parameters
t An instance of graph_hdf5_w (used for type deduction, not value).
Returns
HDF5 data type identifier (hid_t).
Definition at line 17 of file types.cxx.
References data_edge, data_graph, data_node, edge_index, event_weight(), px, truth_edge, truth_graph, and truth_node.
Message()
void notification::Message (std::string msg, std::string tag = "", bool newline = true) inherited
Outputs a message with custom formatting.
Parameters
msg The message to output.
tag A custom tag to prepend to the message.
newline Whether to append a newline (default: true).
op_func()
static herr_t io::op_func (hid_t loc_id, const char * name, const H5L_info_t * linfo, void * opdata) static private
Static callback function for H5Literate (alternative version or specific use case).
Parameters
loc_id Location identifier.
name Name of the object.
linfo Pointer to H5L_info_t struct containing link information.
opdata Pointer to operator data (user-supplied).
Returns
HDF5 error status.
put()
template<typename g > static void tools::put (std::vector< g * > * out, std::vector< g * > * src, std::vector< int > * trg) inline static inherited
Fills a vector with pointers from another vector based on a selection index.
Template Parameters
g The type of objects being pointed to.
Parameters
out Pointer to the output vector to fill.
src Pointer to the source vector to select from.
trg Pointer to a vector of indices for selection.
< Clear the output vector.
< Reserve space for the output elements.
< Loop through each selected index.
< Get the object at the selected index.
< Add it to the output vector.
< Mark the object as in use.
Definition at line 197 of file tools.h.
Referenced by dataloader::get_k_train_set(), dataloader::get_k_validation_set(), and dataloader::get_test_set().
read() [1/3]
template<typename g > void io::read (g * out, std::string set_name) inline
Templated method to read a single object from a dataset.
Template Parameters
g The type of the object.
Parameters
out Pointer to an object of type g where read data will be stored.
set_name The name of the dataset to read from.
< Read data from HDF5.
Definition at line 108 of file io.h.
References m_h5, m_H5event, m_write, read_event_h5(), and notification::Warning().
read() [2/3]
void io::read (graph_hdf5_w * out, std::string set_name)
Reads graph data in HDF5 format specifically for graph_hdf5_w struct.
Parameters
out Pointer to a graph_hdf5_w object to store the read data.
set_name The name of the dataset to read from.
Definition at line 3 of file hdf5.cxx.
References member(), and read().
read() [3/3]
template<typename g > void io::read (std::vector< g > * outpt, std::string set_name) inline
Templated method to read a vector of objects from a dataset.
Template Parameters
g The type of objects in the vector.
Parameters
outpt Pointer to a vector of objects of type g where read data will be stored.
set_name The name of the dataset to read from.
< Read data from HDF5.
Definition at line 95 of file io.h.
References m_h5, m_H5event, m_write, read_event_h5(), and notification::Warning().
Referenced by read().
read_event_h5() [1/2]
template<typename g > void io::read_event_h5 (g * evnt, std::string name) inline private
Templated method to read single event data object from HDF5.
Specific implementation for event-like data structures.
Template Parameters
g Type of the object.
Parameters
evnt Pointer to an object of type g to store read data.
name Name of the dataset.
Definition at line 273 of file io.h.
References H5Read().
read_event_h5() [2/2]
template<typename g > void io::read_event_h5 (std::vector< g > * evnt, std::string name) inline private
Templated method to read event data (vector of objects) from HDF5.
Specific implementation for event-like data structures.
Template Parameters
g Type of objects in the vector.
Parameters
evnt Pointer to a vector of objects of type g to store read data.
name Name of the dataset.
Definition at line 263 of file io.h.
References H5Read().
Referenced by read(), and read().
rename()
void tools::rename (std::string start, std::string target) static inherited
Renames a file or directory.
Parameters
start The original path.
target The new path.
Definition at line 18 of file tools/cxx/io.cxx.
Referenced by dataloader::dump_graphs().
replace()
void tools::replace (std::string * in, std::string repl_str, std::string repl_with) static inherited
Replaces all occurrences of a substring in a string.
Parameters
in Pointer to the string to modify.
repl_str The substring to replace.
repl_with The replacement string.
Definition at line 5 of file strings.cxx.
Referenced by analysis::build_graphs(), analysis::check_cache(), dataloader::dump_graphs(), meta::get_campaign(), meta::parse_json(), and analysis::start().
root_begin()
void io::root_begin ()
Initializes ROOT file processing, potentially opening files specified in settings.
Definition at line 301 of file io/cxx/root.cxx.
References count(), end(), files_open, leaf_data, leaf_typed, root_end(), scan_keys(), tools::split(), and tree_entries.
Referenced by get_data().
root_end()
void io::root_end ()
Finalizes ROOT file processing, closing any ROOT files opened by root_begin.
Definition at line 358 of file io/cxx/root.cxx.
References end(), and tools::flush().
Referenced by ~io(), and root_begin().
root_size()
std::map< std::string, long > io::root_size ()
Retrieves the sizes (number of entries) of TTrees in the open ROOT files.
Returns
A map where keys are TTree names (or unique identifiers) and values are their sizes (long).
Definition at line 290 of file io/cxx/root.cxx.
References scan_keys(), and tree_entries.
scan_keys()
bool io::scan_keys ()
Scans for keys (e.g., TTree names, TBranch names) in the open ROOT files.
Returns
True if keys were successfully scanned, false otherwise (e.g., no files open).
Definition at line 181 of file io/cxx/root.cxx.
References branch_data, branches, count(), end(), tools::ends_with(), files_open, tools::has_value(), keys, leaf_data, leaves, root_files, tree_data, tree_entries, and trees.
Referenced by root_begin(), and root_size().
set_debug_mode()
void notification::set_debug_mode (bool dbg) inherited
Enables or disables debug mode.
Parameters
dbg Boolean flag, set to true to enable debug messages, false to disable.
set_prefix()
void notification::set_prefix (std::string prefix) inherited
Sets the prefix used in log messages from this instance.
Parameters
prefix The string to use as a prefix for log messages.
set_suppress_info()
void notification::set_suppress_info (bool si) inherited
Sets whether info messages should be suppressed.
Parameters
si Boolean flag, set to true to suppress info messages, false to show them.
set_suppress_warning()
void notification::set_suppress_warning (bool sw) inherited
Sets whether warnings should be suppressed.
Parameters
sw Boolean flag, set to true to suppress warnings, false to show them.
split()
std::vector< std::string > tools::split (std::string inpt, std::string del) inherited
Splits a string into a vector of substrings based on a delimiter.
Parameters
inpt The input string to split.
del The delimiter.
Returns
A vector of substrings.
Definition at line 23 of file strings.cxx.
References index.
Referenced by analysis::build_events(), analysis::build_graphs(), analysis::build_inference(), event_template::build_mapping(), analysis::check_cache(), container::compile(), sampletracer::compile_objects(), meta::compiler(), tools::create_path(), dataloader::dump_graphs(), meta::hash(), tools::ls(), graph_t::meta_deserialize(), dataloader::restore_graphs_(), root_begin(), model_template::set_device(), metric_template::set_run_name(), metric_template::set_variables(), and analysis::start().
start()
bool io::start (std::string filename, std::string read_write)
Starts an I/O session, opening a file for reading or writing.
Parameters
filename The name of the file to open.
read_write Mode of operation: "read" or "write".
Returns
True if the file was successfully opened in the specified mode, false otherwise.
Definition at line 15 of file hdf5.cxx.
References tools::create_path(), f, and tools::is_file().
Referenced by dataloader::restore_graphs_().
sum()
template<typename g > g tools::sum (std::vector< g > * inpt) inline inherited
Sums the elements of a vector.
Template Parameters
g The type of elements in the vector.
Parameters
inpt Pointer to the vector to sum.
Returns
The sum of all elements.
< Initialize the output variable.
< Return the sum.
Definition at line 183 of file tools.h.
Referenced by metrics::add_th1f_accuracy(), sampletracer::compile_objects(), particle_template::DeltaR(), graph_template::double_neutrino(), grift::forward(), recursivegraphneuralnetwork::forward(), matching::match_obj(), and grift::message().
to_string() [1/2]
std::string tools::to_string (double val) static inherited
Converts a double value to a string with standard precision.
Parameters
val The double value to convert.
Returns
The string representation of the value.
Definition at line 59 of file strings.cxx.
Referenced by dataloader::generate_kfold_set(), dataloader::generate_test_set(), particle_template::get_hash(), topefficiency::region(), dataloader::restore_dataset(), event_template::set_hash(), selection_template::set_hash(), parton::strategy(), topjets::strategy(), toptruthjets::strategy(), and parton::top_mass_contribution().
to_string() [2/2]
std::string tools::to_string (double val, int prec) static inherited
Converts a double value to a string with specified precision.
Parameters
val The double value to convert.
prec The number of decimal places to consider.
Returns
The string representation of the value.
Definition at line 91 of file strings.cxx.
trigger_pcm()
void io::trigger_pcm ()
Triggers the generation of a ROOT PCM (Precompiled Module) if needed for dictionary generation.
Definition at line 7 of file io/cxx/root.cxx.
References tools::absolute_path(), buildAll(), buildDict(), tools::create_path(), tools::ls(), and undef.
trim()
std::string tools::trim (std::string s) inherited
Removes whitespace from the beginning and end of a string.
Parameters
s The string to trim.
Returns
The trimmed string.
type_name()
template<typename T > std::string tools::type_name () inline inherited
Gets the type name of a variable as a string (for debugging).
Template Parameters
T The type to get the name of.
Returns
The name of the type as a string.
< Gets the type name via RTTI.
< Returns the type name.
Definition at line 155 of file tools.h.
Referenced by event_template::build_mapping().
Warning()
void notification::Warning (std::string msg, bool newline = true) inherited
Outputs a warning message.
Parameters
msg The warning message to output.
newline Whether to append a newline (default: true).
Referenced by read(), read(), write(), and write().
write() [1/2]
template<typename g > void io::write (g * inpt, std::string set_name) inline
Templated method to write a single object to a dataset.
Template Parameters
g The type of the object.
Parameters
inpt Pointer to an object of type g to be written.
set_name The name of the dataset to write to.
< Get the type name of g.
< Write data to HDF5.
Definition at line 80 of file io.h.
References m_h5, m_H5event, m_write, notification::Warning(), and write_event_h5().
write() [2/2]
template<typename g > void io::write (std::vector< g > * inpt, std::string set_name) inline
Templated method to write a vector of objects to a dataset.
Template Parameters
g The type of objects in the vector.
Parameters
inpt Pointer to a vector of objects of type g to be written.
set_name The name of the dataset to write to.
< Get the type name of g.
< Write data to HDF5.
Definition at line 65 of file io.h.
References m_h5, m_H5event, m_write, notification::Warning(), and write_event_h5().
write_event_h5() [1/2]
template<typename g > void io::write_event_h5 (g * evnt, std::string name) inline private
Templated method to write single event data object to HDF5.
Specific implementation for event-like data structures.
Template Parameters
g Type of the object.
Parameters
evnt Pointer to an object of type g.
name Name of the dataset.
Definition at line 253 of file io.h.
References H5Write().
write_event_h5() [2/2]
template<typename g > void io::write_event_h5 (std::vector< g > * evnt, std::string name) inline private
Templated method to write event data (vector of objects) to HDF5.
Specific implementation for event-like data structures.
Template Parameters
g Type of objects in the vector.
Parameters
evnt Pointer to a vector of objects of type g.
name Name of the dataset.
Definition at line 243 of file io.h.
References H5Write().
Referenced by write(), and write().
Member Data Documentation
branch_data
std::map<std::string, std::map<std::string, TBranch*> > io::branch_data = {}
Nested map storing TBranch pointers: Branch Path (e.g., File/Tree) -> (Branch Name -> TBranch*). Initialized empty.
Definition at line 193 of file io.h.
Referenced by scan_keys().
branches
std::vector<std::string> io::branches = {}
Vector to store names of TBranches to be processed. Initialized empty.
Definition at line 183 of file io.h.
Referenced by scan_keys().
current_file
std::string io::current_file = "" private
Name of the currently open file. Initialized empty.
Definition at line 328 of file io.h.
current_working_path
std::string io::current_working_path = "."
Current working directory path. Default ".".
Definition at line 179 of file io.h.
data
std::map<std::string, data_t*> io::data = {} private
Map storing data read from files, keyed by an identifier. Initialized empty.
Definition at line 337 of file io.h.
Referenced by file_info(), H5Read(), H5Read(), H5Write(), and H5Write().
debug_mode
bool notification::debug_mode = false protected inherited
Flag indicating whether debug mode is enabled. Initialized as false.
Definition at line 127 of file notification.h.
Referenced by analysis::build_metric().
enable_pyami
bool io::enable_pyami = true
Flag to enable or disable PyAMI (ATLAS Metadata Interface) usage. Default true.
Definition at line 177 of file io.h.
Referenced by import_settings().
file_to_access_path
std::map<std::string, std::string> io::file_to_access_path = {} private
Maps a file identifier to its access path. Initialized empty.
Definition at line 333 of file io.h.
filename_data
std::string io::filename_data = "" private
Filename associated with data, possibly for metadata. Initialized empty.
Definition at line 330 of file io.h.
filename_meta
std::string io::filename_meta = "" private
Filename associated with metadata. Initialized empty.
Definition at line 331 of file io.h.
files_in_dir
std::map<std::string, std::vector<std::string> > io::files_in_dir = {} private
Maps directory paths to a list of files within them. Initialized empty.
Definition at line 334 of file io.h.
files_in_dir_cache
std::map<std::string, std::string> io::files_in_dir_cache = {} private
Cache for directory listings. Initialized empty.
Definition at line 335 of file io.h.
files_open
std::map<std::string, TFile*> io::files_open = {}
Map storing pointers to open TFile objects, keyed by filename. Initialized empty.
Definition at line 186 of file io.h.
Referenced by ~io(), root_begin(), and scan_keys().
keys
std::map<std::string, std::map<std::string, std::map<std::string, std::vector<std::string> > > > io::keys
Complex nested map for storing scanned keys from ROOT files (e.g., File -> Tree -> Branch -> Leaves).
Definition at line 200 of file io.h.
Referenced by scan_keys().
leaf_data
std::map<std::string, std::map<std::string, TLeaf*> > io::leaf_data = {}
Nested map storing TLeaf pointers: Filename -> (Leaf Name -> TLeaf*). Initialized empty.
Definition at line 196 of file io.h.
Referenced by root_begin(), and scan_keys().
leaf_typed
std::map<std::string, std::map<std::string, std::string> > io::leaf_typed = {}
Nested map storing TLeaf type names: Filename -> (Leaf Name -> Type String). Initialized empty.
Definition at line 197 of file io.h.
Referenced by root_begin().
leaves
std::vector<std::string> io::leaves = {}
Vector to store names of TLeaves (variables) to be processed. Initialized empty.
Definition at line 184 of file io.h.
Referenced by scan_keys().
m_h5
hdf5* io::m_h5 = nullptr private
Pointer to a custom hdf5 handler class instance. Initialized to nullptr.
Definition at line 341 of file io.h.
Referenced by H5Read(), H5Read(), H5Write(), H5Write(), read(), read(), write(), and write().
m_h5_file
H5::H5File* io::m_h5_file = nullptr private
Pointer to an HDF5 file object. Initialized to nullptr.
Definition at line 340 of file io.h.
m_H5event
bool io::m_H5event = true private
Flag related to HDF5 event processing mode. Initialized to true.
Definition at line 345 of file io.h.
Referenced by read(), read(), write(), and write().
m_readers
std::map<std::string, TTreeReader*> io::m_readers = {} private
Map storing TTreeReader objects, keyed by an identifier (e.g., tree name). Initialized empty.
Definition at line 338 of file io.h.
m_settings
settings_t* io::m_settings = nullptr private
Pointer to the settings object. Initialized to nullptr.
Definition at line 342 of file io.h.
m_use_h5
bool io::m_use_h5 = false private
Flag indicating if HDF5 is being used. Initialized to false.
Definition at line 346 of file io.h.
m_use_root
bool io::m_use_root = false private
Flag indicating if ROOT is being used. Initialized to false.
Definition at line 347 of file io.h.
m_write
bool io::m_write = false private
Flag indicating if in write mode. Initialized to false.
Definition at line 344 of file io.h.
Referenced by read(), read(), write(), and write().
meta_data
std::map<std::string, meta*> io::meta_data = {}
Map storing pointers to meta objects (metadata), keyed by an identifier (e.g., filename or sample label). Initialized empty.
Definition at line 187 of file io.h.
Referenced by ~io().
metacache_path
std::string io::metacache_path = "./"
Path to the directory for caching metadata. Default current directory.
Definition at line 178 of file io.h.
Referenced by import_settings().
prefix
std::string notification::prefix = "" protected inherited
Prefix used in log messages from this instance. Initialized as empty string.
Definition at line 126 of file notification.h.
Referenced by analysis::analysis(), dataloader::dataloader(), io(), meta::meta(), optimizer::optimizer(), and metric_template::set_name().
reader_mode
std::string io::reader_mode = "" private
Current reader mode ("read" or "write"). Initialized empty.
Definition at line 329 of file io.h.
root_files
std::map<std::string, bool> io::root_files = {}
Map indicating if a given string (filename) corresponds to a (successfully opened) ROOT file. Initialized empty.
Definition at line 198 of file io.h.
Referenced by check_root_file_paths(), and scan_keys().
sow_name
std::string io::sow_name = ""
Name for Sum-Of-Weights information, if applicable. Default empty.
Definition at line 180 of file io.h.
Referenced by import_settings().
suppress_info
bool notification::suppress_info = false protected inherited
Flag indicating whether info messages are suppressed. Initialized as false.
Definition at line 129 of file notification.h.
suppress_warnings
bool notification::suppress_warnings = false protected inherited
Flag indicating whether warnings are suppressed. Initialized as false.
Definition at line 128 of file notification.h.
tree_data
std::map<std::string, std::map<std::string, TTree*> > io::tree_data = {}
Nested map storing TTree pointers: Filename -> (Tree Name -> TTree*). Initialized empty.
Definition at line 190 of file io.h.
Referenced by scan_keys().
tree_entries
std::map<std::string, std::map<std::string, long> > io::tree_entries = {}
Nested map storing TTree entry counts: Filename -> (Tree Name -> N_Entries). Initialized empty.
Definition at line 191 of file io.h.
Referenced by root_begin(), root_size(), and scan_keys().
trees
std::vector<std::string> io::trees = {}
Vector to store names of TTrees to be processed. Initialized empty.
Definition at line 182 of file io.h.
Referenced by scan_keys().
The documentation for this class was generated from the following files:
io.h
hdf5.cxx
io/cxx/io.cxx
io/cxx/root.cxx
types.cxx