AnalysisG: metric_template Class Reference
metric_template Class Reference
#include <metric_template.h>
Public Member Functions
metric_template ()
virtual ~metric_template ()
virtual metric_template * clone ()
template<typename T >
void register_output (std::string tree, std::string name, T *t)
template<typename T >
void write (std::string tree, std::string name, T *t, bool fill=false)
virtual void define_variables ()
virtual void define_metric (metric_t *v)
virtual void event ()
virtual void batch ()
virtual void end ()
Public Member Functions inherited from tools
tools ()
Constructor for the tools class.
~tools ()
Destructor for the tools class.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Public Member Functions inherited from notification
notification ()
Constructor for the notification class.
~notification ()
Destructor for the notification class.
void set_prefix (std::string prefix)
Sets the prefix used in log messages from this instance.
std::string get_prefix ()
Returns the prefix currently used in log messages.
void Info (std::string msg, bool newline=true)
Outputs an info message.
void Warning (std::string msg, bool newline=true)
Outputs a warning message.
void Error (std::string msg, bool newline=true)
Outputs an error message.
void Debug (std::string msg, bool newline=true)
Outputs a debug message (only in debug mode).
void Message (std::string msg, std::string tag="", bool newline=true)
Outputs a message with custom formatting.
void set_debug_mode (bool dbg)
Enables or disables debug mode.
bool get_debug_mode ()
Returns the current status of debug mode.
void set_suppress_warning (bool sw)
Sets whether warnings should be suppressed.
bool get_suppress_warning ()
Returns the current warning suppression status.
void set_suppress_info (bool si)
Sets whether info messages should be suppressed.
bool get_suppress_info ()
Returns the current info message suppression status.
Public Attributes
cproperty< std::string, metric_template > name
cproperty< std::map< std::string, std::string >, metric_template > run_names
cproperty< std::vector< std::string >, metric_template > variables
meta * meta_data = nullptr
Additional Inherited Members
Static Public Member Functions inherited from tools
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Protected Attributes inherited from notification
std::string prefix = ""
Prefix used in log messages from this instance. Initialized as empty string.
bool debug_mode = false
Flag indicating whether debug mode is enabled. Initialized as false.
bool suppress_warnings = false
Flag indicating whether warnings are suppressed. Initialized as false.
bool suppress_info = false
Flag indicating whether info messages are suppressed. Initialized as false.
Detailed Description
Definition at line 72 of file metric_template.h.
Constructor & Destructor Documentation
metric_template()
metric_template::metric_template ()
Definition at line 5 of file metric_template.cxx.
{
     this -> name.set_object(this);
     this -> name.set_setter(this -> set_name);
     this -> name.set_getter(this -> get_name);
     this -> run_names.set_object(this);
     this -> run_names.set_setter(this -> set_run_name);
     this -> run_names.set_getter(this -> get_run_name);
     this -> variables.set_object(this);
     this -> variables.set_setter(this -> set_variables);
     this -> variables.set_getter(this -> get_variables);
 }
References name, run_names, cproperty< T, G >::set_getter(), cproperty< T, G >::set_object(), cproperty< T, G >::set_setter(), and variables.
Referenced by clone().
~metric_template()
metric_template::~metric_template () virtual
Definition at line 19 of file metric_template.cxx.
{
     if (!this -> handle){return;}
     delete this -> handle;
     this -> handle = nullptr;
 }
Member Function Documentation
batch()
void metric_template::batch () virtual
Reimplemented in accuracy_metric, and pagerank_metric.
Definition at line 36 of file metric_template.cxx.
 {};
clone()
metric_template * metric_template::clone () virtual
Reimplemented in accuracy_metric, and pagerank_metric.
Definition at line 25 of file metric_template.cxx.
 {return new metric_template();}
References metric_template().
define_metric()
void metric_template::define_metric (metric_t * v) virtual
Reimplemented in accuracy_metric, and pagerank_metric.
Definition at line 33 of file metric_template.cxx.
 {}
define_variables()
void metric_template::define_variables () virtual
Reimplemented in accuracy_metric, and pagerank_metric.
Definition at line 34 of file metric_template.cxx.
 {}
end()
void metric_template::end () virtual
Reimplemented in accuracy_metric, and pagerank_metric.
Definition at line 37 of file metric_template.cxx.
 {};
event()
void metric_template::event () virtual
Reimplemented in accuracy_metric, and pagerank_metric.
Definition at line 35 of file metric_template.cxx.
 {};
register_output()
template<typename T > void metric_template::register_output (std::string tree, std::string name, T * t) inline
Definition at line 82 of file metric_template.h.
{
             if (this -> handle){return this -> handle -> process(&tree, &name, t);}
             this -> handle = new writer();
             this -> handle -> create(&this -> _outdir);
             this -> handle -> process(&tree, &name, t);
         }
References name, and test_experimental_mc20::t.
Referenced by accuracy_metric::define_variables().
write()
template<typename T > void metric_template::write (std::string tree, std::string name, T * t, bool fill = false) inline
Definition at line 90 of file metric_template.h.
{
             if (!this -> handle){return;}
             this -> handle -> process(&tree, &name, t);
             if (!fill){return;}
             this -> handle -> write(&tree);
         }
References name, and test_experimental_mc20::t.
Referenced by accuracy_metric::end(), and accuracy_metric::event().
Member Data Documentation
meta_data
meta* metric_template::meta_data = nullptr
Definition at line 106 of file metric_template.h.
name
cproperty<std::string, metric_template> metric_template::name
Definition at line 103 of file metric_template.h.
Referenced by accuracy_metric::accuracy_metric(), metric_template(), pagerank_metric::pagerank_metric(), register_output(), and write().
run_names
cproperty<std::map<std::string, std::string>, metric_template> metric_template::run_names
Definition at line 104 of file metric_template.h.
Referenced by metric_template().
variables
cproperty<std::vector<std::string>, metric_template> metric_template::variables
Definition at line 105 of file metric_template.h.
Referenced by metric_template().
The documentation for this class was generated from the following files:
metric_template.h
metric/cxx/base.cxx
link.cxx
metric_template.cxx
metric/cxx/properties.cxx