AnalysisG: validation Class Reference
validation Class Reference
#include <validation.h>
Public Member Functions
validation ()
~validation () override
selection_template * clone () override
bool selection (event_template *ev) override
bool strategy (event_template *ev) override
void merge (selection_template *sl) override
void reconstruction (packet_t *data)
void update_state (packet_t *data)
Public Member Functions inherited from selection_template
selection_template ()
virtual ~selection_template ()
virtual void bulk_write (const long *idx, std::string *hx)
virtual void write (std::vector< particle_template * > *particles, std::string name, particle_enum attrs)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< std::vector< double >> *data)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< int > *data)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< double > *data)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< bool > *data)
template<typename g >
void write (g *var, std::string name)
template<typename g >
void write (g var, std::string name)
std::vector< std::map< std::string, float > > reverse_hash (std::vector< std::string > *hashes)
bool CompileEvent ()
selection_template * build (event_template *ev)
bool operator== (selection_template &p)
template<typename g , typename k >
void sum (std::vector< g * > *ch, k **out)
template<typename g >
void safe_delete (std::vector< g * > *particles)
template<typename g >
g * sum (std::map< std::string, g * > *ch)
template<typename g >
float sum (std::vector< g * > *ch)
template<typename g >
std::vector< g * > vectorize (std::map< std::string, g * > *in)
template<typename g >
std::vector< g * > make_unique (std::vector< g * > *inpt)
template<typename g >
void downcast (std::vector< g * > *inpt, std::vector< particle_template * > *out)
template<typename o , typename g >
void upcast (std::map< std::string, o * > *inpt, std::vector< g * > *out)
template<typename o , typename g >
void upcast (std::vector< o * > *inpt, std::vector< g * > *out)
template<typename g >
void get_leptonics (std::map< std::string, g * > inpt, std::vector< particle_template * > *out)
template<typename g , typename j >
bool contains (std::vector< g * > *inpt, j *pcheck)
Public Member Functions inherited from tools
tools ()
Constructor for the tools class.
~tools ()
Destructor for the tools class.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Public Attributes
int num_device = 1
double masstop = 172.62*1000
double massw = 80.385*1000
Public Attributes inherited from selection_template
cproperty< std::string, selection_template > name
cproperty< std::string, selection_template > hash
cproperty< std::string, selection_template > tree
cproperty< double, selection_template > weight
cproperty< long, selection_template > index
meta * meta_data = nullptr
std::string filename = ""
event_t data
int threadIdx = -1
std::map< std::string, std::map< std::string, float > > passed_weights = {}
std::map< std::string, meta_t > matched_meta = {}
Additional Inherited Members
Static Public Member Functions inherited from selection_template
static void set_name (std::string *, selection_template *)
static void get_name (std::string *, selection_template *)
static void set_hash (std::string *, selection_template *)
static void get_hash (std::string *, selection_template *)
static void get_tree (std::string *, selection_template *)
static void set_weight (double *, selection_template *)
static void get_weight (double *, selection_template *)
static void set_index (long *, selection_template *)
Static Public Member Functions inherited from tools
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Detailed Description
Definition at line 36 of file validation.h.
Constructor & Destructor Documentation
validation()
validation::validation ()
Definition at line 12 of file validation.cxx.
 {this -> name = "validation";}
References selection_template::name.
Referenced by clone(), and validation.figures::validation().
~validation()
validation::~validation () override
Definition at line 18 of file validation.cxx.
 {this -> safe_delete(&this -> storage);}
References selection_template::safe_delete().
Member Function Documentation
clone()
selection_template * validation::clone () override virtual
Reimplemented from selection_template.
Definition at line 13 of file validation.cxx.
{
     validation* vl = new validation();
     vl -> num_device = this -> num_device;
     return vl;
 }
References num_device, and validation().
merge()
void validation::merge (selection_template * sl) override virtual
Reimplemented from selection_template.
Definition at line 20 of file validation.cxx.
{
     validation* slt = (validation*)sl;
     for (size_t x(0); x < slt -> storage.size(); ++x){
         packet_t* tc = slt -> storage[x];
         this -> write(&tc -> objects, tc -> name, particle_enum::pmu );
         this -> write(&tc -> objects, tc -> name, particle_enum::pdgid);
         this -> write(&tc -> static_nu1 , tc -> name + "_static_nu1" , particle_enum::pmu);
         this -> write(&tc -> static_nu2 , tc -> name + "_static_nu2" , particle_enum::pmu);
         this -> write(&tc -> dynamic_nu1, tc -> name + "_dynamic_nu1", particle_enum::pmu);
         this -> write(&tc -> dynamic_nu2, tc -> name + "_dynamic_nu2", particle_enum::pmu);
         this -> write(&tc -> static_distances , tc -> name + "_static_dst" );
         this -> write(&tc -> dynamic_distances, tc -> name + "_dynamic_dst");
         if (x){continue;}
         this -> write(&tc -> met, "met");
         this -> write(&tc -> phi, "phi");
     }
 }
References selection_template::name, pdgid, pmu, main::sl, selection_template::write(), and main::x.
reconstruction()
void validation::reconstruction (packet_t * data)
Definition at line 58 of file validation.cxx.
{
     if (data -> bquarks.size() != 2){return;}
     std::vector<double> mass_tops, mass_boson;
     std::vector<std::pair<neutrino*, neutrino*>> nux;
     for (size_t x(0); x <  2; ++x){
         std::vector<particle_template*> top;
         top.push_back(data -> bquarks[x]);
         top.push_back(data -> leptons[x]);
         top.push_back(data -> neutrino[x]);
         particle_template* ptr_t = nullptr;
         this -> sum(&top, &ptr_t);
         std::vector<particle_template*> wboson;
         wboson.push_back(data -> leptons[x]);
         wboson.push_back(data -> neutrino[x]);
         particle_template* ptr_w = nullptr;
         this -> sum(&wboson, &ptr_w);
         mass_tops.push_back(ptr_t -> mass);
         mass_boson.push_back(ptr_w -> mass);
     }
     nux = pyc::nusol::NuNu(
             std::vector<particle_template*>({data -> bquarks[0]}), std::vector<particle_template*>({data -> bquarks[1]}),
             std::vector<particle_template*>({data -> leptons[0]}), std::vector<particle_template*>({data -> leptons[1]}),
             std::vector<double>({data -> met}), std::vector<double>({data -> phi}),
             std::vector<std::vector<double>>({{mass_tops[0], mass_boson[0]}}),
             std::vector<std::vector<double>>({{mass_tops[1], mass_boson[1]}}),
             data -> device, data -> null, data -> step, data -> tolerance, data -> timeout
     );
     for (size_t x(0); x < nux.size(); ++x){
         data -> dynamic_nu1.push_back(std::get<0>(nux[x]));
         data -> dynamic_nu2.push_back(std::get<1>(nux[x]));
         data -> dynamic_distances.push_back(std::get<0>(nux[x]) -> min);
     }
     nux = pyc::nusol::NuNu(
             std::vector<particle_template*>({data -> bquarks[0]}), std::vector<particle_template*>({data -> bquarks[1]}),
             std::vector<particle_template*>({data -> leptons[0]}), std::vector<particle_template*>({data -> leptons[1]}),
             std::vector<double>({data -> met}), std::vector<double>({data -> phi}),
             std::vector<std::vector<double>>({{this -> masstop, this -> massw}}),
             std::vector<std::vector<double>>({{this -> masstop, this -> massw}}),
             data -> device, data -> null, data -> step, data -> tolerance, data -> timeout
     );
     for (size_t x(0); x < nux.size(); ++x){
         data -> static_nu1.push_back(std::get<0>(nux[x]));
         data -> static_nu2.push_back(std::get<1>(nux[x]));
         data -> static_distances.push_back(std::get<0>(nux[x]) -> min);
     }
 }
References selection_template::data, main::device, mass, masstop, massw, pyc::nusol::NuNu(), selection_template::sum(), helper::vector(), and main::x.
Referenced by strategy().
selection()
bool validation::selection (event_template * ev) override virtual
Reimplemented from selection_template.
Definition at line 40 of file validation.cxx.
{
     bsm_4tops* evn = (bsm_4tops*)ev;
     std::vector<top*> tops = this -> upcast<top>(&evn -> Tops);
     int num_leps = 0;
     for (size_t x(0); x < tops.size(); ++x){
         std::map<std::string, particle_template*> ch = tops[x] -> children;
         std::vector<top_children*> ch_ = this -> upcast<top_children>(&ch);
         for (size_t i(0); i < ch_.size(); ++i){
             bool lp = ch_[i] -> is_lep;
             if (!lp){continue;}
             num_leps += lp;
             break;
         }
     }
     return num_leps == 2; //  || num_leps == 1;
 }
References main::ev, and test_normalization::evn.
strategy()
bool validation::strategy (event_template * ev) override virtual
Reimplemented from selection_template.
Definition at line 136 of file validation.cxx.
{
     bsm_4tops* evn = (bsm_4tops*)ev;
     std::vector<particle_template*> dleps = {};
     merge_data(&dleps, &evn -> Electrons);
     merge_data(&dleps, &evn -> Muons);
     packet_t* pkt_tc = this -> build_packet(evn, "top_children");
     packet_t* pkt_tj = this -> build_packet(evn, "truthjet"    );
     packet_t* pkt_jc = this -> build_packet(evn, "jetchildren" );
     packet_t* pkt_jl = this -> build_packet(evn, "jetleptons"  );
     std::vector<top*> tops = this -> upcast<top>(&evn -> Tops);
     for (size_t x(0); x < tops.size(); ++x){
         this -> update_state(nullptr); // reset the global matching
         top* tpx = tops[x];
         std::vector<particle_template*> ch = this -> vectorize(&tpx -> children);
         for (size_t c(0); c < ch.size(); ++c){
             if (ch[c] -> is_b){this -> b_qrk = ch[c];}
             if (ch[c] -> is_lep){this -> lepton = ch[c];}
             if (ch[c] -> is_nu){this -> nu_tru = ch[c];}
         }
         this -> update_state(pkt_tc);
         this -> b_qrk  = nullptr;
         for (size_t c(0); c < tpx -> TruthJets.size(); ++c){
             truthjet* ptr = tpx -> TruthJets[c];
             if (!ptr -> is_b){continue;}
             this -> b_qrk = ptr; break;
         }
         this -> update_state(pkt_tj);
         this -> b_qrk  = nullptr;
         for (size_t c(0); c < tpx -> Jets.size(); ++c){
             jet* ptr = tpx -> Jets[c];
             if (!ptr -> is_b){continue;}
             this -> b_qrk = ptr; break;
         }
         this -> update_state(pkt_jc);
         this -> lepton = nullptr;
         for (size_t c(0); c < dleps.size(); ++c){
             std::map<std::string, particle_template*> pr = dleps[c] -> parents;
             for (size_t j(0); j < ch.size(); ++j){
                 if (!ch[j] -> is_lep){continue;}
                 if (!pr.count(ch[j] -> hash)){continue;}
                 this -> lepton = dleps[c]; break;
             }
             if (!this -> lepton){continue;}
             break;
         }
         this -> update_state(pkt_jl);
     }
     this -> reconstruction(pkt_tc);
     this -> reconstruction(pkt_tj);
     this -> reconstruction(pkt_jc);
     this -> reconstruction(pkt_jl);
     return true;
 }
References c, main::ev, test_normalization::evn, selection_template::hash, is_b, is_lep, is_nu, merge_data(), main::parents, reconstruction(), update_state(), selection_template::vectorize(), and main::x.
update_state()
void validation::update_state (packet_t * data)
Definition at line 118 of file validation.cxx.
{
     if (!data){
         this -> b_qrk  = nullptr;
         this -> lepton = nullptr;
         this -> nu_tru = nullptr;
     }
     if (!this -> nu_tru || !this -> b_qrk || !this -> lepton){return;}
     data -> bquarks.push_back(this -> b_qrk);
     data -> leptons.push_back(this -> lepton);
     data -> neutrino.push_back(this -> nu_tru);
     data -> objects.push_back(this -> b_qrk);
     data -> objects.push_back(this -> lepton);
     if (data -> name != "top_children"){return;}
     data -> objects.push_back(this -> nu_tru);
 }
References selection_template::data, and selection_template::name.
Referenced by strategy().
Member Data Documentation
masstop
double validation::masstop = 172.62*1000
Definition at line 50 of file validation.h.
Referenced by reconstruction().
massw
double validation::massw = 80.385*1000
Definition at line 51 of file validation.h.
Referenced by reconstruction().
num_device
int validation::num_device = 1
Definition at line 49 of file validation.h.
Referenced by clone().
The documentation for this class was generated from the following files:
validation.h
validation.cxx