AnalysisG: model_template Class Reference
model_template Class Reference
Base template class for machine learning models.
#include <model_template.h>
Public Member Functions
model_template ()
Constructor for the model_template class.
virtual ~model_template ()
Virtual destructor for the model_template class.
virtual model_template * clone ()
Creates a clone of the model template.
void register_module (torch::nn::Sequential *data)
Registers a PyTorch sequential module with the model.
void register_module (torch::nn::Sequential *data, mlp_init method)
Registers a PyTorch sequential module with the model and initializes its weights.
virtual void forward (graph_t *data)
Virtual forward pass method for a single graph.
virtual void forward (graph_t *data, bool train)
Forward pass for a single graph with training mode flag.
virtual void forward (std::vector< graph_t * > data, bool train)
Forward pass for multiple graphs with training mode flag.
torch::Tensor * assign_features (std::string inpt, graph_enum type, graph_t *data)
Assigns features from a graph to tensors based on feature name and type.
torch::Tensor * assign_features (std::string inpt, graph_enum type, std::vector< graph_t * > *data)
Assigns features from multiple graphs to tensors based on feature name and type.
void flush_outputs ()
Clears all output tensors, freeing memory.
Public Member Functions inherited from tools
tools ()
Constructor for the tools class.
~tools ()
Destructor for the tools class.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Public Member Functions inherited from notification
notification ()
Constructor for the notification class.
~notification ()
Destructor for the notification class.
void set_prefix (std::string prefix)
Sets the prefix used in log messages from this instance.
std::string get_prefix ()
Returns the prefix currently used in log messages.
void Info (std::string msg, bool newline=true)
Outputs an info message.
void Warning (std::string msg, bool newline=true)
Outputs a warning message.
void Error (std::string msg, bool newline=true)
Outputs an error message.
void Debug (std::string msg, bool newline=true)
Outputs a debug message (only in debug mode).
void Message (std::string msg, std::string tag="", bool newline=true)
Outputs a message with custom formatting.
void set_debug_mode (bool dbg)
Enables or disables debug mode.
bool get_debug_mode ()
Returns the current status of debug mode.
void set_suppress_warning (bool sw)
Sets whether warnings should be suppressed.
bool get_suppress_warning ()
Returns the current warning suppression status.
void set_suppress_info (bool si)
Sets whether info messages should be suppressed.
bool get_suppress_info ()
Returns the current info message suppression status.
Static Public Member Functions
static void set_name (std::string *name, model_template *model)
Static setter for the name property.
static void get_name (std::string *name, model_template *model)
Static getter for the name property.
static void set_device (std::string *dev, model_template *model)
Static setter for the device property.
static void set_dev_index (int *dev_idx, model_template *model)
Static setter for the device_index property.
static void get_dev_index (int *dev_idx, model_template *model)
Static getter for the device_index property.
static void set_input_features (std::vector< std::string > *inpt, std::map< std::string, torch::Tensor * > *in_fx)
Sets input features for a specific feature map.
static void set_output_features (std::vector< std::string > *inpt, std::map< std::string, torch::Tensor * > *in_fx)
Sets output features for a specific feature map.
Static Public Member Functions inherited from tools
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Public Attributes
cproperty< std::string, model_template > name
Property: The name of this model.
cproperty< std::string, model_template > device
Property: The device this model runs on (e.g., "cpu", "cuda:0").
cproperty< int, model_template > device_index
Property: The numerical index of the device this model runs on.
cproperty< std::vector< std::string >, std::map< std::string, torch::Tensor * > > i_graph
Property: Graph-level input features.
cproperty< std::vector< std::string >, std::map< std::string, torch::Tensor * > > i_node
Property: Node-level input features.
cproperty< std::vector< std::string >, std::map< std::string, torch::Tensor * > > i_edge
Property: Edge-level input features.
cproperty< std::vector< std::string >, std::map< std::string, torch::Tensor * > > o_graph
Property: Graph-level output features.
cproperty< std::vector< std::string >, std::map< std::string, torch::Tensor * > > o_node
Property: Node-level output features.
cproperty< std::vector< std::string >, std::map< std::string, torch::Tensor * > > o_edge
Property: Edge-level output features.
std::map< std::string, torch::Tensor * > m_i_graph
Map of graph-level input features to tensors.
std::map< std::string, torch::Tensor * > m_i_node
Map of node-level input features to tensors.
std::map< std::string, torch::Tensor * > m_i_edge
Map of edge-level input features to tensors.
std::map< std::string, torch::Tensor * > m_o_graph
Map of graph-level output features to tensors.
std::map< std::string, torch::Tensor * > m_o_node
Map of node-level output features to tensors.
std::map< std::string, torch::Tensor * > m_o_edge
Map of edge-level output features to tensors.
torch::TensorOptions * m_option = nullptr
Pointer to tensor options for configuring tensor creation.
std::vector< torch::nn::Sequential * > m_data
Vector of pointers to sequential modules in the model.
lossfx * m_loss = nullptr
Pointer to the loss function manager.
std::string model_checkpoint_path
Path for saving/loading model checkpoints.
Additional Inherited Members
Protected Attributes inherited from notification
std::string prefix = ""
Prefix used in log messages from this instance. Initialized as empty string.
bool debug_mode = false
Flag indicating whether debug mode is enabled. Initialized as false.
bool suppress_warnings = false
Flag indicating whether warnings are suppressed. Initialized as false.
bool suppress_info = false
Flag indicating whether info messages are suppressed. Initialized as false.
Detailed Description
Base template class for machine learning models.
Inherits from tools and notification to provide utility functions and logging capabilities. This class serves as a foundation for implementing various neural network architectures, with particular focus on graph neural networks. It provides mechanisms for managing model parameters, feature assignment, forward propagation, and more.
Definition at line 46 of file model_template.h.
Constructor & Destructor Documentation
model_template()
model_template::model_template ()
Constructor for the model_template class.
Initializes a new model template with default settings.
Sets up property bindings for input and output features, device settings, and initializes the loss function manager. Each property is bound to its appropriate setter and getter methods.
Definition at line 18 of file model_template.cxx.
{
     // Configure input feature properties
     this -> i_graph.set_setter(this -> set_input_features);
     this -> i_graph.set_object(&this -> m_i_graph);
     this -> i_node.set_setter(this -> set_input_features);
     this -> i_node.set_object(&this -> m_i_node);
     this -> i_edge.set_setter(this -> set_input_features);
     this -> i_edge.set_object(&this -> m_i_edge);
     // Configure output feature properties
     this -> o_graph.set_setter(this -> set_output_features);
     this -> o_graph.set_object(&this -> m_o_graph);
     this -> o_node.set_setter(this -> set_output_features);
     this -> o_node.set_object(&this -> m_o_node);
     this -> o_edge.set_setter(this -> set_output_features);
     this -> o_edge.set_object(&this -> m_o_edge);
     // Configure device property
     this -> device.set_setter(this -> set_device);
     this -> device.set_object(this);
     // Configure name property
     this -> name.set_setter(this -> set_name);
     this -> name.set_getter(this -> get_name);
     this -> name.set_object(this);
     // Configure device index property
     this -> device_index.set_setter(this -> set_dev_index);
     this -> device_index.set_getter(this -> get_dev_index);
     this -> device_index.set_object(this);
     // Initialize loss function manager
     this -> m_loss = new lossfx();
 }
References device, device_index, get_dev_index(), get_name(), i_edge, i_graph, i_node, m_i_edge, m_i_graph, m_i_node, m_loss, m_o_edge, m_o_graph, m_o_node, name, o_edge, o_graph, o_node, set_dev_index(), set_device(), cproperty< T, G >::set_getter(), set_input_features(), set_name(), cproperty< T, G >::set_object(), set_output_features(), and cproperty< T, G >::set_setter().
~model_template()
model_template::~model_template () virtual
Virtual destructor for the model_template class.
Destructor for the model_template class.
Ensures proper cleanup of resources, including module containers and outputs.
Cleans up all resources used by the model, including registered modules, output tensors, and the loss function manager.
Definition at line 102 of file model_template.cxx.
{
     for (size_t x(0); x < this -> m_data.size(); ++x){delete this -> m_data[x];}
     this -> flush_outputs();
     this -> m_data.clear();
     delete this -> m_loss;
 }
References flush_outputs(), m_data, m_loss, and main::x.
Member Function Documentation
assign_features() [1/2]
torch::Tensor * model_template::assign_features (std::string inpt, graph_enum type, graph_t * data)
Assigns features from a graph to tensors based on feature name and type.
Parameters
inpt Feature name to assign.
type Type of graph component (node, edge, or graph).
data Pointer to the graph_t structure containing the features.
Returns
Pointer to the resulting tensor containing the assigned features.
Parameters
inpt Feature name to assign.
type Type of graph component (node, edge, or graph).
data Pointer to the graph_t structure containing the features.
Returns
Pointer to the resulting tensor containing the assigned features.
Extracts specified features from the graph and converts them to PyTorch tensors.
Definition at line 118 of file model_template.cxx.
{
     torch::Tensor* tn = nullptr;
     switch (type){
         case graph_enum::data_graph:  tn = data -> get_data_graph( inpt, this); this -> m_i_graph[inpt] = tn; break;
         case graph_enum::data_node:   tn = data -> get_data_node(  inpt, this); this -> m_i_node[inpt]  = tn; break;
         case graph_enum::data_edge:   tn = data -> get_data_edge(  inpt, this); this -> m_i_edge[inpt]  = tn; break;
         case graph_enum::truth_graph: tn = data -> get_truth_graph(inpt, this); std::get<0>(this -> m_o_graph[inpt]) = tn; break;
         case graph_enum::truth_node:  tn = data -> get_truth_node( inpt, this); std::get<0>(this -> m_o_node[inpt])  = tn; break;
         case graph_enum::truth_edge:  tn = data -> get_truth_edge( inpt, this); std::get<0>(this -> m_o_edge[inpt])  = tn; break;
         default: return tn;
     }
     return tn;
 }
References simply_plot::data, data_edge, data_graph, data_node, m_i_edge, m_i_graph, m_i_node, m_o_edge, m_o_graph, m_o_node, truth_edge, truth_graph, and truth_node.
assign_features() [2/2]
torch::Tensor * model_template::assign_features (std::string inpt, graph_enum type, std::vector< graph_t * > * data)
Assigns features from multiple graphs to tensors based on feature name and type.
Parameters
inpt Feature name to assign.
type Type of graph component (node, edge, or graph).
data Pointer to a vector of graph_t structures containing the features.
Returns
Pointer to the resulting tensor containing the assigned features.
Parameters
inpt Feature name to assign.
type Type of graph component (node, edge, or graph).
data Pointer to a vector of graph_t structures containing the features.
Returns
Pointer to the resulting tensor containing the assigned features.
Extracts specified features from multiple graphs and converts them to batched PyTorch tensors.
Definition at line 141 of file model_template.cxx.
{
     auto g_data  = [this](graph_t* d, std::string key) -> torch::Tensor* {return d -> get_data_graph(key, this);};
     auto n_data  = [this](graph_t* d, std::string key) -> torch::Tensor* {return d -> get_data_node(key, this);};
     auto e_data  = [this](graph_t* d, std::string key) -> torch::Tensor* {return d -> get_data_edge(key, this);};
     auto g_truth = [this](graph_t* d, std::string key) -> torch::Tensor* {return d -> get_truth_graph(key, this);};
     auto n_truth = [this](graph_t* d, std::string key) -> torch::Tensor* {return d -> get_truth_node(key, this);};
     auto e_truth = [this](graph_t* d, std::string key) -> torch::Tensor* {return d -> get_truth_edge(key, this);};
     auto lamb_d  = [this](
             std::function<torch::Tensor*(graph_t*, std::string)> fx,
             std::vector<graph_t*>* merge, std::string key) -> torch::Tensor*
     {
         std::vector<torch::Tensor> arr;
         for (size_t x(0); x < merge -> size(); ++x){
             torch::Tensor* val = fx((*merge)[x], key);
             if (!val){continue;}
             arr.push_back(*val);
         }
         if (!arr.size()){return nullptr;}
         return new torch::Tensor(torch::cat(arr, {0}));
     };
     torch::Tensor* tn = nullptr;
     switch (type){
         case graph_enum::data_graph:  tn = lamb_d(g_data,  data, inpt); this -> m_i_graph[inpt] = tn; return tn;
         case graph_enum::data_node:   tn = lamb_d(n_data,  data, inpt); this -> m_i_node[inpt]  = tn; return tn;
         case graph_enum::data_edge:   tn = lamb_d(e_data,  data, inpt); this -> m_i_edge[inpt]  = tn; return tn;
         case graph_enum::truth_graph: tn = lamb_d(g_truth, data, inpt); std::get<0>(this -> m_o_graph[inpt]) = tn; return tn;
         case graph_enum::truth_node:  tn = lamb_d(n_truth, data, inpt); std::get<0>(this -> m_o_node[inpt])  = tn; return tn;
         case graph_enum::truth_edge:  tn = lamb_d(e_truth, data, inpt); std::get<0>(this -> m_o_edge[inpt])  = tn; return tn;
         default: return tn;
     }
     return tn;
 }
References d, simply_plot::data, data_edge, data_graph, data_node, main::fx, m_i_edge, m_i_graph, m_i_node, m_o_edge, m_o_graph, m_o_node, merge(), truth_edge, truth_graph, truth_node, and main::x.
clone()
model_template * model_template::clone () virtual
Creates a clone of the model template.
Creates and returns a clone of this model template.
Returns
A pointer to a new model_template instance that is a copy of this one.
A new model_template instance.
Reimplemented in grift, and recursivegraphneuralnetwork.
Definition at line 27 of file model_configuration.cxx.
{
     model_template* mo = this -> clone();
     model_settings_t mds;
     this -> clone_settings(&mds);
     mo -> import_settings(&mds);
     return mo;
 }
flush_outputs()
void model_template::flush_outputs ()
Clears all output tensors, freeing memory.
Used to reset the model's output state between forward passes.
Iterates through all output feature maps and deletes their tensor contents.
Definition at line 248 of file model_template.cxx.
{
     auto lambda = [](std::map<std::string, torch::Tensor*>* data){
         std::map<std::string, torch::Tensor*>::iterator itr = data -> begin();
         for (; itr != data -> end(); ++itr){
             if (!itr -> second){continue;}
             delete itr -> second;
             itr -> second = nullptr;
         }
     };
     auto lamb = [](std::map<std::string, std::tuple<torch::Tensor*, loss_enum>>* inpx){
         std::map<std::string, std::tuple<torch::Tensor*, loss_enum>>::iterator itx = inpx -> begin();
         for (; itx != inpx -> end(); ++itx){
             delete std::get<0>(itx -> second);
             std::get<0>(itx -> second) = nullptr;
         }
     };
     lambda(&this -> m_p_graph);
     lambda(&this -> m_p_node);
     lambda(&this -> m_p_edge);
     lambda(&this -> m_p_undef);
     this -> m_p_loss.clear();
     if (!this -> m_batched){return;}
     delete this -> edge_index;
     this -> edge_index = nullptr;
     lambda(&this -> m_i_graph);
     lambda(&this -> m_i_node);
     lambda(&this -> m_i_edge);
     lamb(&this -> m_o_graph);
     lamb(&this -> m_o_node);
     lamb(&this -> m_o_edge);
 }
References simply_plot::data, edge_index, end(), m_i_edge, m_i_graph, m_i_node, m_o_edge, m_o_graph, and m_o_node.
Referenced by forward(), and ~model_template().
forward() [1/3]
void model_template::forward (graph_t * data) virtual
Virtual forward pass method for a single graph.
Default implementation of the forward pass for a single graph.
Parameters
data Pointer to the graph_t structure containing input data.
This method should be overridden by derived classes to implement the forward pass logic.
Parameters
data Pointer to the graph_t structure containing input data.
This is a placeholder that derived classes should override with their specific implementation.
Reimplemented in grift, and recursivegraphneuralnetwork.
Definition at line 94 of file model_template.cxx.
 {}
Referenced by forward().
forward() [2/3]
void model_template::forward (graph_t * data, bool train) virtual
Forward pass for a single graph with training mode flag.
Performs forward pass on a single graph, with optional training mode.
Parameters
data Pointer to the graph_t structure containing input data.
train Flag indicating if the model is in training mode (true) or evaluation mode (false).
Executes the model's forward pass on a single graph, optionally in training mode.
Parameters
data Pointer to the graph_t structure containing input data.
train Flag indicating if the model is in training mode (true) or evaluation mode (false).
Sets the model's modules to training or evaluation mode as specified, then performs the forward pass.
Definition at line 182 of file model_template.cxx.
{
     this -> flush_outputs();
     this -> m_batched = false;
     this -> edge_index = data -> get_edge_index(this);
     if (this -> m_i_graph.size()){this -> assign(&this -> m_i_graph, graph_enum::data_graph, data);}
     if (this -> m_i_node.size()){ this -> assign(&this -> m_i_node,  graph_enum::data_node, data);}
     if (this -> m_i_edge.size()){ this -> assign(&this -> m_i_edge,  graph_enum::data_edge, data);}
     if (this -> m_o_graph.size()){this -> assign(&this -> m_o_graph, graph_enum::truth_graph, data);}
     if (this -> m_o_node.size()){ this -> assign(&this -> m_o_node,  graph_enum::truth_node, data);}
     if (this -> m_o_edge.size()){ this -> assign(&this -> m_o_edge,  graph_enum::truth_edge, data);}
     this -> forward(data);
     this -> train_sequence(train);
 }
References simply_plot::data, data_edge, data_graph, data_node, edge_index, flush_outputs(), forward(), m_i_edge, m_i_graph, m_i_node, m_o_edge, m_o_graph, m_o_node, truth_edge, truth_graph, and truth_node.
forward() [3/3]
void model_template::forward (std::vector< graph_t * > data, bool train) virtual
Forward pass for multiple graphs with training mode flag.
Performs forward pass on multiple graphs, with optional training mode.
Parameters
data Vector of pointers to graph_t structures containing input data.
train Flag indicating if the model is in training mode (true) or evaluation mode (false).
Executes the model's forward pass on multiple graphs, optionally in training mode.
Parameters
data Vector of pointers to graph_t structures containing input data.
train Flag indicating if the model is in training mode (true) or evaluation mode (false).
Sets the model's modules to training or evaluation mode as specified, then performs the forward pass on each graph in the input vector.
Definition at line 207 of file model_template.cxx.
{
     this -> flush_outputs();
     this -> m_batched = true;
     if (this -> m_i_graph.size()){this -> assign(&this -> m_i_graph, graph_enum::data_graph, &data);}
     if (this -> m_i_node.size()){ this -> assign(&this -> m_i_node,  graph_enum::data_node, &data);}
     if (this -> m_i_edge.size()){ this -> assign(&this -> m_i_edge,  graph_enum::data_edge, &data);}
     if (this -> m_o_graph.size()){this -> assign(&this -> m_o_graph, graph_enum::truth_graph, &data);}
     if (this -> m_o_node.size()){ this -> assign(&this -> m_o_node,  graph_enum::truth_node, &data);}
     if (this -> m_o_edge.size()){ this -> assign(&this -> m_o_edge,  graph_enum::truth_edge, &data);}
     int offset_nodes = 0;
     std::vector<torch::Tensor> _edge_index;
     for (size_t x(0); x < data.size(); ++x){
         graph_t* gr = data[x];
         if (!_edge_index.size()){_edge_index.push_back(*gr -> get_edge_index(this));}
         else {_edge_index.push_back((*gr -> get_edge_index(this)) + offset_nodes);}
         this -> forward(gr);
         offset_nodes += gr -> num_nodes;
     }
     this -> edge_index = new torch::Tensor(torch::cat(_edge_index, {-1}));
     this -> train_sequence(train);
 }
References simply_plot::data, data_edge, data_graph, data_node, edge_index, flush_outputs(), forward(), test_evaluation::gr, m_i_edge, m_i_graph, m_i_node, m_o_edge, m_o_graph, m_o_node, truth_edge, truth_graph, truth_node, and main::x.
get_dev_index()
void model_template::get_dev_index (int * dev_idx, model_template * model) static
Static getter for the device_index property.
Parameters
[out] dev_idx Pointer to an integer to store the device index.
[in] model Pointer to the model_template instance.
Definition at line 84 of file model_configuration.cxx.
{
     if (!md -> m_option){*nx = -2; return;}
     if (md -> m_device_idx == -2){md -> m_device_idx = md -> m_option -> device().index();}
     *nx = md -> m_device_idx;
 }
References device, m_option, and test_ssml_mc20::md.
Referenced by model_template().
get_name()
void model_template::get_name (std::string * name, model_template * model) static
Static getter for the name property.
Parameters
[out] name Pointer to a string to store the name.
[in] model Pointer to the model_template instance.
Definition at line 61 of file model_configuration.cxx.
 {*nx = md -> m_name;}
References test_ssml_mc20::md.
Referenced by model_template().
register_module() [1/2]
void model_template::register_module (torch::nn::Sequential * data)
Registers a PyTorch sequential module with the model.
Parameters
data Pointer to the sequential module to register.
Adds the module to the model's collection and places it on the appropriate device.
Parameters
data Pointer to the sequential module to register.
If a device option is set, the module is transferred to that device before registration.
Definition at line 69 of file model_template.cxx.
{
     if (this -> m_option){(*data) -> to(this -> m_option -> device());}
     this -> m_data.push_back(data);
 }
References simply_plot::data, device, m_data, and m_option.
Referenced by grift::grift(), and recursivegraphneuralnetwork::recursivegraphneuralnetwork().
register_module() [2/2]
void model_template::register_module (torch::nn::Sequential * data, mlp_init method)
Registers a PyTorch sequential module with the model and initializes its weights.
Parameters
data Pointer to the sequential module to register.
method The initialization method to use for the module's weights.
Adds the module to the model's collection, places it on the appropriate device, and initializes its weights according to the specified method.
Parameters
data Pointer to the sequential module to register.
method The initialization method to use for the module's weights.
If a device option is set, the module is transferred to that device before registration. The module's weights are initialized according to the specified method.
Definition at line 82 of file model_template.cxx.
{
     if (this -> m_option){(*data) -> to(this -> m_option -> device());}
     this -> m_loss -> weight_init(data, method);
     this -> m_data.push_back(data);
 }
References simply_plot::data, device, m_data, m_loss, m_option, and main::method.
set_dev_index()
void model_template::set_dev_index (int * dev_idx, model_template * model) static
Static setter for the device_index property.
Parameters
[in] dev_idx Pointer to an integer containing the device index.
[in] model Pointer to the model_template instance.
Definition at line 89 of file model_configuration.cxx.
 {}
Referenced by model_template().
set_device()
void model_template::set_device (std::string * dev, model_template * model) static
Static setter for the device property.
Parameters
[in] dev Pointer to a string containing the device name.
[in] model Pointer to the model_template instance.
Definition at line 63 of file model_configuration.cxx.
{
     if (md -> m_option){delete md -> m_option; md -> m_option = nullptr;}
     int device_n = -1;
     c10::DeviceType device_enum;
     std::string device = md -> lower(dev);
     if (md -> has_string(&device, "cuda:")){
         device_enum = c10::kCUDA;
         device_n = std::stoi(md -> split(device, ":")[1]);
     }
     else if (md -> has_string(&device, "cuda")){device_enum = c10::kCUDA; device_n = 0;}
     else {device_enum = c10::kCPU;}
     switch(device_enum){
         case c10::kCPU:  md -> m_option = new torch::TensorOptions(device_enum); break;
         case c10::kCUDA: md -> m_option = new torch::TensorOptions(device_enum, device_n); break;
         default: md -> m_option = new torch::TensorOptions(device_enum); break;
     }
     for (size_t x(0); x < md -> m_data.size(); ++x){(*md -> m_data[x]) -> to(md -> m_option -> device(), true);}
 }
References main::dev, device, tools::has_string(), m_data, m_option, test_ssml_mc20::md, tools::split(), and main::x.
Referenced by model_template().
set_input_features()
void model_template::set_input_features (std::vector< std::string > * inpt, std::map< std::string, torch::Tensor * > * in_fx) static
Sets input features for a specific feature map.
Parameters
inpt Pointer to a vector of strings containing feature names.
in_fx Pointer to the feature map to set.
inpt Pointer to a vector of strings containing feature names.
in_fx Pointer to the feature map to set.
Initializes map entries for each feature name in the input vector.
Definition at line 239 of file model_template.cxx.
{
     for (size_t x(0); x < inpt -> size(); ++x){(*in_fx)[inpt -> at(x)] = nullptr;}
 }
References main::x.
Referenced by model_template().
set_name()
void model_template::set_name (std::string * name, model_template * model) static
Static setter for the name property.
Parameters
[in] name Pointer to a string containing the name.
[in] model Pointer to the model_template instance.
Definition at line 60 of file model_configuration.cxx.
 {md -> m_name = *nx;}
References test_ssml_mc20::md.
Referenced by model_template().
set_output_features()
void model_template::set_output_features (std::vector< std::string > * inpt, std::map< std::string, torch::Tensor * > * in_fx) static
Sets output features for a specific feature map.
Parameters
inpt Pointer to a vector of strings containing feature names.
in_fx Pointer to the feature map to set.
Definition at line 3 of file model_lossfx.cxx.
  {
     std::map<std::string, std::string>::iterator itx = inpt -> begin();
     for (; itx != inpt -> end(); ++itx){
         std::string o_fx = itx -> first;
         std::string l_fx = itx -> second;
         loss_enum loss_type = lossfx().loss_string(l_fx);
         (*out_fx)[o_fx] = {nullptr, loss_type};
     }
 }
References end(), and lossfx::loss_string().
Referenced by model_template().
Member Data Documentation
device
cproperty<std::string, model_template> model_template::device
Property: The device this model runs on (e.g., "cpu", "cuda:0").
Definition at line 148 of file model_template.h.
Referenced by get_dev_index(), loader.data::interpret(), model_template(), register_module(), and set_device().
device_index
cproperty<int, model_template> model_template::device_index
Property: The numerical index of the device this model runs on.
Definition at line 154 of file model_template.h.
Referenced by model_template().
i_edge
cproperty<std::vector<std::string>, std::map<std::string, torch::Tensor*> > model_template::i_edge
Property: Edge-level input features.
Definition at line 167 of file model_template.h.
Referenced by model_template().
i_graph
cproperty<std::vector<std::string>, std::map<std::string, torch::Tensor*> > model_template::i_graph
Property: Graph-level input features.
Definition at line 165 of file model_template.h.
Referenced by model_template().
i_node
cproperty<std::vector<std::string>, std::map<std::string, torch::Tensor*> > model_template::i_node
Property: Node-level input features.
Definition at line 166 of file model_template.h.
Referenced by model_template().
m_data
std::vector<torch::nn::Sequential*> model_template::m_data
Vector of pointers to sequential modules in the model.
Definition at line 198 of file model_template.h.
Referenced by register_module(), set_device(), and ~model_template().
m_i_edge
std::map<std::string, torch::Tensor*> model_template::m_i_edge
Map of edge-level input features to tensors.
Definition at line 191 of file model_template.h.
Referenced by assign_features(), flush_outputs(), forward(), and model_template().
m_i_graph
std::map<std::string, torch::Tensor*> model_template::m_i_graph
Map of graph-level input features to tensors.
Definition at line 189 of file model_template.h.
Referenced by assign_features(), flush_outputs(), forward(), and model_template().
m_i_node
std::map<std::string, torch::Tensor*> model_template::m_i_node
Map of node-level input features to tensors.
Definition at line 190 of file model_template.h.
Referenced by assign_features(), flush_outputs(), forward(), and model_template().
m_loss
lossfx* model_template::m_loss = nullptr
Pointer to the loss function manager.
Definition at line 199 of file model_template.h.
Referenced by model_template(), register_module(), and ~model_template().
m_o_edge
std::map<std::string, torch::Tensor*> model_template::m_o_edge
Map of edge-level output features to tensors.
Definition at line 195 of file model_template.h.
Referenced by assign_features(), flush_outputs(), forward(), and model_template().
m_o_graph
std::map<std::string, torch::Tensor*> model_template::m_o_graph
Map of graph-level output features to tensors.
Definition at line 193 of file model_template.h.
Referenced by assign_features(), flush_outputs(), forward(), and model_template().
m_o_node
std::map<std::string, torch::Tensor*> model_template::m_o_node
Map of node-level output features to tensors.
Definition at line 194 of file model_template.h.
Referenced by assign_features(), flush_outputs(), forward(), and model_template().
m_option
torch::TensorOptions* model_template::m_option = nullptr
Pointer to tensor options for configuring tensor creation.
Definition at line 197 of file model_template.h.
Referenced by get_dev_index(), register_module(), and set_device().
model_checkpoint_path
std::string model_template::model_checkpoint_path
Path for saving/loading model checkpoints.
Definition at line 201 of file model_template.h.
name
cproperty<std::string, model_template> model_template::name
Property: The name of this model.
Definition at line 138 of file model_template.h.
Referenced by model_template().
o_edge
cproperty<std::vector<std::string>, std::map<std::string, torch::Tensor*> > model_template::o_edge
Property: Edge-level output features.
Definition at line 172 of file model_template.h.
Referenced by model_template().
o_graph
cproperty<std::vector<std::string>, std::map<std::string, torch::Tensor*> > model_template::o_graph
Property: Graph-level output features.
Definition at line 170 of file model_template.h.
Referenced by model_template().
o_node
cproperty<std::vector<std::string>, std::map<std::string, torch::Tensor*> > model_template::o_node
Property: Node-level output features.
Definition at line 171 of file model_template.h.
Referenced by model_template().
The documentation for this class was generated from the following files:
model_template.h
model_configuration.cxx
model_lossfx.cxx
model_template.cxx