AnalysisG: metrics Class Reference
metrics Class Reference
#include <metrics.h>
Public Member Functions
metrics ()
~metrics ()
void dump_plots (int k)
Dumps all metric plots for a specific k-fold.
void dump_loss_plots (int k)
void dump_accuracy_plots (int k)
void dump_mass_plots (int k)
Dumps mass plots for a given k-fold.
model_report * register_model (model_template *model, int kfold)
Registers a model and initializes its metrics.
void capture (mode_enum, int kfold, int epoch, int smpl_len)
Captures metrics from the current epoch.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
void set_prefix (std::string prefix)
Sets the prefix used in log messages from this instance.
std::string get_prefix ()
Returns the prefix currently used in log messages.
void Info (std::string msg, bool newline=true)
Outputs an info message.
void Warning (std::string msg, bool newline=true)
Outputs a warning message.
void Error (std::string msg, bool newline=true)
Outputs an error message.
void Debug (std::string msg, bool newline=true)
Outputs a debug message (only in debug mode).
void Message (std::string msg, std::string tag="", bool newline=true)
Outputs a message with custom formatting.
void set_debug_mode (bool dbg)
Enables or disables debug mode.
bool get_debug_mode ()
Returns the current status of debug mode.
void set_suppress_warning (bool sw)
Sets whether warnings should be suppressed.
bool get_suppress_warning ()
Returns the current warning suppression status.
void set_suppress_info (bool si)
Sets whether info messages should be suppressed.
bool get_suppress_info ()
Returns the current info message suppression status.
Static Public Member Functions
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Public Attributes
std::string output_path
const std::vector< Color_t > colors_h
settings_t m_settings
Protected Attributes
std::string prefix = ""
Prefix used in log messages from this instance. Initialized as empty string.
bool debug_mode = false
Flag indicating whether debug mode is enabled. Initialized as false.
bool suppress_warnings = false
Flag indicating whether warnings are suppressed. Initialized as false.
bool suppress_info = false
Flag indicating whether info messages are suppressed. Initialized as false.
Private Member Functions
void build_th1f_loss (std::map< std::string, std::tuple< torch::Tensor *, loss_enum > > *type, graph_enum g_num, int kfold)
void add_th1f_loss (std::map< std::string, torch::Tensor > *type, std::map< std::string, TH1F * > *lss_type, int kfold, int smpl_len)
void build_th1f_accuracy (std::map< std::string, std::tuple< torch::Tensor *, loss_enum > > *type, graph_enum g_num, int kfold)
void add_th1f_accuracy (torch::Tensor *pred, torch::Tensor *truth, TH1F *hist, int kfold, int smpl_len)
void build_th1f_mass (std::string var_name, graph_enum typ, int kfold)
void add_th1f_mass (torch::Tensor *pmc, torch::Tensor *edge_index, torch::Tensor *truth, torch::Tensor *pred, int kfold, mode_enum mode, std::string var_name)
void generic_painter (std::vector< TGraph * > k_graphs, std::string path, std::string title, std::string xtitle, std::string ytitle, int epoch)
std::map< std::string, std::vector< TGraph * > > build_graphs (std::map< std::string, TH1F * > *train, std::map< std::string, float > *tr_, std::map< std::string, TH1F * > *valid, std::map< std::string, float > *va_, std::map< std::string, TH1F * > *eval, std::map< std::string, float > *ev_, int ep)
Private Attributes
std::map< int, analytics_t > registry = {}
Detailed Description
Definition at line 69 of file metrics.h.
Constructor & Destructor Documentation
metrics()
metrics::metrics ()
Definition at line 12 of file metrics.cxx.
~metrics()
metrics::~metrics ()
Definition at line 15 of file metrics.cxx.
References registry.
Member Function Documentation
absolute_path()
std::string tools::absolute_path (std::string path) static inherited
Converts a relative path to an absolute path.
Parameters
path The path to convert.
Returns
The absolute version of the path.
Definition at line 49 of file tools/cxx/io.cxx.
Referenced by analysis::analysis(), analysis::build_events(), io::check_root_file_paths(), and io::trigger_pcm().
add_th1f_accuracy()
void metrics::add_th1f_accuracy (torch::Tensor * pred, torch::Tensor * truth, TH1F * hist, int kfold, int smpl_len) private
Definition at line 220 of file loss_plots.cxx.
References registry, and tools::sum().
Referenced by capture().
add_th1f_loss()
void metrics::add_th1f_loss (std::map< std::string, torch::Tensor > * type, std::map< std::string, TH1F * > * lss_type, int kfold, int smpl_len) private
Definition at line 134 of file loss_plots.cxx.
References registry.
Referenced by capture().
add_th1f_mass()
void metrics::add_th1f_mass (torch::Tensor * pmc, torch::Tensor * edge_index, torch::Tensor * truth, torch::Tensor * pred, int kfold, mode_enum mode, std::string var_name) private
Definition at line 143 of file mass_plots.cxx.
References pyc::graph::edge_aggregation(), edge_index, pyc::physics::cartesian::combined::M(), pmc, and registry.
Referenced by capture().
build_graphs()
std::map< std::string, std::vector< TGraph * > > metrics::build_graphs (std::map< std::string, TH1F * > * train, std::map< std::string, float > * tr_, std::map< std::string, TH1F * > * valid, std::map< std::string, float > * va_, std::map< std::string, TH1F * > * eval, std::map< std::string, float > * ev_, int ep) private
Definition at line 46 of file loss_plots.cxx.
Referenced by dump_accuracy_plots(), and dump_loss_plots().
build_th1f_accuracy()
void metrics::build_th1f_accuracy (std::map< std::string, std::tuple< torch::Tensor *, loss_enum > > * type, graph_enum g_num, int kfold) private
Definition at line 181 of file loss_plots.cxx.
References settings_t::epochs, evaluation, m_settings, registry, settings_t::run_name, training, truth_edge, truth_graph, truth_node, and validation.
Referenced by register_model().
build_th1f_loss()
void metrics::build_th1f_loss (std::map< std::string, std::tuple< torch::Tensor *, loss_enum > > * type, graph_enum g_num, int kfold) private
Definition at line 146 of file loss_plots.cxx.
References settings_t::epochs, evaluation, m_settings, registry, settings_t::run_name, training, truth_edge, truth_graph, truth_node, and validation.
Referenced by register_model().
build_th1f_mass()
void metrics::build_th1f_mass (std::string var_name, graph_enum typ, int kfold) private
Definition at line 117 of file mass_plots.cxx.
References data_edge, evaluation, m_settings, settings_t::max_range, settings_t::nbins, registry, settings_t::run_name, training, truth_edge, and validation.
Referenced by register_model().
capture()
void metrics::capture (mode_enum mode, int kfold, int epoch, int smpl_len)
Captures metrics from the current epoch.
Parameters
mode The current mode (training or validation).
kfold The k-fold index.
epoch The current epoch number.
smpl_len The sample length.
Definition at line 63 of file metrics.cxx.
References add_th1f_accuracy(), add_th1f_loss(), add_th1f_mass(), edge_index, m_settings, pmc, pyc::transform::combined::PxPyPzE(), registry, settings_t::targets, truth_edge, truth_graph, truth_node, settings_t::var_energy, settings_t::var_eta, settings_t::var_phi, and settings_t::var_pt.
create_path()
void tools::create_path (std::string path) static inherited
Creates a directory path, including parent directories if needed.
Parameters
path The directory path to create.
Definition at line 6 of file tools/cxx/io.cxx.
References f, and tools::split().
Referenced by analysis::analysis(), analysis::build_inference(), plotting::build_path(), analysis::build_project(), container::compile(), dump_mass_plots(), metric_template::execute(), generic_painter(), analysis::start(), io::start(), and io::trigger_pcm().
Debug()
void notification::Debug (std::string msg, bool newline = true) inherited
Outputs a debug message (only in debug mode).
Parameters
msg The debug message to output.
newline Whether to append a newline (default: true).
delete_path()
void tools::delete_path (std::string path) static inherited
Deletes a directory path and its contents.
Parameters
path The directory path to delete.
Definition at line 22 of file tools/cxx/io.cxx.
dump_accuracy_plots()
void metrics::dump_accuracy_plots (int k)
Definition at line 229 of file loss_plots.cxx.
References build_graphs(), evaluation, generic_painter(), m_settings, settings_t::output_path, registry, training, and validation.
Referenced by dump_plots().
dump_loss_plots()
void metrics::dump_loss_plots (int k)
Definition at line 75 of file loss_plots.cxx.
References build_graphs(), evaluation, generic_painter(), m_settings, settings_t::output_path, registry, training, and validation.
Referenced by dump_plots().
dump_mass_plots()
void metrics::dump_mass_plots (int k)
Dumps mass plots for a given k-fold.
Definition at line 13 of file mass_plots.cxx.
References colors_h, tools::create_path(), evaluation, m_settings, settings_t::max_range, settings_t::nbins, training, and validation.
Referenced by dump_plots().
dump_plots()
void metrics::dump_plots (int k)
Dumps all metric plots for a specific k-fold.
Parameters
k The k-fold index.
Definition at line 119 of file metrics.cxx.
References dump_accuracy_plots(), dump_loss_plots(), dump_mass_plots(), m_settings, and settings_t::targets.
ends_with()
bool tools::ends_with (std::string * inpt, std::string val) static inherited
Checks if a string ends with a specific substring.
Parameters
inpt Pointer to the string to check.
val The substring to check for at the end.
Returns
True if the string ends with the substring, false otherwise.
Definition at line 71 of file strings.cxx.
References l.
Referenced by plotting::build_path(), io::check_root_file_paths(), dataloader::dump_graphs(), tools::ls(), meta::parse_json(), io::scan_keys(), and analysis::start().
Error()
void notification::Error (std::string msg, bool newline = true) inherited
Outputs an error message.
Parameters
msg The error message to output.
newline Whether to append a newline (default: true).
extract()
template<typename C , typename T > static void tools::extract (std::vector< T > * prop, std::vector< C * > * src, void(*)(T *, C *) get_prop) inline static inherited
Extracts a specific property from a vector of objects into a new vector.
Template Parameters
C The type of objects in the source vector.
T The type of the property to extract.
Parameters
prop Pointer to the output vector to fill with property values.
src Pointer to the source vector of objects.
get_prop Function pointer to extract the property from an object.
< Clear the properties vector.
< Reserve space for the property values.
< Loop through each object in the source vector.
< Create a default-initialized property variable.
< Call the provided function to extract the property.
< Add the property value to the output vector.
Definition at line 216 of file tools.h.
flush()
template<typename T > static void tools::flush (std::vector< T * > * inpt) inline static inherited
Empties a vector and all objects it points to.
Template Parameters
T The type of pointers in the vector.
Parameters
inpt Pointer to the vector to empty.
< Loop through all elements in the vector.
< Delete the object the pointer points to.
< Set the pointer to nullptr to avoid dangling pointers.
< Clear the vector.
Definition at line 167 of file tools.h.
Referenced by analysis::~analysis(), dataloader::~dataloader(), sampletracer::compile_objects(), and io::root_end().
generic_painter()
void metrics::generic_painter (std::vector< TGraph * > k_graphs, std::string path, std::string title, std::string xtitle, std::string ytitle, int epoch) private
Definition at line 3 of file loss_plots.cxx.
References colors_h, tools::create_path(), and tools::has_string().
Referenced by dump_accuracy_plots(), and dump_loss_plots().
get_debug_mode()
bool notification::get_debug_mode () inherited
Returns the current status of debug mode.
Returns
Boolean indicating whether debug mode is enabled (true) or disabled (false).
get_prefix()
std::string notification::get_prefix () inherited
Returns the prefix currently used in log messages.
Returns
The current prefix string.
get_suppress_info()
bool notification::get_suppress_info () inherited
Returns the current info message suppression status.
Returns
Boolean indicating whether info messages are suppressed (true) or shown (false).
get_suppress_warning()
bool notification::get_suppress_warning () inherited
Returns the current warning suppression status.
Returns
Boolean indicating whether warnings are suppressed (true) or shown (false).
has_string()
bool tools::has_string (std::string * inpt, std::string trg) static inherited
Checks if a string contains a specific substring.
Parameters
inpt Pointer to the string to check.
trg The substring to search for.
Returns
True if the substring is found, false otherwise.
Definition at line 65 of file strings.cxx.
References f.
Referenced by analysis::check_cache(), meta::compiler(), generic_painter(), dataloader::restore_graphs_(), meta::scan_sow(), model_template::set_device(), and metric_template::set_run_name().
has_value()
bool tools::has_value (std::vector< std::string > * data, std::string trg) static inherited
Checks if a vector of strings contains a specific string.
Parameters
data Pointer to the vector to search.
trg The string to search for.
Returns
True if the string is found in the vector, false otherwise.
Definition at line 77 of file strings.cxx.
Referenced by io::scan_keys().
Info()
void notification::Info (std::string msg, bool newline = true) inherited
Outputs an info message.
Parameters
msg The message to output.
newline Whether to append a newline (default: true).
is_file()
bool tools::is_file (std::string path) static inherited
Checks if a path refers to an existing file.
Parameters
path The path to check.
Returns
True if the path is a file and exists, false otherwise.
Definition at line 30 of file tools/cxx/io.cxx.
Referenced by io::check_root_file_paths(), analysis::initialize_loop(), metric_template::set_run_name(), and io::start().
ls()
std::vector< std::string > tools::ls (std::string path, std::string ext = "") static inherited
Lists files in a directory, optionally filtered by extension.
Parameters
path The directory to search.
ext File extension filter. If empty, all files are listed.
Returns
A vector of filenames in the directory.
Definition at line 35 of file tools/cxx/io.cxx.
References tools::ends_with(), and tools::split().
Referenced by analysis::analysis(), analysis::check_cache(), io::check_root_file_paths(), dataloader::restore_graphs(), and io::trigger_pcm().
Message()
void notification::Message (std::string msg, std::string tag = "", bool newline = true) inherited
Outputs a message with custom formatting.
Parameters
msg The message to output.
tag A custom tag to prepend to the message.
newline Whether to append a newline (default: true).
put()
template<typename g > static void tools::put (std::vector< g * > * out, std::vector< g * > * src, std::vector< int > * trg) inline static inherited
Fills a vector with pointers from another vector based on a selection index.
Template Parameters
g The type of objects being pointed to.
Parameters
out Pointer to the output vector to fill.
src Pointer to the source vector to select from.
trg Pointer to a vector of indices for selection.
< Clear the output vector.
< Reserve space for the output elements.
< Loop through each selected index.
< Get the object at the selected index.
< Add it to the output vector.
< Mark the object as in use.
Definition at line 197 of file tools.h.
Referenced by dataloader::get_k_train_set(), dataloader::get_k_validation_set(), and dataloader::get_test_set().
register_model()
model_report * metrics::register_model (model_template * mod, int kfold)
Registers a model and initializes its metrics.
This function creates a new model report for the given model template and k-fold index. It initializes the metrics structures and prepares histograms for loss and accuracy tracking.
Parameters
mod Pointer to the model template.
kfold The k-fold index for cross-validation.
Returns
Pointer to the model report.
Definition at line 31 of file metrics.cxx.
References build_th1f_accuracy(), build_th1f_loss(), build_th1f_mass(), data_edge, m_settings, settings_t::output_path, registry, settings_t::run_name, settings_t::targets, truth_edge, truth_graph, and truth_node.
rename()
void tools::rename (std::string start, std::string target) static inherited
Renames a file or directory.
Parameters
start The original path.
target The new path.
Definition at line 18 of file tools/cxx/io.cxx.
Referenced by dataloader::dump_graphs().
replace()
void tools::replace (std::string * in, std::string repl_str, std::string repl_with) static inherited
Replaces all occurrences of a substring in a string.
Parameters
in Pointer to the string to modify.
repl_str The substring to replace.
repl_with The replacement string.
Definition at line 5 of file strings.cxx.
Referenced by analysis::build_graphs(), analysis::check_cache(), dataloader::dump_graphs(), meta::get_campaign(), meta::parse_json(), and analysis::start().
set_debug_mode()
void notification::set_debug_mode (bool dbg) inherited
Enables or disables debug mode.
Parameters
dbg Boolean flag, set to true to enable debug messages, false to disable.
set_prefix()
void notification::set_prefix (std::string prefix) inherited
Sets the prefix used in log messages from this instance.
Parameters
prefix The string to use as a prefix for log messages.
set_suppress_info()
void notification::set_suppress_info (bool si) inherited
Sets whether info messages should be suppressed.
Parameters
si Boolean flag, set to true to suppress info messages, false to show them.
set_suppress_warning()
void notification::set_suppress_warning (bool sw) inherited
Sets whether warnings should be suppressed.
Parameters
sw Boolean flag, set to true to suppress warnings, false to show them.
split()
std::vector< std::string > tools::split (std::string inpt, std::string del) inherited
Splits a string into a vector of substrings based on a delimiter.
Parameters
inpt The input string to split.
del The delimiter.
Returns
A vector of substrings.
Definition at line 23 of file strings.cxx.
References index.
Referenced by analysis::build_events(), analysis::build_graphs(), analysis::build_inference(), event_template::build_mapping(), analysis::check_cache(), container::compile(), sampletracer::compile_objects(), meta::compiler(), tools::create_path(), dataloader::dump_graphs(), meta::hash(), tools::ls(), graph_t::meta_deserialize(), dataloader::restore_graphs_(), io::root_begin(), model_template::set_device(), metric_template::set_run_name(), metric_template::set_variables(), and analysis::start().
sum()
template<typename g > g tools::sum (std::vector< g > * inpt) inline inherited
Sums the elements of a vector.
Template Parameters
g The type of elements in the vector.
Parameters
inpt Pointer to the vector to sum.
Returns
The sum of all elements.
< Initialize the output variable.
< Return the sum.
Definition at line 183 of file tools.h.
Referenced by add_th1f_accuracy(), sampletracer::compile_objects(), particle_template::DeltaR(), graph_template::double_neutrino(), grift::forward(), recursivegraphneuralnetwork::forward(), matching::match_obj(), and grift::message().
to_string() [1/2]
std::string tools::to_string (double val) static inherited
Converts a double value to a string with standard precision.
Parameters
val The double value to convert.
Returns
The string representation of the value.
Definition at line 59 of file strings.cxx.
Referenced by dataloader::generate_kfold_set(), dataloader::generate_test_set(), particle_template::get_hash(), topefficiency::region(), dataloader::restore_dataset(), event_template::set_hash(), selection_template::set_hash(), parton::strategy(), topjets::strategy(), toptruthjets::strategy(), and parton::top_mass_contribution().
to_string() [2/2]
std::string tools::to_string (double val, int prec) static inherited
Converts a double value to a string with specified precision.
Parameters
val The double value to convert.
prec The number of decimal places to consider.
Returns
The string representation of the value.
Definition at line 91 of file strings.cxx.
trim()
std::string tools::trim (std::string s) inherited
Removes whitespace from the beginning and end of a string.
Parameters
s The string to trim.
Returns
The trimmed string.
type_name()
template<typename T > std::string tools::type_name () inline inherited
Gets the type name of a variable as a string (for debugging).
Template Parameters
T The type to get the name of.
Returns
The name of the type as a string.
< Gets the type name via RTTI.
< Returns the type name.
Definition at line 155 of file tools.h.
Referenced by event_template::build_mapping().
Warning()
void notification::Warning (std::string msg, bool newline = true) inherited
Outputs a warning message.
Parameters
msg The warning message to output.
newline Whether to append a newline (default: true).
Referenced by io::read(), io::read(), io::write(), and io::write().
Member Data Documentation
colors_h
const std::vector<Color_t> metrics::colors_h
Initial value:
= {
            kRed, kGreen, kBlue, kCyan,
            kViolet, kOrange, kCoffee, kAurora
        }
Definition at line 79 of file metrics.h.
Referenced by dump_mass_plots(), and generic_painter().
debug_mode
bool notification::debug_mode = false protected inherited
Flag indicating whether debug mode is enabled. Initialized as false.
Definition at line 127 of file notification.h.
Referenced by analysis::build_metric().
m_settings
settings_t metrics::m_settings
Definition at line 84 of file metrics.h.
Referenced by build_th1f_accuracy(), build_th1f_loss(), build_th1f_mass(), capture(), dump_accuracy_plots(), dump_loss_plots(), dump_mass_plots(), dump_plots(), and register_model().
output_path
std::string metrics::output_path
Definition at line 77 of file metrics.h.
prefix
std::string notification::prefix = "" protected inherited
Prefix used in log messages from this instance. Initialized as empty string.
Definition at line 126 of file notification.h.
Referenced by analysis::analysis(), dataloader::dataloader(), io::io(), meta::meta(), optimizer::optimizer(), and metric_template::set_name().
registry
std::map<int, analytics_t> metrics::registry = {} private
Definition at line 139 of file metrics.h.
Referenced by ~metrics(), add_th1f_accuracy(), add_th1f_loss(), add_th1f_mass(), build_th1f_accuracy(), build_th1f_loss(), build_th1f_mass(), capture(), dump_accuracy_plots(), dump_loss_plots(), and register_model().
suppress_info
bool notification::suppress_info = false protected inherited
Flag indicating whether info messages are suppressed. Initialized as false.
Definition at line 129 of file notification.h.
suppress_warnings
bool notification::suppress_warnings = false protected inherited
Flag indicating whether warnings are suppressed. Initialized as false.
Definition at line 128 of file notification.h.
The documentation for this class was generated from the following files:
metrics.h
loss_plots.cxx
mass_plots.cxx
metrics.cxx