AnalysisG: bsc_t Class Reference
bsc_t Class Reference
Basic structure class that provides type translation and buffer management.
#include <base.h>
Public Member Functions
bsc_t ()
Constructor for the bsc_t class.
~bsc_t ()
Destructor for the bsc_t class.
data_enum root_type_translate (std::string *root_str)
Translates a ROOT type string to an internal data enumeration.
std::string as_string ()
Represents the object's state as a string.
std::string scan_buffer ()
Scans and returns the current buffer content.
void flush_buffer ()
Clears the internal buffer.
Public Attributes
std::string buffer
Internal buffer for accumulating textual data.
Detailed Description
Basic structure class that provides type translation and buffer management.
This class serves as a foundation for data type handling in the framework. It provides functionality to translate ROOT types to internal enumerations, manage string buffers, and format type information as strings.
Definition at line 74 of file modules/structs/include/structs/base.h.
Constructor & Destructor Documentation
bsc_t()
bsc_t::bsc_t ()
Constructor for the bsc_t class.
Initializes a new basic structure instance with default settings.
Definition at line 59 of file structs/cxx/base.cxx.
 {}
~bsc_t()
bsc_t::~bsc_t ()
Destructor for the bsc_t class.
Cleans up resources used by the basic structure instance.
Definition at line 60 of file structs/cxx/base.cxx.
 {}
Member Function Documentation
as_string()
std::string bsc_t::as_string ()
Represents the object's state as a string.
Returns
A string representation of the object.
This method returns a human-readable string representation of the object's current state, useful for debugging or logging.
Definition at line 104 of file structs/cxx/base.cxx.
{
     switch (this -> type){
         case data_enum::vvv_ull: return "vector<vector<vector<unsigned long long>>>";
         case data_enum::vvv_ui:  return "vector<vector<vector<unsigned int>>>";
         case data_enum::vvv_d:   return "vector<vector<vector<double>>>";
         case data_enum::vvv_l:   return "vector<vector<vector<long>>>";
         case data_enum::vvv_f:   return "vector<vector<vector<float>>>";
         case data_enum::vvv_i:   return "vector<vector<vector<int>>>" ;
         case data_enum::vvv_b:   return "vector<vector<vector<bool>>>";
         case data_enum::vvv_c:   return "vector<vector<vector<char>>>";
         case data_enum::vv_ull:  return "vector<vector<unsigned long long>>";
         case data_enum::vv_ui:   return "vector<vector<unsigned int>>";
         case data_enum::vv_d:    return "vector<vector<double>>";
         case data_enum::vv_l:    return "vector<vector<long>>";
         case data_enum::vv_f:    return "vector<vector<float>>";
         case data_enum::vv_i:    return "vector<vector<int>>" ;
         case data_enum::vv_b:    return "vector<vector<bool>>";
         case data_enum::vv_c:    return "vector<vector<char>>";
         case data_enum::v_ull:   return "vector<unsigned long long>";
         case data_enum::v_ui:    return "vector<unsigned int>";
         case data_enum::v_d:     return "vector<double>";
         case data_enum::v_l:     return "vector<long>";
         case data_enum::v_f:     return "vector<float>";
         case data_enum::v_i:     return "vector<int>" ;
         case data_enum::v_b:     return "vector<bool>";
         case data_enum::v_c:     return "vector<char>";
         case data_enum::ull:     return "unsigned long long";
         case data_enum::ui:      return "unsigned int";
         case data_enum::d:       return "double";
         case data_enum::l:       return "long";
         case data_enum::f:       return "float";
         case data_enum::i:       return "int" ;
         case data_enum::b:       return "bool";
         case data_enum::c:       return "char";
         case data_enum::unset:   return "unset";
         default:                 return "undef";
     }
 }
References b, c, d, f, i, l, ui, ull, unset, v_b, v_c, v_d, v_f, v_i, v_l, v_ui, v_ull, vv_b, vv_c, vv_d, vv_f, vv_i, vv_l, vv_ui, vv_ull, vvv_b, vvv_c, vvv_d, vvv_f, vvv_i, vvv_l, vvv_ui, and vvv_ull.
flush_buffer()
void bsc_t::flush_buffer ()
Clears the internal buffer.
This method resets the internal buffer to an empty state, typically called after processing the buffer content.
Definition at line 181 of file structs/cxx/base.cxx.
{
     switch (this -> type){
         case data_enum::vvv_ull:  this -> flush_buffer(&this -> vvv_ull); return;
         case data_enum::vvv_ui:   this -> flush_buffer(&this -> vvv_ui ); return;
         case data_enum::vvv_d:    this -> flush_buffer(&this -> vvv_d  ); return;
         case data_enum::vvv_l:    this -> flush_buffer(&this -> vvv_l  ); return;
         case data_enum::vvv_f:    this -> flush_buffer(&this -> vvv_f  ); return;
         case data_enum::vvv_i:    this -> flush_buffer(&this -> vvv_i  ); return;
         case data_enum::vvv_b:    this -> flush_buffer(&this -> vvv_b  ); return;
         case data_enum::vvv_c:    this -> flush_buffer(&this -> vvv_c  ); return;
         case data_enum::vv_ull:   this -> flush_buffer(&this -> vv_ull ); return;
         case data_enum::vv_ui:    this -> flush_buffer(&this -> vv_ui  ); return;
         case data_enum::vv_d:     this -> flush_buffer(&this -> vv_d   ); return;
         case data_enum::vv_l:     this -> flush_buffer(&this -> vv_l   ); return;
         case data_enum::vv_f:     this -> flush_buffer(&this -> vv_f   ); return;
         case data_enum::vv_i:     this -> flush_buffer(&this -> vv_i   ); return;
         case data_enum::vv_b:     this -> flush_buffer(&this -> vv_b   ); return;
         case data_enum::vv_c:     this -> flush_buffer(&this -> vv_c   ); return;
         case data_enum::v_ull:    this -> flush_buffer(&this -> v_ull  ); return;
         case data_enum::v_ui:     this -> flush_buffer(&this -> v_ui   ); return;
         case data_enum::v_d:      this -> flush_buffer(&this -> v_d    ); return;
         case data_enum::v_l:      this -> flush_buffer(&this -> v_l    ); return;
         case data_enum::v_f:      this -> flush_buffer(&this -> v_f    ); return;
         case data_enum::v_i:      this -> flush_buffer(&this -> v_i    ); return;
         case data_enum::v_b:      this -> flush_buffer(&this -> v_b    ); return;
         case data_enum::v_c:      this -> flush_buffer(&this -> v_c    ); return;
         case data_enum::ull:      this -> flush_buffer(&this -> ull    ); return;
         case data_enum::ui:       this -> flush_buffer(&this -> ui     ); return;
         case data_enum::d:        this -> flush_buffer(&this -> d      ); return;
         case data_enum::l:        this -> flush_buffer(&this -> l      ); return;
         case data_enum::f:        this -> flush_buffer(&this -> f      ); return;
         case data_enum::i:        this -> flush_buffer(&this -> i      ); return;
         case data_enum::b:        this -> flush_buffer(&this -> b      ); return;
         case data_enum::c:        this -> flush_buffer(&this -> c      ); return;
         default: break;
     }
     if      (this -> vvv_ull){this -> type = data_enum::vvv_ull;}
     else if (this -> vvv_ui ){this -> type = data_enum::vvv_ui; }
     else if (this -> vvv_d  ){this -> type = data_enum::vvv_d;  }
     else if (this -> vvv_l  ){this -> type = data_enum::vvv_l;  }
     else if (this -> vvv_f  ){this -> type = data_enum::vvv_f;  }
     else if (this -> vvv_i  ){this -> type = data_enum::vvv_i;  }
     else if (this -> vvv_b  ){this -> type = data_enum::vvv_b;  }
     else if (this -> vvv_c  ){this -> type = data_enum::vvv_c;  }
     else if (this -> vv_ull ){this -> type = data_enum::vv_ull; }
     else if (this -> vv_ui  ){this -> type = data_enum::vv_ui;  }
     else if (this -> vv_d   ){this -> type = data_enum::vv_d;   }
     else if (this -> vv_l   ){this -> type = data_enum::vv_l;   }
     else if (this -> vv_f   ){this -> type = data_enum::vv_f;   }
     else if (this -> vv_i   ){this -> type = data_enum::vv_i;   }
     else if (this -> vv_b   ){this -> type = data_enum::vv_b;   }
     else if (this -> vv_c   ){this -> type = data_enum::vv_c;   }
     else if (this -> v_ull  ){this -> type = data_enum::v_ull;  }
     else if (this -> v_ui   ){this -> type = data_enum::v_ui;   }
     else if (this -> v_d    ){this -> type = data_enum::v_d;    }
     else if (this -> v_l    ){this -> type = data_enum::v_l;    }
     else if (this -> v_f    ){this -> type = data_enum::v_f;    }
     else if (this -> v_i    ){this -> type = data_enum::v_i;    }
     else if (this -> v_b    ){this -> type = data_enum::v_b;    }
     else if (this -> v_c    ){this -> type = data_enum::v_c;    }
     else if (this -> ull    ){this -> type = data_enum::ull;    }
     else if (this -> ui     ){this -> type = data_enum::ui;     }
     else if (this -> d      ){this -> type = data_enum::d;      }
     else if (this -> l      ){this -> type = data_enum::l;      }
     else if (this -> f      ){this -> type = data_enum::f;      }
     else if (this -> i      ){this -> type = data_enum::i;      }
     else if (this -> b      ){this -> type = data_enum::b;      }
     else if (this -> c      ){this -> type = data_enum::c;      }
     else if (this -> type == data_enum::unset){return;}
     else {this -> type = data_enum::undef;}
     // =================================================================== //
     if (this -> type != data_enum::undef && this -> type != data_enum::unset){return;}
     std::cout << "UNDEFINED DATA TYPE! SEE modules/structs/cxx/base.cxx" << std::endl;
     abort();
 }
References b, c, d, f, i, l, ui, ull, undef, unset, v_b, v_c, v_d, v_f, v_i, v_l, v_ui, v_ull, vv_b, vv_c, vv_d, vv_f, vv_i, vv_l, vv_ui, vv_ull, vvv_b, vvv_c, vvv_d, vvv_f, vvv_i, vvv_l, vvv_ui, and vvv_ull.
Referenced by data_t::flush(), data_t::initialize(), variable_t::process(), data_t::~data_t(), and variable_t::~variable_t().
root_type_translate()
data_enum bsc_t::root_type_translate (std::string * root_str)
Translates a ROOT type string to an internal data enumeration.
Parameters
root_str Pointer to the string containing the ROOT type.
Returns
The corresponding data_enum value.
This method parses a ROOT type string (e.g., "vector<float>") and returns the corresponding internal data_enum value for type-safe operations.
Definition at line 70 of file structs/cxx/base.cxx.
{
     int vec = count(root_str, "vector");
     if (vec == 0 && (*root_str) ==   "Float_t"){return data_enum::v_f  ;}
     if (vec == 0 && (*root_str) ==  "Double_t"){return data_enum::v_d  ;}
     if (vec == 0 && (*root_str) ==    "UInt_t"){return data_enum::v_ui ;}
     if (vec == 0 && (*root_str) ==     "Int_t"){return data_enum::v_i  ;}
     if (vec == 0 && (*root_str) ==    "Char_t"){return data_enum::v_c  ;}
     if (vec == 0 && (*root_str) ==      "char"){return data_enum::v_c  ;}
     if (vec == 0 && (*root_str) == "ULong64_t"){return data_enum::v_ull;}
     if (vec == 0 && count(root_str, "float")){return   data_enum::v_f;}
     if (vec == 1 && count(root_str, "float")){return  data_enum::vv_f;}
     if (vec == 2 && count(root_str, "float")){return data_enum::vvv_f;}
     if (vec == 0 && count(root_str, "double")){return   data_enum::v_d;}
     if (vec == 1 && count(root_str, "double")){return  data_enum::vv_d;}
     if (vec == 2 && count(root_str, "double")){return data_enum::vvv_d;}
     if (vec == 0 && count(root_str, "int")){return   data_enum::v_i;}
     if (vec == 1 && count(root_str, "int")){return  data_enum::vv_i;}
     if (vec == 2 && count(root_str, "int")){return data_enum::vvv_i;}
     if (vec == 0 && count(root_str, "long")){return   data_enum::v_l;}
     if (vec == 1 && count(root_str, "long")){return  data_enum::vv_l;}
     if (vec == 2 && count(root_str, "long")){return data_enum::vvv_l;}
     if (vec == 0 && count(root_str, "bool")){return   data_enum::v_b;}
     if (vec == 1 && count(root_str, "bool")){return  data_enum::vv_b;}
     if (vec == 2 && count(root_str, "bool")){return data_enum::vvv_b;}
     if (vec == 1 && count(root_str, "char")){return  data_enum::vv_c;}
     return data_enum::undef;
 }
References count(), undef, v_b, v_c, v_d, v_f, v_i, v_l, v_ui, v_ull, vv_b, vv_c, vv_d, vv_f, vv_i, vv_l, vvv_b, vvv_d, vvv_f, vvv_i, and vvv_l.
scan_buffer()
std::string bsc_t::scan_buffer ()
Scans and returns the current buffer content.
Returns
A string containing the current buffer content.
This method returns the current content of the internal buffer, which is used for accumulating textual data during operations.
Definition at line 143 of file structs/cxx/base.cxx.
{
     std::string x = "";
     if (this -> vvv_ull){x += " | vector<vector<vector<unsigned long long>>>";}
     if (this -> vvv_ui ){x += " | vector<vector<vector<unsigned int>>>";      }
     if (this -> vvv_d  ){x += " | vector<vector<vector<double>>>";            }
     if (this -> vvv_l  ){x += " | vector<vector<vector<long>>>";              }
     if (this -> vvv_f  ){x += " | vector<vector<vector<float>>>";             }
     if (this -> vvv_i  ){x += " | vector<vector<vector<int>>>" ;              }
     if (this -> vvv_b  ){x += " | vector<vector<vector<bool>>>";              }
     if (this -> vvv_c  ){x += " | vector<vector<vector<char>>>";              }
     if (this -> vv_ull ){x += " | vector<vector<unsigned long long>>";        }
     if (this -> vv_ui  ){x += " | vector<vector<unsigned int>>";              }
     if (this -> vv_d   ){x += " | vector<vector<double>>";                    }
     if (this -> vv_l   ){x += " | vector<vector<long>>";                      }
     if (this -> vv_f   ){x += " | vector<vector<float>>";                     }
     if (this -> vv_i   ){x += " | vector<vector<int>>" ;                      }
     if (this -> vv_b   ){x += " | vector<vector<bool>>";                      }
     if (this -> vv_c   ){x += " | vector<vector<char>>";                      }
     if (this -> v_ull  ){x += " | vector<unsigned long long>";                }
     if (this -> v_ui   ){x += " | vector<unsigned int>";                      }
     if (this -> v_d    ){x += " | vector<double>";                            }
     if (this -> v_l    ){x += " | vector<long>";                              }
     if (this -> v_f    ){x += " | vector<float>";                             }
     if (this -> v_i    ){x += " | vector<int>" ;                              }
     if (this -> v_b    ){x += " | vector<bool>";                              }
     if (this -> v_c    ){x += " | vector<char>";                              }
     if (this -> ull    ){x += " | unsigned long long";                        }
     if (this -> ui     ){x += " | unsigned int";                              }
     if (this -> d      ){x += " | double";                                    }
     if (this -> l      ){x += " | long";                                      }
     if (this -> f      ){x += " | float";                                     }
     if (this -> i      ){x += " | int" ;                                      }
     if (this -> b      ){x += " | bool";                                      }
     if (this -> c      ){x += " | char";                                      }
     return (x.size()) ? x : "undefined/unset";
 }
References b, c, d, f, i, l, ui, ull, v_b, v_c, v_d, v_f, v_i, v_l, v_ui, v_ull, vv_b, vv_c, vv_d, vv_f, vv_i, vv_l, vv_ui, vv_ull, vvv_b, vvv_c, vvv_d, vvv_f, vvv_i, vvv_l, vvv_ui, vvv_ull, and main::x.
Member Data Documentation
buffer
std::string bsc_t::buffer
Internal buffer for accumulating textual data.
Definition at line 126 of file modules/structs/include/structs/base.h.
The documentation for this class was generated from the following files:
modules/structs/include/structs/base.h
structs/cxx/base.cxx