AnalysisG: tools Class Reference
tools Class Reference
Provides a wide range of utility functions used throughout the framework.
#include <tools.h>
Public Member Functions
tools ()
Constructor for the tools class.
~tools ()
Destructor for the tools class.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Static Public Member Functions
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Detailed Description
Provides a wide range of utility functions used throughout the framework.
The tools class serves as a toolkit, offering methods for file operations, string manipulations, container operations, type information retrieval, and more. Many classes in the AnalysisG framework inherit from tools to gain access to these common functionalities, promoting code reuse and consistency.
Definition at line 29 of file tools.h.
Constructor & Destructor Documentation
tools()
tools::tools ()
Constructor for the tools class.
Initializes a new tools instance.
Definition at line 2 of file tools.cxx.
 {}
Referenced by dataloader::dump_graphs().
~tools()
tools::~tools ()
Destructor for the tools class.
Cleans up resources used by the tools instance.
Definition at line 3 of file tools.cxx.
 {}
Member Function Documentation
absolute_path()
std::string tools::absolute_path (std::string path) static
Converts a relative path to an absolute path.
Parameters
path The path to convert.
Returns
The absolute version of the path.
Definition at line 49 of file tools/cxx/io.cxx.
{
     return std::filesystem::canonical(path).string();
 }
References childrenkinematics.figures::path().
Referenced by analysis::analysis(), io::check_root_file_paths(), and io::trigger_pcm().
create_path()
void tools::create_path (std::string path) static
Creates a directory path, including parent directories if needed.
Parameters
path The directory path to create.
Definition at line 6 of file tools/cxx/io.cxx.
{
     bool f = false;
     if (tools::split(input_path, ".").size() > 1){f = true;}
     std::vector<std::string> cuts = tools::split(input_path, "/");
     std::string path = "";
     for (unsigned int x(0); x < cuts.size() - f; ++x){
         path += cuts[x] + "/";
         mkdir(path.c_str(), S_IRWXU);
     }
 }
References f, childrenkinematics.figures::path(), split(), and main::x.
Referenced by analysis::analysis(), plotting::build_path(), container::compile(), metrics::dump_mass_plots(), analysis::start(), and io::trigger_pcm().
delete_path()
void tools::delete_path (std::string path) static
Deletes a directory path and its contents.
Parameters
path The directory path to delete.
Definition at line 22 of file tools/cxx/io.cxx.
{
     struct stat sb;
     if (!stat(input_path.c_str(), &sb)){
         if (S_ISDIR(sb.st_mode)){rmdir(input_path.c_str());}
         else {unlink(input_path.c_str());}
     }
 }
ends_with()
bool tools::ends_with (std::string * inpt, std::string val) static
Checks if a string ends with a specific substring.
Parameters
inpt Pointer to the string to check.
val The substring to check for at the end.
Returns
True if the string ends with the substring, false otherwise.
Definition at line 71 of file strings.cxx.
{
     if (inpt -> size() < val.size()){return false;}
     std::string l = inpt -> substr(inpt -> size() - val.size(), inpt -> size()-1);
     return val == l;
 }
References l.
Referenced by plotting::build_path(), io::check_root_file_paths(), ls(), meta::parse_json(), io::scan_keys(), and analysis::start().
extract()
template<typename C , typename T > static void tools::extract (std::vector< T > * prop, std::vector< C * > * src, void(*)(T *, C *) get_prop) inline static
Extracts a specific property from a vector of objects into a new vector.
Template Parameters
C The type of objects in the source vector.
T The type of the property to extract.
Parameters
prop Pointer to the output vector to fill with property values.
src Pointer to the source vector of objects.
get_prop Function pointer to extract the property from an object.
< Clear the properties vector.
< Reserve space for the property values.
< Loop through each object in the source vector.
< Create a default-initialized property variable.
< Call the provided function to extract the property.
< Add the property value to the output vector.
Definition at line 216 of file tools.h.
{
         prop -> clear(); ///< Clear the properties vector.
         prop -> reserve(src -> size()); ///< Reserve space for the property values.
         for (size_t x(0); x < src -> size(); ++x){ ///< Loop through each object in the source vector.
             T t_prop = {}; ///< Create a default-initialized property variable.
             get_prop(&t_prop, (*src)[x]); ///< Call the provided function to extract the property.
             prop -> push_back(t_prop); ///< Add the property value to the output vector.
         }
     }
References main::x.
flush()
template<typename T > static void tools::flush (std::vector< T * > * inpt) inline static
Empties a vector and all objects it points to.
Template Parameters
T The type of pointers in the vector.
Parameters
inpt Pointer to the vector to empty.
< Loop through all elements in the vector.
< Delete the object the pointer points to.
< Set the pointer to nullptr to avoid dangling pointers.
< Clear the vector.
Definition at line 167 of file tools.h.
{
         for (size_t t(0); t < inpt -> size(); ++t){ ///< Loop through all elements in the vector.
             if (!(*inpt)[t]){continue;} ///< Skip nullptr entries.
             delete (*inpt)[t]; ///< Delete the object the pointer points to.
             (*inpt)[t] = nullptr; ///< Set the pointer to nullptr to avoid dangling pointers.
         }
         inpt -> clear(); ///< Clear the vector.
     }
References test_experimental_mc20::t.
Referenced by sampletracer::compile_objects(), io::root_end(), analysis::~analysis(), and dataloader::~dataloader().
has_string()
bool tools::has_string (std::string * inpt, std::string trg) static
Checks if a string contains a specific substring.
Parameters
inpt Pointer to the string to check.
trg The substring to search for.
Returns
True if the substring is found, false otherwise.
Definition at line 65 of file strings.cxx.
{
     std::size_t f = inpt -> find(trg);
     if (f != std::string::npos){return true;}
     return false;
 }
References f.
Referenced by meta::scan_sow(), and model_template::set_device().
has_value()
bool tools::has_value (std::vector< std::string > * data, std::string trg) static
Checks if a vector of strings contains a specific string.
Parameters
data Pointer to the vector to search.
trg The string to search for.
Returns
True if the string is found in the vector, false otherwise.
Definition at line 77 of file strings.cxx.
{
     for (size_t x(0); x < data -> size(); ++x){
         if (trg != data -> at(x)){continue;}
         return true;
     }
     return false;
 }
References simply_plot::data, and main::x.
Referenced by io::scan_keys().
is_file()
bool tools::is_file (std::string path) static
Checks if a path refers to an existing file.
Parameters
path The path to check.
Returns
True if the path is a file and exists, false otherwise.
Definition at line 30 of file tools/cxx/io.cxx.
{
     struct stat buffer;
     return (stat (path.c_str(), &buffer) == 0);
 }
References childrenkinematics.figures::path().
Referenced by io::check_root_file_paths().
ls()
std::vector< std::string > tools::ls (std::string path, std::string ext = "") static
Lists files in a directory, optionally filtered by extension.
Parameters
path The directory to search.
ext File extension filter. If empty, all files are listed.
Returns
A vector of filenames in the directory.
Definition at line 35 of file tools/cxx/io.cxx.
{
     if (tools::ends_with(&path, "*")){path = tools::split(path, "*")[0];}
     std::vector<std::string> out = {};
     std::filesystem::recursive_directory_iterator itr;
     try {itr = std::filesystem::recursive_directory_iterator(path);}
     catch (...) {return {};}
     for (const std::filesystem::directory_entry& val : itr){
         std::string s = std::filesystem::canonical(val.path()).string();
         if (ext.size() && !tools::ends_with(&s, ext)){continue;}
         out.push_back(s);
     }
     return out;
 }
References ends_with(), main::out, childrenkinematics.figures::path(), and split().
Referenced by analysis::analysis(), io::check_root_file_paths(), dataloader::restore_graphs(), and io::trigger_pcm().
put()
template<typename g > static void tools::put (std::vector< g * > * out, std::vector< g * > * src, std::vector< int > * trg) inline static
Fills a vector with pointers from another vector based on a selection index.
Template Parameters
g The type of objects being pointed to.
Parameters
out Pointer to the output vector to fill.
src Pointer to the source vector to select from.
trg Pointer to a vector of indices for selection.
< Clear the output vector.
< Reserve space for the output elements.
< Loop through each selected index.
< Get the object at the selected index.
< Add it to the output vector.
< Mark the object as in use.
Definition at line 197 of file tools.h.
{
         out -> clear(); ///< Clear the output vector.
         out -> reserve(trg -> size()); ///< Reserve space for the output elements.
         for (size_t x(0); x < trg -> size(); ++x){ ///< Loop through each selected index.
             g* v = (*src)[(*trg)[x]]; ///< Get the object at the selected index.
             out -> push_back(v); ///< Add it to the output vector.
             v -> in_use = 1; ///< Mark the object as in use.
         }
     }
References main::out, and main::x.
Referenced by dataloader::get_k_train_set(), dataloader::get_k_validation_set(), and dataloader::get_test_set().
rename()
void tools::rename (std::string start, std::string target) static
Renames a file or directory.
Parameters
start The original path.
target The new path.
Definition at line 18 of file tools/cxx/io.cxx.
{
     std::filesystem::rename(start, target);
 }
replace()
void tools::replace (std::string * in, std::string repl_str, std::string repl_with) static
Replaces all occurrences of a substring in a string.
Parameters
in Pointer to the string to modify.
repl_str The substring to replace.
repl_with The replacement string.
Definition at line 5 of file strings.cxx.
{
     std::size_t pos = 0;
     std::size_t ppos;
     std::string buf;
     while (true){
         ppos = pos;
         pos = in -> find(to_repl, pos);
         if (pos == std::string::npos){break;}
         buf.append(*in, ppos, pos - ppos);
         buf += repl_w;
         pos += to_repl.size();
     }
     buf.append(*in, ppos, in -> size() - ppos);
     in -> swap(buf);
 }
Referenced by meta::parse_json(), analysis::start(), validation.figures::template(), and topefficiency.figures::top_kinematic_region().
split()
std::vector< std::string > tools::split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
Parameters
inpt The input string to split.
del The delimiter.
Returns
A vector of substrings.
Definition at line 23 of file strings.cxx.
{
     size_t pos = 0;
     size_t s_dim = search.length();
     size_t index = 0;
     std::string token;
     std::vector<std::string> out = {};
     while ((pos = inpt.find(search)) != std::string::npos){
         out.push_back(inpt.substr(0, pos));
         inpt.erase(0, pos + s_dim);
         ++index;
     }
     out.push_back(inpt);
     return out;
 }
References index, and main::out.
Referenced by container::compile(), sampletracer::compile_objects(), create_path(), meta::hash(), topefficiency.algorithms::kinesplit(), ls(), io::root_begin(), model_template::set_device(), and analysis::start().
sum()
template<typename g > g tools::sum (std::vector< g > * inpt) inline
Sums the elements of a vector.
Template Parameters
g The type of elements in the vector.
Parameters
inpt Pointer to the vector to sum.
Returns
The sum of all elements.
< Initialize the output variable.
< Return the sum.
Definition at line 183 of file tools.h.
{
         g out = 0; ///< Initialize the output variable.
         for (size_t t(0); t < inpt -> size(); ++t){out += (*inpt)[t];} ///< Add each element to the total.
         return out; ///< Return the sum.
     }
References main::out, and test_experimental_mc20::t.
Referenced by sampletracer::compile_objects(), particle_template::DeltaR(), graph_template::double_neutrino(), grift::message(), zprime::strategy(), parton::strategy(), and parton::top_mass_contribution().
to_string() [1/2]
std::string tools::to_string (double val) static
Converts a double value to a string with standard precision.
Parameters
val The double value to convert.
Returns
The string representation of the value.
Definition at line 59 of file strings.cxx.
{
     std::stringstream ss;
     ss << val;
     return ss.str();
 }
Referenced by dataloader::generate_kfold_set(), dataloader::generate_test_set(), particle_template::get_hash(), topefficiency::region(), dataloader::restore_dataset(), selection_template::set_hash(), parton::strategy(), and parton::top_mass_contribution().
to_string() [2/2]
std::string tools::to_string (double val, int prec) static
Converts a double value to a string with specified precision.
Parameters
val The double value to convert.
prec The number of decimal places to consider.
Returns
The string representation of the value.
Definition at line 91 of file strings.cxx.
{
     std::stringstream ss;
     if (prec > -1){ss.precision(prec);}
     ss << std::fixed << val;
     return ss.str();
 }
trim()
std::string tools::trim (std::string s)
Removes whitespace from the beginning and end of a string.
Parameters
s The string to trim.
Returns
The trimmed string.
type_name()
template<typename T > std::string tools::type_name () inline
Gets the type name of a variable as a string (for debugging).
Template Parameters
T The type to get the name of.
Returns
The name of the type as a string.
< Gets the type name via RTTI.
< Returns the type name.
Definition at line 155 of file tools.h.
{
         std::string tn = typeid(T).name(); ///< Gets the type name via RTTI.
         return tn; ///< Returns the type name.
     }
References name.
The documentation for this class was generated from the following files:
tools.h
tools/cxx/io.cxx
strings.cxx
tools.cxx