AnalysisG: selection_template Class Reference
selection_template Class Reference
#include <selection_template.h>
Public Member Functions
selection_template ()
virtual ~selection_template ()
virtual selection_template * clone ()
virtual bool selection (event_template *ev)
virtual bool strategy (event_template *ev)
virtual void merge (selection_template *sel)
virtual void bulk_write (const long *idx, std::string *hx)
virtual void write (std::vector< particle_template * > *particles, std::string name, particle_enum attrs)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< std::vector< double >> *data)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< int > *data)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< double > *data)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< bool > *data)
template<typename g >
void write (g *var, std::string name)
template<typename g >
void write (g var, std::string name)
std::vector< std::map< std::string, float > > reverse_hash (std::vector< std::string > *hashes)
bool CompileEvent ()
selection_template * build (event_template *ev)
bool operator== (selection_template &p)
template<typename g , typename k >
void sum (std::vector< g * > *ch, k **out)
template<typename g >
void safe_delete (std::vector< g * > *particles)
template<typename g >
g * sum (std::map< std::string, g * > *ch)
template<typename g >
float sum (std::vector< g * > *ch)
template<typename g >
std::vector< g * > vectorize (std::map< std::string, g * > *in)
template<typename g >
std::vector< g * > make_unique (std::vector< g * > *inpt)
template<typename g >
void downcast (std::vector< g * > *inpt, std::vector< particle_template * > *out)
template<typename o , typename g >
void upcast (std::map< std::string, o * > *inpt, std::vector< g * > *out)
template<typename o , typename g >
void upcast (std::vector< o * > *inpt, std::vector< g * > *out)
template<typename g >
void get_leptonics (std::map< std::string, g * > inpt, std::vector< particle_template * > *out)
template<typename g , typename j >
bool contains (std::vector< g * > *inpt, j *pcheck)
Public Member Functions inherited from tools
tools ()
Constructor for the tools class.
~tools ()
Destructor for the tools class.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Static Public Member Functions
static void set_name (std::string *, selection_template *)
static void get_name (std::string *, selection_template *)
static void set_hash (std::string *, selection_template *)
static void get_hash (std::string *, selection_template *)
static void get_tree (std::string *, selection_template *)
static void set_weight (double *, selection_template *)
static void get_weight (double *, selection_template *)
static void set_index (long *, selection_template *)
Static Public Member Functions inherited from tools
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Public Attributes
cproperty< std::string, selection_template > name
cproperty< std::string, selection_template > hash
cproperty< std::string, selection_template > tree
cproperty< double, selection_template > weight
cproperty< long, selection_template > index
meta * meta_data = nullptr
std::string filename = ""
event_t data
int threadIdx = -1
std::map< std::string, std::map< std::string, float > > passed_weights = {}
std::map< std::string, meta_t > matched_meta = {}
Detailed Description
Definition at line 18 of file selection_template.h.
Constructor & Destructor Documentation
selection_template()
selection_template::selection_template ()
Definition at line 4 of file selection_core.cxx.
{
     this -> name.set_object(this);
     this -> name.set_setter(this -> set_name);
     this -> name.set_getter(this -> get_name);
     this -> hash.set_setter(this -> set_hash);
     this -> hash.set_getter(this -> get_hash);
     this -> hash.set_object(this);
     this -> tree.set_object(this);
     this -> tree.set_getter(this -> get_tree);
     this -> weight.set_setter(this -> set_weight);
     this -> weight.set_getter(this -> get_weight);
     this -> weight.set_object(this);
     this -> index.set_setter(this -> set_index);
     this -> index.set_object(this);
     this -> name = "selection-template";
 }
References get_hash(), get_name(), get_tree(), get_weight(), hash, index, name, cproperty< T, G >::set_getter(), set_hash(), set_index(), set_name(), cproperty< T, G >::set_object(), cproperty< T, G >::set_setter(), set_weight(), tree, and weight.
Referenced by clone().
~selection_template()
selection_template::~selection_template () virtual
Definition at line 26 of file selection_core.cxx.
{
     std::map<std::string, std::vector<particle_template*>>::iterator itr;
     for (itr = this -> garbage.begin(); itr != this -> garbage.end(); ++itr){
         for (size_t x(0); x < itr -> second.size(); ++x){
             if (!itr -> second[x] -> _is_marked){continue;}
             delete itr -> second[x];
         }
         itr -> second.clear();
     }
     this -> garbage.clear();
 }
References this, and main::x.
Member Function Documentation
build()
selection_template * selection_template::build (event_template * ev)
Definition at line 47 of file selection_core.cxx.
{
     selection_template* sel = this -> clone();
     std::string name = sel -> name;
     sel -> m_event  = ev;
     sel -> data     = ev -> data;
     sel -> name     = name;
     sel -> weight   = ev -> weight;
     sel -> filename = ev -> filename;
     return sel;
 }
References clone(), data, main::ev, filename, name, main::sel, and weight.
bulk_write()
void selection_template::bulk_write (const long * idx, std::string * hx) virtual
Definition at line 8 of file selection_template.cxx.
 {this -> p_bulk_write = false;}
clone()
selection_template * selection_template::clone () virtual
Reimplemented in combinatorial, regions, childrenkinematics, validation, matching, topefficiency, met, decaymodes, event, topjets, topkinematics, topmatching, toptruthjets, topkinematics, and topmatching.
Definition at line 6 of file selection_template.cxx.
 {return new selection_template();}
References selection_template().
Referenced by build().
CompileEvent()
bool selection_template::CompileEvent ()
Definition at line 41 of file selection_core.cxx.
{
     if (!this -> selection(this -> m_event)){return false;}
     if (!this -> strategy(this -> m_event)){return false;}
     return true;
 }
References selection(), and strategy().
contains()
template<typename g , typename j > bool selection_template::contains (std::vector< g * > * inpt, j * pcheck) inline
Definition at line 163 of file selection_template.h.
{
             for (size_t x(0); x < inpt -> size(); ++x){
                 if ((*inpt)[x] -> hash != pcheck -> hash){continue;}
                 return true;
             }
             return false;
         }
References hash, and main::x.
downcast()
template<typename g > void selection_template::downcast (std::vector< g * > * inpt, std::vector< particle_template * > * out) inline
Definition at line 138 of file selection_template.h.
{
             for (size_t x(0); x < inpt -> size(); ++x){out -> push_back((particle_template*)(*inpt)[x]);}
         }
References main::out, and main::x.
Referenced by topjets::strategy(), and toptruthjets::strategy().
get_hash()
void selection_template::get_hash (std::string * val, selection_template * ev) static
Definition at line 18 of file selection/cxx/properties.cxx.
{
     *val = ev -> data.hash;
 }
References data, main::ev, and event_t::hash.
Referenced by selection_template().
get_leptonics()
template<typename g > void selection_template::get_leptonics (std::map< std::string, g * > inpt, std::vector< particle_template * > * out) inline
Definition at line 154 of file selection_template.h.
{
             typename std::map<std::string, g*>::iterator itr = inpt.begin();
             for (; itr != inpt.end(); ++itr){
                 if (!itr -> second -> is_lep && !itr -> second -> is_nu){continue;}
                 out -> push_back((particle_template*)itr -> second);
             }
         }
References is_lep, is_nu, and main::out.
Referenced by topjets::strategy(), and toptruthjets::strategy().
get_name()
void selection_template::get_name (std::string * name, selection_template * ev) static
Definition at line 7 of file selection/cxx/properties.cxx.
{
     *name = ev -> data.name;
 }
References data, main::ev, event_t::name, and name.
Referenced by selection_template().
get_tree()
void selection_template::get_tree (std::string * name, selection_template * ev) static
Definition at line 22 of file selection/cxx/properties.cxx.
{
     *name = ev -> data.tree;
 }
References data, main::ev, name, and event_t::tree.
Referenced by selection_template().
get_weight()
void selection_template::get_weight (double * inpt, selection_template * ev) static
Definition at line 30 of file selection/cxx/properties.cxx.
{
     *inpt = ev -> data.weight;
 }
References data, main::ev, and event_t::weight.
Referenced by selection_template().
make_unique()
template<typename g > std::vector<g*> selection_template::make_unique (std::vector< g * > * inpt) inline
Definition at line 124 of file selection_template.h.
{
             std::map<std::string, g*> tmp;
             for (size_t x(0); x < inpt -> size(); ++x){
                 std::string hash = (*inpt)[x] -> hash;
                 tmp[hash] = (*inpt)[x];
             }
             typename std::vector<g*> out = {};
             typename std::map<std::string, g*>::iterator itr;
             for (itr = tmp.begin(); itr != tmp.end(); ++itr){out.push_back(itr -> second);}
             return out;
         }
References hash, main::out, main::tmp, and main::x.
Referenced by combinatorial::reconstruction(), toptruthjets::strategy(), and topjets::strategy().
merge()
void selection_template::merge (selection_template * sel) virtual
Reimplemented in combinatorial, regions, matching, childrenkinematics, validation, topefficiency, met, decaymodes, event, topjets, topkinematics, topmatching, toptruthjets, topkinematics, and topmatching.
Definition at line 7 of file selection_template.cxx.
 {}
operator==()
bool selection_template::operator== (selection_template & p)
Definition at line 38 of file selection_core.cxx.
 {return this -> hash == p.hash;}
References hash, and rnn_model::p.
reverse_hash()
std::vector< std::map< std::string, float > > selection_template::reverse_hash (std::vector< std::string > * hashes)
Definition at line 84 of file selection_core.cxx.
{
     std::vector<std::map<std::string, float>> output;
     output.assign(hashes -> size(), {{"None", 0}});
     for (size_t x(0); x < hashes -> size(); ++x){
         std::string hash = (*hashes)[x];
         std::map<std::string, std::map<std::string, float>>::iterator itr;
         for (itr = this -> passed_weights.begin(); itr != this -> passed_weights.end(); ++itr){
             if (!itr -> second.count(hash)){continue;}
             output[x] = {{itr -> first, itr -> second[hash]}};
             break;
         }
     }
     return output;
 }
References hash, passed_weights, and main::x.
safe_delete()
template<typename g > void selection_template::safe_delete (std::vector< g * > * particles) inline
Definition at line 92 of file selection_template.h.
{
             for (size_t x(0); x < particles -> size(); ++x){
                 if (particles -> at(x) -> _is_marked){continue;}
                 delete particles -> at(x);
                 (*particles)[x] = nullptr;
             }
         }
References main::x.
Referenced by combinatorial::~combinatorial(), and validation::~validation().
selection()
bool selection_template::selection (event_template * ev) virtual
Reimplemented in combinatorial, regions, childrenkinematics, validation, topefficiency, met, decaymodes, event, topjets, topkinematics, topmatching, toptruthjets, topkinematics, and topmatching.
Definition at line 4 of file selection_template.cxx.
 {return true;}
Referenced by CompileEvent().
set_hash()
void selection_template::set_hash (std::string * path, selection_template * ev) static
Definition at line 11 of file selection/cxx/properties.cxx.
{
     if (ev -> data.hash.size()){return;}
     std::string x = *path + "/" + ev -> to_string(ev -> index);
     ev -> data.hash = ev -> tools::hash(x, 18);
     *path = "";
 }
References data, main::ev, event_t::hash, index, childrenkinematics.figures::path(), tools::to_string(), and main::x.
Referenced by selection_template().
set_index()
void selection_template::set_index (long * inpt, selection_template * ev) static
Definition at line 34 of file selection/cxx/properties.cxx.
{
     ev -> data.index = *inpt;
 }
References data, main::ev, and event_t::index.
Referenced by selection_template().
set_name()
void selection_template::set_name (std::string * name, selection_template * ev) static
Definition at line 3 of file selection/cxx/properties.cxx.
{
     ev -> data.name = *name;
 }
References data, main::ev, event_t::name, and name.
Referenced by selection_template().
set_weight()
void selection_template::set_weight (double * inpt, selection_template * ev) static
Definition at line 26 of file selection/cxx/properties.cxx.
{
     ev -> data.weight = *inpt;
 }
References data, main::ev, and event_t::weight.
Referenced by selection_template().
strategy()
bool selection_template::strategy (event_template * ev) virtual
Reimplemented in combinatorial, regions, matching, childrenkinematics, validation, topefficiency, met, decaymodes, event, topjets, topkinematics, topmatching, toptruthjets, topkinematics, and topmatching.
Definition at line 5 of file selection_template.cxx.
 {return true;}
Referenced by CompileEvent().
sum() [1/3]
template<typename g > g* selection_template::sum (std::map< std::string, g * > * ch) inline
Definition at line 101 of file selection_template.h.
{
             g* out = nullptr;
             typename std::vector<g*> vec = this -> vectorize(ch);
             this -> sum(&vec, &out);
             return out;
         }
References main::out, sum(), and vectorize().
sum() [2/3]
template<typename g > float selection_template::sum (std::vector< g * > * ch) inline
Definition at line 109 of file selection_template.h.
{
             particle_template* prt = nullptr;
             this -> sum(ch, &prt);
             return prt -> mass / 1000;
         }
References mass, and sum().
sum() [3/3]
template<typename g , typename k > void selection_template::sum (std::vector< g * > * ch, k ** out) inline
Definition at line 77 of file selection_template.h.
{
             k* prt = new k();
             prt -> _is_marked = true;
             std::map<std::string, bool> maps;
             for (size_t x(0); x < ch -> size(); ++x){
                 if (maps[ch -> at(x) -> hash]){continue;}
                 maps[ch -> at(x) -> hash] = true;
                 prt -> iadd(ch -> at(x));
             }
             std::string hash_ = prt -> hash;
             this -> garbage[hash_].push_back((particle_template*)prt);
             (*out) = prt;
         }
References hash, and main::x.
Referenced by validation.nusol::intersections_ellipse_line(), validation.nusol::intersections_ellipses(), topjets.figures::jet_partons(), topefficiency.figures::ntops_reco(), decaymodes.figures::pdgid_modes(), validation::reconstruction(), decaymodes.figures::region_stats(), toptruthjets::strategy(), topjets::strategy(), decaymodes::strategy(), childrenkinematics::strategy(), sum(), topefficiency.figures::top_kinematic_region(), topkinematics.figures::top_pair_mass(), and toptruthjets.figures::truthjet_partons().
switch_board() [1/4]
void selection_template::switch_board (particle_enum attrs, particle_template * ptr, std::vector< bool > * data)
Definition at line 122 of file selection_core.cxx.
{
     switch (attrs){
         case particle_enum::is_b:   return data -> push_back(ptr -> is_b);
         case particle_enum::is_lep: return data -> push_back(ptr -> is_lep);
         case particle_enum::is_nu:  return data -> push_back(ptr -> is_nu);
         case particle_enum::is_add: return data -> push_back(ptr -> is_add);
         default: return;
     }
 }
References data, is_add, is_b, is_lep, and is_nu.
switch_board() [2/4]
void selection_template::switch_board (particle_enum attrs, particle_template * ptr, std::vector< double > * data)
Definition at line 107 of file selection_core.cxx.
{
     switch (attrs){
         case particle_enum::pt:     return data -> push_back(ptr -> pt);
         case particle_enum::eta:    return data -> push_back(ptr -> eta);
         case particle_enum::phi:    return data -> push_back(ptr -> phi);
         case particle_enum::energy: return data -> push_back(ptr -> e);
         case particle_enum::px:     return data -> push_back(ptr -> px);
         case particle_enum::py:     return data -> push_back(ptr -> py);
         case particle_enum::pz:     return data -> push_back(ptr -> pz);
         case particle_enum::mass:   return data -> push_back(ptr -> mass);
         case particle_enum::charge: return data -> push_back(ptr -> charge);
         default: return;
     }
 }
References charge, data, test_particles::e, energy, eta, mass, phi, pt, px, py, and pz.
switch_board() [3/4]
void selection_template::switch_board (particle_enum attrs, particle_template * ptr, std::vector< int > * data)
Definition at line 99 of file selection_core.cxx.
{
     switch (attrs){
         case particle_enum::pdgid: return data -> push_back(ptr -> pdgid);
         case particle_enum::index: return data -> push_back(ptr -> index);
         default: return;
     }
 }
References data, index, index, and pdgid.
switch_board() [4/4]
void selection_template::switch_board (particle_enum attrs, particle_template * ptr, std::vector< std::vector< double >> * data)
Definition at line 132 of file selection_core.cxx.
{
     std::vector<double> tmp;
     switch (attrs){
         case particle_enum::pmc:
                 this -> switch_board(particle_enum::px    , ptr, &tmp);
                 this -> switch_board(particle_enum::py    , ptr, &tmp);
                 this -> switch_board(particle_enum::pz    , ptr, &tmp);
                 this -> switch_board(particle_enum::energy, ptr, &tmp);
                 break;
         case particle_enum::pmu:
                 this -> switch_board(particle_enum::pt    , ptr, &tmp);
                 this -> switch_board(particle_enum::eta   , ptr, &tmp);
                 this -> switch_board(particle_enum::phi   , ptr, &tmp);
                 this -> switch_board(particle_enum::energy, ptr, &tmp);
                 break;
         default: return;
     }
     data -> push_back(tmp);
 }
References data, energy, eta, phi, pmc, pmu, pt, px, py, pz, and main::tmp.
Referenced by write().
upcast() [1/2]
template<typename o , typename g > void selection_template::upcast (std::map< std::string, o * > * inpt, std::vector< g * > * out) inline
Definition at line 143 of file selection_template.h.
{
             typename std::map<std::string, o*>::iterator itx = inpt -> begin();
             for (; itx != inpt -> end(); ++itx){out -> push_back((g*)itx -> second);}
         }
References end(), and main::out.
Referenced by regions::strategy().
upcast() [2/2]
template<typename o , typename g > void selection_template::upcast (std::vector< o * > * inpt, std::vector< g * > * out) inline
Definition at line 149 of file selection_template.h.
{
             for (size_t x(0); x < inpt -> size(); ++x){out -> push_back((g*)(*inpt)[x]);}
         }
References main::out, and main::x.
vectorize()
template<typename g > std::vector<g*> selection_template::vectorize (std::map< std::string, g * > * in) inline
Definition at line 116 of file selection_template.h.
{
             typename std::vector<g*> out = {};
             typename std::map<std::string, g*>::iterator itr = in -> begin();
             for (; itr != in -> end(); ++itr){out.push_back(itr -> second);}
             return out;
         }
References end(), and main::out.
Referenced by matching::current(), matching::experimental(), matching::reference(), decaymodes::strategy(), validation::strategy(), childrenkinematics::strategy(), combinatorial::strategy(), and sum().
write() [1/3]
template<typename g > void selection_template::write (g * var, std::string name) inline
Definition at line 55 of file selection_template.h.
{
             if (!this -> handle){return;}
             this -> handle -> process(&name) -> process(var, &name, this -> handle -> tree);
         }
References name, and tree.
write() [2/3]
template<typename g > void selection_template::write (g var, std::string name) inline
Definition at line 61 of file selection_template.h.
{
             if (!this -> handle){return;}
             this -> handle -> process(&name) -> process(&var, &name, this -> handle -> tree);
         }
References name, and tree.
write() [3/3]
void selection_template::write (std::vector< particle_template * > * particles, std::string name, particle_enum attrs) virtual
Definition at line 10 of file selection_template.cxx.
{
     std::vector<int> data_i = {};
     std::vector<bool> data_b = {};
     std::vector<double> data_d = {};
     std::vector<std::vector<double>> data_dd = {};
     data_enum types = data_enum::undef;
     switch (attrs){
         case particle_enum::pt:     name += "_pt"    ; types = data_enum::v_d;  break;
         case particle_enum::eta:    name += "_eta"   ; types = data_enum::v_d;  break;
         case particle_enum::phi:    name += "_phi"   ; types = data_enum::v_d;  break;
         case particle_enum::px:     name += "_px"    ; types = data_enum::v_d;  break;
         case particle_enum::py:     name += "_py"    ; types = data_enum::v_d;  break;
         case particle_enum::pz:     name += "_pz"    ; types = data_enum::v_d;  break;
         case particle_enum::mass:   name += "_mass"  ; types = data_enum::v_d;  break;
         case particle_enum::energy: name += "_energy"; types = data_enum::v_d;  break;
         case particle_enum::charge: name += "_charge"; types = data_enum::v_d;  break;
         case particle_enum::is_b:   name += "_is_b"  ; types = data_enum::v_b;  break;
         case particle_enum::is_lep: name += "_is_l"  ; types = data_enum::v_b;  break;
         case particle_enum::is_nu:  name += "_is_n"  ; types = data_enum::v_b;  break;
         case particle_enum::is_add: name += "_is_a"  ; types = data_enum::v_b;  break;
         case particle_enum::pdgid:  name += "_pdgid" ; types = data_enum::v_i;  break;
         case particle_enum::index:  name += "_index" ; types = data_enum::v_i;  break;
         case particle_enum::pmc:    name += "_pmc"   ; types = data_enum::vv_d; break;
         case particle_enum::pmu:    name += "_pmu"   ; types = data_enum::vv_d; break;
         default: return;
     }
     for (size_t x(0); x < particles -> size(); ++x){
         switch (types){
             case data_enum::v_d:  this -> switch_board(attrs, particles -> at(x), &data_d);  break;
             case data_enum::v_i:  this -> switch_board(attrs, particles -> at(x), &data_i);  break;
             case data_enum::v_b:  this -> switch_board(attrs, particles -> at(x), &data_b);  break;
             case data_enum::vv_d: this -> switch_board(attrs, particles -> at(x), &data_dd); break;
             default: break;
         }
     }
     switch (types){
         case data_enum::v_d:  return this -> write(&data_d,  name);
         case data_enum::v_i:  return this -> write(&data_i,  name);
         case data_enum::v_b:  return this -> write(&data_b,  name);
         case data_enum::vv_d: return this -> write(&data_dd, name);
         default: return;
     }
 }
References charge, energy, eta, index, is_add, is_b, is_lep, is_nu, mass, name, pdgid, phi, pmc, pmu, pt, px, py, pz, switch_board(), undef, v_b, v_d, v_i, vv_d, and main::x.
Referenced by topkinematics::merge(), topmatching::merge(), validation::merge(), childrenkinematics::merge(), matching::merge(), regions::merge(), combinatorial::merge(), and met::strategy().
Member Data Documentation
data
event_t selection_template::data
Definition at line 74 of file selection_template.h.
Referenced by build(), get_hash(), get_name(), get_tree(), get_weight(), simply_plot.DataX::hist(), regions::merge(), simply_plot.DataX::num_events(), validation::reconstruction(), combinatorial::reconstruction(), set_hash(), set_index(), set_name(), set_weight(), topkinematics::strategy(), switch_board(), validation::update_state(), and combinatorial::update_state().
filename
std::string selection_template::filename = ""
Definition at line 73 of file selection_template.h.
Referenced by build().
hash
cproperty<std::string, selection_template> selection_template::hash
Definition at line 28 of file selection_template.h.
Referenced by contains(), matching::current(), make_unique(), validation.helper::MPNuNu(), operator==(), combinatorial::reconstruction(), matching::reference(), reverse_hash(), selection_template(), met::strategy(), topefficiency::strategy(), validation::strategy(), combinatorial::strategy(), and sum().
index
cproperty<long, selection_template> selection_template::index
Definition at line 39 of file selection_template.h.
Referenced by selection_template(), set_hash(), and switch_board().
matched_meta
std::map<std::string, meta_t> selection_template::matched_meta = {}
Definition at line 173 of file selection_template.h.
meta_data
meta* selection_template::meta_data = nullptr
Definition at line 72 of file selection_template.h.
name
cproperty<std::string, selection_template> selection_template::name
Definition at line 24 of file selection_template.h.
Referenced by build(), childrenkinematics::childrenkinematics(), combinatorial::combinatorial(), decaymodes::decaymodes(), event::event(), get_name(), get_tree(), matching::matching(), validation::merge(), regions::merge(), combinatorial::merge(), met::met(), regions::regions(), selection_template(), set_name(), matching::strategy(), topefficiency::topefficiency(), topjets::topjets(), topkinematics::topkinematics(), topmatching::topmatching(), toptruthjets::toptruthjets(), validation::update_state(), validation::validation(), and write().
passed_weights
std::map<std::string, std::map<std::string, float> > selection_template::passed_weights = {}
Definition at line 172 of file selection_template.h.
Referenced by reverse_hash().
threadIdx
int selection_template::threadIdx = -1
Definition at line 171 of file selection_template.h.
tree
cproperty<std::string, selection_template> selection_template::tree
Definition at line 32 of file selection_template.h.
Referenced by selection_template(), and write().
weight
cproperty<double, selection_template> selection_template::weight
Definition at line 35 of file selection_template.h.
Referenced by build(), regions::merge(), and selection_template().
The documentation for this class was generated from the following files:
selection_template.h
selection/cxx/properties.cxx
selection_core.cxx
selection_template.cxx