AnalysisG: nusol.SingleNu Class Reference
nusol.SingleNu Class Reference
Public Member Functions
def __init__ (self, b, mu, ev)
def calcX2 (self, t)
def chi2 (self)
def nu (self)
Public Member Functions inherited from nusol.NuSol
def __init__ (self, b, mu, ev=None, mW2=mW **2, mT2=mT **2, mN2=mN **2)
def b (self)
def mu (self)
def c (self)
def s (self)
def x0p (self)
def x0 (self)
def Sx (self)
def Sy (self)
def w (self)
def Om2 (self)
def eps2 (self)
def x1 (self)
def y1 (self)
def Z2 (self)
def Z (self)
def BaseMatrix (self)
def R_T (self)
def H (self)
def X (self)
def M (self)
def H_perp (self)
def N (self)
Public Attributes
sols
Public Attributes inherited from nusol.NuSol
mW2
mT2
mN2
METx
METy
Detailed Description
Definition at line 199 of file nusol.py.
Constructor & Destructor Documentation
__init__()
def nusol.SingleNu.__init__ (self, b, mu, ev)
Definition at line 201 of file nusol.py.
     def __init__(self, b, mu, ev):
         t = NuSol(b, mu, ev)
         self._M = t.M
         self._X = t.X
         self._H = t.H
         sols, _ = intersections_ellipses(self._M, UnitCircle())
         self.sols = sorted(sols, key = self.calcX2)
References nusol.SingleNu._H, nusol.SingleNu._M, nusol.SingleNu._X, nusol.intersections_ellipses(), and nusol.UnitCircle().
Member Function Documentation
calcX2()
def nusol.SingleNu.calcX2 (self, t)
Definition at line 210 of file nusol.py.
     def calcX2(self, t): return np.dot(t, self._X).dot(t)
References nusol.SingleNu._X.
Referenced by nusol.SingleNu.chi2(), and validation.nusol.SingleNu.chi2().
chi2()
def nusol.SingleNu.chi2 (self)
Definition at line 213 of file nusol.py.
     def chi2(self): return np.array([self.calcX2(self.sols[i]) for i in range(len(self.sols))])
References nusol.SingleNu.calcX2(), and nusol.SingleNu.sols.
nu()
def nusol.SingleNu.nu (self)
Definition at line 216 of file nusol.py.
     def nu(self): return np.array([self._H.dot(self.sols[i]) for i in range(len(self.sols))])
References nusol.SingleNu._H, and nusol.SingleNu.sols.
Member Data Documentation
sols
nusol.SingleNu.sols
Definition at line 208 of file nusol.py.
Referenced by nusol.SingleNu.chi2(), validation.nusol.SingleNu.chi2(), validation.nusol.SingleNu.nu(), and nusol.SingleNu.nu().
The documentation for this class was generated from the following file:
nusol.py