AnalysisG: zprime Class Reference
zprime Class Reference
#include <gnn-particles.h>
Public Member Functions
zprime ()
~zprime ()
zprime ()
~zprime () override
selection_template * clone () override
Creates a clone of this particle.
bool selection (event_template *ev) override
The main selection method to override.
bool strategy (event_template *ev) override
Alternative selection strategy method.
void merge (selection_template *sl) override
Merges results from another selection.
zprime ()
~zprime () override
selection_template * clone () override
Creates a clone of this particle.
bool selection (event_template *ev) override
The main selection method to override.
bool strategy (event_template *ev) override
Alternative selection strategy method.
void merge (selection_template *sl) override
Merges results from another selection.
void to_cartesian ()
Converts internal representation to Cartesian coordinates.
void to_polar ()
Converts internal representation to polar coordinates.
bool is (std::vector< int > p)
Checks if particle matches any of the given PDG IDs.
double DeltaR (particle_template *p)
Calculates the angular separation ΔR from another particle.
bool operator== (particle_template &p)
Equality comparison operator.
template<typename g >
g operator+ (g &p)
Addition operator for combining particles.
void operator+= (particle_template *p)
In-place addition operator.
void iadd (particle_template *p)
In-place addition method (alternative to +=).
bool register_parent (particle_template *p)
Registers a parent particle.
bool register_child (particle_template *p)
Registers a child particle.
void add_leaf (std::string key, std::string leaf="")
Adds a leaf (variable) to read for this particle.
void apply_type_prefix ()
Applies the particle type as a prefix to leaf names.
std::map< std::string, std::map< std::string, particle_t > > __reduce__ ()
Serializes particle data for storage.
virtual void build (std::map< std::string, particle_template * > *event, element_t *el)
Builds the particle from event data.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
virtual void bulk_write (const long *idx, std::string *hx)
Bulk write operation for indices and hashes.
virtual void write (std::vector< particle_template * > *particles, std::string name, particle_enum attrs)
Writes a particle collection to output.
template<typename g >
void write (g *var, std::string name)
Template method to write a variable to output.
template<typename g >
void write (g var, std::string name)
Template method to write a value to output.
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< std::vector< double > > *data)
Switch board for dispatching particle attributes.
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< int > *data)
Switch board overload for integer data.
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< double > *data)
Switch board overload for double data.
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< bool > *data)
Switch board overload for boolean data.
std::vector< std::map< std::string, float > > reverse_hash (std::vector< std::string > *hashes)
Reverses hash strings to their original weight maps.
bool CompileEvent ()
Compiles the event for this selection.
selection_template * build (event_template *ev)
Builds the selection from an event.
bool operator== (selection_template &p)
Equality comparison operator.
template<typename g , typename k >
void sum (std::vector< g * > *ch, k **out)
Sums particles into a combined particle.
template<typename g >
g * sum (std::map< std::string, g * > *ch)
Sums particles from a map and returns the combined particle.
template<typename g >
float sum (std::vector< g * > *ch)
Sums particles and returns the invariant mass in GeV.
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
template<typename g >
void safe_delete (std::vector< g * > *particles)
Safely deletes particles not marked for preservation.
template<typename g >
std::vector< g * > vectorize (std::map< std::string, g * > *in)
Converts a map to a vector.
template<typename g >
std::vector< g * > make_unique (std::vector< g * > *inpt)
Removes duplicate particles based on hash.
template<typename g >
void downcast (std::vector< g * > *inpt, std::vector< particle_template * > *out)
Downcasts particles to base particle_template type.
template<typename o , typename g >
void upcast (std::map< std::string, o * > *inpt, std::vector< g * > *out)
Upcasts particles from a map to a derived type.
template<typename o , typename g >
void upcast (std::vector< o * > *inpt, std::vector< g * > *out)
Upcasts particles from a vector to a derived type.
template<typename g >
void get_leptonics (std::map< std::string, g * > inpt, std::vector< particle_template * > *out)
Extracts leptonic particles (leptons and neutrinos) from a map.
template<typename g , typename j >
bool contains (std::vector< g * > *inpt, j *pcheck)
Checks if a particle is contained in a vector.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
Static Public Member Functions
static void set_e (double *, particle_template *)
Setter for energy.
static void get_e (double *, particle_template *)
Getter for energy.
static void set_mass (double *, particle_template *)
Setter for mass.
static void get_mass (double *, particle_template *)
Getter for mass.
static void set_pt (double *, particle_template *)
Setter for pT.
static void get_pt (double *, particle_template *)
Getter for pT.
static void set_eta (double *, particle_template *)
Setter for η.
static void get_eta (double *, particle_template *)
Getter for η.
static void set_phi (double *, particle_template *)
Setter for φ.
static void get_phi (double *, particle_template *)
Getter for φ.
static void set_px (double *, particle_template *)
Setter for px.
static void get_px (double *, particle_template *)
Getter for px.
static void set_py (double *, particle_template *)
Setter for py.
static void get_py (double *, particle_template *)
Getter for py.
static void set_pz (double *, particle_template *)
Setter for pz.
static void get_pz (double *, particle_template *)
Getter for pz.
static void set_pdgid (int *, particle_template *)
Setter for PDG ID.
static void get_pdgid (int *, particle_template *)
Getter for PDG ID.
static void set_symbol (std::string *, particle_template *)
Setter for symbol.
static void get_symbol (std::string *, particle_template *)
Getter for symbol.
static void set_charge (double *, particle_template *)
Setter for charge.
static void get_charge (double *, particle_template *)
Getter for charge.
static void get_hash (std::string *, particle_template *)
Getter for hash.
static void get_isb (bool *, particle_template *)
Getter for is_b.
static void get_islep (bool *, particle_template *)
Getter for is_lep.
static void get_isnu (bool *, particle_template *)
Getter for is_nu.
static void get_isadd (bool *, particle_template *)
Getter for is_add.
static void get_lepdecay (bool *, particle_template *)
Getter for lep_decay.
static void set_parents (std::map< std::string, particle_template * > *, particle_template *)
Setter for parents.
static void get_parents (std::map< std::string, particle_template * > *, particle_template *)
Getter for parents.
static void set_children (std::map< std::string, particle_template * > *, particle_template *)
Setter for children.
static void get_children (std::map< std::string, particle_template * > *, particle_template *)
Getter for children.
static void set_type (std::string *, particle_template *)
Setter for type.
static void get_type (std::string *, particle_template *)
Getter for type.
static void set_index (int *, particle_template *)
Setter for index.
static void get_index (int *, particle_template *)
Getter for index.
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
static void set_name (std::string *, selection_template *)
Setter for name.
static void get_name (std::string *, selection_template *)
Getter for name.
static void set_hash (std::string *, selection_template *)
Setter for hash.
static void get_hash (std::string *, selection_template *)
Getter for hash.
static void get_tree (std::string *, selection_template *)
Getter for tree.
static void set_weight (double *, selection_template *)
Setter for weight.
static void get_weight (double *, selection_template *)
Getter for weight.
static void set_index (long *, selection_template *)
Setter for index.
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Public Attributes
float av_score = 0
int n_leps = 0
int n_nodes = 0
std::vector< float > zprime_truth_tops = {}
std::vector< float > zprime_children = {}
std::vector< float > zprime_truthjets = {}
std::vector< float > zprime_jets = {}
cproperty< double, particle_template > e
Energy property.
cproperty< double, particle_template > mass
Invariant mass property.
cproperty< double, particle_template > pt
Transverse momentum property.
cproperty< double, particle_template > eta
Pseudorapidity property.
cproperty< double, particle_template > phi
Azimuthal angle property.
cproperty< double, particle_template > px
X-momentum property.
cproperty< double, particle_template > py
Y-momentum property.
cproperty< double, particle_template > pz
Z-momentum property.
cproperty< int, particle_template > pdgid
PDG particle ID property.
cproperty< std::string, particle_template > symbol
Particle symbol property.
cproperty< double, particle_template > charge
Electric charge property.
cproperty< std::string, particle_template > hash
Unique hash identifier.
cproperty< bool, particle_template > is_b
Is b-quark/hadron flag.
cproperty< bool, particle_template > is_lep
Is lepton flag.
cproperty< bool, particle_template > is_nu
Is neutrino flag.
cproperty< bool, particle_template > is_add
Is additional radiation flag.
cproperty< bool, particle_template > lep_decay
Leptonic decay flag.
cproperty< std::map< std::string, particle_template * >, particle_template > parents
Parent particles.
cproperty< std::map< std::string, particle_template * >, particle_template > children
Child particles.
cproperty< std::string, particle_template > type
Particle type string.
cproperty< int, particle_template > index
Index in particle collection.
std::map< std::string, particle_template * > m_parents
Map of parent particles by hash.
std::map< std::string, particle_template * > m_children
Map of child particles by hash.
std::map< std::string, std::string > leaves = {}
Map of leaf names.
particle_t data
Internal data structure holding particle properties.
bool _is_serial = false
Flag indicating if particle is being serialized.
bool _is_marked = false
Flag for garbage collection marking.
cproperty< std::string, selection_template > name
Selection name property.
cproperty< std::string, selection_template > hash
Unique hash identifier.
cproperty< std::string, selection_template > tree
Source tree name.
cproperty< double, selection_template > weight
Event weight.
cproperty< long, selection_template > index
Event index.
meta * meta_data = nullptr
Pointer to metadata.
std::string filename = ""
Associated filename.
event_t data
Event data structure.
int threadIdx = -1
Thread index for parallel processing.
std::map< std::string, std::map< std::string, float > > passed_weights = {}
Weights for passed events.
std::map< std::string, meta_t > matched_meta = {}
Matched metadata.
Private Member Functions
void bulk_write_out ()
void merger (selection_template *sl2)
Private Attributes
friend container
std::unordered_map< long, std::string > sequence
bool p_bulk_write = true
write_t * handle = nullptr
event_template * m_event = nullptr
std::map< std::string, std::vector< particle_template * > > garbage = {}
Garbage collection for created particles.
Detailed Description
Definition at line 37 of file gnn-particles.h.
Constructor & Destructor Documentation
zprime() [1/3]
zprime::zprime ()
Definition at line 42 of file gnn/cxx/particles.cxx.
References particle_template::type.
Referenced by clone().
~zprime() [1/3]
zprime::~zprime ()
Definition at line 46 of file gnn/cxx/particles.cxx.
zprime() [2/3]
zprime::zprime ()
~zprime() [2/3]
zprime::~zprime () override
zprime() [3/3]
zprime::zprime ()
~zprime() [3/3]
zprime::~zprime () override
Member Function Documentation
__reduce__()
std::map< std::string, std::map< std::string, particle_t > > particle_template::__reduce__ () inherited
Serializes particle data for storage.
Returns
Nested map structure for serialization.
Definition at line 131 of file particle_template.cxx.
References particle_template::particle_template(), particle_template::_is_serial, particle_template::data, and particle_t::data_p.
absolute_path() [1/2]
std::string tools::absolute_path (std::string path) static inherited
Converts a relative path to an absolute path.
Parameters
path The path to convert.
Returns
The absolute version of the path.
Definition at line 49 of file tools/cxx/io.cxx.
Referenced by analysis::analysis(), analysis::build_events(), io::check_root_file_paths(), and io::trigger_pcm().
absolute_path() [2/2]
std::string tools::absolute_path (std::string path) static inherited
Converts a relative path to an absolute path.
Parameters
path The path to convert.
Returns
The absolute version of the path.
Definition at line 49 of file tools/cxx/io.cxx.
Referenced by analysis::analysis(), analysis::build_events(), io::check_root_file_paths(), and io::trigger_pcm().
add_leaf()
void particle_template::add_leaf (std::string key, std::string leaf = "") inherited
Adds a leaf (variable) to read for this particle.
Parameters
key The internal name for this leaf.
leaf The actual leaf name in the ROOT file (optional, defaults to key).
Definition at line 99 of file interfaces.cxx.
References particle_template::leaves.
Referenced by child::child(), electron::electron(), jet::jet(), jetparton::jetparton(), lepton::lepton(), muon::muon(), particle_gnn::particle_gnn(), parton::parton(), physics_detector::physics_detector(), physics_truth::physics_truth(), top::top(), top_children::top_children(), truthjet::truthjet(), truthjetparton::truthjetparton(), and zboson::zboson().
apply_type_prefix()
void particle_template::apply_type_prefix () inherited
Applies the particle type as a prefix to leaf names.
Definition at line 191 of file particle_template.cxx.
References particle_template::leaves, and particle_template::type.
Referenced by child::child(), electron::electron(), jet::jet(), jetparton::jetparton(), lepton::lepton(), muon::muon(), physics_detector::physics_detector(), physics_truth::physics_truth(), top::top(), top_children::top_children(), truthjet::truthjet(), truthjetparton::truthjetparton(), and zboson::zboson().
build() [1/2]
selection_template * selection_template::build (event_template * ev) inherited
Builds the selection from an event.
Parameters
ev Pointer to the event.
Returns
Pointer to the built selection.
Definition at line 47 of file selection_core.cxx.
References selection_template::clone(), selection_template::data, selection_template::filename, selection_template::m_event, selection_template::name, and selection_template::weight.
build() [2/2]
void particle_template::build (std::map< std::string, particle_template * > * event, element_t * el) virtual inherited
Builds the particle from event data.
Parameters
event Map of particles in the event.
el Element containing raw data.
Reimplemented in top, top_children, truthjet, truthjetparton, jet, jetparton, electron, muon, top, child, physics_detector, physics_truth, electron, muon, jet, particle_gnn, zboson, top, truthjet, jet, electron, muon, parton, and lepton.
Definition at line 199 of file particle_template.cxx.
bulk_write()
void selection_template::bulk_write (const long * idx, std::string * hx) virtual inherited
Bulk write operation for indices and hashes.
Parameters
idx Pointer to the event index.
hx Pointer to the hash string.
Definition at line 8 of file selection_template.cxx.
References selection_template::p_bulk_write.
Referenced by selection_template::bulk_write_out().
bulk_write_out()
void selection_template::bulk_write_out () private inherited
Definition at line 58 of file selection_core.cxx.
References selection_template::bulk_write(), selection_template::handle, selection_template::p_bulk_write, selection_template::sequence, and selection_template::write().
clone() [1/2]
selection_template * zprime::clone () override virtual
Creates a clone of this particle.
Returns
Pointer to the cloned particle.
Reimplemented from particle_template.
Definition at line 6 of file mc16/zprime/zprime.cxx.
References zprime().
clone() [2/2]
selection_template * zprime::clone () override virtual
Creates a clone of this particle.
Returns
Pointer to the cloned particle.
Reimplemented from particle_template.
CompileEvent()
bool selection_template::CompileEvent () inherited
Compiles the event for this selection.
Returns
True if compilation succeeded.
Definition at line 41 of file selection_core.cxx.
References selection_template::m_event, selection_template::selection(), and selection_template::strategy().
contains()
template<typename g , typename j > bool selection_template::contains (std::vector< g * > * inpt, j * pcheck) inline inherited
Checks if a particle is contained in a vector.
Template Parameters
g The particle type in the vector.
j The particle type to check.
Parameters
inpt Pointer to the vector to search.
pcheck Pointer to the particle to find.
Returns
True if the particle is found.
Definition at line 379 of file selection_template.h.
References selection_template::hash.
Referenced by topjets::strategy(), and toptruthjets::strategy().
create_path() [1/2]
void tools::create_path (std::string path) static inherited
Creates a directory path, including parent directories if needed.
Parameters
path The directory path to create.
Definition at line 6 of file tools/cxx/io.cxx.
References f, and tools::split().
Referenced by analysis::analysis(), analysis::build_inference(), plotting::build_path(), analysis::build_project(), container::compile(), metrics::dump_mass_plots(), metric_template::execute(), metrics::generic_painter(), analysis::start(), io::start(), and io::trigger_pcm().
create_path() [2/2]
void tools::create_path (std::string path) static inherited
Creates a directory path, including parent directories if needed.
Parameters
path The directory path to create.
Definition at line 6 of file tools/cxx/io.cxx.
References f, and tools::split().
Referenced by analysis::analysis(), analysis::build_inference(), plotting::build_path(), analysis::build_project(), container::compile(), metrics::dump_mass_plots(), metric_template::execute(), metrics::generic_painter(), analysis::start(), io::start(), and io::trigger_pcm().
delete_path() [1/2]
void tools::delete_path (std::string path) static inherited
Deletes a directory path and its contents.
Parameters
path The directory path to delete.
Definition at line 22 of file tools/cxx/io.cxx.
delete_path() [2/2]
void tools::delete_path (std::string path) static inherited
Deletes a directory path and its contents.
Parameters
path The directory path to delete.
Definition at line 22 of file tools/cxx/io.cxx.
DeltaR()
double particle_template::DeltaR (particle_template * p) inherited
Calculates the angular separation ΔR from another particle.
Parameters
p Pointer to the other particle.
Returns
ΔR = √(Δη² + Δφ²)
Definition at line 3 of file modules/particle/cxx/physics.cxx.
References particle_template::eta, particle_template::phi, and tools::sum().
downcast()
template<typename g > void selection_template::downcast (std::vector< g * > * inpt, std::vector< particle_template * > * out) inline inherited
Downcasts particles to base particle_template type.
Template Parameters
g The derived particle type.
Parameters
inpt Pointer to input vector of derived particles.
out Pointer to output vector of base particles.
Definition at line 326 of file selection_template.h.
Referenced by topjets::strategy(), toptruthjets::strategy(), and strategy().
ends_with() [1/2]
bool tools::ends_with (std::string * inpt, std::string val) static inherited
Checks if a string ends with a specific substring.
Parameters
inpt Pointer to the string to check.
val The substring to check for at the end.
Returns
True if the string ends with the substring, false otherwise.
Definition at line 71 of file strings.cxx.
References l.
Referenced by plotting::build_path(), io::check_root_file_paths(), dataloader::dump_graphs(), tools::ls(), meta::parse_json(), io::scan_keys(), and analysis::start().
ends_with() [2/2]
bool tools::ends_with (std::string * inpt, std::string val) static inherited
Checks if a string ends with a specific substring.
Parameters
inpt Pointer to the string to check.
val The substring to check for at the end.
Returns
True if the string ends with the substring, false otherwise.
Definition at line 71 of file strings.cxx.
References l.
Referenced by plotting::build_path(), io::check_root_file_paths(), dataloader::dump_graphs(), tools::ls(), meta::parse_json(), io::scan_keys(), and analysis::start().
extract() [1/2]
template<typename C , typename T > static void tools::extract (std::vector< T > * prop, std::vector< C * > * src, void(*)(T *, C *) get_prop) inline static inherited
Extracts a specific property from a vector of objects into a new vector.
Template Parameters
C The type of objects in the source vector.
T The type of the property to extract.
Parameters
prop Pointer to the output vector to fill with property values.
src Pointer to the source vector of objects.
get_prop Function pointer to extract the property from an object.
< Clear the properties vector.
< Reserve space for the property values.
< Loop through each object in the source vector.
< Create a default-initialized property variable.
< Call the provided function to extract the property.
< Add the property value to the output vector.
Definition at line 216 of file tools.h.
extract() [2/2]
template<typename C , typename T > static void tools::extract (std::vector< T > * prop, std::vector< C * > * src, void(*)(T *, C *) get_prop) inline static inherited
Extracts a specific property from a vector of objects into a new vector.
Template Parameters
C The type of objects in the source vector.
T The type of the property to extract.
Parameters
prop Pointer to the output vector to fill with property values.
src Pointer to the source vector of objects.
get_prop Function pointer to extract the property from an object.
< Clear the properties vector.
< Reserve space for the property values.
< Loop through each object in the source vector.
< Create a default-initialized property variable.
< Call the provided function to extract the property.
< Add the property value to the output vector.
Definition at line 216 of file tools.h.
flush() [1/2]
template<typename T > static void tools::flush (std::vector< T * > * inpt) inline static inherited
Empties a vector and all objects it points to.
Template Parameters
T The type of pointers in the vector.
Parameters
inpt Pointer to the vector to empty.
< Loop through all elements in the vector.
< Delete the object the pointer points to.
< Set the pointer to nullptr to avoid dangling pointers.
< Clear the vector.
Definition at line 167 of file tools.h.
Referenced by analysis::~analysis(), dataloader::~dataloader(), sampletracer::compile_objects(), and io::root_end().
flush() [2/2]
template<typename T > static void tools::flush (std::vector< T * > * inpt) inline static inherited
Empties a vector and all objects it points to.
Template Parameters
T The type of pointers in the vector.
Parameters
inpt Pointer to the vector to empty.
< Loop through all elements in the vector.
< Delete the object the pointer points to.
< Set the pointer to nullptr to avoid dangling pointers.
< Clear the vector.
Definition at line 167 of file tools.h.
Referenced by analysis::~analysis(), dataloader::~dataloader(), sampletracer::compile_objects(), and io::root_end().
get_charge()
void particle_template::get_charge (double * val, particle_template * prt) static inherited
Getter for charge.
Definition at line 57 of file interfaces.cxx.
References particle_t::charge, and particle_template::data.
Referenced by particle_template::particle_template().
get_children()
void particle_template::get_children (std::map< std::string, particle_template * > * val, particle_template * prt) static inherited
Getter for children.
Definition at line 128 of file interfaces.cxx.
References count(), particle_template::hash, and particle_template::m_children.
Referenced by particle_template::particle_template().
get_e()
void particle_template::get_e (double * v, particle_template * prt) static inherited
Getter for energy.
Definition at line 12 of file modules/particle/cxx/physics.cxx.
References particle_template::data, particle_template::e, particle_template::mass, particle_template::px, particle_template::py, and particle_template::pz.
Referenced by particle_template::particle_template().
get_eta()
void particle_template::get_eta (double * val, particle_template * prt) static inherited
Getter for η.
Definition at line 19 of file polar.cxx.
References particle_template::data, particle_t::eta, and particle_template::to_polar().
Referenced by particle_template::particle_template().
get_hash() [1/2]
void particle_template::get_hash (std::string * val, particle_template * prt) static inherited
Getter for hash.
Definition at line 152 of file interfaces.cxx.
References particle_template::data, particle_template::e, particle_template::hash, particle_template::px, particle_template::py, particle_template::pz, particle_template::to_cartesian(), and tools::to_string().
Referenced by particle_template::particle_template().
get_hash() [2/2]
void selection_template::get_hash (std::string * val, selection_template * ev) static inherited
Getter for hash.
Definition at line 18 of file selection/cxx/properties.cxx.
References selection_template::data, and event_t::hash.
Referenced by selection_template::selection_template().
get_index()
void particle_template::get_index (int * val, particle_template * prt) static inherited
Getter for index.
Definition at line 177 of file interfaces.cxx.
References particle_template::data, and particle_t::index.
Referenced by particle_template::particle_template().
get_isadd()
void particle_template::get_isadd (bool * val, particle_template * prt) static inherited
Getter for is_add.
Definition at line 73 of file interfaces.cxx.
References particle_template::is_b, particle_template::is_lep, and particle_template::is_nu.
Referenced by particle_template::particle_template().
get_isb()
void particle_template::get_isb (bool * val, particle_template * prt) static inherited
Getter for is_b.
Definition at line 61 of file interfaces.cxx.
References particle_template::is().
Referenced by particle_template::particle_template().
get_islep()
void particle_template::get_islep (bool * val, particle_template * prt) static inherited
Getter for is_lep.
Definition at line 69 of file interfaces.cxx.
References particle_template::data, particle_template::is(), and particle_t::lepdef.
Referenced by particle_template::particle_template().
get_isnu()
void particle_template::get_isnu (bool * val, particle_template * prt) static inherited
Getter for is_nu.
Definition at line 65 of file interfaces.cxx.
References particle_template::data, particle_template::is(), and particle_t::nudef.
Referenced by particle_template::particle_template().
get_lepdecay()
void particle_template::get_lepdecay (bool * val, particle_template * prt) static inherited
Getter for lep_decay.
Definition at line 86 of file interfaces.cxx.
References particle_template::children, particle_template::is_lep, and particle_template::is_nu.
Referenced by particle_template::particle_template().
get_leptonics()
template<typename g > void selection_template::get_leptonics (std::map< std::string, g * > inpt, std::vector< particle_template * > * out) inline inherited
Extracts leptonic particles (leptons and neutrinos) from a map.
Template Parameters
g The particle type.
Parameters
inpt Input map of particles.
out Pointer to output vector.
Definition at line 362 of file selection_template.h.
References is_lep, and is_nu.
Referenced by topjets::strategy(), and toptruthjets::strategy().
get_mass()
void particle_template::get_mass (double * val, particle_template * prt) static inherited
Getter for mass.
Definition at line 31 of file modules/particle/cxx/physics.cxx.
References particle_template::data, particle_template::e, particle_template::mass, particle_template::px, particle_template::py, and particle_template::pz.
Referenced by particle_template::particle_template().
get_name()
void selection_template::get_name (std::string * name, selection_template * ev) static inherited
Getter for name.
Definition at line 7 of file selection/cxx/properties.cxx.
References selection_template::data, and event_t::name.
Referenced by selection_template::selection_template().
get_parents()
void particle_template::get_parents (std::map< std::string, particle_template * > * val, particle_template * prt) static inherited
Getter for parents.
Definition at line 112 of file interfaces.cxx.
References count(), particle_template::hash, and particle_template::m_parents.
Referenced by particle_template::particle_template().
get_pdgid()
void particle_template::get_pdgid (int * val, particle_template * prt) static inherited
Getter for PDG ID.
Definition at line 7 of file interfaces.cxx.
References particle_template::data, particle_template::pdgid, and particle_template::symbol.
Referenced by particle_template::particle_template().
get_phi()
void particle_template::get_phi (double * val, particle_template * prt) static inherited
Getter for φ.
Definition at line 30 of file polar.cxx.
References particle_template::data, particle_t::phi, and particle_template::to_polar().
Referenced by particle_template::particle_template().
get_pt()
void particle_template::get_pt (double * val, particle_template * prt) static inherited
Getter for pT.
Definition at line 8 of file polar.cxx.
References particle_template::data, particle_t::pt, and particle_template::to_polar().
Referenced by particle_template::particle_template().
get_px()
void particle_template::get_px (double * val, particle_template * prt) static inherited
Getter for px.
Definition at line 8 of file cartesian.cxx.
References particle_template::data, particle_t::px, and particle_template::to_cartesian().
Referenced by particle_template::particle_template().
get_py()
void particle_template::get_py (double * val, particle_template * prt) static inherited
Getter for py.
Definition at line 18 of file cartesian.cxx.
References particle_template::data, particle_t::py, and particle_template::to_cartesian().
Referenced by particle_template::particle_template().
get_pz()
void particle_template::get_pz (double * val, particle_template * prt) static inherited
Getter for pz.
Definition at line 28 of file cartesian.cxx.
References particle_template::data, particle_t::pz, and particle_template::to_cartesian().
Referenced by particle_template::particle_template().
get_symbol()
void particle_template::get_symbol (std::string * val, particle_template * prt) static inherited
Getter for symbol.
Definition at line 35 of file interfaces.cxx.
References particle_template::data, particle_template::pdgid, and particle_template::symbol.
Referenced by particle_template::particle_template().
get_tree()
void selection_template::get_tree (std::string * name, selection_template * ev) static inherited
Getter for tree.
Definition at line 22 of file selection/cxx/properties.cxx.
References selection_template::data, and event_t::tree.
Referenced by selection_template::selection_template().
get_type()
void particle_template::get_type (std::string * val, particle_template * prt) static inherited
Getter for type.
Definition at line 169 of file interfaces.cxx.
References particle_template::data, and particle_t::type.
Referenced by particle_template::particle_template().
get_weight()
void selection_template::get_weight (double * inpt, selection_template * ev) static inherited
Getter for weight.
Definition at line 30 of file selection/cxx/properties.cxx.
References selection_template::data, and event_t::weight.
Referenced by selection_template::selection_template().
has_string() [1/2]
bool tools::has_string (std::string * inpt, std::string trg) static inherited
Checks if a string contains a specific substring.
Parameters
inpt Pointer to the string to check.
trg The substring to search for.
Returns
True if the substring is found, false otherwise.
Definition at line 65 of file strings.cxx.
References f.
Referenced by analysis::check_cache(), meta::compiler(), metrics::generic_painter(), dataloader::restore_graphs_(), meta::scan_sow(), model_template::set_device(), and metric_template::set_run_name().
has_string() [2/2]
bool tools::has_string (std::string * inpt, std::string trg) static inherited
Checks if a string contains a specific substring.
Parameters
inpt Pointer to the string to check.
trg The substring to search for.
Returns
True if the substring is found, false otherwise.
Definition at line 65 of file strings.cxx.
References f.
Referenced by analysis::check_cache(), meta::compiler(), metrics::generic_painter(), dataloader::restore_graphs_(), meta::scan_sow(), model_template::set_device(), and metric_template::set_run_name().
has_value() [1/2]
bool tools::has_value (std::vector< std::string > * data, std::string trg) static inherited
Checks if a vector of strings contains a specific string.
Parameters
data Pointer to the vector to search.
trg The string to search for.
Returns
True if the string is found in the vector, false otherwise.
Definition at line 77 of file strings.cxx.
Referenced by io::scan_keys().
has_value() [2/2]
bool tools::has_value (std::vector< std::string > * data, std::string trg) static inherited
Checks if a vector of strings contains a specific string.
Parameters
data Pointer to the vector to search.
trg The string to search for.
Returns
True if the string is found in the vector, false otherwise.
Definition at line 77 of file strings.cxx.
Referenced by io::scan_keys().
iadd()
void particle_template::iadd (particle_template * p) inherited
In-place addition method (alternative to +=).
Parameters
p Pointer to the particle to add.
Definition at line 183 of file particle_template.cxx.
is()
bool particle_template::is (std::vector< int > p) inherited
Checks if particle matches any of the given PDG IDs.
Parameters
p Vector of PDG IDs to check against.
Returns
True if particle's PDG ID matches any in the vector.
Definition at line 78 of file interfaces.cxx.
References particle_template::data, i, and particle_t::pdgid.
Referenced by particle_template::get_isb(), particle_template::get_islep(), and particle_template::get_isnu().
is_file() [1/2]
bool tools::is_file (std::string path) static inherited
Checks if a path refers to an existing file.
Parameters
path The path to check.
Returns
True if the path is a file and exists, false otherwise.
Definition at line 30 of file tools/cxx/io.cxx.
Referenced by io::check_root_file_paths(), analysis::initialize_loop(), metric_template::set_run_name(), and io::start().
is_file() [2/2]
bool tools::is_file (std::string path) static inherited
Checks if a path refers to an existing file.
Parameters
path The path to check.
Returns
True if the path is a file and exists, false otherwise.
Definition at line 30 of file tools/cxx/io.cxx.
Referenced by io::check_root_file_paths(), analysis::initialize_loop(), metric_template::set_run_name(), and io::start().
ls() [1/2]
std::vector< std::string > tools::ls (std::string path, std::string ext = "") static inherited
Lists files in a directory, optionally filtered by extension.
Parameters
path The directory to search.
ext File extension filter. If empty, all files are listed.
Returns
A vector of filenames in the directory.
Definition at line 35 of file tools/cxx/io.cxx.
References tools::ends_with(), and tools::split().
Referenced by analysis::analysis(), analysis::check_cache(), io::check_root_file_paths(), dataloader::restore_graphs(), and io::trigger_pcm().
ls() [2/2]
std::vector< std::string > tools::ls (std::string path, std::string ext = "") static inherited
Lists files in a directory, optionally filtered by extension.
Parameters
path The directory to search.
ext File extension filter. If empty, all files are listed.
Returns
A vector of filenames in the directory.
Definition at line 35 of file tools/cxx/io.cxx.
References tools::ends_with(), and tools::split().
Referenced by analysis::analysis(), analysis::check_cache(), io::check_root_file_paths(), dataloader::restore_graphs(), and io::trigger_pcm().
make_unique()
template<typename g > std::vector< g * > selection_template::make_unique (std::vector< g * > * inpt) inline inherited
Removes duplicate particles based on hash.
Template Parameters
g The particle type.
Parameters
inpt Pointer to input vector.
Returns
Vector with duplicates removed.
Definition at line 306 of file selection_template.h.
References selection_template::hash.
Referenced by combinatorial::reconstruction(), parton::strategy(), topjets::strategy(), toptruthjets::strategy(), and parton::top_mass_contribution().
merge() [1/2]
void zprime::merge (selection_template * sel) override virtual
Merges results from another selection.
Parameters
sel Pointer to the selection to merge from.
Reimplemented from selection_template.
Definition at line 10 of file mc16/zprime/zprime.cxx.
References selection_template::write(), zprime_children, zprime_jets, zprime_truth_tops, and zprime_truthjets.
merge() [2/2]
void zprime::merge (selection_template * sel) override virtual
Merges results from another selection.
Parameters
sel Pointer to the selection to merge from.
Reimplemented from selection_template.
merger()
void selection_template::merger (selection_template * sl2) private inherited
Definition at line 67 of file selection_core.cxx.
References selection_template::filename, selection_template::hash, selection_template::index, selection_template::m_event, selection_template::matched_meta, selection_template::merge(), merge_data(), selection_template::meta_data, selection_template::p_bulk_write, selection_template::passed_weights, selection_template::sequence, selection_template::weight, and selection_template::write().
operator+()
template<typename g > g particle_template::operator+ (g & p) inline inherited
Addition operator for combining particles.
Template Parameters
g The particle type (must inherit from particle_template).
Parameters
p The particle to add.
Returns
A new particle with combined four-momentum.
Definition at line 239 of file particle_template.h.
References particle_template::data, particle_template::e, particle_template::px, particle_template::py, particle_template::pz, and particle_t::type.
operator+=()
void particle_template::operator+= (particle_template * p) inherited
In-place addition operator.
Parameters
p Pointer to the particle to add.
Definition at line 173 of file particle_template.cxx.
References particle_template::data, particle_template::e, particle_t::e, particle_t::polar, particle_template::px, particle_t::px, particle_template::py, particle_t::py, particle_template::pz, particle_t::pz, and particle_template::to_cartesian().
operator==() [1/2]
bool particle_template::operator== (particle_template & p) inherited
Equality comparison operator.
Parameters
p The particle to compare against.
Returns
True if particles have the same hash.
Definition at line 187 of file particle_template.cxx.
References particle_template::hash.
operator==() [2/2]
bool selection_template::operator== (selection_template & p) inherited
Equality comparison operator.
Parameters
p The selection to compare against.
Returns
True if selections are equal.
Definition at line 38 of file selection_core.cxx.
References selection_template::hash.
put() [1/2]
template<typename g > static void tools::put (std::vector< g * > * out, std::vector< g * > * src, std::vector< int > * trg) inline static inherited
Fills a vector with pointers from another vector based on a selection index.
Template Parameters
g The type of objects being pointed to.
Parameters
out Pointer to the output vector to fill.
src Pointer to the source vector to select from.
trg Pointer to a vector of indices for selection.
< Clear the output vector.
< Reserve space for the output elements.
< Loop through each selected index.
< Get the object at the selected index.
< Add it to the output vector.
< Mark the object as in use.
Definition at line 197 of file tools.h.
Referenced by dataloader::get_k_train_set(), dataloader::get_k_validation_set(), and dataloader::get_test_set().
put() [2/2]
template<typename g > static void tools::put (std::vector< g * > * out, std::vector< g * > * src, std::vector< int > * trg) inline static inherited
Fills a vector with pointers from another vector based on a selection index.
Template Parameters
g The type of objects being pointed to.
Parameters
out Pointer to the output vector to fill.
src Pointer to the source vector to select from.
trg Pointer to a vector of indices for selection.
< Clear the output vector.
< Reserve space for the output elements.
< Loop through each selected index.
< Get the object at the selected index.
< Add it to the output vector.
< Mark the object as in use.
Definition at line 197 of file tools.h.
Referenced by dataloader::get_k_train_set(), dataloader::get_k_validation_set(), and dataloader::get_test_set().
register_child()
bool particle_template::register_child (particle_template * p) inherited
Registers a child particle.
Parameters
p Pointer to the child particle.
Returns
True if registration was successful.
Definition at line 136 of file interfaces.cxx.
References particle_t::children, particle_template::data, particle_template::hash, and particle_template::m_children.
Referenced by particle_template::set_children().
register_parent()
bool particle_template::register_parent (particle_template * p) inherited
Registers a parent particle.
Parameters
p Pointer to the parent particle.
Returns
True if registration was successful.
Definition at line 144 of file interfaces.cxx.
References particle_template::data, particle_template::hash, particle_template::m_parents, and particle_t::parents.
Referenced by particle_template::set_parents().
rename() [1/2]
void tools::rename (std::string start, std::string target) static inherited
Renames a file or directory.
Parameters
start The original path.
target The new path.
Definition at line 18 of file tools/cxx/io.cxx.
Referenced by dataloader::dump_graphs().
rename() [2/2]
void tools::rename (std::string start, std::string target) static inherited
Renames a file or directory.
Parameters
start The original path.
target The new path.
Definition at line 18 of file tools/cxx/io.cxx.
Referenced by dataloader::dump_graphs().
replace() [1/2]
void tools::replace (std::string * in, std::string repl_str, std::string repl_with) static inherited
Replaces all occurrences of a substring in a string.
Parameters
in Pointer to the string to modify.
repl_str The substring to replace.
repl_with The replacement string.
Definition at line 5 of file strings.cxx.
Referenced by analysis::build_graphs(), analysis::check_cache(), dataloader::dump_graphs(), meta::get_campaign(), meta::parse_json(), and analysis::start().
replace() [2/2]
void tools::replace (std::string * in, std::string repl_str, std::string repl_with) static inherited
Replaces all occurrences of a substring in a string.
Parameters
in Pointer to the string to modify.
repl_str The substring to replace.
repl_with The replacement string.
Definition at line 5 of file strings.cxx.
Referenced by analysis::build_graphs(), analysis::check_cache(), dataloader::dump_graphs(), meta::get_campaign(), meta::parse_json(), and analysis::start().
reverse_hash()
std::vector< std::map< std::string, float > > selection_template::reverse_hash (std::vector< std::string > * hashes) inherited
Reverses hash strings to their original weight maps.
Parameters
hashes Pointer to vector of hash strings.
Returns
Vector of weight maps.
Definition at line 84 of file selection_core.cxx.
References selection_template::hash, and selection_template::passed_weights.
safe_delete()
template<typename g > void selection_template::safe_delete (std::vector< g * > * particles) inline inherited
Safely deletes particles not marked for preservation.
Template Parameters
g The particle type.
Parameters
particles Pointer to vector of particles.
Definition at line 250 of file selection_template.h.
Referenced by combinatorial::~combinatorial(), and validation::~validation().
selection() [1/2]
bool zprime::selection (event_template * ev) override virtual
The main selection method to override.
Parameters
ev Pointer to the event to evaluate.
Returns
True if the event passes the selection, false otherwise.
Reimplemented from selection_template.
Definition at line 18 of file mc16/zprime/zprime.cxx.
selection() [2/2]
bool zprime::selection (event_template * ev) override virtual
The main selection method to override.
Parameters
ev Pointer to the event to evaluate.
Returns
True if the event passes the selection, false otherwise.
Reimplemented from selection_template.
set_charge()
void particle_template::set_charge (double * val, particle_template * prt) static inherited
Setter for charge.
Definition at line 53 of file interfaces.cxx.
References particle_t::charge, and particle_template::data.
Referenced by particle_template::particle_template().
set_children()
void particle_template::set_children (std::map< std::string, particle_template * > * val, particle_template * prt) static inherited
Setter for children.
Definition at line 120 of file interfaces.cxx.
References particle_t::children, particle_template::data, particle_template::m_children, and particle_template::register_child().
Referenced by particle_template::particle_template().
set_e()
void particle_template::set_e (double * val, particle_template * prt) static inherited
Setter for energy.
Definition at line 23 of file modules/particle/cxx/physics.cxx.
References particle_template::data, and particle_t::e.
Referenced by particle_template::particle_template().
set_eta()
void particle_template::set_eta (double * val, particle_template * prt) static inherited
Setter for η.
Definition at line 14 of file polar.cxx.
References particle_t::cartesian, particle_template::data, and particle_t::eta.
Referenced by particle_template::particle_template().
set_hash()
void selection_template::set_hash (std::string * path, selection_template * ev) static inherited
Setter for hash.
Definition at line 11 of file selection/cxx/properties.cxx.
References selection_template::data, event_t::hash, selection_template::index, and tools::to_string().
Referenced by selection_template::selection_template().
set_index() [1/2]
void particle_template::set_index (int * val, particle_template * prt) static inherited
Setter for index.
Definition at line 173 of file interfaces.cxx.
References particle_template::data, and particle_t::index.
Referenced by particle_template::particle_template().
set_index() [2/2]
void selection_template::set_index (long * inpt, selection_template * ev) static inherited
Setter for index.
Definition at line 34 of file selection/cxx/properties.cxx.
References selection_template::data, and event_t::index.
Referenced by selection_template::selection_template().
set_mass()
void particle_template::set_mass (double * val, particle_template * prt) static inherited
Setter for mass.
Definition at line 27 of file modules/particle/cxx/physics.cxx.
References particle_template::data, and particle_t::mass.
Referenced by particle_template::particle_template().
set_name()
void selection_template::set_name (std::string * name, selection_template * ev) static inherited
Setter for name.
Definition at line 3 of file selection/cxx/properties.cxx.
References selection_template::data, selection_template::name, and event_t::name.
Referenced by selection_template::selection_template().
set_parents()
void particle_template::set_parents (std::map< std::string, particle_template * > * val, particle_template * prt) static inherited
Setter for parents.
Definition at line 104 of file interfaces.cxx.
References particle_template::data, particle_template::m_parents, particle_t::parents, and particle_template::register_parent().
Referenced by particle_template::particle_template().
set_pdgid()
void particle_template::set_pdgid (int * val, particle_template * prt) static inherited
Setter for PDG ID.
Definition at line 3 of file interfaces.cxx.
References particle_template::data, and particle_t::pdgid.
Referenced by particle_template::particle_template().
set_phi()
void particle_template::set_phi (double * val, particle_template * prt) static inherited
Setter for φ.
Definition at line 24 of file polar.cxx.
References particle_t::cartesian, particle_template::data, and particle_t::phi.
Referenced by particle_template::particle_template().
set_pt()
void particle_template::set_pt (double * val, particle_template * prt) static inherited
Setter for pT.
Definition at line 3 of file polar.cxx.
References particle_t::cartesian, particle_template::data, and particle_t::pt.
Referenced by particle_template::particle_template().
set_px()
void particle_template::set_px (double * val, particle_template * prt) static inherited
Setter for px.
Definition at line 3 of file cartesian.cxx.
References particle_template::data, particle_t::polar, and particle_t::px.
Referenced by particle_template::particle_template().
set_py()
void particle_template::set_py (double * val, particle_template * prt) static inherited
Setter for py.
Definition at line 13 of file cartesian.cxx.
References particle_template::data, particle_t::polar, and particle_t::py.
Referenced by particle_template::particle_template().
set_pz()
void particle_template::set_pz (double * val, particle_template * prt) static inherited
Setter for pz.
Definition at line 23 of file cartesian.cxx.
References particle_template::data, particle_t::polar, and particle_t::pz.
Referenced by particle_template::particle_template().
set_symbol()
void particle_template::set_symbol (std::string * val, particle_template * prt) static inherited
Setter for symbol.
Definition at line 31 of file interfaces.cxx.
References particle_template::data, and particle_t::symbol.
Referenced by particle_template::particle_template().
set_type()
void particle_template::set_type (std::string * val, particle_template * prt) static inherited
Setter for type.
Definition at line 165 of file interfaces.cxx.
References particle_template::data, and particle_t::type.
Referenced by particle_template::particle_template().
set_weight()
void selection_template::set_weight (double * inpt, selection_template * ev) static inherited
Setter for weight.
Definition at line 26 of file selection/cxx/properties.cxx.
References selection_template::data, and event_t::weight.
Referenced by selection_template::selection_template().
split() [1/2]
std::vector< std::string > tools::split (std::string inpt, std::string del) inherited
Splits a string into a vector of substrings based on a delimiter.
Parameters
inpt The input string to split.
del The delimiter.
Returns
A vector of substrings.
Definition at line 23 of file strings.cxx.
References index.
Referenced by analysis::build_events(), analysis::build_graphs(), analysis::build_inference(), event_template::build_mapping(), analysis::check_cache(), container::compile(), sampletracer::compile_objects(), meta::compiler(), tools::create_path(), dataloader::dump_graphs(), meta::hash(), tools::ls(), graph_t::meta_deserialize(), dataloader::restore_graphs_(), io::root_begin(), model_template::set_device(), metric_template::set_run_name(), metric_template::set_variables(), and analysis::start().
split() [2/2]
std::vector< std::string > tools::split (std::string inpt, std::string del) inherited
Splits a string into a vector of substrings based on a delimiter.
Parameters
inpt The input string to split.
del The delimiter.
Returns
A vector of substrings.
Definition at line 23 of file strings.cxx.
References index.
Referenced by analysis::build_events(), analysis::build_graphs(), analysis::build_inference(), event_template::build_mapping(), analysis::check_cache(), container::compile(), sampletracer::compile_objects(), meta::compiler(), tools::create_path(), dataloader::dump_graphs(), meta::hash(), tools::ls(), graph_t::meta_deserialize(), dataloader::restore_graphs_(), io::root_begin(), model_template::set_device(), metric_template::set_run_name(), metric_template::set_variables(), and analysis::start().
strategy() [1/2]
bool zprime::strategy (event_template * ev) override virtual
Alternative selection strategy method.
Parameters
ev Pointer to the event to evaluate.
Returns
True if the event passes, false otherwise.
Reimplemented from selection_template.
Definition at line 30 of file mc16/zprime/zprime.cxx.
References particle_template::children, selection_template::downcast(), particle_template::is_lep, particle_template::is_nu, particle_template::mass, merge_data(), selection_template::sum(), selection_template::vectorize(), zprime_children, zprime_jets, zprime_truth_tops, and zprime_truthjets.
strategy() [2/2]
bool zprime::strategy (event_template * ev) override virtual
Alternative selection strategy method.
Parameters
ev Pointer to the event to evaluate.
Returns
True if the event passes, false otherwise.
Reimplemented from selection_template.
sum() [1/5]
template<typename g > g * selection_template::sum (std::map< std::string, g * > * ch) inline inherited
Sums particles from a map and returns the combined particle.
Template Parameters
g The particle type.
Parameters
ch Pointer to map of particles.
Returns
Pointer to the summed particle.
Definition at line 265 of file selection_template.h.
References selection_template::sum(), and selection_template::vectorize().
sum() [2/5]
template<typename g > float selection_template::sum (std::vector< g * > * ch) inline inherited
Sums particles and returns the invariant mass in GeV.
Template Parameters
g The particle type.
Parameters
ch Pointer to vector of particles.
Returns
Invariant mass of the combined system in GeV.
Definition at line 279 of file selection_template.h.
References mass, and selection_template::sum().
sum() [3/5]
template<typename g , typename k > void selection_template::sum (std::vector< g * > * ch, k ** out) inline inherited
Sums particles into a combined particle.
Template Parameters
g Input particle type.
k Output particle type.
Parameters
ch Pointer to vector of particles to sum.
out Pointer to output particle pointer.
Definition at line 230 of file selection_template.h.
References selection_template::garbage, and selection_template::hash.
Referenced by matching::dump(), validation::reconstruction(), childrenkinematics::strategy(), decaymodes::strategy(), parton::strategy(), topjets::strategy(), topmatching::strategy(), toptruthjets::strategy(), strategy(), selection_template::sum(), selection_template::sum(), and parton::top_mass_contribution().
sum() [4/5]
template<typename g > g tools::sum (std::vector< g > * inpt) inline inherited
Sums the elements of a vector.
Template Parameters
g The type of elements in the vector.
Parameters
inpt Pointer to the vector to sum.
Returns
The sum of all elements.
< Initialize the output variable.
< Return the sum.
Definition at line 183 of file tools.h.
Referenced by metrics::add_th1f_accuracy(), sampletracer::compile_objects(), particle_template::DeltaR(), graph_template::double_neutrino(), grift::forward(), recursivegraphneuralnetwork::forward(), matching::match_obj(), and grift::message().
sum() [5/5]
template<typename g > g tools::sum (std::vector< g > * inpt) inline inherited
Sums the elements of a vector.
Template Parameters
g The type of elements in the vector.
Parameters
inpt Pointer to the vector to sum.
Returns
The sum of all elements.
< Initialize the output variable.
< Return the sum.
Definition at line 183 of file tools.h.
Referenced by metrics::add_th1f_accuracy(), sampletracer::compile_objects(), particle_template::DeltaR(), graph_template::double_neutrino(), grift::forward(), recursivegraphneuralnetwork::forward(), matching::match_obj(), and grift::message().
switch_board() [1/4]
void selection_template::switch_board (particle_enum attrs, particle_template * ptr, std::vector< bool > * data) inherited
Switch board overload for boolean data.
Definition at line 122 of file selection_core.cxx.
References selection_template::data, is_add, is_b, is_lep, and is_nu.
switch_board() [2/4]
void selection_template::switch_board (particle_enum attrs, particle_template * ptr, std::vector< double > * data) inherited
Switch board overload for double data.
Definition at line 107 of file selection_core.cxx.
References charge, selection_template::data, energy, eta, mass, phi, pt, px, py, and pz.
switch_board() [3/4]
void selection_template::switch_board (particle_enum attrs, particle_template * ptr, std::vector< int > * data) inherited
Switch board overload for integer data.
Definition at line 99 of file selection_core.cxx.
References selection_template::data, selection_template::index, index, and pdgid.
switch_board() [4/4]
void selection_template::switch_board (particle_enum attrs, particle_template * ptr, std::vector< std::vector< double > > * data) inherited
Switch board for dispatching particle attributes.
Parameters
attrs The attribute type to extract.
ptr Pointer to the particle.
data Output vector for 2D double data.
Definition at line 132 of file selection_core.cxx.
References selection_template::data, energy, eta, phi, pmc, pmu, pt, px, py, pz, and selection_template::switch_board().
Referenced by selection_template::switch_board(), and selection_template::write().
to_cartesian()
void particle_template::to_cartesian () inherited
Converts internal representation to Cartesian coordinates.
Definition at line 33 of file cartesian.cxx.
References particle_template::data, particle_template::eta, particle_template::phi, particle_template::pt, particle_template::px, particle_template::py, and particle_template::pz.
Referenced by particle_template::get_hash(), particle_template::get_px(), particle_template::get_py(), particle_template::get_pz(), and particle_template::operator+=().
to_polar()
void particle_template::to_polar () inherited
Converts internal representation to polar coordinates.
Definition at line 35 of file polar.cxx.
References particle_template::data, particle_template::eta, particle_template::phi, particle_template::pt, particle_template::px, particle_template::py, and particle_template::pz.
Referenced by particle_template::get_eta(), particle_template::get_phi(), and particle_template::get_pt().
to_string() [1/4]
std::string tools::to_string (double val) static inherited
Converts a double value to a string with standard precision.
Parameters
val The double value to convert.
Returns
The string representation of the value.
Definition at line 59 of file strings.cxx.
Referenced by dataloader::generate_kfold_set(), dataloader::generate_test_set(), particle_template::get_hash(), topefficiency::region(), dataloader::restore_dataset(), event_template::set_hash(), selection_template::set_hash(), parton::strategy(), topjets::strategy(), toptruthjets::strategy(), and parton::top_mass_contribution().
to_string() [2/4]
std::string tools::to_string (double val) static inherited
Converts a double value to a string with standard precision.
Parameters
val The double value to convert.
Returns
The string representation of the value.
Definition at line 59 of file strings.cxx.
Referenced by dataloader::generate_kfold_set(), dataloader::generate_test_set(), particle_template::get_hash(), topefficiency::region(), dataloader::restore_dataset(), event_template::set_hash(), selection_template::set_hash(), parton::strategy(), topjets::strategy(), toptruthjets::strategy(), and parton::top_mass_contribution().
to_string() [3/4]
std::string tools::to_string (double val, int prec) static inherited
Converts a double value to a string with specified precision.
Parameters
val The double value to convert.
prec The number of decimal places to consider.
Returns
The string representation of the value.
Definition at line 91 of file strings.cxx.
to_string() [4/4]
std::string tools::to_string (double val, int prec) static inherited
Converts a double value to a string with specified precision.
Parameters
val The double value to convert.
prec The number of decimal places to consider.
Returns
The string representation of the value.
Definition at line 91 of file strings.cxx.
trim() [1/2]
std::string tools::trim (std::string s) inherited
Removes whitespace from the beginning and end of a string.
Parameters
s The string to trim.
Returns
The trimmed string.
trim() [2/2]
std::string tools::trim (std::string s) inherited
Removes whitespace from the beginning and end of a string.
Parameters
s The string to trim.
Returns
The trimmed string.
type_name() [1/2]
template<typename T > std::string tools::type_name () inline inherited
Gets the type name of a variable as a string (for debugging).
Template Parameters
T The type to get the name of.
Returns
The name of the type as a string.
< Gets the type name via RTTI.
< Returns the type name.
Definition at line 155 of file tools.h.
Referenced by event_template::build_mapping().
type_name() [2/2]
template<typename T > std::string tools::type_name () inline inherited
Gets the type name of a variable as a string (for debugging).
Template Parameters
T The type to get the name of.
Returns
The name of the type as a string.
< Gets the type name via RTTI.
< Returns the type name.
Definition at line 155 of file tools.h.
Referenced by event_template::build_mapping().
upcast() [1/2]
template<typename o , typename g > void selection_template::upcast (std::map< std::string, o * > * inpt, std::vector< g * > * out) inline inherited
Upcasts particles from a map to a derived type.
Template Parameters
o The source particle type.
g The target particle type.
Parameters
inpt Pointer to input map.
out Pointer to output vector.
Definition at line 338 of file selection_template.h.
Referenced by regions::strategy(), parton::strategy(), and parton::top_mass_contribution().
upcast() [2/2]
template<typename o , typename g > void selection_template::upcast (std::vector< o * > * inpt, std::vector< g * > * out) inline inherited
Upcasts particles from a vector to a derived type.
Template Parameters
o The source particle type.
g The target particle type.
Parameters
inpt Pointer to input vector.
out Pointer to output vector.
Definition at line 351 of file selection_template.h.
vectorize()
template<typename g > std::vector< g * > selection_template::vectorize (std::map< std::string, g * > * in) inline inherited
Converts a map to a vector.
Template Parameters
g The value type in the map.
Parameters
in Pointer to the input map.
Returns
Vector of values from the map.
Definition at line 292 of file selection_template.h.
Referenced by matching::current(), matching::experimental(), matching::match_obj(), matching::reference(), childrenkinematics::strategy(), decaymodes::strategy(), topjets::strategy(), toptruthjets::strategy(), strategy(), combinatorial::strategy(), validation::strategy(), selection_template::sum(), combinatorial::upcast(), and validation::upcast().
write() [1/3]
template<typename g > void selection_template::write (g * var, std::string name) inline inherited
Template method to write a variable to output.
Template Parameters
g The type of variable to write.
Parameters
var Pointer to the variable.
name Name for this variable in output.
Definition at line 174 of file selection_template.h.
References selection_template::handle, and selection_template::tree.
write() [2/3]
template<typename g > void selection_template::write (g var, std::string name) inline inherited
Template method to write a value to output.
Template Parameters
g The type of value to write.
Parameters
var The value to write.
name Name for this variable in output.
Definition at line 186 of file selection_template.h.
References selection_template::handle, and selection_template::tree.
write() [3/3]
void selection_template::write (std::vector< particle_template * > * particles, std::string name, particle_enum attrs) virtual inherited
Writes a particle collection to output.
Parameters
particles Pointer to vector of particles to write.
name Name for this collection in output.
attrs Particle attributes to write.
Definition at line 10 of file selection_template.cxx.
References charge, energy, eta, index, is_add, is_b, is_lep, is_nu, mass, pdgid, phi, pmc, pmu, pt, px, py, pz, selection_template::switch_board(), undef, v_b, v_d, v_i, vv_d, and selection_template::write().
Referenced by selection_template::bulk_write_out(), regions::merge(), childrenkinematics::merge(), topkinematics::merge(), topmatching::merge(), merge(), matching::merge(), combinatorial::merge(), validation::merge(), selection_template::merger(), met::strategy(), and selection_template::write().
Member Data Documentation
_is_marked
bool particle_template::_is_marked = false inherited
Flag for garbage collection marking.
Definition at line 313 of file particle_template.h.
_is_serial
bool particle_template::_is_serial = false inherited
Flag indicating if particle is being serialized.
Definition at line 312 of file particle_template.h.
Referenced by particle_template::__reduce__().
av_score
float zprime::av_score = 0
Definition at line 42 of file gnn-particles.h.
charge
cproperty<double, particle_template> particle_template::charge inherited
Electric charge property.
Definition at line 173 of file particle_template.h.
Referenced by particle_template::particle_template(), top_children::build(), truthjetparton::build(), jetparton::build(), electron::build(), muon::build(), child::build(), physics_detector::build(), physics_truth::build(), and lepton::build().
children
cproperty<std::map<std::string, particle_template*>, particle_template> particle_template::children inherited
Child particles.
Definition at line 206 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::get_lepdecay(), parton::strategy(), and strategy().
container
friend selection_template::container private inherited
Definition at line 392 of file selection_template.h.
data [1/2]
particle_t particle_template::data inherited
Internal data structure holding particle properties.
Definition at line 310 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::particle_template(), particle_template::particle_template(), particle_template::particle_template(), particle_template::~particle_template(), particle_template::__reduce__(), particle_template::get_charge(), particle_template::get_e(), particle_template::get_eta(), particle_template::get_hash(), particle_template::get_index(), particle_template::get_islep(), particle_template::get_isnu(), particle_template::get_mass(), particle_template::get_pdgid(), particle_template::get_phi(), particle_template::get_pt(), particle_template::get_px(), particle_template::get_py(), particle_template::get_pz(), particle_template::get_symbol(), particle_template::get_type(), particle_template::is(), particle_template::operator+(), particle_template::operator+=(), particle_template::register_child(), particle_template::register_parent(), particle_template::set_charge(), particle_template::set_children(), particle_template::set_e(), particle_template::set_eta(), particle_template::set_index(), particle_template::set_mass(), particle_template::set_parents(), particle_template::set_pdgid(), particle_template::set_phi(), particle_template::set_pt(), particle_template::set_px(), particle_template::set_py(), particle_template::set_pz(), particle_template::set_symbol(), particle_template::set_type(), particle_template::to_cartesian(), and particle_template::to_polar().
data [2/2]
event_t selection_template::data inherited
Event data structure.
Definition at line 220 of file selection_template.h.
Referenced by selection_template::build(), combinatorial::build_packet(), validation::build_packet(), childrenkinematics::dump_kinematics(), childrenkinematics::dump_kinematics(), selection_template::get_hash(), selection_template::get_name(), selection_template::get_tree(), selection_template::get_weight(), regions::merge(), combinatorial::reconstruction(), validation::reconstruction(), selection_template::set_hash(), selection_template::set_index(), selection_template::set_name(), selection_template::set_weight(), regions::strategy(), topkinematics::strategy(), selection_template::switch_board(), selection_template::switch_board(), selection_template::switch_board(), selection_template::switch_board(), combinatorial::update_state(), and validation::update_state().
e
cproperty<double, particle_template> particle_template::e inherited
Energy property.
Definition at line 133 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::particle_template(), particle_template::particle_template(), assign_vector(), top_children::build(), truthjetparton::build(), jet::build(), jetparton::build(), electron::build(), muon::build(), particle_gnn::build(), lepton::build(), particle_template::get_e(), particle_template::get_hash(), particle_template::get_mass(), particle_template::operator+(), particle_template::operator+=(), parton::strategy(), and parton::top_mass_contribution().
eta
cproperty<double, particle_template> particle_template::eta inherited
Pseudorapidity property.
Definition at line 145 of file particle_template.h.
Referenced by particle_template::particle_template(), top_children::build(), truthjetparton::build(), jet::build(), jetparton::build(), electron::build(), muon::build(), particle_gnn::build(), zboson::build(), parton::build(), lepton::build(), particle_template::DeltaR(), particle_template::to_cartesian(), and particle_template::to_polar().
filename
std::string selection_template::filename = "" inherited
Associated filename.
Definition at line 219 of file selection_template.h.
Referenced by selection_template::build(), and selection_template::merger().
garbage
std::map<std::string, std::vector<particle_template*> > selection_template::garbage = {} private inherited
Garbage collection for created particles.
Definition at line 402 of file selection_template.h.
Referenced by selection_template::~selection_template(), and selection_template::sum().
handle
write_t* selection_template::handle = nullptr private inherited
Definition at line 400 of file selection_template.h.
Referenced by selection_template::bulk_write_out(), selection_template::write(), and selection_template::write().
hash [1/2]
cproperty<std::string, particle_template> particle_template::hash inherited
Unique hash identifier.
Definition at line 177 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::~particle_template(), top::build(), top_children::build(), truthjet::build(), truthjetparton::build(), jet::build(), jetparton::build(), electron::build(), muon::build(), child::build(), physics_detector::build(), physics_truth::build(), particle_gnn::build(), zboson::build(), parton::build(), lepton::build(), particle_template::get_children(), particle_template::get_hash(), particle_template::get_parents(), particle_template::operator==(), particle_template::register_child(), particle_template::register_parent(), and parton::top_mass_contribution().
hash [2/2]
cproperty<std::string, selection_template> selection_template::hash inherited
Unique hash identifier.
Definition at line 89 of file selection_template.h.
Referenced by selection_template::selection_template(), selection_template::contains(), matching::current(), matching::experimental(), selection_template::make_unique(), matching::match_obj(), selection_template::merger(), selection_template::operator==(), combinatorial::reconstruction(), matching::reference(), selection_template::reverse_hash(), met::strategy(), topjets::strategy(), topmatching::strategy(), toptruthjets::strategy(), combinatorial::strategy(), validation::strategy(), topefficiency::strategy(), and selection_template::sum().
index [1/2]
cproperty<int, particle_template> particle_template::index inherited
Index in particle collection.
Definition at line 214 of file particle_template.h.
Referenced by particle_template::particle_template(), top_children::build(), truthjetparton::build(), jet::build(), jetparton::build(), electron::build(), muon::build(), child::build(), physics_detector::build(), physics_truth::build(), particle_gnn::build(), parton::build(), and lepton::build().
index [2/2]
cproperty<long, selection_template> selection_template::index inherited
Event index.
Definition at line 100 of file selection_template.h.
Referenced by selection_template::selection_template(), selection_template::merger(), selection_template::set_hash(), and selection_template::switch_board().
is_add
cproperty<bool, particle_template> particle_template::is_add inherited
Is additional radiation flag.
Definition at line 196 of file particle_template.h.
Referenced by particle_template::particle_template().
is_b
cproperty<bool, particle_template> particle_template::is_b inherited
Is b-quark/hadron flag.
Definition at line 187 of file particle_template.h.
Referenced by particle_template::particle_template(), jet::build(), and particle_template::get_isadd().
is_lep
cproperty<bool, particle_template> particle_template::is_lep inherited
Is lepton flag.
Definition at line 190 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::get_isadd(), particle_template::get_lepdecay(), parton::strategy(), and strategy().
is_nu
cproperty<bool, particle_template> particle_template::is_nu inherited
Is neutrino flag.
Definition at line 193 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::get_isadd(), particle_template::get_lepdecay(), and strategy().
leaves
std::map<std::string, std::string> particle_template::leaves = {} inherited
Map of leaf names.
Definition at line 284 of file particle_template.h.
Referenced by particle_template::add_leaf(), and particle_template::apply_type_prefix().
lep_decay
cproperty<bool, particle_template> particle_template::lep_decay inherited
Leptonic decay flag.
Definition at line 199 of file particle_template.h.
Referenced by particle_template::particle_template().
m_children
std::map<std::string, particle_template*> particle_template::m_children inherited
Map of child particles by hash.
Definition at line 276 of file particle_template.h.
Referenced by particle_template::get_children(), particle_template::register_child(), and particle_template::set_children().
m_event
event_template* selection_template::m_event = nullptr private inherited
Definition at line 401 of file selection_template.h.
Referenced by selection_template::build(), selection_template::CompileEvent(), and selection_template::merger().
m_parents
std::map<std::string, particle_template*> particle_template::m_parents inherited
Map of parent particles by hash.
Definition at line 268 of file particle_template.h.
Referenced by particle_template::get_parents(), particle_template::register_parent(), and particle_template::set_parents().
mass
cproperty<double, particle_template> particle_template::mass inherited
Invariant mass property.
Definition at line 137 of file particle_template.h.
Referenced by particle_template::particle_template(), zboson::build(), parton::build(), particle_template::get_e(), particle_template::get_mass(), topkinematics::strategy(), and strategy().
matched_meta
std::map<std::string, meta_t> selection_template::matched_meta = {} inherited
Matched metadata.
Definition at line 389 of file selection_template.h.
Referenced by selection_template::merger().
meta_data
meta* selection_template::meta_data = nullptr inherited
Pointer to metadata.
Definition at line 218 of file selection_template.h.
Referenced by selection_template::merger(), and regions::strategy().
n_leps
int zprime::n_leps = 0
Definition at line 43 of file gnn-particles.h.
n_nodes
int zprime::n_nodes = 0
Definition at line 44 of file gnn-particles.h.
name
cproperty<std::string, selection_template> selection_template::name inherited
Selection name property.
Definition at line 85 of file selection_template.h.
Referenced by selection_template::build(), combinatorial::build_packet(), validation::build_packet(), regions::merge(), selection_template::set_name(), and matching::strategy().
p_bulk_write
bool selection_template::p_bulk_write = true private inherited
Definition at line 398 of file selection_template.h.
Referenced by selection_template::bulk_write(), selection_template::bulk_write_out(), and selection_template::merger().
parents
cproperty<std::map<std::string, particle_template*>, particle_template> particle_template::parents inherited
Parent particles.
Definition at line 202 of file particle_template.h.
Referenced by particle_template::particle_template(), top_children::get_from_res(), electron::get_from_res(), muon::get_from_res(), and parton::top_mass_contribution().
passed_weights
std::map<std::string, std::map<std::string, float> > selection_template::passed_weights = {} inherited
Weights for passed events.
Definition at line 388 of file selection_template.h.
Referenced by selection_template::merger(), and selection_template::reverse_hash().
pdgid
cproperty<int, particle_template> particle_template::pdgid inherited
PDG particle ID property.
Definition at line 165 of file particle_template.h.
Referenced by particle_template::particle_template(), top_children::build(), truthjetparton::build(), jetparton::build(), electron::build(), muon::build(), child::build(), physics_detector::build(), physics_truth::build(), parton::build(), particle_template::get_pdgid(), particle_template::get_symbol(), parton::strategy(), and parton::top_mass_contribution().
phi
cproperty<double, particle_template> particle_template::phi inherited
Azimuthal angle property.
Definition at line 149 of file particle_template.h.
Referenced by particle_template::particle_template(), top_children::build(), truthjetparton::build(), jet::build(), jetparton::build(), electron::build(), muon::build(), particle_gnn::build(), zboson::build(), parton::build(), lepton::build(), particle_template::DeltaR(), particle_template::to_cartesian(), and particle_template::to_polar().
pt
cproperty<double, particle_template> particle_template::pt inherited
Transverse momentum property.
Definition at line 141 of file particle_template.h.
Referenced by particle_template::particle_template(), top_children::build(), truthjetparton::build(), jet::build(), jetparton::build(), electron::build(), muon::build(), particle_gnn::build(), zboson::build(), parton::build(), lepton::build(), parton::strategy(), particle_template::to_cartesian(), and particle_template::to_polar().
px
cproperty<double, particle_template> particle_template::px inherited
X-momentum property.
Definition at line 153 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::particle_template(), particle_template::particle_template(), parton::build(), lepton::build(), particle_template::get_e(), particle_template::get_hash(), particle_template::get_mass(), particle_template::operator+(), particle_template::operator+=(), particle_template::to_cartesian(), and particle_template::to_polar().
py
cproperty<double, particle_template> particle_template::py inherited
Y-momentum property.
Definition at line 157 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::particle_template(), particle_template::particle_template(), particle_template::get_e(), particle_template::get_hash(), particle_template::get_mass(), particle_template::operator+(), particle_template::operator+=(), particle_template::to_cartesian(), and particle_template::to_polar().
pz
cproperty<double, particle_template> particle_template::pz inherited
Z-momentum property.
Definition at line 161 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::particle_template(), particle_template::particle_template(), particle_template::get_e(), particle_template::get_hash(), particle_template::get_mass(), particle_template::operator+(), particle_template::operator+=(), particle_template::to_cartesian(), and particle_template::to_polar().
sequence
std::unordered_map<long, std::string> selection_template::sequence private inherited
Definition at line 397 of file selection_template.h.
Referenced by selection_template::bulk_write_out(), and selection_template::merger().
symbol
cproperty<std::string, particle_template> particle_template::symbol inherited
Particle symbol property.
Definition at line 169 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::get_pdgid(), and particle_template::get_symbol().
threadIdx
int selection_template::threadIdx = -1 inherited
Thread index for parallel processing.
Definition at line 387 of file selection_template.h.
Referenced by combinatorial::build_packet(), and validation::build_packet().
tree
cproperty<std::string, selection_template> selection_template::tree inherited
Source tree name.
Definition at line 93 of file selection_template.h.
Referenced by selection_template::selection_template(), selection_template::write(), and selection_template::write().
type
cproperty<std::string, particle_template> particle_template::type inherited
Particle type string.
Definition at line 210 of file particle_template.h.
Referenced by child::child(), electron::electron(), jet::jet(), jetparton::jetparton(), lepton::lepton(), muon::muon(), particle_gnn::particle_gnn(), particle_template::particle_template(), parton::parton(), physics_detector::physics_detector(), physics_truth::physics_truth(), top::top(), top_children::top_children(), truthjet::truthjet(), truthjetparton::truthjetparton(), zboson::zboson(), zprime(), particle_template::apply_type_prefix(), and top_children::get_from_res().
weight
cproperty<double, selection_template> selection_template::weight inherited
Event weight.
Definition at line 96 of file selection_template.h.
Referenced by selection_template::selection_template(), selection_template::build(), regions::merge(), and selection_template::merger().
zprime_children
std::vector< float > zprime::zprime_children = {}
Definition at line 19 of file mc16/zprime/zprime.h.
Referenced by merge(), and strategy().
zprime_jets
std::vector< float > zprime::zprime_jets = {}
Definition at line 21 of file mc16/zprime/zprime.h.
Referenced by merge(), and strategy().
zprime_truth_tops
std::vector< float > zprime::zprime_truth_tops = {}
Definition at line 18 of file mc16/zprime/zprime.h.
Referenced by merge(), and strategy().
zprime_truthjets
std::vector< float > zprime::zprime_truthjets = {}
Definition at line 20 of file mc16/zprime/zprime.h.
Referenced by merge(), and strategy().
The documentation for this class was generated from the following files:
gnn-particles.h
mc16/zprime/zprime.h
mc20/zprime/zprime.h
gnn/cxx/particles.cxx
mc16/zprime/zprime.cxx
mc20/zprime/zprime.cxx