AnalysisG: particle_gnn Class Reference
particle_gnn Class Reference
#include <gnn-particles.h>
Public Member Functions
particle_gnn ()
~particle_gnn ()
particle_template * clone () override
Creates a clone of this particle.
void build (std::map< std::string, particle_template * > *prt, element_t *el) override
Builds the particle from event data.
void to_cartesian ()
Converts internal representation to Cartesian coordinates.
void to_polar ()
Converts internal representation to polar coordinates.
bool is (std::vector< int > p)
Checks if particle matches any of the given PDG IDs.
double DeltaR (particle_template *p)
Calculates the angular separation ΔR from another particle.
bool operator== (particle_template &p)
Equality comparison operator.
template<typename g >
g operator+ (g &p)
Addition operator for combining particles.
void operator+= (particle_template *p)
In-place addition operator.
void iadd (particle_template *p)
In-place addition method (alternative to +=).
bool register_parent (particle_template *p)
Registers a parent particle.
bool register_child (particle_template *p)
Registers a child particle.
void add_leaf (std::string key, std::string leaf="")
Adds a leaf (variable) to read for this particle.
void apply_type_prefix ()
Applies the particle type as a prefix to leaf names.
std::map< std::string, std::map< std::string, particle_t > > __reduce__ ()
Serializes particle data for storage.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Static Public Member Functions
static void set_e (double *, particle_template *)
Setter for energy.
static void get_e (double *, particle_template *)
Getter for energy.
static void set_mass (double *, particle_template *)
Setter for mass.
static void get_mass (double *, particle_template *)
Getter for mass.
static void set_pt (double *, particle_template *)
Setter for pT.
static void get_pt (double *, particle_template *)
Getter for pT.
static void set_eta (double *, particle_template *)
Setter for η.
static void get_eta (double *, particle_template *)
Getter for η.
static void set_phi (double *, particle_template *)
Setter for φ.
static void get_phi (double *, particle_template *)
Getter for φ.
static void set_px (double *, particle_template *)
Setter for px.
static void get_px (double *, particle_template *)
Getter for px.
static void set_py (double *, particle_template *)
Setter for py.
static void get_py (double *, particle_template *)
Getter for py.
static void set_pz (double *, particle_template *)
Setter for pz.
static void get_pz (double *, particle_template *)
Getter for pz.
static void set_pdgid (int *, particle_template *)
Setter for PDG ID.
static void get_pdgid (int *, particle_template *)
Getter for PDG ID.
static void set_symbol (std::string *, particle_template *)
Setter for symbol.
static void get_symbol (std::string *, particle_template *)
Getter for symbol.
static void set_charge (double *, particle_template *)
Setter for charge.
static void get_charge (double *, particle_template *)
Getter for charge.
static void get_hash (std::string *, particle_template *)
Getter for hash.
static void get_isb (bool *, particle_template *)
Getter for is_b.
static void get_islep (bool *, particle_template *)
Getter for is_lep.
static void get_isnu (bool *, particle_template *)
Getter for is_nu.
static void get_isadd (bool *, particle_template *)
Getter for is_add.
static void get_lepdecay (bool *, particle_template *)
Getter for lep_decay.
static void set_parents (std::map< std::string, particle_template * > *, particle_template *)
Setter for parents.
static void get_parents (std::map< std::string, particle_template * > *, particle_template *)
Getter for parents.
static void set_children (std::map< std::string, particle_template * > *, particle_template *)
Setter for children.
static void get_children (std::map< std::string, particle_template * > *, particle_template *)
Getter for children.
static void set_type (std::string *, particle_template *)
Setter for type.
static void get_type (std::string *, particle_template *)
Getter for type.
static void set_index (int *, particle_template *)
Setter for index.
static void get_index (int *, particle_template *)
Getter for index.
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Public Attributes
bool lep = false
cproperty< double, particle_template > e
Energy property.
cproperty< double, particle_template > mass
Invariant mass property.
cproperty< double, particle_template > pt
Transverse momentum property.
cproperty< double, particle_template > eta
Pseudorapidity property.
cproperty< double, particle_template > phi
Azimuthal angle property.
cproperty< double, particle_template > px
X-momentum property.
cproperty< double, particle_template > py
Y-momentum property.
cproperty< double, particle_template > pz
Z-momentum property.
cproperty< int, particle_template > pdgid
PDG particle ID property.
cproperty< std::string, particle_template > symbol
Particle symbol property.
cproperty< double, particle_template > charge
Electric charge property.
cproperty< std::string, particle_template > hash
Unique hash identifier.
cproperty< bool, particle_template > is_b
Is b-quark/hadron flag.
cproperty< bool, particle_template > is_lep
Is lepton flag.
cproperty< bool, particle_template > is_nu
Is neutrino flag.
cproperty< bool, particle_template > is_add
Is additional radiation flag.
cproperty< bool, particle_template > lep_decay
Leptonic decay flag.
cproperty< std::map< std::string, particle_template * >, particle_template > parents
Parent particles.
cproperty< std::map< std::string, particle_template * >, particle_template > children
Child particles.
cproperty< std::string, particle_template > type
Particle type string.
cproperty< int, particle_template > index
Index in particle collection.
std::map< std::string, particle_template * > m_parents
Map of parent particles by hash.
std::map< std::string, particle_template * > m_children
Map of child particles by hash.
std::map< std::string, std::string > leaves = {}
Map of leaf names.
particle_t data
Internal data structure holding particle properties.
bool _is_serial = false
Flag indicating if particle is being serialized.
bool _is_marked = false
Flag for garbage collection marking.
Detailed Description
Definition at line 15 of file gnn-particles.h.
Constructor & Destructor Documentation
particle_gnn()
particle_gnn::particle_gnn ()
Definition at line 3 of file gnn/cxx/particles.cxx.
References particle_template::add_leaf(), and particle_template::type.
Referenced by build(), and clone().
~particle_gnn()
particle_gnn::~particle_gnn ()
Definition at line 12 of file gnn/cxx/particles.cxx.
Member Function Documentation
__reduce__()
std::map< std::string, std::map< std::string, particle_t > > particle_template::__reduce__ () inherited
Serializes particle data for storage.
Returns
Nested map structure for serialization.
Definition at line 131 of file particle_template.cxx.
References particle_template::particle_template(), particle_template::_is_serial, particle_template::data, and particle_t::data_p.
absolute_path()
std::string tools::absolute_path (std::string path) static inherited
Converts a relative path to an absolute path.
Parameters
path The path to convert.
Returns
The absolute version of the path.
Definition at line 49 of file tools/cxx/io.cxx.
Referenced by analysis::analysis(), analysis::build_events(), io::check_root_file_paths(), and io::trigger_pcm().
add_leaf()
void particle_template::add_leaf (std::string key, std::string leaf = "") inherited
Adds a leaf (variable) to read for this particle.
Parameters
key The internal name for this leaf.
leaf The actual leaf name in the ROOT file (optional, defaults to key).
Definition at line 99 of file interfaces.cxx.
References particle_template::leaves.
Referenced by child::child(), electron::electron(), jet::jet(), jetparton::jetparton(), lepton::lepton(), muon::muon(), particle_gnn(), parton::parton(), physics_detector::physics_detector(), physics_truth::physics_truth(), top::top(), top_children::top_children(), truthjet::truthjet(), truthjetparton::truthjetparton(), and zboson::zboson().
apply_type_prefix()
void particle_template::apply_type_prefix () inherited
Applies the particle type as a prefix to leaf names.
Definition at line 191 of file particle_template.cxx.
References particle_template::leaves, and particle_template::type.
Referenced by child::child(), electron::electron(), jet::jet(), jetparton::jetparton(), lepton::lepton(), muon::muon(), physics_detector::physics_detector(), physics_truth::physics_truth(), top::top(), top_children::top_children(), truthjet::truthjet(), truthjetparton::truthjetparton(), and zboson::zboson().
build()
void particle_gnn::build (std::map< std::string, particle_template * > * event, element_t * el) override virtual
Builds the particle from event data.
Parameters
event Map of particles in the event.
el Element containing raw data.
Reimplemented from particle_template.
Definition at line 16 of file gnn/cxx/particles.cxx.
References particle_gnn(), particle_template::e, particle_template::eta, particle_template::hash, particle_template::index, lep, particle_template::phi, and particle_template::pt.
clone()
particle_template * particle_gnn::clone () override virtual
Creates a clone of this particle.
Returns
Pointer to the cloned particle.
Reimplemented from particle_template.
Definition at line 14 of file gnn/cxx/particles.cxx.
References particle_gnn().
create_path()
void tools::create_path (std::string path) static inherited
Creates a directory path, including parent directories if needed.
Parameters
path The directory path to create.
Definition at line 6 of file tools/cxx/io.cxx.
References f, and tools::split().
Referenced by analysis::analysis(), analysis::build_inference(), plotting::build_path(), analysis::build_project(), container::compile(), metrics::dump_mass_plots(), metric_template::execute(), metrics::generic_painter(), analysis::start(), io::start(), and io::trigger_pcm().
delete_path()
void tools::delete_path (std::string path) static inherited
Deletes a directory path and its contents.
Parameters
path The directory path to delete.
Definition at line 22 of file tools/cxx/io.cxx.
DeltaR()
double particle_template::DeltaR (particle_template * p) inherited
Calculates the angular separation ΔR from another particle.
Parameters
p Pointer to the other particle.
Returns
ΔR = √(Δη² + Δφ²)
Definition at line 3 of file modules/particle/cxx/physics.cxx.
References particle_template::eta, particle_template::phi, and tools::sum().
ends_with()
bool tools::ends_with (std::string * inpt, std::string val) static inherited
Checks if a string ends with a specific substring.
Parameters
inpt Pointer to the string to check.
val The substring to check for at the end.
Returns
True if the string ends with the substring, false otherwise.
Definition at line 71 of file strings.cxx.
References l.
Referenced by plotting::build_path(), io::check_root_file_paths(), dataloader::dump_graphs(), tools::ls(), meta::parse_json(), io::scan_keys(), and analysis::start().
extract()
template<typename C , typename T > static void tools::extract (std::vector< T > * prop, std::vector< C * > * src, void(*)(T *, C *) get_prop) inline static inherited
Extracts a specific property from a vector of objects into a new vector.
Template Parameters
C The type of objects in the source vector.
T The type of the property to extract.
Parameters
prop Pointer to the output vector to fill with property values.
src Pointer to the source vector of objects.
get_prop Function pointer to extract the property from an object.
< Clear the properties vector.
< Reserve space for the property values.
< Loop through each object in the source vector.
< Create a default-initialized property variable.
< Call the provided function to extract the property.
< Add the property value to the output vector.
Definition at line 216 of file tools.h.
flush()
template<typename T > static void tools::flush (std::vector< T * > * inpt) inline static inherited
Empties a vector and all objects it points to.
Template Parameters
T The type of pointers in the vector.
Parameters
inpt Pointer to the vector to empty.
< Loop through all elements in the vector.
< Delete the object the pointer points to.
< Set the pointer to nullptr to avoid dangling pointers.
< Clear the vector.
Definition at line 167 of file tools.h.
Referenced by analysis::~analysis(), dataloader::~dataloader(), sampletracer::compile_objects(), and io::root_end().
get_charge()
void particle_template::get_charge (double * val, particle_template * prt) static inherited
Getter for charge.
Definition at line 57 of file interfaces.cxx.
References particle_t::charge, and particle_template::data.
Referenced by particle_template::particle_template().
get_children()
void particle_template::get_children (std::map< std::string, particle_template * > * val, particle_template * prt) static inherited
Getter for children.
Definition at line 128 of file interfaces.cxx.
References count(), particle_template::hash, and particle_template::m_children.
Referenced by particle_template::particle_template().
get_e()
void particle_template::get_e (double * v, particle_template * prt) static inherited
Getter for energy.
Definition at line 12 of file modules/particle/cxx/physics.cxx.
References particle_template::data, particle_template::e, particle_template::mass, particle_template::px, particle_template::py, and particle_template::pz.
Referenced by particle_template::particle_template().
get_eta()
void particle_template::get_eta (double * val, particle_template * prt) static inherited
Getter for η.
Definition at line 19 of file polar.cxx.
References particle_template::data, particle_t::eta, and particle_template::to_polar().
Referenced by particle_template::particle_template().
get_hash()
void particle_template::get_hash (std::string * val, particle_template * prt) static inherited
Getter for hash.
Definition at line 152 of file interfaces.cxx.
References particle_template::data, particle_template::e, particle_template::hash, particle_template::px, particle_template::py, particle_template::pz, particle_template::to_cartesian(), and tools::to_string().
Referenced by particle_template::particle_template().
get_index()
void particle_template::get_index (int * val, particle_template * prt) static inherited
Getter for index.
Definition at line 177 of file interfaces.cxx.
References particle_template::data, and particle_t::index.
Referenced by particle_template::particle_template().
get_isadd()
void particle_template::get_isadd (bool * val, particle_template * prt) static inherited
Getter for is_add.
Definition at line 73 of file interfaces.cxx.
References particle_template::is_b, particle_template::is_lep, and particle_template::is_nu.
Referenced by particle_template::particle_template().
get_isb()
void particle_template::get_isb (bool * val, particle_template * prt) static inherited
Getter for is_b.
Definition at line 61 of file interfaces.cxx.
References particle_template::is().
Referenced by particle_template::particle_template().
get_islep()
void particle_template::get_islep (bool * val, particle_template * prt) static inherited
Getter for is_lep.
Definition at line 69 of file interfaces.cxx.
References particle_template::data, particle_template::is(), and particle_t::lepdef.
Referenced by particle_template::particle_template().
get_isnu()
void particle_template::get_isnu (bool * val, particle_template * prt) static inherited
Getter for is_nu.
Definition at line 65 of file interfaces.cxx.
References particle_template::data, particle_template::is(), and particle_t::nudef.
Referenced by particle_template::particle_template().
get_lepdecay()
void particle_template::get_lepdecay (bool * val, particle_template * prt) static inherited
Getter for lep_decay.
Definition at line 86 of file interfaces.cxx.
References particle_template::children, particle_template::is_lep, and particle_template::is_nu.
Referenced by particle_template::particle_template().
get_mass()
void particle_template::get_mass (double * val, particle_template * prt) static inherited
Getter for mass.
Definition at line 31 of file modules/particle/cxx/physics.cxx.
References particle_template::data, particle_template::e, particle_template::mass, particle_template::px, particle_template::py, and particle_template::pz.
Referenced by particle_template::particle_template().
get_parents()
void particle_template::get_parents (std::map< std::string, particle_template * > * val, particle_template * prt) static inherited
Getter for parents.
Definition at line 112 of file interfaces.cxx.
References count(), particle_template::hash, and particle_template::m_parents.
Referenced by particle_template::particle_template().
get_pdgid()
void particle_template::get_pdgid (int * val, particle_template * prt) static inherited
Getter for PDG ID.
Definition at line 7 of file interfaces.cxx.
References particle_template::data, particle_template::pdgid, and particle_template::symbol.
Referenced by particle_template::particle_template().
get_phi()
void particle_template::get_phi (double * val, particle_template * prt) static inherited
Getter for φ.
Definition at line 30 of file polar.cxx.
References particle_template::data, particle_t::phi, and particle_template::to_polar().
Referenced by particle_template::particle_template().
get_pt()
void particle_template::get_pt (double * val, particle_template * prt) static inherited
Getter for pT.
Definition at line 8 of file polar.cxx.
References particle_template::data, particle_t::pt, and particle_template::to_polar().
Referenced by particle_template::particle_template().
get_px()
void particle_template::get_px (double * val, particle_template * prt) static inherited
Getter for px.
Definition at line 8 of file cartesian.cxx.
References particle_template::data, particle_t::px, and particle_template::to_cartesian().
Referenced by particle_template::particle_template().
get_py()
void particle_template::get_py (double * val, particle_template * prt) static inherited
Getter for py.
Definition at line 18 of file cartesian.cxx.
References particle_template::data, particle_t::py, and particle_template::to_cartesian().
Referenced by particle_template::particle_template().
get_pz()
void particle_template::get_pz (double * val, particle_template * prt) static inherited
Getter for pz.
Definition at line 28 of file cartesian.cxx.
References particle_template::data, particle_t::pz, and particle_template::to_cartesian().
Referenced by particle_template::particle_template().
get_symbol()
void particle_template::get_symbol (std::string * val, particle_template * prt) static inherited
Getter for symbol.
Definition at line 35 of file interfaces.cxx.
References particle_template::data, particle_template::pdgid, and particle_template::symbol.
Referenced by particle_template::particle_template().
get_type()
void particle_template::get_type (std::string * val, particle_template * prt) static inherited
Getter for type.
Definition at line 169 of file interfaces.cxx.
References particle_template::data, and particle_t::type.
Referenced by particle_template::particle_template().
has_string()
bool tools::has_string (std::string * inpt, std::string trg) static inherited
Checks if a string contains a specific substring.
Parameters
inpt Pointer to the string to check.
trg The substring to search for.
Returns
True if the substring is found, false otherwise.
Definition at line 65 of file strings.cxx.
References f.
Referenced by analysis::check_cache(), meta::compiler(), metrics::generic_painter(), dataloader::restore_graphs_(), meta::scan_sow(), model_template::set_device(), and metric_template::set_run_name().
has_value()
bool tools::has_value (std::vector< std::string > * data, std::string trg) static inherited
Checks if a vector of strings contains a specific string.
Parameters
data Pointer to the vector to search.
trg The string to search for.
Returns
True if the string is found in the vector, false otherwise.
Definition at line 77 of file strings.cxx.
Referenced by io::scan_keys().
iadd()
void particle_template::iadd (particle_template * p) inherited
In-place addition method (alternative to +=).
Parameters
p Pointer to the particle to add.
Definition at line 183 of file particle_template.cxx.
is()
bool particle_template::is (std::vector< int > p) inherited
Checks if particle matches any of the given PDG IDs.
Parameters
p Vector of PDG IDs to check against.
Returns
True if particle's PDG ID matches any in the vector.
Definition at line 78 of file interfaces.cxx.
References particle_template::data, i, and particle_t::pdgid.
Referenced by particle_template::get_isb(), particle_template::get_islep(), and particle_template::get_isnu().
is_file()
bool tools::is_file (std::string path) static inherited
Checks if a path refers to an existing file.
Parameters
path The path to check.
Returns
True if the path is a file and exists, false otherwise.
Definition at line 30 of file tools/cxx/io.cxx.
Referenced by io::check_root_file_paths(), analysis::initialize_loop(), metric_template::set_run_name(), and io::start().
ls()
std::vector< std::string > tools::ls (std::string path, std::string ext = "") static inherited
Lists files in a directory, optionally filtered by extension.
Parameters
path The directory to search.
ext File extension filter. If empty, all files are listed.
Returns
A vector of filenames in the directory.
Definition at line 35 of file tools/cxx/io.cxx.
References tools::ends_with(), and tools::split().
Referenced by analysis::analysis(), analysis::check_cache(), io::check_root_file_paths(), dataloader::restore_graphs(), and io::trigger_pcm().
operator+()
template<typename g > g particle_template::operator+ (g & p) inline inherited
Addition operator for combining particles.
Template Parameters
g The particle type (must inherit from particle_template).
Parameters
p The particle to add.
Returns
A new particle with combined four-momentum.
Definition at line 239 of file particle_template.h.
References particle_template::data, particle_template::e, particle_template::px, particle_template::py, particle_template::pz, and particle_t::type.
operator+=()
void particle_template::operator+= (particle_template * p) inherited
In-place addition operator.
Parameters
p Pointer to the particle to add.
Definition at line 173 of file particle_template.cxx.
References particle_template::data, particle_template::e, particle_t::e, particle_t::polar, particle_template::px, particle_t::px, particle_template::py, particle_t::py, particle_template::pz, particle_t::pz, and particle_template::to_cartesian().
operator==()
bool particle_template::operator== (particle_template & p) inherited
Equality comparison operator.
Parameters
p The particle to compare against.
Returns
True if particles have the same hash.
Definition at line 187 of file particle_template.cxx.
References particle_template::hash.
put()
template<typename g > static void tools::put (std::vector< g * > * out, std::vector< g * > * src, std::vector< int > * trg) inline static inherited
Fills a vector with pointers from another vector based on a selection index.
Template Parameters
g The type of objects being pointed to.
Parameters
out Pointer to the output vector to fill.
src Pointer to the source vector to select from.
trg Pointer to a vector of indices for selection.
< Clear the output vector.
< Reserve space for the output elements.
< Loop through each selected index.
< Get the object at the selected index.
< Add it to the output vector.
< Mark the object as in use.
Definition at line 197 of file tools.h.
Referenced by dataloader::get_k_train_set(), dataloader::get_k_validation_set(), and dataloader::get_test_set().
register_child()
bool particle_template::register_child (particle_template * p) inherited
Registers a child particle.
Parameters
p Pointer to the child particle.
Returns
True if registration was successful.
Definition at line 136 of file interfaces.cxx.
References particle_t::children, particle_template::data, particle_template::hash, and particle_template::m_children.
Referenced by particle_template::set_children().
register_parent()
bool particle_template::register_parent (particle_template * p) inherited
Registers a parent particle.
Parameters
p Pointer to the parent particle.
Returns
True if registration was successful.
Definition at line 144 of file interfaces.cxx.
References particle_template::data, particle_template::hash, particle_template::m_parents, and particle_t::parents.
Referenced by particle_template::set_parents().
rename()
void tools::rename (std::string start, std::string target) static inherited
Renames a file or directory.
Parameters
start The original path.
target The new path.
Definition at line 18 of file tools/cxx/io.cxx.
Referenced by dataloader::dump_graphs().
replace()
void tools::replace (std::string * in, std::string repl_str, std::string repl_with) static inherited
Replaces all occurrences of a substring in a string.
Parameters
in Pointer to the string to modify.
repl_str The substring to replace.
repl_with The replacement string.
Definition at line 5 of file strings.cxx.
Referenced by analysis::build_graphs(), analysis::check_cache(), dataloader::dump_graphs(), meta::get_campaign(), meta::parse_json(), and analysis::start().
set_charge()
void particle_template::set_charge (double * val, particle_template * prt) static inherited
Setter for charge.
Definition at line 53 of file interfaces.cxx.
References particle_t::charge, and particle_template::data.
Referenced by particle_template::particle_template().
set_children()
void particle_template::set_children (std::map< std::string, particle_template * > * val, particle_template * prt) static inherited
Setter for children.
Definition at line 120 of file interfaces.cxx.
References particle_t::children, particle_template::data, particle_template::m_children, and particle_template::register_child().
Referenced by particle_template::particle_template().
set_e()
void particle_template::set_e (double * val, particle_template * prt) static inherited
Setter for energy.
Definition at line 23 of file modules/particle/cxx/physics.cxx.
References particle_template::data, and particle_t::e.
Referenced by particle_template::particle_template().
set_eta()
void particle_template::set_eta (double * val, particle_template * prt) static inherited
Setter for η.
Definition at line 14 of file polar.cxx.
References particle_t::cartesian, particle_template::data, and particle_t::eta.
Referenced by particle_template::particle_template().
set_index()
void particle_template::set_index (int * val, particle_template * prt) static inherited
Setter for index.
Definition at line 173 of file interfaces.cxx.
References particle_template::data, and particle_t::index.
Referenced by particle_template::particle_template().
set_mass()
void particle_template::set_mass (double * val, particle_template * prt) static inherited
Setter for mass.
Definition at line 27 of file modules/particle/cxx/physics.cxx.
References particle_template::data, and particle_t::mass.
Referenced by particle_template::particle_template().
set_parents()
void particle_template::set_parents (std::map< std::string, particle_template * > * val, particle_template * prt) static inherited
Setter for parents.
Definition at line 104 of file interfaces.cxx.
References particle_template::data, particle_template::m_parents, particle_t::parents, and particle_template::register_parent().
Referenced by particle_template::particle_template().
set_pdgid()
void particle_template::set_pdgid (int * val, particle_template * prt) static inherited
Setter for PDG ID.
Definition at line 3 of file interfaces.cxx.
References particle_template::data, and particle_t::pdgid.
Referenced by particle_template::particle_template().
set_phi()
void particle_template::set_phi (double * val, particle_template * prt) static inherited
Setter for φ.
Definition at line 24 of file polar.cxx.
References particle_t::cartesian, particle_template::data, and particle_t::phi.
Referenced by particle_template::particle_template().
set_pt()
void particle_template::set_pt (double * val, particle_template * prt) static inherited
Setter for pT.
Definition at line 3 of file polar.cxx.
References particle_t::cartesian, particle_template::data, and particle_t::pt.
Referenced by particle_template::particle_template().
set_px()
void particle_template::set_px (double * val, particle_template * prt) static inherited
Setter for px.
Definition at line 3 of file cartesian.cxx.
References particle_template::data, particle_t::polar, and particle_t::px.
Referenced by particle_template::particle_template().
set_py()
void particle_template::set_py (double * val, particle_template * prt) static inherited
Setter for py.
Definition at line 13 of file cartesian.cxx.
References particle_template::data, particle_t::polar, and particle_t::py.
Referenced by particle_template::particle_template().
set_pz()
void particle_template::set_pz (double * val, particle_template * prt) static inherited
Setter for pz.
Definition at line 23 of file cartesian.cxx.
References particle_template::data, particle_t::polar, and particle_t::pz.
Referenced by particle_template::particle_template().
set_symbol()
void particle_template::set_symbol (std::string * val, particle_template * prt) static inherited
Setter for symbol.
Definition at line 31 of file interfaces.cxx.
References particle_template::data, and particle_t::symbol.
Referenced by particle_template::particle_template().
set_type()
void particle_template::set_type (std::string * val, particle_template * prt) static inherited
Setter for type.
Definition at line 165 of file interfaces.cxx.
References particle_template::data, and particle_t::type.
Referenced by particle_template::particle_template().
split()
std::vector< std::string > tools::split (std::string inpt, std::string del) inherited
Splits a string into a vector of substrings based on a delimiter.
Parameters
inpt The input string to split.
del The delimiter.
Returns
A vector of substrings.
Definition at line 23 of file strings.cxx.
References index.
Referenced by analysis::build_events(), analysis::build_graphs(), analysis::build_inference(), event_template::build_mapping(), analysis::check_cache(), container::compile(), sampletracer::compile_objects(), meta::compiler(), tools::create_path(), dataloader::dump_graphs(), meta::hash(), tools::ls(), graph_t::meta_deserialize(), dataloader::restore_graphs_(), io::root_begin(), model_template::set_device(), metric_template::set_run_name(), metric_template::set_variables(), and analysis::start().
sum()
template<typename g > g tools::sum (std::vector< g > * inpt) inline inherited
Sums the elements of a vector.
Template Parameters
g The type of elements in the vector.
Parameters
inpt Pointer to the vector to sum.
Returns
The sum of all elements.
< Initialize the output variable.
< Return the sum.
Definition at line 183 of file tools.h.
Referenced by metrics::add_th1f_accuracy(), sampletracer::compile_objects(), particle_template::DeltaR(), graph_template::double_neutrino(), grift::forward(), recursivegraphneuralnetwork::forward(), matching::match_obj(), and grift::message().
to_cartesian()
void particle_template::to_cartesian () inherited
Converts internal representation to Cartesian coordinates.
Definition at line 33 of file cartesian.cxx.
References particle_template::data, particle_template::eta, particle_template::phi, particle_template::pt, particle_template::px, particle_template::py, and particle_template::pz.
Referenced by particle_template::get_hash(), particle_template::get_px(), particle_template::get_py(), particle_template::get_pz(), and particle_template::operator+=().
to_polar()
void particle_template::to_polar () inherited
Converts internal representation to polar coordinates.
Definition at line 35 of file polar.cxx.
References particle_template::data, particle_template::eta, particle_template::phi, particle_template::pt, particle_template::px, particle_template::py, and particle_template::pz.
Referenced by particle_template::get_eta(), particle_template::get_phi(), and particle_template::get_pt().
to_string() [1/2]
std::string tools::to_string (double val) static inherited
Converts a double value to a string with standard precision.
Parameters
val The double value to convert.
Returns
The string representation of the value.
Definition at line 59 of file strings.cxx.
Referenced by dataloader::generate_kfold_set(), dataloader::generate_test_set(), particle_template::get_hash(), topefficiency::region(), dataloader::restore_dataset(), event_template::set_hash(), selection_template::set_hash(), parton::strategy(), topjets::strategy(), toptruthjets::strategy(), and parton::top_mass_contribution().
to_string() [2/2]
std::string tools::to_string (double val, int prec) static inherited
Converts a double value to a string with specified precision.
Parameters
val The double value to convert.
prec The number of decimal places to consider.
Returns
The string representation of the value.
Definition at line 91 of file strings.cxx.
trim()
std::string tools::trim (std::string s) inherited
Removes whitespace from the beginning and end of a string.
Parameters
s The string to trim.
Returns
The trimmed string.
type_name()
template<typename T > std::string tools::type_name () inline inherited
Gets the type name of a variable as a string (for debugging).
Template Parameters
T The type to get the name of.
Returns
The name of the type as a string.
< Gets the type name via RTTI.
< Returns the type name.
Definition at line 155 of file tools.h.
Referenced by event_template::build_mapping().
Member Data Documentation
_is_marked
bool particle_template::_is_marked = false inherited
Flag for garbage collection marking.
Definition at line 313 of file particle_template.h.
_is_serial
bool particle_template::_is_serial = false inherited
Flag indicating if particle is being serialized.
Definition at line 312 of file particle_template.h.
Referenced by particle_template::__reduce__().
charge
cproperty<double, particle_template> particle_template::charge inherited
Electric charge property.
Definition at line 173 of file particle_template.h.
Referenced by particle_template::particle_template(), top_children::build(), truthjetparton::build(), jetparton::build(), electron::build(), muon::build(), child::build(), physics_detector::build(), physics_truth::build(), and lepton::build().
children
cproperty<std::map<std::string, particle_template*>, particle_template> particle_template::children inherited
Child particles.
Definition at line 206 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::get_lepdecay(), parton::strategy(), and zprime::strategy().
data
particle_t particle_template::data inherited
Internal data structure holding particle properties.
Definition at line 310 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::particle_template(), particle_template::particle_template(), particle_template::particle_template(), particle_template::~particle_template(), particle_template::__reduce__(), particle_template::get_charge(), particle_template::get_e(), particle_template::get_eta(), particle_template::get_hash(), particle_template::get_index(), particle_template::get_islep(), particle_template::get_isnu(), particle_template::get_mass(), particle_template::get_pdgid(), particle_template::get_phi(), particle_template::get_pt(), particle_template::get_px(), particle_template::get_py(), particle_template::get_pz(), particle_template::get_symbol(), particle_template::get_type(), particle_template::is(), particle_template::operator+(), particle_template::operator+=(), particle_template::register_child(), particle_template::register_parent(), particle_template::set_charge(), particle_template::set_children(), particle_template::set_e(), particle_template::set_eta(), particle_template::set_index(), particle_template::set_mass(), particle_template::set_parents(), particle_template::set_pdgid(), particle_template::set_phi(), particle_template::set_pt(), particle_template::set_px(), particle_template::set_py(), particle_template::set_pz(), particle_template::set_symbol(), particle_template::set_type(), particle_template::to_cartesian(), and particle_template::to_polar().
e
cproperty<double, particle_template> particle_template::e inherited
Energy property.
Definition at line 133 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::particle_template(), particle_template::particle_template(), assign_vector(), top_children::build(), truthjetparton::build(), jet::build(), jetparton::build(), electron::build(), muon::build(), build(), lepton::build(), particle_template::get_e(), particle_template::get_hash(), particle_template::get_mass(), particle_template::operator+(), particle_template::operator+=(), parton::strategy(), and parton::top_mass_contribution().
eta
cproperty<double, particle_template> particle_template::eta inherited
Pseudorapidity property.
Definition at line 145 of file particle_template.h.
Referenced by particle_template::particle_template(), top_children::build(), truthjetparton::build(), jet::build(), jetparton::build(), electron::build(), muon::build(), build(), zboson::build(), parton::build(), lepton::build(), particle_template::DeltaR(), particle_template::to_cartesian(), and particle_template::to_polar().
hash
cproperty<std::string, particle_template> particle_template::hash inherited
Unique hash identifier.
Definition at line 177 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::~particle_template(), top::build(), top_children::build(), truthjet::build(), truthjetparton::build(), jet::build(), jetparton::build(), electron::build(), muon::build(), child::build(), physics_detector::build(), physics_truth::build(), build(), zboson::build(), parton::build(), lepton::build(), particle_template::get_children(), particle_template::get_hash(), particle_template::get_parents(), particle_template::operator==(), particle_template::register_child(), particle_template::register_parent(), and parton::top_mass_contribution().
index
cproperty<int, particle_template> particle_template::index inherited
Index in particle collection.
Definition at line 214 of file particle_template.h.
Referenced by particle_template::particle_template(), top_children::build(), truthjetparton::build(), jet::build(), jetparton::build(), electron::build(), muon::build(), child::build(), physics_detector::build(), physics_truth::build(), build(), parton::build(), and lepton::build().
is_add
cproperty<bool, particle_template> particle_template::is_add inherited
Is additional radiation flag.
Definition at line 196 of file particle_template.h.
Referenced by particle_template::particle_template().
is_b
cproperty<bool, particle_template> particle_template::is_b inherited
Is b-quark/hadron flag.
Definition at line 187 of file particle_template.h.
Referenced by particle_template::particle_template(), jet::build(), and particle_template::get_isadd().
is_lep
cproperty<bool, particle_template> particle_template::is_lep inherited
Is lepton flag.
Definition at line 190 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::get_isadd(), particle_template::get_lepdecay(), parton::strategy(), and zprime::strategy().
is_nu
cproperty<bool, particle_template> particle_template::is_nu inherited
Is neutrino flag.
Definition at line 193 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::get_isadd(), particle_template::get_lepdecay(), and zprime::strategy().
leaves
std::map<std::string, std::string> particle_template::leaves = {} inherited
Map of leaf names.
Definition at line 284 of file particle_template.h.
Referenced by particle_template::add_leaf(), and particle_template::apply_type_prefix().
lep
bool particle_gnn::lep = false
Definition at line 20 of file gnn-particles.h.
Referenced by build().
lep_decay
cproperty<bool, particle_template> particle_template::lep_decay inherited
Leptonic decay flag.
Definition at line 199 of file particle_template.h.
Referenced by particle_template::particle_template().
m_children
std::map<std::string, particle_template*> particle_template::m_children inherited
Map of child particles by hash.
Definition at line 276 of file particle_template.h.
Referenced by particle_template::get_children(), particle_template::register_child(), and particle_template::set_children().
m_parents
std::map<std::string, particle_template*> particle_template::m_parents inherited
Map of parent particles by hash.
Definition at line 268 of file particle_template.h.
Referenced by particle_template::get_parents(), particle_template::register_parent(), and particle_template::set_parents().
mass
cproperty<double, particle_template> particle_template::mass inherited
Invariant mass property.
Definition at line 137 of file particle_template.h.
Referenced by particle_template::particle_template(), zboson::build(), parton::build(), particle_template::get_e(), particle_template::get_mass(), topkinematics::strategy(), and zprime::strategy().
parents
cproperty<std::map<std::string, particle_template*>, particle_template> particle_template::parents inherited
Parent particles.
Definition at line 202 of file particle_template.h.
Referenced by particle_template::particle_template(), top_children::get_from_res(), electron::get_from_res(), muon::get_from_res(), and parton::top_mass_contribution().
pdgid
cproperty<int, particle_template> particle_template::pdgid inherited
PDG particle ID property.
Definition at line 165 of file particle_template.h.
Referenced by particle_template::particle_template(), top_children::build(), truthjetparton::build(), jetparton::build(), electron::build(), muon::build(), child::build(), physics_detector::build(), physics_truth::build(), parton::build(), particle_template::get_pdgid(), particle_template::get_symbol(), parton::strategy(), and parton::top_mass_contribution().
phi
cproperty<double, particle_template> particle_template::phi inherited
Azimuthal angle property.
Definition at line 149 of file particle_template.h.
Referenced by particle_template::particle_template(), top_children::build(), truthjetparton::build(), jet::build(), jetparton::build(), electron::build(), muon::build(), build(), zboson::build(), parton::build(), lepton::build(), particle_template::DeltaR(), particle_template::to_cartesian(), and particle_template::to_polar().
pt
cproperty<double, particle_template> particle_template::pt inherited
Transverse momentum property.
Definition at line 141 of file particle_template.h.
Referenced by particle_template::particle_template(), top_children::build(), truthjetparton::build(), jet::build(), jetparton::build(), electron::build(), muon::build(), build(), zboson::build(), parton::build(), lepton::build(), parton::strategy(), particle_template::to_cartesian(), and particle_template::to_polar().
px
cproperty<double, particle_template> particle_template::px inherited
X-momentum property.
Definition at line 153 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::particle_template(), particle_template::particle_template(), parton::build(), lepton::build(), particle_template::get_e(), particle_template::get_hash(), particle_template::get_mass(), particle_template::operator+(), particle_template::operator+=(), particle_template::to_cartesian(), and particle_template::to_polar().
py
cproperty<double, particle_template> particle_template::py inherited
Y-momentum property.
Definition at line 157 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::particle_template(), particle_template::particle_template(), particle_template::get_e(), particle_template::get_hash(), particle_template::get_mass(), particle_template::operator+(), particle_template::operator+=(), particle_template::to_cartesian(), and particle_template::to_polar().
pz
cproperty<double, particle_template> particle_template::pz inherited
Z-momentum property.
Definition at line 161 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::particle_template(), particle_template::particle_template(), particle_template::get_e(), particle_template::get_hash(), particle_template::get_mass(), particle_template::operator+(), particle_template::operator+=(), particle_template::to_cartesian(), and particle_template::to_polar().
symbol
cproperty<std::string, particle_template> particle_template::symbol inherited
Particle symbol property.
Definition at line 169 of file particle_template.h.
Referenced by particle_template::particle_template(), particle_template::get_pdgid(), and particle_template::get_symbol().
type
cproperty<std::string, particle_template> particle_template::type inherited
Particle type string.
Definition at line 210 of file particle_template.h.
Referenced by child::child(), electron::electron(), jet::jet(), jetparton::jetparton(), lepton::lepton(), muon::muon(), particle_gnn(), particle_template::particle_template(), parton::parton(), physics_detector::physics_detector(), physics_truth::physics_truth(), top::top(), top_children::top_children(), truthjet::truthjet(), truthjetparton::truthjetparton(), zboson::zboson(), zprime::zprime(), particle_template::apply_type_prefix(), and top_children::get_from_res().
The documentation for this class was generated from the following files:
gnn-particles.h
gnn/cxx/particles.cxx