AnalysisG: recursivegraphneuralnetwork Class Reference
recursivegraphneuralnetwork Class Reference
#include <RecursiveGraphNeuralNetwork.h>
Public Member Functions
recursivegraphneuralnetwork (int rep=1024, double dpt=0.1)
~recursivegraphneuralnetwork ()
model_template * clone () override
Creates a clone of the model template.
void forward (graph_t *) override
Virtual forward pass method for a single graph.
torch::Tensor message (torch::Tensor trk_i, torch::Tensor trk_j, torch::Tensor pmc, torch::Tensor pmc_i, torch::Tensor pmc_j, torch::Tensor hx_i, torch::Tensor hx_j)
void register_module (torch::nn::Sequential *data)
Registers a PyTorch sequential module with the model.
void register_module (torch::nn::Sequential *data, mlp_init method)
Registers a PyTorch sequential module with the model and initializes its weights.
virtual void forward (graph_t *data, bool train)
Forward pass for a single graph with training mode flag.
virtual void forward (std::vector< graph_t * > data, bool train)
Forward pass for multiple graphs with training mode flag.
torch::Tensor * assign_features (std::string inpt, graph_enum type, graph_t *data)
Assigns features from a graph to tensors based on feature name and type.
torch::Tensor * assign_features (std::string inpt, graph_enum type, std::vector< graph_t * > *data)
Assigns features from multiple graphs to tensors based on feature name and type.
void flush_outputs ()
Clears all output tensors, freeing memory.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
void set_prefix (std::string prefix)
Sets the prefix used in log messages from this instance.
std::string get_prefix ()
Returns the prefix currently used in log messages.
void Info (std::string msg, bool newline=true)
Outputs an info message.
void Warning (std::string msg, bool newline=true)
Outputs a warning message.
void Error (std::string msg, bool newline=true)
Outputs an error message.
void Debug (std::string msg, bool newline=true)
Outputs a debug message (only in debug mode).
void Message (std::string msg, std::string tag="", bool newline=true)
Outputs a message with custom formatting.
void set_debug_mode (bool dbg)
Enables or disables debug mode.
bool get_debug_mode ()
Returns the current status of debug mode.
void set_suppress_warning (bool sw)
Sets whether warnings should be suppressed.
bool get_suppress_warning ()
Returns the current warning suppression status.
void set_suppress_info (bool si)
Sets whether info messages should be suppressed.
bool get_suppress_info ()
Returns the current info message suppression status.
Static Public Member Functions
static void set_name (std::string *name, model_template *model)
Static setter for the name property.
static void get_name (std::string *name, model_template *model)
Static getter for the name property.
static void set_device (std::string *dev, model_template *model)
Static setter for the device property.
static void set_dev_index (int *dev_idx, model_template *model)
Static setter for the device_index property.
static void get_dev_index (int *dev_idx, model_template *model)
Static getter for the device_index property.
static void set_input_features (std::vector< std::string > *inpt, std::map< std::string, torch::Tensor * > *in_fx)
Sets input features for a specific feature map.
static void set_output_features (std::vector< std::string > *inpt, std::map< std::string, torch::Tensor * > *in_fx)
Sets output features for a specific feature map.
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Public Attributes
int _dx = 26
int _x = 5
int _output = 2
int _rep = 256
double res_mass = 0
double drop_out = 0.1
bool is_mc = true
torch::nn::Sequential * rnn_x = nullptr
torch::nn::Sequential * rnn_dx = nullptr
torch::nn::Sequential * rnn_merge = nullptr
torch::nn::Sequential * rnn_update = nullptr
torch::nn::Sequential * exotic_mlp = nullptr
torch::nn::Sequential * node_aggr_mlp = nullptr
torch::nn::Sequential * ntops_mlp = nullptr
torch::nn::Sequential * exo_mlp = nullptr
cproperty< std::string, model_template > name
Property: The name of this model.
cproperty< std::string, model_template > device
Property: The device this model runs on (e.g., "cpu", "cuda:0").
cproperty< int, model_template > device_index
Property: The numerical index of the device this model runs on.
cproperty< std::vector< std::string >, std::map< std::string, torch::Tensor * > > i_graph
Property: Graph-level input features.
cproperty< std::vector< std::string >, std::map< std::string, torch::Tensor * > > i_node
Property: Node-level input features.
cproperty< std::vector< std::string >, std::map< std::string, torch::Tensor * > > i_edge
Property: Edge-level input features.
cproperty< std::vector< std::string >, std::map< std::string, torch::Tensor * > > o_graph
Property: Graph-level output features.
cproperty< std::vector< std::string >, std::map< std::string, torch::Tensor * > > o_node
Property: Node-level output features.
cproperty< std::vector< std::string >, std::map< std::string, torch::Tensor * > > o_edge
Property: Edge-level output features.
std::map< std::string, torch::Tensor * > m_i_graph
Map of graph-level input features to tensors.
std::map< std::string, torch::Tensor * > m_i_node
Map of node-level input features to tensors.
std::map< std::string, torch::Tensor * > m_i_edge
Map of edge-level input features to tensors.
std::map< std::string, torch::Tensor * > m_o_graph
Map of graph-level output features to tensors.
std::map< std::string, torch::Tensor * > m_o_node
Map of node-level output features to tensors.
std::map< std::string, torch::Tensor * > m_o_edge
Map of edge-level output features to tensors.
torch::TensorOptions * m_option = nullptr
Pointer to tensor options for configuring tensor creation.
std::vector< torch::nn::Sequential * > m_data
Vector of pointers to sequential modules in the model.
lossfx * m_loss = nullptr
Pointer to the loss function manager.
std::string model_checkpoint_path
Path for saving/loading model checkpoints.
Protected Attributes
std::string prefix = ""
Prefix used in log messages from this instance. Initialized as empty string.
bool debug_mode = false
Flag indicating whether debug mode is enabled. Initialized as false.
bool suppress_warnings = false
Flag indicating whether warnings are suppressed. Initialized as false.
bool suppress_info = false
Flag indicating whether info messages are suppressed. Initialized as false.
Detailed Description
Definition at line 5 of file RecursiveGraphNeuralNetwork.h.
Constructor & Destructor Documentation
recursivegraphneuralnetwork()
recursivegraphneuralnetwork::recursivegraphneuralnetwork (int rep = 1024, double dpt = 0.1)
Definition at line 4 of file RecursiveGraphNeuralNetwork.cxx.
References _dx, _output, _rep, _x, drop_out, exo_mlp, exotic_mlp, node_aggr_mlp, ntops_mlp, model_template::register_module(), rnn_dx, rnn_merge, rnn_update, rnn_x, and xavier_uniform.
~recursivegraphneuralnetwork()
recursivegraphneuralnetwork::~recursivegraphneuralnetwork ()
Definition at line 302 of file RecursiveGraphNeuralNetwork.cxx.
Member Function Documentation
absolute_path()
std::string tools::absolute_path (std::string path) static inherited
Converts a relative path to an absolute path.
Parameters
path The path to convert.
Returns
The absolute version of the path.
Definition at line 49 of file tools/cxx/io.cxx.
Referenced by analysis::analysis(), analysis::build_events(), io::check_root_file_paths(), and io::trigger_pcm().
assign_features() [1/2]
torch::Tensor * model_template::assign_features (std::string inpt, graph_enum type, graph_t * data) inherited
Assigns features from a graph to tensors based on feature name and type.
Parameters
inpt Feature name to assign.
type Type of graph component (node, edge, or graph).
data Pointer to the graph_t structure containing the features.
Returns
Pointer to the resulting tensor containing the assigned features.
Parameters
inpt Feature name to assign.
type Type of graph component (node, edge, or graph).
data Pointer to the graph_t structure containing the features.
Returns
Pointer to the resulting tensor containing the assigned features.
Extracts specified features from the graph and converts them to PyTorch tensors.
Definition at line 118 of file model_template.cxx.
References data_edge, data_graph, data_node, model_template::m_i_edge, model_template::m_i_graph, model_template::m_i_node, model_template::m_o_edge, model_template::m_o_graph, model_template::m_o_node, truth_edge, truth_graph, and truth_node.
assign_features() [2/2]
torch::Tensor * model_template::assign_features (std::string inpt, graph_enum type, std::vector< graph_t * > * data) inherited
Assigns features from multiple graphs to tensors based on feature name and type.
Parameters
inpt Feature name to assign.
type Type of graph component (node, edge, or graph).
data Pointer to a vector of graph_t structures containing the features.
Returns
Pointer to the resulting tensor containing the assigned features.
Parameters
inpt Feature name to assign.
type Type of graph component (node, edge, or graph).
data Pointer to a vector of graph_t structures containing the features.
Returns
Pointer to the resulting tensor containing the assigned features.
Extracts specified features from multiple graphs and converts them to batched PyTorch tensors.
Definition at line 141 of file model_template.cxx.
References d, data_edge, data_graph, data_node, model_template::m_i_edge, model_template::m_i_graph, model_template::m_i_node, model_template::m_o_edge, model_template::m_o_graph, model_template::m_o_node, truth_edge, truth_graph, and truth_node.
clone()
model_template * recursivegraphneuralnetwork::clone () override virtual
Creates a clone of the model template.
Creates and returns a clone of this model template.
Returns
A pointer to a new model_template instance that is a copy of this one.
A new model_template instance.
Reimplemented from model_template.
Definition at line 303 of file RecursiveGraphNeuralNetwork.cxx.
References _dx, _output, _rep, _x, drop_out, is_mc, and res_mass.
Referenced by forward().
create_path()
void tools::create_path (std::string path) static inherited
Creates a directory path, including parent directories if needed.
Parameters
path The directory path to create.
Definition at line 6 of file tools/cxx/io.cxx.
References f, and tools::split().
Referenced by analysis::analysis(), analysis::build_inference(), plotting::build_path(), analysis::build_project(), container::compile(), metrics::dump_mass_plots(), metric_template::execute(), metrics::generic_painter(), analysis::start(), io::start(), and io::trigger_pcm().
Debug()
void notification::Debug (std::string msg, bool newline = true) inherited
Outputs a debug message (only in debug mode).
Parameters
msg The debug message to output.
newline Whether to append a newline (default: true).
delete_path()
void tools::delete_path (std::string path) static inherited
Deletes a directory path and its contents.
Parameters
path The directory path to delete.
Definition at line 22 of file tools/cxx/io.cxx.
ends_with()
bool tools::ends_with (std::string * inpt, std::string val) static inherited
Checks if a string ends with a specific substring.
Parameters
inpt Pointer to the string to check.
val The substring to check for at the end.
Returns
True if the string ends with the substring, false otherwise.
Definition at line 71 of file strings.cxx.
References l.
Referenced by plotting::build_path(), io::check_root_file_paths(), dataloader::dump_graphs(), tools::ls(), meta::parse_json(), io::scan_keys(), and analysis::start().
Error()
void notification::Error (std::string msg, bool newline = true) inherited
Outputs an error message.
Parameters
msg The error message to output.
newline Whether to append a newline (default: true).
extract()
template<typename C , typename T > static void tools::extract (std::vector< T > * prop, std::vector< C * > * src, void(*)(T *, C *) get_prop) inline static inherited
Extracts a specific property from a vector of objects into a new vector.
Template Parameters
C The type of objects in the source vector.
T The type of the property to extract.
Parameters
prop Pointer to the output vector to fill with property values.
src Pointer to the source vector of objects.
get_prop Function pointer to extract the property from an object.
< Clear the properties vector.
< Reserve space for the property values.
< Loop through each object in the source vector.
< Create a default-initialized property variable.
< Call the provided function to extract the property.
< Add the property value to the output vector.
Definition at line 216 of file tools.h.
flush()
template<typename T > static void tools::flush (std::vector< T * > * inpt) inline static inherited
Empties a vector and all objects it points to.
Template Parameters
T The type of pointers in the vector.
Parameters
inpt Pointer to the vector to empty.
< Loop through all elements in the vector.
< Delete the object the pointer points to.
< Set the pointer to nullptr to avoid dangling pointers.
< Clear the vector.
Definition at line 167 of file tools.h.
Referenced by analysis::~analysis(), dataloader::~dataloader(), sampletracer::compile_objects(), and io::root_end().
flush_outputs()
void model_template::flush_outputs () inherited
Clears all output tensors, freeing memory.
Used to reset the model's output state between forward passes.
Iterates through all output feature maps and deletes their tensor contents.
Definition at line 248 of file model_template.cxx.
References edge_index, model_template::m_i_edge, model_template::m_i_graph, model_template::m_i_node, model_template::m_o_edge, model_template::m_o_graph, and model_template::m_o_node.
Referenced by model_template::~model_template(), model_template::forward(), and model_template::forward().
forward() [1/3]
void recursivegraphneuralnetwork::forward (graph_t * data) override virtual
Virtual forward pass method for a single graph.
Default implementation of the forward pass for a single graph.
Parameters
data Pointer to the graph_t structure containing input data.
This method should be overridden by derived classes to implement the forward pass logic.
Parameters
data Pointer to the graph_t structure containing input data.
This is a placeholder that derived classes should override with their specific implementation.
Reimplemented from model_template.
Definition at line 143 of file RecursiveGraphNeuralNetwork.cxx.
References _rep, clone(), pyc::graph::edge_aggregation(), edge_index, energy, eta, exo_mlp, exotic_mlp, forward(), is_lep, is_mc, pyc::physics::cartesian::combined::M(), message(), node_aggr_mlp, ntops_mlp, nulls(), num_jets(), num_leps(), phi, pmc, pt, pyc::transform::separate::Px(), pyc::transform::separate::PxPyPzE(), pyc::transform::separate::Py(), res_edge(), res_mass, rnn_update, rnn_x, tools::sum(), and pyc::graph::unique_aggregation().
Referenced by forward(), and message().
forward() [2/3]
void model_template::forward (graph_t * data, bool train) virtual inherited
Forward pass for a single graph with training mode flag.
Performs forward pass on a single graph, with optional training mode.
Parameters
data Pointer to the graph_t structure containing input data.
train Flag indicating if the model is in training mode (true) or evaluation mode (false).
Executes the model's forward pass on a single graph, optionally in training mode.
Parameters
data Pointer to the graph_t structure containing input data.
train Flag indicating if the model is in training mode (true) or evaluation mode (false).
Sets the model's modules to training or evaluation mode as specified, then performs the forward pass.
Definition at line 182 of file model_template.cxx.
References data_edge, data_graph, data_node, edge_index, model_template::flush_outputs(), model_template::forward(), model_template::m_i_edge, model_template::m_i_graph, model_template::m_i_node, model_template::m_o_edge, model_template::m_o_graph, model_template::m_o_node, truth_edge, truth_graph, and truth_node.
forward() [3/3]
void model_template::forward (std::vector< graph_t * > data, bool train) virtual inherited
Forward pass for multiple graphs with training mode flag.
Performs forward pass on multiple graphs, with optional training mode.
Parameters
data Vector of pointers to graph_t structures containing input data.
train Flag indicating if the model is in training mode (true) or evaluation mode (false).
Executes the model's forward pass on multiple graphs, optionally in training mode.
Parameters
data Vector of pointers to graph_t structures containing input data.
train Flag indicating if the model is in training mode (true) or evaluation mode (false).
Sets the model's modules to training or evaluation mode as specified, then performs the forward pass on each graph in the input vector.
Definition at line 207 of file model_template.cxx.
References data_edge, data_graph, data_node, edge_index, model_template::flush_outputs(), model_template::forward(), model_template::m_i_edge, model_template::m_i_graph, model_template::m_i_node, model_template::m_o_edge, model_template::m_o_graph, model_template::m_o_node, truth_edge, truth_graph, and truth_node.
get_debug_mode()
bool notification::get_debug_mode () inherited
Returns the current status of debug mode.
Returns
Boolean indicating whether debug mode is enabled (true) or disabled (false).
get_dev_index()
void model_template::get_dev_index (int * dev_idx, model_template * model) static inherited
Static getter for the device_index property.
Parameters
[out] dev_idx Pointer to an integer to store the device index.
[in] model Pointer to the model_template instance.
Definition at line 84 of file model_configuration.cxx.
References model_template::device, and model_template::m_option.
Referenced by model_template::model_template().
get_name()
void model_template::get_name (std::string * name, model_template * model) static inherited
Static getter for the name property.
Parameters
[out] name Pointer to a string to store the name.
[in] model Pointer to the model_template instance.
Definition at line 61 of file model_configuration.cxx.
Referenced by model_template::model_template().
get_prefix()
std::string notification::get_prefix () inherited
Returns the prefix currently used in log messages.
Returns
The current prefix string.
get_suppress_info()
bool notification::get_suppress_info () inherited
Returns the current info message suppression status.
Returns
Boolean indicating whether info messages are suppressed (true) or shown (false).
get_suppress_warning()
bool notification::get_suppress_warning () inherited
Returns the current warning suppression status.
Returns
Boolean indicating whether warnings are suppressed (true) or shown (false).
has_string()
bool tools::has_string (std::string * inpt, std::string trg) static inherited
Checks if a string contains a specific substring.
Parameters
inpt Pointer to the string to check.
trg The substring to search for.
Returns
True if the substring is found, false otherwise.
Definition at line 65 of file strings.cxx.
References f.
Referenced by analysis::check_cache(), meta::compiler(), metrics::generic_painter(), dataloader::restore_graphs_(), meta::scan_sow(), model_template::set_device(), and metric_template::set_run_name().
has_value()
bool tools::has_value (std::vector< std::string > * data, std::string trg) static inherited
Checks if a vector of strings contains a specific string.
Parameters
data Pointer to the vector to search.
trg The string to search for.
Returns
True if the string is found in the vector, false otherwise.
Definition at line 77 of file strings.cxx.
Referenced by io::scan_keys().
Info()
void notification::Info (std::string msg, bool newline = true) inherited
Outputs an info message.
Parameters
msg The message to output.
newline Whether to append a newline (default: true).
is_file()
bool tools::is_file (std::string path) static inherited
Checks if a path refers to an existing file.
Parameters
path The path to check.
Returns
True if the path is a file and exists, false otherwise.
Definition at line 30 of file tools/cxx/io.cxx.
Referenced by io::check_root_file_paths(), analysis::initialize_loop(), metric_template::set_run_name(), and io::start().
ls()
std::vector< std::string > tools::ls (std::string path, std::string ext = "") static inherited
Lists files in a directory, optionally filtered by extension.
Parameters
path The directory to search.
ext File extension filter. If empty, all files are listed.
Returns
A vector of filenames in the directory.
Definition at line 35 of file tools/cxx/io.cxx.
References tools::ends_with(), and tools::split().
Referenced by analysis::analysis(), analysis::check_cache(), io::check_root_file_paths(), dataloader::restore_graphs(), and io::trigger_pcm().
Message()
void notification::Message (std::string msg, std::string tag = "", bool newline = true) inherited
Outputs a message with custom formatting.
Parameters
msg The message to output.
tag A custom tag to prepend to the message.
newline Whether to append a newline (default: true).
message()
torch::Tensor recursivegraphneuralnetwork::message (torch::Tensor trk_i, torch::Tensor trk_j, torch::Tensor pmc, torch::Tensor pmc_i, torch::Tensor pmc_j, torch::Tensor hx_i, torch::Tensor hx_j)
Definition at line 105 of file RecursiveGraphNeuralNetwork.cxx.
References pyc::physics::cartesian::combined::DeltaR(), forward(), pyc::physics::cartesian::combined::M(), pmc, rnn_dx, rnn_merge, and pyc::graph::unique_aggregation().
Referenced by forward().
put()
template<typename g > static void tools::put (std::vector< g * > * out, std::vector< g * > * src, std::vector< int > * trg) inline static inherited
Fills a vector with pointers from another vector based on a selection index.
Template Parameters
g The type of objects being pointed to.
Parameters
out Pointer to the output vector to fill.
src Pointer to the source vector to select from.
trg Pointer to a vector of indices for selection.
< Clear the output vector.
< Reserve space for the output elements.
< Loop through each selected index.
< Get the object at the selected index.
< Add it to the output vector.
< Mark the object as in use.
Definition at line 197 of file tools.h.
Referenced by dataloader::get_k_train_set(), dataloader::get_k_validation_set(), and dataloader::get_test_set().
register_module() [1/2]
void model_template::register_module (torch::nn::Sequential * data) inherited
Registers a PyTorch sequential module with the model.
Parameters
data Pointer to the sequential module to register.
Adds the module to the model's collection and places it on the appropriate device.
Parameters
data Pointer to the sequential module to register.
If a device option is set, the module is transferred to that device before registration.
Definition at line 69 of file model_template.cxx.
References model_template::device, model_template::m_data, and model_template::m_option.
Referenced by grift::grift(), and recursivegraphneuralnetwork().
register_module() [2/2]
void model_template::register_module (torch::nn::Sequential * data, mlp_init method) inherited
Registers a PyTorch sequential module with the model and initializes its weights.
Parameters
data Pointer to the sequential module to register.
method The initialization method to use for the module's weights.
Adds the module to the model's collection, places it on the appropriate device, and initializes its weights according to the specified method.
Parameters
data Pointer to the sequential module to register.
method The initialization method to use for the module's weights.
If a device option is set, the module is transferred to that device before registration. The module's weights are initialized according to the specified method.
Definition at line 82 of file model_template.cxx.
References model_template::device, model_template::m_data, model_template::m_loss, and model_template::m_option.
rename()
void tools::rename (std::string start, std::string target) static inherited
Renames a file or directory.
Parameters
start The original path.
target The new path.
Definition at line 18 of file tools/cxx/io.cxx.
Referenced by dataloader::dump_graphs().
replace()
void tools::replace (std::string * in, std::string repl_str, std::string repl_with) static inherited
Replaces all occurrences of a substring in a string.
Parameters
in Pointer to the string to modify.
repl_str The substring to replace.
repl_with The replacement string.
Definition at line 5 of file strings.cxx.
Referenced by analysis::build_graphs(), analysis::check_cache(), dataloader::dump_graphs(), meta::get_campaign(), meta::parse_json(), and analysis::start().
set_debug_mode()
void notification::set_debug_mode (bool dbg) inherited
Enables or disables debug mode.
Parameters
dbg Boolean flag, set to true to enable debug messages, false to disable.
set_dev_index()
void model_template::set_dev_index (int * dev_idx, model_template * model) static inherited
Static setter for the device_index property.
Parameters
[in] dev_idx Pointer to an integer containing the device index.
[in] model Pointer to the model_template instance.
Definition at line 89 of file model_configuration.cxx.
Referenced by model_template::model_template().
set_device()
void model_template::set_device (std::string * dev, model_template * model) static inherited
Static setter for the device property.
Parameters
[in] dev Pointer to a string containing the device name.
[in] model Pointer to the model_template instance.
Definition at line 63 of file model_configuration.cxx.
References model_template::device, tools::has_string(), model_template::m_data, model_template::m_option, and tools::split().
Referenced by model_template::model_template().
set_input_features()
void model_template::set_input_features (std::vector< std::string > * inpt, std::map< std::string, torch::Tensor * > * in_fx) static inherited
Sets input features for a specific feature map.
Parameters
inpt Pointer to a vector of strings containing feature names.
in_fx Pointer to the feature map to set.
inpt Pointer to a vector of strings containing feature names.
in_fx Pointer to the feature map to set.
Initializes map entries for each feature name in the input vector.
Definition at line 239 of file model_template.cxx.
Referenced by model_template::model_template().
set_name()
void model_template::set_name (std::string * name, model_template * model) static inherited
Static setter for the name property.
Parameters
[in] name Pointer to a string containing the name.
[in] model Pointer to the model_template instance.
Definition at line 60 of file model_configuration.cxx.
Referenced by model_template::model_template().
set_output_features()
void model_template::set_output_features (std::vector< std::string > * inpt, std::map< std::string, torch::Tensor * > * in_fx) static inherited
Sets output features for a specific feature map.
Parameters
inpt Pointer to a vector of strings containing feature names.
in_fx Pointer to the feature map to set.
Definition at line 3 of file model_lossfx.cxx.
References lossfx::loss_string().
Referenced by model_template::model_template().
set_prefix()
void notification::set_prefix (std::string prefix) inherited
Sets the prefix used in log messages from this instance.
Parameters
prefix The string to use as a prefix for log messages.
set_suppress_info()
void notification::set_suppress_info (bool si) inherited
Sets whether info messages should be suppressed.
Parameters
si Boolean flag, set to true to suppress info messages, false to show them.
set_suppress_warning()
void notification::set_suppress_warning (bool sw) inherited
Sets whether warnings should be suppressed.
Parameters
sw Boolean flag, set to true to suppress warnings, false to show them.
split()
std::vector< std::string > tools::split (std::string inpt, std::string del) inherited
Splits a string into a vector of substrings based on a delimiter.
Parameters
inpt The input string to split.
del The delimiter.
Returns
A vector of substrings.
Definition at line 23 of file strings.cxx.
References index.
Referenced by analysis::build_events(), analysis::build_graphs(), analysis::build_inference(), event_template::build_mapping(), analysis::check_cache(), container::compile(), sampletracer::compile_objects(), meta::compiler(), tools::create_path(), dataloader::dump_graphs(), meta::hash(), tools::ls(), graph_t::meta_deserialize(), dataloader::restore_graphs_(), io::root_begin(), model_template::set_device(), metric_template::set_run_name(), metric_template::set_variables(), and analysis::start().
sum()
template<typename g > g tools::sum (std::vector< g > * inpt) inline inherited
Sums the elements of a vector.
Template Parameters
g The type of elements in the vector.
Parameters
inpt Pointer to the vector to sum.
Returns
The sum of all elements.
< Initialize the output variable.
< Return the sum.
Definition at line 183 of file tools.h.
Referenced by metrics::add_th1f_accuracy(), sampletracer::compile_objects(), particle_template::DeltaR(), graph_template::double_neutrino(), grift::forward(), forward(), matching::match_obj(), and grift::message().
to_string() [1/2]
std::string tools::to_string (double val) static inherited
Converts a double value to a string with standard precision.
Parameters
val The double value to convert.
Returns
The string representation of the value.
Definition at line 59 of file strings.cxx.
Referenced by dataloader::generate_kfold_set(), dataloader::generate_test_set(), particle_template::get_hash(), topefficiency::region(), dataloader::restore_dataset(), event_template::set_hash(), selection_template::set_hash(), parton::strategy(), topjets::strategy(), toptruthjets::strategy(), and parton::top_mass_contribution().
to_string() [2/2]
std::string tools::to_string (double val, int prec) static inherited
Converts a double value to a string with specified precision.
Parameters
val The double value to convert.
prec The number of decimal places to consider.
Returns
The string representation of the value.
Definition at line 91 of file strings.cxx.
trim()
std::string tools::trim (std::string s) inherited
Removes whitespace from the beginning and end of a string.
Parameters
s The string to trim.
Returns
The trimmed string.
type_name()
template<typename T > std::string tools::type_name () inline inherited
Gets the type name of a variable as a string (for debugging).
Template Parameters
T The type to get the name of.
Returns
The name of the type as a string.
< Gets the type name via RTTI.
< Returns the type name.
Definition at line 155 of file tools.h.
Referenced by event_template::build_mapping().
Warning()
void notification::Warning (std::string msg, bool newline = true) inherited
Outputs a warning message.
Parameters
msg The warning message to output.
newline Whether to append a newline (default: true).
Referenced by io::read(), io::read(), io::write(), and io::write().
Member Data Documentation
_dx
int recursivegraphneuralnetwork::_dx = 26
Definition at line 20 of file RecursiveGraphNeuralNetwork.h.
Referenced by recursivegraphneuralnetwork(), and clone().
_output
int recursivegraphneuralnetwork::_output = 2
Definition at line 22 of file RecursiveGraphNeuralNetwork.h.
Referenced by recursivegraphneuralnetwork(), and clone().
_rep
int recursivegraphneuralnetwork::_rep = 256
Definition at line 23 of file RecursiveGraphNeuralNetwork.h.
Referenced by recursivegraphneuralnetwork(), clone(), and forward().
_x
int recursivegraphneuralnetwork::_x = 5
Definition at line 21 of file RecursiveGraphNeuralNetwork.h.
Referenced by recursivegraphneuralnetwork(), and clone().
debug_mode
bool notification::debug_mode = false protected inherited
Flag indicating whether debug mode is enabled. Initialized as false.
Definition at line 127 of file notification.h.
Referenced by analysis::build_metric().
device
cproperty<std::string, model_template> model_template::device inherited
Property: The device this model runs on (e.g., "cpu", "cuda:0").
Definition at line 148 of file model_template.h.
Referenced by model_template::model_template(), model_template::get_dev_index(), model_template::register_module(), model_template::register_module(), and model_template::set_device().
device_index
cproperty<int, model_template> model_template::device_index inherited
Property: The numerical index of the device this model runs on.
Definition at line 154 of file model_template.h.
Referenced by model_template::model_template().
drop_out
double recursivegraphneuralnetwork::drop_out = 0.1
Definition at line 25 of file RecursiveGraphNeuralNetwork.h.
Referenced by recursivegraphneuralnetwork(), and clone().
exo_mlp
torch::nn::Sequential* recursivegraphneuralnetwork::exo_mlp = nullptr
Definition at line 37 of file RecursiveGraphNeuralNetwork.h.
Referenced by recursivegraphneuralnetwork(), and forward().
exotic_mlp
torch::nn::Sequential* recursivegraphneuralnetwork::exotic_mlp = nullptr
Definition at line 34 of file RecursiveGraphNeuralNetwork.h.
Referenced by recursivegraphneuralnetwork(), and forward().
i_edge
cproperty<std::vector<std::string>, std::map<std::string, torch::Tensor*> > model_template::i_edge inherited
Property: Edge-level input features.
Definition at line 167 of file model_template.h.
Referenced by model_template::model_template().
i_graph
cproperty<std::vector<std::string>, std::map<std::string, torch::Tensor*> > model_template::i_graph inherited
Property: Graph-level input features.
Definition at line 165 of file model_template.h.
Referenced by model_template::model_template().
i_node
cproperty<std::vector<std::string>, std::map<std::string, torch::Tensor*> > model_template::i_node inherited
Property: Node-level input features.
Definition at line 166 of file model_template.h.
Referenced by model_template::model_template().
is_mc
bool recursivegraphneuralnetwork::is_mc = true
Definition at line 28 of file RecursiveGraphNeuralNetwork.h.
Referenced by clone(), and forward().
m_data
std::vector<torch::nn::Sequential*> model_template::m_data inherited
Vector of pointers to sequential modules in the model.
Definition at line 198 of file model_template.h.
Referenced by model_template::~model_template(), model_template::register_module(), model_template::register_module(), and model_template::set_device().
m_i_edge
std::map<std::string, torch::Tensor*> model_template::m_i_edge inherited
Map of edge-level input features to tensors.
Definition at line 191 of file model_template.h.
Referenced by model_template::model_template(), model_template::assign_features(), model_template::assign_features(), model_template::flush_outputs(), model_template::forward(), and model_template::forward().
m_i_graph
std::map<std::string, torch::Tensor*> model_template::m_i_graph inherited
Map of graph-level input features to tensors.
Definition at line 189 of file model_template.h.
Referenced by model_template::model_template(), model_template::assign_features(), model_template::assign_features(), model_template::flush_outputs(), model_template::forward(), and model_template::forward().
m_i_node
std::map<std::string, torch::Tensor*> model_template::m_i_node inherited
Map of node-level input features to tensors.
Definition at line 190 of file model_template.h.
Referenced by model_template::model_template(), model_template::assign_features(), model_template::assign_features(), model_template::flush_outputs(), model_template::forward(), and model_template::forward().
m_loss
lossfx* model_template::m_loss = nullptr inherited
Pointer to the loss function manager.
Definition at line 199 of file model_template.h.
Referenced by model_template::model_template(), model_template::~model_template(), and model_template::register_module().
m_o_edge
std::map<std::string, torch::Tensor*> model_template::m_o_edge inherited
Map of edge-level output features to tensors.
Definition at line 195 of file model_template.h.
Referenced by model_template::model_template(), model_template::assign_features(), model_template::assign_features(), model_template::flush_outputs(), model_template::forward(), and model_template::forward().
m_o_graph
std::map<std::string, torch::Tensor*> model_template::m_o_graph inherited
Map of graph-level output features to tensors.
Definition at line 193 of file model_template.h.
Referenced by model_template::model_template(), model_template::assign_features(), model_template::assign_features(), model_template::flush_outputs(), model_template::forward(), and model_template::forward().
m_o_node
std::map<std::string, torch::Tensor*> model_template::m_o_node inherited
Map of node-level output features to tensors.
Definition at line 194 of file model_template.h.
Referenced by model_template::model_template(), model_template::assign_features(), model_template::assign_features(), model_template::flush_outputs(), model_template::forward(), and model_template::forward().
m_option
torch::TensorOptions* model_template::m_option = nullptr inherited
Pointer to tensor options for configuring tensor creation.
Definition at line 197 of file model_template.h.
Referenced by model_template::get_dev_index(), model_template::register_module(), model_template::register_module(), and model_template::set_device().
model_checkpoint_path
std::string model_template::model_checkpoint_path inherited
Path for saving/loading model checkpoints.
Definition at line 201 of file model_template.h.
name
cproperty<std::string, model_template> model_template::name inherited
Property: The name of this model.
Definition at line 138 of file model_template.h.
node_aggr_mlp
torch::nn::Sequential* recursivegraphneuralnetwork::node_aggr_mlp = nullptr
Definition at line 35 of file RecursiveGraphNeuralNetwork.h.
Referenced by recursivegraphneuralnetwork(), and forward().
ntops_mlp
torch::nn::Sequential* recursivegraphneuralnetwork::ntops_mlp = nullptr
Definition at line 36 of file RecursiveGraphNeuralNetwork.h.
Referenced by recursivegraphneuralnetwork(), and forward().
o_edge
cproperty<std::vector<std::string>, std::map<std::string, torch::Tensor*> > model_template::o_edge inherited
Property: Edge-level output features.
Definition at line 172 of file model_template.h.
Referenced by model_template::model_template().
o_graph
cproperty<std::vector<std::string>, std::map<std::string, torch::Tensor*> > model_template::o_graph inherited
Property: Graph-level output features.
Definition at line 170 of file model_template.h.
Referenced by model_template::model_template().
o_node
cproperty<std::vector<std::string>, std::map<std::string, torch::Tensor*> > model_template::o_node inherited
Property: Node-level output features.
Definition at line 171 of file model_template.h.
Referenced by model_template::model_template().
prefix
std::string notification::prefix = "" protected inherited
Prefix used in log messages from this instance. Initialized as empty string.
Definition at line 126 of file notification.h.
Referenced by analysis::analysis(), dataloader::dataloader(), io::io(), meta::meta(), optimizer::optimizer(), and metric_template::set_name().
res_mass
double recursivegraphneuralnetwork::res_mass = 0
Definition at line 24 of file RecursiveGraphNeuralNetwork.h.
Referenced by clone(), and forward().
rnn_dx
torch::nn::Sequential* recursivegraphneuralnetwork::rnn_dx = nullptr
Definition at line 31 of file RecursiveGraphNeuralNetwork.h.
Referenced by recursivegraphneuralnetwork(), and message().
rnn_merge
torch::nn::Sequential* recursivegraphneuralnetwork::rnn_merge = nullptr
Definition at line 32 of file RecursiveGraphNeuralNetwork.h.
Referenced by recursivegraphneuralnetwork(), and message().
rnn_update
torch::nn::Sequential* recursivegraphneuralnetwork::rnn_update = nullptr
Definition at line 33 of file RecursiveGraphNeuralNetwork.h.
Referenced by recursivegraphneuralnetwork(), and forward().
rnn_x
torch::nn::Sequential* recursivegraphneuralnetwork::rnn_x = nullptr
Definition at line 30 of file RecursiveGraphNeuralNetwork.h.
Referenced by recursivegraphneuralnetwork(), and forward().
suppress_info
bool notification::suppress_info = false protected inherited
Flag indicating whether info messages are suppressed. Initialized as false.
Definition at line 129 of file notification.h.
suppress_warnings
bool notification::suppress_warnings = false protected inherited
Flag indicating whether warnings are suppressed. Initialized as false.
Definition at line 128 of file notification.h.
The documentation for this class was generated from the following files:
RecursiveGraphNeuralNetwork.h
RecursiveGraphNeuralNetwork.cxx