AnalysisG: combinatorial Class Reference
combinatorial Class Reference
#include <combinatorial.h>
Public Member Functions
combinatorial ()
~combinatorial () override
selection_template * clone () override
bool selection (event_template *ev) override
bool strategy (event_template *ev) override
void merge (selection_template *sl) override
void update_state (packet_t *data)
void reconstruction (packet_t *data)
Public Member Functions inherited from selection_template
selection_template ()
virtual ~selection_template ()
virtual void bulk_write (const long *idx, std::string *hx)
virtual void write (std::vector< particle_template * > *particles, std::string name, particle_enum attrs)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< std::vector< double >> *data)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< int > *data)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< double > *data)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< bool > *data)
template<typename g >
void write (g *var, std::string name)
template<typename g >
void write (g var, std::string name)
std::vector< std::map< std::string, float > > reverse_hash (std::vector< std::string > *hashes)
bool CompileEvent ()
selection_template * build (event_template *ev)
bool operator== (selection_template &p)
template<typename g , typename k >
void sum (std::vector< g * > *ch, k **out)
template<typename g >
void safe_delete (std::vector< g * > *particles)
template<typename g >
g * sum (std::map< std::string, g * > *ch)
template<typename g >
float sum (std::vector< g * > *ch)
template<typename g >
std::vector< g * > vectorize (std::map< std::string, g * > *in)
template<typename g >
std::vector< g * > make_unique (std::vector< g * > *inpt)
template<typename g >
void downcast (std::vector< g * > *inpt, std::vector< particle_template * > *out)
template<typename o , typename g >
void upcast (std::map< std::string, o * > *inpt, std::vector< g * > *out)
template<typename o , typename g >
void upcast (std::vector< o * > *inpt, std::vector< g * > *out)
template<typename g >
void get_leptonics (std::map< std::string, g * > inpt, std::vector< particle_template * > *out)
template<typename g , typename j >
bool contains (std::vector< g * > *inpt, j *pcheck)
Public Member Functions inherited from tools
tools ()
Constructor for the tools class.
~tools ()
Destructor for the tools class.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Public Attributes
int num_device = 1
double masstop = 172.62*1000
double massw = 80.385*1000
Public Attributes inherited from selection_template
cproperty< std::string, selection_template > name
cproperty< std::string, selection_template > hash
cproperty< std::string, selection_template > tree
cproperty< double, selection_template > weight
cproperty< long, selection_template > index
meta * meta_data = nullptr
std::string filename = ""
event_t data
int threadIdx = -1
std::map< std::string, std::map< std::string, float > > passed_weights = {}
std::map< std::string, meta_t > matched_meta = {}
Additional Inherited Members
Static Public Member Functions inherited from selection_template
static void set_name (std::string *, selection_template *)
static void get_name (std::string *, selection_template *)
static void set_hash (std::string *, selection_template *)
static void get_hash (std::string *, selection_template *)
static void get_tree (std::string *, selection_template *)
static void set_weight (double *, selection_template *)
static void get_weight (double *, selection_template *)
static void set_index (long *, selection_template *)
Static Public Member Functions inherited from tools
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Detailed Description
Definition at line 46 of file combinatorial.h.
Constructor & Destructor Documentation
combinatorial()
combinatorial::combinatorial ()
Definition at line 11 of file combinatorial.cxx.
 {this -> name = "combinatorial";}
References selection_template::name.
Referenced by clone(), and combinatorial.figures::combinatorial().
~combinatorial()
combinatorial::~combinatorial () override
Definition at line 12 of file combinatorial.cxx.
 {this -> safe_delete(&this -> storage);}
References selection_template::safe_delete().
Member Function Documentation
clone()
selection_template * combinatorial::clone () override virtual
Reimplemented from selection_template.
Definition at line 14 of file combinatorial.cxx.
{
     combinatorial* cl = new combinatorial();
     cl -> num_device = this -> num_device;
     return cl;
 }
References combinatorial(), and num_device.
merge()
void combinatorial::merge (selection_template * sl) override virtual
Reimplemented from selection_template.
Definition at line 20 of file combinatorial.cxx.
{
     combinatorial* slt = (combinatorial*)sl;
     for (size_t x(0); x < slt -> storage.size(); ++x){
         packet_t* tc = slt -> storage[x];
         std::vector<particle_template*> vout = {};
         merge_data(&vout, &tc -> t_bquarks);
         merge_data(&vout, &tc -> t_leptons);
         merge_data(&vout, &tc -> t_neutrino);
         this -> write(&vout, tc -> name, particle_enum::pmu);
         this -> write(&vout, tc -> name, particle_enum::pdgid);
         this -> write(&tc -> matched_bquarks, tc -> name + "_matched_bquark");
         this -> write(&tc -> matched_leptons, tc -> name + "_matched_lepton");
         this -> write(&tc -> distance  , tc -> name + "_distance");
         this -> write(&tc -> chi2_nu1  , tc -> name + "_nu1_chi2");
         this -> write(&tc -> chi2_nu2  , tc -> name + "_nu2_chi2");
         this -> write(&tc -> nu1, tc -> name + "_nu1", particle_enum::pmu);
         this -> write(&tc -> nu2, tc -> name + "_nu2", particle_enum::pmu);
     }
 }
References merge_data(), selection_template::name, pdgid, pmu, main::sl, selection_template::write(), and main::x.
reconstruction()
void combinatorial::reconstruction (packet_t * data)
Definition at line 72 of file combinatorial.cxx.
{
     std::vector<std::vector<particle_template*>> particles = {this -> make_unique(&data -> particles)};
     if (!particles.size()){return;}
     std::vector<std::pair<neutrino*, neutrino*>> nux = pyc::nusol::combinatorial(
             std::vector<double>({data -> met}), std::vector<double>({data -> phi}),
             particles, data -> device, this -> masstop, this -> massw,
             data -> null, data -> perturb, data -> steps
     );
     if (!nux.size()){return;}
     particle_template* nu1_t = safe_get(&data -> t_neutrino, 0);
     particle_template* nu2_t = safe_get(&data -> t_neutrino, 1);
     particle_template* bqrk1 = safe_get(&data -> t_bquarks , 0);
     particle_template* bqrk2 = safe_get(&data -> t_bquarks , 1);
     particle_template* leps1 = safe_get(&data -> t_leptons , 0);
     particle_template* leps2 = safe_get(&data -> t_leptons , 1);
     for (size_t x(0); x < nux.size(); ++x){
         neutrino* nu1 = std::get<0>(nux[x]);
         neutrino* nu2 = std::get<1>(nux[x]);
         data -> nu1.push_back(nu1);
         data -> nu2.push_back(nu2);
         data -> distance.push_back(nu1 -> min);
         double nu1_chi2_e = chi2(nu1, nu1_t);
         double nu1_chi2_s = chi2(nu2, nu1_t);
         double nu2_chi2_e = chi2(nu1, nu2_t);
         double nu2_chi2_s = chi2(nu2, nu2_t);
         data -> chi2_nu1.push_back((nu1_chi2_e < nu1_chi2_s) ? nu1_chi2_e : nu1_chi2_s);
         data -> chi2_nu2.push_back((nu2_chi2_e < nu2_chi2_s) ? nu2_chi2_e : nu2_chi2_s);
         data -> matched_bquarks.push_back(0);
         data -> matched_leptons.push_back(0);
         if (!nu1_t || !bqrk1 || !leps1){continue;}
         bool found = true;
         found *= std::string(nu1 -> bquark -> hash) == std::string(bqrk1 -> hash);
         found *= std::string(nu2 -> bquark -> hash) == std::string(bqrk2 -> hash);
         if (found){data -> matched_bquarks[x] = 1;}
         // ------ swapped case -------- //
         found = true;
         found *= std::string(nu1 -> bquark -> hash) == std::string(bqrk2 -> hash);
         found *= std::string(nu2 -> bquark -> hash) == std::string(bqrk1 -> hash);
         if (found){data -> matched_bquarks[x] = -1;}
         found = true;
         found *= std::string(nu1 -> lepton -> hash) == std::string(leps1 -> hash);
         found *= std::string(nu2 -> lepton -> hash) == std::string(leps2 -> hash);
         if (found){data -> matched_leptons[x] = 1;}
         // ------ swapped case -------- //
         found = true;
         found *= std::string(nu1 -> lepton -> hash) == std::string(leps2 -> hash);
         found *= std::string(nu2 -> lepton -> hash) == std::string(leps1 -> hash);
         if (found){data -> matched_leptons[x] = -1;}
     }
 }
References chi2(), pyc::nusol::combinatorial(), selection_template::data, main::device, selection_template::hash, selection_template::make_unique(), masstop, massw, safe_get(), and main::x.
Referenced by strategy().
selection()
bool combinatorial::selection (event_template * ev) override virtual
Reimplemented from selection_template.
Definition at line 41 of file combinatorial.cxx.
{
     bsm_4tops* evn = (bsm_4tops*)ev;
     std::vector<top*> tops = this -> upcast<top>(&evn -> Tops);
     int num_leps = 0;
     for (size_t x(0); x < tops.size(); ++x){
         std::map<std::string, particle_template*> ch = tops[x] -> children;
         std::vector<top_children*> ch_ = this -> upcast<top_children>(&ch);
         for (size_t i(0); i < ch_.size(); ++i){
             bool lp = ch_[i] -> is_lep;
             if (!lp){continue;}
             num_leps += lp;
             break;
         }
     }
     return true; //num_leps == 2;
 }
References main::ev, and test_normalization::evn.
strategy()
bool combinatorial::strategy (event_template * ev) override virtual
Reimplemented from selection_template.
Definition at line 154 of file combinatorial.cxx.
{
     bsm_4tops* evn = (bsm_4tops*)ev;
     std::vector<particle_template*> dleps = {};
     merge_data(&dleps, &evn -> Electrons);
     merge_data(&dleps, &evn -> Muons);
     packet_t* pkt_tc = this -> build_packet(evn, "top_children");
     packet_t* pkt_tj = this -> build_packet(evn, "truthjet"    );
     packet_t* pkt_jc = this -> build_packet(evn, "jetchildren" );
     packet_t* pkt_jl = this -> build_packet(evn, "jetleptons"  );
     std::vector<top*> tops = this -> upcast<top>(&evn -> Tops);
     for (size_t x(0); x < tops.size(); ++x){
         this -> update_state(nullptr); // reset the global matching
         top* tpx = tops[x];
         std::vector<particle_template*> ch = this -> vectorize(&tpx -> children);
         for (size_t c(0); c < ch.size(); ++c){
             if (ch[c] -> is_b){this -> b_qrk = ch[c];}
             if (ch[c] -> is_lep){this -> lepton = ch[c];}
             if (ch[c] -> is_nu){this -> nu_tru = ch[c];}
         }
         this -> update_state(pkt_tc);
         this -> b_qrk  = nullptr;
         for (size_t c(0); c < tpx -> TruthJets.size(); ++c){
             truthjet* ptr = tpx -> TruthJets[c];
             if (!ptr -> is_b){continue;}
             this -> b_qrk = ptr; break;
         }
         this -> update_state(pkt_tj);
         this -> b_qrk  = nullptr;
         for (size_t c(0); c < tpx -> Jets.size(); ++c){
             jet* ptr = tpx -> Jets[c];
             if (!ptr -> is_b){continue;}
             this -> b_qrk = ptr; break;
         }
         this -> update_state(pkt_jc);
         this -> lepton = nullptr;
         for (size_t c(0); c < dleps.size(); ++c){
             std::map<std::string, particle_template*> pr = dleps[c] -> parents;
             for (size_t j(0); j < ch.size(); ++j){
                 if (!ch[j] -> is_lep){continue;}
                 if (!pr.count(ch[j] -> hash)){continue;}
                 this -> lepton = dleps[c]; break;
             }
             if (!this -> lepton){continue;}
             break;
         }
         this -> update_state(pkt_jl);
     }
     // ------------- Children ----------- //
     merge_data(&pkt_tc -> particles, &evn -> Children);
     // ------------- Truth Jets + Children --------- //
     merge_data(&pkt_tj -> particles, &evn -> TruthJets);
     merge_data(&pkt_tj -> particles, &pkt_tc -> t_leptons);
     // ------------- Jets + Children -------------- //
     merge_data(&pkt_jc -> particles, &evn -> Jets);
     merge_data(&pkt_jc -> particles, &pkt_tc -> t_leptons);
     // ------------- Jets + Leptons --------------- //
     merge_data(&pkt_jl -> particles, &evn -> DetectorObjects);
     this -> reconstruction(pkt_tc);
     this -> reconstruction(pkt_tj);
     this -> reconstruction(pkt_jc);
     this -> reconstruction(pkt_jl);
     return true;
 }
References c, main::ev, test_normalization::evn, selection_template::hash, is_b, is_lep, is_nu, merge_data(), main::parents, reconstruction(), update_state(), selection_template::vectorize(), and main::x.
update_state()
void combinatorial::update_state (packet_t * data)
Definition at line 139 of file combinatorial.cxx.
{
     if (!data){
         this -> b_qrk  = nullptr;
         this -> lepton = nullptr;
         this -> nu_tru = nullptr;
     }
     if (!this -> nu_tru || !this -> b_qrk || !this -> lepton){return;}
     data -> t_bquarks.push_back(this -> b_qrk);
     data -> t_leptons.push_back(this -> lepton);
     data -> t_neutrino.push_back(this -> nu_tru);
 }
References selection_template::data.
Referenced by strategy().
Member Data Documentation
masstop
double combinatorial::masstop = 172.62*1000
Definition at line 60 of file combinatorial.h.
Referenced by reconstruction().
massw
double combinatorial::massw = 80.385*1000
Definition at line 61 of file combinatorial.h.
Referenced by reconstruction().
num_device
int combinatorial::num_device = 1
Definition at line 59 of file combinatorial.h.
Referenced by clone().
The documentation for this class was generated from the following files:
combinatorial.h
combinatorial.cxx