AnalysisG: ssml_mc20 Class Reference
ssml_mc20 Class Reference
#include <event.h>
Public Member Functions
ssml_mc20 ()
virtual ~ssml_mc20 ()
event_template * clone () override
Creates a new event template instance.
void build (element_t *el) override
Builds an event data structure from an element.
void CompileEvent () override
virtual void reset ()
Resets the event template to its initial state.
void initialize ()
Initializes the event template with necessary settings.
void build ()
Builds an event from raw data.
void build_mapping (std::map< std::string, data_t * > *evnt)
Builds a mapping between event data structures and handlers.
void clear_leaves ()
Clears all leaf string references.
void register_particle (std::string name, std::string collection)
Registers a particle for tracking in this event.
void add_tree (std::string key, std::string tree="")
Adds a tree to the event structure.
void add_branch (std::string key, std::string branch="")
Adds a branch to the event structure.
void add_leaf (std::string key, std::string leaf="")
Adds a leaf (variable) to the event structure.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Static Public Member Functions
static void set_name (std::string *, event_template *)
Static setter for the name property.
static void set_hash (std::string *, event_template *)
Static setter for the hash property.
static void get_tree (std::string *, event_template *)
Static getter for the tree property.
static void set_weight (double *, event_template *)
Static setter for the weight property.
static void set_index (long *, event_template *)
Static setter for the index property.
static void get_leaves (std::vector< std::string > *, event_template *)
Static getter for the leaves property.
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Public Attributes
unsigned long long eventNumber
float event_category
float weight_mc
float weight_pileup
float weight_beamspot
float weight_jvt_effSF
float weight_lep_tightSF
float weight_ftag_effSF
float global_trigger_SF
float phi
float met
float met_sum
float HT_all
int pass_ssee
int pass_ssem
int pass_ssmm
int pass_eem_zveto
int pass_eee_zveto
int pass_emm_zveto
int pass_mmm_zveto
int pass_llll_zveto
int pass_eem
int pass_eee
int pass_emm
int pass_mmm
bool broken_event = false
int n_electrons
int n_fjets
int n_jets
int n_leptons
int n_muons
std::vector< particle_template * > Tops
std::vector< particle_template * > TruthChildren
std::vector< particle_template * > Zprime
std::vector< particle_template * > Leptsn
std::vector< particle_template * > Electrons
std::vector< particle_template * > Jets
std::vector< particle_template * > Leptons
std::vector< particle_template * > Detector
std::vector< particle_template * > TruthJets
cproperty< std::string, event_template > name
Property: A name for this event template or instance.
cproperty< std::string, event_template > hash
Property: A hash string that may identify the configuration or source of this event.
cproperty< std::string, event_template > tree
Property: The primary TTree name for this event.
cproperty< double, event_template > weight
Property: The event weight used for normalization or scaling.
cproperty< long, event_template > index
Property: The event index or entry number in the source TTree.
cproperty< std::vector< std::string >, event_template > leaves
Property: List of TLeaf names (variables) to read for this event.
std::map< std::string, std::string > m_trees = {}
Internal map for storing tree name mappings or aliases.
std::map< std::string, std::string > m_branches = {}
Internal map for storing branch name mappings or aliases.
std::map< std::string, std::string > m_leaves = {}
Internal map for storing leaf name mappings or aliases.
std::map< std::string, std::map< std::string, particle_template * > * > particle_link
Map of registered particles by type and name.
std::map< std::string, particle_template *(*)()> particle_generators
Map of particle generator functions by type.
meta * meta_data = nullptr
Pointer to event metadata.
std::string filename = ""
Source filename for this event.
event_t data
Internal event data structure.
Private Member Functions
template<typename G >
std::map< int, G * > sort_by_index (std::map< std::string, G * > *ipt)
template<typename m , typename G , typename g >
void vectorize (std::map< m, G * > *ipt, std::vector< g * > *vec)
template<typename lx >
bool match_object (std::map< int, top * > *topx, std::map< std::string, lx * > *objects)
Private Attributes
std::map< std::string, jet * > m_jets
std::map< std::string, muon * > m_muons
std::map< std::string, electron * > m_electrons
std::map< std::string, lepton * > m_leptons
std::map< std::string, zboson * > m_zprime
std::map< std::string, top * > m_tops
std::map< std::string, parton * > m_partons
std::map< std::string, truthjet * > m_truthjets
Detailed Description
Definition at line 7 of file events/ssml_mc20/include/ssml_mc20/event.h.
Constructor & Destructor Documentation
ssml_mc20()
ssml_mc20::ssml_mc20 ()
Definition at line 3 of file events/ssml_mc20/cxx/event.cxx.
References event_template::add_leaf(), m_electrons, m_jets, m_leptons, m_muons, m_partons, m_tops, m_truthjets, m_zprime, and event_template::register_particle().
Referenced by clone().
~ssml_mc20()
ssml_mc20::~ssml_mc20 () virtual
Definition at line 59 of file events/ssml_mc20/cxx/event.cxx.
Member Function Documentation
absolute_path()
std::string tools::absolute_path (std::string path) static inherited
Converts a relative path to an absolute path.
Parameters
path The path to convert.
Returns
The absolute version of the path.
Definition at line 49 of file tools/cxx/io.cxx.
Referenced by analysis::analysis(), analysis::build_events(), io::check_root_file_paths(), and io::trigger_pcm().
add_branch()
void event_template::add_branch (std::string key, std::string branch = "") inherited
Adds a branch to the event structure.
Parameters
key The primary key or name for this branch (e.g., "el_").
branch The specific branch name if different from key, or an alias.
add_leaf()
void event_template::add_leaf (std::string key, std::string val = "") inherited
Adds a leaf (variable) to the event structure.
Adds a leaf to the event template.
Parameters
key The primary key or name for this leaf (e.g., "met_et").
leaf The specific leaf name if different from key, or an alias.
key The key name for the leaf.
val The value for the leaf (defaults to key if empty).
Definition at line 39 of file event/cxx/properties.cxx.
References event_template::m_leaves, and event_template::name.
Referenced by bsm_4tops::bsm_4tops(), exp_mc20::exp_mc20(), gnn_event::gnn_event(), and ssml_mc20().
add_tree()
void event_template::add_tree (std::string key, std::string tree = "") inherited
Adds a tree to the event structure.
Parameters
key The primary key or name for this tree.
tree The specific tree name if different from key, or an alias.
build() [1/2]
void event_template::build () inherited
Builds an event from raw data.
Virtual method that processes raw data to create a structured event representation. This base method delegates implementation to the overloaded build(element_t*) method.
build() [2/2]
void ssml_mc20::build (element_t * el) override virtual
Builds an event data structure from an element.
Empty implementation of the build method (to be overridden in derived classes).
Parameters
el Pointer to an element_t structure containing raw event data.
Virtual method that processes raw element data to build the event structure. This method is typically overridden in derived classes to handle specific event formats.
Parameters
ele Pointer to an element_t structure
This is a placeholder method that derived classes are expected to override with their specific event building logic.
Reimplemented from event_template.
Definition at line 62 of file events/ssml_mc20/cxx/event.cxx.
References event_category, eventNumber, global_trigger_SF, HT_all, met_sum, n_electrons, n_fjets, n_jets, n_leptons, n_muons, pass_eee, pass_eee_zveto, pass_eem, pass_eem_zveto, pass_emm, pass_emm_zveto, pass_llll_zveto, pass_mmm, pass_mmm_zveto, pass_ssee, pass_ssem, pass_ssmm, phi, weight_beamspot, weight_ftag_effSF, weight_jvt_effSF, weight_lep_tightSF, weight_mc, and weight_pileup.
build_mapping()
void event_template::build_mapping (std::map< std::string, data_t * > * evnt) inherited
Builds a mapping between event data structures and handlers.
Builds a mapping between event data and tree/branch structures.
Parameters
evnt Pointer to a map associating strings with data_t pointers.
Creates relationships between the event's trees, branches, leaves and their corresponding data handlers to facilitate data access and manipulation.
Parameters
evnt Map of data pointers keyed by name
Creates internal mapping between the data containers and the logical tree/branch/leaf structure used in physics analysis.
Definition at line 78 of file event_template.cxx.
References event_template::m_leaves, event_template::particle_link, tools::split(), and tools::type_name().
clear_leaves()
void event_template::clear_leaves () inherited
Clears all leaf string references.
Resets internal collections of trees, branches, and leaves. This is useful when preparing to process a new event format.
clone()
event_template * ssml_mc20::clone () override virtual
Creates a new event template instance.
Creates a copy of the current event_template object.
Returns
Pointer to the newly created event_template object.
Factory method that creates and returns a new instance of the event_template class. Useful for creating derived class instances in a polymorphic context.
Returns
Pointer to the newly created event_template object
This method creates a new instance of the event_template class, copying the current object's state into the new instance.
Reimplemented from event_template.
Definition at line 60 of file events/ssml_mc20/cxx/event.cxx.
References ssml_mc20().
CompileEvent()
void ssml_mc20::CompileEvent () override
Definition at line 119 of file events/ssml_mc20/cxx/event.cxx.
References broken_event, Detector, Electrons, event_template::hash, Leptons, Leptsn, m_electrons, m_jets, m_leptons, m_muons, m_partons, m_tops, m_truthjets, m_zprime, match_object(), px, sort_by_index(), Tops, vectorize(), and Zprime.
create_path()
void tools::create_path (std::string path) static inherited
Creates a directory path, including parent directories if needed.
Parameters
path The directory path to create.
Definition at line 6 of file tools/cxx/io.cxx.
References f, and tools::split().
Referenced by analysis::analysis(), analysis::build_inference(), plotting::build_path(), analysis::build_project(), container::compile(), metrics::dump_mass_plots(), metric_template::execute(), metrics::generic_painter(), analysis::start(), io::start(), and io::trigger_pcm().
delete_path()
void tools::delete_path (std::string path) static inherited
Deletes a directory path and its contents.
Parameters
path The directory path to delete.
Definition at line 22 of file tools/cxx/io.cxx.
ends_with()
bool tools::ends_with (std::string * inpt, std::string val) static inherited
Checks if a string ends with a specific substring.
Parameters
inpt Pointer to the string to check.
val The substring to check for at the end.
Returns
True if the string ends with the substring, false otherwise.
Definition at line 71 of file strings.cxx.
References l.
Referenced by plotting::build_path(), io::check_root_file_paths(), dataloader::dump_graphs(), tools::ls(), meta::parse_json(), io::scan_keys(), and analysis::start().
extract()
template<typename C , typename T > static void tools::extract (std::vector< T > * prop, std::vector< C * > * src, void(*)(T *, C *) get_prop) inline static inherited
Extracts a specific property from a vector of objects into a new vector.
Template Parameters
C The type of objects in the source vector.
T The type of the property to extract.
Parameters
prop Pointer to the output vector to fill with property values.
src Pointer to the source vector of objects.
get_prop Function pointer to extract the property from an object.
< Clear the properties vector.
< Reserve space for the property values.
< Loop through each object in the source vector.
< Create a default-initialized property variable.
< Call the provided function to extract the property.
< Add the property value to the output vector.
Definition at line 216 of file tools.h.
flush()
template<typename T > static void tools::flush (std::vector< T * > * inpt) inline static inherited
Empties a vector and all objects it points to.
Template Parameters
T The type of pointers in the vector.
Parameters
inpt Pointer to the vector to empty.
< Loop through all elements in the vector.
< Delete the object the pointer points to.
< Set the pointer to nullptr to avoid dangling pointers.
< Clear the vector.
Definition at line 167 of file tools.h.
Referenced by analysis::~analysis(), dataloader::~dataloader(), sampletracer::compile_objects(), and io::root_end().
get_leaves()
void event_template::get_leaves (std::vector< std::string > * inpt, event_template * ev) static inherited
Static getter for the leaves property.
Gets all leaves from the event template.
Parameters
[out] inpt Pointer to a vector of strings to store the leaf names.
[in] ev Pointer to the event_template instance.
inpt Vector to store leaf names.
ev Pointer to the event template.
Definition at line 51 of file event/cxx/properties.cxx.
References event_template::m_leaves.
Referenced by event_template::event_template().
get_tree()
void event_template::get_tree (std::string * name, event_template * ev) static inherited
Static getter for the tree property.
Gets the tree name from the event.
Parameters
[out] name Pointer to a string to store the tree name.
[in] ev Pointer to the event_template instance.
name Pointer to store the tree name.
ev Pointer to the event template.
Definition at line 72 of file event/cxx/properties.cxx.
References event_template::data, and event_t::name.
Referenced by event_template::event_template().
has_string()
bool tools::has_string (std::string * inpt, std::string trg) static inherited
Checks if a string contains a specific substring.
Parameters
inpt Pointer to the string to check.
trg The substring to search for.
Returns
True if the substring is found, false otherwise.
Definition at line 65 of file strings.cxx.
References f.
Referenced by analysis::check_cache(), meta::compiler(), metrics::generic_painter(), dataloader::restore_graphs_(), meta::scan_sow(), model_template::set_device(), and metric_template::set_run_name().
has_value()
bool tools::has_value (std::vector< std::string > * data, std::string trg) static inherited
Checks if a vector of strings contains a specific string.
Parameters
data Pointer to the vector to search.
trg The string to search for.
Returns
True if the string is found in the vector, false otherwise.
Definition at line 77 of file strings.cxx.
Referenced by io::scan_keys().
initialize()
void event_template::initialize () inherited
Initializes the event template with necessary settings.
Sets up internal data structures and configurations. This method should be called before performing other operations on the template.
is_file()
bool tools::is_file (std::string path) static inherited
Checks if a path refers to an existing file.
Parameters
path The path to check.
Returns
True if the path is a file and exists, false otherwise.
Definition at line 30 of file tools/cxx/io.cxx.
Referenced by io::check_root_file_paths(), analysis::initialize_loop(), metric_template::set_run_name(), and io::start().
ls()
std::vector< std::string > tools::ls (std::string path, std::string ext = "") static inherited
Lists files in a directory, optionally filtered by extension.
Parameters
path The directory to search.
ext File extension filter. If empty, all files are listed.
Returns
A vector of filenames in the directory.
Definition at line 35 of file tools/cxx/io.cxx.
References tools::ends_with(), and tools::split().
Referenced by analysis::analysis(), analysis::check_cache(), io::check_root_file_paths(), dataloader::restore_graphs(), and io::trigger_pcm().
match_object()
template<typename lx > bool ssml_mc20::match_object (std::map< int, top * > * topx, std::map< std::string, lx * > * objects) inline private
Definition at line 94 of file events/ssml_mc20/include/ssml_mc20/event.h.
References count(), Jets, Leptons, TruthChildren, and TruthJets.
Referenced by CompileEvent().
put()
template<typename g > static void tools::put (std::vector< g * > * out, std::vector< g * > * src, std::vector< int > * trg) inline static inherited
Fills a vector with pointers from another vector based on a selection index.
Template Parameters
g The type of objects being pointed to.
Parameters
out Pointer to the output vector to fill.
src Pointer to the source vector to select from.
trg Pointer to a vector of indices for selection.
< Clear the output vector.
< Reserve space for the output elements.
< Loop through each selected index.
< Get the object at the selected index.
< Add it to the output vector.
< Mark the object as in use.
Definition at line 197 of file tools.h.
Referenced by dataloader::get_k_train_set(), dataloader::get_k_validation_set(), and dataloader::get_test_set().
register_particle()
void event_template::register_particle (std::string name, std::string collection) inherited
Registers a particle for tracking in this event.
Parameters
name The name that identifies this particle type (e.g., "Electron").
collection The branch prefix for this particle collection (e.g., "el_").
Referenced by bsm_4tops::bsm_4tops(), exp_mc20::exp_mc20(), gnn_event::gnn_event(), and ssml_mc20().
rename()
void tools::rename (std::string start, std::string target) static inherited
Renames a file or directory.
Parameters
start The original path.
target The new path.
Definition at line 18 of file tools/cxx/io.cxx.
Referenced by dataloader::dump_graphs().
replace()
void tools::replace (std::string * in, std::string repl_str, std::string repl_with) static inherited
Replaces all occurrences of a substring in a string.
Parameters
in Pointer to the string to modify.
repl_str The substring to replace.
repl_with The replacement string.
Definition at line 5 of file strings.cxx.
Referenced by analysis::build_graphs(), analysis::check_cache(), dataloader::dump_graphs(), meta::get_campaign(), meta::parse_json(), and analysis::start().
reset()
virtual void event_template::reset () virtual inherited
Resets the event template to its initial state.
Clears all event data and prepares the template for new event processing.
set_hash()
void event_template::set_hash (std::string * path, event_template * ev) static inherited
Static setter for the hash property.
Sets the hash for the event.
Parameters
[in] hash Pointer to a string containing the hash.
[in] ev Pointer to the event_template instance.
path Pointer to the path used for hashing.
ev Pointer to the event template.
Definition at line 92 of file event/cxx/properties.cxx.
References event_template::data, event_t::hash, event_template::index, and tools::to_string().
Referenced by event_template::event_template().
set_index()
void event_template::set_index (long * inpt, event_template * ev) static inherited
Static setter for the index property.
Sets the index for the event.
Parameters
[in] val Pointer to a long containing the index value.
[in] ev Pointer to the event_template instance.
inpt Pointer to the index value.
ev Pointer to the event template.
Definition at line 125 of file event/cxx/properties.cxx.
References event_template::data, and event_t::index.
Referenced by event_template::event_template().
set_name()
void event_template::set_name (std::string * name, event_template * ev) static inherited
Static setter for the name property.
Sets the name for the event.
Parameters
[in] name Pointer to a string containing the name.
[in] ev Pointer to the event_template instance.
name Pointer to the name.
ev Pointer to the event template.
Definition at line 82 of file event/cxx/properties.cxx.
References event_template::data, event_template::name, and event_t::name.
Referenced by event_template::event_template().
set_weight()
void event_template::set_weight (double * inpt, event_template * ev) static inherited
Static setter for the weight property.
Sets the weight for the event.
Parameters
[in] val Pointer to a double containing the weight value.
[in] ev Pointer to the event_template instance.
inpt Pointer to the weight value.
ev Pointer to the event template.
Definition at line 115 of file event/cxx/properties.cxx.
References event_template::data, and event_t::weight.
Referenced by event_template::event_template().
sort_by_index()
template<typename G > std::map< int, G * > ssml_mc20::sort_by_index (std::map< std::string, G * > * ipt) inline private
Definition at line 80 of file events/ssml_mc20/include/ssml_mc20/event.h.
References event_template::data, and event_template::index.
Referenced by CompileEvent().
split()
std::vector< std::string > tools::split (std::string inpt, std::string del) inherited
Splits a string into a vector of substrings based on a delimiter.
Parameters
inpt The input string to split.
del The delimiter.
Returns
A vector of substrings.
Definition at line 23 of file strings.cxx.
References index.
Referenced by analysis::build_events(), analysis::build_graphs(), analysis::build_inference(), event_template::build_mapping(), analysis::check_cache(), container::compile(), sampletracer::compile_objects(), meta::compiler(), tools::create_path(), dataloader::dump_graphs(), meta::hash(), tools::ls(), graph_t::meta_deserialize(), dataloader::restore_graphs_(), io::root_begin(), model_template::set_device(), metric_template::set_run_name(), metric_template::set_variables(), and analysis::start().
sum()
template<typename g > g tools::sum (std::vector< g > * inpt) inline inherited
Sums the elements of a vector.
Template Parameters
g The type of elements in the vector.
Parameters
inpt Pointer to the vector to sum.
Returns
The sum of all elements.
< Initialize the output variable.
< Return the sum.
Definition at line 183 of file tools.h.
Referenced by metrics::add_th1f_accuracy(), sampletracer::compile_objects(), particle_template::DeltaR(), graph_template::double_neutrino(), grift::forward(), recursivegraphneuralnetwork::forward(), matching::match_obj(), and grift::message().
to_string() [1/2]
std::string tools::to_string (double val) static inherited
Converts a double value to a string with standard precision.
Parameters
val The double value to convert.
Returns
The string representation of the value.
Definition at line 59 of file strings.cxx.
Referenced by dataloader::generate_kfold_set(), dataloader::generate_test_set(), particle_template::get_hash(), topefficiency::region(), dataloader::restore_dataset(), event_template::set_hash(), selection_template::set_hash(), parton::strategy(), topjets::strategy(), toptruthjets::strategy(), and parton::top_mass_contribution().
to_string() [2/2]
std::string tools::to_string (double val, int prec) static inherited
Converts a double value to a string with specified precision.
Parameters
val The double value to convert.
prec The number of decimal places to consider.
Returns
The string representation of the value.
Definition at line 91 of file strings.cxx.
trim()
std::string tools::trim (std::string s) inherited
Removes whitespace from the beginning and end of a string.
Parameters
s The string to trim.
Returns
The trimmed string.
type_name()
template<typename T > std::string tools::type_name () inline inherited
Gets the type name of a variable as a string (for debugging).
Template Parameters
T The type to get the name of.
Returns
The name of the type as a string.
< Gets the type name via RTTI.
< Returns the type name.
Definition at line 155 of file tools.h.
Referenced by event_template::build_mapping().
vectorize()
template<typename m , typename G , typename g > void ssml_mc20::vectorize (std::map< m, G * > * ipt, std::vector< g * > * vec) inline private
Definition at line 88 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by CompileEvent().
Member Data Documentation
broken_event
bool ssml_mc20::broken_event = false
Definition at line 44 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by CompileEvent().
data
event_t event_template::data inherited
Internal event data structure.
Definition at line 292 of file event_template.h.
Referenced by event_template::get_tree(), gnn_event::print(), gnn_event::print(), gnn_event::print(), event_template::set_hash(), event_template::set_index(), event_template::set_name(), event_template::set_weight(), bsm_4tops::sort_by_index(), exp_mc20::sort_by_index(), gnn_event::sort_by_index(), and sort_by_index().
Detector
std::vector<particle_template*> ssml_mc20::Detector
Definition at line 60 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by CompileEvent().
Electrons
std::vector<particle_template*> ssml_mc20::Electrons
Definition at line 56 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by CompileEvent().
event_category
float ssml_mc20::event_category
Definition at line 14 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
eventNumber
unsigned long long ssml_mc20::eventNumber
Definition at line 12 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
filename
std::string event_template::filename = "" inherited
Source filename for this event.
Definition at line 291 of file event_template.h.
Referenced by event_template::~event_template().
global_trigger_SF
float ssml_mc20::global_trigger_SF
Definition at line 22 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
hash
cproperty<std::string, event_template> event_template::hash inherited
Property: A hash string that may identify the configuration or source of this event.
This property stores a hash value typically used to uniquely identify the event or its configuration. This can be useful for caching or cross-referencing.
Definition at line 203 of file event_template.h.
Referenced by event_template::event_template(), bsm_4tops::CompileEvent(), gnn_event::CompileEvent(), CompileEvent(), and gnn_event::sum().
HT_all
float ssml_mc20::HT_all
Definition at line 28 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
index
cproperty<long, event_template> event_template::index inherited
Property: The event index or entry number in the source TTree.
This property stores the position or index of the event within the source data, which is useful for tracing or identifying individual events.
Definition at line 245 of file event_template.h.
Referenced by event_template::event_template(), bsm_4tops::CompileEvent(), exp_mc20::CompileEvent(), gnn_event::CompileEvent(), event_template::set_hash(), bsm_4tops::sort_by_index(), exp_mc20::sort_by_index(), gnn_event::sort_by_index(), and sort_by_index().
Jets
std::vector<particle_template*> ssml_mc20::Jets
Definition at line 58 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by match_object().
leaves
cproperty<std::vector<std::string>, event_template> event_template::leaves inherited
Property: List of TLeaf names (variables) to read for this event.
This property stores the names of all variables or data fields that should be extracted and made available from the raw data for this event.
Definition at line 259 of file event_template.h.
Referenced by event_template::event_template().
Leptons
std::vector<particle_template*> ssml_mc20::Leptons
Definition at line 59 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by CompileEvent(), and match_object().
Leptsn
std::vector<particle_template*> ssml_mc20::Leptsn
Definition at line 55 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by CompileEvent().
m_branches
std::map<std::string, std::string> event_template::m_branches = {} inherited
Internal map for storing branch name mappings or aliases.
Map of branch name aliases.
Definition at line 278 of file event_template.h.
m_electrons
std::map<std::string, electron*> ssml_mc20::m_electrons private
Definition at line 70 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by ssml_mc20(), and CompileEvent().
m_jets
std::map<std::string, jet*> ssml_mc20::m_jets private
Definition at line 68 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by ssml_mc20(), and CompileEvent().
m_leaves
std::map<std::string, std::string> event_template::m_leaves = {} inherited
Internal map for storing leaf name mappings or aliases.
Map of leaf name aliases.
Definition at line 283 of file event_template.h.
Referenced by event_template::add_leaf(), event_template::build_mapping(), and event_template::get_leaves().
m_leptons
std::map<std::string, lepton*> ssml_mc20::m_leptons private
Definition at line 71 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by ssml_mc20(), and CompileEvent().
m_muons
std::map<std::string, muon*> ssml_mc20::m_muons private
Definition at line 69 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by ssml_mc20(), and CompileEvent().
m_partons
std::map<std::string, parton*> ssml_mc20::m_partons private
Definition at line 76 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by ssml_mc20(), and CompileEvent().
m_tops
std::map<std::string, top*> ssml_mc20::m_tops private
Definition at line 74 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by ssml_mc20(), and CompileEvent().
m_trees
std::map<std::string, std::string> event_template::m_trees = {} inherited
Internal map for storing tree name mappings or aliases.
This map connects logical tree names (used as keys in the analysis) with their actual names in the ROOT files. Map of tree name aliases.
Definition at line 273 of file event_template.h.
m_truthjets
std::map<std::string, truthjet*> ssml_mc20::m_truthjets private
Definition at line 77 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by ssml_mc20(), and CompileEvent().
m_zprime
std::map<std::string, zboson*> ssml_mc20::m_zprime private
Definition at line 73 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by ssml_mc20(), and CompileEvent().
met
float ssml_mc20::met
Definition at line 25 of file events/ssml_mc20/include/ssml_mc20/event.h.
met_sum
float ssml_mc20::met_sum
Definition at line 26 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
meta_data
meta* event_template::meta_data = nullptr inherited
Pointer to event metadata.
Definition at line 290 of file event_template.h.
n_electrons
int ssml_mc20::n_electrons
Definition at line 46 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
n_fjets
int ssml_mc20::n_fjets
Definition at line 47 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
n_jets
int ssml_mc20::n_jets
Definition at line 48 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
n_leptons
int ssml_mc20::n_leptons
Definition at line 49 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
n_muons
int ssml_mc20::n_muons
Definition at line 50 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
name
cproperty<std::string, event_template> event_template::name inherited
Property: A name for this event template or instance.
This property allows setting and getting a custom name for the event, which can be helpful in identifying or labeling events in complex analyses.
Definition at line 189 of file event_template.h.
Referenced by event_template::add_leaf(), and event_template::set_name().
particle_generators
std::map<std::string, particle_template*(*)()> event_template::particle_generators inherited
Map of particle generator functions by type.
Definition at line 288 of file event_template.h.
Referenced by event_template::~event_template().
particle_link
std::map<std::string, std::map<std::string, particle_template*>*> event_template::particle_link inherited
Map of registered particles by type and name.
Definition at line 287 of file event_template.h.
Referenced by event_template::build_mapping().
pass_eee
int ssml_mc20::pass_eee
Definition at line 40 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
pass_eee_zveto
int ssml_mc20::pass_eee_zveto
Definition at line 34 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
pass_eem
int ssml_mc20::pass_eem
Definition at line 39 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
pass_eem_zveto
int ssml_mc20::pass_eem_zveto
Definition at line 33 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
pass_emm
int ssml_mc20::pass_emm
Definition at line 41 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
pass_emm_zveto
int ssml_mc20::pass_emm_zveto
Definition at line 35 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
pass_llll_zveto
int ssml_mc20::pass_llll_zveto
Definition at line 37 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
pass_mmm
int ssml_mc20::pass_mmm
Definition at line 42 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
pass_mmm_zveto
int ssml_mc20::pass_mmm_zveto
Definition at line 36 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
pass_ssee
int ssml_mc20::pass_ssee
Definition at line 29 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
pass_ssem
int ssml_mc20::pass_ssem
Definition at line 30 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
pass_ssmm
int ssml_mc20::pass_ssmm
Definition at line 31 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
phi
float ssml_mc20::phi
Definition at line 24 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
Tops
std::vector<particle_template*> ssml_mc20::Tops
Definition at line 52 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by CompileEvent().
tree
cproperty<std::string, event_template> event_template::tree inherited
Property: The primary TTree name for this event.
This property stores the name of the main TTree from which this event originates. This is particularly relevant when working with ROOT files containing multiple TTrees.
Definition at line 217 of file event_template.h.
Referenced by event_template::event_template().
TruthChildren
std::vector<particle_template*> ssml_mc20::TruthChildren
Definition at line 53 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by match_object().
TruthJets
std::vector<particle_template*> ssml_mc20::TruthJets
Definition at line 61 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by match_object().
weight
cproperty<double, event_template> event_template::weight inherited
Property: The event weight used for normalization or scaling.
This property stores the event weight, which is typically used for normalization, cross-section adjustments, or other physics-based scalings.
Definition at line 231 of file event_template.h.
Referenced by event_template::event_template(), bsm_4tops::build(), exp_mc20::build(), and gnn_event::build().
weight_beamspot
float ssml_mc20::weight_beamspot
Definition at line 18 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
weight_ftag_effSF
float ssml_mc20::weight_ftag_effSF
Definition at line 21 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
weight_jvt_effSF
float ssml_mc20::weight_jvt_effSF
Definition at line 19 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
weight_lep_tightSF
float ssml_mc20::weight_lep_tightSF
Definition at line 20 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
weight_mc
float ssml_mc20::weight_mc
Definition at line 16 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
weight_pileup
float ssml_mc20::weight_pileup
Definition at line 17 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by build().
Zprime
std::vector<particle_template*> ssml_mc20::Zprime
Definition at line 54 of file events/ssml_mc20/include/ssml_mc20/event.h.
Referenced by CompileEvent().
The documentation for this class was generated from the following files:
events/ssml_mc20/include/ssml_mc20/event.h
events/ssml_mc20/cxx/event.cxx