AnalysisG: topmatching Class Reference
topmatching Class Reference
#include <topmatching.h>
Public Member Functions
topmatching ()
~topmatching () override
selection_template * clone () override
bool selection (event_template *ev) override
bool strategy (event_template *ev) override
void merge (selection_template *sl) override
template<typename T >
std::vector< T * > vectorize (std::map< std::string, T * > *mp)
template<typename T >
std::vector< particle_template * > downcast (std::vector< T * > *mp)
topmatching ()
~topmatching () override
selection_template * clone () override
bool selection (event_template *ev) override
bool strategy (event_template *ev) override
void merge (selection_template *sl) override
template<typename T >
std::vector< T * > vectorize (std::map< std::string, T * > *mp)
template<typename T >
std::vector< particle_template * > downcast (std::vector< T * > *mp)
Public Member Functions inherited from selection_template
selection_template ()
virtual ~selection_template ()
virtual void bulk_write (const long *idx, std::string *hx)
virtual void write (std::vector< particle_template * > *particles, std::string name, particle_enum attrs)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< std::vector< double >> *data)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< int > *data)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< double > *data)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< bool > *data)
template<typename g >
void write (g *var, std::string name)
template<typename g >
void write (g var, std::string name)
std::vector< std::map< std::string, float > > reverse_hash (std::vector< std::string > *hashes)
bool CompileEvent ()
selection_template * build (event_template *ev)
bool operator== (selection_template &p)
template<typename g , typename k >
void sum (std::vector< g * > *ch, k **out)
template<typename g >
void safe_delete (std::vector< g * > *particles)
template<typename g >
g * sum (std::map< std::string, g * > *ch)
template<typename g >
float sum (std::vector< g * > *ch)
template<typename g >
std::vector< g * > vectorize (std::map< std::string, g * > *in)
template<typename g >
std::vector< g * > make_unique (std::vector< g * > *inpt)
template<typename g >
void downcast (std::vector< g * > *inpt, std::vector< particle_template * > *out)
template<typename o , typename g >
void upcast (std::map< std::string, o * > *inpt, std::vector< g * > *out)
template<typename o , typename g >
void upcast (std::vector< o * > *inpt, std::vector< g * > *out)
template<typename g >
void get_leptonics (std::map< std::string, g * > inpt, std::vector< particle_template * > *out)
template<typename g , typename j >
bool contains (std::vector< g * > *inpt, j *pcheck)
Public Member Functions inherited from tools
tools ()
Constructor for the tools class.
~tools ()
Destructor for the tools class.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Public Attributes
std::vector< float > truth_top = {}
std::vector< int > no_children = {}
std::vector< float > topchildren_mass = {}
std::vector< int > topchildren_leptonic = {}
std::vector< float > toptruthjets_mass = {}
std::vector< int > toptruthjets_leptonic = {}
std::vector< int > toptruthjets_njets = {}
std::vector< float > topjets_children_mass = {}
std::vector< int > topjets_children_leptonic = {}
std::vector< float > topjets_leptons_mass = {}
std::vector< int > topjets_leptons_leptonic = {}
std::vector< int > topjets_leptons_pdgid = {}
std::vector< int > topjets_leptons_njets = {}
std::map< std::string, std::vector< float > > truth_children = {}
std::map< std::string, std::vector< float > > truth_jets = {}
std::map< std::string, std::vector< float > > n_truth_jets_lep = {}
std::map< std::string, std::vector< float > > n_truth_jets_had = {}
std::map< std::string, std::vector< float > > jets_truth_leps = {}
std::map< std::string, std::vector< float > > jet_leps = {}
std::map< std::string, std::vector< float > > n_jets_lep = {}
std::map< std::string, std::vector< float > > n_jets_had = {}
Public Attributes inherited from selection_template
cproperty< std::string, selection_template > name
cproperty< std::string, selection_template > hash
cproperty< std::string, selection_template > tree
cproperty< double, selection_template > weight
cproperty< long, selection_template > index
meta * meta_data = nullptr
std::string filename = ""
event_t data
int threadIdx = -1
std::map< std::string, std::map< std::string, float > > passed_weights = {}
std::map< std::string, meta_t > matched_meta = {}
Additional Inherited Members
Static Public Member Functions inherited from selection_template
static void set_name (std::string *, selection_template *)
static void get_name (std::string *, selection_template *)
static void set_hash (std::string *, selection_template *)
static void get_hash (std::string *, selection_template *)
static void get_tree (std::string *, selection_template *)
static void set_weight (double *, selection_template *)
static void get_weight (double *, selection_template *)
static void set_index (long *, selection_template *)
Static Public Member Functions inherited from tools
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Detailed Description
Definition at line 7 of file mc16/topmatching/topmatching.h.
Constructor & Destructor Documentation
topmatching() [1/2]
topmatching::topmatching ()
Definition at line 3 of file mc16/topmatching/topmatching.cxx.
 {this -> name = "top-matching";}
References selection_template::name.
Referenced by clone().
~topmatching() [1/2]
topmatching::~topmatching () override
Definition at line 4 of file mc16/topmatching/topmatching.cxx.
 {}
topmatching() [2/2]
topmatching::topmatching ()
~topmatching() [2/2]
topmatching::~topmatching () override
Member Function Documentation
clone() [1/2]
selection_template * topmatching::clone () override virtual
Reimplemented from selection_template.
Definition at line 6 of file mc16/topmatching/topmatching.cxx.
{
     return (selection_template*)new topmatching();
 }
References topmatching().
clone() [2/2]
selection_template* topmatching::clone () override virtual
Reimplemented from selection_template.
downcast() [1/2]
template<typename T > std::vector<particle_template*> topmatching::downcast (std::vector< T * > * mp) inline
Definition at line 42 of file mc20/topmatching/topmatching.h.
{
             std::vector<particle_template*> out = {};
             for (size_t x(0); x < mp -> size(); ++x){
                 out.push_back((particle_template*)mp -> at(x));
             }
             return out;
         }
References main::mp, main::out, and main::x.
downcast() [2/2]
template<typename T > std::vector<particle_template*> topmatching::downcast (std::vector< T * > * mp) inline
Definition at line 46 of file mc16/topmatching/topmatching.h.
{
             std::vector<particle_template*> out = {};
             for (size_t x(0); x < mp -> size(); ++x){
                 out.push_back((particle_template*)mp -> at(x));
             }
             return out;
         }
References main::mp, main::out, and main::x.
merge() [1/2]
void topmatching::merge (selection_template * sl) override virtual
Reimplemented from selection_template.
Definition at line 10 of file mc16/topmatching/topmatching.cxx.
{
     topmatching* slt = (topmatching*)sl;
     this -> write(&slt -> truth_top, "top_mass");
     this -> write(&slt -> topchildren_mass    , "topchildren_mass");
     this -> write(&slt -> topchildren_leptonic, "topchildren_islep");
     this -> write(&slt -> toptruthjets_mass    , "toptruthjets_mass");
     this -> write(&slt -> toptruthjets_leptonic, "toptruthjets_islep");
     this -> write(&slt -> toptruthjets_njets   , "toptruthjets_njets");
     this -> write(&slt -> topjets_children_mass    , "topjets_children_mass");
     this -> write(&slt -> topjets_children_leptonic, "topjets_children_islep");
     this -> write(&slt -> topjets_leptons_mass    , "topjets_leptons_mass");
     this -> write(&slt -> topjets_leptons_leptonic, "topjets_leptons_islep");
     this -> write(&slt -> topjets_leptons_pdgid   , "topjets_leptons_pdgid");
     this -> write(&slt -> topjets_leptons_njets   , "topjets_leptons_njets");
 }
References main::sl, topchildren_leptonic, topchildren_mass, topjets_children_leptonic, topjets_children_mass, topjets_leptons_leptonic, topjets_leptons_mass, topjets_leptons_njets, topjets_leptons_pdgid, toptruthjets_leptonic, toptruthjets_mass, toptruthjets_njets, truth_top, and selection_template::write().
merge() [2/2]
void topmatching::merge (selection_template * sl) override virtual
Reimplemented from selection_template.
selection() [1/2]
bool topmatching::selection (event_template * ev) override virtual
Reimplemented from selection_template.
selection() [2/2]
bool topmatching::selection (event_template * ev) override virtual
Reimplemented from selection_template.
Definition at line 31 of file mc16/topmatching/topmatching.cxx.
 {return true;}
strategy() [1/2]
bool topmatching::strategy (event_template * ev) override virtual
Reimplemented from selection_template.
strategy() [2/2]
bool topmatching::strategy (event_template * ev) override virtual
Reimplemented from selection_template.
Definition at line 33 of file mc16/topmatching/topmatching.cxx.
{
     bsm_4tops* evn = (bsm_4tops*)ev;
     std::vector<particle_template*> dleps = {};
     merge_data(&dleps, &evn -> Electrons);
     merge_data(&dleps, &evn -> Muons);
     std::vector<particle_template*> dtops = evn -> Tops;
     for (size_t x(0); x < dtops.size(); ++x){
         top* top_i = (top*)dtops[x];
         this -> truth_top.push_back(float(top_i -> mass)/1000);
         std::map<std::string, particle_template*> children_ = top_i -> children;
         std::vector<particle_template*> ch = this -> vectorize(&children_);
         if (!ch.size()){this -> no_children.push_back(1);}
         bool is_lepton = false;
         std::vector<particle_template*> ch_ = {};
         for (size_t c(0); c < ch.size(); ++c){
             if (!ch[c] -> is_lep && !ch[c] -> is_nu){continue;}
             ch_.push_back(ch[c]);
             is_lepton = true;
         }
         if (ch.size()){
             this -> topchildren_mass.push_back(this -> sum(&ch));
             this -> topchildren_leptonic.push_back(is_lepton);
         }
         std::vector<particle_template*> tj = this -> downcast(&top_i -> TruthJets);
         merge_data(&tj, &ch_);
         if (top_i -> TruthJets.size()){
             this -> toptruthjets_mass.push_back(this -> sum(&tj));
             this -> toptruthjets_leptonic.push_back(is_lepton);
             this -> toptruthjets_njets.push_back(int(top_i -> TruthJets.size()));
         }
         if (!top_i -> Jets.size()){continue;}
         std::vector<particle_template*> jt = this -> downcast(&top_i -> Jets);
         merge_data(&jt, &ch_);
         this -> topjets_children_mass.push_back(this -> sum(&jt));
         this -> topjets_children_leptonic.push_back(is_lepton);
         int pdgid = 0;
         std::vector<particle_template*> jts = this -> downcast(&top_i -> Jets);
         for (size_t c(0); c < dleps.size(); ++c){
             std::map<std::string, particle_template*> pr = dleps[c] -> parents;
             bool lep_match = false;
             for (size_t x(0); x < ch.size(); ++x){
                 if (!pr.count(ch[x] -> hash)){continue;}
                 if (!ch[x] -> is_lep){continue;}
                 pdgid = ch[x] -> pdgid;
                 lep_match = true;
                 break;
             }
             if (!lep_match){continue;}
             jts.push_back(dleps[c]);
             break;
         }
         for (size_t c(0); c < ch_.size(); ++c){
             if (!ch_[c] -> is_nu){continue;}
             jts.push_back(ch_[c]);
         }
         this -> topjets_leptons_mass.push_back(this -> sum(&jts));
         this -> topjets_leptons_leptonic.push_back(is_lepton);
         this -> topjets_leptons_pdgid.push_back(std::abs(pdgid));
         this -> topjets_leptons_njets.push_back(int(top_i -> Jets.size()));
     }
     return true;
 }
References main::ev, test_normalization::evn, mass, merge_data(), no_children, truth_top, vectorize(), and main::x.
vectorize() [1/2]
template<typename T > std::vector<T*> topmatching::vectorize (std::map< std::string, T * > * mp) inline
Definition at line 34 of file mc20/topmatching/topmatching.h.
{
             typename std::vector<T*> out = {};
             typename std::map<std::string, T*>::iterator itr = mp -> begin();
             for (; itr != mp -> end(); ++itr){out.push_back(itr -> second);}
             return out;
         }
References end(), main::mp, and main::out.
vectorize() [2/2]
template<typename T > std::vector<T*> topmatching::vectorize (std::map< std::string, T * > * mp) inline
Definition at line 38 of file mc16/topmatching/topmatching.h.
{
             typename std::vector<T*> out = {};
             typename std::map<std::string, T*>::iterator itr = mp -> begin();
             for (; itr != mp -> end(); ++itr){out.push_back(itr -> second);}
             return out;
         }
References end(), main::mp, and main::out.
Referenced by strategy().
Member Data Documentation
jet_leps
std::map<std::string, std::vector<float> > topmatching::jet_leps = {}
Definition at line 27 of file mc20/topmatching/topmatching.h.
jets_truth_leps
std::map<std::string, std::vector<float> > topmatching::jets_truth_leps = {}
Definition at line 26 of file mc20/topmatching/topmatching.h.
n_jets_had
std::map<std::string, std::vector<float> > topmatching::n_jets_had = {}
Definition at line 30 of file mc20/topmatching/topmatching.h.
n_jets_lep
std::map<std::string, std::vector<float> > topmatching::n_jets_lep = {}
Definition at line 29 of file mc20/topmatching/topmatching.h.
n_truth_jets_had
std::map<std::string, std::vector<float> > topmatching::n_truth_jets_had = {}
Definition at line 24 of file mc20/topmatching/topmatching.h.
n_truth_jets_lep
std::map<std::string, std::vector<float> > topmatching::n_truth_jets_lep = {}
Definition at line 23 of file mc20/topmatching/topmatching.h.
no_children
std::vector< int > topmatching::no_children = {}
Definition at line 19 of file mc16/topmatching/topmatching.h.
Referenced by strategy().
topchildren_leptonic
std::vector<int> topmatching::topchildren_leptonic = {}
Definition at line 22 of file mc16/topmatching/topmatching.h.
Referenced by merge().
topchildren_mass
std::vector<float> topmatching::topchildren_mass = {}
Definition at line 21 of file mc16/topmatching/topmatching.h.
Referenced by merge().
topjets_children_leptonic
std::vector<int> topmatching::topjets_children_leptonic = {}
Definition at line 29 of file mc16/topmatching/topmatching.h.
Referenced by merge().
topjets_children_mass
std::vector<float> topmatching::topjets_children_mass = {}
Definition at line 28 of file mc16/topmatching/topmatching.h.
Referenced by merge().
topjets_leptons_leptonic
std::vector<int> topmatching::topjets_leptons_leptonic = {}
Definition at line 32 of file mc16/topmatching/topmatching.h.
Referenced by merge().
topjets_leptons_mass
std::vector<float> topmatching::topjets_leptons_mass = {}
Definition at line 31 of file mc16/topmatching/topmatching.h.
Referenced by merge().
topjets_leptons_njets
std::vector<int> topmatching::topjets_leptons_njets = {}
Definition at line 34 of file mc16/topmatching/topmatching.h.
Referenced by merge().
topjets_leptons_pdgid
std::vector<int> topmatching::topjets_leptons_pdgid = {}
Definition at line 33 of file mc16/topmatching/topmatching.h.
Referenced by merge().
toptruthjets_leptonic
std::vector<int> topmatching::toptruthjets_leptonic = {}
Definition at line 25 of file mc16/topmatching/topmatching.h.
Referenced by merge().
toptruthjets_mass
std::vector<float> topmatching::toptruthjets_mass = {}
Definition at line 24 of file mc16/topmatching/topmatching.h.
Referenced by merge().
toptruthjets_njets
std::vector<int> topmatching::toptruthjets_njets = {}
Definition at line 26 of file mc16/topmatching/topmatching.h.
Referenced by merge().
truth_children
std::map<std::string, std::vector<float> > topmatching::truth_children = {}
Definition at line 20 of file mc20/topmatching/topmatching.h.
truth_jets
std::map<std::string, std::vector<float> > topmatching::truth_jets = {}
Definition at line 21 of file mc20/topmatching/topmatching.h.
truth_top
std::vector< float > topmatching::truth_top = {}
Definition at line 18 of file mc16/topmatching/topmatching.h.
Referenced by merge(), and strategy().
The documentation for this class was generated from the following files:
mc16/topmatching/topmatching.h
mc16/topmatching/topmatching.cxx