AnalysisG: grift Class Reference
grift Class Reference
#include <grift.h>
Public Member Functions
grift ()
~grift ()
model_template * clone () override
Creates a clone of the model template.
void forward (graph_t *) override
Virtual forward pass method for a single graph.
torch::Tensor message (torch::Tensor trk_i, torch::Tensor trk_j, torch::Tensor pmc, torch::Tensor hx_i, torch::Tensor hx_j)
Public Member Functions inherited from model_template
model_template ()
Constructor for the model_template class.
virtual ~model_template ()
Virtual destructor for the model_template class.
void register_module (torch::nn::Sequential *data)
Registers a PyTorch sequential module with the model.
void register_module (torch::nn::Sequential *data, mlp_init method)
Registers a PyTorch sequential module with the model and initializes its weights.
virtual void forward (graph_t *data, bool train)
Forward pass for a single graph with training mode flag.
virtual void forward (std::vector< graph_t * > data, bool train)
Forward pass for multiple graphs with training mode flag.
torch::Tensor * assign_features (std::string inpt, graph_enum type, graph_t *data)
Assigns features from a graph to tensors based on feature name and type.
torch::Tensor * assign_features (std::string inpt, graph_enum type, std::vector< graph_t * > *data)
Assigns features from multiple graphs to tensors based on feature name and type.
void flush_outputs ()
Clears all output tensors, freeing memory.
Public Member Functions inherited from tools
tools ()
Constructor for the tools class.
~tools ()
Destructor for the tools class.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Public Member Functions inherited from notification
notification ()
Constructor for the notification class.
~notification ()
Destructor for the notification class.
void set_prefix (std::string prefix)
Sets the prefix used in log messages from this instance.
std::string get_prefix ()
Returns the prefix currently used in log messages.
void Info (std::string msg, bool newline=true)
Outputs an info message.
void Warning (std::string msg, bool newline=true)
Outputs a warning message.
void Error (std::string msg, bool newline=true)
Outputs an error message.
void Debug (std::string msg, bool newline=true)
Outputs a debug message (only in debug mode).
void Message (std::string msg, std::string tag="", bool newline=true)
Outputs a message with custom formatting.
void set_debug_mode (bool dbg)
Enables or disables debug mode.
bool get_debug_mode ()
Returns the current status of debug mode.
void set_suppress_warning (bool sw)
Sets whether warnings should be suppressed.
bool get_suppress_warning ()
Returns the current warning suppression status.
void set_suppress_info (bool si)
Sets whether info messages should be suppressed.
bool get_suppress_info ()
Returns the current info message suppression status.
Public Attributes
int _hidden = 1024
int _xrec = 128
int _xin = 6
int _xout = 2
int _xtop = 5
double drop_out = 0.01
bool is_mc = true
bool init = false
bool pagerank = true
torch::nn::Sequential * rnn_x = nullptr
torch::nn::Sequential * rnn_dx = nullptr
torch::nn::Sequential * rnn_top_edge = nullptr
torch::nn::Sequential * rnn_res_edge = nullptr
torch::nn::Sequential * rnn_hxx = nullptr
torch::nn::Sequential * mlp_ntop = nullptr
torch::nn::Sequential * mlp_sig = nullptr
torch::Tensor x_nulls
torch::Tensor dx_nulls
torch::Tensor te_nulls
Public Attributes inherited from model_template
cproperty< std::string, model_template > name
Property: The name of this model.
cproperty< std::string, model_template > device
Property: The device this model runs on (e.g., "cpu", "cuda:0").
cproperty< int, model_template > device_index
Property: The numerical index of the device this model runs on.
cproperty< std::vector< std::string >, std::map< std::string, torch::Tensor * > > i_graph
Property: Graph-level input features.
cproperty< std::vector< std::string >, std::map< std::string, torch::Tensor * > > i_node
Property: Node-level input features.
cproperty< std::vector< std::string >, std::map< std::string, torch::Tensor * > > i_edge
Property: Edge-level input features.
cproperty< std::vector< std::string >, std::map< std::string, torch::Tensor * > > o_graph
Property: Graph-level output features.
cproperty< std::vector< std::string >, std::map< std::string, torch::Tensor * > > o_node
Property: Node-level output features.
cproperty< std::vector< std::string >, std::map< std::string, torch::Tensor * > > o_edge
Property: Edge-level output features.
std::map< std::string, torch::Tensor * > m_i_graph
Map of graph-level input features to tensors.
std::map< std::string, torch::Tensor * > m_i_node
Map of node-level input features to tensors.
std::map< std::string, torch::Tensor * > m_i_edge
Map of edge-level input features to tensors.
std::map< std::string, torch::Tensor * > m_o_graph
Map of graph-level output features to tensors.
std::map< std::string, torch::Tensor * > m_o_node
Map of node-level output features to tensors.
std::map< std::string, torch::Tensor * > m_o_edge
Map of edge-level output features to tensors.
torch::TensorOptions * m_option = nullptr
Pointer to tensor options for configuring tensor creation.
std::vector< torch::nn::Sequential * > m_data
Vector of pointers to sequential modules in the model.
lossfx * m_loss = nullptr
Pointer to the loss function manager.
std::string model_checkpoint_path
Path for saving/loading model checkpoints.
Additional Inherited Members
Static Public Member Functions inherited from model_template
static void set_name (std::string *name, model_template *model)
Static setter for the name property.
static void get_name (std::string *name, model_template *model)
Static getter for the name property.
static void set_device (std::string *dev, model_template *model)
Static setter for the device property.
static void set_dev_index (int *dev_idx, model_template *model)
Static setter for the device_index property.
static void get_dev_index (int *dev_idx, model_template *model)
Static getter for the device_index property.
static void set_input_features (std::vector< std::string > *inpt, std::map< std::string, torch::Tensor * > *in_fx)
Sets input features for a specific feature map.
static void set_output_features (std::vector< std::string > *inpt, std::map< std::string, torch::Tensor * > *in_fx)
Sets output features for a specific feature map.
Static Public Member Functions inherited from tools
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Protected Attributes inherited from notification
std::string prefix = ""
Prefix used in log messages from this instance. Initialized as empty string.
bool debug_mode = false
Flag indicating whether debug mode is enabled. Initialized as false.
bool suppress_warnings = false
Flag indicating whether warnings are suppressed. Initialized as false.
bool suppress_info = false
Flag indicating whether info messages are suppressed. Initialized as false.
Detailed Description
Definition at line 5 of file grift.h.
Constructor & Destructor Documentation
grift()
grift::grift ()
Definition at line 4 of file grift.cxx.
             {
     // create the null buffers
     this ->  x_nulls = torch::zeros({1, this -> _xrec}).to(torch::kInt);
     this -> dx_nulls = torch::zeros({1, this -> _xrec}).to(torch::kFloat32);
     this -> te_nulls = torch::zeros({1, this -> _xout}).to(torch::kFloat32);
     this -> rnn_x = new torch::nn::Sequential({
             {"rnn_x_l1", torch::nn::Linear(this -> _xin + this -> _xrec, this -> _hidden)},
             {"rnn_x_n1", torch::nn::LayerNorm(torch::nn::LayerNormOptions({this -> _hidden}))},
             {"rnn_x_l2", torch::nn::Linear(this -> _hidden, this -> _hidden)},
             {"rnn_x_n2", torch::nn::LayerNorm(torch::nn::LayerNormOptions({this -> _hidden}))},
             {"rnn_x_l3", torch::nn::Linear(this -> _hidden, this -> _xrec)}
     });
     int dxx_1 = (this -> _xin + this -> _xrec)*3;
     this -> rnn_dx = new torch::nn::Sequential({
             {"rnn_dx_l1", torch::nn::Linear(dxx_1, this -> _hidden)},
             {"rnn_dx_r1", torch::nn::ReLU()},
             {"rnn_dx_l2", torch::nn::Linear(this -> _hidden, this -> _hidden)},
             {"rnn_dx_s2", torch::nn::Sigmoid()},
             {"rnn_dx_n2", torch::nn::LayerNorm(torch::nn::LayerNormOptions({this -> _hidden}))},
             {"rnn_dx_l3", torch::nn::Linear(this -> _hidden, this -> _xrec)}
     });
     this -> rnn_hxx = new torch::nn::Sequential({
             {"rnn_hxx_l1", torch::nn::Linear(this -> _xrec*4, this -> _hidden)},
             {"rnn_hxx_n1", torch::nn::LayerNorm(torch::nn::LayerNormOptions({this -> _hidden}))},
             {"rnn_hxx_l2", torch::nn::Linear(this -> _hidden, this -> _xrec)}
     });
     this -> rnn_top_edge = new torch::nn::Sequential({
             {"rnn_top_l1", torch::nn::Linear(this -> _xrec*4, this -> _hidden)},
             {"rnn_top_r1", torch::nn::ReLU()},
             {"rnn_top_n1", torch::nn::LayerNorm(torch::nn::LayerNormOptions({this -> _hidden}))},
             {"rnn_top_l2", torch::nn::Linear(this -> _hidden, this -> _hidden)},
             {"rnn_top_t2", torch::nn::Sigmoid()},
             {"rnn_top_l3", torch::nn::Linear(this -> _hidden, this -> _xout)}
     });
     int dxx_r = this -> _xrec*4;
     this -> rnn_res_edge = new torch::nn::Sequential({
             {"rnn_res_l1", torch::nn::Linear(dxx_r, this -> _hidden)},
             {"rnn_res_r1", torch::nn::ReLU()},
             {"rnn_res_n1", torch::nn::LayerNorm(torch::nn::LayerNormOptions({this -> _hidden}))},
             {"rnn_res_l2", torch::nn::Linear(this -> _hidden, this -> _hidden)},
             {"rnn_res_t2", torch::nn::Sigmoid()},
             {"rnn_res_l3", torch::nn::Linear(this -> _hidden, this -> _xout)}
     });
     this -> mlp_ntop = new torch::nn::Sequential({
             {"ntop_l1", torch::nn::Linear(this -> _xtop + this -> _xrec, this -> _xrec)},
             {"ntop_r1", torch::nn::ReLU()},
             {"ntop_n1", torch::nn::LayerNorm(torch::nn::LayerNormOptions({this -> _xrec}))},
             {"ntop_l2", torch::nn::Linear(this -> _xrec, this -> _xrec)},
             {"ntop_t2", torch::nn::Sigmoid()},
             {"ntop_l3", torch::nn::Linear(this -> _xrec, this -> _xtop)}
     });
     this -> mlp_sig = new torch::nn::Sequential({
             {"res_l1", torch::nn::Linear(this -> _xout*2 + dxx_r + this -> _xtop*2, this -> _xrec*2)},
             {"res_r1", torch::nn::ReLU()},
             {"res_n1", torch::nn::LayerNorm(torch::nn::LayerNormOptions({this -> _xrec*2}))},
             {"res_l2", torch::nn::Linear(this -> _xrec*2, this -> _xrec)},
             {"res_t2", torch::nn::Sigmoid()},
             {"res_l3", torch::nn::Linear(this -> _xrec, this -> _xout)}
     });
     this -> register_module(this -> rnn_x       );
     this -> register_module(this -> rnn_dx      );
     this -> register_module(this -> rnn_hxx     );
     this -> register_module(this -> rnn_top_edge);
     this -> register_module(this -> rnn_res_edge);
     this -> register_module(this -> mlp_ntop    );
     this -> register_module(this -> mlp_sig     );
 }
References _hidden, _xin, _xout, _xrec, _xtop, dx_nulls, mlp_ntop, mlp_sig, model_template::register_module(), rnn_dx, rnn_hxx, rnn_res_edge, rnn_top_edge, rnn_x, te_nulls, and x_nulls.
Referenced by clone().
~grift()
grift::~grift ()
Definition at line 298 of file grift.cxx.
 {}
Member Function Documentation
clone()
model_template * grift::clone () override virtual
Creates a clone of the model template.
Creates and returns a clone of this model template.
Returns
A pointer to a new model_template instance that is a copy of this one.
A new model_template instance.
Reimplemented from model_template.
Definition at line 299 of file grift.cxx.
{
     grift* md = new grift();
     md -> drop_out = this -> drop_out;
     md -> is_mc    = this -> is_mc;
     md -> pagerank = this -> pagerank;
     return md;
 }
References drop_out, grift(), is_mc, test_ssml_mc20::md, and pagerank.
Referenced by forward().
forward()
void grift::forward (graph_t * data) override virtual
Virtual forward pass method for a single graph.
Default implementation of the forward pass for a single graph.
Parameters
data Pointer to the graph_t structure containing input data.
This method should be overridden by derived classes to implement the forward pass logic.
Parameters
data Pointer to the graph_t structure containing input data.
This is a placeholder that derived classes should override with their specific implementation.
Reimplemented from model_template.
Definition at line 112 of file grift.cxx.
{
     // get the particle 4-vector and convert it to cartesian
     torch::Tensor batch_index  = data -> get_batch_index(this) -> view({-1}).clone();
     torch::Tensor event_index  = std::get<0>(torch::_unique(batch_index));
     torch::Tensor* pt          = data -> get_data_node("pt", this);
     torch::Tensor* eta         = data -> get_data_node("eta", this);
     torch::Tensor* phi         = data -> get_data_node("phi", this);
     torch::Tensor* energy      = data -> get_data_node("energy", this);
     torch::Tensor* is_lep      = data -> get_data_node("is_lep", this);
     torch::Tensor pmc          = pyc::transform::separate::PxPyPzE(*pt, *eta, *phi, *energy) / 1000.0;
     torch::Tensor edge_index   = data -> get_edge_index(this) -> to(torch::kLong);
     torch::Tensor src          = edge_index.index({0}).view({-1});
     torch::Tensor dst          = edge_index.index({1}).view({-1});
     // the event features
     torch::Tensor* num_jets = data -> get_data_graph("num_jets", this);
     torch::Tensor* num_leps = data -> get_data_graph("num_leps", this);
     torch::Tensor* met_phi  = data -> get_data_graph("phi", this);
     torch::Tensor* met      = data -> get_data_graph("met", this);
     torch::Tensor num_bjet = data -> get_data_node("is_b", this) -> clone();
     torch::Tensor num_bjets_ = torch::zeros({event_index.size({0}), 1}, num_bjet.device()).to(num_bjet.dtype());
     num_bjets_.index_add_({0}, batch_index, num_bjet);
     torch::Tensor pid = torch::cat({*num_jets, num_bjets_, *num_leps, (*met)/1000.0, *met_phi}, {-1});
     // ------ index the nodes from 0 to N-1 ----- //
     if (!this -> init){
         this -> x_nulls = this -> x_nulls.to(src.device());
         this -> dx_nulls = this -> dx_nulls.to(src.device());
         this -> te_nulls = this -> te_nulls.to(src.device());
         this -> init = true;
     }
     // ------ initialize nulls -------- //
     torch::Tensor trk = torch::zeros_like(*pt).to(torch::kInt);
     torch::Tensor null_idx = torch::zeros_like(src);
     torch::Tensor node_rnn = this -> x_nulls.index({trk.view({-1})}).to(torch::kFloat32);
     torch::Tensor edge_rnn = this -> dx_nulls.index({null_idx});
     torch::Tensor top_edge = this -> te_nulls.index({null_idx});
     torch::Tensor num_node = torch::ones_like(trk);
     torch::Tensor node_i   = num_node.cumsum({0})-1;
     torch::Tensor node_i_  = node_i.clone();
     torch::Tensor node_s = torch::cat({pyc::physics::cartesian::combined::M(pmc), pmc, num_node, node_rnn}, {-1});
     node_s = (*this -> rnn_x) -> forward(node_s.to(torch::kFloat32));
     // ------ index the edges from 0 to N^2 -1 ------ //
     unsigned int n_nodes  = data -> num_nodes;
     torch::Tensor idx_mat = torch::zeros({n_nodes, n_nodes}, src.device()).to(torch::kLong);
     idx_mat.index_put_({src, dst}, (null_idx+1).cumsum({-1})-1);
     torch::Tensor norm   = torch::zeros_like(idx_mat);
     norm.index_put_({src, dst}, (null_idx+1));
     torch::Tensor hx_i  = node_s.index({src});
     torch::Tensor hx_j  = node_s.index({dst});
     std::string key_idx = "cls::1::node-indices";
     std::string key_smx = "cls::1::node-sum";
     torch::Dict<std::string, torch::Tensor> gr_;
     torch::Tensor top_edge_   = top_edge.clone();
     torch::Tensor edge_index_ = edge_index.clone();
     while (edge_index_.size({1})){
         torch::Tensor node_state, hx_ij;
         // ----- use the index matrix to map the source and destination edges to the edge index ----- //
         torch::Tensor src_ = edge_index_.index({0});
         torch::Tensor dst_ = edge_index_.index({1});
         // ------------------ loop states ------------------------ //
         // ------------------ create a new message --------------------- //
         hx_i  = this -> message(node_i.index({src_}) , node_i_.index({dst_}), pmc, hx_i, node_s.index({dst_}));
         hx_j  = this -> message(node_i_.index({src_}), node_i.index({dst_}) , pmc, node_s.index({src_}), hx_j);
         hx_ij = this -> message(node_i.index({src_}) , node_i.index({dst_}) , pmc, hx_i, hx_j);
         hx_ij = torch::cat({hx_ij, edge_rnn, hx_i, hx_j + hx_i}, {-1});
         // ------------------ check edges for new paths ---------------- //
         top_edge_ = (*this -> rnn_top_edge) -> forward(hx_ij);
         edge_rnn  = (*this -> rnn_hxx) -> forward(hx_ij);
         // ----- update the top_edge prediction weights by index ------- //
         torch::Tensor idx = idx_mat.index({src_, dst_});
         top_edge.index_put_({idx}, top_edge_);
         torch::Tensor sel = std::get<1>((top_edge_).max({-1}));
         // ---- check if the new prediction is simply null ---- /
         sel = sel < 1;
         if (!sel.index({sel == false}).size({0})){break;}
         node_s  = node_rnn.clone();
         node_i_ = node_i;
         // ----------- create a new intermediate state of the nodes ----------- //
         gr_ = pyc::graph::edge_aggregation(edge_index, top_edge, pmc);
         num_node = (gr_.at(key_idx) > -1).sum({-1}, true);
         torch::Tensor pmx = gr_.at(key_smx);
         node_state = torch::cat({pyc::physics::cartesian::combined::M(pmx), pmx, num_node, node_rnn}, {-1});
         // ------ protection against depleted event graphs ---------- //
         //if (!skp.index({skp}).size({0})){break;}
         torch::Tensor skp = (norm.sum({-1}, true) > 0).view({-1});
         node_state = (*this -> rnn_x) -> forward(node_state.to(torch::kFloat32)) / num_node;
         node_rnn.index_put_({skp}, node_state.index({skp}));
         norm.index_put_({src_, dst_}, sel*1);
         // ------ walk to the next node (nxt) ------- //
         hx_i        = hx_i.index({sel});
         hx_j        = hx_j.index({sel});
         edge_rnn    = edge_rnn.index({sel});
         top_edge_   = top_edge_.index({sel});
         node_i      = gr_.at(key_idx);
         edge_index_ = edge_index_.index({torch::indexing::Slice(), sel});
     }
     // ----------- compress the top data ----------- //
     gr_ = pyc::graph::edge_aggregation(edge_index, top_edge, pmc);
     torch::Tensor node_trk = gr_.at(key_idx);
     num_node = (node_trk > -1).sum({-1}, true);
     torch::Tensor pmx_     = gr_.at(key_smx);
     torch::Tensor top_mass = pyc::physics::cartesian::combined::M(pmx_);
     torch::Tensor enc_tops = torch::cat({top_mass, pmx_, num_node, node_rnn}, {-1});
     torch::Tensor ntops    = (*this -> rnn_x) -> forward(enc_tops.to(torch::kFloat32)) / num_node;
     torch::Tensor tmlp     = torch::zeros({event_index.size({0}), ntops.size({1})}, ntops.device()).to(ntops.dtype());
     tmlp.index_add_({0}, batch_index, ntops);
     tmlp = torch::cat({tmlp, pid}, {-1});
     tmlp = (*this -> mlp_ntop) -> forward(tmlp.to(torch::kFloat32));
     torch::Tensor hxt_i = node_rnn.index({src});
     torch::Tensor hxt_j = node_rnn.index({dst});
     torch::Tensor _trk_j = torch::cat({node_trk.index({src}), node_trk.index({dst})}, {-1});
     torch::Dict<std::string, torch::Tensor> aggr = pyc::graph::unique_aggregation(_trk_j, pmc);
     num_node = (aggr.at("unique") > -1).sum({-1}, true);
     torch::Tensor pmy_     = aggr.at("node-sum");
     torch::Tensor res_mass = pyc::physics::cartesian::combined::M(pmy_);
     torch::Tensor enc_res  = torch::cat({res_mass, pmy_, num_node, hxt_i}, {-1});
     torch::Tensor node_res = (*this -> rnn_x) -> forward(enc_res.to(torch::kFloat32)) / num_node;
     torch::Tensor fx_ij  = torch::cat({node_res, ntops.index({src}), hxt_i, hxt_j - hxt_i}, {-1});
     torch::Tensor res_edge = (*this -> rnn_res_edge) -> forward(fx_ij);
     torch::Tensor isres_ = torch::cat({res_edge, top_edge - res_edge, fx_ij}, {-1});
     torch::Tensor tmp = torch::zeros({event_index.size({0}), isres_.size({1})}, isres_.device()).to(isres_.dtype());
     tmp.index_add_({0}, batch_index.index({src}), isres_);
     isres_ = torch::cat({tmp, pid, tmlp}, {-1});
     isres_ = (*this -> mlp_sig) -> forward(isres_.to(torch::kFloat32));
     this -> prediction_edge_feature("top_edge", top_edge);
     this -> prediction_edge_feature("res_edge", res_edge);
     this -> prediction_graph_feature("ntops" , tmlp);
     this -> prediction_graph_feature("signal", isres_);
     if (!this -> inference_mode){return;}
     if (this -> pagerank){
         gr_ = pyc::graph::PageRankReconstruction(edge_index, top_edge, pmc);
         this -> prediction_extra("page-nodes", gr_.at("page-nodes"));
         this -> prediction_extra("page-mass" , gr_.at("page-mass" ));
     }
     this -> prediction_extra("top_edge_score", top_edge.softmax(-1));
     this -> prediction_extra("res_edge_score", res_edge.softmax(-1));
     this -> prediction_extra("ntops_score"   , tmlp.softmax(-1));
     this -> prediction_extra("is_res_score"  , isres_.softmax(-1));
     this -> prediction_extra("is_lep"        , *is_lep);
     this -> prediction_extra("num_leps"      , *num_leps);
     this -> prediction_extra("num_jets"      , *num_jets);
     this -> prediction_extra("num_bjets"     , num_bjets_);
     if (!this -> is_mc){return;}
     torch::Tensor* ntops_t  = data -> get_truth_graph("ntops"  , this);
     torch::Tensor* signa_t  = data -> get_truth_graph("signal" , this);
     torch::Tensor* r_edge_t = data -> get_truth_edge("res_edge", this);
     torch::Tensor* t_edge_t = data -> get_truth_edge("top_edge", this);
     this -> prediction_extra("truth_ntops"   , *ntops_t);
     this -> prediction_extra("truth_signal"  , *signa_t);
     this -> prediction_extra("truth_res_edge", *r_edge_t);
     this -> prediction_extra("truth_top_edge", *t_edge_t);
 }
References batch_index, clone(), simply_plot::data, edge_index, energy, eta, is_lep, phi, pmc, pt, and pyc::transform::separate::PxPyPzE().
Referenced by message().
message()
torch::Tensor grift::message (torch::Tensor trk_i, torch::Tensor trk_j, torch::Tensor pmc, torch::Tensor hx_i, torch::Tensor hx_j)
Definition at line 83 of file grift.cxx.
  {
     std::string key_idx = "unique";
     std::string key_smx = "node-sum";
     torch::Dict<std::string, torch::Tensor> aggr;
     torch::Tensor trk_ij = torch::cat({_trk_i, _trk_j}, {-1});
     aggr = pyc::graph::unique_aggregation(trk_ij, pmc);
     torch::Tensor pmc_ij = aggr.at(key_smx);
     torch::Tensor m_ij   = pyc::physics::cartesian::combined::M(pmc_ij);
     torch::Tensor nds_ij = (aggr.at(key_idx) > -1).sum({-1}, true);
     torch::Tensor fx_ij  = torch::cat({m_ij, pmc_ij, nds_ij, hx_i+hx_j}, {-1});
     aggr = pyc::graph::unique_aggregation(_trk_i, pmc);
     torch::Tensor pmc_i = aggr.at(key_smx);
     torch::Tensor m_i   = pyc::physics::cartesian::combined::M(pmc_i);
     torch::Tensor nds_i = (aggr.at(key_idx) > -1).sum({-1}, true);
     torch::Tensor fx_i  = torch::cat({m_i, pmc_i, nds_i, hx_i}, {-1});
     aggr = pyc::graph::unique_aggregation(_trk_j, pmc);
     torch::Tensor pmc_j = aggr.at(key_smx);
     torch::Tensor m_j   = pyc::physics::cartesian::combined::M(pmc_j);
     torch::Tensor nds_j = (aggr.at(key_idx) > -1).sum({-1}, true);
     torch::Tensor fx_j  = torch::cat({m_j, pmc_j, nds_j, hx_j}, {-1});
     return (*this -> rnn_dx) -> forward(torch::cat({fx_ij, fx_i, fx_j - fx_i}, {-1}).to(torch::kFloat32));
 }
References forward(), pyc::physics::cartesian::combined::M(), pmc, rnn_dx, tools::sum(), and pyc::graph::unique_aggregation().
Member Data Documentation
_hidden
int grift::_hidden = 1024
Definition at line 19 of file grift.h.
Referenced by grift().
_xin
int grift::_xin = 6
Definition at line 22 of file grift.h.
Referenced by grift().
_xout
int grift::_xout = 2
Definition at line 23 of file grift.h.
Referenced by grift().
_xrec
int grift::_xrec = 128
Definition at line 20 of file grift.h.
Referenced by grift().
_xtop
int grift::_xtop = 5
Definition at line 24 of file grift.h.
Referenced by grift().
drop_out
double grift::drop_out = 0.01
Definition at line 26 of file grift.h.
Referenced by clone().
dx_nulls
torch::Tensor grift::dx_nulls
Definition at line 42 of file grift.h.
Referenced by grift().
init
bool grift::init = false
Definition at line 30 of file grift.h.
is_mc
bool grift::is_mc = true
Definition at line 29 of file grift.h.
Referenced by clone().
mlp_ntop
torch::nn::Sequential* grift::mlp_ntop = nullptr
Definition at line 39 of file grift.h.
Referenced by grift().
mlp_sig
torch::nn::Sequential* grift::mlp_sig = nullptr
Definition at line 40 of file grift.h.
Referenced by grift().
pagerank
bool grift::pagerank = true
Definition at line 31 of file grift.h.
Referenced by clone().
rnn_dx
torch::nn::Sequential* grift::rnn_dx = nullptr
Definition at line 34 of file grift.h.
Referenced by grift(), and message().
rnn_hxx
torch::nn::Sequential* grift::rnn_hxx = nullptr
Definition at line 37 of file grift.h.
Referenced by grift().
rnn_res_edge
torch::nn::Sequential* grift::rnn_res_edge = nullptr
Definition at line 36 of file grift.h.
Referenced by grift().
rnn_top_edge
torch::nn::Sequential* grift::rnn_top_edge = nullptr
Definition at line 35 of file grift.h.
Referenced by grift().
rnn_x
torch::nn::Sequential* grift::rnn_x = nullptr
Definition at line 33 of file grift.h.
Referenced by grift().
te_nulls
torch::Tensor grift::te_nulls
Definition at line 43 of file grift.h.
Referenced by grift().
x_nulls
torch::Tensor grift::x_nulls
Definition at line 41 of file grift.h.
Referenced by grift().
The documentation for this class was generated from the following files:
grift.h
grift.cxx