AnalysisG: particle_template Class Reference
particle_template Class Reference
#include <particle_template.h>
Public Member Functions
particle_template ()
virtual ~particle_template ()
particle_template (particle_t *p)
particle_template (particle_template *p, bool dump=false)
particle_template (double px, double py, double pz, double e)
particle_template (double px, double py, double pz)
void to_cartesian ()
void to_polar ()
bool is (std::vector< int > p)
double DeltaR (particle_template *p)
bool operator== (particle_template &p)
template<typename g >
g operator+ (g &p)
void operator+= (particle_template *p)
void iadd (particle_template *p)
bool register_parent (particle_template *p)
bool register_child (particle_template *p)
void add_leaf (std::string key, std::string leaf="")
void apply_type_prefix ()
std::map< std::string, std::map< std::string, particle_t > > __reduce__ ()
virtual void build (std::map< std::string, particle_template * > *event, element_t *el)
virtual particle_template * clone ()
Public Member Functions inherited from tools
tools ()
Constructor for the tools class.
~tools ()
Destructor for the tools class.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Static Public Member Functions
static void set_e (double *, particle_template *)
static void get_e (double *, particle_template *)
static void set_mass (double *, particle_template *)
static void get_mass (double *, particle_template *)
static void set_pt (double *, particle_template *)
static void get_pt (double *, particle_template *)
static void set_eta (double *, particle_template *)
static void get_eta (double *, particle_template *)
static void set_phi (double *, particle_template *)
static void get_phi (double *, particle_template *)
static void set_px (double *, particle_template *)
static void get_px (double *, particle_template *)
static void set_py (double *, particle_template *)
static void get_py (double *, particle_template *)
static void set_pz (double *, particle_template *)
static void get_pz (double *, particle_template *)
static void set_pdgid (int *, particle_template *)
static void get_pdgid (int *, particle_template *)
static void set_symbol (std::string *, particle_template *)
static void get_symbol (std::string *, particle_template *)
static void set_charge (double *, particle_template *)
static void get_charge (double *, particle_template *)
static void get_hash (std::string *, particle_template *)
static void get_isb (bool *, particle_template *)
static void get_islep (bool *, particle_template *)
static void get_isnu (bool *, particle_template *)
static void get_isadd (bool *, particle_template *)
static void get_lepdecay (bool *, particle_template *)
static void set_parents (std::map< std::string, particle_template * > *, particle_template *)
static void get_parents (std::map< std::string, particle_template * > *, particle_template *)
static void set_children (std::map< std::string, particle_template * > *, particle_template *)
static void get_children (std::map< std::string, particle_template * > *, particle_template *)
static void set_type (std::string *, particle_template *)
static void get_type (std::string *, particle_template *)
static void set_index (int *, particle_template *)
static void get_index (int *, particle_template *)
Static Public Member Functions inherited from tools
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Public Attributes
cproperty< double, particle_template > e
cproperty< double, particle_template > mass
cproperty< double, particle_template > pt
cproperty< double, particle_template > eta
cproperty< double, particle_template > phi
cproperty< double, particle_template > px
cproperty< double, particle_template > py
cproperty< double, particle_template > pz
cproperty< int, particle_template > pdgid
cproperty< std::string, particle_template > symbol
cproperty< double, particle_template > charge
cproperty< std::string, particle_template > hash
cproperty< bool, particle_template > is_b
cproperty< bool, particle_template > is_lep
cproperty< bool, particle_template > is_nu
cproperty< bool, particle_template > is_add
cproperty< bool, particle_template > lep_decay
cproperty< std::map< std::string, particle_template * >, particle_template > parents
cproperty< std::map< std::string, particle_template * >, particle_template > children
cproperty< std::string, particle_template > type
cproperty< int, particle_template > index
std::map< std::string, particle_template * > m_parents
std::map< std::string, particle_template * > m_children
std::map< std::string, std::string > leaves = {}
particle_t data
bool _is_serial = false
bool _is_marked = false
Detailed Description
Definition at line 18 of file particle_template.h.
Constructor & Destructor Documentation
particle_template() [1/5]
particle_template::particle_template ()
Definition at line 3 of file particle_template.cxx.
{
     this -> e.set_setter(this -> set_e);
     this -> e.set_getter(this -> get_e);
     this -> e.set_object(this);
     this -> mass.set_setter(this -> set_mass);
     this -> mass.set_getter(this -> get_mass);
     this -> mass.set_object(this);
     this -> pt.set_setter(this -> set_pt);
     this -> pt.set_getter(this -> get_pt);
     this -> pt.set_object(this);
     this -> eta.set_setter(this -> set_eta);
     this -> eta.set_getter(this -> get_eta);
     this -> eta.set_object(this);
     this -> phi.set_setter(this -> set_phi);
     this -> phi.set_getter(this -> get_phi);
     this -> phi.set_object(this);
     this -> px.set_setter(this -> set_px);
     this -> px.set_getter(this -> get_px);
     this -> px.set_object(this);
     this -> py.set_setter(this -> set_py);
     this -> py.set_getter(this -> get_py);
     this -> py.set_object(this);
     this -> pz.set_setter(this -> set_pz);
     this -> pz.set_getter(this -> get_pz);
     this -> pz.set_object(this);
     this -> pdgid.set_setter(this -> set_pdgid);
     this -> pdgid.set_getter(this -> get_pdgid);
     this -> pdgid.set_object(this);
     this -> symbol.set_setter(this -> set_symbol);
     this -> symbol.set_getter(this -> get_symbol);
     this -> symbol.set_object(this);
     this -> charge.set_setter(this -> set_charge);
     this -> charge.set_getter(this -> get_charge);
     this -> charge.set_object(this);
     this -> hash.set_getter(this -> get_hash);
     this -> hash.set_object(this);
     this -> is_b.set_getter(this -> get_isb);
     this -> is_b.set_object(this);
     this -> is_lep.set_getter(this -> get_islep);
     this -> is_lep.set_object(this);
     this -> is_nu.set_getter(this -> get_isnu);
     this -> is_nu.set_object(this);
     this -> is_add.set_getter(this -> get_isadd);
     this -> is_add.set_object(this);
     this -> lep_decay.set_getter(this -> get_lepdecay);
     this -> lep_decay.set_object(this);
     this -> parents.set_setter(this -> set_parents);
     this -> parents.set_getter(this -> get_parents);
     this -> parents.set_object(this);
     this -> children.set_setter(this -> set_children);
     this -> children.set_getter(this -> get_children);
     this -> children.set_object(this);
     this -> type.set_setter(this -> set_type);
     this -> type.set_getter(this -> get_type);
     this -> type.set_object(this);
     this -> index.set_setter(this -> set_index);
     this -> index.set_getter(this -> get_index);
     this -> index.set_object(this);
 }
References charge, children, e, eta, get_charge(), get_children(), get_e(), get_eta(), get_hash(), get_index(), get_isadd(), get_isb(), get_islep(), get_isnu(), get_lepdecay(), get_mass(), get_parents(), get_pdgid(), get_phi(), get_pt(), get_px(), get_py(), get_pz(), get_symbol(), get_type(), hash, index, is_add, is_b, is_lep, is_nu, lep_decay, mass, parents, pdgid, phi, pt, px, py, pz, set_charge(), set_children(), set_e(), set_eta(), cproperty< T, G >::set_getter(), set_index(), set_mass(), cproperty< T, G >::set_object(), set_parents(), set_pdgid(), set_phi(), set_pt(), set_px(), set_py(), set_pz(), cproperty< T, G >::set_setter(), set_symbol(), set_type(), symbol, and type.
Referenced by __reduce__(), clone(), and particle_template().
~particle_template()
particle_template::~particle_template () virtual
Definition at line 159 of file particle_template.cxx.
{
     if (!this -> data.data_p){return;}
     std::string hash_ = this -> hash;
     (*this -> data.data_p)[hash_] = nullptr;
     std::map<std::string, particle_template*>::iterator itr = this -> data.data_p -> begin();
     for (; itr != this -> data.data_p -> end(); ++itr){
         if (!itr -> second){continue;}
         delete itr -> second;
         itr -> second = nullptr;
     }
     this -> data.data_p -> clear();
     delete this -> data.data_p;
 }
References data, particle_t::data_p, end(), and hash.
particle_template() [2/5]
particle_template::particle_template (particle_t * p) explicit
Definition at line 83 of file particle_template.cxx.
 : particle_template(){this -> data = *p;}
References data, and rnn_model::p.
particle_template() [3/5]
particle_template::particle_template (particle_template * p, bool dump = false) explicit
Definition at line 85 of file particle_template.cxx.
                                                                     : particle_template(){
     if (!p){return;}
     this -> data = p -> data;
     this -> data.children.clear();
     this -> data.parents.clear();
     if (!dump){return;}
     p -> data.data_p = nullptr;
     bool init = (!this -> data.data_p);
     std::map<std::string, particle_template*>* tr = nullptr;
     if (init){tr = new std::map<std::string, particle_template*>();}
     else {tr = this -> data.data_p;}
     (*tr)[this -> hash] = this;
     this -> _is_serial = p -> _is_serial;
     std::map<std::string, particle_template*> ch_ = p -> children;
     std::map<std::string, particle_template*> pr_ = p -> parents;
     std::map<std::string, particle_template*>::iterator itr;
     for (itr = ch_.begin(); itr != ch_.end(); ++itr){
         itr -> second -> data.data_p = tr;
         if (!tr -> count(itr -> first)){(*tr)[itr -> first] = new particle_template(itr -> second, true);}
         itr -> second -> data.data_p = nullptr;
         particle_template* pr = (*tr)[itr -> first];
         this -> register_child(pr);
         pr -> data.data_p = nullptr;
         itr -> second -> _is_serial += p -> _is_serial;
         pr -> _is_serial = itr -> second -> _is_serial;
     }
     for (itr = pr_.begin(); itr != pr_.end(); ++itr){
         itr -> second -> data.data_p = tr;
         if (!tr -> count(itr -> first)){(*tr)[itr -> first] = new particle_template(itr -> second, true);}
         itr -> second -> data.data_p = nullptr;
         particle_template* pr = (*tr)[itr -> first];
         this -> register_parent(pr);
         pr -> data.data_p = nullptr;
         itr -> second -> _is_serial += p -> _is_serial;
         pr -> _is_serial = itr -> second -> _is_serial;
     }
     if (init){this -> data.data_p = tr;}
     else {this -> data.data_p = nullptr;}
 }
References _is_serial, particle_t::children, children, count(), data, particle_t::data_p, hash, rnn_model::p, particle_t::parents, parents, particle_template(), register_child(), and register_parent().
particle_template() [4/5]
particle_template::particle_template (double px, double py, double pz, double e) explicit
Definition at line 147 of file particle_template.cxx.
                                                                               : particle_template(){
     particle_t* p = &this -> data;
     p -> px = px; p -> py = py; p -> pz = pz; p -> e = e;
     p -> polar = true;
 }
References data, e, rnn_model::p, px, py, and pz.
particle_template() [5/5]
particle_template::particle_template (double px, double py, double pz) explicit
Definition at line 153 of file particle_template.cxx.
                                                                     : particle_template() {
     particle_t* p = &this -> data;
     p -> px = px; p -> py = py; p -> pz = pz; p -> e = this -> e;
     p -> polar = true;
 }
References data, e, rnn_model::p, px, py, and pz.
Member Function Documentation
__reduce__()
std::map< std::string, std::map< std::string, particle_t > > particle_template::__reduce__ ()
Definition at line 131 of file particle_template.cxx.
{
     std::map<std::string, particle_template*>* tmp = this -> data.data_p;
     this -> data.data_p = nullptr;
     particle_template* t = new particle_template(this, true);
     std::map<std::string, std::map<std::string, particle_t>> out;
     std::map<std::string, particle_template*>::iterator itr = t -> data.data_p -> begin();
     for (; itr != t -> data.data_p -> end(); ++itr){
         if (itr -> second -> _is_serial){continue;}
         out[itr -> first]["data"] = itr -> second -> data;
     }
     delete t;
     this -> data.data_p = tmp;
     return out;
 }
References _is_serial, data, particle_t::data_p, end(), main::out, particle_template(), test_experimental_mc20::t, and main::tmp.
add_leaf()
void particle_template::add_leaf (std::string key, std::string leaf = "")
Definition at line 99 of file interfaces.cxx.
{
     if (!leaf.size()){leaf = key;}
     this -> leaves[key] = leaf;
 }
References leaves.
Referenced by child::child(), electron::electron(), jet::jet(), jetparton::jetparton(), lepton::lepton(), muon::muon(), particle_gnn::particle_gnn(), parton::parton(), physics_detector::physics_detector(), physics_truth::physics_truth(), top::top(), top_children::top_children(), truthjet::truthjet(), truthjetparton::truthjetparton(), and zboson::zboson().
apply_type_prefix()
void particle_template::apply_type_prefix ()
Definition at line 191 of file particle_template.cxx.
{
     std::map<std::string, std::string> lf = {};
     std::map<std::string, std::string>::iterator itr = this -> leaves.begin();
     for (; itr != this -> leaves.end(); ++itr){lf[itr -> first] = this -> type + itr -> second;}
     this -> leaves = lf;
 }
References leaves, and type.
Referenced by child::child(), electron::electron(), jet::jet(), jetparton::jetparton(), lepton::lepton(), muon::muon(), physics_detector::physics_detector(), physics_truth::physics_truth(), top::top(), top_children::top_children(), truthjet::truthjet(), truthjetparton::truthjetparton(), and zboson::zboson().
build()
void particle_template::build (std::map< std::string, particle_template * > * event, element_t * el) virtual
Reimplemented in muon, electron, jetparton, lepton, parton, jet, muon, jet, electron, truthjetparton, muon, jet, truthjet, electron, truthjet, top_children, physics_truth, top, physics_detector, top, zboson, child, top, and particle_gnn.
Definition at line 199 of file particle_template.cxx.
{
     return;
 }
clone()
particle_template * particle_template::clone () virtual
Reimplemented in muon, electron, jetparton, lepton, parton, jet, muon, jet, electron, truthjetparton, muon, jet, truthjet, electron, truthjet, top_children, physics_truth, top, physics_detector, top, zboson, child, top, particle_gnn, parton, zprime, and zprime.
Definition at line 203 of file particle_template.cxx.
 {return new particle_template();}
References particle_template().
DeltaR()
double particle_template::DeltaR (particle_template * p)
Definition at line 3 of file modules/particle/cxx/physics.cxx.
{
     double sum = std::fabs( this -> phi - part -> phi);
     sum = std::fmod(sum, 2*M_PI);
     sum = M_PI - std::fabs(sum - M_PI);
     sum = std::pow(sum, 2);
     sum += std::pow(this -> eta - part -> eta, 2);
     return std::pow(sum, 0.5);
 }
References eta, phi, and tools::sum().
get_charge()
void particle_template::get_charge (double * val, particle_template * prt) static
Definition at line 57 of file interfaces.cxx.
{
     *val = prt -> data.charge;
 }
References particle_t::charge, and data.
Referenced by particle_template().
get_children()
void particle_template::get_children (std::map< std::string, particle_template * > * val, particle_template * prt) static
Definition at line 128 of file interfaces.cxx.
{
     std::map<std::string, particle_template*>::iterator itr = prt -> m_children.begin();
     for (; itr != prt -> m_children.end(); ++itr){
         if (val -> count(itr -> second -> hash)){continue;}
         (*val)[itr -> second -> hash] = itr -> second;
     }
 }
References count(), hash, and m_children.
Referenced by particle_template().
get_e()
void particle_template::get_e (double * v, particle_template * prt) static
Definition at line 12 of file modules/particle/cxx/physics.cxx.
{
     particle_t* p = &prt -> data;
     if (p -> e >= 0){*v = p -> e; return;}
     p -> e += std::pow(prt -> px, 2);
     p -> e += std::pow(prt -> py, 2);
     p -> e += std::pow(prt -> pz, 2);
     if (p -> mass >= 0){p -> e += p -> mass;}
     p -> e  = std::pow(p -> e, 0.5);
     *v = p -> e;
 }
References data, e, mass, rnn_model::p, px, py, and pz.
Referenced by particle_template().
get_eta()
void particle_template::get_eta (double * val, particle_template * prt) static
Definition at line 19 of file polar.cxx.
{
     prt -> to_polar();
     *val = prt -> data.eta;
 }
References data, particle_t::eta, and to_polar().
Referenced by particle_template().
get_hash()
void particle_template::get_hash (std::string * val, particle_template * prt) static
Definition at line 152 of file interfaces.cxx.
{
     particle_t* p = &prt -> data;
     if ((p -> hash).size()){*val = p -> hash; return; }
     prt -> to_cartesian();
     p -> hash  = prt -> to_string(prt -> px);
     p -> hash += prt -> to_string(prt -> py);
     p -> hash += prt -> to_string(prt -> pz);
     p -> hash += prt -> to_string(prt -> e);
     p -> hash  = prt -> tools::hash(p -> hash);
     *val = p -> hash;
 }
References data, e, hash, rnn_model::p, px, py, pz, to_cartesian(), and tools::to_string().
Referenced by particle_template().
get_index()
void particle_template::get_index (int * val, particle_template * prt) static
Definition at line 177 of file interfaces.cxx.
{
     *val = prt -> data.index;
 }
References data, and particle_t::index.
Referenced by particle_template().
get_isadd()
void particle_template::get_isadd (bool * val, particle_template * prt) static
Definition at line 73 of file interfaces.cxx.
{
     *val = !(prt -> is_lep || prt -> is_nu || prt -> is_b);
 }
References is_b, is_lep, and is_nu.
Referenced by particle_template().
get_isb()
void particle_template::get_isb (bool * val, particle_template * prt) static
Definition at line 61 of file interfaces.cxx.
{
     *val = prt -> is({5});
 }
References is().
Referenced by particle_template().
get_islep()
void particle_template::get_islep (bool * val, particle_template * prt) static
Definition at line 69 of file interfaces.cxx.
{
     *val = prt -> is(prt -> data.lepdef);
 }
References data, is(), and particle_t::lepdef.
Referenced by particle_template().
get_isnu()
void particle_template::get_isnu (bool * val, particle_template * prt) static
Definition at line 65 of file interfaces.cxx.
{
     *val = prt -> is(prt -> data.nudef);
 }
References data, is(), and particle_t::nudef.
Referenced by particle_template().
get_lepdecay()
void particle_template::get_lepdecay (bool * val, particle_template * prt) static
Definition at line 86 of file interfaces.cxx.
{
     bool nu  = false;
     bool lep = false;
     std::map<std::string, particle_template*> tmp = prt -> children;
     std::map<std::string, particle_template*>::iterator itr = tmp.begin();
     for (; itr != tmp.end(); ++itr){
         if (!nu) { nu  = itr -> second -> is_nu;}
         if (!lep){ lep = itr -> second -> is_lep;}
     }
     if (lep && nu){ *val = true; return;}
     *val = false;
 }
References children, is_lep, is_nu, and main::tmp.
Referenced by particle_template().
get_mass()
void particle_template::get_mass (double * val, particle_template * prt) static
Definition at line 31 of file modules/particle/cxx/physics.cxx.
{
     particle_t* p = &prt -> data;
     if (p -> mass > -1){ *val = p -> mass; return; }
     p -> mass = 0;
     p -> mass -= std::pow(prt -> px, 2);
     p -> mass -= std::pow(prt -> py, 2);
     p -> mass -= std::pow(prt -> pz, 2);
     p -> mass += std::pow(prt -> e , 2);
     p -> mass = (p -> mass >= 0) ? std::pow(p -> mass, 0.5) : -1;
     *val = p -> mass;
 }
References data, e, mass, rnn_model::p, px, py, and pz.
Referenced by particle_template().
get_parents()
void particle_template::get_parents (std::map< std::string, particle_template * > * val, particle_template * prt) static
Definition at line 112 of file interfaces.cxx.
{
     std::map<std::string, particle_template*>::iterator itr = prt -> m_parents.begin();
     for (; itr != prt -> m_parents.end(); ++itr){
         if (val -> count(itr -> second -> hash)){continue;}
         (*val)[itr -> second -> hash] = itr -> second;
     }
 }
References count(), hash, and m_parents.
Referenced by particle_template().
get_pdgid()
void particle_template::get_pdgid (int * val, particle_template * prt) static
Definition at line 7 of file interfaces.cxx.
{
     particle_t* p = &prt -> data;
     if (p -> pdgid != 0){ *val = p -> pdgid; return; }
     if (p -> symbol.size() == 0){ *val = p -> pdgid; return; }
     std::map<int, std::string> sym = {
              {1, "d"}, {2, "u"}, {3, "s"},
              {4, "c"}, {5, "b"}, {6, "t"},
              {11, "e"}, {12, "$\\nu_{e}$"},
              {13, "$\\mu$"}, {14, "$\\nu_{\\mu}$"},
              {15, "$\\tau$"}, {16, "$\\nu_{\\tau}$"},
              {21, "g"}, {22, "$\\gamma$"}
     };
     std::map<int, std::string>::iterator it = sym.begin();
     for (; it != sym.end(); ++it){
         if (it -> second != p -> symbol){continue;}
         p -> pdgid = it -> first;
         *val = p -> pdgid;
         return;
     }
     *val = p -> pdgid;
 }
References data, rnn_model::p, pdgid, and symbol.
Referenced by particle_template().
get_phi()
void particle_template::get_phi (double * val, particle_template * prt) static
Definition at line 30 of file polar.cxx.
{
     prt -> to_polar();
     *val = prt -> data.phi;
 }
References data, particle_t::phi, and to_polar().
Referenced by particle_template().
get_pt()
void particle_template::get_pt (double * val, particle_template * prt) static
Definition at line 8 of file polar.cxx.
{
     prt -> to_polar();
     *val = prt -> data.pt;
 }
References data, particle_t::pt, and to_polar().
Referenced by particle_template().
get_px()
void particle_template::get_px (double * val, particle_template * prt) static
Definition at line 8 of file cartesian.cxx.
{
     prt -> to_cartesian();
     *val = prt -> data.px;
 }
References data, particle_t::px, and to_cartesian().
Referenced by particle_template().
get_py()
void particle_template::get_py (double * val, particle_template * prt) static
Definition at line 18 of file cartesian.cxx.
{
     prt -> to_cartesian();
     *val = prt -> data.py;
 }
References data, particle_t::py, and to_cartesian().
Referenced by particle_template().
get_pz()
void particle_template::get_pz (double * val, particle_template * prt) static
Definition at line 28 of file cartesian.cxx.
{
     prt -> to_cartesian();
     *val = prt -> data.pz;
 }
References data, particle_t::pz, and to_cartesian().
Referenced by particle_template().
get_symbol()
void particle_template::get_symbol (std::string * val, particle_template * prt) static
Definition at line 35 of file interfaces.cxx.
{
     particle_t* p = &prt -> data;
     if ((p -> symbol).size() != 0){*val = p -> symbol; return; }
     std::map<int, std::string> sym = {
              {1, "d"}, {2, "u"}, {3, "s"},
              {4, "c"}, {5, "b"}, {6, "t"},
              {11, "e"}, {12, "$\\nu_{e}$"},
              {13, "$\\mu$"}, {14, "$\\nu_{\\mu}$"},
              {15, "$\\tau$"}, {16, "$\\nu_{\\tau}$"},
              {21, "g"}, {22, "$\\gamma$"}
     };
     std::stringstream ss;
     ss << sym[std::abs(p -> pdgid)];
     *val = ss.str();
 }
References data, rnn_model::p, pdgid, and symbol.
Referenced by particle_template().
get_type()
void particle_template::get_type (std::string * val, particle_template * prt) static
Definition at line 169 of file interfaces.cxx.
{
     *val = prt -> data.type;
 }
References data, and particle_t::type.
Referenced by particle_template().
iadd()
void particle_template::iadd (particle_template * p)
Definition at line 183 of file particle_template.cxx.
{
     *this += p;
 }
References rnn_model::p.
is()
bool particle_template::is (std::vector< int > p)
Definition at line 78 of file interfaces.cxx.
{
     for (int& i : p){
         if (std::abs(i) != std::abs(this -> data.pdgid)){continue;}
         return true;
     }
     return false;
 }
References data, i, rnn_model::p, and particle_t::pdgid.
Referenced by get_isb(), get_islep(), and get_isnu().
operator+()
template<typename g > g particle_template::operator+ (g & p) inline
Definition at line 117 of file particle_template.h.
{
             g p2 = g();
             p2.data.px = double(p.px) + double(this -> px);
             p2.data.py = double(p.py) + double(this -> py);
             p2.data.pz = double(p.pz) + double(this -> pz);
             p2.data.e  = double(p.e ) + double(this -> e);
             p2.data.type = this -> data.type;
             p2.data.polar = true;
             return p2;
         }
References data, e, rnn_model::p, px, py, pz, and particle_t::type.
operator+=()
void particle_template::operator+= (particle_template * p)
Definition at line 173 of file particle_template.cxx.
{
     p -> to_cartesian();
     this -> to_cartesian();
     this -> data.px += double(p -> px);
     this -> data.py += double(p -> py);
     this -> data.pz += double(p -> pz);
     this -> data.e  += double(p -> e);
     this -> data.polar = true;
 }
References data, particle_t::e, e, rnn_model::p, particle_t::polar, particle_t::px, px, particle_t::py, py, particle_t::pz, pz, and to_cartesian().
operator==()
bool particle_template::operator== (particle_template & p)
Definition at line 187 of file particle_template.cxx.
{
     return this -> hash == p.hash;
 }
References hash, and rnn_model::p.
register_child()
bool particle_template::register_child (particle_template * p)
Definition at line 136 of file interfaces.cxx.
{
     std::string hash = p -> hash;
     if (this -> data.children[hash]){return false;}
     this -> m_children[hash] = p;
     this -> data.children[hash] = true;
     return true;
 }
References particle_t::children, data, hash, m_children, and rnn_model::p.
Referenced by particle_template(), and set_children().
register_parent()
bool particle_template::register_parent (particle_template * p)
Definition at line 144 of file interfaces.cxx.
{
     std::string hash = p -> hash;
     if (this -> data.parents[hash]){return true;}
     this -> m_parents[hash] = p;
     this -> data.parents[hash] = true;
     return true;
 }
References data, hash, m_parents, rnn_model::p, and particle_t::parents.
Referenced by particle_template(), and set_parents().
set_charge()
void particle_template::set_charge (double * val, particle_template * prt) static
Definition at line 53 of file interfaces.cxx.
{
     prt -> data.charge = *val;
 }
References particle_t::charge, and data.
Referenced by particle_template().
set_children()
void particle_template::set_children (std::map< std::string, particle_template * > * val, particle_template * prt) static
Definition at line 120 of file interfaces.cxx.
{
     std::map<std::string, particle_template*>::iterator itr = val -> begin();
     for (; itr != val -> end(); ++itr){prt -> register_child(itr -> second);}
     if (val -> size()){return;}
     prt -> data.children = {};
     prt -> m_children = {};
 }
References particle_t::children, data, end(), m_children, and register_child().
Referenced by particle_template().
set_e()
void particle_template::set_e (double * val, particle_template * prt) static
Definition at line 23 of file modules/particle/cxx/physics.cxx.
{
     prt -> data.e = *val;
 }
References data, and particle_t::e.
Referenced by particle_template().
set_eta()
void particle_template::set_eta (double * val, particle_template * prt) static
Definition at line 14 of file polar.cxx.
{
     prt -> data.eta = *val;
     prt -> data.cartesian = true;
 }
References particle_t::cartesian, data, and particle_t::eta.
Referenced by particle_template().
set_index()
void particle_template::set_index (int * val, particle_template * prt) static
Definition at line 173 of file interfaces.cxx.
{
     prt -> data.index = *val;
 }
References data, and particle_t::index.
Referenced by particle_template().
set_mass()
void particle_template::set_mass (double * val, particle_template * prt) static
Definition at line 27 of file modules/particle/cxx/physics.cxx.
{
     prt -> data.mass = *val;
 }
References data, and particle_t::mass.
Referenced by particle_template().
set_parents()
void particle_template::set_parents (std::map< std::string, particle_template * > * val, particle_template * prt) static
Definition at line 104 of file interfaces.cxx.
{
     std::map<std::string, particle_template*>::iterator itr = val -> begin();
     for (; itr != val -> end(); ++itr){prt -> register_parent(itr -> second);}
     if (val -> size()){return;}
     prt -> data.parents = {};
     prt -> m_parents = {};
 }
References data, end(), m_parents, particle_t::parents, and register_parent().
Referenced by particle_template().
set_pdgid()
void particle_template::set_pdgid (int * val, particle_template * prt) static
Definition at line 3 of file interfaces.cxx.
{
     prt -> data.pdgid = *val;
 }
References data, and particle_t::pdgid.
Referenced by particle_template().
set_phi()
void particle_template::set_phi (double * val, particle_template * prt) static
Definition at line 24 of file polar.cxx.
{
     prt -> data.phi = *val;
     prt -> data.cartesian = true;
 }
References particle_t::cartesian, data, and particle_t::phi.
Referenced by particle_template().
set_pt()
void particle_template::set_pt (double * val, particle_template * prt) static
Definition at line 3 of file polar.cxx.
{
     prt -> data.pt = *val;
     prt -> data.cartesian = true;
 }
References particle_t::cartesian, data, and particle_t::pt.
Referenced by particle_template().
set_px()
void particle_template::set_px (double * val, particle_template * prt) static
Definition at line 3 of file cartesian.cxx.
{
     prt -> data.px = *val;
     prt -> data.polar = true;
 }
References data, particle_t::polar, and particle_t::px.
Referenced by particle_template().
set_py()
void particle_template::set_py (double * val, particle_template * prt) static
Definition at line 13 of file cartesian.cxx.
{
     prt -> data.py = *val;
     prt -> data.polar = true;
 }
References data, particle_t::polar, and particle_t::py.
Referenced by particle_template().
set_pz()
void particle_template::set_pz (double * val, particle_template * prt) static
Definition at line 23 of file cartesian.cxx.
{
     prt -> data.pz = *val;
     prt -> data.polar = true;
 }
References data, particle_t::polar, and particle_t::pz.
Referenced by particle_template().
set_symbol()
void particle_template::set_symbol (std::string * val, particle_template * prt) static
Definition at line 31 of file interfaces.cxx.
{
     prt -> data.symbol = *val;
 }
References data, and particle_t::symbol.
Referenced by particle_template().
set_type()
void particle_template::set_type (std::string * val, particle_template * prt) static
Definition at line 165 of file interfaces.cxx.
{
     prt -> data.type = *val;
 }
References data, and particle_t::type.
Referenced by particle_template().
to_cartesian()
void particle_template::to_cartesian ()
Definition at line 33 of file cartesian.cxx.
{
     particle_t* p = &this -> data;
     if (!p -> cartesian){ return; }
     p -> px = (p -> pt)*std::cos(p -> phi);
     p -> py = (p -> pt)*std::sin(p -> phi);
     p -> pz = (p -> pt)*std::sinh(p -> eta);
     p -> cartesian = false;
 }
References data, eta, rnn_model::p, phi, pt, px, py, and pz.
Referenced by get_hash(), get_px(), get_py(), get_pz(), and operator+=().
to_polar()
void particle_template::to_polar ()
Definition at line 35 of file polar.cxx.
{
     particle_t* p = &this -> data;
     if (!p -> polar){ return; }
     // Transverse Momenta
     p -> pt  = std::pow(p -> px, 2);
     p -> pt += std::pow(p -> py, 2);
     p -> pt  = std::pow(p -> pt, 0.5);
     // Rapidity
     p -> eta = std::asinh(p -> pz / p -> pt);
     p -> phi = std::atan2(p -> py, p -> px);
     p -> polar = false;
 }
References data, eta, rnn_model::p, phi, pt, px, py, and pz.
Referenced by get_eta(), get_phi(), and get_pt().
Member Data Documentation
_is_marked
bool particle_template::_is_marked = false
Definition at line 148 of file particle_template.h.
_is_serial
bool particle_template::_is_serial = false
Definition at line 147 of file particle_template.h.
Referenced by __reduce__(), and particle_template().
charge
cproperty<double, particle_template> particle_template::charge
Definition at line 73 of file particle_template.h.
Referenced by child::build(), physics_detector::build(), top_children::build(), physics_truth::build(), truthjetparton::build(), lepton::build(), jetparton::build(), electron::build(), muon::build(), and particle_template().
children
cproperty<std::map<std::string, particle_template*>, particle_template> particle_template::children
Definition at line 100 of file particle_template.h.
Referenced by get_lepdecay(), particle_template(), zprime::strategy(), and parton::strategy().
data
particle_t particle_template::data
Definition at line 145 of file particle_template.h.
Referenced by __reduce__(), get_charge(), get_e(), get_eta(), get_hash(), get_index(), get_islep(), get_isnu(), get_mass(), get_pdgid(), get_phi(), get_pt(), get_px(), get_py(), get_pz(), get_symbol(), get_type(), simply_plot.DataX::hist(), is(), simply_plot.DataX::num_events(), operator+(), operator+=(), particle_template(), register_child(), register_parent(), set_charge(), set_children(), set_e(), set_eta(), set_index(), set_mass(), set_parents(), set_pdgid(), set_phi(), set_pt(), set_px(), set_py(), set_pz(), set_symbol(), set_type(), to_cartesian(), to_polar(), and ~particle_template().
e
cproperty<double, particle_template> particle_template::e
Definition at line 32 of file particle_template.h.
Referenced by particle_gnn::build(), top_children::build(), truthjetparton::build(), jet::build(), lepton::build(), jetparton::build(), electron::build(), muon::build(), get_e(), get_hash(), get_mass(), operator+(), operator+=(), particle_template(), parton::strategy(), and parton::top_mass_contribution().
eta
cproperty<double, particle_template> particle_template::eta
Definition at line 44 of file particle_template.h.
Referenced by assign_vector(), particle_gnn::build(), zboson::build(), top_children::build(), truthjetparton::build(), jet::build(), parton::build(), lepton::build(), jetparton::build(), electron::build(), muon::build(), DeltaR(), particle_template(), to_cartesian(), and to_polar().
hash
cproperty<std::string, particle_template> particle_template::hash
Definition at line 77 of file particle_template.h.
Referenced by particle_gnn::build(), child::build(), top::build(), zboson::build(), physics_detector::build(), top_children::build(), physics_truth::build(), truthjet::build(), truthjetparton::build(), jet::build(), parton::build(), lepton::build(), jetparton::build(), electron::build(), muon::build(), get_children(), get_hash(), get_parents(), operator==(), particle_template(), register_child(), register_parent(), parton::top_mass_contribution(), and ~particle_template().
index
cproperty<int, particle_template> particle_template::index
Definition at line 108 of file particle_template.h.
Referenced by assign_vector(), particle_gnn::build(), child::build(), physics_detector::build(), top_children::build(), physics_truth::build(), truthjetparton::build(), jet::build(), parton::build(), lepton::build(), jetparton::build(), electron::build(), muon::build(), and particle_template().
is_add
cproperty<bool, particle_template> particle_template::is_add
Definition at line 90 of file particle_template.h.
Referenced by particle_template().
is_b
cproperty<bool, particle_template> particle_template::is_b
Definition at line 81 of file particle_template.h.
Referenced by jet::build(), get_isadd(), and particle_template().
is_lep
cproperty<bool, particle_template> particle_template::is_lep
Definition at line 84 of file particle_template.h.
Referenced by get_isadd(), get_lepdecay(), particle_template(), and zprime::strategy().
is_nu
cproperty<bool, particle_template> particle_template::is_nu
Definition at line 87 of file particle_template.h.
Referenced by get_isadd(), get_lepdecay(), particle_template(), and zprime::strategy().
leaves
std::map<std::string, std::string> particle_template::leaves = {}
Definition at line 138 of file particle_template.h.
Referenced by add_leaf(), and apply_type_prefix().
lep_decay
cproperty<bool, particle_template> particle_template::lep_decay
Definition at line 93 of file particle_template.h.
Referenced by particle_template().
m_children
std::map<std::string, particle_template*> particle_template::m_children
Definition at line 135 of file particle_template.h.
Referenced by get_children(), register_child(), and set_children().
m_parents
std::map<std::string, particle_template*> particle_template::m_parents
Definition at line 132 of file particle_template.h.
Referenced by get_parents(), register_parent(), and set_parents().
mass
cproperty<double, particle_template> particle_template::mass
Definition at line 36 of file particle_template.h.
Referenced by zboson::build(), parton::build(), get_e(), get_mass(), particle_template(), zprime::strategy(), and topkinematics::strategy().
parents
cproperty<std::map<std::string, particle_template*>, particle_template> particle_template::parents
Definition at line 96 of file particle_template.h.
Referenced by electron::get_from_res(), muon::get_from_res(), particle_template(), and parton::top_mass_contribution().
pdgid
cproperty<int, particle_template> particle_template::pdgid
Definition at line 65 of file particle_template.h.
Referenced by assign_vector(), child::build(), physics_detector::build(), top_children::build(), physics_truth::build(), truthjetparton::build(), parton::build(), jetparton::build(), electron::build(), muon::build(), get_pdgid(), get_symbol(), particle_template(), parton::strategy(), and parton::top_mass_contribution().
phi
cproperty<double, particle_template> particle_template::phi
Definition at line 48 of file particle_template.h.
Referenced by assign_vector(), particle_gnn::build(), zboson::build(), top_children::build(), truthjetparton::build(), jet::build(), parton::build(), lepton::build(), jetparton::build(), electron::build(), muon::build(), DeltaR(), particle_template(), to_cartesian(), and to_polar().
pt
cproperty<double, particle_template> particle_template::pt
Definition at line 40 of file particle_template.h.
Referenced by assign_vector(), particle_gnn::build(), zboson::build(), top_children::build(), truthjetparton::build(), jet::build(), parton::build(), lepton::build(), jetparton::build(), electron::build(), muon::build(), particle_template(), parton::strategy(), to_cartesian(), and to_polar().
px
cproperty<double, particle_template> particle_template::px
Definition at line 53 of file particle_template.h.
Referenced by parton::build(), lepton::build(), get_e(), get_hash(), get_mass(), operator+(), operator+=(), particle_template(), to_cartesian(), and to_polar().
py
cproperty<double, particle_template> particle_template::py
Definition at line 57 of file particle_template.h.
Referenced by get_e(), get_hash(), get_mass(), operator+(), operator+=(), particle_template(), to_cartesian(), and to_polar().
pz
cproperty<double, particle_template> particle_template::pz
Definition at line 61 of file particle_template.h.
Referenced by get_e(), get_hash(), get_mass(), operator+(), operator+=(), particle_template(), to_cartesian(), and to_polar().
symbol
cproperty<std::string, particle_template> particle_template::symbol
Definition at line 69 of file particle_template.h.
Referenced by get_pdgid(), get_symbol(), and particle_template().
type
cproperty<std::string, particle_template> particle_template::type
Definition at line 104 of file particle_template.h.
Referenced by classes.atomic::__str__(), validation.classes.atomic::__str__(), apply_type_prefix(), child::child(), electron::electron(), jet::jet(), jetparton::jetparton(), lepton::lepton(), muon::muon(), particle_gnn::particle_gnn(), particle_template(), parton::parton(), physics_detector::physics_detector(), physics_truth::physics_truth(), top::top(), top_children::top_children(), truthjet::truthjet(), truthjetparton::truthjetparton(), zboson::zboson(), and zprime::zprime().
The documentation for this class was generated from the following files:
particle_template.h
cartesian.cxx
interfaces.cxx
particle_template.cxx
modules/particle/cxx/physics.cxx
polar.cxx