AnalysisG: childrenkinematics Class Reference
childrenkinematics Class Reference
#include <childrenkinematics.h>
Public Member Functions
childrenkinematics ()
~childrenkinematics () override
selection_template * clone () override
bool selection (event_template *ev) override
bool strategy (event_template *ev) override
void merge (selection_template *sl) override
Public Member Functions inherited from selection_template
selection_template ()
virtual ~selection_template ()
virtual void bulk_write (const long *idx, std::string *hx)
virtual void write (std::vector< particle_template * > *particles, std::string name, particle_enum attrs)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< std::vector< double >> *data)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< int > *data)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< double > *data)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< bool > *data)
template<typename g >
void write (g *var, std::string name)
template<typename g >
void write (g var, std::string name)
std::vector< std::map< std::string, float > > reverse_hash (std::vector< std::string > *hashes)
bool CompileEvent ()
selection_template * build (event_template *ev)
bool operator== (selection_template &p)
template<typename g , typename k >
void sum (std::vector< g * > *ch, k **out)
template<typename g >
void safe_delete (std::vector< g * > *particles)
template<typename g >
g * sum (std::map< std::string, g * > *ch)
template<typename g >
float sum (std::vector< g * > *ch)
template<typename g >
std::vector< g * > vectorize (std::map< std::string, g * > *in)
template<typename g >
std::vector< g * > make_unique (std::vector< g * > *inpt)
template<typename g >
void downcast (std::vector< g * > *inpt, std::vector< particle_template * > *out)
template<typename o , typename g >
void upcast (std::map< std::string, o * > *inpt, std::vector< g * > *out)
template<typename o , typename g >
void upcast (std::vector< o * > *inpt, std::vector< g * > *out)
template<typename g >
void get_leptonics (std::map< std::string, g * > inpt, std::vector< particle_template * > *out)
template<typename g , typename j >
bool contains (std::vector< g * > *inpt, j *pcheck)
Public Member Functions inherited from tools
tools ()
Constructor for the tools class.
~tools ()
Destructor for the tools class.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Public Attributes
std::vector< kinematic_t > res_kinematics = {}
std::vector< kinematic_t > spec_kinematics = {}
std::vector< misc_t > res_decay_mode = {}
std::vector< misc_t > spec_decay_mode = {}
std::vector< perms_t > top_clusters = {}
Public Attributes inherited from selection_template
cproperty< std::string, selection_template > name
cproperty< std::string, selection_template > hash
cproperty< std::string, selection_template > tree
cproperty< double, selection_template > weight
cproperty< long, selection_template > index
meta * meta_data = nullptr
std::string filename = ""
event_t data
int threadIdx = -1
std::map< std::string, std::map< std::string, float > > passed_weights = {}
std::map< std::string, meta_t > matched_meta = {}
Additional Inherited Members
Static Public Member Functions inherited from selection_template
static void set_name (std::string *, selection_template *)
static void get_name (std::string *, selection_template *)
static void set_hash (std::string *, selection_template *)
static void get_hash (std::string *, selection_template *)
static void get_tree (std::string *, selection_template *)
static void set_weight (double *, selection_template *)
static void get_weight (double *, selection_template *)
static void set_index (long *, selection_template *)
Static Public Member Functions inherited from tools
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Detailed Description
Definition at line 39 of file childrenkinematics.h.
Constructor & Destructor Documentation
childrenkinematics()
childrenkinematics::childrenkinematics ()
Definition at line 3 of file childrenkinematics.cxx.
 {this -> name = "childrenkinematics";}
References selection_template::name.
Referenced by clone().
~childrenkinematics()
childrenkinematics::~childrenkinematics () override
Definition at line 4 of file childrenkinematics.cxx.
 {}
Member Function Documentation
clone()
selection_template * childrenkinematics::clone () override virtual
Reimplemented from selection_template.
Definition at line 6 of file childrenkinematics.cxx.
{
     return (selection_template*)new childrenkinematics();
 }
References childrenkinematics().
merge()
void childrenkinematics::merge (selection_template * sl) override virtual
Reimplemented from selection_template.
Definition at line 10 of file childrenkinematics.cxx.
{
     childrenkinematics* slt = (childrenkinematics*)sl;
     auto lambK = [this](std::vector<kinematic_t>* ptr, std::string key){
         std::vector<float> pt, e, eta, phi;
         std::vector<int> pdgid;
         for (size_t x(0); x < ptr -> size(); ++x){
             pt.push_back((*ptr)[x].pt);
              e.push_back((*ptr)[x].energy);
             eta.push_back((*ptr)[x].eta);
             phi.push_back((*ptr)[x].phi);
             pdgid.push_back((*ptr)[x].pdgid);
         }
         this -> write(&pt   , key + "_pt");
         this -> write(&e    , key + "_energy");
         this -> write(&eta  , key + "_eta");
         this -> write(&phi  , key + "_phi");
         this -> write(&pdgid, key + "_pdgid");
     };
     auto lambM = [this](std::vector<misc_t>* ptr, std::string key){
         std::vector<int> pdgid;
         std::vector<bool> is_lep;
         std::vector<float> pt, e, eta, phi, mass, dR, frc_e, frc_pt;
         for (size_t x(0); x < ptr -> size(); ++x){
             pt.push_back((*ptr)[x].kin.pt);
             e.push_back((*ptr)[x].kin.energy);
             eta.push_back((*ptr)[x].kin.eta);
             phi.push_back((*ptr)[x].kin.phi);
             pdgid.push_back((*ptr)[x].kin.pdgid);
             is_lep.push_back((*ptr)[x].is_lep);
             mass.push_back((*ptr)[x].mass_clust);
             dR.push_back((*ptr)[x].delta_R);
             frc_e.push_back((*ptr)[x].frc_energy);
             frc_pt.push_back((*ptr)[x].frc_pt);
         }
         this -> write(&pt    , key + "_decay_pt");
         this -> write(&e     , key + "_decay_energy");
         this -> write(&eta   , key + "_decay_eta");
         this -> write(&phi   , key + "_decay_phi");
         this -> write(&pdgid , key + "_decay_pdgid");
         this -> write(&is_lep, key + "_decay_islep");
         this -> write(&mass  , key + "_decay_mass");
         this -> write(&dR    , key + "_decay_dR");
         this -> write(&frc_e , key + "_decay_frc_e");
         this -> write(&frc_pt, key + "_decay_frc_pt");
     };
     auto lambP = [this](std::vector<perms_t>* ptr, std::string key){
         std::vector<bool> rr, ss, rs, ct, ft;
         std::vector<float> pt, dR, e, mass;
         for (size_t x(0); x < ptr -> size(); ++x){
             pt.push_back((*ptr)[x].top_pt);
              e.push_back((*ptr)[x].top_e);
             dR.push_back((*ptr)[x].delta_R);
             mass.push_back((*ptr)[x].mass);
             rr.push_back((*ptr)[x].RR);
             ss.push_back((*ptr)[x].SS);
             rs.push_back((*ptr)[x].RS);
             ct.push_back((*ptr)[x].CT);
             ft.push_back((*ptr)[x].FT);
         }
         this -> write(&pt  , key + "_pt");
         this -> write(&e   , key + "_energy");
         this -> write(&mass, key + "_mass");
         this -> write(&dR  , key + "_dR");
         this -> write(&rr  , key + "_RR");
         this -> write(&ss  , key + "_SS");
         this -> write(&rs  , key + "_RS");
         this -> write(&ct  , key + "_CT");
         this -> write(&ft  , key + "_FT");
     };
     lambK(&slt -> res_kinematics , "res");
     lambK(&slt -> spec_kinematics, "spec");
     lambM(&slt -> res_decay_mode , "res");
     lambM(&slt -> spec_decay_mode, "spec");
     lambP(&slt -> top_clusters   , "top_perm");
     //merge_data(&this -> res_kinematics       , &slt -> res_kinematics);
     //merge_data(&this -> spec_kinematics      , &slt -> spec_kinematics);
     //merge_data(&this -> res_pdgid_kinematics , &slt -> res_pdgid_kinematics);
     //merge_data(&this -> spec_pdgid_kinematics, &slt -> spec_pdgid_kinematics);
     //merge_data(&this -> res_decay_mode       , &slt -> res_decay_mode);
     //merge_data(&this -> spec_decay_mode      , &slt -> spec_decay_mode);
     //merge_data(&this -> mass_clustering      , &slt -> mass_clustering);
     //merge_data(&this -> fractional           , &slt -> fractional);
     //merge_data(&this -> dr_clustering        , &slt -> dr_clustering);
     //merge_data(&this -> top_pt_clustering    , &slt -> top_pt_clustering);
     //merge_data(&this -> top_energy_clustering, &slt -> top_energy_clustering);
     //merge_data(&this -> top_children_dr      , &slt -> top_children_dr);
 }
References test_particles::e, is_lep, mass, res_decay_mode, res_kinematics, main::sl, spec_decay_mode, spec_kinematics, top_clusters, selection_template::write(), and main::x.
selection()
bool childrenkinematics::selection (event_template * ev) override virtual
Reimplemented from selection_template.
Definition at line 107 of file childrenkinematics.cxx.
{
     bsm_4tops* evn = (bsm_4tops*)ev;
     std::vector<particle_template*> tops = evn -> Tops;
     int n_res = 0;
     int n_spec = 0;
     for (size_t x(0); x < tops.size(); ++x){
         top* t = (top*)tops[x];
         if (t -> from_res){n_res++;}
         else {n_spec++;}
     }
     return (n_res == 2) && (n_spec == 2);
 }
References main::ev, test_normalization::evn, test_experimental_mc20::t, and main::x.
strategy()
bool childrenkinematics::strategy (event_template * ev) override virtual
Reimplemented from selection_template.
Definition at line 121 of file childrenkinematics.cxx.
{
     bsm_4tops* evn = (bsm_4tops*)ev;
     std::vector<particle_template*> tops = evn -> Tops;
     std::vector<particle_template*> res_t = {};
     std::vector<particle_template*> res_children = {};
     for (size_t x(0); x < tops.size(); ++x){
         top* t = (top*)tops[x];
         if (!t -> from_res){continue;}
         res_t.push_back(tops[x]);
         std::map<std::string, particle_template*> ch = t -> children;
         std::vector<particle_template*> ch_ = this -> vectorize(&ch);
         merge_data(&res_children, &ch_);
     }
     for (size_t x(0); x < res_children.size(); ++x){
         this -> dump_kinematics(&this -> res_kinematics, res_children[x]);
     }
     for (size_t x(0); x < res_t.size(); ++x){
         top* t = (top*)res_t[x];
         std::string flag = "had";
         std::map<std::string, particle_template*> ch = t -> children;
         std::vector<particle_template*> ch_ = this -> vectorize(&ch);
         for (size_t c(0); c < ch_.size(); ++c){
             if (!ch_[c] -> is_lep){continue;}
             flag = "lep";
             break;
         }
         for (size_t c(0); c < ch_.size(); ++c){
             particle_template* c_ = ch_[c];
             misc_t msx;
             msx.is_lep = (flag == "lep");
             this -> dump_kinematics(&msx.kin, c_);
             msx.delta_R = t -> DeltaR(c_);
             msx.frc_pt = (c_ -> pt / t -> pt);
             msx.frc_energy = (c_ -> e / t -> e);
             this -> res_decay_mode.push_back(msx);
         }
     }
     std::vector<particle_template*> spec_t = {};
     std::vector<particle_template*> spec_children = {};
     for (size_t x(0); x < tops.size(); ++x){
         top* t = (top*)tops[x];
         if (t -> from_res){continue;}
         spec_t.push_back(tops[x]);
         std::map<std::string, particle_template*> ch = t -> children;
         std::vector<particle_template*> ch_ = this -> vectorize(&ch);
         merge_data(&spec_children, &ch_);
     }
     for (size_t x(0); x < spec_children.size(); ++x){
         this -> dump_kinematics(&this -> spec_kinematics, spec_children[x]);
     }
     for (size_t x(0); x < spec_t.size(); ++x){
         top* t = (top*)spec_t[x];
         std::string flag = "had";
         std::map<std::string, particle_template*> ch = t -> children;
         std::vector<particle_template*> ch_ = this -> vectorize(&ch);
         for (size_t c(0); c < ch_.size(); ++c){
             if (!ch_[c] -> is_lep){continue;}
             flag = "lep";
             break;
         }
         for (size_t c(0); c < ch_.size(); ++c){
             particle_template* c_ = ch_[c];
             misc_t msx;
             msx.is_lep = (flag == "lep");
             this -> dump_kinematics(&msx.kin, c_);
             msx.delta_R = t -> DeltaR(c_);
             msx.frc_pt = (c_ -> pt / t -> pt);
             msx.frc_energy = (c_ -> e / t -> e);
             this -> spec_decay_mode.push_back(msx);
         }
     }
     std::vector<std::vector<particle_template*>> pairs = {};
     for (size_t x(0); x < tops.size(); ++x){
         std::map<std::string, particle_template*> ch_ = tops[x] -> children;
         std::vector<particle_template*> ch = this -> vectorize(&ch_);
         for (size_t c(0); c < ch.size(); ++c){pairs.push_back({tops[x], ch[c]});}
     }
     for (size_t t1(0); t1 < pairs.size(); ++t1){
         for (size_t t2(t1+1); t2 < pairs.size(); ++t2){
             top* t1_ = (top*)pairs[t1][0];
             top* t2_ = (top*)pairs[t2][0];
             particle_template* c1_ = pairs[t1][1];
             particle_template* c2_ = pairs[t2][1];
             perms_t xt;
             xt.RR  = ( t1_ -> from_res) * ( t2_ -> from_res);
             xt.RS  = ( t1_ -> from_res) * (!t2_ -> from_res);
             xt.RS += (!t1_ -> from_res) * ( t2_ -> from_res);
             xt.SS  = (!t1_ -> from_res) * (!t2_ -> from_res);
             xt.CT  =  ((*t1_) == (*t2_));
             xt.FT  = !((*t1_) == (*t2_));
             xt.delta_R = c1_ -> DeltaR(c2_);
             xt.top_pt = t2_ -> pt / 1000;
             xt.top_e  = t2_ -> e  / 1000;
             std::map<std::string, particle_template*> ch_1 = t1_ -> children;
             std::map<std::string, particle_template*> ch_2 = t2_ -> children;
             std::vector<particle_template*> c_1 = this -> vectorize(&ch_1);
             std::vector<particle_template*> c_2 = this -> vectorize(&ch_2);
             std::vector<particle_template*> pair_mass = {};
             merge_data(&pair_mass, &c_1);
             merge_data(&pair_mass, &c_2);
             xt.mass  = this -> sum(&pair_mass);
             this -> top_clusters.push_back(xt);
         }
     }
     return true;
 }
References c, perms_t::CT, misc_t::delta_R, perms_t::delta_R, pyc::physics::cartesian::separate::DeltaR(), test_particles::e, main::ev, test_normalization::evn, misc_t::frc_energy, misc_t::frc_pt, perms_t::FT, misc_t::is_lep, is_lep, misc_t::kin, perms_t::mass, merge_data(), res_decay_mode, res_kinematics, perms_t::RR, perms_t::RS, spec_decay_mode, spec_kinematics, perms_t::SS, selection_template::sum(), test_experimental_mc20::t, top_clusters, perms_t::top_e, perms_t::top_pt, selection_template::vectorize(), and main::x.
Member Data Documentation
res_decay_mode
std::vector<misc_t> childrenkinematics::res_decay_mode = {}
Definition at line 53 of file childrenkinematics.h.
Referenced by merge(), and strategy().
res_kinematics
std::vector<kinematic_t> childrenkinematics::res_kinematics = {}
Definition at line 50 of file childrenkinematics.h.
Referenced by merge(), and strategy().
spec_decay_mode
std::vector<misc_t> childrenkinematics::spec_decay_mode = {}
Definition at line 54 of file childrenkinematics.h.
Referenced by merge(), and strategy().
spec_kinematics
std::vector<kinematic_t> childrenkinematics::spec_kinematics = {}
Definition at line 51 of file childrenkinematics.h.
Referenced by merge(), and strategy().
top_clusters
std::vector<perms_t> childrenkinematics::top_clusters = {}
Definition at line 55 of file childrenkinematics.h.
Referenced by merge(), and strategy().
The documentation for this class was generated from the following files:
childrenkinematics.h
childrenkinematics.cxx