AnalysisG: graph_template Class Reference
graph_template Class Reference
#include <graph_template.h>
Public Member Functions
graph_template ()
virtual ~graph_template ()
virtual graph_template * clone ()
virtual void CompileEvent ()
virtual bool PreSelection ()
void define_particle_nodes (std::vector< particle_template * > *prt)
void define_topology (std::function< bool(particle_template *, particle_template *)> fx)
void flush_particles ()
bool operator== (graph_template &p)
template<typename G >
G * get_event ()
template<typename G , typename O , typename X >
void add_graph_truth_feature (O *ev, X fx, std::string name)
template<typename G , typename O , typename X >
void add_graph_data_feature (O *ev, X fx, std::string name)
template<typename G , typename O , typename X >
void add_node_truth_feature (X fx, std::string name)
template<typename G , typename O , typename X >
void add_node_data_feature (X fx, std::string name)
template<typename G , typename O , typename X >
void add_edge_truth_feature (X fx, std::string name)
template<typename G , typename O , typename X >
void add_edge_data_feature (X fx, std::string name)
bool double_neutrino (double mass_top=172.62 *1000, double mass_wboson=80.385 *1000, double top_perc=0.85, double w_perc=0.95, double distance=1e-8, int steps=10)
Public Member Functions inherited from tools
tools ()
Constructor for the tools class.
~tools ()
Destructor for the tools class.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Public Attributes
cproperty< long, graph_template > index
cproperty< double, graph_template > weight
cproperty< bool, graph_template > preselection
cproperty< std::string, graph_template > hash
cproperty< std::string, graph_template > tree
cproperty< std::string, graph_template > name
int threadIdx = -1
std::string filename = ""
meta * meta_data = nullptr
Additional Inherited Members
Static Public Member Functions inherited from tools
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Detailed Description
Definition at line 178 of file graph_template.h.
Constructor & Destructor Documentation
graph_template()
graph_template::graph_template ()
Definition at line 3 of file graph_template.cxx.
{
     this -> op = new torch::TensorOptions(torch::kCPU);
     this -> name.set_setter(this -> set_name);
     this -> name.set_object(this);
     this -> preselection.set_setter(this -> set_preselection);
     this -> preselection.set_getter(this -> get_preselection);
     this -> preselection.set_object(this);
     this -> hash.set_getter(this -> get_hash);
     this -> hash.set_object(this);
     this -> tree.set_getter(this -> get_tree);
     this -> tree.set_object(this);
     this -> index.set_getter(this -> get_index);
     this -> index.set_object(this);
     this -> weight.set_getter(this -> get_weight);
     this -> weight.set_object(this);
 }
References hash, index, name, preselection, cproperty< T, G >::set_getter(), cproperty< T, G >::set_object(), cproperty< T, G >::set_setter(), tree, and weight.
Referenced by clone().
~graph_template()
graph_template::~graph_template () virtual
Definition at line 25 of file graph_template.cxx.
{
     if (!this -> op){return;}
     delete this -> op;
 }
Member Function Documentation
add_edge_data_feature()
template<typename G , typename O , typename X > void graph_template::add_edge_data_feature (X fx, std::string name) inline
Definition at line 279 of file graph_template.h.
{
             int dx = -1;
             std::vector<G> edge_data = {};
             std::map<int, particle_template*>::iterator itr1;
             std::map<int, particle_template*>::iterator itr2;
             if (!this -> _topological_index.size()){this -> define_topology(fulltopo);}
             for (itr1 = this -> node_particles.begin(); itr1 != this -> node_particles.end(); ++itr1){
                 for (itr2 = this -> node_particles.begin(); itr2 != this -> node_particles.end(); ++itr2){
                     ++dx;
                     if (this -> _topological_index[dx] < 0){continue;}
                     std::tuple<O*, O*> p_ij(itr1 -> second, itr2 -> second);
                     cproperty<G, std::tuple<O*, O*>> cdef;
                     cdef.set_object(&p_ij);
                     cdef.set_getter(fx);
                     edge_data.push_back(cdef);
                 }
             }
             this -> add_edge_feature(edge_data, "D-" + name);
         }
References define_topology().
add_edge_truth_feature()
template<typename G , typename O , typename X > void graph_template::add_edge_truth_feature (X fx, std::string name) inline
Definition at line 256 of file graph_template.h.
{
             int dx = -1;
             std::vector<G> edge_data = {};
             std::map<int, particle_template*>::iterator itr1;
             std::map<int, particle_template*>::iterator itr2;
             if (!this -> _topological_index.size()){this -> define_topology(fulltopo);}
             for (itr1 = this -> node_particles.begin(); itr1 != this -> node_particles.end(); ++itr1){
                 for (itr2 = this -> node_particles.begin(); itr2 != this -> node_particles.end(); ++itr2){
                     ++dx;
                     if (this -> _topological_index[dx] < 0){continue;}
                     std::tuple<O*, O*> p_ij((O*)itr1 -> second, (O*)itr2 -> second);
                     cproperty<G, std::tuple<O*, O*>> cdef;
                     cdef.set_object(&p_ij);
                     cdef.set_getter(fx);
                     edge_data.push_back(cdef);
                 }
             }
             this -> add_edge_feature(edge_data, "T-" + name);
         }
References define_topology().
add_graph_data_feature()
template<typename G , typename O , typename X > void graph_template::add_graph_data_feature (O * ev, X fx, std::string name) inline
Definition at line 219 of file graph_template.h.
{
             cproperty<G, O> cdef;
             cdef.set_getter(fx);
             cdef.set_object(ev);
             G r = cdef;
             this -> add_graph_feature(r, "D-" + name);
         }
References main::ev, main::fx, name, cproperty< T, G >::set_getter(), and cproperty< T, G >::set_object().
add_graph_truth_feature()
template<typename G , typename O , typename X > void graph_template::add_graph_truth_feature (O * ev, X fx, std::string name) inline
Definition at line 209 of file graph_template.h.
{
             cproperty<G, O> cdef;
             cdef.set_getter(fx);
             cdef.set_object(ev);
             G r = cdef;
             this -> add_graph_feature(r, "T-" + name);
         }
References main::ev, main::fx, name, cproperty< T, G >::set_getter(), and cproperty< T, G >::set_object().
add_node_data_feature()
template<typename G , typename O , typename X > void graph_template::add_node_data_feature (X fx, std::string name) inline
Definition at line 242 of file graph_template.h.
{
             std::vector<G> nodes_data = {};
             std::map<int, particle_template*>::iterator itr = this -> node_particles.begin();
             for (; itr != this -> node_particles.end(); ++itr){
                 cproperty<G, O> cdef;
                 cdef.set_getter(fx);
                 cdef.set_object((O*)itr -> second);
                 nodes_data.push_back((G)cdef);
             }
             this -> add_node_feature(nodes_data, "D-" + name);
         }
References main::fx, name, cproperty< T, G >::set_getter(), and cproperty< T, G >::set_object().
add_node_truth_feature()
template<typename G , typename O , typename X > void graph_template::add_node_truth_feature (X fx, std::string name) inline
Definition at line 228 of file graph_template.h.
{
             std::vector<G> nodes_data = {};
             std::map<int, particle_template*>::iterator itr = this -> node_particles.begin();
             for (; itr != this -> node_particles.end(); ++itr){
                 cproperty<G, O> cdef;
                 cdef.set_getter(fx);
                 cdef.set_object((O*)itr -> second);
                 nodes_data.push_back((G)cdef);
             }
             this -> add_node_feature(nodes_data, "T-" + name);
         }
References main::fx, name, cproperty< T, G >::set_getter(), and cproperty< T, G >::set_object().
clone()
graph_template * graph_template::clone () virtual
Reimplemented in graph_detector, graph_jets_detector_lep, graph_jets_nonu, graph_jets, graph_detector, graph_detector, graph_truthjets_nonu, graph_jets_detector_lep, graph_jets_detector_lep, graph_truthjets, graph_jets_nonu, graph_jets_nonu, graph_children, graph_tops, graph_jets, and graph_jets.
Definition at line 34 of file graph_template.cxx.
{
     return new graph_template();
 }
References graph_template().
CompileEvent()
void graph_template::CompileEvent () virtual
Reimplemented in graph_detector, graph_jets_detector_lep, graph_jets_nonu, graph_jets, graph_detector, graph_detector, graph_truthjets_nonu, graph_jets_detector_lep, graph_jets_detector_lep, graph_truthjets, graph_jets_nonu, graph_jets_nonu, graph_children, graph_tops, graph_jets, and graph_jets.
Definition at line 203 of file graph_template.cxx.
 {}
define_particle_nodes()
void graph_template::define_particle_nodes (std::vector< particle_template * > * prt)
Definition at line 47 of file graph_template.cxx.
{
     for (size_t x(0); x < prt -> size(); ++x){
         std::string hash_ = (*prt)[x] -> hash;
         if (this -> nodes.count(hash_)){continue;}
         int n_nodes = (int)this -> nodes.size();
         this -> node_particles[n_nodes] = (*prt)[x];
         this -> nodes[hash_] = n_nodes;
     }
     this -> num_nodes = this -> nodes.size();
 }
References hash, and main::x.
Referenced by graph_tops::CompileEvent(), graph_children::CompileEvent(), graph_truthjets::CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), and graph_detector::CompileEvent().
define_topology()
void graph_template::define_topology (std::function< bool(particle_template *, particle_template *)> fx)
Definition at line 58 of file graph_template.cxx.
{
     std::map<int, particle_template*>::iterator itr1;
     std::map<int, particle_template*>::iterator itr2;
     this -> _topology = {};
     this -> _topological_index = {};
     int idx = 0;
     std::vector<int> src_, dst_ = {};
     for (itr1 = this -> node_particles.begin(); itr1 != this -> node_particles.end(); ++itr1){
         for (itr2 = this -> node_particles.begin(); itr2 != this -> node_particles.end(); ++itr2){
             if (!fx(itr1 -> second, itr2 -> second)){
                 this -> _topology.push_back({});
                 this -> _topological_index.push_back(-1);
                 continue;
             }
             src_.push_back(itr1 -> first);
             dst_.push_back(itr2 -> first);
             this -> _topology.push_back({itr1 -> first, itr2 -> first});
             this -> _topological_index.push_back(idx);
             ++idx;
         }
     }
     torch::Tensor t1 = this -> to_tensor(src_, torch::kInt, int()).view({1, -1});
     torch::Tensor t2 = this -> to_tensor(dst_, torch::kInt, int()).view({1, -1});
     this -> m_topology = torch::cat({t1, t2}, 0);
 }
References main::fx, and this.
Referenced by add_edge_data_feature(), add_edge_truth_feature(), graph_children::CompileEvent(), graph_truthjets::CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), and graph_detector::CompileEvent().
double_neutrino()
bool graph_template::double_neutrino (double mass_top = 172.62*1000, double mass_wboson = 80.385*1000, double top_perc = 0.85, double w_perc = 0.95, double distance = 1e-8, int steps = 10)
Definition at line 87 of file graph_template.cxx.
  {
     if (!this -> node_fx.count("D-pt")){return false;}
     if (!this -> node_fx.count("D-eta")){return false;}
     if (!this -> node_fx.count("D-phi")){return false;}
     if (!this -> node_fx.count("D-energy")){return false;}
     if (!this -> node_fx.count("D-is_lep")){return false;}
     if (!this -> node_fx.count("D-is_b")){return false;}
     if (!this -> graph_fx.count("D-met")){return false;}
     if (!this -> graph_fx.count("D-phi")){return false;}
     torch::Tensor is_b   = this -> node_fx["D-is_b"];
     torch::Tensor is_lep = this -> node_fx["D-is_lep"];
     torch::Tensor chk = (is_b.view({-1}).sum({-1}) >= 2) * (is_lep.view({-1}).sum({-1}) >= 2);
     if (!chk.index({chk}).size({0})){return true;}
     torch::Tensor pt         = this -> node_fx["D-pt"].to(cu_pyc);
     torch::Tensor eta        = this -> node_fx["D-eta"].to(cu_pyc);
     torch::Tensor phi        = this -> node_fx["D-phi"].to(cu_pyc);
     torch::Tensor energy     = this -> node_fx["D-energy"].to(cu_pyc);
     torch::Tensor pmc        = pyc::transform::separate::PxPyPzE(pt, eta, phi, energy);
     torch::Tensor pid        = torch::cat({is_lep, is_b}, {-1}).to(cu_pyc);
     torch::Tensor edge_index = this -> m_topology.to(torch::kLong).to(cu_pyc);
     torch::Tensor met        = this -> graph_fx["D-met"].to(cu_pyc);
     torch::Tensor met_phi    = this -> graph_fx["D-phi"].to(cu_pyc);
     torch::Tensor batch      = torch::zeros_like(pt.view({-1})).to(torch::kLong);
     torch::Tensor met_xy     = torch::cat({
             pyc::transform::separate::Px(met, met_phi),
             pyc::transform::separate::Py(met, met_phi)
     }, {-1});
     // protection against overloading the cuda cores.
     std::this_thread::sleep_for(std::chrono::microseconds(10));
     torch::Dict<std::string, torch::Tensor> nus = pyc::nusol::combinatorial(
         edge_index, batch, pmc, pid, met_xy, mass_top, mass_wboson, top_perc, w_perc, steps, distance
     );
     torch::Tensor l1 = nus.at("l1");
     torch::Tensor l2 = nus.at("l2");
     torch::Tensor b1 = nus.at("b1");
     torch::Tensor b2 = nus.at("b2");
     //if (!combi.index({combi}).size({0})){return true;}
     //torch::Tensor lep1 = nus["combi"].index({combi, 2}).to(torch::kInt);
     //torch::Tensor lep2 = nus["combi"].index({combi, 3}).to(torch::kInt);
     //pmc.index_put_({lep1}, nus["nu_1f"] + pmc.index({lep1}));
     //pmc.index_put_({lep2}, nus["nu_2f"] + pmc.index({lep2}));
     //pmc = transform::cuda::PtEtaPhiE(pmc).to(c10::kCPU);
     //this -> node_fx["D-pt"]     = pmc.index({torch::indexing::Slice(), 0}).view({-1, 1});
     //this -> node_fx["D-eta"]    = pmc.index({torch::indexing::Slice(), 1}).view({-1, 1});
     //this -> node_fx["D-phi"]    = pmc.index({torch::indexing::Slice(), 2}).view({-1, 1});
     //this -> node_fx["D-energy"] = pmc.index({torch::indexing::Slice(), 3}).view({-1, 1});
     return true;
 }
References is_b, is_lep, and tools::sum().
flush_particles()
void graph_template::flush_particles ()
Definition at line 38 of file graph_template.cxx.
{
     this -> m_event = nullptr;
     this -> _topology = {};
     this -> _topological_index = {};
     this -> nodes = {};
     this -> node_particles = {};
 }
get_event()
template<typename G > G* graph_template::get_event () inline
Definition at line 206 of file graph_template.h.
 {return (G*)this -> m_event;}
operator==()
bool graph_template::operator== (graph_template & p)
Definition at line 30 of file graph_template.cxx.
{
     return this -> hash == p.hash;
 }
References hash, and rnn_model::p.
PreSelection()
bool graph_template::PreSelection () virtual
Reimplemented in graph_jets.
Definition at line 204 of file graph_template.cxx.
 {return true;}
Member Data Documentation
filename
std::string graph_template::filename = ""
Definition at line 202 of file graph_template.h.
hash
cproperty<std::string, graph_template> graph_template::hash
Definition at line 197 of file graph_template.h.
Referenced by define_particle_nodes(), graph_template(), and operator==().
index
cproperty<long , graph_template> graph_template::index
Definition at line 193 of file graph_template.h.
Referenced by graph_template().
meta_data
meta* graph_template::meta_data = nullptr
Definition at line 203 of file graph_template.h.
name
cproperty<std::string, graph_template> graph_template::name
Definition at line 199 of file graph_template.h.
Referenced by add_graph_data_feature(), add_graph_truth_feature(), add_node_data_feature(), add_node_truth_feature(), graph_children::graph_children(), graph_detector::graph_detector(), graph_jets::graph_jets(), graph_jets_detector_lep::graph_jets_detector_lep(), graph_jets_nonu::graph_jets_nonu(), graph_template(), graph_tops::graph_tops(), graph_truthjets::graph_truthjets(), and graph_truthjets_nonu::graph_truthjets_nonu().
preselection
cproperty<bool , graph_template> graph_template::preselection
Definition at line 195 of file graph_template.h.
Referenced by graph_template().
threadIdx
int graph_template::threadIdx = -1
Definition at line 201 of file graph_template.h.
tree
cproperty<std::string, graph_template> graph_template::tree
Definition at line 198 of file graph_template.h.
Referenced by graph_template().
weight
cproperty<double, graph_template> graph_template::weight
Definition at line 194 of file graph_template.h.
Referenced by graph_template().
The documentation for this class was generated from the following files:
graph_template.h
graph_template.cxx
graph/cxx/properties.cxx