AnalysisG: jet Class Reference
jet Class Reference
#include <particles.h>
Public Member Functions
jet ()
virtual ~jet ()
particle_template * clone () override
void build (std::map< std::string, particle_template * > *prt, element_t *el) override
jet ()
virtual ~jet ()
particle_template * clone () override
void build (std::map< std::string, particle_template * > *prt, element_t *el) override
jet ()
virtual ~jet ()
particle_template * clone () override
void build (std::map< std::string, particle_template * > *prt, element_t *el) override
particle_template ()
particle_template (particle_t *p)
particle_template (particle_template *p, bool dump=false)
particle_template (double px, double py, double pz, double e)
particle_template (double px, double py, double pz)
Public Member Functions inherited from particle_template
particle_template ()
virtual ~particle_template ()
particle_template (particle_t *p)
particle_template (particle_template *p, bool dump=false)
particle_template (double px, double py, double pz, double e)
particle_template (double px, double py, double pz)
void to_cartesian ()
void to_polar ()
bool is (std::vector< int > p)
double DeltaR (particle_template *p)
bool operator== (particle_template &p)
template<typename g >
g operator+ (g &p)
void operator+= (particle_template *p)
void iadd (particle_template *p)
bool register_parent (particle_template *p)
bool register_child (particle_template *p)
void add_leaf (std::string key, std::string leaf="")
void apply_type_prefix ()
std::map< std::string, std::map< std::string, particle_t > > __reduce__ ()
Public Member Functions inherited from tools
tools ()
Constructor for the tools class.
~tools ()
Destructor for the tools class.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Static Public Member Functions
static void get_from_res (bool *val, jet *el)
Static Public Member Functions inherited from particle_template
static void set_e (double *, particle_template *)
static void get_e (double *, particle_template *)
static void set_mass (double *, particle_template *)
static void get_mass (double *, particle_template *)
static void set_pt (double *, particle_template *)
static void get_pt (double *, particle_template *)
static void set_eta (double *, particle_template *)
static void get_eta (double *, particle_template *)
static void set_phi (double *, particle_template *)
static void get_phi (double *, particle_template *)
static void set_px (double *, particle_template *)
static void get_px (double *, particle_template *)
static void set_py (double *, particle_template *)
static void get_py (double *, particle_template *)
static void set_pz (double *, particle_template *)
static void get_pz (double *, particle_template *)
static void set_pdgid (int *, particle_template *)
static void get_pdgid (int *, particle_template *)
static void set_symbol (std::string *, particle_template *)
static void get_symbol (std::string *, particle_template *)
static void set_charge (double *, particle_template *)
static void get_charge (double *, particle_template *)
static void get_hash (std::string *, particle_template *)
static void get_isb (bool *, particle_template *)
static void get_islep (bool *, particle_template *)
static void get_isnu (bool *, particle_template *)
static void get_isadd (bool *, particle_template *)
static void get_lepdecay (bool *, particle_template *)
static void set_parents (std::map< std::string, particle_template * > *, particle_template *)
static void get_parents (std::map< std::string, particle_template * > *, particle_template *)
static void set_children (std::map< std::string, particle_template * > *, particle_template *)
static void get_children (std::map< std::string, particle_template * > *, particle_template *)
static void set_type (std::string *, particle_template *)
static void get_type (std::string *, particle_template *)
static void set_index (int *, particle_template *)
static void get_index (int *, particle_template *)
Static Public Member Functions inherited from tools
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Public Attributes
std::vector< top * > Tops = {}
std::vector< jetparton * > Parton = {}
std::vector< int > top_index = {}
cproperty< bool, jet > from_res
bool btag_DL1r_60
bool btag_DL1_60
bool btag_DL1r_70
bool btag_DL1_70
bool btag_DL1r_77
bool btag_DL1_77
bool btag_DL1r_85
bool btag_DL1_85
float DL1_b
float DL1_c
float DL1_u
float DL1r_b
float DL1r_c
float DL1r_u
bool btag_65
bool btag_70
bool btag_77 = false
bool btag_85 = false
bool btag_90 = false
int flav
int label
int top_index = -1
bool sel_85 = false
Public Attributes inherited from particle_template
cproperty< double, particle_template > e
cproperty< double, particle_template > mass
cproperty< double, particle_template > pt
cproperty< double, particle_template > eta
cproperty< double, particle_template > phi
cproperty< double, particle_template > px
cproperty< double, particle_template > py
cproperty< double, particle_template > pz
cproperty< int, particle_template > pdgid
cproperty< std::string, particle_template > symbol
cproperty< double, particle_template > charge
cproperty< std::string, particle_template > hash
cproperty< bool, particle_template > is_b
cproperty< bool, particle_template > is_lep
cproperty< bool, particle_template > is_nu
cproperty< bool, particle_template > is_add
cproperty< bool, particle_template > lep_decay
cproperty< std::map< std::string, particle_template * >, particle_template > parents
cproperty< std::map< std::string, particle_template * >, particle_template > children
cproperty< std::string, particle_template > type
cproperty< int, particle_template > index
std::map< std::string, particle_template * > m_parents
std::map< std::string, particle_template * > m_children
std::map< std::string, std::string > leaves = {}
particle_t data
bool _is_serial = false
bool _is_marked = false
Detailed Description
Definition at line 116 of file events/bsm_4tops/include/bsm_4tops/particles.h.
Constructor & Destructor Documentation
jet() [1/3]
jet::jet ()
Definition at line 209 of file bsm_4tops/cxx/particles.cxx.
          : particle_template(){
     this -> type = "jet";
     this -> add_leaf("pt" , "_pt");
     this -> add_leaf("eta", "_eta");
     this -> add_leaf("phi", "_phi");
     this -> add_leaf("e"  , "_e");
     this -> add_leaf("index", "_index");
     this -> add_leaf("top_index"   , "_TopIndex");
     this -> add_leaf("btag_DL1r_60", "_isbtagged_DL1r_60");
     this -> add_leaf("btag_DL1_60" , "_isbtagged_DL1_60");
     this -> add_leaf("btag_DL1r_70", "_isbtagged_DL1r_70");
     this -> add_leaf("btag_DL1_70" , "_isbtagged_DL1_70");
     this -> add_leaf("btag_DL1r_77", "_isbtagged_DL1r_77");
     this -> add_leaf("btag_DL1_77" , "_isbtagged_DL1_77");
     this -> add_leaf("btag_DL1r_85", "_isbtagged_DL1r_85");
     this -> add_leaf("btag_DL1_85" , "_isbtagged_DL1_85");
     this -> add_leaf("DL1_b" , "_DL1_pb");
     this -> add_leaf("DL1_c" , "_DL1_pc");
     this -> add_leaf("DL1_u" , "_DL1_pu");
     this -> add_leaf("DL1r_b", "_DL1r_pb");
     this -> add_leaf("DL1r_c", "_DL1r_pc");
     this -> add_leaf("DL1r_u", "_DL1r_pu");
     this -> apply_type_prefix();
     this -> from_res.set_object(this);
     this -> from_res.set_getter(this -> get_from_res);
 }
References particle_template::add_leaf(), particle_template::apply_type_prefix(), from_res, cproperty< T, G >::set_getter(), cproperty< T, G >::set_object(), and particle_template::type.
Referenced by build(), and clone().
~jet() [1/3]
jet::~jet () virtual
Definition at line 330 of file bsm_4tops/cxx/particles.cxx.
 {}
jet() [2/3]
jet::jet ()
~jet() [2/3]
virtual jet::~jet () virtual
jet() [3/3]
jet::jet ()
~jet() [3/3]
virtual jet::~jet () virtual
Member Function Documentation
build() [1/3]
void jet::build (std::map< std::string, particle_template * > * prt, element_t * el) override virtual
Reimplemented from particle_template.
build() [2/3]
void jet::build (std::map< std::string, particle_template * > * prt, element_t * el) override virtual
Reimplemented from particle_template.
build() [3/3]
void jet::build (std::map< std::string, particle_template * > * prt, element_t * el) override virtual
Reimplemented from particle_template.
Definition at line 245 of file bsm_4tops/cxx/particles.cxx.
{
     std::vector<int> _index;
     el -> get("index"     , &_index);
     std::vector<std::vector<int>> _top_index;
     el -> get("top_index" , &_top_index);
     std::vector<float> _pt, _eta, _phi, _e;
     el -> get("pt" , &_pt);
     el -> get("eta", &_eta);
     el -> get("phi", &_phi);
     el -> get("e"  , &_e);
     std::vector<char> _btag_DL1r_60;
     std::vector<char> _btag_DL1_60;
     std::vector<char> _btag_DL1r_70;
     std::vector<char> _btag_DL1_70;
     std::vector<char> _btag_DL1r_77;
     std::vector<char> _btag_DL1_77;
     std::vector<char> _btag_DL1r_85;
     std::vector<char> _btag_DL1_85;
     el -> get("btag_DL1r_60", &_btag_DL1r_60);
     el -> get("btag_DL1_60" , &_btag_DL1_60);
     el -> get("btag_DL1r_70", &_btag_DL1r_70);
     el -> get("btag_DL1_70" , &_btag_DL1_70);
     el -> get("btag_DL1r_77", &_btag_DL1r_77);
     el -> get("btag_DL1_77" , &_btag_DL1_77);
     el -> get("btag_DL1r_85", &_btag_DL1r_85);
     el -> get("btag_DL1_85" , &_btag_DL1_85);
     std::vector<float> _DL1_b;
     std::vector<float> _DL1_c;
     std::vector<float> _DL1_u;
     std::vector<float> _DL1r_b;
     std::vector<float> _DL1r_c;
     std::vector<float> _DL1r_u;
     el -> get("DL1_b" , &_DL1_b );
     el -> get("DL1_c" , &_DL1_c );
     el -> get("DL1_u" , &_DL1_u );
     el -> get("DL1r_b", &_DL1r_b);
     el -> get("DL1r_c", &_DL1r_c);
     el -> get("DL1r_u", &_DL1r_u);
     for (int x(0); x < _pt.size(); ++x){
         jet* p         = new jet();
         p -> pt        = _pt[x];
         p -> eta       = _eta[x];
         p -> phi       = _phi[x];
         p -> e         = _e[x];
         p -> index     = _index[x];
         p -> top_index = _top_index[x];
         p -> btag_DL1r_60 = (bool)_btag_DL1r_60[x];
         p -> btag_DL1_60  = (bool)_btag_DL1_60[x];
         p -> btag_DL1r_70 = (bool)_btag_DL1r_70[x];
         p -> btag_DL1_70  = (bool)_btag_DL1_70[x];
         p -> btag_DL1r_77 = (bool)_btag_DL1r_77[x];
         p -> btag_DL1_77  = (bool)_btag_DL1_77[x];
         p -> btag_DL1r_85 = (bool)_btag_DL1r_85[x];
         p -> btag_DL1_85  = (bool)_btag_DL1_85[x];
         p -> is_b         = (bool)_btag_DL1_85[x];
         p -> DL1_b  = _DL1_b[x];
         p -> DL1_c  = _DL1_c[x];
         p -> DL1_u  = _DL1_u[x];
         p -> DL1r_b = _DL1r_b[x];
         p -> DL1r_c = _DL1r_c[x];
         p -> DL1r_u = _DL1r_u[x];
         (*prt)[std::string(p -> hash)] = p;
     }
 }
References btag_DL1_60, btag_DL1_70, btag_DL1_77, btag_DL1_85, btag_DL1r_60, btag_DL1r_70, btag_DL1r_77, btag_DL1r_85, DL1_b, DL1_c, DL1_u, DL1r_b, DL1r_c, DL1r_u, particle_template::e, particle_template::eta, particle_template::hash, particle_template::index, particle_template::is_b, jet(), rnn_model::p, particle_template::phi, particle_template::pt, top_index, and main::x.
clone() [1/3]
particle_template* jet::clone () override virtual
Reimplemented from particle_template.
clone() [2/3]
particle_template* jet::clone () override virtual
Reimplemented from particle_template.
clone() [3/3]
particle_template * jet::clone () override virtual
Reimplemented from particle_template.
Definition at line 243 of file bsm_4tops/cxx/particles.cxx.
 {return new jet();}
References jet().
get_from_res()
static void jet::get_from_res (bool * val, jet * el) static
particle_template() [1/5]
particle_template::particle_template
Definition at line 3 of file particle_template.cxx.
{
     this -> e.set_setter(this -> set_e);
     this -> e.set_getter(this -> get_e);
     this -> e.set_object(this);
     this -> mass.set_setter(this -> set_mass);
     this -> mass.set_getter(this -> get_mass);
     this -> mass.set_object(this);
     this -> pt.set_setter(this -> set_pt);
     this -> pt.set_getter(this -> get_pt);
     this -> pt.set_object(this);
     this -> eta.set_setter(this -> set_eta);
     this -> eta.set_getter(this -> get_eta);
     this -> eta.set_object(this);
     this -> phi.set_setter(this -> set_phi);
     this -> phi.set_getter(this -> get_phi);
     this -> phi.set_object(this);
     this -> px.set_setter(this -> set_px);
     this -> px.set_getter(this -> get_px);
     this -> px.set_object(this);
     this -> py.set_setter(this -> set_py);
     this -> py.set_getter(this -> get_py);
     this -> py.set_object(this);
     this -> pz.set_setter(this -> set_pz);
     this -> pz.set_getter(this -> get_pz);
     this -> pz.set_object(this);
     this -> pdgid.set_setter(this -> set_pdgid);
     this -> pdgid.set_getter(this -> get_pdgid);
     this -> pdgid.set_object(this);
     this -> symbol.set_setter(this -> set_symbol);
     this -> symbol.set_getter(this -> get_symbol);
     this -> symbol.set_object(this);
     this -> charge.set_setter(this -> set_charge);
     this -> charge.set_getter(this -> get_charge);
     this -> charge.set_object(this);
     this -> hash.set_getter(this -> get_hash);
     this -> hash.set_object(this);
     this -> is_b.set_getter(this -> get_isb);
     this -> is_b.set_object(this);
     this -> is_lep.set_getter(this -> get_islep);
     this -> is_lep.set_object(this);
     this -> is_nu.set_getter(this -> get_isnu);
     this -> is_nu.set_object(this);
     this -> is_add.set_getter(this -> get_isadd);
     this -> is_add.set_object(this);
     this -> lep_decay.set_getter(this -> get_lepdecay);
     this -> lep_decay.set_object(this);
     this -> parents.set_setter(this -> set_parents);
     this -> parents.set_getter(this -> get_parents);
     this -> parents.set_object(this);
     this -> children.set_setter(this -> set_children);
     this -> children.set_getter(this -> get_children);
     this -> children.set_object(this);
     this -> type.set_setter(this -> set_type);
     this -> type.set_getter(this -> get_type);
     this -> type.set_object(this);
     this -> index.set_setter(this -> set_index);
     this -> index.set_getter(this -> get_index);
     this -> index.set_object(this);
 }
particle_template() [2/5]
particle_template::particle_template explicit
Definition at line 153 of file particle_template.cxx.
                                                                     : particle_template() {
     particle_t* p = &this -> data;
     p -> px = px; p -> py = py; p -> pz = pz; p -> e = this -> e;
     p -> polar = true;
 }
particle_template() [3/5]
particle_template::particle_template explicit
Definition at line 147 of file particle_template.cxx.
                                                                               : particle_template(){
     particle_t* p = &this -> data;
     p -> px = px; p -> py = py; p -> pz = pz; p -> e = e;
     p -> polar = true;
 }
particle_template() [4/5]
particle_template::particle_template explicit
Definition at line 83 of file particle_template.cxx.
 : particle_template(){this -> data = *p;}
particle_template() [5/5]
particle_template::particle_template explicit
Definition at line 85 of file particle_template.cxx.
                                                                     : particle_template(){
     if (!p){return;}
     this -> data = p -> data;
     this -> data.children.clear();
     this -> data.parents.clear();
     if (!dump){return;}
     p -> data.data_p = nullptr;
     bool init = (!this -> data.data_p);
     std::map<std::string, particle_template*>* tr = nullptr;
     if (init){tr = new std::map<std::string, particle_template*>();}
     else {tr = this -> data.data_p;}
     (*tr)[this -> hash] = this;
     this -> _is_serial = p -> _is_serial;
     std::map<std::string, particle_template*> ch_ = p -> children;
     std::map<std::string, particle_template*> pr_ = p -> parents;
     std::map<std::string, particle_template*>::iterator itr;
     for (itr = ch_.begin(); itr != ch_.end(); ++itr){
         itr -> second -> data.data_p = tr;
         if (!tr -> count(itr -> first)){(*tr)[itr -> first] = new particle_template(itr -> second, true);}
         itr -> second -> data.data_p = nullptr;
         particle_template* pr = (*tr)[itr -> first];
         this -> register_child(pr);
         pr -> data.data_p = nullptr;
         itr -> second -> _is_serial += p -> _is_serial;
         pr -> _is_serial = itr -> second -> _is_serial;
     }
     for (itr = pr_.begin(); itr != pr_.end(); ++itr){
         itr -> second -> data.data_p = tr;
         if (!tr -> count(itr -> first)){(*tr)[itr -> first] = new particle_template(itr -> second, true);}
         itr -> second -> data.data_p = nullptr;
         particle_template* pr = (*tr)[itr -> first];
         this -> register_parent(pr);
         pr -> data.data_p = nullptr;
         itr -> second -> _is_serial += p -> _is_serial;
         pr -> _is_serial = itr -> second -> _is_serial;
     }
     if (init){this -> data.data_p = tr;}
     else {this -> data.data_p = nullptr;}
 }
Member Data Documentation
btag_65
bool jet::btag_65
Definition at line 113 of file events/exp_mc20/include/exp_mc20/particles.h.
btag_70
bool jet::btag_70
Definition at line 114 of file events/exp_mc20/include/exp_mc20/particles.h.
btag_77
bool jet::btag_77 = false
Definition at line 115 of file events/exp_mc20/include/exp_mc20/particles.h.
btag_85
bool jet::btag_85 = false
Definition at line 116 of file events/exp_mc20/include/exp_mc20/particles.h.
btag_90
bool jet::btag_90 = false
Definition at line 117 of file events/exp_mc20/include/exp_mc20/particles.h.
btag_DL1_60
bool jet::btag_DL1_60
Definition at line 131 of file events/bsm_4tops/include/bsm_4tops/particles.h.
Referenced by build().
btag_DL1_70
bool jet::btag_DL1_70
Definition at line 133 of file events/bsm_4tops/include/bsm_4tops/particles.h.
Referenced by build().
btag_DL1_77
bool jet::btag_DL1_77
Definition at line 135 of file events/bsm_4tops/include/bsm_4tops/particles.h.
Referenced by build().
btag_DL1_85
bool jet::btag_DL1_85
Definition at line 137 of file events/bsm_4tops/include/bsm_4tops/particles.h.
Referenced by build().
btag_DL1r_60
bool jet::btag_DL1r_60
Definition at line 130 of file events/bsm_4tops/include/bsm_4tops/particles.h.
Referenced by build().
btag_DL1r_70
bool jet::btag_DL1r_70
Definition at line 132 of file events/bsm_4tops/include/bsm_4tops/particles.h.
Referenced by build().
btag_DL1r_77
bool jet::btag_DL1r_77
Definition at line 134 of file events/bsm_4tops/include/bsm_4tops/particles.h.
Referenced by build().
btag_DL1r_85
bool jet::btag_DL1r_85
Definition at line 136 of file events/bsm_4tops/include/bsm_4tops/particles.h.
Referenced by build().
DL1_b
float jet::DL1_b
Definition at line 139 of file events/bsm_4tops/include/bsm_4tops/particles.h.
Referenced by build().
DL1_c
float jet::DL1_c
Definition at line 140 of file events/bsm_4tops/include/bsm_4tops/particles.h.
Referenced by build().
DL1_u
float jet::DL1_u
Definition at line 141 of file events/bsm_4tops/include/bsm_4tops/particles.h.
Referenced by build().
DL1r_b
float jet::DL1r_b
Definition at line 142 of file events/bsm_4tops/include/bsm_4tops/particles.h.
Referenced by build().
DL1r_c
float jet::DL1r_c
Definition at line 143 of file events/bsm_4tops/include/bsm_4tops/particles.h.
Referenced by build().
DL1r_u
float jet::DL1r_u
Definition at line 144 of file events/bsm_4tops/include/bsm_4tops/particles.h.
Referenced by build().
flav
int jet::flav
Definition at line 119 of file events/exp_mc20/include/exp_mc20/particles.h.
from_res
cproperty< bool, jet > jet::from_res
Definition at line 128 of file events/bsm_4tops/include/bsm_4tops/particles.h.
Referenced by jet().
label
int jet::label
Definition at line 120 of file events/exp_mc20/include/exp_mc20/particles.h.
Parton
std::vector<jetparton*> jet::Parton = {}
Definition at line 125 of file events/bsm_4tops/include/bsm_4tops/particles.h.
sel_85
bool jet::sel_85 = false
Definition at line 95 of file events/ssml_mc20/include/ssml_mc20/particles.h.
top_index [1/2]
int jet::top_index = -1
Definition at line 91 of file events/ssml_mc20/include/ssml_mc20/particles.h.
top_index [2/2]
std::vector< int > jet::top_index = {}
Definition at line 127 of file events/bsm_4tops/include/bsm_4tops/particles.h.
Referenced by build().
Tops
std::vector<top*> jet::Tops = {}
Definition at line 124 of file events/bsm_4tops/include/bsm_4tops/particles.h.
The documentation for this class was generated from the following files:
events/bsm_4tops/include/bsm_4tops/particles.h
bsm_4tops/cxx/particles.cxx
jets.cxx