AnalysisG: analysis Class Reference
analysis Class Reference
< Inherits from the tools class for utility functions.
#include <analysis.h>
Public Member Functions
analysis ()
< Public access specifier for the following members.
~analysis ()
Destructor for the analysis class.
void add_samples (std::string path, std::string label)
Adds data samples to the analysis.
void add_selection_template (selection_template *sel)
Adds a selection template to the analysis.
void add_event_template (event_template *ev, std::string label)
Adds an event template to the analysis, associating it with a label.
void add_graph_template (graph_template *gr, std::string label)
Adds a graph template to the analysis, associating it with a label.
void add_metric_template (metric_template *mx, model_template *mdl)
Adds a metric template to the analysis, associating it with a model.
void add_model (model_template *model, optimizer_params_t *op, std::string run_name)
Adds a machine learning model and its optimizer parameters to the analysis for training.
void add_model (model_template *model, std::string run_name)
Adds a machine learning model to the analysis, typically for inference or metrics without explicit optimizer params here.
void attach_threads ()
Attaches or manages threads for parallel processing, if implemented.
void start ()
Starts the analysis execution.
std::map< std::string, std::vector< float > > progress ()
Retrieves the progress of different analysis tasks or model trainings.
std::map< std::string, std::string > progress_mode ()
Retrieves the current mode (e.g., training, evaluating) of different analysis tasks.
std::map< std::string, std::string > progress_report ()
Retrieves a textual report of the progress or status of different analysis tasks.
std::map< std::string, bool > is_complete ()
Checks if specific analysis tasks or model trainings are complete.
void set_prefix (std::string prefix)
Sets the prefix used in log messages from this instance.
std::string get_prefix ()
Returns the prefix currently used in log messages.
void Info (std::string msg, bool newline=true)
Outputs an info message.
void Warning (std::string msg, bool newline=true)
Outputs a warning message.
void Error (std::string msg, bool newline=true)
Outputs an error message.
void Debug (std::string msg, bool newline=true)
Outputs a debug message (only in debug mode).
void Message (std::string msg, std::string tag="", bool newline=true)
Outputs a message with custom formatting.
void set_debug_mode (bool dbg)
Enables or disables debug mode.
bool get_debug_mode ()
Returns the current status of debug mode.
void set_suppress_warning (bool sw)
Sets whether warnings should be suppressed.
bool get_suppress_warning ()
Returns the current warning suppression status.
void set_suppress_info (bool si)
Sets whether info messages should be suppressed.
bool get_suppress_info ()
Returns the current info message suppression status.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Static Public Member Functions
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Public Attributes
settings_t m_settings
Object holding the analysis-wide settings and configurations.
std::map< std::string, meta * > meta_data = {}
Map storing metadata objects, keyed by a string identifier (e.g., sample label). Initialized empty.
Protected Attributes
std::string prefix = ""
Prefix used in log messages from this instance. Initialized as empty string.
bool debug_mode = false
Flag indicating whether debug mode is enabled. Initialized as false.
bool suppress_warnings = false
Flag indicating whether warnings are suppressed. Initialized as false.
bool suppress_info = false
Flag indicating whether info messages are suppressed. Initialized as false.
Private Member Functions
void check_cache ()
< Private access specifier for the following members.
void build_project ()
Builds the project structure, possibly setting up directories or initial configurations.
void build_events ()
Builds or processes event data based on the added event templates and samples.
void build_selections ()
Builds or applies event selections based on the added selection templates.
void build_graphs ()
Builds graph representations of the event data based on the added graph templates.
void build_model_session ()
Sets up and configures machine learning model sessions for training or inference.
void build_inference ()
Sets up the environment for model inference (prediction).
bool build_metric ()
Builds or calculates metrics for evaluating model performance.
void build_metric_folds ()
Builds or calculates metrics across different data folds (e.g., for k-fold cross-validation).
void build_dataloader (bool training)
Builds or configures the data loader for training or evaluation.
void fetchtags ()
Fetches tags, possibly related to data versions, processing stages, or k-folds.
template<typename g >
void safe_clone (std::map< std::string, g * > *mp, g *in)
Templated helper method to safely clone objects (e.g., event or graph templates).
Static Private Member Functions
static int add_content (std::map< std::string, torch::Tensor * > *data, std::vector< variable_t > *content, int index, std::string prefx, TTree *tt=nullptr)
Static helper method to add content (features) to a data map from various sources.
static void add_content (std::map< std::string, torch::Tensor * > *data, std::vector< std::vector< torch::Tensor > > *buff, torch::Tensor *edge, torch::Tensor *node, torch::Tensor *batch, std::vector< long > mask)
Static helper method to add content (features) to a data map from a buffer of tensors.
static void execution (model_template *mdx, model_settings_t mds, std::vector< graph_t * > *data, size_t *prg, std::string output, std::vector< variable_t > *content, std::string *msg)
Static method to execute a model (training or inference) on a set of data.
static void execution_metric (metric_t *mt, size_t *prg, std::string *msg)
Static method to execute metric calculation.
static void initialize_loop (optimizer *op, int k, model_template *model, optimizer_params_t *config, model_report **rep)
Static method to initialize a training loop for an optimizer.
Private Attributes
bool started = false
Flag indicating whether the analysis has been started. Initialized to false.
std::map< std::string, std::string > file_labels = {}
Map to associate file paths or identifiers with user-defined labels. Initialized empty.
std::map< std::string, event_template * > event_labels = {}
Map storing event templates, keyed by a label. Initialized empty.
std::map< std::string, metric_template * > metric_names = {}
Map storing metric templates, keyed by a name or identifier. Initialized empty.
std::map< std::string, selection_template * > selection_names = {}
Map storing selection templates, keyed by a name or identifier. Initialized empty.
std::map< std::string, std::map< std::string, graph_template * > > graph_labels = {}
Map storing graph templates, nested by two string keys (e.g., category and label). Initialized empty.
std::vector< std::string > model_session_names = {}
Vector storing names of model sessions (e.g., for different training runs). Initialized empty.
std::map< std::string, model_template * > model_inference = {}
Map storing models configured for inference, keyed by a run name. Initialized empty.
std::map< std::string, model_template * > model_metrics = {}
Map storing models for which metrics are to be calculated, keyed by a run name. Initialized empty.
std::vector< std::tuple< model_template *, optimizer_params_t * > > model_sessions = {}
Vector storing tuples of model templates and their optimizer parameters for training sessions. Initialized empty.
std::map< std::string, optimizer * > trainer = {}
Map storing optimizer objects, keyed by a run name or model identifier. Initialized empty.
std::map< std::string, model_report * > reports = {}
Map storing model reports (e.g., training progress, evaluation results), keyed by a run name. Initialized empty.
std::vector< std::thread * > threads = {}
Vector to store pointers to std::thread objects for multithreaded execution. Initialized empty.
std::map< std::string, std::map< std::string, bool > > in_cache = {}
Map to track cache status for data, nested by two string keys (e.g., sample and data type). Initialized empty.
std::map< std::string, bool > skip_event_build = {}
Map to indicate whether event building should be skipped for certain samples/labels. Initialized empty.
std::map< std::string, std::string > graph_types = {}
Map to store types of graphs associated with labels. Initialized empty.
std::vector< folds_t > * tags = nullptr
Pointer to a vector of folds_t (tags for data partitioning/versioning). Initialized to nullptr.
dataloader * loader = nullptr
Pointer to the dataloader object. Initialized to nullptr.
sampletracer * tracer = nullptr
Pointer to the sampletracer object. Initialized to nullptr.
io * reader = nullptr
Pointer to the io object for data input. Initialized to nullptr.
Detailed Description
< Inherits from the tools class for utility functions.
Orchestrates the entire physics analysis workflow.
The analysis class is the main driver for performing a physics analysis. It manages the configuration, data processing, model execution, and result collection. Users interact with this class to define the analysis steps, add samples, specify models, and run the analysis.
Definition at line 36 of file analysis.h.
Constructor & Destructor Documentation
analysis()
analysis::analysis ()
< Public access specifier for the following members.
Constructor for the analysis class. Initializes a new analysis instance.
Definition at line 7 of file analysis.cxx.
References tools::absolute_path(), buildAll(), buildDict(), tools::create_path(), loader, tools::ls(), notification::prefix, reader, tags, tracer, and undef.
~analysis()
analysis::~analysis ()
Destructor for the analysis class.
Cleans up resources, such as deleting dynamically allocated objects.
Definition at line 36 of file analysis.cxx.
References tools::flush(), loader, metric_names, model_metrics, reader, tags, tracer, and trainer.
Member Function Documentation
absolute_path()
std::string tools::absolute_path (std::string path) static inherited
Converts a relative path to an absolute path.
Parameters
path The path to convert.
Returns
The absolute version of the path.
Definition at line 49 of file tools/cxx/io.cxx.
Referenced by analysis(), build_events(), io::check_root_file_paths(), and io::trigger_pcm().
add_content() [1/2]
void analysis::add_content (std::map< std::string, torch::Tensor * > * data, std::vector< std::vector< torch::Tensor > > * buff, torch::Tensor * edge, torch::Tensor * node, torch::Tensor * batch, std::vector< long > mask) static private
Static helper method to add content (features) to a data map from a buffer of tensors.
This version likely handles adding features from pre-loaded tensor buffers.
Parameters
data Pointer to a map where keys are feature names and values are torch::Tensor pointers.
buff Pointer to a vector of vectors of torch::Tensor (the buffer).
edge Pointer to a torch::Tensor object for edge features.
node Pointer to a torch::Tensor object for node features.
batch Pointer to a torch::Tensor object for batch information.
mask Vector of long integers representing a mask.
Definition at line 65 of file methods.cxx.
References index.
add_content() [2/2]
int analysis::add_content (std::map< std::string, torch::Tensor * > * data, std::vector< variable_t > * content, int index, std::string prefx, TTree * tt = nullptr) static private
Static helper method to add content (features) to a data map from various sources.
This version likely handles adding features from a TTree to torch::Tensor objects.
Parameters
data Pointer to a map where keys are feature names and values are torch::Tensor pointers.
content Pointer to a vector of variable_t structs describing the features to extract.
index Current event index or entry number.
prefx A prefix string for feature names.
tt Pointer to the TTree to read from (optional, defaults to nullptr).
Returns
An integer status code (e.g., 0 for success).
Definition at line 51 of file methods.cxx.
References index.
Referenced by build_inference(), and execution().
add_event_template()
void analysis::add_event_template (event_template * ev, std::string label)
Adds an event template to the analysis, associating it with a label.
Parameters
ev Pointer to an event_template object.
label A label to identify this event template.
Definition at line 52 of file analysis.cxx.
References event_labels.
add_graph_template()
void analysis::add_graph_template (graph_template * gr, std::string label)
Adds a graph template to the analysis, associating it with a label.
Parameters
gr Pointer to a graph_template object.
label A label to identify this graph template.
Definition at line 56 of file analysis.cxx.
References graph_labels.
add_metric_template()
void analysis::add_metric_template (metric_template * mx, model_template * mdl)
Adds a metric template to the analysis, associating it with a model.
Parameters
mx Pointer to a metric_template object.
mdl Pointer to a model_template object that this metric applies to.
Definition at line 64 of file analysis.cxx.
References metric_names, model_metrics, and safe_clone().
add_model() [1/2]
void analysis::add_model (model_template * model, optimizer_params_t * op, std::string run_name)
Adds a machine learning model and its optimizer parameters to the analysis for training.
Parameters
model Pointer to a model_template object.
op Pointer to an optimizer_params_t object containing optimizer settings.
run_name A name for this training run or model session.
Definition at line 70 of file analysis.cxx.
References model_session_names, and model_sessions.
add_model() [2/2]
void analysis::add_model (model_template * model, std::string run_name)
Adds a machine learning model to the analysis, typically for inference or metrics without explicit optimizer params here.
Parameters
model Pointer to a model_template object.
run_name A name for this model session (e.g., for inference or pre-trained model metrics).
Definition at line 76 of file analysis.cxx.
References model_inference, and model_session_names.
add_samples()
void analysis::add_samples (std::string path, std::string label)
Adds data samples to the analysis.
Parameters
path Path to the data sample (file or directory).
label A label to identify this sample.
Definition at line 48 of file analysis.cxx.
References file_labels.
add_selection_template()
void analysis::add_selection_template (selection_template * sel)
Adds a selection template to the analysis.
Parameters
sel Pointer to a selection_template object.
Definition at line 60 of file analysis.cxx.
References selection_names.
attach_threads()
void analysis::attach_threads ()
Attaches or manages threads for parallel processing, if implemented.
Attaches training threads for parallel execution.
This method starts training threads for each optimizer, allowing multiple models to train concurrently when appropriate hardware resources are available.
Definition at line 168 of file optimizer_build.cxx.
References threads.
build_dataloader()
void analysis::build_dataloader (bool training) private
Builds or configures the data loader for training or evaluation.
Parameters
training Boolean flag, true if for training, false if for evaluation/inference.
Definition at line 32 of file graph_build.cxx.
References settings_t::kfolds, loader, m_settings, tracer, settings_t::train_size, training, and settings_t::training_dataset.
Referenced by build_metric(), and start().
build_events()
void analysis::build_events () private
Builds or processes event data based on the added event templates and samples.
Definition at line 4 of file event_build.cxx.
References tools::absolute_path(), io::end(), event_labels, file_labels, m_settings, meta_data, reader, skip_event_build, tools::split(), tags, settings_t::threads, and tracer.
Referenced by start().
build_graphs()
void analysis::build_graphs () private
Builds graph representations of the event data based on the added graph templates.
Definition at line 3 of file graph_build.cxx.
References graph_labels, in_cache, tools::replace(), tools::split(), and tracer.
Referenced by start().
build_inference()
void analysis::build_inference () private
Sets up the environment for model inference (prediction).
Definition at line 5 of file inference_build.cxx.
References add_content(), settings_t::batch_size, tools::create_path(), execution(), i, index, loader, m_settings, model_inference, settings_t::output_path, tools::split(), settings_t::threads, and model_settings_t::weight_name.
Referenced by start().
build_metric()
bool analysis::build_metric () private
Builds or calculates metrics for evaluating model performance.
Returns
True if metric building was successful, false otherwise.
Definition at line 16 of file metric_build.cxx.
References build_dataloader(), build_project(), count(), notification::debug_mode, settings_t::debug_mode, evaluation, settings_t::evaluation, execution_metric(), loader, m_settings, metric_names, model_metrics, settings_t::threads, training, settings_t::training, validation, and settings_t::validation.
Referenced by start().
build_metric_folds()
void analysis::build_metric_folds () private
Builds or calculates metrics across different data folds (e.g., for k-fold cross-validation).
Definition at line 4 of file metric_build.cxx.
References settings_t::kfold, m_settings, metric_names, and model_metrics.
Referenced by start().
build_model_session()
void analysis::build_model_session () private
Sets up and configures machine learning model sessions for training or inference.
Builds model sessions for training and inference.
This method initializes model sessions based on configuration settings, sets up optimizers, and transfers data to appropriate devices. It prepares the environment for model training or inference by:
Creating device maps for data tensors
Setting up optimizers with appropriate parameters
Configuring k-fold cross-validation
Distributing training/validation data appropriately
Definition at line 25 of file optimizer_build.cxx.
References settings_t::debug_mode, initialize_loop(), settings_t::kfold, settings_t::kfolds, loader, m_settings, model_session_names, model_sessions, reports, settings_t::run_name, threads, and trainer.
Referenced by start().
build_project()
void analysis::build_project () private
Builds the project structure, possibly setting up directories or initial configurations.
Definition at line 81 of file analysis.cxx.
References tools::create_path(), m_settings, metric_names, model_session_names, model_sessions, and settings_t::output_path.
Referenced by build_metric(), and start().
build_selections()
void analysis::build_selections () private
Builds or applies event selections based on the added selection templates.
Definition at line 3 of file selection_build.cxx.
References m_settings, settings_t::output_path, selection_names, settings_t::selection_root, and tracer.
Referenced by start().
check_cache()
void analysis::check_cache () private
< Private access specifier for the following members.
Checks for cached data and potentially loads it to speed up processing.
Definition at line 97 of file analysis.cxx.
References count(), file_labels, settings_t::graph_cache, graph_labels, graph_types, tools::has_string(), in_cache, tools::ls(), m_settings, tools::replace(), skip_event_build, and tools::split().
Referenced by start().
create_path()
void tools::create_path (std::string path) static inherited
Creates a directory path, including parent directories if needed.
Parameters
path The directory path to create.
Definition at line 6 of file tools/cxx/io.cxx.
References f, and tools::split().
Referenced by analysis(), build_inference(), plotting::build_path(), build_project(), container::compile(), metrics::dump_mass_plots(), metric_template::execute(), metrics::generic_painter(), start(), io::start(), and io::trigger_pcm().
Debug()
void notification::Debug (std::string msg, bool newline = true) inherited
Outputs a debug message (only in debug mode).
Parameters
msg The debug message to output.
newline Whether to append a newline (default: true).
delete_path()
void tools::delete_path (std::string path) static inherited
Deletes a directory path and its contents.
Parameters
path The directory path to delete.
Definition at line 22 of file tools/cxx/io.cxx.
ends_with()
bool tools::ends_with (std::string * inpt, std::string val) static inherited
Checks if a string ends with a specific substring.
Parameters
inpt Pointer to the string to check.
val The substring to check for at the end.
Returns
True if the string ends with the substring, false otherwise.
Definition at line 71 of file strings.cxx.
References l.
Referenced by plotting::build_path(), io::check_root_file_paths(), dataloader::dump_graphs(), tools::ls(), meta::parse_json(), io::scan_keys(), and start().
Error()
void notification::Error (std::string msg, bool newline = true) inherited
Outputs an error message.
Parameters
msg The error message to output.
newline Whether to append a newline (default: true).
execution()
void analysis::execution (model_template * mdx, model_settings_t mds, std::vector< graph_t * > * data, size_t * prg, std::string output, std::vector< variable_t > * content, std::string * msg) static private
Static method to execute a model (training or inference) on a set of data.
Parameters
mdx Pointer to the model_template to be executed.
mds model_settings_t object containing settings for this model execution.
data Pointer to a vector of graph_t objects (input data).
prg Pointer to a size_t variable for progress tracking.
output Path or identifier for the output.
content Pointer to a vector of variable_t for output content description.
msg Pointer to a string for status messages.
Definition at line 88 of file methods.cxx.
References add_content(), f, i, index, l, model_settings_t::tree_name, and model_settings_t::weight_name.
Referenced by build_inference().
execution_metric()
void analysis::execution_metric (metric_t * mt, size_t * prg, std::string * msg) static private
Static method to execute metric calculation.
Parameters
mt Pointer to a metric_t object (likely containing metric definitions and results).
prg Pointer to a size_t variable for progress tracking.
msg Pointer to a string for status messages.
Definition at line 215 of file methods.cxx.
Referenced by build_metric().
extract()
template<typename C , typename T > static void tools::extract (std::vector< T > * prop, std::vector< C * > * src, void(*)(T *, C *) get_prop) inline static inherited
Extracts a specific property from a vector of objects into a new vector.
Template Parameters
C The type of objects in the source vector.
T The type of the property to extract.
Parameters
prop Pointer to the output vector to fill with property values.
src Pointer to the source vector of objects.
get_prop Function pointer to extract the property from an object.
< Clear the properties vector.
< Reserve space for the property values.
< Loop through each object in the source vector.
< Create a default-initialized property variable.
< Call the provided function to extract the property.
< Add the property value to the output vector.
Definition at line 216 of file tools.h.
fetchtags()
void analysis::fetchtags () private
Fetches tags, possibly related to data versions, processing stages, or k-folds.
Definition at line 144 of file analysis.cxx.
References m_settings, read(), start(), tags, and settings_t::training_dataset.
Referenced by start().
flush()
template<typename T > static void tools::flush (std::vector< T * > * inpt) inline static inherited
Empties a vector and all objects it points to.
Template Parameters
T The type of pointers in the vector.
Parameters
inpt Pointer to the vector to empty.
< Loop through all elements in the vector.
< Delete the object the pointer points to.
< Set the pointer to nullptr to avoid dangling pointers.
< Clear the vector.
Definition at line 167 of file tools.h.
Referenced by ~analysis(), dataloader::~dataloader(), sampletracer::compile_objects(), and io::root_end().
get_debug_mode()
bool notification::get_debug_mode () inherited
Returns the current status of debug mode.
Returns
Boolean indicating whether debug mode is enabled (true) or disabled (false).
get_prefix()
std::string notification::get_prefix () inherited
Returns the prefix currently used in log messages.
Returns
The current prefix string.
get_suppress_info()
bool notification::get_suppress_info () inherited
Returns the current info message suppression status.
Returns
Boolean indicating whether info messages are suppressed (true) or shown (false).
get_suppress_warning()
bool notification::get_suppress_warning () inherited
Returns the current warning suppression status.
Returns
Boolean indicating whether warnings are suppressed (true) or shown (false).
has_string()
bool tools::has_string (std::string * inpt, std::string trg) static inherited
Checks if a string contains a specific substring.
Parameters
inpt Pointer to the string to check.
trg The substring to search for.
Returns
True if the substring is found, false otherwise.
Definition at line 65 of file strings.cxx.
References f.
Referenced by check_cache(), meta::compiler(), metrics::generic_painter(), dataloader::restore_graphs_(), meta::scan_sow(), model_template::set_device(), and metric_template::set_run_name().
has_value()
bool tools::has_value (std::vector< std::string > * data, std::string trg) static inherited
Checks if a vector of strings contains a specific string.
Parameters
data Pointer to the vector to search.
trg The string to search for.
Returns
True if the string is found in the vector, false otherwise.
Definition at line 77 of file strings.cxx.
Referenced by io::scan_keys().
Info()
void notification::Info (std::string msg, bool newline = true) inherited
Outputs an info message.
Parameters
msg The message to output.
newline Whether to append a newline (default: true).
initialize_loop()
void analysis::initialize_loop (optimizer * op, int k, model_template * model, optimizer_params_t * config, model_report ** rep) static private
Static method to initialize a training loop for an optimizer.
Parameters
op Pointer to the optimizer object.
k The k-fold index or a similar loop identifier.
model Pointer to the model_template being trained.
config Pointer to the optimizer_params_t for this training session.
rep Double pointer to a model_report object to store training reports.
Definition at line 7 of file methods.cxx.
References settings_t::continue_training, settings_t::epochs, index, tools::is_file(), loader, m_settings, and reports.
Referenced by build_model_session().
is_complete()
std::map< std::string, bool > analysis::is_complete ()
Checks if specific analysis tasks or model trainings are complete.
Checks if training is complete for all models.
Returns
A map where keys are task/model names and values are booleans (true if complete, false otherwise).
A map of model names to boolean values indicating completion status.
This method determines whether each model training session has completed its specified number of epochs or met other completion criteria.
Definition at line 155 of file optimizer_build.cxx.
References is_complete(), and reports.
Referenced by is_complete().
is_file()
bool tools::is_file (std::string path) static inherited
Checks if a path refers to an existing file.
Parameters
path The path to check.
Returns
True if the path is a file and exists, false otherwise.
Definition at line 30 of file tools/cxx/io.cxx.
Referenced by io::check_root_file_paths(), initialize_loop(), metric_template::set_run_name(), and io::start().
ls()
std::vector< std::string > tools::ls (std::string path, std::string ext = "") static inherited
Lists files in a directory, optionally filtered by extension.
Parameters
path The directory to search.
ext File extension filter. If empty, all files are listed.
Returns
A vector of filenames in the directory.
Definition at line 35 of file tools/cxx/io.cxx.
References tools::ends_with(), and tools::split().
Referenced by analysis(), check_cache(), io::check_root_file_paths(), dataloader::restore_graphs(), and io::trigger_pcm().
Message()
void notification::Message (std::string msg, std::string tag = "", bool newline = true) inherited
Outputs a message with custom formatting.
Parameters
msg The message to output.
tag A custom tag to prepend to the message.
newline Whether to append a newline (default: true).
progress()
std::map< std::string, std::vector< float > > analysis::progress ()
Retrieves the progress of different analysis tasks or model trainings.
Retrieves training progress information for all models.
Returns
A map where keys are task/model names and values are vectors of floats representing progress (e.g., percentage or epoch number).
A map of model names to vectors of float values representing progress metrics.
This method collects progress information from all active model training sessions, including metrics like loss and accuracy values over time.
Definition at line 96 of file optimizer_build.cxx.
References progress(), and reports.
Referenced by progress().
progress_mode()
std::map< std::string, std::string > analysis::progress_mode ()
Retrieves the current mode (e.g., training, evaluating) of different analysis tasks.
Retrieves the current training mode for all models.
Returns
A map where keys are task/model names and values are strings describing the mode.
A map of model names to strings indicating current training mode.
This method provides information about the current operation mode of each training session (e.g., "training", "validation", "inference").
Definition at line 115 of file optimizer_build.cxx.
References reports.
progress_report()
std::map< std::string, std::string > analysis::progress_report ()
Retrieves a textual report of the progress or status of different analysis tasks.
Retrieves detailed progress reports for all models.
Returns
A map where keys are task/model names and values are strings containing progress reports.
A map of model names to report strings.
This method provides detailed textual progress reports for each training session, including current metrics, epoch information, and time estimates.
Definition at line 135 of file optimizer_build.cxx.
References reports.
put()
template<typename g > static void tools::put (std::vector< g * > * out, std::vector< g * > * src, std::vector< int > * trg) inline static inherited
Fills a vector with pointers from another vector based on a selection index.
Template Parameters
g The type of objects being pointed to.
Parameters
out Pointer to the output vector to fill.
src Pointer to the source vector to select from.
trg Pointer to a vector of indices for selection.
< Clear the output vector.
< Reserve space for the output elements.
< Loop through each selected index.
< Get the object at the selected index.
< Add it to the output vector.
< Mark the object as in use.
Definition at line 197 of file tools.h.
Referenced by dataloader::get_k_train_set(), dataloader::get_k_validation_set(), and dataloader::get_test_set().
rename()
void tools::rename (std::string start, std::string target) static inherited
Renames a file or directory.
Parameters
start The original path.
target The new path.
Definition at line 18 of file tools/cxx/io.cxx.
Referenced by dataloader::dump_graphs().
replace()
void tools::replace (std::string * in, std::string repl_str, std::string repl_with) static inherited
Replaces all occurrences of a substring in a string.
Parameters
in Pointer to the string to modify.
repl_str The substring to replace.
repl_with The replacement string.
Definition at line 5 of file strings.cxx.
Referenced by build_graphs(), check_cache(), dataloader::dump_graphs(), meta::get_campaign(), meta::parse_json(), and start().
safe_clone()
template<typename g > void analysis::safe_clone (std::map< std::string, g * > * mp, g * in) inline private
Templated helper method to safely clone objects (e.g., event or graph templates).
Template Parameters
g The type of the object to clone.
Parameters
mp Pointer to a map where the cloned object might be stored or looked up.
in Pointer to the object to be cloned.
Definition at line 253 of file analysis.h.
References count().
Referenced by add_metric_template().
set_debug_mode()
void notification::set_debug_mode (bool dbg) inherited
Enables or disables debug mode.
Parameters
dbg Boolean flag, set to true to enable debug messages, false to disable.
set_prefix()
void notification::set_prefix (std::string prefix) inherited
Sets the prefix used in log messages from this instance.
Parameters
prefix The string to use as a prefix for log messages.
set_suppress_info()
void notification::set_suppress_info (bool si) inherited
Sets whether info messages should be suppressed.
Parameters
si Boolean flag, set to true to suppress info messages, false to show them.
set_suppress_warning()
void notification::set_suppress_warning (bool sw) inherited
Sets whether warnings should be suppressed.
Parameters
sw Boolean flag, set to true to suppress warnings, false to show them.
split()
std::vector< std::string > tools::split (std::string inpt, std::string del) inherited
Splits a string into a vector of substrings based on a delimiter.
Parameters
inpt The input string to split.
del The delimiter.
Returns
A vector of substrings.
Definition at line 23 of file strings.cxx.
References index.
Referenced by build_events(), build_graphs(), build_inference(), event_template::build_mapping(), check_cache(), container::compile(), sampletracer::compile_objects(), meta::compiler(), tools::create_path(), dataloader::dump_graphs(), meta::hash(), tools::ls(), graph_t::meta_deserialize(), dataloader::restore_graphs_(), io::root_begin(), model_template::set_device(), metric_template::set_run_name(), metric_template::set_variables(), and start().
start()
void analysis::start ()
Starts the analysis execution.
This method triggers the main analysis loop, including data processing, model training/inference, etc.
Definition at line 153 of file analysis.cxx.
References settings_t::build_cache, build_dataloader(), build_events(), build_graphs(), build_inference(), build_metric(), build_metric_folds(), build_model_session(), build_project(), build_selections(), check_cache(), tools::create_path(), settings_t::debug_mode, tools::ends_with(), event_labels, fetchtags(), file_labels, settings_t::graph_cache, graph_labels, graph_types, loader, m_settings, meta_data, model_inference, model_sessions, settings_t::output_path, settings_t::pretagevents, reader, tools::replace(), selection_names, tools::split(), started, settings_t::threads, and tracer.
Referenced by fetchtags().
sum()
template<typename g > g tools::sum (std::vector< g > * inpt) inline inherited
Sums the elements of a vector.
Template Parameters
g The type of elements in the vector.
Parameters
inpt Pointer to the vector to sum.
Returns
The sum of all elements.
< Initialize the output variable.
< Return the sum.
Definition at line 183 of file tools.h.
Referenced by metrics::add_th1f_accuracy(), sampletracer::compile_objects(), particle_template::DeltaR(), graph_template::double_neutrino(), grift::forward(), recursivegraphneuralnetwork::forward(), matching::match_obj(), and grift::message().
to_string() [1/2]
std::string tools::to_string (double val) static inherited
Converts a double value to a string with standard precision.
Parameters
val The double value to convert.
Returns
The string representation of the value.
Definition at line 59 of file strings.cxx.
Referenced by dataloader::generate_kfold_set(), dataloader::generate_test_set(), particle_template::get_hash(), topefficiency::region(), dataloader::restore_dataset(), event_template::set_hash(), selection_template::set_hash(), parton::strategy(), topjets::strategy(), toptruthjets::strategy(), and parton::top_mass_contribution().
to_string() [2/2]
std::string tools::to_string (double val, int prec) static inherited
Converts a double value to a string with specified precision.
Parameters
val The double value to convert.
prec The number of decimal places to consider.
Returns
The string representation of the value.
Definition at line 91 of file strings.cxx.
trim()
std::string tools::trim (std::string s) inherited
Removes whitespace from the beginning and end of a string.
Parameters
s The string to trim.
Returns
The trimmed string.
type_name()
template<typename T > std::string tools::type_name () inline inherited
Gets the type name of a variable as a string (for debugging).
Template Parameters
T The type to get the name of.
Returns
The name of the type as a string.
< Gets the type name via RTTI.
< Returns the type name.
Definition at line 155 of file tools.h.
Referenced by event_template::build_mapping().
Warning()
void notification::Warning (std::string msg, bool newline = true) inherited
Outputs a warning message.
Parameters
msg The warning message to output.
newline Whether to append a newline (default: true).
Referenced by io::read(), io::read(), io::write(), and io::write().
Member Data Documentation
debug_mode
bool notification::debug_mode = false protected inherited
Flag indicating whether debug mode is enabled. Initialized as false.
Definition at line 127 of file notification.h.
Referenced by build_metric().
event_labels
std::map<std::string, event_template*> analysis::event_labels = {} private
Map storing event templates, keyed by a label. Initialized empty.
Definition at line 260 of file analysis.h.
Referenced by add_event_template(), build_events(), and start().
file_labels
std::map<std::string, std::string> analysis::file_labels = {} private
Map to associate file paths or identifiers with user-defined labels. Initialized empty.
Definition at line 259 of file analysis.h.
Referenced by add_samples(), build_events(), check_cache(), and start().
graph_labels
std::map<std::string, std::map<std::string, graph_template*> > analysis::graph_labels = {} private
Map storing graph templates, nested by two string keys (e.g., category and label). Initialized empty.
Definition at line 263 of file analysis.h.
Referenced by add_graph_template(), build_graphs(), check_cache(), and start().
graph_types
std::map<std::string, std::string> analysis::graph_types = {} private
Map to store types of graphs associated with labels. Initialized empty.
Definition at line 276 of file analysis.h.
Referenced by check_cache(), and start().
in_cache
std::map<std::string, std::map<std::string, bool> > analysis::in_cache = {} private
Map to track cache status for data, nested by two string keys (e.g., sample and data type). Initialized empty.
Definition at line 274 of file analysis.h.
Referenced by build_graphs(), and check_cache().
loader
dataloader* analysis::loader = nullptr private
Pointer to the dataloader object. Initialized to nullptr.
Definition at line 279 of file analysis.h.
Referenced by analysis(), ~analysis(), build_dataloader(), build_inference(), build_metric(), build_model_session(), initialize_loop(), and start().
m_settings
settings_t analysis::m_settings
Object holding the analysis-wide settings and configurations.
Definition at line 125 of file analysis.h.
Referenced by build_dataloader(), build_events(), build_inference(), build_metric(), build_metric_folds(), build_model_session(), build_project(), build_selections(), check_cache(), fetchtags(), initialize_loop(), and start().
meta_data
std::map<std::string, meta*> analysis::meta_data = {}
Map storing metadata objects, keyed by a string identifier (e.g., sample label). Initialized empty.
Definition at line 126 of file analysis.h.
Referenced by build_events(), and start().
metric_names
std::map<std::string, metric_template*> analysis::metric_names = {} private
Map storing metric templates, keyed by a name or identifier. Initialized empty.
Definition at line 261 of file analysis.h.
Referenced by ~analysis(), add_metric_template(), build_metric(), build_metric_folds(), and build_project().
model_inference
std::map<std::string, model_template*> analysis::model_inference = {} private
Map storing models configured for inference, keyed by a run name. Initialized empty.
Definition at line 266 of file analysis.h.
Referenced by add_model(), build_inference(), and start().
model_metrics
std::map<std::string, model_template*> analysis::model_metrics = {} private
Map storing models for which metrics are to be calculated, keyed by a run name. Initialized empty.
Definition at line 267 of file analysis.h.
Referenced by ~analysis(), add_metric_template(), build_metric(), and build_metric_folds().
model_session_names
std::vector<std::string> analysis::model_session_names = {} private
Vector storing names of model sessions (e.g., for different training runs). Initialized empty.
Definition at line 265 of file analysis.h.
Referenced by add_model(), add_model(), build_model_session(), and build_project().
model_sessions
std::vector<std::tuple<model_template*, optimizer_params_t*> > analysis::model_sessions = {} private
Vector storing tuples of model templates and their optimizer parameters for training sessions. Initialized empty.
Definition at line 268 of file analysis.h.
Referenced by add_model(), build_model_session(), build_project(), and start().
prefix
std::string notification::prefix = "" protected inherited
Prefix used in log messages from this instance. Initialized as empty string.
Definition at line 126 of file notification.h.
Referenced by analysis(), dataloader::dataloader(), io::io(), meta::meta(), optimizer::optimizer(), and metric_template::set_name().
reader
io* analysis::reader = nullptr private
Pointer to the io object for data input. Initialized to nullptr.
Definition at line 281 of file analysis.h.
Referenced by analysis(), ~analysis(), build_events(), and start().
reports
std::map<std::string, model_report*> analysis::reports = {} private
Map storing model reports (e.g., training progress, evaluation results), keyed by a run name. Initialized empty.
Definition at line 271 of file analysis.h.
Referenced by build_model_session(), initialize_loop(), is_complete(), progress(), progress_mode(), and progress_report().
selection_names
std::map<std::string, selection_template*> analysis::selection_names = {} private
Map storing selection templates, keyed by a name or identifier. Initialized empty.
Definition at line 262 of file analysis.h.
Referenced by add_selection_template(), build_selections(), and start().
skip_event_build
std::map<std::string, bool> analysis::skip_event_build = {} private
Map to indicate whether event building should be skipped for certain samples/labels. Initialized empty.
Definition at line 275 of file analysis.h.
Referenced by build_events(), and check_cache().
started
bool analysis::started = false private
Flag indicating whether the analysis has been started. Initialized to false.
Definition at line 177 of file analysis.h.
Referenced by start().
suppress_info
bool notification::suppress_info = false protected inherited
Flag indicating whether info messages are suppressed. Initialized as false.
Definition at line 129 of file notification.h.
suppress_warnings
bool notification::suppress_warnings = false protected inherited
Flag indicating whether warnings are suppressed. Initialized as false.
Definition at line 128 of file notification.h.
tags
std::vector<folds_t>* analysis::tags = nullptr private
Pointer to a vector of folds_t (tags for data partitioning/versioning). Initialized to nullptr.
Definition at line 278 of file analysis.h.
Referenced by analysis(), ~analysis(), build_events(), and fetchtags().
threads
std::vector<std::thread*> analysis::threads = {} private
Vector to store pointers to std::thread objects for multithreaded execution. Initialized empty.
Definition at line 272 of file analysis.h.
Referenced by attach_threads(), and build_model_session().
tracer
sampletracer* analysis::tracer = nullptr private
Pointer to the sampletracer object. Initialized to nullptr.
Definition at line 280 of file analysis.h.
Referenced by analysis(), ~analysis(), build_dataloader(), build_events(), build_graphs(), build_selections(), and start().
trainer
std::map<std::string, optimizer*> analysis::trainer = {} private
Map storing optimizer objects, keyed by a run name or model identifier. Initialized empty.
Definition at line 270 of file analysis.h.
Referenced by ~analysis(), and build_model_session().
The documentation for this class was generated from the following files:
analysis.h
analysis.cxx
event_build.cxx
graph_build.cxx
inference_build.cxx
methods.cxx
metric_build.cxx
optimizer_build.cxx
selection_build.cxx