AnalysisG: plotting Class Reference
plotting Class Reference
Provides functionality for creating and managing visualizations.
#include <plotting.h>
Public Member Functions
plotting ()
Constructor for the plotting class.
~plotting ()
Destructor for the plotting class.
std::string build_path ()
Builds a complete path for output files based on configured settings.
float get_max (std::string dim)
Gets the maximum value for a specified dimension.
float get_min (std::string dim)
Gets the minimum value for a specified dimension.
float sum_of_weights ()
Calculates the sum of weights for normalization.
void build_error ()
Builds error bars or uncertainty bands for plots.
std::tuple< float, float > mean_stdev (std::vector< float > *data)
Calculates the mean and standard deviation of a data vector.
void build_ROC (std::string name, int kfold, std::vector< int > *labels, std::vector< std::vector< double > > *scores)
Builds a Receiver Operating Characteristic (ROC) curve from classification results.
std::vector< roc_t > get_ROC ()
Gets the computed ROC curve data.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
void set_prefix (std::string prefix)
Sets the prefix used in log messages from this instance.
std::string get_prefix ()
Returns the prefix currently used in log messages.
void Info (std::string msg, bool newline=true)
Outputs an info message.
void Warning (std::string msg, bool newline=true)
Outputs a warning message.
void Error (std::string msg, bool newline=true)
Outputs an error message.
void Debug (std::string msg, bool newline=true)
Outputs a debug message (only in debug mode).
void Message (std::string msg, std::string tag="", bool newline=true)
Outputs a message with custom formatting.
void set_debug_mode (bool dbg)
Enables or disables debug mode.
bool get_debug_mode ()
Returns the current status of debug mode.
void set_suppress_warning (bool sw)
Sets whether warnings should be suppressed.
bool get_suppress_warning ()
Returns the current warning suppression status.
void set_suppress_info (bool si)
Sets whether info messages should be suppressed.
bool get_suppress_info ()
Returns the current info message suppression status.
Static Public Member Functions
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Public Attributes
std::string extension = ".pdf"
File extension for output files (e.g., ".pdf", ".png"). Default is ".pdf".
std::string filename = "untitled"
Base filename for output files. Default is "untitled".
std::string output_path = "./Figures"
Directory path for output files. Default is "./Figures".
float x_min = 0
Minimum value for x-axis. Default is 0.
float y_min = 0
Minimum value for y-axis. Default is 0.
float x_max = 0
Maximum value for x-axis. Default is 0 (auto-determined if not set).
float y_max = 0
Maximum value for y-axis. Default is 0 (auto-determined if not set).
int x_bins = 100
Number of bins for x-axis. Default is 100.
int y_bins = 100
Number of bins for y-axis. Default is 100.
bool errors = false
Flag to enable/disable error bars. Default is false.
bool counts = false
Flag to enable/disable counts display. Default is false.
std::string style = "ROOT"
Plot style. Default is "ROOT".
std::string title = "untitled"
Plot title. Default is "untitled".
std::string ytitle = "y-axis"
Y-axis title. Default is "y-axis".
std::string xtitle = "x-axis"
X-axis title. Default is "x-axis".
std::string histfill = "fill"
Histogram fill style. Default is "fill".
std::string overflow = "sum"
Overflow handling. Default is "sum".
std::string marker = "."
Marker style. Default is ".".
std::string hatch = ""
Hatch style. Default is empty.
std::string linestyle = "-"
Line style. Default is "-".
std::string color = ""
Default color for plots. Default is empty.
std::vector< std::string > colors = {}
List of colors for multi-series plots.
bool stack = false
Flag to enable/disable stacking. Default is false.
bool density = false
Flag to enable/disable density normalization. Default is false.
bool x_logarithmic = false
Flag to enable/disable logarithmic x-axis. Default is false.
bool y_logarithmic = false
Flag to enable/disable logarithmic y-axis. Default is false.
float line_width = 0.1
Line width for plots. Default is 0.1.
float cap_size = 1.0
Cap size for error bars. Default is 1.0.
float alpha = 0.4
Transparency level for plots. Default is 0.4.
float x_step = -1
Step size for x-axis. Default is -1 (auto-determined).
float y_step = -1
Step size for y-axis. Default is -1 (auto-determined).
float font_size = 10
Font size for text. Default is 10.
float axis_size = 12.5
Font size for axis labels. Default is 12.5.
float legend_size = 10
Font size for legend. Default is 10.
float title_size = 10
Font size for title. Default is 10.
bool use_latex = true
Flag to enable/disable LaTeX rendering. Default is true.
int dpi = 400
Dots per inch for output resolution. Default is 400.
float xscaling = 1.25*6.4
Scaling factor for x-axis. Default is 1.25*6.4.
float yscaling = 1.25*4.8
Scaling factor for y-axis. Default is 1.25*4.8.
bool auto_scale = true
Flag to enable/disable auto-scaling. Default is true.
std::vector< float > x_data = {}
Data for x-axis.
std::vector< float > y_data = {}
Data for y-axis.
std::map< std::string, std::map< int, std::vector< std::vector< double > > * > > roc_data = {}
ROC data storage.
std::map< std::string, std::map< int, std::vector< std::vector< int > > * > > labels = {}
Labels storage.
std::vector< float > y_error_up = {}
Upper error values for y-axis.
std::vector< float > y_error_down = {}
Lower error values for y-axis.
std::unordered_map< std::string, float > x_labels = {}
Labels for x-axis.
std::unordered_map< std::string, float > y_labels = {}
Labels for y-axis.
std::vector< float > variable_x_bins = {}
Variable binning for x-axis.
std::vector< float > variable_y_bins = {}
Variable binning for y-axis.
std::vector< float > weights = {}
Weights for data points.
float cross_section = -1
Cross-section value. Default is -1.
float integrated_luminosity = 140.1
Integrated luminosity in fb-1. Default is 140.1.
Protected Attributes
std::string prefix = ""
Prefix used in log messages from this instance. Initialized as empty string.
bool debug_mode = false
Flag indicating whether debug mode is enabled. Initialized as false.
bool suppress_warnings = false
Flag indicating whether warnings are suppressed. Initialized as false.
bool suppress_info = false
Flag indicating whether info messages are suppressed. Initialized as false.
Private Member Functions
template<typename g >
std::vector< std::vector< g > > * generate (size_t x, size_t y)
Generates a 2D vector of specified dimensions and initializes it with zeros.
Detailed Description
Provides functionality for creating and managing visualizations.
The plotting class handles various aspects of data visualization, including creating plots, managing output formats and paths, computing statistics for plotting, and specialized physics visualization techniques like ROC curves for classifier evaluation. It inherits from both tools (for utility functions) and notification (for messaging).
Definition at line 47 of file plotting.h.
Constructor & Destructor Documentation
plotting()
plotting::plotting ()
Constructor for the plotting class.
Initializes a new plotting instance with default settings.
Definition at line 10 of file plotting.cxx.
~plotting()
plotting::~plotting ()
Destructor for the plotting class.
Cleans up any resources used by the plotting system.
Definition at line 11 of file plotting.cxx.
References labels, and roc_data.
Member Function Documentation
absolute_path()
std::string tools::absolute_path (std::string path) static inherited
Converts a relative path to an absolute path.
Parameters
path The path to convert.
Returns
The absolute version of the path.
Definition at line 49 of file tools/cxx/io.cxx.
Referenced by analysis::analysis(), analysis::build_events(), io::check_root_file_paths(), and io::trigger_pcm().
build_error()
void plotting::build_error ()
Builds error bars or uncertainty bands for plots.
Definition at line 65 of file plotting.cxx.
References mean_stdev(), x_data, y_data, y_error_down, and y_error_up.
build_path()
std::string plotting::build_path ()
Builds a complete path for output files based on configured settings.
Returns
The constructed path as a string.
Definition at line 22 of file plotting.cxx.
References tools::create_path(), tools::ends_with(), extension, filename, and output_path.
build_ROC()
void plotting::build_ROC (std::string name, int kfold, std::vector< int > * labels, std::vector< std::vector< double > > * scores)
Builds a Receiver Operating Characteristic (ROC) curve from classification results.
Parameters
name The name of the ROC curve (for identification and labeling).
kfold The k-fold cross-validation index, if applicable.
labels Pointer to a vector of true labels (0 or 1).
scores Pointer to a vector of classifier scores/probabilities.
Definition at line 90 of file plotting.cxx.
References count(), labels, and roc_data.
create_path()
void tools::create_path (std::string path) static inherited
Creates a directory path, including parent directories if needed.
Parameters
path The directory path to create.
Definition at line 6 of file tools/cxx/io.cxx.
References f, and tools::split().
Referenced by analysis::analysis(), analysis::build_inference(), build_path(), analysis::build_project(), container::compile(), metrics::dump_mass_plots(), metric_template::execute(), metrics::generic_painter(), analysis::start(), io::start(), and io::trigger_pcm().
Debug()
void notification::Debug (std::string msg, bool newline = true) inherited
Outputs a debug message (only in debug mode).
Parameters
msg The debug message to output.
newline Whether to append a newline (default: true).
delete_path()
void tools::delete_path (std::string path) static inherited
Deletes a directory path and its contents.
Parameters
path The directory path to delete.
Definition at line 22 of file tools/cxx/io.cxx.
ends_with()
bool tools::ends_with (std::string * inpt, std::string val) static inherited
Checks if a string ends with a specific substring.
Parameters
inpt Pointer to the string to check.
val The substring to check for at the end.
Returns
True if the string ends with the substring, false otherwise.
Definition at line 71 of file strings.cxx.
References l.
Referenced by build_path(), io::check_root_file_paths(), dataloader::dump_graphs(), tools::ls(), meta::parse_json(), io::scan_keys(), and analysis::start().
Error()
void notification::Error (std::string msg, bool newline = true) inherited
Outputs an error message.
Parameters
msg The error message to output.
newline Whether to append a newline (default: true).
extract()
template<typename C , typename T > static void tools::extract (std::vector< T > * prop, std::vector< C * > * src, void(*)(T *, C *) get_prop) inline static inherited
Extracts a specific property from a vector of objects into a new vector.
Template Parameters
C The type of objects in the source vector.
T The type of the property to extract.
Parameters
prop Pointer to the output vector to fill with property values.
src Pointer to the source vector of objects.
get_prop Function pointer to extract the property from an object.
< Clear the properties vector.
< Reserve space for the property values.
< Loop through each object in the source vector.
< Create a default-initialized property variable.
< Call the provided function to extract the property.
< Add the property value to the output vector.
Definition at line 216 of file tools.h.
flush()
template<typename T > static void tools::flush (std::vector< T * > * inpt) inline static inherited
Empties a vector and all objects it points to.
Template Parameters
T The type of pointers in the vector.
Parameters
inpt Pointer to the vector to empty.
< Loop through all elements in the vector.
< Delete the object the pointer points to.
< Set the pointer to nullptr to avoid dangling pointers.
< Clear the vector.
Definition at line 167 of file tools.h.
Referenced by analysis::~analysis(), dataloader::~dataloader(), sampletracer::compile_objects(), and io::root_end().
generate()
template<typename g > std::vector< std::vector< g > > * plotting::generate (size_t x, size_t y) inline private
Generates a 2D vector of specified dimensions and initializes it with zeros.
Template Parameters
g The data type of the elements in the vector.
Parameters
x The number of rows.
y The number of columns.
Returns
A pointer to the generated 2D vector.
Definition at line 195 of file plotting.h.
get_debug_mode()
bool notification::get_debug_mode () inherited
Returns the current status of debug mode.
Returns
Boolean indicating whether debug mode is enabled (true) or disabled (false).
get_max()
float plotting::get_max (std::string dim)
Gets the maximum value for a specified dimension.
Parameters
dim The dimension to find the maximum for (e.g., "x", "y", "pt").
Returns
The maximum value as a float.
Definition at line 32 of file plotting.cxx.
References x_data, and y_data.
get_min()
float plotting::get_min (std::string dim)
Gets the minimum value for a specified dimension.
Parameters
dim The dimension to find the minimum for (e.g., "x", "y", "pt").
Returns
The minimum value as a float.
Definition at line 38 of file plotting.cxx.
References x_data, and y_data.
get_prefix()
std::string notification::get_prefix () inherited
Returns the prefix currently used in log messages.
Returns
The current prefix string.
get_ROC()
std::vector< roc_t > plotting::get_ROC ()
Gets the computed ROC curve data.
Returns
A vector of roc_t structures containing the ROC curve information.
Definition at line 124 of file plotting.cxx.
References roc_t::cls, roc_t::kfold, labels, roc_t::model, roc_data, roc_t::scores, and roc_t::truth.
get_suppress_info()
bool notification::get_suppress_info () inherited
Returns the current info message suppression status.
Returns
Boolean indicating whether info messages are suppressed (true) or shown (false).
get_suppress_warning()
bool notification::get_suppress_warning () inherited
Returns the current warning suppression status.
Returns
Boolean indicating whether warnings are suppressed (true) or shown (false).
has_string()
bool tools::has_string (std::string * inpt, std::string trg) static inherited
Checks if a string contains a specific substring.
Parameters
inpt Pointer to the string to check.
trg The substring to search for.
Returns
True if the substring is found, false otherwise.
Definition at line 65 of file strings.cxx.
References f.
Referenced by analysis::check_cache(), meta::compiler(), metrics::generic_painter(), dataloader::restore_graphs_(), meta::scan_sow(), model_template::set_device(), and metric_template::set_run_name().
has_value()
bool tools::has_value (std::vector< std::string > * data, std::string trg) static inherited
Checks if a vector of strings contains a specific string.
Parameters
data Pointer to the vector to search.
trg The string to search for.
Returns
True if the string is found in the vector, false otherwise.
Definition at line 77 of file strings.cxx.
Referenced by io::scan_keys().
Info()
void notification::Info (std::string msg, bool newline = true) inherited
Outputs an info message.
Parameters
msg The message to output.
newline Whether to append a newline (default: true).
is_file()
bool tools::is_file (std::string path) static inherited
Checks if a path refers to an existing file.
Parameters
path The path to check.
Returns
True if the path is a file and exists, false otherwise.
Definition at line 30 of file tools/cxx/io.cxx.
Referenced by io::check_root_file_paths(), analysis::initialize_loop(), metric_template::set_run_name(), and io::start().
ls()
std::vector< std::string > tools::ls (std::string path, std::string ext = "") static inherited
Lists files in a directory, optionally filtered by extension.
Parameters
path The directory to search.
ext File extension filter. If empty, all files are listed.
Returns
A vector of filenames in the directory.
Definition at line 35 of file tools/cxx/io.cxx.
References tools::ends_with(), and tools::split().
Referenced by analysis::analysis(), analysis::check_cache(), io::check_root_file_paths(), dataloader::restore_graphs(), and io::trigger_pcm().
mean_stdev()
std::tuple< float, float > plotting::mean_stdev (std::vector< float > * data)
Calculates the mean and standard deviation of a data vector.
Parameters
data Pointer to the vector of data values.
Returns
A tuple containing the mean and standard deviation.
Definition at line 53 of file plotting.cxx.
Referenced by build_error().
Message()
void notification::Message (std::string msg, std::string tag = "", bool newline = true) inherited
Outputs a message with custom formatting.
Parameters
msg The message to output.
tag A custom tag to prepend to the message.
newline Whether to append a newline (default: true).
put()
template<typename g > static void tools::put (std::vector< g * > * out, std::vector< g * > * src, std::vector< int > * trg) inline static inherited
Fills a vector with pointers from another vector based on a selection index.
Template Parameters
g The type of objects being pointed to.
Parameters
out Pointer to the output vector to fill.
src Pointer to the source vector to select from.
trg Pointer to a vector of indices for selection.
< Clear the output vector.
< Reserve space for the output elements.
< Loop through each selected index.
< Get the object at the selected index.
< Add it to the output vector.
< Mark the object as in use.
Definition at line 197 of file tools.h.
Referenced by dataloader::get_k_train_set(), dataloader::get_k_validation_set(), and dataloader::get_test_set().
rename()
void tools::rename (std::string start, std::string target) static inherited
Renames a file or directory.
Parameters
start The original path.
target The new path.
Definition at line 18 of file tools/cxx/io.cxx.
Referenced by dataloader::dump_graphs().
replace()
void tools::replace (std::string * in, std::string repl_str, std::string repl_with) static inherited
Replaces all occurrences of a substring in a string.
Parameters
in Pointer to the string to modify.
repl_str The substring to replace.
repl_with The replacement string.
Definition at line 5 of file strings.cxx.
Referenced by analysis::build_graphs(), analysis::check_cache(), dataloader::dump_graphs(), meta::get_campaign(), meta::parse_json(), and analysis::start().
set_debug_mode()
void notification::set_debug_mode (bool dbg) inherited
Enables or disables debug mode.
Parameters
dbg Boolean flag, set to true to enable debug messages, false to disable.
set_prefix()
void notification::set_prefix (std::string prefix) inherited
Sets the prefix used in log messages from this instance.
Parameters
prefix The string to use as a prefix for log messages.
set_suppress_info()
void notification::set_suppress_info (bool si) inherited
Sets whether info messages should be suppressed.
Parameters
si Boolean flag, set to true to suppress info messages, false to show them.
set_suppress_warning()
void notification::set_suppress_warning (bool sw) inherited
Sets whether warnings should be suppressed.
Parameters
sw Boolean flag, set to true to suppress warnings, false to show them.
split()
std::vector< std::string > tools::split (std::string inpt, std::string del) inherited
Splits a string into a vector of substrings based on a delimiter.
Parameters
inpt The input string to split.
del The delimiter.
Returns
A vector of substrings.
Definition at line 23 of file strings.cxx.
References index.
Referenced by analysis::build_events(), analysis::build_graphs(), analysis::build_inference(), event_template::build_mapping(), analysis::check_cache(), container::compile(), sampletracer::compile_objects(), meta::compiler(), tools::create_path(), dataloader::dump_graphs(), meta::hash(), tools::ls(), graph_t::meta_deserialize(), dataloader::restore_graphs_(), io::root_begin(), model_template::set_device(), metric_template::set_run_name(), metric_template::set_variables(), and analysis::start().
sum()
template<typename g > g tools::sum (std::vector< g > * inpt) inline inherited
Sums the elements of a vector.
Template Parameters
g The type of elements in the vector.
Parameters
inpt Pointer to the vector to sum.
Returns
The sum of all elements.
< Initialize the output variable.
< Return the sum.
Definition at line 183 of file tools.h.
Referenced by metrics::add_th1f_accuracy(), sampletracer::compile_objects(), particle_template::DeltaR(), graph_template::double_neutrino(), grift::forward(), recursivegraphneuralnetwork::forward(), matching::match_obj(), and grift::message().
sum_of_weights()
float plotting::sum_of_weights ()
Calculates the sum of weights for normalization.
Returns
The sum of weights as a float.
Definition at line 44 of file plotting.cxx.
References weights.
to_string() [1/2]
std::string tools::to_string (double val) static inherited
Converts a double value to a string with standard precision.
Parameters
val The double value to convert.
Returns
The string representation of the value.
Definition at line 59 of file strings.cxx.
Referenced by dataloader::generate_kfold_set(), dataloader::generate_test_set(), particle_template::get_hash(), topefficiency::region(), dataloader::restore_dataset(), event_template::set_hash(), selection_template::set_hash(), parton::strategy(), topjets::strategy(), toptruthjets::strategy(), and parton::top_mass_contribution().
to_string() [2/2]
std::string tools::to_string (double val, int prec) static inherited
Converts a double value to a string with specified precision.
Parameters
val The double value to convert.
prec The number of decimal places to consider.
Returns
The string representation of the value.
Definition at line 91 of file strings.cxx.
trim()
std::string tools::trim (std::string s) inherited
Removes whitespace from the beginning and end of a string.
Parameters
s The string to trim.
Returns
The trimmed string.
type_name()
template<typename T > std::string tools::type_name () inline inherited
Gets the type name of a variable as a string (for debugging).
Template Parameters
T The type to get the name of.
Returns
The name of the type as a string.
< Gets the type name via RTTI.
< Returns the type name.
Definition at line 155 of file tools.h.
Referenced by event_template::build_mapping().
Warning()
void notification::Warning (std::string msg, bool newline = true) inherited
Outputs a warning message.
Parameters
msg The warning message to output.
newline Whether to append a newline (default: true).
Referenced by io::read(), io::read(), io::write(), and io::write().
Member Data Documentation
alpha
float plotting::alpha = 0.4
Transparency level for plots. Default is 0.4.
Definition at line 149 of file plotting.h.
auto_scale
bool plotting::auto_scale = true
Flag to enable/disable auto-scaling. Default is true.
Definition at line 164 of file plotting.h.
axis_size
float plotting::axis_size = 12.5
Font size for axis labels. Default is 12.5.
Definition at line 155 of file plotting.h.
cap_size
float plotting::cap_size = 1.0
Cap size for error bars. Default is 1.0.
Definition at line 148 of file plotting.h.
color
std::string plotting::color = ""
Default color for plots. Default is empty.
Definition at line 138 of file plotting.h.
colors
std::vector<std::string> plotting::colors = {}
List of colors for multi-series plots.
Definition at line 139 of file plotting.h.
counts
bool plotting::counts = false
Flag to enable/disable counts display. Default is false.
Definition at line 125 of file plotting.h.
cross_section
float plotting::cross_section = -1
Cross-section value. Default is -1.
Definition at line 183 of file plotting.h.
debug_mode
bool notification::debug_mode = false protected inherited
Flag indicating whether debug mode is enabled. Initialized as false.
Definition at line 127 of file notification.h.
Referenced by analysis::build_metric().
density
bool plotting::density = false
Flag to enable/disable density normalization. Default is false.
Definition at line 142 of file plotting.h.
dpi
int plotting::dpi = 400
Dots per inch for output resolution. Default is 400.
Definition at line 161 of file plotting.h.
errors
bool plotting::errors = false
Flag to enable/disable error bars. Default is false.
Definition at line 124 of file plotting.h.
extension
std::string plotting::extension = ".pdf"
File extension for output files (e.g., ".pdf", ".png"). Default is ".pdf".
Definition at line 111 of file plotting.h.
Referenced by build_path().
filename
std::string plotting::filename = "untitled"
Base filename for output files. Default is "untitled".
Definition at line 112 of file plotting.h.
Referenced by build_path().
font_size
float plotting::font_size = 10
Font size for text. Default is 10.
Definition at line 154 of file plotting.h.
hatch
std::string plotting::hatch = ""
Hatch style. Default is empty.
Definition at line 135 of file plotting.h.
histfill
std::string plotting::histfill = "fill"
Histogram fill style. Default is "fill".
Definition at line 132 of file plotting.h.
integrated_luminosity
float plotting::integrated_luminosity = 140.1
Integrated luminosity in fb-1. Default is 140.1.
Definition at line 184 of file plotting.h.
labels
std::map<std::string, std::map<int, std::vector<std::vector<int> >*> > plotting::labels = {}
Labels storage.
Definition at line 171 of file plotting.h.
Referenced by ~plotting(), build_ROC(), and get_ROC().
legend_size
float plotting::legend_size = 10
Font size for legend. Default is 10.
Definition at line 156 of file plotting.h.
line_width
float plotting::line_width = 0.1
Line width for plots. Default is 0.1.
Definition at line 147 of file plotting.h.
linestyle
std::string plotting::linestyle = "-"
Line style. Default is "-".
Definition at line 136 of file plotting.h.
marker
std::string plotting::marker = "."
Marker style. Default is ".".
Definition at line 134 of file plotting.h.
output_path
std::string plotting::output_path = "./Figures"
Directory path for output files. Default is "./Figures".
Definition at line 113 of file plotting.h.
Referenced by build_path().
overflow
std::string plotting::overflow = "sum"
Overflow handling. Default is "sum".
Definition at line 133 of file plotting.h.
prefix
std::string notification::prefix = "" protected inherited
Prefix used in log messages from this instance. Initialized as empty string.
Definition at line 126 of file notification.h.
Referenced by analysis::analysis(), dataloader::dataloader(), io::io(), meta::meta(), optimizer::optimizer(), and metric_template::set_name().
roc_data
std::map<std::string, std::map<int, std::vector<std::vector<double> >*> > plotting::roc_data = {}
ROC data storage.
Definition at line 170 of file plotting.h.
Referenced by ~plotting(), build_ROC(), and get_ROC().
stack
bool plotting::stack = false
Flag to enable/disable stacking. Default is false.
Definition at line 141 of file plotting.h.
style
std::string plotting::style = "ROOT"
Plot style. Default is "ROOT".
Definition at line 128 of file plotting.h.
suppress_info
bool notification::suppress_info = false protected inherited
Flag indicating whether info messages are suppressed. Initialized as false.
Definition at line 129 of file notification.h.
suppress_warnings
bool notification::suppress_warnings = false protected inherited
Flag indicating whether warnings are suppressed. Initialized as false.
Definition at line 128 of file notification.h.
title
std::string plotting::title = "untitled"
Plot title. Default is "untitled".
Definition at line 129 of file plotting.h.
title_size
float plotting::title_size = 10
Font size for title. Default is 10.
Definition at line 157 of file plotting.h.
use_latex
bool plotting::use_latex = true
Flag to enable/disable LaTeX rendering. Default is true.
Definition at line 158 of file plotting.h.
variable_x_bins
std::vector<float> plotting::variable_x_bins = {}
Variable binning for x-axis.
Definition at line 179 of file plotting.h.
variable_y_bins
std::vector<float> plotting::variable_y_bins = {}
Variable binning for y-axis.
Definition at line 180 of file plotting.h.
weights
std::vector<float> plotting::weights = {}
Weights for data points.
Definition at line 182 of file plotting.h.
Referenced by sum_of_weights().
x_bins
int plotting::x_bins = 100
Number of bins for x-axis. Default is 100.
Definition at line 122 of file plotting.h.
x_data
std::vector<float> plotting::x_data = {}
Data for x-axis.
Definition at line 167 of file plotting.h.
Referenced by build_error(), get_max(), and get_min().
x_labels
std::unordered_map<std::string, float> plotting::x_labels = {}
Labels for x-axis.
Definition at line 176 of file plotting.h.
x_logarithmic
bool plotting::x_logarithmic = false
Flag to enable/disable logarithmic x-axis. Default is false.
Definition at line 144 of file plotting.h.
x_max
float plotting::x_max = 0
Maximum value for x-axis. Default is 0 (auto-determined if not set).
Definition at line 119 of file plotting.h.
x_min
float plotting::x_min = 0
Minimum value for x-axis. Default is 0.
Definition at line 116 of file plotting.h.
x_step
float plotting::x_step = -1
Step size for x-axis. Default is -1 (auto-determined).
Definition at line 150 of file plotting.h.
xscaling
float plotting::xscaling = 1.25*6.4
Scaling factor for x-axis. Default is 1.25*6.4.
Definition at line 162 of file plotting.h.
xtitle
std::string plotting::xtitle = "x-axis"
X-axis title. Default is "x-axis".
Definition at line 131 of file plotting.h.
y_bins
int plotting::y_bins = 100
Number of bins for y-axis. Default is 100.
Definition at line 123 of file plotting.h.
y_data
std::vector<float> plotting::y_data = {}
Data for y-axis.
Definition at line 168 of file plotting.h.
Referenced by build_error(), get_max(), and get_min().
y_error_down
std::vector<float> plotting::y_error_down = {}
Lower error values for y-axis.
Definition at line 174 of file plotting.h.
Referenced by build_error().
y_error_up
std::vector<float> plotting::y_error_up = {}
Upper error values for y-axis.
Definition at line 173 of file plotting.h.
Referenced by build_error().
y_labels
std::unordered_map<std::string, float> plotting::y_labels = {}
Labels for y-axis.
Definition at line 177 of file plotting.h.
y_logarithmic
bool plotting::y_logarithmic = false
Flag to enable/disable logarithmic y-axis. Default is false.
Definition at line 145 of file plotting.h.
y_max
float plotting::y_max = 0
Maximum value for y-axis. Default is 0 (auto-determined if not set).
Definition at line 120 of file plotting.h.
y_min
float plotting::y_min = 0
Minimum value for y-axis. Default is 0.
Definition at line 117 of file plotting.h.
y_step
float plotting::y_step = -1
Step size for y-axis. Default is -1 (auto-determined).
Definition at line 151 of file plotting.h.
yscaling
float plotting::yscaling = 1.25*4.8
Scaling factor for y-axis. Default is 1.25*4.8.
Definition at line 163 of file plotting.h.
ytitle
std::string plotting::ytitle = "y-axis"
Y-axis title. Default is "y-axis".
Definition at line 130 of file plotting.h.
The documentation for this class was generated from the following files:
plotting.h
plotting.cxx