AnalysisG: physics_truth Class Reference
physics_truth Class Reference
#include <particles.h>
Public Member Functions
physics_truth ()
virtual ~physics_truth ()
particle_template * clone () override
void build (std::map< std::string, particle_template * > *prt, element_t *el) override
Public Member Functions inherited from particle_template
particle_template ()
virtual ~particle_template ()
particle_template (particle_t *p)
particle_template (particle_template *p, bool dump=false)
particle_template (double px, double py, double pz, double e)
particle_template (double px, double py, double pz)
void to_cartesian ()
void to_polar ()
bool is (std::vector< int > p)
double DeltaR (particle_template *p)
bool operator== (particle_template &p)
template<typename g >
g operator+ (g &p)
void operator+= (particle_template *p)
void iadd (particle_template *p)
bool register_parent (particle_template *p)
bool register_child (particle_template *p)
void add_leaf (std::string key, std::string leaf="")
void apply_type_prefix ()
std::map< std::string, std::map< std::string, particle_t > > __reduce__ ()
Public Member Functions inherited from tools
tools ()
Constructor for the tools class.
~tools ()
Destructor for the tools class.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Public Attributes
std::vector< int > top_index = {}
Public Attributes inherited from particle_template
cproperty< double, particle_template > e
cproperty< double, particle_template > mass
cproperty< double, particle_template > pt
cproperty< double, particle_template > eta
cproperty< double, particle_template > phi
cproperty< double, particle_template > px
cproperty< double, particle_template > py
cproperty< double, particle_template > pz
cproperty< int, particle_template > pdgid
cproperty< std::string, particle_template > symbol
cproperty< double, particle_template > charge
cproperty< std::string, particle_template > hash
cproperty< bool, particle_template > is_b
cproperty< bool, particle_template > is_lep
cproperty< bool, particle_template > is_nu
cproperty< bool, particle_template > is_add
cproperty< bool, particle_template > lep_decay
cproperty< std::map< std::string, particle_template * >, particle_template > parents
cproperty< std::map< std::string, particle_template * >, particle_template > children
cproperty< std::string, particle_template > type
cproperty< int, particle_template > index
std::map< std::string, particle_template * > m_parents
std::map< std::string, particle_template * > m_children
std::map< std::string, std::string > leaves = {}
particle_t data
bool _is_serial = false
bool _is_marked = false
Additional Inherited Members
Static Public Member Functions inherited from particle_template
static void set_e (double *, particle_template *)
static void get_e (double *, particle_template *)
static void set_mass (double *, particle_template *)
static void get_mass (double *, particle_template *)
static void set_pt (double *, particle_template *)
static void get_pt (double *, particle_template *)
static void set_eta (double *, particle_template *)
static void get_eta (double *, particle_template *)
static void set_phi (double *, particle_template *)
static void get_phi (double *, particle_template *)
static void set_px (double *, particle_template *)
static void get_px (double *, particle_template *)
static void set_py (double *, particle_template *)
static void get_py (double *, particle_template *)
static void set_pz (double *, particle_template *)
static void get_pz (double *, particle_template *)
static void set_pdgid (int *, particle_template *)
static void get_pdgid (int *, particle_template *)
static void set_symbol (std::string *, particle_template *)
static void get_symbol (std::string *, particle_template *)
static void set_charge (double *, particle_template *)
static void get_charge (double *, particle_template *)
static void get_hash (std::string *, particle_template *)
static void get_isb (bool *, particle_template *)
static void get_islep (bool *, particle_template *)
static void get_isnu (bool *, particle_template *)
static void get_isadd (bool *, particle_template *)
static void get_lepdecay (bool *, particle_template *)
static void set_parents (std::map< std::string, particle_template * > *, particle_template *)
static void get_parents (std::map< std::string, particle_template * > *, particle_template *)
static void set_children (std::map< std::string, particle_template * > *, particle_template *)
static void get_children (std::map< std::string, particle_template * > *, particle_template *)
static void set_type (std::string *, particle_template *)
static void get_type (std::string *, particle_template *)
static void set_index (int *, particle_template *)
static void get_index (int *, particle_template *)
Static Public Member Functions inherited from tools
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Detailed Description
Definition at line 60 of file events/exp_mc20/include/exp_mc20/particles.h.
Constructor & Destructor Documentation
physics_truth()
physics_truth::physics_truth ()
Definition at line 118 of file exp_mc20/cxx/particles.cxx.
{
     this -> type = "phystru";
     this -> add_leaf("pt"    , "_pt");
     this -> add_leaf("eta"   , "_eta");
     this -> add_leaf("phi"   , "_phi");
     this -> add_leaf("energy", "_e");
     this -> add_leaf("charge", "_charge");
     this -> add_leaf("index" , "_index");
     this -> add_leaf("parton", "_partontruthlabel");
     this -> add_leaf("type"     , "_type");
     this -> add_leaf("top_index", "_top_index");
     this -> apply_type_prefix();
 }
References particle_template::add_leaf(), particle_template::apply_type_prefix(), and particle_template::type.
Referenced by clone().
~physics_truth()
physics_truth::~physics_truth () virtual
Definition at line 134 of file exp_mc20/cxx/particles.cxx.
 {}
Member Function Documentation
build()
void physics_truth::build (std::map< std::string, particle_template * > * prt, element_t * el) override virtual
Reimplemented from particle_template.
Definition at line 136 of file exp_mc20/cxx/particles.cxx.
{
     auto lamb = [](physics_truth* msp, std::vector<int>* prt){
         int pdg = msp -> pdgid;
         pdg = std::abs(pdg);
         if (!prt -> size()){return false;}
         if (pdg == 0){return false;}
         if (pdg == 6){return false;}
         if (pdg == 24){return false;}
         if (pdg >= 11 && pdg <= 16){return false;}
         if (msp -> top_index.size() > 1){return true;}
         if (msp -> top_index[0] == -1){return false;}
         int mx(0);
         std::map<int, int> out;
         std::map<int, int>::iterator itx;
         for (size_t x(0); x < prt -> size(); ++x){out[std::abs((*prt)[x])] += 1;}
         for (itx = out.begin(); itx != out.end(); ++itx){
             if (itx -> second < mx){continue;}
             mx = itx -> second; pdg = itx -> first;
         }
         msp -> pdgid = pdg;
         return true;
     };
     std::vector<physics_truth*> tps = {};
     pmu(&tps, el);
     std::vector<int> _index, parton, ch;
     el -> get("charge", &ch);
     el -> get("index" , &_index);
     el -> get("parton", &parton);
     std::vector<std::vector<int>> _top_index, _type;
     el -> get("top_index", &_top_index);
     el -> get("type", &_type);
     for (size_t x(0); x < tps.size(); ++x){
         tps[x] -> charge    = ch[x];
         tps[x] -> index     = _index[x];
         tps[x] -> top_index = _top_index[x];
         tps[x] -> pdgid     = parton[x];
         if (!lamb(tps[x], &_type[x])){delete tps[x]; tps[x] = nullptr;}
         else {(*prt)[std::string(tps[x] -> hash)] = tps[x];}
     }
 }
References particle_template::charge, particle_template::hash, particle_template::index, test_evaluation::mx, main::out, particle_template::pdgid, pmu, top_index, and main::x.
clone()
particle_template * physics_truth::clone () override virtual
Reimplemented from particle_template.
Definition at line 135 of file exp_mc20/cxx/particles.cxx.
 {return (particle_template*)new physics_truth();}
References physics_truth().
Member Data Documentation
top_index
std::vector<int> physics_truth::top_index = {}
Definition at line 66 of file events/exp_mc20/include/exp_mc20/particles.h.
Referenced by build().
The documentation for this class was generated from the following files:
events/exp_mc20/include/exp_mc20/particles.h
exp_mc20/cxx/particles.cxx