AnalysisG: graph_truthjets Class Reference
graph_truthjets Class Reference
#include <graphs.h>
Public Member Functions
graph_truthjets ()
virtual ~graph_truthjets ()
graph_template * clone () override
Creates a clone of this graph template.
void CompileEvent () override
Compiles the event into a graph.
virtual bool PreSelection ()
Pre-selection filter for events.
void define_particle_nodes (std::vector< particle_template * > *prt)
Defines which particles become graph nodes.
void define_topology (std::function< bool(particle_template *, particle_template *)> fx)
Defines the edge topology between nodes.
void flush_particles ()
Clears all particle references.
bool operator== (graph_template &p)
Equality comparison operator.
template<typename G >
G * get_event ()
Gets the source event cast to a specific type.
template<typename G , typename O , typename X >
void add_graph_truth_feature (O *ev, X fx, std::string name)
Adds a graph-level truth feature.
template<typename G , typename O , typename X >
void add_graph_data_feature (O *ev, X fx, std::string name)
Adds a graph-level data feature.
template<typename G , typename O , typename X >
void add_node_truth_feature (X fx, std::string name)
Adds a node-level truth feature.
template<typename G , typename O , typename X >
void add_node_data_feature (X fx, std::string name)
Adds a node-level data feature.
template<typename G , typename O , typename X >
void add_edge_truth_feature (X fx, std::string name)
Adds an edge-level truth feature.
template<typename G , typename O , typename X >
void add_edge_data_feature (X fx, std::string name)
Adds an edge-level data feature.
bool double_neutrino (double mass_top=172.62 *1000, double mass_wboson=80.385 *1000, double top_perc=0.85, double w_perc=0.95, double distance=1e-8, int steps=10)
Reconstructs double neutrino momenta for di-leptonic events.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Static Public Member Functions
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Public Attributes
cproperty< long, graph_template > index
Event index property.
cproperty< double, graph_template > weight
Event weight property.
cproperty< bool, graph_template > preselection
Preselection result property.
cproperty< std::string, graph_template > hash
Unique hash identifier.
cproperty< std::string, graph_template > tree
Source tree name.
cproperty< std::string, graph_template > name
Graph template name.
int threadIdx = -1
Thread index for parallel processing.
std::string filename = ""
Source filename.
meta * meta_data = nullptr
Pointer to event metadata.
Private Member Functions
void add_graph_feature (bool, std::string)
void add_graph_feature (std::vector< bool >, std::string)
void add_graph_feature (float, std::string)
void add_graph_feature (std::vector< float >, std::string)
void add_graph_feature (double, std::string)
void add_graph_feature (std::vector< double >, std::string)
void add_graph_feature (long, std::string)
void add_graph_feature (std::vector< long >, std::string)
void add_graph_feature (int, std::string)
void add_graph_feature (std::vector< int >, std::string)
void add_graph_feature (std::vector< std::vector< int > >, std::string)
void add_node_feature (bool, std::string)
void add_node_feature (std::vector< bool >, std::string)
void add_node_feature (float, std::string)
void add_node_feature (std::vector< float >, std::string)
void add_node_feature (double, std::string)
void add_node_feature (std::vector< double >, std::string)
void add_node_feature (long, std::string)
void add_node_feature (std::vector< long >, std::string)
void add_node_feature (int, std::string)
void add_node_feature (std::vector< int >, std::string)
void add_node_feature (std::vector< std::vector< int > >, std::string)
void add_edge_feature (bool, std::string)
void add_edge_feature (std::vector< bool >, std::string)
void add_edge_feature (float, std::string)
void add_edge_feature (std::vector< float >, std::string)
void add_edge_feature (double, std::string)
void add_edge_feature (std::vector< double >, std::string)
void add_edge_feature (long, std::string)
void add_edge_feature (std::vector< long >, std::string)
void add_edge_feature (int, std::string)
void add_edge_feature (std::vector< int >, std::string)
void add_edge_feature (std::vector< std::vector< int > >, std::string)
template<typename G , typename g >
torch::Tensor to_tensor (std::vector< G > _data, at::ScalarType _op, g prim)
graph_template * build (event_template *el)
graph_t * data_export ()
Static Private Member Functions
static void set_name (std::string *, graph_template *)
static void set_preselection (bool *, graph_template *)
static void get_hash (std::string *, graph_template *)
static void get_index (long *, graph_template *)
static void get_weight (double *, graph_template *)
static void get_tree (std::string *, graph_template *)
static void get_preselection (bool *, graph_template *)
static void build_export (std::map< std::string, torch::Tensor * > *_truth_t, std::map< std::string, int > *_truth_i, std::map< std::string, torch::Tensor * > *_data_t, std::map< std::string, int > *_data_i, std::map< std::string, torch::Tensor > *_fx)
Private Attributes
friend container
friend analysis
int num_nodes = 0
std::map< std::string, int > nodes = {}
std::map< int, particle_template * > node_particles = {}
std::map< std::string, torch::Tensor > graph_fx = {}
std::map< std::string, torch::Tensor > node_fx = {}
std::map< std::string, torch::Tensor > edge_fx = {}
std::vector< std::vector< int > > _topology
std::vector< int > _topological_index
torch::Tensor m_topology
torch::TensorOptions * op = nullptr
event_template * m_event = nullptr
bool m_preselection = true
event_t data
Detailed Description
Definition at line 25 of file bsm_4tops/include/bsm_4tops/graphs.h.
Constructor & Destructor Documentation
graph_truthjets()
graph_truthjets::graph_truthjets ()
Definition at line 80 of file bsm_4tops/cxx/graphs.cxx.
Referenced by clone().
~graph_truthjets()
graph_truthjets::~graph_truthjets () virtual
Definition at line 81 of file bsm_4tops/cxx/graphs.cxx.
Member Function Documentation
absolute_path()
std::string tools::absolute_path (std::string path) static inherited
Converts a relative path to an absolute path.
Parameters
path The path to convert.
Returns
The absolute version of the path.
Definition at line 49 of file tools/cxx/io.cxx.
Referenced by analysis::analysis(), analysis::build_events(), io::check_root_file_paths(), and io::trigger_pcm().
add_edge_data_feature()
template<typename G , typename O , typename X > void graph_template::add_edge_data_feature (X fx, std::string name) inline inherited
Adds an edge-level data feature.
Template Parameters
G Feature value type.
O Particle type.
X Getter function type.
Parameters
fx Getter function called for each edge (particle pair).
name Feature name (D- prefix added automatically).
Definition at line 566 of file graph_template.h.
References graph_template::_topological_index, graph_template::add_edge_feature(), graph_template::define_topology(), fulltopo(), graph_template::node_particles, cproperty< T, G >::set_getter(), and cproperty< T, G >::set_object().
add_edge_feature() [1/11]
void graph_template::add_edge_feature (bool data, std::string name) private inherited
Definition at line 123 of file graph/cxx/properties.cxx.
References graph_template::data, graph_template::edge_fx, graph_template::name, and graph_template::to_tensor().
Referenced by graph_template::add_edge_data_feature(), and graph_template::add_edge_truth_feature().
add_edge_feature() [2/11]
void graph_template::add_edge_feature (double data, std::string name) private inherited
Definition at line 139 of file graph/cxx/properties.cxx.
References graph_template::data, graph_template::edge_fx, graph_template::name, and graph_template::to_tensor().
add_edge_feature() [3/11]
void graph_template::add_edge_feature (float data, std::string name) private inherited
Definition at line 131 of file graph/cxx/properties.cxx.
References graph_template::data, graph_template::edge_fx, graph_template::name, and graph_template::to_tensor().
add_edge_feature() [4/11]
void graph_template::add_edge_feature (int data, std::string name) private inherited
Definition at line 155 of file graph/cxx/properties.cxx.
References graph_template::data, graph_template::edge_fx, graph_template::name, and graph_template::to_tensor().
add_edge_feature() [5/11]
void graph_template::add_edge_feature (long data, std::string name) private inherited
Definition at line 147 of file graph/cxx/properties.cxx.
References graph_template::data, graph_template::edge_fx, graph_template::name, and graph_template::to_tensor().
add_edge_feature() [6/11]
void graph_template::add_edge_feature (std::vector< bool > _data, std::string name) private inherited
Definition at line 127 of file graph/cxx/properties.cxx.
References graph_template::edge_fx, graph_template::name, and graph_template::to_tensor().
add_edge_feature() [7/11]
void graph_template::add_edge_feature (std::vector< double > _data, std::string name) private inherited
Definition at line 143 of file graph/cxx/properties.cxx.
References graph_template::edge_fx, graph_template::name, and graph_template::to_tensor().
add_edge_feature() [8/11]
void graph_template::add_edge_feature (std::vector< float > _data, std::string name) private inherited
Definition at line 135 of file graph/cxx/properties.cxx.
References graph_template::edge_fx, graph_template::name, and graph_template::to_tensor().
add_edge_feature() [9/11]
void graph_template::add_edge_feature (std::vector< int > _data, std::string name) private inherited
Definition at line 159 of file graph/cxx/properties.cxx.
References graph_template::edge_fx, graph_template::name, and graph_template::to_tensor().
add_edge_feature() [10/11]
void graph_template::add_edge_feature (std::vector< long > _data, std::string name) private inherited
Definition at line 151 of file graph/cxx/properties.cxx.
References graph_template::edge_fx, graph_template::name, and graph_template::to_tensor().
add_edge_feature() [11/11]
void graph_template::add_edge_feature (std::vector< std::vector< int > > _data, std::string name) private inherited
Definition at line 163 of file graph/cxx/properties.cxx.
References graph_template::edge_fx, graph_template::name, and graph_template::to_tensor().
add_edge_truth_feature()
template<typename G , typename O , typename X > void graph_template::add_edge_truth_feature (X fx, std::string name) inline inherited
Adds an edge-level truth feature.
Template Parameters
G Feature value type.
O Particle type.
X Getter function type.
Parameters
fx Getter function called for each edge (particle pair).
name Feature name (T- prefix added automatically).
Definition at line 536 of file graph_template.h.
References graph_template::_topological_index, graph_template::add_edge_feature(), graph_template::define_topology(), fulltopo(), graph_template::node_particles, cproperty< T, G >::set_getter(), and cproperty< T, G >::set_object().
add_graph_data_feature()
template<typename G , typename O , typename X > void graph_template::add_graph_data_feature (O * ev, X fx, std::string name) inline inherited
Adds a graph-level data feature.
Template Parameters
G Feature value type.
O Object type to extract feature from.
X Getter function type.
Parameters
ev Object to get feature from.
fx Getter function.
name Feature name (D- prefix added automatically).
Definition at line 476 of file graph_template.h.
References graph_template::add_graph_feature(), cproperty< T, G >::set_getter(), and cproperty< T, G >::set_object().
add_graph_feature() [1/11]
void graph_template::add_graph_feature (bool data, std::string name) private inherited
Definition at line 32 of file graph/cxx/properties.cxx.
References graph_template::data, graph_template::graph_fx, graph_template::name, and graph_template::to_tensor().
Referenced by graph_template::add_graph_data_feature(), and graph_template::add_graph_truth_feature().
add_graph_feature() [2/11]
void graph_template::add_graph_feature (double data, std::string name) private inherited
Definition at line 48 of file graph/cxx/properties.cxx.
References graph_template::data, graph_template::graph_fx, graph_template::name, and graph_template::to_tensor().
add_graph_feature() [3/11]
void graph_template::add_graph_feature (float data, std::string name) private inherited
Definition at line 40 of file graph/cxx/properties.cxx.
References graph_template::data, graph_template::graph_fx, graph_template::name, and graph_template::to_tensor().
add_graph_feature() [4/11]
void graph_template::add_graph_feature (int data, std::string name) private inherited
Definition at line 64 of file graph/cxx/properties.cxx.
References graph_template::data, graph_template::graph_fx, graph_template::name, and graph_template::to_tensor().
add_graph_feature() [5/11]
void graph_template::add_graph_feature (long data, std::string name) private inherited
Definition at line 56 of file graph/cxx/properties.cxx.
References graph_template::data, graph_template::graph_fx, graph_template::name, and graph_template::to_tensor().
add_graph_feature() [6/11]
void graph_template::add_graph_feature (std::vector< bool > _data, std::string name) private inherited
Definition at line 36 of file graph/cxx/properties.cxx.
References graph_template::graph_fx, graph_template::name, and graph_template::to_tensor().
add_graph_feature() [7/11]
void graph_template::add_graph_feature (std::vector< double > _data, std::string name) private inherited
Definition at line 52 of file graph/cxx/properties.cxx.
References graph_template::graph_fx, graph_template::name, and graph_template::to_tensor().
add_graph_feature() [8/11]
void graph_template::add_graph_feature (std::vector< float > _data, std::string name) private inherited
Definition at line 44 of file graph/cxx/properties.cxx.
References graph_template::graph_fx, graph_template::name, and graph_template::to_tensor().
add_graph_feature() [9/11]
void graph_template::add_graph_feature (std::vector< int > _data, std::string name) private inherited
Definition at line 68 of file graph/cxx/properties.cxx.
References graph_template::graph_fx, graph_template::name, and graph_template::to_tensor().
add_graph_feature() [10/11]
void graph_template::add_graph_feature (std::vector< long > _data, std::string name) private inherited
Definition at line 60 of file graph/cxx/properties.cxx.
References graph_template::graph_fx, graph_template::name, and graph_template::to_tensor().
add_graph_feature() [11/11]
void graph_template::add_graph_feature (std::vector< std::vector< int > > _data, std::string name) private inherited
Definition at line 72 of file graph/cxx/properties.cxx.
References graph_template::graph_fx, graph_template::name, and graph_template::to_tensor().
add_graph_truth_feature()
template<typename G , typename O , typename X > void graph_template::add_graph_truth_feature (O * ev, X fx, std::string name) inline inherited
Adds a graph-level truth feature.
Template Parameters
G Feature value type.
O Object type to extract feature from.
X Getter function type.
Parameters
ev Object to get feature from.
fx Getter function.
name Feature name (T- prefix added automatically).
Definition at line 458 of file graph_template.h.
References graph_template::add_graph_feature(), cproperty< T, G >::set_getter(), and cproperty< T, G >::set_object().
add_node_data_feature()
template<typename G , typename O , typename X > void graph_template::add_node_data_feature (X fx, std::string name) inline inherited
Adds a node-level data feature.
Template Parameters
G Feature value type.
O Particle type.
X Getter function type.
Parameters
fx Getter function called for each node particle.
name Feature name (D- prefix added automatically).
Definition at line 514 of file graph_template.h.
References graph_template::add_node_feature(), graph_template::node_particles, cproperty< T, G >::set_getter(), and cproperty< T, G >::set_object().
add_node_feature() [1/11]
void graph_template::add_node_feature (bool data, std::string name) private inherited
Definition at line 78 of file graph/cxx/properties.cxx.
References graph_template::data, graph_template::name, graph_template::node_fx, and graph_template::to_tensor().
Referenced by graph_template::add_node_data_feature(), and graph_template::add_node_truth_feature().
add_node_feature() [2/11]
void graph_template::add_node_feature (double data, std::string name) private inherited
Definition at line 94 of file graph/cxx/properties.cxx.
References graph_template::data, graph_template::name, graph_template::node_fx, and graph_template::to_tensor().
add_node_feature() [3/11]
void graph_template::add_node_feature (float data, std::string name) private inherited
Definition at line 86 of file graph/cxx/properties.cxx.
References graph_template::data, graph_template::name, graph_template::node_fx, and graph_template::to_tensor().
add_node_feature() [4/11]
void graph_template::add_node_feature (int data, std::string name) private inherited
Definition at line 110 of file graph/cxx/properties.cxx.
References graph_template::data, graph_template::name, graph_template::node_fx, and graph_template::to_tensor().
add_node_feature() [5/11]
void graph_template::add_node_feature (long data, std::string name) private inherited
Definition at line 102 of file graph/cxx/properties.cxx.
References graph_template::data, graph_template::name, graph_template::node_fx, and graph_template::to_tensor().
add_node_feature() [6/11]
void graph_template::add_node_feature (std::vector< bool > _data, std::string name) private inherited
Definition at line 82 of file graph/cxx/properties.cxx.
References graph_template::name, graph_template::node_fx, and graph_template::to_tensor().
add_node_feature() [7/11]
void graph_template::add_node_feature (std::vector< double > _data, std::string name) private inherited
Definition at line 98 of file graph/cxx/properties.cxx.
References graph_template::name, graph_template::node_fx, and graph_template::to_tensor().
add_node_feature() [8/11]
void graph_template::add_node_feature (std::vector< float > _data, std::string name) private inherited
Definition at line 90 of file graph/cxx/properties.cxx.
References graph_template::name, graph_template::node_fx, and graph_template::to_tensor().
add_node_feature() [9/11]
void graph_template::add_node_feature (std::vector< int > _data, std::string name) private inherited
Definition at line 114 of file graph/cxx/properties.cxx.
References graph_template::name, graph_template::node_fx, and graph_template::to_tensor().
add_node_feature() [10/11]
void graph_template::add_node_feature (std::vector< long > _data, std::string name) private inherited
Definition at line 106 of file graph/cxx/properties.cxx.
References graph_template::name, graph_template::node_fx, and graph_template::to_tensor().
add_node_feature() [11/11]
void graph_template::add_node_feature (std::vector< std::vector< int > > _data, std::string name) private inherited
Definition at line 118 of file graph/cxx/properties.cxx.
References graph_template::name, graph_template::node_fx, and graph_template::to_tensor().
add_node_truth_feature()
template<typename G , typename O , typename X > void graph_template::add_node_truth_feature (X fx, std::string name) inline inherited
Adds a node-level truth feature.
Template Parameters
G Feature value type.
O Particle type.
X Getter function type.
Parameters
fx Getter function called for each node particle.
name Feature name (T- prefix added automatically).
Definition at line 493 of file graph_template.h.
References graph_template::add_node_feature(), graph_template::node_particles, cproperty< T, G >::set_getter(), and cproperty< T, G >::set_object().
build()
graph_template * graph_template::build (event_template * el) private inherited
Definition at line 189 of file graph_template.cxx.
References graph_template::clone(), graph_template::data, graph_template::filename, graph_template::m_event, graph_template::meta_data, graph_template::name, and graph_template::preselection.
build_export()
void graph_template::build_export (std::map< std::string, torch::Tensor * > * _truth_t, std::map< std::string, int > * _truth_i, std::map< std::string, torch::Tensor * > * _data_t, std::map< std::string, int > * _data_i, std::map< std::string, torch::Tensor > * _fx) static private inherited
Definition at line 168 of file graph/cxx/properties.cxx.
Referenced by graph_template::data_export().
clone()
graph_template * graph_truthjets::clone () override virtual
Creates a clone of this graph template.
Returns
Pointer to the cloned instance.
Reimplemented from graph_template.
Definition at line 82 of file bsm_4tops/cxx/graphs.cxx.
References graph_truthjets().
CompileEvent()
void graph_truthjets::CompileEvent () override virtual
Compiles the event into a graph.
Override this method to define custom graph construction logic. Access the event via get_event<EventType>().
Reimplemented from graph_template.
Definition at line 84 of file bsm_4tops/cxx/graphs.cxx.
References charge, graph_template::define_particle_nodes(), graph_template::define_topology(), energy, eta, event_number(), event_weight(), fulltopo(), is_bquark(), is_lep, is_lepton(), is_neutrino(), is_nu, missing_et(), missing_phi(), graph_template::nodes, num_children_leps(), num_lepton(), num_neutrino(), num_tops(), num_truthjets(), phi, pt, res_edge(), res_node(), signal_event(), top_edge(), and top_node().
create_path()
void tools::create_path (std::string path) static inherited
Creates a directory path, including parent directories if needed.
Parameters
path The directory path to create.
Definition at line 6 of file tools/cxx/io.cxx.
References f, and tools::split().
Referenced by analysis::analysis(), analysis::build_inference(), plotting::build_path(), analysis::build_project(), container::compile(), metrics::dump_mass_plots(), metric_template::execute(), metrics::generic_painter(), analysis::start(), io::start(), and io::trigger_pcm().
data_export()
graph_t * graph_template::data_export () private inherited
Definition at line 148 of file graph_template.cxx.
References graph_template::build_export(), graph_template::edge_fx, edge_index, event_weight(), graph_template::graph_fx, graph_template::index, graph_template::m_topology, graph_template::node_fx, graph_template::num_nodes, graph_template::preselection, and graph_template::weight.
define_particle_nodes()
void graph_template::define_particle_nodes (std::vector< particle_template * > * prt) inherited
Defines which particles become graph nodes.
Parameters
prt Vector of particles to use as nodes.
Definition at line 47 of file graph_template.cxx.
References graph_template::hash, graph_template::node_particles, graph_template::nodes, and graph_template::num_nodes.
Referenced by graph_tops::CompileEvent(), graph_children::CompileEvent(), CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), and graph_detector::CompileEvent().
define_topology()
void graph_template::define_topology (std::function< bool(particle_template *, particle_template *)> fx) inherited
Defines the edge topology between nodes.
Parameters
fx Function that returns true if two particles should be connected.
Definition at line 58 of file graph_template.cxx.
References graph_template::_topological_index, graph_template::_topology, graph_template::m_topology, graph_template::node_particles, and graph_template::to_tensor().
Referenced by graph_template::add_edge_data_feature(), graph_template::add_edge_truth_feature(), graph_children::CompileEvent(), CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), and graph_detector::CompileEvent().
delete_path()
void tools::delete_path (std::string path) static inherited
Deletes a directory path and its contents.
Parameters
path The directory path to delete.
Definition at line 22 of file tools/cxx/io.cxx.
double_neutrino()
bool graph_template::double_neutrino (double mass_top = 172.62*1000, double mass_wboson = 80.385*1000, double top_perc = 0.85, double w_perc = 0.95, double distance = 1e-8, int steps = 10) inherited
Reconstructs double neutrino momenta for di-leptonic events.
Parameters
mass_top Top quark mass in MeV (default 172.62 GeV).
mass_wboson W boson mass in MeV (default 80.385 GeV).
top_perc Top mass constraint percentage (default 0.85).
w_perc W mass constraint percentage (default 0.95).
distance Convergence tolerance (default 1e-8).
steps Maximum iteration steps (default 10).
Returns
True if reconstruction succeeded.
Definition at line 87 of file graph_template.cxx.
References graph_template::graph_fx, is_b, is_lep, graph_template::node_fx, and tools::sum().
Referenced by graph_truthjets_nonu::CompileEvent(), graph_jets_nonu::CompileEvent(), and graph_detector::CompileEvent().
ends_with()
bool tools::ends_with (std::string * inpt, std::string val) static inherited
Checks if a string ends with a specific substring.
Parameters
inpt Pointer to the string to check.
val The substring to check for at the end.
Returns
True if the string ends with the substring, false otherwise.
Definition at line 71 of file strings.cxx.
References l.
Referenced by plotting::build_path(), io::check_root_file_paths(), dataloader::dump_graphs(), tools::ls(), meta::parse_json(), io::scan_keys(), and analysis::start().
extract()
template<typename C , typename T > static void tools::extract (std::vector< T > * prop, std::vector< C * > * src, void(*)(T *, C *) get_prop) inline static inherited
Extracts a specific property from a vector of objects into a new vector.
Template Parameters
C The type of objects in the source vector.
T The type of the property to extract.
Parameters
prop Pointer to the output vector to fill with property values.
src Pointer to the source vector of objects.
get_prop Function pointer to extract the property from an object.
< Clear the properties vector.
< Reserve space for the property values.
< Loop through each object in the source vector.
< Create a default-initialized property variable.
< Call the provided function to extract the property.
< Add the property value to the output vector.
Definition at line 216 of file tools.h.
flush()
template<typename T > static void tools::flush (std::vector< T * > * inpt) inline static inherited
Empties a vector and all objects it points to.
Template Parameters
T The type of pointers in the vector.
Parameters
inpt Pointer to the vector to empty.
< Loop through all elements in the vector.
< Delete the object the pointer points to.
< Set the pointer to nullptr to avoid dangling pointers.
< Clear the vector.
Definition at line 167 of file tools.h.
Referenced by analysis::~analysis(), dataloader::~dataloader(), sampletracer::compile_objects(), and io::root_end().
flush_particles()
void graph_template::flush_particles () inherited
Clears all particle references.
Definition at line 38 of file graph_template.cxx.
References graph_template::_topological_index, graph_template::_topology, graph_template::m_event, graph_template::node_particles, and graph_template::nodes.
get_event()
template<typename G > G * graph_template::get_event () inline inherited
Gets the source event cast to a specific type.
Template Parameters
G The event type to cast to.
Returns
Pointer to the event.
Definition at line 446 of file graph_template.h.
References graph_template::m_event.
get_hash()
void graph_template::get_hash (std::string * val, graph_template * ev) static private inherited
Definition at line 7 of file graph/cxx/properties.cxx.
References graph_template::data, and event_t::hash.
Referenced by graph_template::graph_template().
get_index()
void graph_template::get_index (long * inpt, graph_template * ev) static private inherited
Definition at line 15 of file graph/cxx/properties.cxx.
References graph_template::data, and event_t::index.
Referenced by graph_template::graph_template().
get_preselection()
void graph_template::get_preselection (bool * inpt, graph_template * ev) static private inherited
Definition at line 27 of file graph/cxx/properties.cxx.
References graph_template::m_preselection.
Referenced by graph_template::graph_template().
get_tree()
void graph_template::get_tree (std::string * name, graph_template * ev) static private inherited
Definition at line 11 of file graph/cxx/properties.cxx.
References graph_template::data, and event_t::tree.
Referenced by graph_template::graph_template().
get_weight()
void graph_template::get_weight (double * inpt, graph_template * ev) static private inherited
Definition at line 19 of file graph/cxx/properties.cxx.
References graph_template::data, and event_t::weight.
Referenced by graph_template::graph_template().
has_string()
bool tools::has_string (std::string * inpt, std::string trg) static inherited
Checks if a string contains a specific substring.
Parameters
inpt Pointer to the string to check.
trg The substring to search for.
Returns
True if the substring is found, false otherwise.
Definition at line 65 of file strings.cxx.
References f.
Referenced by analysis::check_cache(), meta::compiler(), metrics::generic_painter(), dataloader::restore_graphs_(), meta::scan_sow(), model_template::set_device(), and metric_template::set_run_name().
has_value()
bool tools::has_value (std::vector< std::string > * data, std::string trg) static inherited
Checks if a vector of strings contains a specific string.
Parameters
data Pointer to the vector to search.
trg The string to search for.
Returns
True if the string is found in the vector, false otherwise.
Definition at line 77 of file strings.cxx.
Referenced by io::scan_keys().
is_file()
bool tools::is_file (std::string path) static inherited
Checks if a path refers to an existing file.
Parameters
path The path to check.
Returns
True if the path is a file and exists, false otherwise.
Definition at line 30 of file tools/cxx/io.cxx.
Referenced by io::check_root_file_paths(), analysis::initialize_loop(), metric_template::set_run_name(), and io::start().
ls()
std::vector< std::string > tools::ls (std::string path, std::string ext = "") static inherited
Lists files in a directory, optionally filtered by extension.
Parameters
path The directory to search.
ext File extension filter. If empty, all files are listed.
Returns
A vector of filenames in the directory.
Definition at line 35 of file tools/cxx/io.cxx.
References tools::ends_with(), and tools::split().
Referenced by analysis::analysis(), analysis::check_cache(), io::check_root_file_paths(), dataloader::restore_graphs(), and io::trigger_pcm().
operator==()
bool graph_template::operator== (graph_template & p) inherited
Equality comparison operator.
Parameters
p The graph template to compare against.
Returns
True if templates have the same hash.
Definition at line 30 of file graph_template.cxx.
References graph_template::hash.
PreSelection()
bool graph_template::PreSelection () virtual inherited
Pre-selection filter for events.
Override to skip events that shouldn't produce graphs.
Returns
True to keep the event, false to skip.
Reimplemented in graph_jets.
Definition at line 204 of file graph_template.cxx.
put()
template<typename g > static void tools::put (std::vector< g * > * out, std::vector< g * > * src, std::vector< int > * trg) inline static inherited
Fills a vector with pointers from another vector based on a selection index.
Template Parameters
g The type of objects being pointed to.
Parameters
out Pointer to the output vector to fill.
src Pointer to the source vector to select from.
trg Pointer to a vector of indices for selection.
< Clear the output vector.
< Reserve space for the output elements.
< Loop through each selected index.
< Get the object at the selected index.
< Add it to the output vector.
< Mark the object as in use.
Definition at line 197 of file tools.h.
Referenced by dataloader::get_k_train_set(), dataloader::get_k_validation_set(), and dataloader::get_test_set().
rename()
void tools::rename (std::string start, std::string target) static inherited
Renames a file or directory.
Parameters
start The original path.
target The new path.
Definition at line 18 of file tools/cxx/io.cxx.
Referenced by dataloader::dump_graphs().
replace()
void tools::replace (std::string * in, std::string repl_str, std::string repl_with) static inherited
Replaces all occurrences of a substring in a string.
Parameters
in Pointer to the string to modify.
repl_str The substring to replace.
repl_with The replacement string.
Definition at line 5 of file strings.cxx.
Referenced by analysis::build_graphs(), analysis::check_cache(), dataloader::dump_graphs(), meta::get_campaign(), meta::parse_json(), and analysis::start().
set_name()
void graph_template::set_name (std::string * name, graph_template * ev) static private inherited
Definition at line 3 of file graph/cxx/properties.cxx.
References graph_template::data, graph_template::name, and event_t::name.
Referenced by graph_template::graph_template().
set_preselection()
void graph_template::set_preselection (bool * inpt, graph_template * ev) static private inherited
Definition at line 23 of file graph/cxx/properties.cxx.
References graph_template::m_preselection.
Referenced by graph_template::graph_template().
split()
std::vector< std::string > tools::split (std::string inpt, std::string del) inherited
Splits a string into a vector of substrings based on a delimiter.
Parameters
inpt The input string to split.
del The delimiter.
Returns
A vector of substrings.
Definition at line 23 of file strings.cxx.
References index.
Referenced by analysis::build_events(), analysis::build_graphs(), analysis::build_inference(), event_template::build_mapping(), analysis::check_cache(), container::compile(), sampletracer::compile_objects(), meta::compiler(), tools::create_path(), dataloader::dump_graphs(), meta::hash(), tools::ls(), graph_t::meta_deserialize(), dataloader::restore_graphs_(), io::root_begin(), model_template::set_device(), metric_template::set_run_name(), metric_template::set_variables(), and analysis::start().
sum()
template<typename g > g tools::sum (std::vector< g > * inpt) inline inherited
Sums the elements of a vector.
Template Parameters
g The type of elements in the vector.
Parameters
inpt Pointer to the vector to sum.
Returns
The sum of all elements.
< Initialize the output variable.
< Return the sum.
Definition at line 183 of file tools.h.
Referenced by metrics::add_th1f_accuracy(), sampletracer::compile_objects(), particle_template::DeltaR(), graph_template::double_neutrino(), grift::forward(), recursivegraphneuralnetwork::forward(), matching::match_obj(), and grift::message().
to_string() [1/2]
std::string tools::to_string (double val) static inherited
Converts a double value to a string with standard precision.
Parameters
val The double value to convert.
Returns
The string representation of the value.
Definition at line 59 of file strings.cxx.
Referenced by dataloader::generate_kfold_set(), dataloader::generate_test_set(), particle_template::get_hash(), topefficiency::region(), dataloader::restore_dataset(), event_template::set_hash(), selection_template::set_hash(), parton::strategy(), topjets::strategy(), toptruthjets::strategy(), and parton::top_mass_contribution().
to_string() [2/2]
std::string tools::to_string (double val, int prec) static inherited
Converts a double value to a string with specified precision.
Parameters
val The double value to convert.
prec The number of decimal places to consider.
Returns
The string representation of the value.
Definition at line 91 of file strings.cxx.
to_tensor()
template<typename G , typename g > torch::Tensor graph_template::to_tensor (std::vector< G > _data, at::ScalarType _op, g prim) inline private inherited
Definition at line 660 of file graph_template.h.
References build_tensor(), and graph_template::op.
Referenced by graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), and graph_template::define_topology().
trim()
std::string tools::trim (std::string s) inherited
Removes whitespace from the beginning and end of a string.
Parameters
s The string to trim.
Returns
The trimmed string.
type_name()
template<typename T > std::string tools::type_name () inline inherited
Gets the type name of a variable as a string (for debugging).
Template Parameters
T The type to get the name of.
Returns
The name of the type as a string.
< Gets the type name via RTTI.
< Returns the type name.
Definition at line 155 of file tools.h.
Referenced by event_template::build_mapping().
Member Data Documentation
_topological_index
std::vector<int> graph_template::_topological_index private inherited
Definition at line 688 of file graph_template.h.
Referenced by graph_template::add_edge_data_feature(), graph_template::add_edge_truth_feature(), graph_template::define_topology(), and graph_template::flush_particles().
_topology
std::vector<std::vector<int> > graph_template::_topology private inherited
Definition at line 687 of file graph_template.h.
Referenced by graph_template::define_topology(), and graph_template::flush_particles().
analysis
friend graph_template::analysis private inherited
Definition at line 605 of file graph_template.h.
container
friend graph_template::container private inherited
Definition at line 604 of file graph_template.h.
data
event_t graph_template::data private inherited
Definition at line 697 of file graph_template.h.
Referenced by graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::build(), graph_template::get_hash(), graph_template::get_index(), graph_template::get_tree(), graph_template::get_weight(), and graph_template::set_name().
edge_fx
std::map<std::string, torch::Tensor> graph_template::edge_fx = {} private inherited
Definition at line 685 of file graph_template.h.
Referenced by graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), and graph_template::data_export().
filename
std::string graph_template::filename = "" inherited
Source filename.
Definition at line 437 of file graph_template.h.
Referenced by graph_template::build().
graph_fx
std::map<std::string, torch::Tensor> graph_template::graph_fx = {} private inherited
Definition at line 683 of file graph_template.h.
Referenced by graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::data_export(), and graph_template::double_neutrino().
hash
cproperty<std::string, graph_template> graph_template::hash inherited
Unique hash identifier.
Definition at line 432 of file graph_template.h.
Referenced by graph_template::graph_template(), graph_template::define_particle_nodes(), and graph_template::operator==().
index
cproperty<long , graph_template> graph_template::index inherited
Event index property.
Definition at line 428 of file graph_template.h.
Referenced by graph_template::graph_template(), and graph_template::data_export().
m_event
event_template* graph_template::m_event = nullptr private inherited
Definition at line 692 of file graph_template.h.
Referenced by graph_template::build(), graph_template::flush_particles(), and graph_template::get_event().
m_preselection
bool graph_template::m_preselection = true private inherited
Definition at line 694 of file graph_template.h.
Referenced by graph_template::get_preselection(), and graph_template::set_preselection().
m_topology
torch::Tensor graph_template::m_topology private inherited
Definition at line 689 of file graph_template.h.
Referenced by graph_template::data_export(), and graph_template::define_topology().
meta_data
meta* graph_template::meta_data = nullptr inherited
Pointer to event metadata.
Definition at line 438 of file graph_template.h.
Referenced by graph_template::build().
name
cproperty<std::string, graph_template> graph_template::name inherited
Graph template name.
Definition at line 434 of file graph_template.h.
Referenced by graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_edge_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_graph_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::build(), and graph_template::set_name().
node_fx
std::map<std::string, torch::Tensor> graph_template::node_fx = {} private inherited
Definition at line 684 of file graph_template.h.
Referenced by graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::add_node_feature(), graph_template::data_export(), and graph_template::double_neutrino().
node_particles
std::map<int, particle_template*> graph_template::node_particles = {} private inherited
Definition at line 682 of file graph_template.h.
Referenced by graph_template::add_edge_data_feature(), graph_template::add_edge_truth_feature(), graph_template::add_node_data_feature(), graph_template::add_node_truth_feature(), graph_template::define_particle_nodes(), graph_template::define_topology(), and graph_template::flush_particles().
nodes
std::map<std::string, int> graph_template::nodes = {} private inherited
Definition at line 681 of file graph_template.h.
Referenced by CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), graph_detector::CompileEvent(), graph_template::define_particle_nodes(), and graph_template::flush_particles().
num_nodes
int graph_template::num_nodes = 0 private inherited
Definition at line 680 of file graph_template.h.
Referenced by graph_template::data_export(), and graph_template::define_particle_nodes().
op
torch::TensorOptions* graph_template::op = nullptr private inherited
Definition at line 691 of file graph_template.h.
Referenced by graph_template::graph_template(), graph_template::~graph_template(), and graph_template::to_tensor().
preselection
cproperty<bool , graph_template> graph_template::preselection inherited
Preselection result property.
Definition at line 430 of file graph_template.h.
Referenced by graph_template::graph_template(), graph_template::build(), and graph_template::data_export().
threadIdx
int graph_template::threadIdx = -1 inherited
Thread index for parallel processing.
Definition at line 436 of file graph_template.h.
tree
cproperty<std::string, graph_template> graph_template::tree inherited
Source tree name.
Definition at line 433 of file graph_template.h.
Referenced by graph_template::graph_template().
weight
cproperty<double, graph_template> graph_template::weight inherited
Event weight property.
Definition at line 429 of file graph_template.h.
Referenced by graph_template::graph_template(), and graph_template::data_export().
The documentation for this class was generated from the following files:
bsm_4tops/include/bsm_4tops/graphs.h
bsm_4tops/cxx/graphs.cxx