AnalysisG: meta Class Reference
meta Class Reference
Provides properties and methods for metadata management.
#include <meta.h>
Public Member Functions
meta ()
< Public access specifier for the following members.
~meta ()
Destructor for the meta class.
const folds_t * get_tags (std::string hash)
Retrieves tags based on a hash.
void scan_data (TObject *obj)
Scans data from a generic ROOT object (e.g., TTree, TH1).
void scan_sow (TObject *obj)
Scans sum of weights (SoW) information from a ROOT object.
void parse_json (std::string inpt)
Parses a JSON string to extract metadata.
std::string hash (std::string fname)
Generates a hash for a given filename.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
void set_prefix (std::string prefix)
Sets the prefix used in log messages from this instance.
std::string get_prefix ()
Returns the prefix currently used in log messages.
void Info (std::string msg, bool newline=true)
Outputs an info message.
void Warning (std::string msg, bool newline=true)
Outputs a warning message.
void Error (std::string msg, bool newline=true)
Outputs an error message.
void Debug (std::string msg, bool newline=true)
Outputs a debug message (only in debug mode).
void Message (std::string msg, std::string tag="", bool newline=true)
Outputs a message with custom formatting.
void set_debug_mode (bool dbg)
Enables or disables debug mode.
bool get_debug_mode ()
Returns the current status of debug mode.
void set_suppress_warning (bool sw)
Sets whether warnings should be suppressed.
bool get_suppress_warning ()
Returns the current warning suppression status.
void set_suppress_info (bool si)
Sets whether info messages should be suppressed.
bool get_suppress_info ()
Returns the current info message suppression status.
Static Public Member Functions
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Public Attributes
cproperty< bool, meta > isMC
Property: Indicates whether the dataset is Monte Carlo (MC) simulation (true) or real data (false).
cproperty< bool, meta > found
Property: Indicates whether the required metadata was successfully found and loaded.
cproperty< double, meta > eventNumber
Property: The number of events in the dataset or a specific file.
cproperty< double, meta > event_index
Property: An index related to events, possibly for iteration or identification.
cproperty< double, meta > totalSize
Property: The total size of the dataset, potentially in bytes or some other unit.
cproperty< double, meta > kfactor
Property: The k-factor, a theoretical correction factor used in physics calculations.
cproperty< double, meta > ecmEnergy
Property: The center-of-mass energy of the collision (e.g., in GeV or TeV).
cproperty< double, meta > genFiltEff
Property: The generator filter efficiency for MC simulations.
cproperty< double, meta > completion
Property: A measure of the dataset's processing completion, if applicable.
cproperty< double, meta > beam_energy
Property: The energy of the colliding beams.
cproperty< double, meta > cross_section_nb
Property: The physics process cross-section in nanobarns (nb).
cproperty< double, meta > cross_section_fb
Property: The physics process cross-section in femtobarns (fb).
cproperty< double, meta > cross_section_pb
Property: The physics process cross-section in picobarns (pb).
cproperty< double, meta > campaign_luminosity
Property: The integrated luminosity of the data-taking campaign.
cproperty< double, meta > sum_of_weights
Property: The sum of event weights, crucial for MC normalization.
cproperty< unsigned int, meta > dsid
Property: The Dataset Identifier (DSID), a unique number for the dataset.
cproperty< unsigned int, meta > nFiles
Property: The number of files associated with this dataset.
cproperty< unsigned int, meta > totalEvents
Property: The total number of events across all files in the dataset.
cproperty< unsigned int, meta > datasetNumber
Property: Another numerical identifier for the dataset, possibly synonymous with DSID.
cproperty< std::string, meta > derivationFormat
Property: The format of the derived data (e.g., DAOD_PHYS).
cproperty< std::string, meta > AMITag
Property: The AMI (ATLAS Metadata Interface) tag for the dataset.
cproperty< std::string, meta > generators
Property: Information about the Monte Carlo event generators used.
cproperty< std::string, meta > identifier
Property: A generic string identifier for the metadata or dataset.
cproperty< std::string, meta > DatasetName
Property: The human-readable name of the dataset.
cproperty< std::string, meta > prodsysStatus
Property: The status of the dataset in the production system.
cproperty< std::string, meta > dataType
Property: The type of data (e.g., "mc", "data").
cproperty< std::string, meta > version
Property: Version string for the dataset or metadata schema.
cproperty< std::string, meta > PDF
Property: Information about the Parton Density Function (PDF) used in MC generation.
cproperty< std::string, meta > AtlasRelease
Property: The ATLAS software release version used for processing.
cproperty< std::string, meta > principalPhysicsGroup
Property: The main physics group associated with this dataset (e.g., "SM", "SUSY").
cproperty< std::string, meta > physicsShort
Property: A short description of the physics process or analysis.
cproperty< std::string, meta > generatorName
Property: The specific name of the MC event generator.
cproperty< std::string, meta > geometryVersion
Property: The version of the detector geometry simulation used.
cproperty< std::string, meta > conditionsTag
Property: The tag for the detector conditions database.
cproperty< std::string, meta > generatorTune
Property: The specific tune (parameter set) of the MC generator.
cproperty< std::string, meta > amiStatus
Property: The status of the dataset in the AMI catalog.
cproperty< std::string, meta > beamType
Property: The type of colliding beams (e.g., "pp", "PbPb").
cproperty< std::string, meta > productionStep
Property: The step in the data production chain (e.g., "recon", "merge").
cproperty< std::string, meta > projectName
Property: The name of the project this dataset belongs to (e.g., "mc16_13TeV").
cproperty< std::string, meta > statsAlgorithm
Property: Algorithm used for statistical combination or analysis.
cproperty< std::string, meta > genFilterNames
Property: Names of any generator-level filters applied.
cproperty< std::string, meta > file_type
Property: The type of the file (e.g., "ROOT", "HDF5").
cproperty< std::string, meta > sample_name
Property: A user-defined name for the sample.
cproperty< std::string, meta > logicalDatasetName
Property: The Logical Dataset Name (LFN) as used in grid systems.
cproperty< std::string, meta > campaign
Property: The data-taking or simulation campaign (e.g., "mc16a", "Run2").
cproperty< std::vector< std::string >, meta > keywords
Property: A list of keywords associated with the dataset.
cproperty< std::vector< std::string >, meta > weights
Property: A list of weight names or definitions.
cproperty< std::vector< std::string >, meta > keyword
Property: (Possibly redundant with 'keywords') A list of keywords.
cproperty< std::vector< std::string >, meta > fileGUID
Property: A list of Globally Unique Identifiers (GUIDs) for the files.
cproperty< std::vector< int >, meta > events
Property: A list of event counts, possibly per file or run.
cproperty< std::vector< int >, meta > run_number
Property: A list of run numbers.
cproperty< std::vector< double >, meta > fileSize
Property: A list of file sizes.
cproperty< std::map< int, int >, meta > inputrange
Property: A map defining input ranges, possibly for event processing.
cproperty< std::map< int, std::string >, meta > inputfiles
Property: A map linking an index to input file names/paths.
cproperty< std::map< std::string, int >, meta > LFN
Property: A map from Logical File Names (LFNs) to an integer (e.g., count or index).
cproperty< std::map< std::string, weights_t >, meta > misc
Property: A map for miscellaneous weights or related information, using weights_t struct.
cproperty< std::map< std::string, std::string >, meta > config
Property: A map for general configuration settings as key-value string pairs.
Protected Attributes
std::string prefix = ""
Prefix used in log messages from this instance. Initialized as empty string.
bool debug_mode = false
Flag indicating whether debug mode is enabled. Initialized as false.
bool suppress_warnings = false
Flag indicating whether warnings are suppressed. Initialized as false.
bool suppress_info = false
Flag indicating whether info messages are suppressed. Initialized as false.
Private Member Functions
void compiler ()
Internal method to compile or process metadata after parsing.
float parse_float (std::string key, TTree *tr)
Parses a float value from a TTree based on a key.
std::string parse_string (std::string key, TTree *tr)
Parses a string value from a TTree based on a key.
Static Private Member Functions
static void get_isMC (bool *value, meta *instance)
Static getter for the isMC property.
static void get_found (bool *value, meta *instance)
Static getter for the found property.
static void get_eventNumber (double *value, meta *instance)
Static getter for the eventNumber property.
static void get_totalSize (double *value, meta *instance)
Static getter for the totalSize property.
static void get_event_index (double *value, meta *instance)
Static getter for the event_index property.
static void get_kfactor (double *value, meta *instance)
Static getter for the kfactor property.
static void get_ecmEnergy (double *value, meta *instance)
Static getter for the ecmEnergy property.
static void get_genFiltEff (double *value, meta *instance)
Static getter for the genFiltEff property.
static void get_completion (double *value, meta *instance)
Static getter for the completion property.
static void get_beam_energy (double *value, meta *instance)
Static getter for the beam_energy property.
static void get_cross_section_pb (double *value, meta *instance)
Static getter for the cross_section_pb property.
static void get_cross_section_nb (double *value, meta *instance)
Static getter for the cross_section_nb property.
static void get_cross_section_fb (double *value, meta *instance)
Static getter for the cross_section_fb property.
static void get_campaign_luminosity (double *value, meta *instance)
Static getter for the campaign_luminosity property.
static void get_dsid (unsigned int *value, meta *instance)
Static getter for the dsid property.
static void get_nFiles (unsigned int *value, meta *instance)
Static getter for the nFiles property.
static void get_totalEvents (unsigned int *value, meta *instance)
Static getter for the totalEvents property.
static void get_datasetNumber (unsigned int *value, meta *instance)
Static getter for the datasetNumber property.
static void get_derivationFormat (std::string *value, meta *instance)
Static getter for the derivationFormat property.
static void get_AMITag (std::string *value, meta *instance)
Static getter for the AMITag property.
static void get_generators (std::string *value, meta *instance)
Static getter for the generators property.
static void get_identifier (std::string *value, meta *instance)
Static getter for the identifier property.
static void get_DatasetName (std::string *value, meta *instance)
Static getter for the DatasetName property.
static void get_prodsysStatus (std::string *value, meta *instance)
Static getter for the prodsysStatus property.
static void get_dataType (std::string *value, meta *instance)
Static getter for the dataType property.
static void get_version (std::string *value, meta *instance)
Static getter for the version property.
static void get_PDF (std::string *value, meta *instance)
Static getter for the PDF property.
static void get_AtlasRelease (std::string *value, meta *instance)
Static getter for the AtlasRelease property.
static void get_principalPhysicsGroup (std::string *value, meta *instance)
Static getter for the principalPhysicsGroup property.
static void get_physicsShort (std::string *value, meta *instance)
Static getter for the physicsShort property.
static void get_generatorName (std::string *value, meta *instance)
Static getter for the generatorName property.
static void get_geometryVersion (std::string *value, meta *instance)
Static getter for the geometryVersion property.
static void get_conditionsTag (std::string *value, meta *instance)
Static getter for the conditionsTag property.
static void get_generatorTune (std::string *value, meta *instance)
Static getter for the generatorTune property.
static void get_amiStatus (std::string *value, meta *instance)
Static getter for the amiStatus property.
static void get_beamType (std::string *value, meta *instance)
Static getter for the beamType property.
static void get_productionStep (std::string *value, meta *instance)
Static getter for the productionStep property.
static void get_projectName (std::string *value, meta *instance)
Static getter for the projectName property.
static void get_statsAlgorithm (std::string *value, meta *instance)
Static getter for the statsAlgorithm property.
static void get_genFilterNames (std::string *value, meta *instance)
Static getter for the genFilterNames property.
static void get_file_type (std::string *value, meta *instance)
Static getter for the file_type property.
static void get_sample_name (std::string *value, meta *instance)
Static getter for the sample_name property.
static void get_logicalDatasetName (std::string *value, meta *instance)
Static getter for the logicalDatasetName property.
static void get_campaign (std::string *value, meta *instance)
Static getter for the campaign property.
static void get_keywords (std::vector< std::string > *value, meta *instance)
Static getter for the keywords property.
static void get_weights (std::vector< std::string > *value, meta *instance)
Static getter for the weights property.
static void get_keyword (std::vector< std::string > *value, meta *instance)
Static getter for the keyword property.
static void get_fileGUID (std::vector< std::string > *value, meta *instance)
Static getter for the fileGUID property.
static void get_events (std::vector< int > *value, meta *instance)
Static getter for the events property.
static void get_run_number (std::vector< int > *value, meta *instance)
Static getter for the run_number property.
static void get_fileSize (std::vector< double > *value, meta *instance)
Static getter for the fileSize property.
static void get_inputrange (std::map< int, int > *value, meta *instance)
Static getter for the inputrange property.
static void get_inputfiles (std::map< int, std::string > *value, meta *instance)
Static getter for the inputfiles property.
static void get_LFN (std::map< std::string, int > *value, meta *instance)
Static getter for the LFN property.
static void get_misc (std::map< std::string, weights_t > *value, meta *instance)
Static getter for the misc property.
static void get_config (std::map< std::string, std::string > *value, meta *instance)
Static getter for the config property.
static void get_sum_of_weights (double *value, meta *instance)
Static getter for the sum_of_weights property.
Private Attributes
rapidjson::Document * rpd = nullptr
< Private access specifier for the following members.
std::string metacache_path
String storing the path to a metadata cache, if used.
meta_t meta_data
Instance of meta_t struct, likely holding the raw or processed metadata values.
std::vector< folds_t > * folds = nullptr
Pointer to a vector of folds_t structures, possibly for k-fold data. Initialized to nullptr.
Friends
class analysis
Declares the analysis class as a friend, allowing it to access private members of meta.
Detailed Description
Provides properties and methods for metadata management.
The meta class inherits from tools (providing utility functions) and notification (providing logging/messaging capabilities). It offers a comprehensive interface for handling various metadata attributes such as event numbers, cross-sections, dataset information, and other parameters crucial for physics analysis. It supports reading metadata from ROOT files and JSON sources.
Definition at line 36 of file meta/include/meta/meta.h.
Constructor & Destructor Documentation
meta()
meta::meta ()
< Public access specifier for the following members.
Constructor for the meta class. Initializes a new instance of the meta class.
Definition at line 4 of file meta.cxx.
References amiStatus, AMITag, AtlasRelease, beam_energy, beamType, campaign, campaign_luminosity, completion, conditionsTag, config, cross_section_fb, cross_section_nb, cross_section_pb, DatasetName, datasetNumber, dataType, derivationFormat, dsid, ecmEnergy, event_index, eventNumber, events, file_type, fileGUID, fileSize, found, generatorName, generators, generatorTune, genFiltEff, genFilterNames, geometryVersion, get_amiStatus(), get_AMITag(), get_AtlasRelease(), get_beam_energy(), get_beamType(), get_campaign(), get_campaign_luminosity(), get_completion(), get_conditionsTag(), get_config(), get_cross_section_fb(), get_cross_section_nb(), get_cross_section_pb(), get_DatasetName(), get_datasetNumber(), get_dataType(), get_derivationFormat(), get_dsid(), get_ecmEnergy(), get_event_index(), get_eventNumber(), get_events(), get_file_type(), get_fileGUID(), get_fileSize(), get_found(), get_generatorName(), get_generators(), get_generatorTune(), get_genFiltEff(), get_genFilterNames(), get_geometryVersion(), get_identifier(), get_inputfiles(), get_inputrange(), get_isMC(), get_keyword(), get_keywords(), get_kfactor(), get_LFN(), get_logicalDatasetName(), get_misc(), get_nFiles(), get_PDF(), get_physicsShort(), get_principalPhysicsGroup(), get_prodsysStatus(), get_productionStep(), get_projectName(), get_run_number(), get_sample_name(), get_statsAlgorithm(), get_sum_of_weights(), get_totalEvents(), get_totalSize(), get_version(), get_weights(), identifier, inputfiles, inputrange, isMC, keyword, keywords, kfactor, LFN, logicalDatasetName, misc, nFiles, PDF, physicsShort, notification::prefix, principalPhysicsGroup, prodsysStatus, productionStep, projectName, run_number, sample_name, cproperty< T, G >::set_getter(), cproperty< T, G >::set_object(), statsAlgorithm, sum_of_weights, totalEvents, totalSize, version, and weights.
~meta()
meta::~meta ()
Destructor for the meta class.
Cleans up resources used by the meta instance, such as the RapidJSON document.
Definition at line 128 of file meta.cxx.
References rpd.
Member Function Documentation
absolute_path()
std::string tools::absolute_path (std::string path) static inherited
Converts a relative path to an absolute path.
Parameters
path The path to convert.
Returns
The absolute version of the path.
Definition at line 49 of file tools/cxx/io.cxx.
Referenced by analysis::analysis(), analysis::build_events(), io::check_root_file_paths(), and io::trigger_pcm().
compiler()
void meta::compiler () private
Internal method to compile or process metadata after parsing.
This might involve organizing, validating, or transforming the raw metadata.
Definition at line 154 of file meta.cxx.
References meta_t::AMITag, meta_t::config, meta_t::derivationFormat, meta_t::dsid, tools::has_string(), i, meta_t::inputfiles, meta_t::isMC, meta_data, rpd, meta_t::sample_name, and tools::split().
Referenced by parse_json().
create_path()
void tools::create_path (std::string path) static inherited
Creates a directory path, including parent directories if needed.
Parameters
path The directory path to create.
Definition at line 6 of file tools/cxx/io.cxx.
References f, and tools::split().
Referenced by analysis::analysis(), analysis::build_inference(), plotting::build_path(), analysis::build_project(), container::compile(), metrics::dump_mass_plots(), metric_template::execute(), metrics::generic_painter(), analysis::start(), io::start(), and io::trigger_pcm().
Debug()
void notification::Debug (std::string msg, bool newline = true) inherited
Outputs a debug message (only in debug mode).
Parameters
msg The debug message to output.
newline Whether to append a newline (default: true).
delete_path()
void tools::delete_path (std::string path) static inherited
Deletes a directory path and its contents.
Parameters
path The directory path to delete.
Definition at line 22 of file tools/cxx/io.cxx.
ends_with()
bool tools::ends_with (std::string * inpt, std::string val) static inherited
Checks if a string ends with a specific substring.
Parameters
inpt Pointer to the string to check.
val The substring to check for at the end.
Returns
True if the string ends with the substring, false otherwise.
Definition at line 71 of file strings.cxx.
References l.
Referenced by plotting::build_path(), io::check_root_file_paths(), dataloader::dump_graphs(), tools::ls(), parse_json(), io::scan_keys(), and analysis::start().
Error()
void notification::Error (std::string msg, bool newline = true) inherited
Outputs an error message.
Parameters
msg The error message to output.
newline Whether to append a newline (default: true).
extract()
template<typename C , typename T > static void tools::extract (std::vector< T > * prop, std::vector< C * > * src, void(*)(T *, C *) get_prop) inline static inherited
Extracts a specific property from a vector of objects into a new vector.
Template Parameters
C The type of objects in the source vector.
T The type of the property to extract.
Parameters
prop Pointer to the output vector to fill with property values.
src Pointer to the source vector of objects.
get_prop Function pointer to extract the property from an object.
< Clear the properties vector.
< Reserve space for the property values.
< Loop through each object in the source vector.
< Create a default-initialized property variable.
< Call the provided function to extract the property.
< Add the property value to the output vector.
Definition at line 216 of file tools.h.
flush()
template<typename T > static void tools::flush (std::vector< T * > * inpt) inline static inherited
Empties a vector and all objects it points to.
Template Parameters
T The type of pointers in the vector.
Parameters
inpt Pointer to the vector to empty.
< Loop through all elements in the vector.
< Delete the object the pointer points to.
< Set the pointer to nullptr to avoid dangling pointers.
< Clear the vector.
Definition at line 167 of file tools.h.
Referenced by analysis::~analysis(), dataloader::~dataloader(), sampletracer::compile_objects(), and io::root_end().
get_amiStatus()
void meta::get_amiStatus (std::string * value, meta * instance) static private
Static getter for the amiStatus property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 351 of file meta.cxx.
References meta_t::amiStatus, and meta_data.
Referenced by meta().
get_AMITag()
void meta::get_AMITag (std::string * value, meta * instance) static private
Static getter for the AMITag property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 336 of file meta.cxx.
References meta_t::AMITag, and meta_data.
Referenced by meta().
get_AtlasRelease()
void meta::get_AtlasRelease (std::string * value, meta * instance) static private
Static getter for the AtlasRelease property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 344 of file meta.cxx.
References meta_t::AtlasRelease, and meta_data.
Referenced by meta().
get_beam_energy()
void meta::get_beam_energy (double * value, meta * instance) static private
Static getter for the beam_energy property.
Parameters
[out] value Pointer to store the retrieved double value.
[in] instance Pointer to the meta instance.
Definition at line 328 of file meta.cxx.
References meta_t::beam_energy, and meta_data.
Referenced by meta().
get_beamType()
void meta::get_beamType (std::string * value, meta * instance) static private
Static getter for the beamType property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 352 of file meta.cxx.
References meta_t::beamType, and meta_data.
Referenced by meta().
get_campaign()
void meta::get_campaign (std::string * value, meta * instance) static private
Static getter for the campaign property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 314 of file meta.cxx.
References meta_t::campaign, meta_data, and tools::replace().
Referenced by meta().
get_campaign_luminosity()
void meta::get_campaign_luminosity (double * value, meta * instance) static private
Static getter for the campaign_luminosity property.
Parameters
[out] value Pointer to store the retrieved double value.
[in] instance Pointer to the meta instance.
Definition at line 330 of file meta.cxx.
References meta_t::campaign_luminosity, and meta_data.
Referenced by meta().
get_completion()
void meta::get_completion (double * value, meta * instance) static private
Static getter for the completion property.
Parameters
[out] value Pointer to store the retrieved double value.
[in] instance Pointer to the meta instance.
Definition at line 327 of file meta.cxx.
References meta_t::completion, and meta_data.
Referenced by meta().
get_conditionsTag()
void meta::get_conditionsTag (std::string * value, meta * instance) static private
Static getter for the conditionsTag property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 349 of file meta.cxx.
References meta_t::conditionsTag, and meta_data.
Referenced by meta().
get_config()
void meta::get_config (std::map< std::string, std::string > * value, meta * instance) static private
Static getter for the config property.
Parameters
[out] value Pointer to store the retrieved map of string to string.
[in] instance Pointer to the meta instance.
Definition at line 372 of file meta.cxx.
References meta_t::config, and meta_data.
Referenced by meta().
get_cross_section_fb()
void meta::get_cross_section_fb (double * value, meta * instance) static private
Static getter for the cross_section_fb property.
Parameters
[out] value Pointer to store the retrieved double value (femtobarns).
[in] instance Pointer to the meta instance.
Definition at line 300 of file meta.cxx.
References cross_section_nb.
Referenced by meta().
get_cross_section_nb()
void meta::get_cross_section_nb (double * value, meta * instance) static private
Static getter for the cross_section_nb property.
Parameters
[out] value Pointer to store the retrieved double value (nanobarns).
[in] instance Pointer to the meta instance.
Definition at line 308 of file meta.cxx.
References meta_t::crossSection_mean, and meta_data.
Referenced by meta().
get_cross_section_pb()
void meta::get_cross_section_pb (double * value, meta * instance) static private
Static getter for the cross_section_pb property.
Parameters
[out] value Pointer to store the retrieved double value (picobarns).
[in] instance Pointer to the meta instance.
Definition at line 304 of file meta.cxx.
References cross_section_nb.
Referenced by meta().
get_DatasetName()
void meta::get_DatasetName (std::string * value, meta * instance) static private
Static getter for the DatasetName property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 339 of file meta.cxx.
References meta_t::DatasetName, and meta_data.
Referenced by meta().
get_datasetNumber()
void meta::get_datasetNumber (unsigned int * value, meta * instance) static private
Static getter for the datasetNumber property.
Parameters
[out] value Pointer to store the retrieved unsigned int value.
[in] instance Pointer to the meta instance.
Definition at line 334 of file meta.cxx.
References meta_t::datasetNumber, and meta_data.
Referenced by meta().
get_dataType()
void meta::get_dataType (std::string * value, meta * instance) static private
Static getter for the dataType property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 341 of file meta.cxx.
References meta_t::dataType, and meta_data.
Referenced by meta().
get_debug_mode()
bool notification::get_debug_mode () inherited
Returns the current status of debug mode.
Returns
Boolean indicating whether debug mode is enabled (true) or disabled (false).
get_derivationFormat()
void meta::get_derivationFormat (std::string * value, meta * instance) static private
Static getter for the derivationFormat property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 335 of file meta.cxx.
References meta_t::derivationFormat, and meta_data.
Referenced by meta().
get_dsid()
void meta::get_dsid (unsigned int * value, meta * instance) static private
Static getter for the dsid property.
Parameters
[out] value Pointer to store the retrieved unsigned int value.
[in] instance Pointer to the meta instance.
Definition at line 331 of file meta.cxx.
References meta_t::dsid, and meta_data.
Referenced by meta().
get_ecmEnergy()
void meta::get_ecmEnergy (double * value, meta * instance) static private
Static getter for the ecmEnergy property.
Parameters
[out] value Pointer to store the retrieved double value.
[in] instance Pointer to the meta instance.
Definition at line 325 of file meta.cxx.
References meta_t::ecmEnergy, and meta_data.
Referenced by meta().
get_event_index()
void meta::get_event_index (double * value, meta * instance) static private
Static getter for the event_index property.
Parameters
[out] value Pointer to store the retrieved double value.
[in] instance Pointer to the meta instance.
Definition at line 322 of file meta.cxx.
References meta_t::event_index, and meta_data.
Referenced by meta().
get_eventNumber()
void meta::get_eventNumber (double * value, meta * instance) static private
Static getter for the eventNumber property.
Parameters
[out] value Pointer to store the retrieved double value.
[in] instance Pointer to the meta instance.
Definition at line 321 of file meta.cxx.
References meta_t::eventNumber, and meta_data.
Referenced by meta().
get_events()
void meta::get_events (std::vector< int > * value, meta * instance) static private
Static getter for the events property.
Parameters
[out] value Pointer to store the retrieved vector of integers.
[in] instance Pointer to the meta instance.
Definition at line 365 of file meta.cxx.
References meta_t::events, and meta_data.
Referenced by meta(), and sampletracer::get_events().
get_file_type()
void meta::get_file_type (std::string * value, meta * instance) static private
Static getter for the file_type property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 357 of file meta.cxx.
References meta_t::file_type, and meta_data.
Referenced by meta().
get_fileGUID()
void meta::get_fileGUID (std::vector< std::string > * value, meta * instance) static private
Static getter for the fileGUID property.
Parameters
[out] value Pointer to store the retrieved vector of strings (GUIDs).
[in] instance Pointer to the meta instance.
Definition at line 364 of file meta.cxx.
References meta_t::fileGUID, and meta_data.
Referenced by meta().
get_fileSize()
void meta::get_fileSize (std::vector< double > * value, meta * instance) static private
Static getter for the fileSize property.
Parameters
[out] value Pointer to store the retrieved vector of doubles.
[in] instance Pointer to the meta instance.
Definition at line 367 of file meta.cxx.
References meta_t::fileSize, and meta_data.
Referenced by meta().
get_found()
void meta::get_found (bool * value, meta * instance) static private
Static getter for the found property.
Parameters
[out] value Pointer to store the retrieved boolean value.
[in] instance Pointer to the meta instance.
Definition at line 320 of file meta.cxx.
References meta_t::found, and meta_data.
Referenced by meta().
get_generatorName()
void meta::get_generatorName (std::string * value, meta * instance) static private
Static getter for the generatorName property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 347 of file meta.cxx.
References meta_t::generatorName, and meta_data.
Referenced by meta().
get_generators()
void meta::get_generators (std::string * value, meta * instance) static private
Static getter for the generators property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 337 of file meta.cxx.
References meta_t::generators, and meta_data.
Referenced by meta().
get_generatorTune()
void meta::get_generatorTune (std::string * value, meta * instance) static private
Static getter for the generatorTune property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 350 of file meta.cxx.
References meta_t::generatorTune, and meta_data.
Referenced by meta().
get_genFiltEff()
void meta::get_genFiltEff (double * value, meta * instance) static private
Static getter for the genFiltEff property.
Parameters
[out] value Pointer to store the retrieved double value.
[in] instance Pointer to the meta instance.
Definition at line 326 of file meta.cxx.
References meta_t::genFiltEff, and meta_data.
Referenced by meta().
get_genFilterNames()
void meta::get_genFilterNames (std::string * value, meta * instance) static private
Static getter for the genFilterNames property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 356 of file meta.cxx.
References meta_t::genFilterNames, and meta_data.
Referenced by meta().
get_geometryVersion()
void meta::get_geometryVersion (std::string * value, meta * instance) static private
Static getter for the geometryVersion property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 348 of file meta.cxx.
References meta_t::geometryVersion, and meta_data.
Referenced by meta().
get_identifier()
void meta::get_identifier (std::string * value, meta * instance) static private
Static getter for the identifier property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 338 of file meta.cxx.
References meta_t::identifier, and meta_data.
Referenced by meta().
get_inputfiles()
void meta::get_inputfiles (std::map< int, std::string > * value, meta * instance) static private
Static getter for the inputfiles property.
Parameters
[out] value Pointer to store the retrieved map of int to string.
[in] instance Pointer to the meta instance.
Definition at line 369 of file meta.cxx.
References meta_t::inputfiles, and meta_data.
Referenced by meta().
get_inputrange()
void meta::get_inputrange (std::map< int, int > * value, meta * instance) static private
Static getter for the inputrange property.
Parameters
[out] value Pointer to store the retrieved map of int to int.
[in] instance Pointer to the meta instance.
Definition at line 368 of file meta.cxx.
References meta_t::inputrange, and meta_data.
Referenced by meta().
get_isMC()
void meta::get_isMC (bool * value, meta * instance) static private
Static getter for the isMC property.
Parameters
[out] value Pointer to store the retrieved boolean value.
[in] instance Pointer to the meta instance from which to get the value.
Definition at line 319 of file meta.cxx.
References meta_t::isMC, and meta_data.
Referenced by meta().
get_keyword()
void meta::get_keyword (std::vector< std::string > * value, meta * instance) static private
Static getter for the keyword property.
Parameters
[out] value Pointer to store the retrieved vector of strings.
[in] instance Pointer to the meta instance.
Definition at line 363 of file meta.cxx.
References meta_t::keyword, and meta_data.
Referenced by meta().
get_keywords()
void meta::get_keywords (std::vector< std::string > * value, meta * instance) static private
Static getter for the keywords property.
Parameters
[out] value Pointer to store the retrieved vector of strings.
[in] instance Pointer to the meta instance.
Definition at line 361 of file meta.cxx.
References meta_t::keywords, and meta_data.
Referenced by meta().
get_kfactor()
void meta::get_kfactor (double * value, meta * instance) static private
Static getter for the kfactor property.
Parameters
[out] value Pointer to store the retrieved double value.
[in] instance Pointer to the meta instance.
Definition at line 324 of file meta.cxx.
References meta_t::kfactor, and meta_data.
Referenced by meta().
get_LFN()
void meta::get_LFN (std::map< std::string, int > * value, meta * instance) static private
Static getter for the LFN property.
Parameters
[out] value Pointer to store the retrieved map of string to int.
[in] instance Pointer to the meta instance.
Definition at line 370 of file meta.cxx.
References meta_t::LFN, and meta_data.
Referenced by meta().
get_logicalDatasetName()
void meta::get_logicalDatasetName (std::string * value, meta * instance) static private
Static getter for the logicalDatasetName property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 359 of file meta.cxx.
References meta_t::logicalDatasetName, and meta_data.
Referenced by meta().
get_misc()
void meta::get_misc (std::map< std::string, weights_t > * value, meta * instance) static private
Static getter for the misc property.
Parameters
[out] value Pointer to store the retrieved map of string to weights_t.
[in] instance Pointer to the meta instance.
Definition at line 371 of file meta.cxx.
References meta_data, and meta_t::misc.
Referenced by meta().
get_nFiles()
void meta::get_nFiles (unsigned int * value, meta * instance) static private
Static getter for the nFiles property.
Parameters
[out] value Pointer to store the retrieved unsigned int value.
[in] instance Pointer to the meta instance.
Definition at line 332 of file meta.cxx.
References meta_data, and meta_t::nFiles.
Referenced by meta().
get_PDF()
void meta::get_PDF (std::string * value, meta * instance) static private
Static getter for the PDF property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 343 of file meta.cxx.
References meta_data, and meta_t::PDF.
Referenced by meta().
get_physicsShort()
void meta::get_physicsShort (std::string * value, meta * instance) static private
Static getter for the physicsShort property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 346 of file meta.cxx.
References meta_data, and meta_t::physicsShort.
Referenced by meta().
get_prefix()
std::string notification::get_prefix () inherited
Returns the prefix currently used in log messages.
Returns
The current prefix string.
get_principalPhysicsGroup()
void meta::get_principalPhysicsGroup (std::string * value, meta * instance) static private
Static getter for the principalPhysicsGroup property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 345 of file meta.cxx.
References meta_data, and meta_t::principalPhysicsGroup.
Referenced by meta().
get_prodsysStatus()
void meta::get_prodsysStatus (std::string * value, meta * instance) static private
Static getter for the prodsysStatus property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 340 of file meta.cxx.
References meta_data, and meta_t::prodsysStatus.
Referenced by meta().
get_productionStep()
void meta::get_productionStep (std::string * value, meta * instance) static private
Static getter for the productionStep property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 353 of file meta.cxx.
References meta_data, and meta_t::productionStep.
Referenced by meta().
get_projectName()
void meta::get_projectName (std::string * value, meta * instance) static private
Static getter for the projectName property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 354 of file meta.cxx.
References meta_data, and meta_t::projectName.
Referenced by meta().
get_run_number()
void meta::get_run_number (std::vector< int > * value, meta * instance) static private
Static getter for the run_number property.
Parameters
[out] value Pointer to store the retrieved vector of integers.
[in] instance Pointer to the meta instance.
Definition at line 366 of file meta.cxx.
References meta_data, and meta_t::run_number.
Referenced by meta().
get_sample_name()
void meta::get_sample_name (std::string * value, meta * instance) static private
Static getter for the sample_name property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 358 of file meta.cxx.
References meta_data, and meta_t::sample_name.
Referenced by meta().
get_statsAlgorithm()
void meta::get_statsAlgorithm (std::string * value, meta * instance) static private
Static getter for the statsAlgorithm property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 355 of file meta.cxx.
References meta_data, and meta_t::statsAlgorithm.
Referenced by meta().
get_sum_of_weights()
void meta::get_sum_of_weights (double * value, meta * instance) static private
Static getter for the sum_of_weights property.
Parameters
[out] value Pointer to store the retrieved double value.
[in] instance Pointer to the meta instance.
Definition at line 281 of file meta.cxx.
References misc.
Referenced by meta().
get_suppress_info()
bool notification::get_suppress_info () inherited
Returns the current info message suppression status.
Returns
Boolean indicating whether info messages are suppressed (true) or shown (false).
get_suppress_warning()
bool notification::get_suppress_warning () inherited
Returns the current warning suppression status.
Returns
Boolean indicating whether warnings are suppressed (true) or shown (false).
get_tags()
const folds_t * meta::get_tags (std::string hash)
Retrieves tags based on a hash.
Parameters
hash The hash string used to identify and retrieve the specific set of tags.
Returns
A constant pointer to a folds_t structure containing the tags, or nullptr if not found.
Definition at line 291 of file meta.cxx.
References folds, and hash().
get_totalEvents()
void meta::get_totalEvents (unsigned int * value, meta * instance) static private
Static getter for the totalEvents property.
Parameters
[out] value Pointer to store the retrieved unsigned int value.
[in] instance Pointer to the meta instance.
Definition at line 333 of file meta.cxx.
References meta_data, and meta_t::totalEvents.
Referenced by meta().
get_totalSize()
void meta::get_totalSize (double * value, meta * instance) static private
Static getter for the totalSize property.
Parameters
[out] value Pointer to store the retrieved double value.
[in] instance Pointer to the meta instance.
Definition at line 323 of file meta.cxx.
References meta_data, and meta_t::totalSize.
Referenced by meta().
get_version()
void meta::get_version (std::string * value, meta * instance) static private
Static getter for the version property.
Parameters
[out] value Pointer to store the retrieved string value.
[in] instance Pointer to the meta instance.
Definition at line 342 of file meta.cxx.
References meta_data, and meta_t::version.
Referenced by meta().
get_weights()
void meta::get_weights (std::vector< std::string > * value, meta * instance) static private
Static getter for the weights property.
Parameters
[out] value Pointer to store the retrieved vector of strings.
[in] instance Pointer to the meta instance.
Definition at line 362 of file meta.cxx.
References meta_data, and meta_t::weights.
Referenced by meta().
has_string()
bool tools::has_string (std::string * inpt, std::string trg) static inherited
Checks if a string contains a specific substring.
Parameters
inpt Pointer to the string to check.
trg The substring to search for.
Returns
True if the substring is found, false otherwise.
Definition at line 65 of file strings.cxx.
References f.
Referenced by analysis::check_cache(), compiler(), metrics::generic_painter(), dataloader::restore_graphs_(), scan_sow(), model_template::set_device(), and metric_template::set_run_name().
has_value()
bool tools::has_value (std::vector< std::string > * data, std::string trg) static inherited
Checks if a vector of strings contains a specific string.
Parameters
data Pointer to the vector to search.
trg The string to search for.
Returns
True if the string is found in the vector, false otherwise.
Definition at line 77 of file strings.cxx.
Referenced by io::scan_keys().
hash()
std::string meta::hash (std::string fname)
Generates a hash for a given filename.
This hash can be used for caching or uniquely identifying file-specific metadata.
Parameters
fname The filename (or path) for which to generate the hash.
Returns
The generated hash string.
Definition at line 274 of file meta.cxx.
References tools::split().
Referenced by get_tags().
Info()
void notification::Info (std::string msg, bool newline = true) inherited
Outputs an info message.
Parameters
msg The message to output.
newline Whether to append a newline (default: true).
is_file()
bool tools::is_file (std::string path) static inherited
Checks if a path refers to an existing file.
Parameters
path The path to check.
Returns
True if the path is a file and exists, false otherwise.
Definition at line 30 of file tools/cxx/io.cxx.
Referenced by io::check_root_file_paths(), analysis::initialize_loop(), metric_template::set_run_name(), and io::start().
ls()
std::vector< std::string > tools::ls (std::string path, std::string ext = "") static inherited
Lists files in a directory, optionally filtered by extension.
Parameters
path The directory to search.
ext File extension filter. If empty, all files are listed.
Returns
A vector of filenames in the directory.
Definition at line 35 of file tools/cxx/io.cxx.
References tools::ends_with(), and tools::split().
Referenced by analysis::analysis(), analysis::check_cache(), io::check_root_file_paths(), dataloader::restore_graphs(), and io::trigger_pcm().
Message()
void notification::Message (std::string msg, std::string tag = "", bool newline = true) inherited
Outputs a message with custom formatting.
Parameters
msg The message to output.
tag A custom tag to prepend to the message.
newline Whether to append a newline (default: true).
parse_float()
float meta::parse_float (std::string key, TTree * tr) private
Parses a float value from a TTree based on a key.
Parameters
key The key (branch/leaf name) to look for in the TTree.
tr Pointer to the TTree to parse from.
Returns
The parsed float value. Returns 0 if not found or on error.
Definition at line 208 of file meta.cxx.
Referenced by scan_sow().
parse_json()
void meta::parse_json (std::string inpt)
Parses a JSON string to extract metadata.
Parameters
inpt The JSON string containing metadata to be parsed.
Definition at line 133 of file meta.cxx.
References compiler(), tools::ends_with(), f, tools::replace(), and rpd.
Referenced by scan_data().
parse_string()
std::string meta::parse_string (std::string key, TTree * tr) private
Parses a string value from a TTree based on a key.
Parameters
key The key (branch/leaf name) to look for in the TTree.
tr Pointer to the TTree to parse from.
Returns
The parsed string value. Returns empty string if not found or on error.
Definition at line 213 of file meta.cxx.
Referenced by scan_data(), and scan_sow().
put()
template<typename g > static void tools::put (std::vector< g * > * out, std::vector< g * > * src, std::vector< int > * trg) inline static inherited
Fills a vector with pointers from another vector based on a selection index.
Template Parameters
g The type of objects being pointed to.
Parameters
out Pointer to the output vector to fill.
src Pointer to the source vector to select from.
trg Pointer to a vector of indices for selection.
< Clear the output vector.
< Reserve space for the output elements.
< Loop through each selected index.
< Get the object at the selected index.
< Add it to the output vector.
< Mark the object as in use.
Definition at line 197 of file tools.h.
Referenced by dataloader::get_k_train_set(), dataloader::get_k_validation_set(), and dataloader::get_test_set().
rename()
void tools::rename (std::string start, std::string target) static inherited
Renames a file or directory.
Parameters
start The original path.
target The new path.
Definition at line 18 of file tools/cxx/io.cxx.
Referenced by dataloader::dump_graphs().
replace()
void tools::replace (std::string * in, std::string repl_str, std::string repl_with) static inherited
Replaces all occurrences of a substring in a string.
Parameters
in Pointer to the string to modify.
repl_str The substring to replace.
repl_with The replacement string.
Definition at line 5 of file strings.cxx.
Referenced by analysis::build_graphs(), analysis::check_cache(), dataloader::dump_graphs(), get_campaign(), parse_json(), and analysis::start().
scan_data()
void meta::scan_data (TObject * obj)
Scans data from a generic ROOT object (e.g., TTree, TH1).
This method is likely used to extract metadata embedded within ROOT objects.
Parameters
obj Pointer to the ROOT TObject to scan for metadata.
Definition at line 200 of file meta.cxx.
References meta_data, parse_json(), parse_string(), and scan_sow().
scan_sow()
void meta::scan_sow (TObject * obj)
Scans sum of weights (SoW) information from a ROOT object.
This is often important for normalizing Monte Carlo simulations.
Parameters
obj Pointer to the ROOT TObject to scan for sum of weights information.
Definition at line 226 of file meta.cxx.
References meta_t::AMITag, meta_t::campaign, dsid, meta_t::dsid, tools::has_string(), meta_t::inputfiles, meta_data, meta_t::misc, parse_float(), and parse_string().
Referenced by scan_data().
set_debug_mode()
void notification::set_debug_mode (bool dbg) inherited
Enables or disables debug mode.
Parameters
dbg Boolean flag, set to true to enable debug messages, false to disable.
set_prefix()
void notification::set_prefix (std::string prefix) inherited
Sets the prefix used in log messages from this instance.
Parameters
prefix The string to use as a prefix for log messages.
set_suppress_info()
void notification::set_suppress_info (bool si) inherited
Sets whether info messages should be suppressed.
Parameters
si Boolean flag, set to true to suppress info messages, false to show them.
set_suppress_warning()
void notification::set_suppress_warning (bool sw) inherited
Sets whether warnings should be suppressed.
Parameters
sw Boolean flag, set to true to suppress warnings, false to show them.
split()
std::vector< std::string > tools::split (std::string inpt, std::string del) inherited
Splits a string into a vector of substrings based on a delimiter.
Parameters
inpt The input string to split.
del The delimiter.
Returns
A vector of substrings.
Definition at line 23 of file strings.cxx.
References index.
Referenced by analysis::build_events(), analysis::build_graphs(), analysis::build_inference(), event_template::build_mapping(), analysis::check_cache(), container::compile(), sampletracer::compile_objects(), compiler(), tools::create_path(), dataloader::dump_graphs(), hash(), tools::ls(), graph_t::meta_deserialize(), dataloader::restore_graphs_(), io::root_begin(), model_template::set_device(), metric_template::set_run_name(), metric_template::set_variables(), and analysis::start().
sum()
template<typename g > g tools::sum (std::vector< g > * inpt) inline inherited
Sums the elements of a vector.
Template Parameters
g The type of elements in the vector.
Parameters
inpt Pointer to the vector to sum.
Returns
The sum of all elements.
< Initialize the output variable.
< Return the sum.
Definition at line 183 of file tools.h.
Referenced by metrics::add_th1f_accuracy(), sampletracer::compile_objects(), particle_template::DeltaR(), graph_template::double_neutrino(), grift::forward(), recursivegraphneuralnetwork::forward(), matching::match_obj(), and grift::message().
to_string() [1/2]
std::string tools::to_string (double val) static inherited
Converts a double value to a string with standard precision.
Parameters
val The double value to convert.
Returns
The string representation of the value.
Definition at line 59 of file strings.cxx.
Referenced by dataloader::generate_kfold_set(), dataloader::generate_test_set(), particle_template::get_hash(), topefficiency::region(), dataloader::restore_dataset(), event_template::set_hash(), selection_template::set_hash(), parton::strategy(), topjets::strategy(), toptruthjets::strategy(), and parton::top_mass_contribution().
to_string() [2/2]
std::string tools::to_string (double val, int prec) static inherited
Converts a double value to a string with specified precision.
Parameters
val The double value to convert.
prec The number of decimal places to consider.
Returns
The string representation of the value.
Definition at line 91 of file strings.cxx.
trim()
std::string tools::trim (std::string s) inherited
Removes whitespace from the beginning and end of a string.
Parameters
s The string to trim.
Returns
The trimmed string.
type_name()
template<typename T > std::string tools::type_name () inline inherited
Gets the type name of a variable as a string (for debugging).
Template Parameters
T The type to get the name of.
Returns
The name of the type as a string.
< Gets the type name via RTTI.
< Returns the type name.
Definition at line 155 of file tools.h.
Referenced by event_template::build_mapping().
Warning()
void notification::Warning (std::string msg, bool newline = true) inherited
Outputs a warning message.
Parameters
msg The warning message to output.
newline Whether to append a newline (default: true).
Referenced by io::read(), io::read(), io::write(), and io::write().
Friends And Related Symbol Documentation
analysis
friend class analysis friend
Declares the analysis class as a friend, allowing it to access private members of meta.
Definition at line 158 of file meta/include/meta/meta.h.
Member Data Documentation
amiStatus
cproperty<std::string, meta> meta::amiStatus
Property: The status of the dataset in the AMI catalog.
Definition at line 125 of file meta/include/meta/meta.h.
Referenced by meta().
AMITag
cproperty<std::string, meta> meta::AMITag
Property: The AMI (ATLAS Metadata Interface) tag for the dataset.
Definition at line 110 of file meta/include/meta/meta.h.
Referenced by meta().
AtlasRelease
cproperty<std::string, meta> meta::AtlasRelease
Property: The ATLAS software release version used for processing.
Definition at line 118 of file meta/include/meta/meta.h.
Referenced by meta().
beam_energy
cproperty<double, meta> meta::beam_energy
Property: The energy of the colliding beams.
Definition at line 95 of file meta/include/meta/meta.h.
Referenced by meta().
beamType
cproperty<std::string, meta> meta::beamType
Property: The type of colliding beams (e.g., "pp", "PbPb").
Definition at line 126 of file meta/include/meta/meta.h.
Referenced by meta().
campaign
cproperty<std::string, meta> meta::campaign
Property: The data-taking or simulation campaign (e.g., "mc16a", "Run2").
Definition at line 134 of file meta/include/meta/meta.h.
Referenced by meta().
campaign_luminosity
cproperty<double, meta> meta::campaign_luminosity
Property: The integrated luminosity of the data-taking campaign.
Definition at line 101 of file meta/include/meta/meta.h.
Referenced by meta().
completion
cproperty<double, meta> meta::completion
Property: A measure of the dataset's processing completion, if applicable.
Definition at line 94 of file meta/include/meta/meta.h.
Referenced by meta().
conditionsTag
cproperty<std::string, meta> meta::conditionsTag
Property: The tag for the detector conditions database.
Definition at line 123 of file meta/include/meta/meta.h.
Referenced by meta().
config
cproperty<std::map<std::string, std::string>, meta> meta::config
Property: A map for general configuration settings as key-value string pairs.
Definition at line 151 of file meta/include/meta/meta.h.
Referenced by meta().
cross_section_fb
cproperty<double, meta> meta::cross_section_fb
Property: The physics process cross-section in femtobarns (fb).
Definition at line 98 of file meta/include/meta/meta.h.
Referenced by meta().
cross_section_nb
cproperty<double, meta> meta::cross_section_nb
Property: The physics process cross-section in nanobarns (nb).
Definition at line 97 of file meta/include/meta/meta.h.
Referenced by meta(), get_cross_section_fb(), and get_cross_section_pb().
cross_section_pb
cproperty<double, meta> meta::cross_section_pb
Property: The physics process cross-section in picobarns (pb).
Definition at line 99 of file meta/include/meta/meta.h.
Referenced by meta().
DatasetName
cproperty<std::string, meta> meta::DatasetName
Property: The human-readable name of the dataset.
Definition at line 113 of file meta/include/meta/meta.h.
Referenced by meta().
datasetNumber
cproperty<unsigned int, meta> meta::datasetNumber
Property: Another numerical identifier for the dataset, possibly synonymous with DSID.
Definition at line 107 of file meta/include/meta/meta.h.
Referenced by meta().
dataType
cproperty<std::string, meta> meta::dataType
Property: The type of data (e.g., "mc", "data").
Definition at line 115 of file meta/include/meta/meta.h.
Referenced by meta().
debug_mode
bool notification::debug_mode = false protected inherited
Flag indicating whether debug mode is enabled. Initialized as false.
Definition at line 127 of file notification.h.
Referenced by analysis::build_metric().
derivationFormat
cproperty<std::string, meta> meta::derivationFormat
Property: The format of the derived data (e.g., DAOD_PHYS).
Definition at line 109 of file meta/include/meta/meta.h.
Referenced by meta().
dsid
cproperty<unsigned int, meta> meta::dsid
Property: The Dataset Identifier (DSID), a unique number for the dataset.
Definition at line 104 of file meta/include/meta/meta.h.
Referenced by meta(), and scan_sow().
ecmEnergy
cproperty<double, meta> meta::ecmEnergy
Property: The center-of-mass energy of the collision (e.g., in GeV or TeV).
Definition at line 92 of file meta/include/meta/meta.h.
Referenced by meta().
event_index
cproperty<double, meta> meta::event_index
Property: An index related to events, possibly for iteration or identification.
Definition at line 89 of file meta/include/meta/meta.h.
Referenced by meta().
eventNumber
cproperty<double, meta> meta::eventNumber
Property: The number of events in the dataset or a specific file.
Definition at line 88 of file meta/include/meta/meta.h.
Referenced by meta().
events
cproperty<std::vector<int>, meta> meta::events
Property: A list of event counts, possibly per file or run.
Definition at line 141 of file meta/include/meta/meta.h.
Referenced by meta().
file_type
cproperty<std::string, meta> meta::file_type
Property: The type of the file (e.g., "ROOT", "HDF5").
Definition at line 131 of file meta/include/meta/meta.h.
Referenced by meta().
fileGUID
cproperty<std::vector<std::string>, meta> meta::fileGUID
Property: A list of Globally Unique Identifiers (GUIDs) for the files.
Definition at line 139 of file meta/include/meta/meta.h.
Referenced by meta().
fileSize
cproperty<std::vector<double>, meta> meta::fileSize
Property: A list of file sizes.
Definition at line 143 of file meta/include/meta/meta.h.
Referenced by meta().
folds
std::vector<folds_t>* meta::folds = nullptr private
Pointer to a vector of folds_t structures, possibly for k-fold data. Initialized to nullptr.
Definition at line 165 of file meta/include/meta/meta.h.
Referenced by get_tags().
found
cproperty<bool, meta> meta::found
Property: Indicates whether the required metadata was successfully found and loaded.
Definition at line 87 of file meta/include/meta/meta.h.
Referenced by meta().
generatorName
cproperty<std::string, meta> meta::generatorName
Property: The specific name of the MC event generator.
Definition at line 121 of file meta/include/meta/meta.h.
Referenced by meta().
generators
cproperty<std::string, meta> meta::generators
Property: Information about the Monte Carlo event generators used.
Definition at line 111 of file meta/include/meta/meta.h.
Referenced by meta().
generatorTune
cproperty<std::string, meta> meta::generatorTune
Property: The specific tune (parameter set) of the MC generator.
Definition at line 124 of file meta/include/meta/meta.h.
Referenced by meta().
genFiltEff
cproperty<double, meta> meta::genFiltEff
Property: The generator filter efficiency for MC simulations.
Definition at line 93 of file meta/include/meta/meta.h.
Referenced by meta().
genFilterNames
cproperty<std::string, meta> meta::genFilterNames
Property: Names of any generator-level filters applied.
Definition at line 130 of file meta/include/meta/meta.h.
Referenced by meta().
geometryVersion
cproperty<std::string, meta> meta::geometryVersion
Property: The version of the detector geometry simulation used.
Definition at line 122 of file meta/include/meta/meta.h.
Referenced by meta().
identifier
cproperty<std::string, meta> meta::identifier
Property: A generic string identifier for the metadata or dataset.
Definition at line 112 of file meta/include/meta/meta.h.
Referenced by meta().
inputfiles
cproperty<std::map<int, std::string>, meta> meta::inputfiles
Property: A map linking an index to input file names/paths.
Definition at line 146 of file meta/include/meta/meta.h.
Referenced by meta().
inputrange
cproperty<std::map<int, int>, meta> meta::inputrange
Property: A map defining input ranges, possibly for event processing.
Definition at line 145 of file meta/include/meta/meta.h.
Referenced by meta().
isMC
cproperty<bool, meta> meta::isMC
Property: Indicates whether the dataset is Monte Carlo (MC) simulation (true) or real data (false).
Definition at line 86 of file meta/include/meta/meta.h.
Referenced by meta().
keyword
cproperty<std::vector<std::string>, meta> meta::keyword
Property: (Possibly redundant with 'keywords') A list of keywords.
Definition at line 138 of file meta/include/meta/meta.h.
Referenced by meta().
keywords
cproperty<std::vector<std::string>, meta> meta::keywords
Property: A list of keywords associated with the dataset.
Definition at line 136 of file meta/include/meta/meta.h.
Referenced by meta().
kfactor
cproperty<double, meta> meta::kfactor
Property: The k-factor, a theoretical correction factor used in physics calculations.
Definition at line 91 of file meta/include/meta/meta.h.
Referenced by meta().
LFN
cproperty<std::map<std::string, int>, meta> meta::LFN
Property: A map from Logical File Names (LFNs) to an integer (e.g., count or index).
Definition at line 148 of file meta/include/meta/meta.h.
Referenced by meta().
logicalDatasetName
cproperty<std::string, meta> meta::logicalDatasetName
Property: The Logical Dataset Name (LFN) as used in grid systems.
Definition at line 133 of file meta/include/meta/meta.h.
Referenced by meta().
meta_data
meta_t meta::meta_data private
Instance of meta_t struct, likely holding the raw or processed metadata values.
Definition at line 156 of file meta/include/meta/meta.h.
Referenced by compiler(), get_amiStatus(), get_AMITag(), get_AtlasRelease(), get_beam_energy(), get_beamType(), get_campaign(), get_campaign_luminosity(), get_completion(), get_conditionsTag(), get_config(), get_cross_section_nb(), get_DatasetName(), get_datasetNumber(), get_dataType(), get_derivationFormat(), get_dsid(), get_ecmEnergy(), get_event_index(), get_eventNumber(), get_events(), get_file_type(), get_fileGUID(), get_fileSize(), get_found(), get_generatorName(), get_generators(), get_generatorTune(), get_genFiltEff(), get_genFilterNames(), get_geometryVersion(), get_identifier(), get_inputfiles(), get_inputrange(), get_isMC(), get_keyword(), get_keywords(), get_kfactor(), get_LFN(), get_logicalDatasetName(), get_misc(), get_nFiles(), get_PDF(), get_physicsShort(), get_principalPhysicsGroup(), get_prodsysStatus(), get_productionStep(), get_projectName(), get_run_number(), get_sample_name(), get_statsAlgorithm(), get_totalEvents(), get_totalSize(), get_version(), get_weights(), scan_data(), and scan_sow().
metacache_path
std::string meta::metacache_path private
String storing the path to a metadata cache, if used.
Definition at line 155 of file meta/include/meta/meta.h.
misc
cproperty<std::map<std::string, weights_t>, meta> meta::misc
Property: A map for miscellaneous weights or related information, using weights_t struct.
Definition at line 149 of file meta/include/meta/meta.h.
Referenced by meta(), and get_sum_of_weights().
nFiles
cproperty<unsigned int, meta> meta::nFiles
Property: The number of files associated with this dataset.
Definition at line 105 of file meta/include/meta/meta.h.
Referenced by meta().
PDF
cproperty<std::string, meta> meta::PDF
Property: Information about the Parton Density Function (PDF) used in MC generation.
Definition at line 117 of file meta/include/meta/meta.h.
Referenced by meta().
physicsShort
cproperty<std::string, meta> meta::physicsShort
Property: A short description of the physics process or analysis.
Definition at line 120 of file meta/include/meta/meta.h.
Referenced by meta().
prefix
std::string notification::prefix = "" protected inherited
Prefix used in log messages from this instance. Initialized as empty string.
Definition at line 126 of file notification.h.
Referenced by analysis::analysis(), dataloader::dataloader(), io::io(), meta(), optimizer::optimizer(), and metric_template::set_name().
principalPhysicsGroup
cproperty<std::string, meta> meta::principalPhysicsGroup
Property: The main physics group associated with this dataset (e.g., "SM", "SUSY").
Definition at line 119 of file meta/include/meta/meta.h.
Referenced by meta().
prodsysStatus
cproperty<std::string, meta> meta::prodsysStatus
Property: The status of the dataset in the production system.
Definition at line 114 of file meta/include/meta/meta.h.
Referenced by meta().
productionStep
cproperty<std::string, meta> meta::productionStep
Property: The step in the data production chain (e.g., "recon", "merge").
Definition at line 127 of file meta/include/meta/meta.h.
Referenced by meta().
projectName
cproperty<std::string, meta> meta::projectName
Property: The name of the project this dataset belongs to (e.g., "mc16_13TeV").
Definition at line 128 of file meta/include/meta/meta.h.
Referenced by meta().
rpd
rapidjson::Document* meta::rpd = nullptr private
< Private access specifier for the following members.
Pointer to a RapidJSON document object, used for parsing JSON metadata. Initialized to nullptr.
Definition at line 154 of file meta/include/meta/meta.h.
Referenced by ~meta(), compiler(), and parse_json().
run_number
cproperty<std::vector<int>, meta> meta::run_number
Property: A list of run numbers.
Definition at line 142 of file meta/include/meta/meta.h.
Referenced by meta().
sample_name
cproperty<std::string, meta> meta::sample_name
Property: A user-defined name for the sample.
Definition at line 132 of file meta/include/meta/meta.h.
Referenced by meta().
statsAlgorithm
cproperty<std::string, meta> meta::statsAlgorithm
Property: Algorithm used for statistical combination or analysis.
Definition at line 129 of file meta/include/meta/meta.h.
Referenced by meta().
sum_of_weights
cproperty<double, meta> meta::sum_of_weights
Property: The sum of event weights, crucial for MC normalization.
Definition at line 102 of file meta/include/meta/meta.h.
Referenced by meta().
suppress_info
bool notification::suppress_info = false protected inherited
Flag indicating whether info messages are suppressed. Initialized as false.
Definition at line 129 of file notification.h.
suppress_warnings
bool notification::suppress_warnings = false protected inherited
Flag indicating whether warnings are suppressed. Initialized as false.
Definition at line 128 of file notification.h.
totalEvents
cproperty<unsigned int, meta> meta::totalEvents
Property: The total number of events across all files in the dataset.
Definition at line 106 of file meta/include/meta/meta.h.
Referenced by meta().
totalSize
cproperty<double, meta> meta::totalSize
Property: The total size of the dataset, potentially in bytes or some other unit.
Definition at line 90 of file meta/include/meta/meta.h.
Referenced by meta().
version
cproperty<std::string, meta> meta::version
Property: Version string for the dataset or metadata schema.
Definition at line 116 of file meta/include/meta/meta.h.
Referenced by meta().
weights
cproperty<std::vector<std::string>, meta> meta::weights
Property: A list of weight names or definitions.
Definition at line 137 of file meta/include/meta/meta.h.
Referenced by meta().
The documentation for this class was generated from the following files:
meta/include/meta/meta.h
meta.cxx