AnalysisG: lossfx Class Reference
lossfx Class Reference
#include <lossfx.h>
Public Member Functions
lossfx ()
~lossfx ()
loss_enum loss_string (std::string name)
opt_enum optim_string (std::string name)
torch::Tensor loss (torch::Tensor *pred, torch::Tensor *truth, loss_enum lss)
void weight_init (torch::nn::Sequential *data, mlp_init method)
torch::optim::Optimizer * build_optimizer (optimizer_params_t *op, std::vector< torch::Tensor > *params)
bool build_loss_function (loss_enum lss)
void to (torch::TensorOptions *)
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Static Public Member Functions
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Private Member Functions
void build_adam (optimizer_params_t *op, std::vector< torch::Tensor > *params)
void build_adagrad (optimizer_params_t *op, std::vector< torch::Tensor > *params)
void build_adamw (optimizer_params_t *op, std::vector< torch::Tensor > *params)
void build_lbfgs (optimizer_params_t *op, std::vector< torch::Tensor > *params)
void build_rmsprop (optimizer_params_t *op, std::vector< torch::Tensor > *params)
void build_sgd (optimizer_params_t *op, std::vector< torch::Tensor > *params)
torch::Tensor _fx_loss (torch::nn::BCELossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::BCEWithLogitsLossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::CosineEmbeddingLossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::CrossEntropyLossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::CTCLossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::HingeEmbeddingLossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::HuberLossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::KLDivLossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::L1LossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::MarginRankingLossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::MSELossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::MultiLabelMarginLossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::MultiLabelSoftMarginLossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::MultiMarginLossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::NLLLossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::PoissonNLLLossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::SmoothL1LossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::SoftMarginLossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::TripletMarginLossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
torch::Tensor _fx_loss (torch::nn::TripletMarginWithDistanceLossImpl *lossfx_, torch::Tensor *pred, torch::Tensor *truth)
Private Attributes
torch::optim::Adam * m_adam = nullptr
torch::optim::Adagrad * m_adagrad = nullptr
torch::optim::AdamW * m_adamw = nullptr
torch::optim::LBFGS * m_lbfgs = nullptr
torch::optim::RMSprop * m_rmsprop = nullptr
torch::optim::SGD * m_sgd = nullptr
torch::nn::BCELossImpl * m_bce = nullptr
torch::nn::BCEWithLogitsLossImpl * m_bce_with_logits = nullptr
torch::nn::CosineEmbeddingLossImpl * m_cosine_embedding = nullptr
torch::nn::CrossEntropyLossImpl * m_cross_entropy = nullptr
torch::nn::CTCLossImpl * m_ctc = nullptr
torch::nn::HingeEmbeddingLossImpl * m_hinge_embedding = nullptr
torch::nn::HuberLossImpl * m_huber = nullptr
torch::nn::KLDivLossImpl * m_kl_div = nullptr
torch::nn::L1LossImpl * m_l1 = nullptr
torch::nn::MarginRankingLossImpl * m_margin_ranking = nullptr
torch::nn::MSELossImpl * m_mse = nullptr
torch::nn::MultiLabelMarginLossImpl * m_multi_label_margin = nullptr
torch::nn::MultiLabelSoftMarginLossImpl * m_multi_label_soft_margin = nullptr
torch::nn::MultiMarginLossImpl * m_multi_margin = nullptr
torch::nn::NLLLossImpl * m_nll = nullptr
torch::nn::PoissonNLLLossImpl * m_poisson_nll = nullptr
torch::nn::SmoothL1LossImpl * m_smooth_l1 = nullptr
torch::nn::SoftMarginLossImpl * m_soft_margin = nullptr
torch::nn::TripletMarginLossImpl * m_triplet_margin = nullptr
torch::nn::TripletMarginWithDistanceLossImpl * m_triplet_margin_with_distance = nullptr
Detailed Description
Definition at line 12 of file lossfx.h.
Constructor & Destructor Documentation
lossfx()
lossfx::lossfx ()
Definition at line 3 of file lossfx.cxx.
~lossfx()
lossfx::~lossfx ()
Definition at line 4 of file lossfx.cxx.
References m_adagrad, m_adam, m_adamw, m_bce, m_bce_with_logits, m_cosine_embedding, m_cross_entropy, m_ctc, m_hinge_embedding, m_huber, m_kl_div, m_l1, m_lbfgs, m_margin_ranking, m_mse, m_multi_label_margin, m_multi_label_soft_margin, m_multi_margin, m_nll, m_poisson_nll, m_rmsprop, m_sgd, m_smooth_l1, m_soft_margin, m_triplet_margin, and m_triplet_margin_with_distance.
Member Function Documentation
_fx_loss() [1/20]
torch::Tensor lossfx::_fx_loss (torch::nn::BCELossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 29 of file loss_config.cxx.
References to().
Referenced by loss().
_fx_loss() [2/20]
torch::Tensor lossfx::_fx_loss (torch::nn::BCEWithLogitsLossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 33 of file loss_config.cxx.
References to().
_fx_loss() [3/20]
torch::Tensor lossfx::_fx_loss (torch::nn::CosineEmbeddingLossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 38 of file loss_config.cxx.
_fx_loss() [4/20]
torch::Tensor lossfx::_fx_loss (torch::nn::CrossEntropyLossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 43 of file loss_config.cxx.
References to().
_fx_loss() [5/20]
torch::Tensor lossfx::_fx_loss (torch::nn::CTCLossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 47 of file loss_config.cxx.
_fx_loss() [6/20]
torch::Tensor lossfx::_fx_loss (torch::nn::HingeEmbeddingLossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 52 of file loss_config.cxx.
References to().
_fx_loss() [7/20]
torch::Tensor lossfx::_fx_loss (torch::nn::HuberLossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 57 of file loss_config.cxx.
References to().
_fx_loss() [8/20]
torch::Tensor lossfx::_fx_loss (torch::nn::KLDivLossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 62 of file loss_config.cxx.
References to().
_fx_loss() [9/20]
torch::Tensor lossfx::_fx_loss (torch::nn::L1LossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 67 of file loss_config.cxx.
References to().
_fx_loss() [10/20]
torch::Tensor lossfx::_fx_loss (torch::nn::MarginRankingLossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 72 of file loss_config.cxx.
_fx_loss() [11/20]
torch::Tensor lossfx::_fx_loss (torch::nn::MSELossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 77 of file loss_config.cxx.
References to().
_fx_loss() [12/20]
torch::Tensor lossfx::_fx_loss (torch::nn::MultiLabelMarginLossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 82 of file loss_config.cxx.
References to().
_fx_loss() [13/20]
torch::Tensor lossfx::_fx_loss (torch::nn::MultiLabelSoftMarginLossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 87 of file loss_config.cxx.
References to().
_fx_loss() [14/20]
torch::Tensor lossfx::_fx_loss (torch::nn::MultiMarginLossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 92 of file loss_config.cxx.
References to().
_fx_loss() [15/20]
torch::Tensor lossfx::_fx_loss (torch::nn::NLLLossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 96 of file loss_config.cxx.
References to().
_fx_loss() [16/20]
torch::Tensor lossfx::_fx_loss (torch::nn::PoissonNLLLossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 100 of file loss_config.cxx.
References to().
_fx_loss() [17/20]
torch::Tensor lossfx::_fx_loss (torch::nn::SmoothL1LossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 104 of file loss_config.cxx.
References to().
_fx_loss() [18/20]
torch::Tensor lossfx::_fx_loss (torch::nn::SoftMarginLossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 108 of file loss_config.cxx.
References to().
_fx_loss() [19/20]
torch::Tensor lossfx::_fx_loss (torch::nn::TripletMarginLossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 112 of file loss_config.cxx.
_fx_loss() [20/20]
torch::Tensor lossfx::_fx_loss (torch::nn::TripletMarginWithDistanceLossImpl * lossfx_, torch::Tensor * pred, torch::Tensor * truth) private
Definition at line 116 of file loss_config.cxx.
absolute_path()
std::string tools::absolute_path (std::string path) static inherited
Converts a relative path to an absolute path.
Parameters
path The path to convert.
Returns
The absolute version of the path.
Definition at line 49 of file tools/cxx/io.cxx.
Referenced by analysis::analysis(), analysis::build_events(), io::check_root_file_paths(), and io::trigger_pcm().
build_adagrad()
void lossfx::build_adagrad (optimizer_params_t * op, std::vector< torch::Tensor > * params) private
Definition at line 13 of file optimizer_config.cxx.
References m_adagrad.
Referenced by build_optimizer().
build_adam()
void lossfx::build_adam (optimizer_params_t * op, std::vector< torch::Tensor > * params) private
Definition at line 3 of file optimizer_config.cxx.
References m_adam.
Referenced by build_optimizer().
build_adamw()
void lossfx::build_adamw (optimizer_params_t * op, std::vector< torch::Tensor > * params) private
Definition at line 23 of file optimizer_config.cxx.
References m_adamw.
Referenced by build_optimizer().
build_lbfgs()
void lossfx::build_lbfgs (optimizer_params_t * op, std::vector< torch::Tensor > * params) private
Definition at line 33 of file optimizer_config.cxx.
References m_lbfgs.
Referenced by build_optimizer().
build_loss_function()
bool lossfx::build_loss_function (loss_enum lss)
Definition at line 48 of file lossfx.cxx.
References bce, bce_with_logits, cosine_embedding, cross_entropy, ctc, hinge_embedding, huber, kl_div, l1, m_bce, m_bce_with_logits, m_cosine_embedding, m_cross_entropy, m_ctc, m_hinge_embedding, m_huber, m_kl_div, m_l1, m_margin_ranking, m_mse, m_multi_label_margin, m_multi_label_soft_margin, m_multi_margin, m_nll, m_poisson_nll, m_smooth_l1, m_soft_margin, m_triplet_margin, m_triplet_margin_with_distance, margin_ranking, mse, multi_label_margin, multi_label_soft_margin, multi_margin, nll, poisson_nll, smooth_l1, soft_margin, triplet_margin, and triplet_margin_with_distance.
build_optimizer()
torch::optim::Optimizer * lossfx::build_optimizer (optimizer_params_t * op, std::vector< torch::Tensor > * params)
Definition at line 33 of file lossfx.cxx.
References adagrad, adam, adamw, build_adagrad(), build_adam(), build_adamw(), build_lbfgs(), build_rmsprop(), build_sgd(), lbfgs, m_adagrad, m_adam, m_adamw, m_lbfgs, m_rmsprop, m_sgd, optim_string(), rmsprop, and sgd.
build_rmsprop()
void lossfx::build_rmsprop (optimizer_params_t * op, std::vector< torch::Tensor > * params) private
Definition at line 45 of file optimizer_config.cxx.
References m_rmsprop.
Referenced by build_optimizer().
build_sgd()
void lossfx::build_sgd (optimizer_params_t * op, std::vector< torch::Tensor > * params) private
Definition at line 57 of file optimizer_config.cxx.
References m_sgd.
Referenced by build_optimizer().
create_path()
void tools::create_path (std::string path) static inherited
Creates a directory path, including parent directories if needed.
Parameters
path The directory path to create.
Definition at line 6 of file tools/cxx/io.cxx.
References f, and tools::split().
Referenced by analysis::analysis(), analysis::build_inference(), plotting::build_path(), analysis::build_project(), container::compile(), metrics::dump_mass_plots(), metric_template::execute(), metrics::generic_painter(), analysis::start(), io::start(), and io::trigger_pcm().
delete_path()
void tools::delete_path (std::string path) static inherited
Deletes a directory path and its contents.
Parameters
path The directory path to delete.
Definition at line 22 of file tools/cxx/io.cxx.
ends_with()
bool tools::ends_with (std::string * inpt, std::string val) static inherited
Checks if a string ends with a specific substring.
Parameters
inpt Pointer to the string to check.
val The substring to check for at the end.
Returns
True if the string ends with the substring, false otherwise.
Definition at line 71 of file strings.cxx.
References l.
Referenced by plotting::build_path(), io::check_root_file_paths(), dataloader::dump_graphs(), tools::ls(), meta::parse_json(), io::scan_keys(), and analysis::start().
extract()
template<typename C , typename T > static void tools::extract (std::vector< T > * prop, std::vector< C * > * src, void(*)(T *, C *) get_prop) inline static inherited
Extracts a specific property from a vector of objects into a new vector.
Template Parameters
C The type of objects in the source vector.
T The type of the property to extract.
Parameters
prop Pointer to the output vector to fill with property values.
src Pointer to the source vector of objects.
get_prop Function pointer to extract the property from an object.
< Clear the properties vector.
< Reserve space for the property values.
< Loop through each object in the source vector.
< Create a default-initialized property variable.
< Call the provided function to extract the property.
< Add the property value to the output vector.
Definition at line 216 of file tools.h.
flush()
template<typename T > static void tools::flush (std::vector< T * > * inpt) inline static inherited
Empties a vector and all objects it points to.
Template Parameters
T The type of pointers in the vector.
Parameters
inpt Pointer to the vector to empty.
< Loop through all elements in the vector.
< Delete the object the pointer points to.
< Set the pointer to nullptr to avoid dangling pointers.
< Clear the vector.
Definition at line 167 of file tools.h.
Referenced by analysis::~analysis(), dataloader::~dataloader(), sampletracer::compile_objects(), and io::root_end().
has_string()
bool tools::has_string (std::string * inpt, std::string trg) static inherited
Checks if a string contains a specific substring.
Parameters
inpt Pointer to the string to check.
trg The substring to search for.
Returns
True if the substring is found, false otherwise.
Definition at line 65 of file strings.cxx.
References f.
Referenced by analysis::check_cache(), meta::compiler(), metrics::generic_painter(), dataloader::restore_graphs_(), meta::scan_sow(), model_template::set_device(), and metric_template::set_run_name().
has_value()
bool tools::has_value (std::vector< std::string > * data, std::string trg) static inherited
Checks if a vector of strings contains a specific string.
Parameters
data Pointer to the vector to search.
trg The string to search for.
Returns
True if the string is found in the vector, false otherwise.
Definition at line 77 of file strings.cxx.
Referenced by io::scan_keys().
is_file()
bool tools::is_file (std::string path) static inherited
Checks if a path refers to an existing file.
Parameters
path The path to check.
Returns
True if the path is a file and exists, false otherwise.
Definition at line 30 of file tools/cxx/io.cxx.
Referenced by io::check_root_file_paths(), analysis::initialize_loop(), metric_template::set_run_name(), and io::start().
loss()
torch::Tensor lossfx::loss (torch::Tensor * pred, torch::Tensor * truth, loss_enum lss)
Definition at line 3 of file loss_config.cxx.
References _fx_loss(), bce, bce_with_logits, cosine_embedding, cross_entropy, ctc, hinge_embedding, huber, kl_div, l1, m_bce, m_bce_with_logits, m_cosine_embedding, m_cross_entropy, m_ctc, m_hinge_embedding, m_huber, m_kl_div, m_l1, m_margin_ranking, m_mse, m_multi_label_margin, m_multi_label_soft_margin, m_multi_margin, m_nll, m_poisson_nll, m_smooth_l1, m_soft_margin, m_triplet_margin, m_triplet_margin_with_distance, margin_ranking, mse, multi_label_margin, multi_label_soft_margin, multi_margin, nll, poisson_nll, smooth_l1, soft_margin, triplet_margin, and triplet_margin_with_distance.
loss_string()
loss_enum lossfx::loss_string (std::string name)
Definition at line 3 of file switching.cxx.
References bce, bce_with_logits, cosine_embedding, cross_entropy, ctc, hinge_embedding, huber, invalid_loss, kl_div, l1, margin_ranking, mse, multi_label_margin, multi_label_soft_margin, multi_margin, nll, poisson_nll, smooth_l1, soft_margin, triplet_margin, and triplet_margin_with_distance.
Referenced by model_template::set_output_features().
ls()
std::vector< std::string > tools::ls (std::string path, std::string ext = "") static inherited
Lists files in a directory, optionally filtered by extension.
Parameters
path The directory to search.
ext File extension filter. If empty, all files are listed.
Returns
A vector of filenames in the directory.
Definition at line 35 of file tools/cxx/io.cxx.
References tools::ends_with(), and tools::split().
Referenced by analysis::analysis(), analysis::check_cache(), io::check_root_file_paths(), dataloader::restore_graphs(), and io::trigger_pcm().
optim_string()
opt_enum lossfx::optim_string (std::string name)
Definition at line 28 of file switching.cxx.
References adagrad, adam, adamw, invalid_optimizer, lbfgs, rmsprop, and sgd.
Referenced by build_optimizer().
put()
template<typename g > static void tools::put (std::vector< g * > * out, std::vector< g * > * src, std::vector< int > * trg) inline static inherited
Fills a vector with pointers from another vector based on a selection index.
Template Parameters
g The type of objects being pointed to.
Parameters
out Pointer to the output vector to fill.
src Pointer to the source vector to select from.
trg Pointer to a vector of indices for selection.
< Clear the output vector.
< Reserve space for the output elements.
< Loop through each selected index.
< Get the object at the selected index.
< Add it to the output vector.
< Mark the object as in use.
Definition at line 197 of file tools.h.
Referenced by dataloader::get_k_train_set(), dataloader::get_k_validation_set(), and dataloader::get_test_set().
rename()
void tools::rename (std::string start, std::string target) static inherited
Renames a file or directory.
Parameters
start The original path.
target The new path.
Definition at line 18 of file tools/cxx/io.cxx.
Referenced by dataloader::dump_graphs().
replace()
void tools::replace (std::string * in, std::string repl_str, std::string repl_with) static inherited
Replaces all occurrences of a substring in a string.
Parameters
in Pointer to the string to modify.
repl_str The substring to replace.
repl_with The replacement string.
Definition at line 5 of file strings.cxx.
Referenced by analysis::build_graphs(), analysis::check_cache(), dataloader::dump_graphs(), meta::get_campaign(), meta::parse_json(), and analysis::start().
split()
std::vector< std::string > tools::split (std::string inpt, std::string del) inherited
Splits a string into a vector of substrings based on a delimiter.
Parameters
inpt The input string to split.
del The delimiter.
Returns
A vector of substrings.
Definition at line 23 of file strings.cxx.
References index.
Referenced by analysis::build_events(), analysis::build_graphs(), analysis::build_inference(), event_template::build_mapping(), analysis::check_cache(), container::compile(), sampletracer::compile_objects(), meta::compiler(), tools::create_path(), dataloader::dump_graphs(), meta::hash(), tools::ls(), graph_t::meta_deserialize(), dataloader::restore_graphs_(), io::root_begin(), model_template::set_device(), metric_template::set_run_name(), metric_template::set_variables(), and analysis::start().
sum()
template<typename g > g tools::sum (std::vector< g > * inpt) inline inherited
Sums the elements of a vector.
Template Parameters
g The type of elements in the vector.
Parameters
inpt Pointer to the vector to sum.
Returns
The sum of all elements.
< Initialize the output variable.
< Return the sum.
Definition at line 183 of file tools.h.
Referenced by metrics::add_th1f_accuracy(), sampletracer::compile_objects(), particle_template::DeltaR(), graph_template::double_neutrino(), grift::forward(), recursivegraphneuralnetwork::forward(), matching::match_obj(), and grift::message().
to()
void lossfx::to (torch::TensorOptions * op)
Definition at line 76 of file lossfx.cxx.
References m_bce, m_bce_with_logits, m_cosine_embedding, m_cross_entropy, m_ctc, m_hinge_embedding, m_huber, m_kl_div, m_l1, m_margin_ranking, m_mse, m_multi_label_margin, m_multi_label_soft_margin, m_multi_margin, m_nll, m_poisson_nll, m_smooth_l1, m_soft_margin, m_triplet_margin, m_triplet_margin_with_distance, and to().
Referenced by _fx_loss(), _fx_loss(), _fx_loss(), _fx_loss(), _fx_loss(), _fx_loss(), _fx_loss(), _fx_loss(), _fx_loss(), _fx_loss(), _fx_loss(), _fx_loss(), _fx_loss(), _fx_loss(), _fx_loss(), and to().
to_string() [1/2]
std::string tools::to_string (double val) static inherited
Converts a double value to a string with standard precision.
Parameters
val The double value to convert.
Returns
The string representation of the value.
Definition at line 59 of file strings.cxx.
Referenced by dataloader::generate_kfold_set(), dataloader::generate_test_set(), particle_template::get_hash(), topefficiency::region(), dataloader::restore_dataset(), event_template::set_hash(), selection_template::set_hash(), parton::strategy(), topjets::strategy(), toptruthjets::strategy(), and parton::top_mass_contribution().
to_string() [2/2]
std::string tools::to_string (double val, int prec) static inherited
Converts a double value to a string with specified precision.
Parameters
val The double value to convert.
prec The number of decimal places to consider.
Returns
The string representation of the value.
Definition at line 91 of file strings.cxx.
trim()
std::string tools::trim (std::string s) inherited
Removes whitespace from the beginning and end of a string.
Parameters
s The string to trim.
Returns
The trimmed string.
type_name()
template<typename T > std::string tools::type_name () inline inherited
Gets the type name of a variable as a string (for debugging).
Template Parameters
T The type to get the name of.
Returns
The name of the type as a string.
< Gets the type name via RTTI.
< Returns the type name.
Definition at line 155 of file tools.h.
Referenced by event_template::build_mapping().
weight_init()
void lossfx::weight_init (torch::nn::Sequential * data, mlp_init method)
Definition at line 113 of file optimizer_config.cxx.
References kaiming_normal, kaiming_uniform, m_kaiming_normal(), m_kaiming_uniform(), m_normal(), m_uniform(), m_xavier_normal(), m_xavier_uniform(), normal, uniform, xavier_normal, and xavier_uniform.
Member Data Documentation
m_adagrad
torch::optim::Adagrad* lossfx::m_adagrad = nullptr private
Definition at line 60 of file lossfx.h.
Referenced by ~lossfx(), build_adagrad(), and build_optimizer().
m_adam
torch::optim::Adam* lossfx::m_adam = nullptr private
Definition at line 59 of file lossfx.h.
Referenced by ~lossfx(), build_adam(), and build_optimizer().
m_adamw
torch::optim::AdamW* lossfx::m_adamw = nullptr private
Definition at line 61 of file lossfx.h.
Referenced by ~lossfx(), build_adamw(), and build_optimizer().
m_bce
torch::nn::BCELossImpl* lossfx::m_bce = nullptr private
Definition at line 66 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_bce_with_logits
torch::nn::BCEWithLogitsLossImpl* lossfx::m_bce_with_logits = nullptr private
Definition at line 67 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_cosine_embedding
torch::nn::CosineEmbeddingLossImpl* lossfx::m_cosine_embedding = nullptr private
Definition at line 68 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_cross_entropy
torch::nn::CrossEntropyLossImpl* lossfx::m_cross_entropy = nullptr private
Definition at line 69 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_ctc
torch::nn::CTCLossImpl* lossfx::m_ctc = nullptr private
Definition at line 70 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_hinge_embedding
torch::nn::HingeEmbeddingLossImpl* lossfx::m_hinge_embedding = nullptr private
Definition at line 71 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_huber
torch::nn::HuberLossImpl* lossfx::m_huber = nullptr private
Definition at line 72 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_kl_div
torch::nn::KLDivLossImpl* lossfx::m_kl_div = nullptr private
Definition at line 73 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_l1
torch::nn::L1LossImpl* lossfx::m_l1 = nullptr private
Definition at line 74 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_lbfgs
torch::optim::LBFGS* lossfx::m_lbfgs = nullptr private
Definition at line 62 of file lossfx.h.
Referenced by ~lossfx(), build_lbfgs(), and build_optimizer().
m_margin_ranking
torch::nn::MarginRankingLossImpl* lossfx::m_margin_ranking = nullptr private
Definition at line 75 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_mse
torch::nn::MSELossImpl* lossfx::m_mse = nullptr private
Definition at line 76 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_multi_label_margin
torch::nn::MultiLabelMarginLossImpl* lossfx::m_multi_label_margin = nullptr private
Definition at line 77 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_multi_label_soft_margin
torch::nn::MultiLabelSoftMarginLossImpl* lossfx::m_multi_label_soft_margin = nullptr private
Definition at line 78 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_multi_margin
torch::nn::MultiMarginLossImpl* lossfx::m_multi_margin = nullptr private
Definition at line 79 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_nll
torch::nn::NLLLossImpl* lossfx::m_nll = nullptr private
Definition at line 80 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_poisson_nll
torch::nn::PoissonNLLLossImpl* lossfx::m_poisson_nll = nullptr private
Definition at line 81 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_rmsprop
torch::optim::RMSprop* lossfx::m_rmsprop = nullptr private
Definition at line 63 of file lossfx.h.
Referenced by ~lossfx(), build_optimizer(), and build_rmsprop().
m_sgd
torch::optim::SGD* lossfx::m_sgd = nullptr private
Definition at line 64 of file lossfx.h.
Referenced by ~lossfx(), build_optimizer(), and build_sgd().
m_smooth_l1
torch::nn::SmoothL1LossImpl* lossfx::m_smooth_l1 = nullptr private
Definition at line 82 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_soft_margin
torch::nn::SoftMarginLossImpl* lossfx::m_soft_margin = nullptr private
Definition at line 83 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_triplet_margin
torch::nn::TripletMarginLossImpl* lossfx::m_triplet_margin = nullptr private
Definition at line 84 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
m_triplet_margin_with_distance
torch::nn::TripletMarginWithDistanceLossImpl* lossfx::m_triplet_margin_with_distance = nullptr private
Definition at line 85 of file lossfx.h.
Referenced by ~lossfx(), build_loss_function(), loss(), and to().
The documentation for this class was generated from the following files:
lossfx.h
loss_config.cxx
lossfx.cxx
optimizer_config.cxx
switching.cxx