AnalysisG: topkinematics Class Reference
topkinematics Class Reference
#include <topkinematics.h>
Public Member Functions
topkinematics ()
~topkinematics () override
selection_template * clone () override
bool selection (event_template *ev) override
bool strategy (event_template *ev) override
void merge (selection_template *sl) override
topkinematics ()
~topkinematics () override
selection_template * clone () override
bool selection (event_template *ev) override
bool strategy (event_template *ev) override
void merge (selection_template *sl) override
Public Member Functions inherited from selection_template
selection_template ()
virtual ~selection_template ()
virtual void bulk_write (const long *idx, std::string *hx)
virtual void write (std::vector< particle_template * > *particles, std::string name, particle_enum attrs)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< std::vector< double >> *data)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< int > *data)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< double > *data)
void switch_board (particle_enum attrs, particle_template *ptr, std::vector< bool > *data)
template<typename g >
void write (g *var, std::string name)
template<typename g >
void write (g var, std::string name)
std::vector< std::map< std::string, float > > reverse_hash (std::vector< std::string > *hashes)
bool CompileEvent ()
selection_template * build (event_template *ev)
bool operator== (selection_template &p)
template<typename g , typename k >
void sum (std::vector< g * > *ch, k **out)
template<typename g >
void safe_delete (std::vector< g * > *particles)
template<typename g >
g * sum (std::map< std::string, g * > *ch)
template<typename g >
float sum (std::vector< g * > *ch)
template<typename g >
std::vector< g * > vectorize (std::map< std::string, g * > *in)
template<typename g >
std::vector< g * > make_unique (std::vector< g * > *inpt)
template<typename g >
void downcast (std::vector< g * > *inpt, std::vector< particle_template * > *out)
template<typename o , typename g >
void upcast (std::map< std::string, o * > *inpt, std::vector< g * > *out)
template<typename o , typename g >
void upcast (std::vector< o * > *inpt, std::vector< g * > *out)
template<typename g >
void get_leptonics (std::map< std::string, g * > inpt, std::vector< particle_template * > *out)
template<typename g , typename j >
bool contains (std::vector< g * > *inpt, j *pcheck)
Public Member Functions inherited from tools
tools ()
Constructor for the tools class.
~tools ()
Destructor for the tools class.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Public Attributes
std::map< std::string, std::vector< float > > res_top_kinematics = {}
std::map< std::string, std::vector< float > > spec_top_kinematics = {}
std::map< std::string, std::vector< float > > mass_combi = {}
std::map< std::string, std::vector< float > > deltaR = {}
Public Attributes inherited from selection_template
cproperty< std::string, selection_template > name
cproperty< std::string, selection_template > hash
cproperty< std::string, selection_template > tree
cproperty< double, selection_template > weight
cproperty< long, selection_template > index
meta * meta_data = nullptr
std::string filename = ""
event_t data
int threadIdx = -1
std::map< std::string, std::map< std::string, float > > passed_weights = {}
std::map< std::string, meta_t > matched_meta = {}
Additional Inherited Members
Static Public Member Functions inherited from selection_template
static void set_name (std::string *, selection_template *)
static void get_name (std::string *, selection_template *)
static void set_hash (std::string *, selection_template *)
static void get_hash (std::string *, selection_template *)
static void get_tree (std::string *, selection_template *)
static void set_weight (double *, selection_template *)
static void get_weight (double *, selection_template *)
static void set_index (long *, selection_template *)
Static Public Member Functions inherited from tools
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Detailed Description
Definition at line 7 of file mc16/topkinematics/topkinematics.h.
Constructor & Destructor Documentation
topkinematics() [1/2]
topkinematics::topkinematics ()
Definition at line 3 of file mc16/topkinematics/topkinematics.cxx.
 {this -> name = "top-kinematics";}
References selection_template::name.
Referenced by clone().
~topkinematics() [1/2]
topkinematics::~topkinematics () override
Definition at line 4 of file mc16/topkinematics/topkinematics.cxx.
 {}
topkinematics() [2/2]
topkinematics::topkinematics ()
~topkinematics() [2/2]
topkinematics::~topkinematics () override
Member Function Documentation
clone() [1/2]
selection_template * topkinematics::clone () override virtual
Reimplemented from selection_template.
Definition at line 6 of file mc16/topkinematics/topkinematics.cxx.
{
     return (selection_template*)new topkinematics();
 }
References topkinematics().
clone() [2/2]
selection_template* topkinematics::clone () override virtual
Reimplemented from selection_template.
merge() [1/2]
void topkinematics::merge (selection_template * sl) override virtual
Reimplemented from selection_template.
merge() [2/2]
void topkinematics::merge (selection_template * sl) override virtual
Reimplemented from selection_template.
Definition at line 10 of file mc16/topkinematics/topkinematics.cxx.
{
     auto lamb =[this](std::map<std::string, std::vector<float>>* dx, std::string key){
         std::map<std::string, std::vector<float>>::iterator itr = dx -> begin();
         for (; itr != dx -> end(); ++itr){this -> write(&itr -> second, key + "_" + itr -> first);}
     };
     topkinematics* slt = (topkinematics*)sl;
     lamb(&slt -> res_top_kinematics, "res");
     lamb(&slt -> spec_top_kinematics, "spec");
     lamb(&slt -> mass_combi, "mass");
     lamb(&slt -> deltaR, "dr");
 }
References deltaR, end(), mass_combi, res_top_kinematics, main::sl, spec_top_kinematics, and selection_template::write().
selection() [1/2]
bool topkinematics::selection (event_template * ev) override virtual
Reimplemented from selection_template.
Definition at line 23 of file mc16/topkinematics/topkinematics.cxx.
{
     bsm_4tops* evn = (bsm_4tops*)ev;
     std::vector<particle_template*>* tops = &evn -> Tops;
     int res = 0;
     for (size_t x(0); x < tops -> size(); ++x){res += ((top*)tops -> at(x)) -> from_res;}
     return res == 2;
 }
References main::ev, test_normalization::evn, and main::x.
selection() [2/2]
bool topkinematics::selection (event_template * ev) override virtual
Reimplemented from selection_template.
strategy() [1/2]
bool topkinematics::strategy (event_template * ev) override virtual
Reimplemented from selection_template.
Definition at line 31 of file mc16/topkinematics/topkinematics.cxx.
{
     auto kins = [](std::map<std::string, std::vector<float>>* data, std::vector<top*>* td){
         for (size_t x(0); x < td -> size(); ++x){
             (*data)["pt"].push_back(td -> at(x) -> pt / 1000);
             (*data)["eta"].push_back(td -> at(x) -> eta);
             (*data)["phi"].push_back(td -> at(x) -> phi);
             (*data)["energy"].push_back(td -> at(x) -> e / 1000);
         }
     };
     bsm_4tops* evn = (bsm_4tops*)ev;
     std::vector<top*> r_tops = {};
     std::vector<top*> s_tops = {};
     for (size_t x(0); x < evn -> Tops.size(); ++x){
         top* t = (top*)evn -> Tops[x];
         if (t -> from_res){r_tops.push_back(t);}
         else {s_tops.push_back(t);}
     }
     kins(&this -> res_top_kinematics , &r_tops);
     kins(&this -> spec_top_kinematics, &s_tops);
     std::vector<float>* data = nullptr;
     data = &this -> deltaR["RS"];
     for (size_t x(0); x < r_tops.size(); ++x){
         for (size_t y(0); y < s_tops.size(); ++y){
             data -> push_back(r_tops[x] -> DeltaR(s_tops[y]));
         }
     }
     data = &this -> deltaR["RR"];
     for (size_t x(0); x < r_tops.size(); ++x){
         for (size_t y(x); y < r_tops.size(); ++y){
             if (x == y){continue;}
             data -> push_back(r_tops[x] -> DeltaR(r_tops[y]));
         }
     }
     data = &this -> deltaR["SS"];
     for (size_t x(0); x < s_tops.size(); ++x){
         for (size_t y(x); y < s_tops.size(); ++y){
             if (x == y){continue;}
             data -> push_back(s_tops[x] -> DeltaR(s_tops[y]));
         }
     }
     data = &this -> mass_combi["RS"];
     for (size_t x(0); x < r_tops.size(); ++x){
         for (size_t y(0); y < s_tops.size(); ++y){
             top r = (*(r_tops[x]) + *s_tops[y]);
             data -> push_back(r.mass / 1000);
         }
     }
     data = &this -> mass_combi["RR"];
     for (size_t x(0); x < r_tops.size(); ++x){
         for (size_t y(x); y < r_tops.size(); ++y){
             if (x == y){continue;}
             top r = (*(r_tops[x]) + *r_tops[y]);
             data -> push_back(r.mass / 1000);
         }
     }
     data = &this -> mass_combi["SS"];
     for (size_t x(0); x < s_tops.size(); ++x){
         for (size_t y(x); y < s_tops.size(); ++y){
             if (x == y){continue;}
             top r = (*(s_tops[x]) + *s_tops[y]);
             data -> push_back(r.mass / 1000);
          }
     }
     return true;
 }
References selection_template::data, deltaR, pyc::physics::cartesian::separate::DeltaR(), test_particles::e, main::ev, test_normalization::evn, particle_template::mass, mass_combi, res_top_kinematics, spec_top_kinematics, test_experimental_mc20::t, and main::x.
strategy() [2/2]
bool topkinematics::strategy (event_template * ev) override virtual
Reimplemented from selection_template.
Member Data Documentation
deltaR
std::map< std::string, std::vector< float > > topkinematics::deltaR = {}
Definition at line 21 of file mc16/topkinematics/topkinematics.h.
Referenced by merge(), and strategy().
mass_combi
std::map< std::string, std::vector< float > > topkinematics::mass_combi = {}
Definition at line 20 of file mc16/topkinematics/topkinematics.h.
Referenced by merge(), and strategy().
res_top_kinematics
std::map< std::string, std::vector< float > > topkinematics::res_top_kinematics = {}
Definition at line 18 of file mc16/topkinematics/topkinematics.h.
Referenced by merge(), and strategy().
spec_top_kinematics
std::map< std::string, std::vector< float > > topkinematics::spec_top_kinematics = {}
Definition at line 19 of file mc16/topkinematics/topkinematics.h.
Referenced by merge(), and strategy().
The documentation for this class was generated from the following files:
mc16/topkinematics/topkinematics.h
mc16/topkinematics/topkinematics.cxx