AnalysisG: dataloader Class Reference
dataloader Class Reference
#include <dataloader.h>
Public Member Functions
dataloader ()
~dataloader ()
std::vector< graph_t * > * get_k_train_set (int k)
std::vector< graph_t * > * get_k_validation_set (int k)
std::vector< graph_t * > * get_test_set ()
std::vector< graph_t * > * build_batch (std::vector< graph_t * > *data, model_template *mdl, model_report *rep)
std::map< std::string, std::vector< graph_t * > > * get_inference ()
void generate_test_set (float percentage=50)
void generate_kfold_set (int k)
void dump_dataset (std::string path)
bool restore_dataset (std::string path)
std::vector< graph_t * > get_random (int num=5)
void extract_data (graph_t *gr)
void datatransfer (torch::TensorOptions *op, size_t *num_events=nullptr, size_t *prg_events=nullptr)
void datatransfer (std::map< int, torch::TensorOptions * > *ops)
bool dump_graphs (std::string path="./", int threads=10)
void restore_graphs (std::vector< std::string > paths, int threads)
void restore_graphs (std::string paths, int threads)
void start_cuda_server ()
Public Member Functions inherited from notification
notification ()
Constructor for the notification class.
~notification ()
Destructor for the notification class.
void set_prefix (std::string prefix)
Sets the prefix used in log messages from this instance.
std::string get_prefix ()
Returns the prefix currently used in log messages.
void Info (std::string msg, bool newline=true)
Outputs an info message.
void Warning (std::string msg, bool newline=true)
Outputs a warning message.
void Error (std::string msg, bool newline=true)
Outputs an error message.
void Debug (std::string msg, bool newline=true)
Outputs a debug message (only in debug mode).
void Message (std::string msg, std::string tag="", bool newline=true)
Outputs a message with custom formatting.
void set_debug_mode (bool dbg)
Enables or disables debug mode.
bool get_debug_mode ()
Returns the current status of debug mode.
void set_suppress_warning (bool sw)
Sets whether warnings should be suppressed.
bool get_suppress_warning ()
Returns the current warning suppression status.
void set_suppress_info (bool si)
Sets whether info messages should be suppressed.
bool get_suppress_info ()
Returns the current info message suppression status.
Public Member Functions inherited from tools
tools ()
Constructor for the tools class.
~tools ()
Destructor for the tools class.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Static Public Member Functions
static void safe_delete (std::vector< graph_t * > *data)
Static Public Member Functions inherited from tools
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Friends
class analysis
Additional Inherited Members
Protected Attributes inherited from notification
std::string prefix = ""
Prefix used in log messages from this instance. Initialized as empty string.
bool debug_mode = false
Flag indicating whether debug mode is enabled. Initialized as false.
bool suppress_warnings = false
Flag indicating whether warnings are suppressed. Initialized as false.
bool suppress_info = false
Flag indicating whether info messages are suppressed. Initialized as false.
Detailed Description
Definition at line 28 of file dataloader.h.
Constructor & Destructor Documentation
dataloader()
dataloader::dataloader ()
Definition at line 6 of file dataloader.cxx.
                       {
     this -> prefix = "dataloader";
     this -> data_set   = new std::vector<graph_t*>();
     this -> data_index = new std::vector<int>();
     this -> test_set   = new std::vector<int>();
     this -> train_set  = new std::vector<int>();
 }
References notification::prefix.
~dataloader()
dataloader::~dataloader ()
Definition at line 14 of file dataloader.cxx.
{
     auto flush = [](std::vector<graph_t*>* grx){
         for (size_t x(0); x < grx -> size(); ++x){
             (*grx)[x] -> _purge_all();
             delete (*grx)[x];
             (*grx)[x] = nullptr;
         }
         grx -> clear();
         grx -> shrink_to_fit();
     };
     auto flushM = [](std::vector<std::map<std::string, int>*>* data){
         for (size_t x(0); x < data -> size(); ++x){
             delete (*data)[x]; (*data)[x] = nullptr;
         }
         data -> clear();
     };
     flushM(&this -> truth_map_graph);
     flushM(&this -> truth_map_node);
     flushM(&this -> truth_map_edge);
     flushM(&this -> data_map_graph);
     flushM(&this -> data_map_node);
     flushM(&this -> data_map_edge);
     std::map<int, std::vector<int>*>::iterator itr = this -> k_fold_training.begin();
     for (; itr != this -> k_fold_training.end(); ++itr){
         delete this -> gr_k_fold_training[itr -> first];
         delete itr -> second;
     }
     std::map<int, std::vector<int>*>::iterator itx = this -> k_fold_validation.begin();
     for (; itx != this -> k_fold_validation.end(); ++itx){
         delete this -> gr_k_fold_validation[itr -> first];
         delete itx -> second;
     }
     delete this -> test_set;
     delete this -> train_set;
     std::vector<graph_t*>* data_ = this -> data_set;
     this -> data_set = nullptr;
     if (this -> cuda_mem){this -> cuda_mem -> join(); delete this -> cuda_mem;}
     delete this -> data_index;
     flush(data_);
     delete data_; data_ = nullptr;
     std::map<int, std::vector<graph_t*>*>::iterator itc = this -> batched_cache.begin();
     for (; itc != this -> batched_cache.end(); ++itc){
         flush(itc -> second); delete itc -> second; itc -> second = nullptr;
     }
     if (this -> gr_test){delete this -> gr_test;}
 }
References simply_plot::data, tools::flush(), and main::x.
Member Function Documentation
build_batch()
std::vector< graph_t * > * dataloader::build_batch (std::vector< graph_t * > * data, model_template * mdl, model_report * rep)
Definition at line 151 of file dataloader.cxx.
{
     auto g_data  = [this](graph_t* d) -> std::map<int, std::vector<torch::Tensor>>* {return &d -> dev_data_graph;};
     auto n_data  = [this](graph_t* d) -> std::map<int, std::vector<torch::Tensor>>* {return &d -> dev_data_node;};
     auto e_data  = [this](graph_t* d) -> std::map<int, std::vector<torch::Tensor>>* {return &d -> dev_data_edge;};
     auto g_truth = [this](graph_t* d) -> std::map<int, std::vector<torch::Tensor>>* {return &d -> dev_truth_graph;};
     auto n_truth = [this](graph_t* d) -> std::map<int, std::vector<torch::Tensor>>* {return &d -> dev_truth_node;};
     auto e_truth = [this](graph_t* d) -> std::map<int, std::vector<torch::Tensor>>* {return &d -> dev_truth_edge;};
     auto collect = [this](
             model_template* mdl,
             std::vector<graph_t*>* data,
             std::map<std::string, int>* loc,
             std::map<int, std::vector<torch::Tensor>>* cnt,
             std::function<std::map<int, std::vector<torch::Tensor>>* (graph_t*)> fx)
     {
         std::map<int, torch::Tensor> tmp;
         std::map<std::string, int>::iterator ilx;
         for (ilx = loc -> begin(); ilx != loc -> end(); ++ilx){
             std::string key = ilx -> first;
             std::vector<torch::Tensor> arr;
             for (size_t x(0); x < data -> size(); ++x){
                 graph_t* grx = (*data)[x];
                 torch::Tensor* val = grx -> return_any(loc, fx(grx), key, mdl -> device_index);
                 if (!val){continue;}
                 arr.push_back(*val);
             }
             if (!arr.size()){continue;}
             tmp[ilx -> second] = torch::Tensor(torch::cat(arr, {0}));
         }
         int dev_ = (int)mdl -> m_option -> device().index();
         for (ilx = loc -> begin(); ilx != loc -> end(); ++ilx){(*cnt)[dev_].push_back(tmp[ilx -> second]);}
     };
     auto build_graph = [this, g_data, n_data, e_data, g_truth, n_truth, e_truth, collect](
             std::vector<graph_t*>* inpt,
             std::vector<graph_t*>* out,
             model_template* mdl,
             size_t index, size_t* prg = nullptr
     ){
         torch::TensorOptions* op = mdl -> m_option;
         for (size_t x(0); x < inpt -> size(); ++x){
             (*inpt)[x] -> in_use = 1;
             (*inpt)[x] -> transfer_to_device(op);
         }
         graph_t* tr = (*inpt)[0];
         bool cached = true;
         graph_t* gr = (*out)[index];
         if (!gr){
             cached = false;
             gr = new graph_t();
             gr -> data_map_graph  = tr -> data_map_graph;
             gr -> data_map_node   = tr -> data_map_node;
             gr -> data_map_edge   = tr -> data_map_edge;
             gr -> truth_map_graph = tr -> truth_map_graph;
             gr -> truth_map_node  = tr -> truth_map_node ;
             gr -> truth_map_edge  = tr -> truth_map_edge ;
         }
         int dev_ = (int)op -> device().index();
         // observables
         collect(mdl, inpt, gr -> data_map_graph, &gr -> dev_data_graph, g_data);
         collect(mdl, inpt, gr -> data_map_node,  &gr -> dev_data_node,  n_data);
         collect(mdl, inpt, gr -> data_map_edge,  &gr -> dev_data_edge,  e_data);
         // truth data
         collect(mdl, inpt, gr -> truth_map_graph, &gr -> dev_truth_graph, g_truth);
         collect(mdl, inpt, gr -> truth_map_node,  &gr -> dev_truth_node,  n_truth);
         collect(mdl, inpt, gr -> truth_map_edge,  &gr -> dev_truth_edge,  e_truth);
         int offset_nodes = 0;
         std::vector<long> batch_index;
         std::vector<torch::Tensor> _edge_index;
         std::vector<torch::Tensor> _event_weight;
         for (size_t x(0); x < inpt -> size(); ++x){
             graph_t* grx = (*inpt)[x];
             _edge_index.push_back((*grx -> get_edge_index(mdl)) + offset_nodes);
             for (int t(0); t < grx -> num_nodes; ++t){batch_index.push_back(x);}
             _event_weight.push_back(*grx -> get_event_weight(mdl));
             offset_nodes += grx -> num_nodes;
             gr -> in_use = 0;
             if (cached){continue;}
             gr -> batched_events.push_back(x);
         }
         if (!cached){
             gr -> num_nodes = offset_nodes;
             gr -> device = op -> device().type();
         }
         torch::TensorOptions opx = torch::TensorOptions(torch::kCPU).dtype(torch::kLong);
         torch::Tensor bx = torch::from_blob(batch_index.data(), {offset_nodes}, opx);
         torch::Tensor bi = torch::from_blob(gr -> batched_events.data(), {(long)inpt -> size()}, opx);
         gr -> dev_edge_index[dev_]     = torch::cat(_edge_index, {-1});
         gr -> dev_event_weight[dev_]   = torch::cat(_event_weight, {0});
         gr -> dev_batch_index[dev_]    = bx.clone().to(op -> device());
         gr -> dev_batched_events[dev_] = bi.clone().to(op -> device());
         gr -> device_index[dev_] = true;
         (*out)[index] = gr;
         torch::cuda::synchronize();
         if (!prg){return;}
         *prg = 1;
     };
     int k = mdl -> kfold-1;
     int dev = mdl -> m_option -> device().index();
     std::vector<graph_t*>* out = nullptr;
     if (rep && rep -> mode == "evaluation"){k = -1;}
     std::vector<std::vector<graph_t*>> batched = this -> discretize(data, this -> setting -> batch_size);
     int thr = this -> setting -> threads;
     bool skip = bool(thr > batched.size());
     if (rep && (rep -> mode == "validation" || rep -> mode == "evaluation") && this -> batched_cache.count(k)){
         out = this -> batched_cache[k];
         if ((*out)[0] -> device_index[dev]){return out;}
     }
     else {out = new std::vector<graph_t*>(batched.size(), nullptr);}
     int r = 0;
     std::vector<size_t> trgt(batched.size(), 1);
     std::vector<size_t> prg(batched.size(), 0);
     std::vector<std::thread*> th_(batched.size(), nullptr);
     for (size_t x(0); x < batched.size(); ++x, ++r){
         if (skip){build_graph(&batched[x], out, mdl, x); continue;}
         th_[x] = new std::thread(build_graph, &batched[x], out, mdl, x, &prg[x]);
         while (r >= thr){r = this -> running(&th_, &prg, &trgt);}
     }
     this -> monitor(&th_);
     if (!rep){}
     else if (rep -> mode == "validation"){this -> batched_cache[k] = out;}
     else if (rep -> mode == "evaluation"){this -> batched_cache[-1] = out;}
     return out;
 }
References batch_index, d, simply_plot::data, main::dev, main::device, end(), main::fx, test_evaluation::gr, index, main::kfold, main::mdl, test_generator::op, main::out, test_experimental_mc20::t, main::tmp, and main::x.
datatransfer() [1/2]
void dataloader::datatransfer (std::map< int, torch::TensorOptions * > * ops)
Definition at line 128 of file dataloader.cxx.
{
     auto lamb = [this](torch::TensorOptions* op, size_t* num_ev, size_t* prg){this -> datatransfer(op, num_ev, prg);};
     size_t num_thr = 0;
     std::vector<std::thread*> trans(ops -> size(), nullptr);
     std::vector<std::string*> titles(ops -> size(), nullptr);
     std::vector<size_t> num_events(ops -> size(), 0);
     std::vector<size_t> prg_events(ops -> size(), 0);
     this -> info("Transferring graphs to device" + std::string((ops -> size() > 1) ? "s" : ""));
     std::map<int, torch::TensorOptions*>::iterator ito = ops -> begin();
     for (; ito != ops -> end(); ++ito, ++num_thr){
         trans[num_thr]  = new std::thread(lamb, ito -> second, &num_events[num_thr], &prg_events[num_thr]);
         titles[num_thr] = new std::string("Progress on device:" + std::to_string(ito -> first));
     }
     std::thread* thr = new std::thread(this -> progressbar3, &prg_events, &num_events, &titles);
     this -> monitor(&trans);
     this -> success("Transfer Complete!");
     thr -> join(); delete thr; thr = nullptr;
 }
References datatransfer(), end(), test_generator::op, and simply_plot::titles.
datatransfer() [2/2]
void dataloader::datatransfer (torch::TensorOptions * op, size_t * num_events = nullptr, size_t * prg_events = nullptr)
Definition at line 115 of file dataloader.cxx.
{
     auto lamb = [](std::vector<graph_t*>* data, torch::TensorOptions* op, size_t* handle){
         for (size_t f(0); f < data -> size(); ++f){
             (*data)[f] -> transfer_to_device(op);
             if (!handle){continue;}
             *handle = f+1;
         }
     };
     if (num_ev){*num_ev = this -> data_set -> size();}
     lamb(this -> data_set, op, cur_evnt);
 }
References simply_plot::data, f, and test_generator::op.
Referenced by datatransfer().
dump_dataset()
void dataloader::dump_dataset (std::string path)
Definition at line 129 of file dataset.cxx.
{
     std::vector<folds_t> data = {};
     std::map<int, std::vector<int>*> data_e;
     std::map<int, std::vector<int>*>::iterator itr;
     data_e = this -> k_fold_training;
     for (itr = data_e.begin(); itr != data_e.end(); ++itr){
         size_t len = itr -> second -> size();
         for (size_t x(0); x < len; ++x){
             folds_t kf = folds_t();
             kf.k = itr -> first;
             kf.is_train = true;
             graph_t* gr = (*this -> data_set)[(*itr -> second)[x]];
             kf.hash = const_cast<char*>(gr -> hash -> data());
             data.push_back(kf);
         }
     }
     data_e = this -> k_fold_validation;
     for (itr = data_e.begin(); itr != data_e.end(); ++itr){
         size_t len = itr -> second -> size();
         for (size_t x(0); x < len; ++x){
             folds_t kf = folds_t();
             kf.k = itr -> first;
             kf.is_valid = true;
             graph_t* gr = (*this -> data_set)[(*itr -> second)[x]];
             kf.hash = const_cast<char*>(gr -> hash -> data());
             data.push_back(kf);
         }
     }
     for (size_t x(0); x < this -> test_set -> size(); ++x){
         folds_t kf = folds_t();
         kf.is_eval = true;
         graph_t* gr = (*this -> data_set)[(*this -> test_set)[x]];
         kf.hash = const_cast<char*>(gr -> hash -> data());
         data.push_back(kf);
     }
     io* io_g = new io();
     io_g -> start(path, "write");
     io_g -> write(&data, "kfolds");
     io_g -> end();
     delete io_g;
 }
References simply_plot::data, end(), test_evaluation::gr, main::kf, childrenkinematics.figures::path(), analysis::start(), and main::x.
dump_graphs()
bool dataloader::dump_graphs (std::string path = "./", int threads = 10)
Definition at line 5 of file cache.cxx.
{
     auto serialize = [](
             std::vector<graph_t*>* quant,
             std::vector<std::tuple<graph_hdf5_w, graph_hdf5>>* data_c,
             std::map<std::string, std::vector<int>*>* fname_index,
             size_t* handle
     ){
         tools tl = tools();
         for (size_t t(0); t < quant -> size(); ++t){
             graph_t* gr = (*quant)[t];
             data_c -> push_back({});
             graph_hdf5* data = &std::get<1>((*data_c)[t]);
             gr -> serialize(data);
             graph_hdf5_w* grw      = &std::get<0>((*data_c)[t]);
             grw -> num_nodes       = data -> num_nodes;
             grw -> event_index     = data -> event_index;
             grw -> event_weight    = data -> event_weight;
             grw -> hash            = const_cast<char*>(data -> hash.data());
             grw -> filename        = const_cast<char*>(data -> filename.data());
             grw -> edge_index      = const_cast<char*>(data -> edge_index.data());
             grw -> data_map_graph  = const_cast<char*>(data -> data_map_graph.data());
             grw -> data_map_node   = const_cast<char*>(data -> data_map_node.data());
             grw -> data_map_edge   = const_cast<char*>(data -> data_map_edge.data());
             grw -> truth_map_graph = const_cast<char*>(data -> truth_map_graph.data());
             grw -> truth_map_node  = const_cast<char*>(data -> truth_map_node.data());
             grw -> truth_map_edge  = const_cast<char*>(data -> truth_map_edge.data());
             grw -> data_graph      = const_cast<char*>(data -> data_graph.data());
             grw -> data_node       = const_cast<char*>(data -> data_node.data());
             grw -> data_edge       = const_cast<char*>(data -> data_edge.data());
             grw -> truth_graph     = const_cast<char*>(data -> truth_graph.data());
             grw -> truth_node      = const_cast<char*>(data -> truth_node.data());
             grw -> truth_edge      = const_cast<char*>(data -> truth_edge.data());
             std::string fname = data -> filename;
             std::vector<std::string> spl = tl.split(fname, "/");
             fname = spl[spl.size()-1];
             std::string hash  = tl.hash(fname);
             tl.replace(&fname, ".root", ".h5");
             fname = (*gr -> graph_name) + "/." + hash + "-" + fname;
             delete gr -> graph_name; gr -> graph_name = nullptr;
             if (!fname_index -> count(fname)){(*fname_index)[fname] = new std::vector<int>();}
             (*fname_index)[fname] -> push_back(t);
             *handle = t+1;
         }
     };
     auto write = [this](
             std::string* title, std::string fname, size_t* dx,
             std::vector< std::tuple<graph_hdf5_w, graph_hdf5>* > datax
     ){
         io* wrt = new io();
         wrt -> start(fname, "write");
         std::vector<std::string> spl = this -> split(fname, "/");
         *title = "Writing HDF5 -> " + spl[spl.size()-1];
         for (size_t l(0); l < datax.size(); ++l){
             graph_hdf5_w* h5wrt = &std::get<0>(*datax[l]);
             graph_hdf5*   h5_   = &std::get<1>(*datax[l]);
             wrt -> write(h5wrt, h5_ -> hash);
             *dx = l+1;
         }
         wrt -> end();
         delete wrt;
     };
     if (!this -> data_set -> size()){this -> warning("Nothing to do. Skipping..."); return true;}
     size_t x = (this -> data_set -> size()/threads);
     if (this -> data_set -> size() < size_t(threads)){ x = this -> data_set -> size(); }
     std::vector<std::vector<graph_t*>> quant = this -> discretize(this -> data_set, x);
     std::vector<std::vector<std::tuple<graph_hdf5_w, graph_hdf5>>*> serials(quant.size(), nullptr);
     // do prealloc
     std::vector<std::map<std::string, std::vector<int>*>> fnames(quant.size());
     for (size_t t(0); t < quant.size(); ++t){
         fnames.push_back(std::map<std::string, std::vector<int>*>());
         serials[t] = new std::vector<std::tuple<graph_hdf5_w, graph_hdf5>>();
         serials[t] -> reserve(quant[t].size());
     }
     std::vector<size_t> handles(quant.size(), 0);
     std::vector<std::thread*> th_(quant.size(), nullptr);
     for (size_t t(0); t < th_.size(); ++t){th_[t] = new std::thread(serialize, &quant[t], serials[t], &fnames[t], &handles[t]);}
     std::string title = "Graph Serialization";
     std::thread* prg = new std::thread(this -> progressbar1, &handles, this -> data_set -> size(), title);
     // sort the graphs to be saves according to their original root name and assure the
     // sample indexing is consistent.
     size_t idx = 0;
     std::map<std::string, std::vector< std::tuple<graph_hdf5_w, graph_hdf5>* >> collect = {};
     for (size_t t(0); t < quant.size(); ++t){
         th_[t] -> join(); delete th_[t];
         std::map<std::string, std::vector<int>*>::iterator itr;
         for (itr = fnames[t].begin(); itr != fnames[t].end(); ++itr){
             std::vector<std::string> spl = this -> split(itr -> first, "/");
             std::string id = itr -> first;
             id = (this -> ends_with(&path, "/")) ? path + id : path + "/" + id;
             for (int i : *itr -> second){collect[id].push_back(&(*serials[t])[i]);}
             idx += itr -> second -> size();
             delete itr -> second;
         }
     }
     std::vector<std::map<std::string, std::vector<int>*>>().swap(fnames);
     prg -> join(); delete prg;
     std::vector<size_t> prdata(collect.size(), 0);
     std::vector<size_t> lrdata(collect.size(), 0);
     std::vector<std::string*> titles(collect.size(), nullptr);
     std::vector<std::thread*> thdata(collect.size(), nullptr);
     std::vector<std::string> pth_verify(collect.size(), "");
     int dx(0), thrs(0);
     std::map<std::string, std::vector< std::tuple<graph_hdf5_w, graph_hdf5>* >>::iterator itf;
     for (itf = collect.begin(); itf != collect.end(); ++itf, ++dx){
         pth_verify[dx] = itf -> first;
         lrdata[dx] = itf -> second.size();
         titles[dx] = new std::string();
     }
     dx = 0;
     prg = new std::thread(this -> progressbar3, &prdata, &lrdata, &titles);
     for (itf = collect.begin(); itf != collect.end(); ++itf, ++dx, ++thrs){
         thdata[dx] = new std::thread(write, titles[dx], itf -> first, &prdata[dx], itf -> second);
         while (thrs >= threads){thrs = this -> running(&thdata, &prdata, &lrdata);}
     }
     this -> monitor(&thdata);
     for (size_t t(0); t < quant.size(); ++t){delete serials[t]; serials[t] = nullptr;}
     prg -> join(); delete prg;
     for (size_t x(0); x < pth_verify.size(); ++x){
         std::string nx = pth_verify[x];
         this -> replace(&nx, "/.", "/");
         this -> rename(pth_verify[x], nx);
         pth_verify[x] = nx;
     }
     this -> info("Validating Graph Cache...");
     std::map<std::string, graph_t*>* restored = this -> restore_graphs_(pth_verify, threads);
     bool valid = true;
     for (size_t x(0); x < this -> data_set -> size(); ++x){
         graph_t* dt = (*this -> data_set)[x];
         if (dt -> preselection){continue;}
         valid = valid && restored -> count(*dt -> hash);
         if (valid){continue;}
         break;
     }
     std::map<std::string, graph_t*>::iterator itr = restored -> begin();
     for (; itr != restored -> end(); ++itr){
         graph_t* grs = itr -> second;
         grs -> _purge_all();
         delete grs -> data_map_graph ; grs -> data_map_graph  = nullptr;
         delete grs -> data_map_node  ; grs -> data_map_node   = nullptr;
         delete grs -> data_map_edge  ; grs -> data_map_edge   = nullptr;
         delete grs -> truth_map_graph; grs -> truth_map_graph = nullptr;
         delete grs -> truth_map_node ; grs -> truth_map_node  = nullptr;
         delete grs -> truth_map_edge ; grs -> truth_map_edge  = nullptr;
         delete grs; itr -> second = nullptr;
     }
     restored -> clear();
     delete restored;
     if (valid){this -> success("Graph cache has been validated!"); return true;}
     this -> failure("The stored cache could not be verified, manually delete the cache folder");
     return false;
 }
References simply_plot::data, test_evaluation::gr, test_experimental_mc20::t, and tools::tools().
extract_data()
void dataloader::extract_data (graph_t * gr)
Definition at line 102 of file dataloader.cxx.
{
     this -> clean_data_elements(&gr -> truth_map_graph, &this -> truth_map_graph);
     this -> clean_data_elements(&gr -> truth_map_node , &this -> truth_map_node);
     this -> clean_data_elements(&gr -> truth_map_edge , &this -> truth_map_edge);
     this -> clean_data_elements(&gr -> data_map_graph , &this -> data_map_graph);
     this -> clean_data_elements(&gr -> data_map_node  , &this -> data_map_node);
     this -> clean_data_elements(&gr -> data_map_edge  , &this -> data_map_edge);
     this -> hash_map[*gr -> hash] = this -> data_set -> size();
     this -> data_index -> push_back(this -> data_set -> size());
     this -> data_set -> push_back(gr);
 }
References test_evaluation::gr.
Referenced by restore_graphs().
generate_kfold_set()
void dataloader::generate_kfold_set (int k)
Definition at line 12 of file dataset.cxx.
{
     if (this -> k_fold_validation.size()){return;}
     if (!this -> test_set -> size()){return;}
     bool all = false;
     for (int x(0); x < k; ++x){
         if (this -> k_fold_training.count(x)){continue;}
         this -> k_fold_training[x] = new std::vector<int>();
         this -> k_fold_validation[x] = new std::vector<int>();
         all = true;
     }
     if (!all){return;}
     std::map<int, std::vector<int>> folds = {};
     for (size_t x(0); x < this -> train_set -> size(); ++x){folds[x%(k+1)].push_back((*this -> train_set)[x]);}
     this -> success("Splitting training dataset (" + this -> to_string(this -> train_set -> size()) + ")");
     for (int x(0); x < k; ++x){
         std::vector<int>* val = this -> k_fold_validation[x];
         val -> insert(val -> end(), folds[x].begin(), folds[x].end());
         for (int y(0); y < k+1; ++y){
             if (y == x){continue;}
             val = this -> k_fold_training[x];
             val -> insert(val -> end(), folds[y].begin(), folds[y].end());
         }
         this -> success("---------------- k-Fold: " + this -> to_string(x+1) + " ----------------");
         this -> success("-> train: " + this -> to_string(this -> k_fold_training[x] -> size()) + ")");
         this -> success("-> validation: " + this -> to_string(this -> k_fold_validation[x] -> size()) + ")");
     }
 }
References end(), tools::to_string(), and main::x.
generate_test_set()
void dataloader::generate_test_set (float percentage = 50)
Definition at line 41 of file dataset.cxx.
{
     if (this -> test_set -> size()){return;}
     this -> data_set    -> shrink_to_fit();
     this -> data_index  -> shrink_to_fit();
     size_t fx = (this -> data_set -> size()) * float(percentage/100);
     this -> shuffle(this -> data_index);
     for (size_t x(0); x < this -> data_index -> size(); ++x){
         std::vector<int>* dx = nullptr;
         if (x >= fx){dx = this -> test_set;}
         else {dx = this -> train_set;}
         dx -> push_back(this -> data_index -> at(x));
     }
     this -> test_set -> shrink_to_fit();
     this -> train_set -> shrink_to_fit();
     this -> success("Splitting entire dataset (" + this -> to_string(this -> data_set -> size()) + ")");
     this -> success("-> test: "  + this -> to_string(this -> test_set -> size())  + ")");
     this -> success("-> train: " + this -> to_string(this -> train_set -> size()) + ")");
 }
References main::fx, tools::to_string(), and main::x.
get_inference()
std::map< std::string, std::vector< graph_t * > > * dataloader::get_inference ()
Definition at line 104 of file dataset.cxx.
{
     auto lamb = [](std::vector<graph_t*>* sort){
         std::map<long, graph_t*> tmp = {};
         for (size_t x(0); x < sort -> size(); ++x){tmp[(*sort)[x] -> event_index] = (*sort)[x];}
         std::map<long, graph_t*>::iterator itr = tmp.begin();
         for (size_t t(0); itr != tmp.end(); ++itr, ++t){(*sort)[t] = itr -> second;}
     };
     std::map<std::string, std::vector<graph_t*>>* out = new std::map<std::string, std::vector<graph_t*>>();
     for (size_t x(0); x < this -> data_set -> size(); ++x){
         graph_t* gr = (*this -> data_set)[x];
         (*out)[*(gr -> filename)].push_back(gr);
     }
     std::vector<std::thread*> th(out -> size(), nullptr);
     std::map<std::string, std::vector<graph_t*>>::iterator itr = out -> begin();
     for (size_t t(0); itr != out -> end(); ++itr, ++t){th[t] = new std::thread(lamb, &itr -> second);}
     this -> monitor(&th);
     return out;
 }
References end(), test_evaluation::gr, main::out, test_experimental_mc20::t, main::tmp, and main::x.
get_k_train_set()
std::vector< graph_t * > * dataloader::get_k_train_set (int k)
Definition at line 61 of file dataset.cxx.
{
     if (this -> gr_k_fold_training.count(k)){
         this -> shuffle(this -> gr_k_fold_training[k]);
         return this -> gr_k_fold_training[k];
     }
     std::vector<int>* kdata = nullptr;
     if (!this -> k_fold_training.size()){kdata = this -> data_index;}
     else if (!this -> k_fold_training.count(k)){
         this -> warning("Specified an invalid k-fold index.");
         return nullptr;
     }
     else {kdata = this -> k_fold_training[k];}
     this -> shuffle(kdata);
     this -> gr_k_fold_training[k] = new std::vector<graph_t*>();
     this -> put(this -> gr_k_fold_training[k], this -> data_set, kdata);
     this -> gr_k_fold_training[k] -> shrink_to_fit();
     return this -> gr_k_fold_training[k];
 }
References tools::put().
get_k_validation_set()
std::vector< graph_t * > * dataloader::get_k_validation_set (int k)
Definition at line 82 of file dataset.cxx.
{
     if (this -> gr_k_fold_validation.count(k)){return this -> gr_k_fold_validation[k];}
     std::vector<int>* kdata = this -> k_fold_validation[k];
     this -> shuffle(kdata);
     this -> gr_k_fold_validation[k] = new std::vector<graph_t*>();
     this -> put(this -> gr_k_fold_validation[k], this -> data_set, kdata);
     this -> gr_k_fold_validation[k] -> shrink_to_fit();
     return this -> gr_k_fold_validation[k];
 }
References tools::put().
get_random()
std::vector< graph_t * > dataloader::get_random (int num = 5)
Definition at line 5 of file dataset.cxx.
{
     this -> shuffle(this -> data_index);
     std::vector<graph_t*> out = {};
     for (int k(0); k < num; ++k){out.push_back((*this -> data_set)[(*this -> data_index)[k]]);}
     return out;
 }
References main::out.
get_test_set()
std::vector< graph_t * > * dataloader::get_test_set ()
Definition at line 92 of file dataset.cxx.
{
     if (this -> gr_test){return this -> gr_test;}
     this -> shuffle(this -> test_set);
     std::vector<graph_t*>* output = new std::vector<graph_t*>();
     this -> put(output, this -> data_set, test_set);
     output -> shrink_to_fit();
     this -> gr_test = output;
     return output;
 }
References tools::put().
restore_dataset()
bool dataloader::restore_dataset (std::string path)
Definition at line 175 of file dataset.cxx.
{
     if (!path.size()){return true;}
     if (this -> k_fold_training.size()){return true;}
     std::vector<folds_t> data = {};
     io* io_g = new io();
     io_g -> start(path, "read");
     io_g -> read(&data, "kfolds");
     io_g -> end();
     delete io_g;
     for (size_t x(0); x < data.size(); ++x){
         folds_t* kf = &data[x];
         int kv = kf -> k;
         std::string hash = std::string(kf -> hash);
         kf -> flush_data();
         if (!this -> hash_map.count(hash)){continue;}
         int index = this -> hash_map[hash];
         if (kf -> is_eval){this -> test_set -> push_back(index); continue;}
         if (!kv){this -> train_set -> push_back(index);}
         if (!this -> k_fold_training.count(kv)){
             this -> k_fold_training[kv]   = new std::vector<int>();
             this -> k_fold_validation[kv] = new std::vector<int>();
         }
         std::vector<int>* bin = nullptr;
         if (kf -> is_train){bin = this -> k_fold_training[kv];}
         else if (kf -> is_valid){bin = this -> k_fold_validation[kv];}
         else {continue;}
         bin -> push_back(index);
     }
     if (!data.size()){return false;}
     std::string msg_tr = "Restored training dataset (" + this -> to_string(this -> train_set -> size()) + ")";
     std::string msg_ts = "Leave out sample is (" + this -> to_string(this -> test_set -> size()) + ")";
     this -> success(msg_tr);
     if (this -> test_set -> size()){this -> success(msg_ts);}
     std::map<int, std::vector<int>*>::iterator itr = this -> k_fold_training.begin();
     for (; itr != this -> k_fold_training.end(); ++itr){
         int k = itr -> first;
         this -> success("---------------- k-Fold: " + this -> to_string(k+1) + " ----------------");
         this -> success("-> train: "      + this -> to_string(this -> k_fold_training[k] -> size())   + ")");
         this -> success("-> validation: " + this -> to_string(this -> k_fold_validation[k] -> size()) + ")");
     }
     this -> hash_map.clear();
     return true;
 }
References simply_plot::data, end(), index, main::kf, childrenkinematics.figures::path(), read(), analysis::start(), tools::to_string(), and main::x.
restore_graphs() [1/2]
void dataloader::restore_graphs (std::string paths, int threads)
Definition at line 334 of file cache.cxx.
{
     std::vector<std::string> files = this -> ls(path, ".h5");
     this -> restore_graphs(files, threads);
 }
References tools::ls(), childrenkinematics.figures::path(), restore_graphs(), and main::threads.
restore_graphs() [2/2]
void dataloader::restore_graphs (std::vector< std::string > paths, int threads)
Definition at line 321 of file cache.cxx.
{
     std::map<std::string, graph_t*>* restored = this -> restore_graphs_(path, threads);
     std::map<std::string, graph_t*>::iterator itr;
     for (itr = restored -> begin(); itr != restored -> end(); ++itr){
         this -> extract_data(itr -> second);
         (*restored)[itr -> first] = nullptr;
     }
     this -> success("Restored " + std::to_string(restored -> size()) + " Graphs from cache!");
     restored -> clear();
     delete restored;
 }
References end(), extract_data(), childrenkinematics.figures::path(), and main::threads.
Referenced by restore_graphs().
safe_delete()
void dataloader::safe_delete (std::vector< graph_t * > * data) static
Definition at line 294 of file dataloader.cxx.
{
     for (size_t x(0); x < data -> size(); ++x){
         (*data)[x] -> _purge_all();
         delete (*data)[x];
         (*data)[x] = nullptr;
     }
     data -> clear();
     data -> shrink_to_fit();
     delete data;
     #if _server
     c10::cuda::CUDACachingAllocator::emptyCache();
     #endif
 }
References simply_plot::data, and main::x.
start_cuda_server()
void dataloader::start_cuda_server ()
Definition at line 383 of file dataloader.cxx.
{
     if (!_server){return;}
     if (this -> cuda_mem){return;}
     auto monitor = [this](){
         this -> info("Starting CUDA server!");
         while (this -> data_set){this -> cuda_memory_server();}
         this -> info("Closing CUDA server!");
     };
     this -> cuda_mem = new std::thread(monitor);
 }
References _server.
Friends And Related Function Documentation
analysis
friend class analysis friend
Definition at line 60 of file dataloader.h.
The documentation for this class was generated from the following files:
dataloader.h
cache.cxx
dataloader.cxx
dataset.cxx