AnalysisG: cproperty< T, G > Class Template Reference
cproperty< T, G > Class Template Reference
A template class implementing a property system with getter/setter callbacks.
#include <property.h>
Public Member Functions
cproperty ()
Default constructor.
void set_setter (std::function< void(T *, G *)> c=x_setter< T, G >)
Sets the setter callback function.
void set_getter (std::function< void(T *, G *)> c=x_getter< T, G >)
Sets the getter callback function.
void set_object (G *obj)
Sets the owning object for callback invocation.
cproperty & operator= (const T &val)
Assignment operator.
T operator+ (const T &val)
Addition operator.
bool operator== (const T &val)
Equality comparison operator.
bool operator!= (const T &val)
Inequality comparison operator.
std::ostream & operator<< (std::ostream &out)
Stream output operator.
operator T ()
Implicit conversion operator.
T * operator& ()
Address-of operator.
void clear ()
Clears the property value to its default state.
Private Attributes
T data
The stored property value.
G * obj = nullptr
Pointer to the owning object.
bool has_getter = false
Flag indicating if a getter is set.
bool has_setter = false
Flag indicating if a setter is set.
std::function< void(T *, G *)> setter
The setter callback function.
std::function< void(T *, G *)> getter
The getter callback function.
Detailed Description
template<typename T, typename G>
class cproperty< T, G >
A template class implementing a property system with getter/setter callbacks.
The cproperty class provides a property-like interface where reading or writing the property value can trigger custom getter or setter functions. This is useful for:
Validating values before assignment
Computing values on-demand (lazy evaluation)
Synchronizing values with internal state
Providing Python-friendly property access via Cython bindings
Template Parameters
T The type of the property value.
G The type of the owning object (used for callbacks).
Usage Example
class MyClass {
public:
    cproperty<int, MyClass> value;
    MyClass() {
        value.set_getter(get_value);
        value.set_setter(set_value);
        value.set_object(this);
    }
private:
    int m_value = 0;
    static void get_value(int* out, MyClass* obj) {
        *out = obj->m_value;
    }
    static void set_value(int* in, MyClass* obj) {
        if (*in >= 0) obj->m_value = *in;  // Validation
    }
};
// Usage:
MyClass obj;
obj.value = 42;      // Calls set_value
int x = obj.value;   // Calls get_value
Definition at line 82 of file property.h.
Constructor & Destructor Documentation
cproperty()
template<typename T , typename G > cproperty< T, G >::cproperty () inline
Default constructor.
Initializes the property with a default-constructed value.
Definition at line 89 of file property.h.
Member Function Documentation
clear()
template<typename T , typename G > void cproperty< T, G >::clear () inline
Clears the property value to its default state.
Definition at line 186 of file property.h.
References cproperty< T, G >::data, and cproperty< T, G >::has_getter.
operator T()
template<typename T , typename G > cproperty< T, G >::operator T () inline
Implicit conversion operator.
Converts the property to its value type, calling the getter if defined.
Returns
The property value.
Definition at line 166 of file property.h.
operator!=()
template<typename T , typename G > bool cproperty< T, G >::operator!= (const T & val) inline
Inequality comparison operator.
Parameters
val The value to compare against.
Returns
True if the property value does not equal val.
Definition at line 149 of file property.h.
References cproperty< T, G >::data.
operator&()
template<typename T , typename G > T * cproperty< T, G >::operator& () inline
Address-of operator.
Returns a pointer to the property value, calling the getter first if defined.
Returns
Pointer to the property value.
Definition at line 177 of file property.h.
References cproperty< T, G >::data, cproperty< T, G >::getter, cproperty< T, G >::has_getter, and cproperty< T, G >::obj.
operator+()
template<typename T , typename G > T cproperty< T, G >::operator+ (const T & val) inline
Addition operator.
Parameters
val The value to add.
Returns
The result of adding val to the property value.
Definition at line 135 of file property.h.
References cproperty< T, G >::data.
operator<<()
template<typename T , typename G > std::ostream & cproperty< T, G >::operator<< (std::ostream & out) inline
Stream output operator.
Parameters
out The output stream.
Returns
Reference to the output stream.
Definition at line 156 of file property.h.
References cproperty< T, G >::data.
operator=()
template<typename T , typename G > cproperty & cproperty< T, G >::operator= (const T & val) inline
Assignment operator.
Assigns a value to the property and calls the setter if defined.
Parameters
val The value to assign.
Returns
Reference to this property.
Definition at line 123 of file property.h.
References cproperty< T, G >::data, cproperty< T, G >::has_setter, cproperty< T, G >::obj, and cproperty< T, G >::setter.
operator==()
template<typename T , typename G > bool cproperty< T, G >::operator== (const T & val) inline
Equality comparison operator.
Parameters
val The value to compare against.
Returns
True if the property value equals val.
Definition at line 142 of file property.h.
References cproperty< T, G >::data.
set_getter()
template<typename T , typename G > void cproperty< T, G >::set_getter (std::function< void(T *, G *)> c = x_getter<T, G>) inline
Sets the getter callback function.
Parameters
c The getter function to call when the property is read. Signature: void(T* value, G* owner)
Definition at line 106 of file property.h.
References c, cproperty< T, G >::getter, and cproperty< T, G >::has_getter.
Referenced by event_template::event_template(), graph_template::graph_template(), jet::jet(), meta::meta(), metric_template::metric_template(), model_template::model_template(), particle_template::particle_template(), selection_template::selection_template(), top_children::top_children(), truthjet::truthjet(), graph_template::add_edge_data_feature(), graph_template::add_edge_truth_feature(), graph_template::add_graph_data_feature(), graph_template::add_graph_truth_feature(), graph_template::add_node_data_feature(), and graph_template::add_node_truth_feature().
set_object()
template<typename T , typename G > void cproperty< T, G >::set_object (G * obj) inline
Sets the owning object for callback invocation.
Parameters
obj Pointer to the object that owns this property.
Definition at line 115 of file property.h.
References cproperty< T, G >::obj.
Referenced by event_template::event_template(), graph_template::graph_template(), jet::jet(), meta::meta(), metric_template::metric_template(), model_template::model_template(), particle_template::particle_template(), selection_template::selection_template(), top_children::top_children(), truthjet::truthjet(), graph_template::add_edge_data_feature(), graph_template::add_edge_truth_feature(), graph_template::add_graph_data_feature(), graph_template::add_graph_truth_feature(), graph_template::add_node_data_feature(), graph_template::add_node_truth_feature(), and optimizer_params_t::operator()().
set_setter()
template<typename T , typename G > void cproperty< T, G >::set_setter (std::function< void(T *, G *)> c = x_setter<T, G>) inline
Sets the setter callback function.
Parameters
c The setter function to call when the property is assigned. Signature: void(T* value, G* owner)
Definition at line 96 of file property.h.
References c, cproperty< T, G >::has_setter, and cproperty< T, G >::setter.
Referenced by event_template::event_template(), graph_template::graph_template(), metric_template::metric_template(), model_template::model_template(), particle_template::particle_template(), selection_template::selection_template(), and optimizer_params_t::operator()().
Member Data Documentation
data
template<typename T , typename G > T cproperty< T, G >::data private
The stored property value.
Definition at line 193 of file property.h.
Referenced by cproperty< T, G >::clear(), cproperty< bool, electron >::operator bool(), cproperty< T, G >::operator!=(), cproperty< T, G >::operator&(), cproperty< T, G >::operator+(), cproperty< T, G >::operator<<(), cproperty< T, G >::operator=(), and cproperty< T, G >::operator==().
getter
template<typename T , typename G > std::function<void(T*, G*)> cproperty< T, G >::getter private
The getter callback function.
Definition at line 198 of file property.h.
Referenced by cproperty< bool, electron >::operator bool(), cproperty< T, G >::operator&(), and cproperty< T, G >::set_getter().
has_getter
template<typename T , typename G > bool cproperty< T, G >::has_getter = false private
Flag indicating if a getter is set.
Definition at line 195 of file property.h.
Referenced by cproperty< T, G >::clear(), cproperty< bool, electron >::operator bool(), cproperty< T, G >::operator&(), and cproperty< T, G >::set_getter().
has_setter
template<typename T , typename G > bool cproperty< T, G >::has_setter = false private
Flag indicating if a setter is set.
Definition at line 196 of file property.h.
Referenced by cproperty< T, G >::operator=(), and cproperty< T, G >::set_setter().
obj
template<typename T , typename G > G* cproperty< T, G >::obj = nullptr private
Pointer to the owning object.
Definition at line 194 of file property.h.
Referenced by cproperty< bool, electron >::operator bool(), cproperty< T, G >::operator&(), cproperty< T, G >::operator=(), and cproperty< T, G >::set_object().
setter
template<typename T , typename G > std::function<void(T*, G*)> cproperty< T, G >::setter private
The setter callback function.
Definition at line 197 of file property.h.
Referenced by cproperty< T, G >::operator=(), and cproperty< T, G >::set_setter().
The documentation for this class was generated from the following file:
property.h