AnalysisG: graph_jets Class Reference
graph_jets Class Reference
#include <graphs.h>
Public Member Functions
graph_jets ()
virtual ~graph_jets ()
graph_template * clone () override
void CompileEvent () override
bool PreSelection () override
graph_jets ()
~graph_jets () override
graph_template * clone () override
void CompileEvent () override
graph_jets ()
~graph_jets () override
graph_template * clone () override
void CompileEvent () override
Public Member Functions inherited from graph_template
graph_template ()
virtual ~graph_template ()
void define_particle_nodes (std::vector< particle_template * > *prt)
void define_topology (std::function< bool(particle_template *, particle_template *)> fx)
void flush_particles ()
bool operator== (graph_template &p)
template<typename G >
G * get_event ()
template<typename G , typename O , typename X >
void add_graph_truth_feature (O *ev, X fx, std::string name)
template<typename G , typename O , typename X >
void add_graph_data_feature (O *ev, X fx, std::string name)
template<typename G , typename O , typename X >
void add_node_truth_feature (X fx, std::string name)
template<typename G , typename O , typename X >
void add_node_data_feature (X fx, std::string name)
template<typename G , typename O , typename X >
void add_edge_truth_feature (X fx, std::string name)
template<typename G , typename O , typename X >
void add_edge_data_feature (X fx, std::string name)
bool double_neutrino (double mass_top=172.62 *1000, double mass_wboson=80.385 *1000, double top_perc=0.85, double w_perc=0.95, double distance=1e-8, int steps=10)
Public Member Functions inherited from tools
tools ()
Constructor for the tools class.
~tools ()
Destructor for the tools class.
std::vector< std::string > split (std::string inpt, std::string del)
Splits a string into a vector of substrings based on a delimiter.
std::string trim (std::string s)
Removes whitespace from the beginning and end of a string.
template<typename T >
std::string type_name ()
Gets the type name of a variable as a string (for debugging).
template<typename g >
g sum (std::vector< g > *inpt)
Sums the elements of a vector.
Additional Inherited Members
Static Public Member Functions inherited from tools
static void create_path (std::string path)
Creates a directory path, including parent directories if needed.
static void delete_path (std::string path)
Deletes a directory path and its contents.
static bool is_file (std::string path)
Checks if a path refers to an existing file.
static void rename (std::string start, std::string target)
Renames a file or directory.
static std::string absolute_path (std::string path)
Converts a relative path to an absolute path.
static std::vector< std::string > ls (std::string path, std::string ext="")
Lists files in a directory, optionally filtered by extension.
static std::string to_string (double val)
Converts a double value to a string with standard precision.
static std::string to_string (double val, int prec)
Converts a double value to a string with specified precision.
static void replace (std::string *in, std::string repl_str, std::string repl_with)
Replaces all occurrences of a substring in a string.
static bool has_string (std::string *inpt, std::string trg)
Checks if a string contains a specific substring.
static bool ends_with (std::string *inpt, std::string val)
Checks if a string ends with a specific substring.
static bool has_value (std::vector< std::string > *data, std::string trg)
Checks if a vector of strings contains a specific string.
template<typename T >
static void flush (std::vector< T * > *inpt)
Empties a vector and all objects it points to.
template<typename g >
static void put (std::vector< g * > *out, std::vector< g * > *src, std::vector< int > *trg)
Fills a vector with pointers from another vector based on a selection index.
template<typename C , typename T >
static void extract (std::vector< T > *prop, std::vector< C * > *src, void(*get_prop)(T *, C *))
Extracts a specific property from a vector of objects into a new vector.
Public Attributes inherited from graph_template
cproperty< long, graph_template > index
cproperty< double, graph_template > weight
cproperty< bool, graph_template > preselection
cproperty< std::string, graph_template > hash
cproperty< std::string, graph_template > tree
cproperty< std::string, graph_template > name
int threadIdx = -1
std::string filename = ""
meta * meta_data = nullptr
Detailed Description
Definition at line 43 of file bsm_4tops/include/bsm_4tops/graphs.h.
Constructor & Destructor Documentation
graph_jets() [1/3]
graph_jets::graph_jets ()
Definition at line 178 of file bsm_4tops/cxx/graphs.cxx.
 {this -> name = "graph_jets";}
References graph_template::name.
Referenced by clone().
~graph_jets() [1/3]
graph_jets::~graph_jets () virtual
Definition at line 179 of file bsm_4tops/cxx/graphs.cxx.
 {}
graph_jets() [2/3]
graph_jets::graph_jets ()
~graph_jets() [2/3]
graph_jets::~graph_jets () override
graph_jets() [3/3]
graph_jets::graph_jets ()
~graph_jets() [3/3]
graph_jets::~graph_jets () override
Member Function Documentation
clone() [1/3]
graph_template* graph_jets::clone () override virtual
Reimplemented from graph_template.
clone() [2/3]
graph_template* graph_jets::clone () override virtual
Reimplemented from graph_template.
clone() [3/3]
graph_template * graph_jets::clone () override virtual
Reimplemented from graph_template.
Definition at line 180 of file bsm_4tops/cxx/graphs.cxx.
 {return (graph_template*)new graph_jets();}
References graph_jets().
CompileEvent() [1/3]
void graph_jets::CompileEvent () override virtual
Reimplemented from graph_template.
CompileEvent() [2/3]
void graph_jets::CompileEvent () override virtual
Reimplemented from graph_template.
CompileEvent() [3/3]
void graph_jets::CompileEvent () override virtual
Reimplemented from graph_template.
Definition at line 191 of file bsm_4tops/cxx/graphs.cxx.
{
     bsm_4tops* event = this -> get_event<bsm_4tops>();
     std::vector<particle_template*> nodes = {};
     std::vector<particle_template*> ch = event -> Children;
     for (size_t x(0); x < ch.size(); ++x){
         if (!ch[x] -> is_lep && !ch[x] -> is_nu){continue;}
         nodes.push_back(ch[x]);
     }
     nodes.insert(nodes.end(), event -> Jets.begin(), event -> Jets.end());
     this -> define_particle_nodes(&nodes);
     this -> define_topology(fulltopo);
     // ---------------- truth ------------------- //
     this -> add_graph_truth_feature<bool, bsm_4tops>(event, signal_event, "signal");
     this -> add_graph_truth_feature<int , bsm_4tops>(event, num_lepton  , "n_lep");
     this -> add_graph_truth_feature<int , bsm_4tops>(event, num_tops    , "ntops");
     this -> add_node_truth_feature<int, particle_template>(top_node, "top_node");
     this -> add_node_truth_feature<int, particle_template>(res_node, "res_node");
     this -> add_edge_truth_feature<int, particle_template>(res_edge, "res_edge");
     this -> add_edge_truth_feature<int, particle_template>(top_edge, "top_edge");
     // ---------------- data -------------------- //
     this -> add_graph_data_feature<double, bsm_4tops>(event, missing_et       , "met");
     this -> add_graph_data_feature<double, bsm_4tops>(event, missing_phi      , "phi");
     this -> add_graph_data_feature<double, bsm_4tops>(event, num_jets         , "num_jets");
     this -> add_graph_data_feature<double, bsm_4tops>(event, num_children_leps, "num_leps");
     this -> add_graph_data_feature<double, bsm_4tops>(event, event_weight     , "weight");
     this -> add_graph_data_feature<long  , bsm_4tops>(event, event_number     , "event_number");
     this -> add_node_data_feature<double, particle_template>(pt    , "pt");
     this -> add_node_data_feature<double, particle_template>(eta   , "eta");
     this -> add_node_data_feature<double, particle_template>(phi   , "phi");
     this -> add_node_data_feature<double, particle_template>(energy, "energy");
     this -> add_node_data_feature<double, particle_template>(charge, "charge");
     this -> add_node_data_feature<int, particle_template>(is_lepton, "is_lep");
     this -> add_node_data_feature<int, particle_template>(is_bquark, "is_b");
 }
References graph_template::define_particle_nodes(), graph_template::define_topology(), is_lep, is_nu, and main::x.
PreSelection()
bool graph_jets::PreSelection () override virtual
Reimplemented from graph_template.
Definition at line 182 of file bsm_4tops/cxx/graphs.cxx.
{
 //    bsm_4tops* evn = this -> get_event<bsm_4tops>();
 //    std::vector<particle_template*> leptons;
 //    for (size_t x(0); x < evn -> Electrons.size(); ++x){leptons.push_back(evn -> Electrons[x]);}
 //    for (size_t x(0); x < evn -> Muons.size(); ++x){leptons.push_back(evn -> Muons[x]);}
 //    if (leptons.size() != 2){return false;}
     return true; //leptons[0] -> charge == leptons[1] -> charge;
 }
The documentation for this class was generated from the following files:
bsm_4tops/include/bsm_4tops/graphs.h
bsm_4tops/cxx/graphs.cxx