AnalysisG: combinatorial.cxx File Reference
combinatorial.cxx File Reference
#include "combinatorial.h"
#include <bsm_4tops/event.h>
#include <pyc/pyc.h>
Functions
double chi2 (neutrino *nu, particle_template *nut)
particle_template * safe_get (std::vector< particle_template * > *data, int idx)
Function Documentation
chi2()
double chi2 (neutrino * nu, particle_template * nut)
Definition at line 59 of file combinatorial.cxx.
{
     if (!nut){return -1;}
     double ch = std::pow(nu -> px - nut -> px, 2);
     ch += std::pow(nu -> py - nut -> py, 2);
     ch += std::pow(nu -> pz - nut -> pz, 2);
     return ch;
 }
Referenced by nusol_::Nu(), and combinatorial::reconstruction().
safe_get()
particle_template* safe_get (std::vector< particle_template * > * data, int idx)
Definition at line 68 of file combinatorial.cxx.
{
     return (data -> size() != 2) ? nullptr : data -> at(idx);
 }
References simply_plot::data.
Referenced by combinatorial::reconstruction().