AnalysisG: eigen.cxx File Reference
eigen.cxx File Reference
#include <iostream>
#include <complex>
#include <cstdio>
#include <cmath>
Macros
#define SIZE 3
Functions
void multiply (double matrix[SIZE][SIZE], double vector[SIZE], double result[SIZE])
double vector_norm (double vector[SIZE])
void normalize (double vector[SIZE])
double power_iteration (double matrix[SIZE][SIZE], double eigenvector[SIZE], int max_iterations, double tolerance)
int main ()
Macro Definition Documentation
SIZE
#define SIZE 3
Definition at line 6 of file eigen.cxx.
Function Documentation
main()
int main ()
Definition at line 47 of file eigen.cxx.
            {
     double M[3][3] = {
         8.01318657e+01, 5.51435597e+00, 1.16572607e+07,
         4.27558938e+01, 8.36588978e+00, 7.40343012e+06,
         1.33325465e-05 -4.11361520e-05, -7.23462912e+00
     };
     double eigenvector[SIZE];
     double eigenvalue = power_iteration(M, eigenvector, 10000, 1e-12);
     printf("%.10g %.10g %.10g \n", M[0][0], M[0][1], M[0][2]);
     printf("%.10g %.10g %.10g \n", M[1][0], M[1][1], M[1][2]);
     printf("%.10g %.10g %.10g \n", M[2][0], M[2][1], M[2][2]);
     printf("Dominant Eigenvalue: %f\n", eigenvalue);
     printf("Corresponding Eigenvector: [");
     for (int i = 0; i < SIZE; i++) {
         printf("%f", eigenvector[i]);
         if (i < SIZE - 1) printf(", ");
     }
     printf("]\n");
     return 0;
 }
References test_particles::e, pyc::physics::cartesian::separate::M(), power_iteration(), and SIZE.
multiply()
void multiply (double matrix[SIZE][SIZE], double vector[SIZE], double result[SIZE])
Definition at line 8 of file eigen.cxx.
{
     for (int i = 0; i < SIZE; i++) {
         result[i] = 0.0;
         for (int j = 0; j < SIZE; j++) {result[i] += matrix[i][j] * vector[j];}
     }
 }
References SIZE, and helper::vector().
Referenced by power_iteration().
normalize()
void normalize (double vector[SIZE])
Definition at line 21 of file eigen.cxx.
{
     double norm = vector_norm(vector);
     for (int i = 0; i < SIZE; i++) {vector[i] /= norm;}
 }
References SIZE, helper::vector(), and vector_norm().
Referenced by power_iteration().
power_iteration()
double power_iteration (double matrix[SIZE][SIZE], double eigenvector[SIZE], int max_iterations, double tolerance)
Definition at line 26 of file eigen.cxx.
{
     double eigenvalue = 0.0;
     double temp_vector[SIZE] = {1.0, 1.0, 1.0};  // Initial guess for the eigenvector
     for (int iteration = 0; iteration < max_iterations; iteration++) {
         double result[SIZE];
         multiply(matrix, temp_vector, result);
         // Calculate the new eigenvalue
         double new_eigenvalue = vector_norm(result);
         normalize(result);
         // Check for convergence
         if (fabs(new_eigenvalue - eigenvalue) < tolerance) {break;}
         eigenvalue = new_eigenvalue;
         for (int i = 0; i < SIZE; i++) {temp_vector[i] = result[i];}
         for (int i = 0; i < SIZE; i++) {eigenvector[i] = result[i];}
     }
     return eigenvalue;
 }
References multiply(), normalize(), SIZE, and vector_norm().
Referenced by main().
vector_norm()
double vector_norm (double vector[SIZE])
Definition at line 15 of file eigen.cxx.
{
     double norm = 0.0;
     for (int i = 0; i < SIZE; i++) {norm += vector[i] * vector[i];}
     return sqrt(norm);
 }
References SIZE, and helper::vector().
Referenced by normalize(), and power_iteration().