AnalysisG: particles.h File Reference
events/exp_mc20/include/exp_mc20/particles.h File Reference
#include <templates/particle_template.h>
Classes
class top
class child
class physics_detector
class physics_truth
class electron
class muon
class jet
Functions
template<typename g >
void pmu (std::vector< g * > *out, element_t *el)
Function Documentation
pmu()
template<typename g > void pmu (std::vector< g * > * out, element_t * el)
Definition at line 7 of file events/exp_mc20/include/exp_mc20/particles.h.
{
     std::vector<float> pt, eta, phi, en, ch;
     el -> get("pt"    , &pt);
     el -> get("eta"   , &eta);
     el -> get("phi"   , &phi);
     el -> get("energy", &en);
     for (size_t x(0); x < pt.size(); ++x){
         g* prt     = new g();
         prt -> pt  = pt[x];
         prt -> eta = eta[x];
         prt -> phi = phi[x];
         prt -> e   = en[x];
         out -> push_back(prt);
     }
 }
References test_particles::e, main::out, and main::x.
Referenced by pyc::physics::polar::combined::Beta(), pyc::physics::polar::combined::Beta2(), graph_::edge_aggregation(), pyc::graph::polar::edge_aggregation(), pyc::physics::polar::combined::M(), pyc::physics::polar::combined::M2(), pyc::physics::polar::combined::Mt(), pyc::physics::polar::combined::Mt2(), pyc::graph::polar::node_aggregation(), pyc::physics::polar::combined::P(), pyc::physics::polar::combined::P2(), pyc::transform::combined::Px(), pyc::transform::combined::PxPyPz(), transform_::PxPyPz(), pyc::transform::combined::PxPyPzE(), transform_::PxPyPzE(), pyc::transform::combined::Py(), pyc::transform::combined::Pz(), and pyc::physics::polar::combined::Theta().