AnalysisG: graph_features.h File Reference
graph_features.h File Reference
Functions
static void signal_event (bool *o, exp_mc20 *event)
static void num_tops (int *o, exp_mc20 *event)
static void num_neutrino (int *o, exp_mc20 *event)
static void num_lepton (int *o, exp_mc20 *event)
static void missing_et (double *o, exp_mc20 *event)
static void missing_phi (double *o, exp_mc20 *event)
static void num_children_leps (double *o, exp_mc20 *event)
static void num_leps (double *o, exp_mc20 *event)
static void num_jets (double *o, exp_mc20 *event)
static void event_number (long *o, exp_mc20 *event)
static void event_weight (double *o, exp_mc20 *event)
Function Documentation
event_number()
static void event_number (long * o, exp_mc20 * event) static
Definition at line 57 of file exp_mc20/include/exp_mc20/graph_features.h.
References event_number().
Referenced by event_number().
event_weight()
static void event_weight (double * o, exp_mc20 * event) static
Definition at line 58 of file exp_mc20/include/exp_mc20/graph_features.h.
References weight.
missing_et()
static void missing_et (double * o, exp_mc20 * event) static
Definition at line 42 of file exp_mc20/include/exp_mc20/graph_features.h.
missing_phi()
static void missing_phi (double * o, exp_mc20 * event) static
Definition at line 43 of file exp_mc20/include/exp_mc20/graph_features.h.
References phi.
num_children_leps()
static void num_children_leps (double * o, exp_mc20 * event) static
Definition at line 45 of file exp_mc20/include/exp_mc20/graph_features.h.
References is_lep, is_nu, and num_leps().
num_jets()
static void num_jets (double * o, exp_mc20 * event) static
Definition at line 56 of file exp_mc20/include/exp_mc20/graph_features.h.
num_leps()
static void num_leps (double * o, exp_mc20 * event) static
Definition at line 55 of file exp_mc20/include/exp_mc20/graph_features.h.
Referenced by num_children_leps().
num_lepton()
static void num_lepton (int * o, exp_mc20 * event) static
Definition at line 30 of file exp_mc20/include/exp_mc20/graph_features.h.
References is_lep, and is_nu.
num_neutrino()
static void num_neutrino (int * o, exp_mc20 * event) static
Definition at line 20 of file exp_mc20/include/exp_mc20/graph_features.h.
References is_nu.
num_tops()
static void num_tops (int * o, exp_mc20 * event) static
Definition at line 18 of file exp_mc20/include/exp_mc20/graph_features.h.
signal_event()
static void signal_event (bool * o, exp_mc20 * event) static
Definition at line 5 of file exp_mc20/include/exp_mc20/graph_features.h.