AnalysisG: graph_template.h File Reference
graph_template.h File Reference
Defines the graph_template class and graph_t structure for graph-based analysis.
#include <templates/particle_template.h>
#include <templates/event_template.h>
#include <structs/property.h>
#include <structs/event.h>
#include <structs/folds.h>
#include <structs/enums.h>
#include <tools/tensor_cast.h>
#include <tools/tools.h>
#include <c10/core/DeviceType.h>
#include <torch/torch.h>
#include <mutex>
#include <pyc/pyc.h>
Classes
struct graph_t
Data structure holding graph tensors for ML training and inference.
class graph_template
Base class for converting physics events into graph representations.
Macros
#define cu_pyc c10::kCPU
Functions
static bool fulltopo (particle_template *, particle_template *)
Default topology function that connects all node pairs.
Detailed Description
Defines the graph_template class and graph_t structure for graph-based analysis.
This file contains the declaration of the graph_template class and graph_t structure, which form the foundation of graph-based machine learning analysis in AnalysisG. The graph template defines how physics events are converted into graph representations, while graph_t holds the actual tensor data for training and inference.
Overview
Graph construction in AnalysisG follows this workflow:
Define which particles become nodes via define_particle_nodes()
Define edge topology via define_topology()
Add node/edge/graph features using template methods
Export to graph_t for batching and GPU transfer
Feature Types
Features are prefixed to indicate their purpose:
D-*: Data features (model inputs)
T-*: Truth features (training targets)
Definition in file graph_template.h.
Macro Definition Documentation
cu_pyc
#define cu_pyc c10::kCPU
Definition at line 48 of file graph_template.h.
Function Documentation
fulltopo()
static bool fulltopo (particle_template * , particle_template *) static
Default topology function that connects all node pairs.
Parameters
p1 First particle (unused).
p2 Second particle (unused).
Returns
Always returns true (fully connected graph).
Definition at line 312 of file graph_template.h.
Referenced by graph_template::add_edge_data_feature(), graph_template::add_edge_truth_feature(), graph_children::CompileEvent(), graph_truthjets::CompileEvent(), graph_truthjets_nonu::CompileEvent(), graph_jets::CompileEvent(), graph_jets_nonu::CompileEvent(), graph_jets_detector_lep::CompileEvent(), and graph_detector::CompileEvent().