AnalysisG: interface.cxx File Reference
interface.cxx File Reference
#include <pyc/pyc.h>
#include <tools/tensor_cast.h>
#include <tools/vector_cast.h>
#include <utils/utils.h>
Functions
std::vector< neutrino * > construct_particle (torch::Tensor *inpt, torch::Tensor *ln, torch::Tensor *bn, std::vector< double > *dst)
Function Documentation
construct_particle()
std::vector<neutrino*> construct_particle (torch::Tensor * inpt, torch::Tensor * ln, torch::Tensor * bn, std::vector< double > * dst)
Definition at line 54 of file interface.cxx.
{
     std::vector<std::vector<double>> pmc;
     std::vector<signed long> s = tensor_size(inpt);
     tensor_to_vector(inpt, &pmc, &s, double(0));
     std::vector<std::vector<long>> _l, _b;
     if (ln){
         s = tensor_size(ln);
         tensor_to_vector(ln, &_l, &s, long(0));
         tensor_to_vector(bn, &_b, &s, long(0));
    }
     size_t o = 0;
     for (size_t x(0); x < dst -> size(); ++x){o += (*dst)[x] != 0;}
     if (!o){return {};}
     std::vector<neutrino*> out(o, nullptr); o = 0;
     for (size_t x(0); x < pmc.size(); ++x){
         if (!(*dst)[x]){continue;}
         neutrino* nx = new neutrino(pmc[x][0], pmc[x][1], pmc[x][2]);
         nx -> min   = (*dst)[x];
         nx -> b_idx = (bn) ? _b[x][0] : x / 6;
         nx -> l_idx = (ln) ? _l[x][0] : x / 6;
         out[o] = nx; ++o;
     }
     return out;
 }
References main::out, pmc, tensor_size(), tensor_to_vector(), and main::x.
Referenced by pyc::nusol::combinatorial(), and pyc::nusol::NuNu().