AnalysisG: merge_cast.h File Reference
merge_cast.h File Reference
#include <string>
#include <vector>
#include <map>
Functions
template<typename G >
void merge_data (std::vector< G > *out, std::vector< G > *p2)
template<typename G >
void merge_data (G *out, G *p2)
template<typename g , typename G >
void merge_data (std::map< g, G > *out, std::map< g, G > *p2)
template<typename G >
void sum_data (G *out, G *p2)
template<typename G >
void sum_data (std::vector< G > *out, std::vector< G > *p2)
template<typename g , typename G >
void sum_data (std::map< g, G > *out, std::map< g, G > *p2)
template<typename g >
void reserve_count (g *inp, long *ix)
template<typename g >
void reserve_count (std::vector< g > *inp, long *ix)
template<typename g >
void contract_data (std::vector< g > *out, g *p2)
template<typename g >
void contract_data (std::vector< g > *out, std::vector< g > *p2)
template<typename g >
void contract_data (std::vector< g > *out, std::vector< std::vector< g >> *p2)
Function Documentation
contract_data() [1/3]
template<typename g > void contract_data (std::vector< g > * out, g * p2)
Definition at line 47 of file merge_cast.h.
 {out -> push_back(*p2);}
References main::out.
Referenced by contract_data().
contract_data() [2/3]
template<typename g > void contract_data (std::vector< g > * out, std::vector< g > * p2)
Definition at line 50 of file merge_cast.h.
{
     for (size_t i(0); i < p2 -> size(); ++i){contract_data(out, &p2 -> at(i));}
 }
References contract_data(), and main::out.
contract_data() [3/3]
template<typename g > void contract_data (std::vector< g > * out, std::vector< std::vector< g >> * p2)
Definition at line 56 of file merge_cast.h.
{
     long ix = 0;
     reserve_count(p2, &ix);
     out -> reserve(ix);
     for (size_t i(0); i < p2 -> size(); ++i){contract_data(out, &p2 -> at(i));}
 }
References contract_data(), main::out, and reserve_count().
merge_data() [1/3]
template<typename G > void merge_data (G * out, G * p2)
Definition at line 14 of file merge_cast.h.
 {(*out) = *p2;}
merge_data() [2/3]
template<typename g , typename G > void merge_data (std::map< g, G > * out, std::map< g, G > * p2)
Definition at line 17 of file merge_cast.h.
{
     typename std::map<g, G>::iterator itr = p2 -> begin();
     for (; itr != p2 -> end(); ++itr){merge_data(&(*out)[itr -> first], &itr -> second);}
 }
References end(), merge_data(), and main::out.
merge_data() [3/3]
template<typename G > void merge_data (std::vector< G > * out, std::vector< G > * p2)
Definition at line 9 of file merge_cast.h.
{
     out -> insert(out -> end(), p2 -> begin(), p2 -> end());
 }
References end(), and main::out.
Referenced by decaymodes::merge(), met::merge(), toptruthjets::merge(), topjets::merge(), parton::merge(), topefficiency::merge(), regions::merge(), combinatorial::merge(), merge_data(), matching::reference(), decaymodes::strategy(), toptruthjets::strategy(), topjets::strategy(), zprime::strategy(), topmatching::strategy(), validation::strategy(), childrenkinematics::strategy(), and combinatorial::strategy().
reserve_count() [1/2]
template<typename g > void reserve_count (g * inp, long * ix)
Definition at line 39 of file merge_cast.h.
 {*ix += 1;}
Referenced by contract_data(), and reserve_count().
reserve_count() [2/2]
template<typename g > void reserve_count (std::vector< g > * inp, long * ix)
Definition at line 42 of file merge_cast.h.
{
     for (size_t x(0); x < inp -> size(); ++x){reserve_count(&inp -> at(x), ix);}
 }
References reserve_count(), and main::x.
sum_data() [1/3]
template<typename G > void sum_data (G * out, G * p2)
Definition at line 24 of file merge_cast.h.
 {(*out) += (*p2);}
Referenced by decaymodes::merge(), topefficiency::merge(), and sum_data().
sum_data() [2/3]
template<typename g , typename G > void sum_data (std::map< g, G > * out, std::map< g, G > * p2)
Definition at line 32 of file merge_cast.h.
{
     typename std::map<g, G>::iterator itr = p2 -> begin();
     for (; itr != p2 -> end(); ++itr){sum_data(&(*out)[itr -> first], &itr -> second);}
 }
References end(), main::out, and sum_data().
sum_data() [3/3]
template<typename G > void sum_data (std::vector< G > * out, std::vector< G > * p2)
Definition at line 27 of file merge_cast.h.
{
     out -> insert(out -> end(), p2 -> begin(), p2 -> end());
 }
References end(), and main::out.