AnalysisG: base.h File Reference
modules/structs/include/structs/base.h File Reference
Defines fundamental data structures and type handling for the AnalysisG framework.
#include <string>
#include <vector>
#include <map>
#include <structs/enums.h>
Classes
class bsc_t
Basic structure class that provides type translation and buffer management.
Macros
#define STRUCTS_BASE_H
< Start of include guard for STRUCTS_BASE_H.
Functions
void buildDict (std::string _name, std::string _shrt)
Builds a dictionary for a specific data type.
void registerInclude (std::string pth, bool is_abs)
Registers an include path with the interpreter.
void buildPCM (std::string name, std::string incl, bool exl)
Builds a Precompiled Module (PCM) file for a specific module.
void buildAll ()
Initiates the build of all dictionaries and PCM files.
int count (const std::string *str, const std::string sub)
Counts occurrences of a substring within a string.
Detailed Description
Defines fundamental data structures and type handling for the AnalysisG framework.
This file contains declarations for basic structures and functions that handle data type identification, conversion, and management across the framework. It provides essential functionality for type safety and data management in a heterogeneous, physics data analysis environment.
Definition in file modules/structs/include/structs/base.h.
Macro Definition Documentation
STRUCTS_BASE_H
#define STRUCTS_BASE_H
< Start of include guard for STRUCTS_BASE_H.
Definition of STRUCTS_BASE_H to signify the header has been included. Include standard string library for string manipulation. Include standard vector container for sequence storage. Include standard map container for key-value associations. Include enumerations used in the framework.
Definition at line 12 of file modules/structs/include/structs/base.h.
Function Documentation
buildAll()
void buildAll ()
Initiates the build of all dictionaries and PCM files.
This function triggers the generation of all necessary dictionaries and PCM files for the types registered in the framework. This is typically called during initialization.
Definition at line 24 of file structs/cxx/base.cxx.
                {
     buildPCM("vector<vector<vector<unsigned long long>>>", "vector", false);
     buildPCM("vector<vector<vector<unsigned int>>>"      , "vector", false);
     buildPCM("vector<vector<vector<double>>>"            , "vector", false);
     buildPCM("vector<vector<vector<long>>>"              , "vector", false);
     buildPCM("vector<vector<vector<float>>>"             , "vector", false);
     buildPCM("vector<vector<vector<int>>>"               , "vector", false);
     buildPCM("vector<vector<vector<bool>>>"              , "vector", false);
     buildPCM("vector<vector<vector<char>>>"              , "vector", false);
     buildPCM("vector<vector<unsigned long long>>"        , "vector", false);
     buildPCM("vector<vector<unsigned int>>"              , "vector", false);
     buildPCM("vector<vector<double>>"                    , "vector", false);
     buildPCM("vector<vector<long>>"                      , "vector", false);
     buildPCM("vector<vector<float>>"                     , "vector", false);
     buildPCM("vector<vector<int>>"                       , "vector", false);
     buildPCM("vector<vector<bool>>"                      , "vector", false);
     buildPCM("vector<vector<char>>"                      , "vector", false);
     buildPCM("vector<unsigned long long>"                , "vector", false);
     buildPCM("vector<unsigned int>"                      , "vector", false);
     buildPCM("vector<double>"                            , "vector", false);
     buildPCM("vector<long>"                              , "vector", false);
     buildPCM("vector<float>"                             , "vector", false);
     buildPCM("vector<int>"                               , "vector", false);
     buildPCM("vector<bool>"                              , "vector", false);
     buildPCM("vector<char>"                              , "vector", false);
     buildPCM("unsigned long long"                        , ""      , true );
     buildPCM("unsigned int"                              , ""      , true );
     buildPCM("double"                                    , ""      , true );
     buildPCM("long"                                      , ""      , true );
     buildPCM("float"                                     , ""      , true );
     buildPCM("int"                                       , ""      , true );
     buildPCM("bool"                                      , ""      , true );
     buildPCM("char"                                      , ""      , true );
 }
References buildPCM().
Referenced by analysis::analysis(), and io::trigger_pcm().
buildDict()
void buildDict (std::string _name, std::string _shrt)
Builds a dictionary for a specific data type.
Parameters
_name Full name of the data type.
_shrt Short alias for the data type.
This function registers a data type with the ROOT dictionary system, enabling serialization and deserialization of custom objects.
Definition at line 5 of file structs/cxx/base.cxx.
{
     std::string name = std::string(_name);
     gInterpreter -> GenerateDictionary(name.c_str(), _shrt.c_str());
 }
References name.
Referenced by analysis::analysis(), buildPCM(), and io::trigger_pcm().
buildPCM()
void buildPCM (std::string name, std::string incl, bool exl)
Builds a Precompiled Module (PCM) file for a specific module.
Parameters
name Name of the module.
incl Include path for the module.
exl Flag indicating if the module should be excluded from certain operations.
This function generates a PCM file which speeds up loading and interpretation of C++ code in the ROOT framework.
Definition at line 17 of file structs/cxx/base.cxx.
{
     if (exl){return;}
     buildDict(name, incl);
 }
References buildDict(), and name.
Referenced by buildAll().
count()
int count (const std::string * str, const std::string sub)
Counts occurrences of a substring within a string.
Parameters
str Pointer to the string to search within.
sub The substring to search for.
Returns
The number of occurrences of the substring.
Definition at line 62 of file structs/cxx/base.cxx.
{
     int count = 0;
     std::string::size_type pos = 0;
     while ((pos = str -> find(sub, pos)) != std::string::npos){++count; ++pos;}
     return count;
 }
References count().
Referenced by plotting::build_ROC(), gnn_event::CompileEvent(), count(), particle_template::get_children(), particle_template::get_parents(), particle_template::particle_template(), write_t::process(), io::root_begin(), bsc_t::root_type_translate(), and io::scan_keys().
registerInclude()
void registerInclude (std::string pth, bool is_abs)
Registers an include path with the interpreter.
Parameters
pth Path to register.
is_abs Flag indicating if the path is absolute (true) or relative (false).
This function adds a directory to the interpreter's include path, allowing it to find header files during runtime compilation.
Definition at line 10 of file structs/cxx/base.cxx.
{
     std::string shrt = "#include ";
     if (is_abs){shrt += " \"" + pth + "\"";}
     else {shrt += "<" + pth + ">";}
     gInterpreter -> ProcessLine(shrt.c_str());
 }
References main::pth.