AnalysisG: test_ssml_mc20 Namespace Reference
test_ssml_mc20 Namespace Reference
Variables
string ttbar = "/home/tnom6927/Downloads/mc20/user.rqian.503575.MGPy8EG.DAOD_PHYS.e8307_s3797_r13167_p6490.2024-11-23_output"
ev = SSML_MC20()
gr = GraphDetector()
md = Grift()
o_edge
o_graph
device
checkpoint_path
ana = Analysis()
BatchSize
GraphCache
Variable Documentation
ana
test_ssml_mc20.ana = Analysis()
Definition at line 34 of file test_ssml_mc20.py.
BatchSize
test_ssml_mc20.BatchSize
Definition at line 53 of file test_ssml_mc20.py.
checkpoint_path
test_ssml_mc20.checkpoint_path
Definition at line 27 of file test_ssml_mc20.py.
device
test_ssml_mc20.device
Definition at line 26 of file test_ssml_mc20.py.
ev
test_ssml_mc20.ev = SSML_MC20()
Definition at line 11 of file test_ssml_mc20.py.
gr
test_ssml_mc20.gr = GraphDetector()
Definition at line 12 of file test_ssml_mc20.py.
GraphCache
test_ssml_mc20.GraphCache
Definition at line 56 of file test_ssml_mc20.py.
md
test_ssml_mc20.md = Grift()
Definition at line 13 of file test_ssml_mc20.py.
Referenced by grift.clone(), model_template.get_dev_index(), model_template.get_name(), model_template.set_device(), and model_template.set_name().
o_edge
test_ssml_mc20.o_edge
Definition at line 14 of file test_ssml_mc20.py.
o_graph
test_ssml_mc20.o_graph
Definition at line 19 of file test_ssml_mc20.py.
ttbar
string test_ssml_mc20.ttbar = "/home/tnom6927/Downloads/mc20/user.rqian.503575.MGPy8EG.DAOD_PHYS.e8307_s3797_r13167_p6490.2024-11-23_output"
Definition at line 9 of file test_ssml_mc20.py.