AnalysisG: transform_ Namespace Reference
transform_ Namespace Reference
< Includes PyTorch C++ headers for tensor operations.
Functions
torch::Tensor Px (torch::Tensor *pt, torch::Tensor *phi)
Computes the x-component of momentum (Px).
torch::Tensor Py (torch::Tensor *pt, torch::Tensor *phi)
Computes the y-component of momentum (Py).
torch::Tensor Pz (torch::Tensor *pt, torch::Tensor *eta)
Computes the z-component of momentum (Pz).
torch::Tensor PxPyPz (torch::Tensor *pt, torch::Tensor *eta, torch::Tensor *phi)
Computes the 3-momentum (Px, Py, Pz).
torch::Tensor PxPyPzE (torch::Tensor *pt, torch::Tensor *eta, torch::Tensor *phi, torch::Tensor *energy)
Computes the 4-momentum (Px, Py, Pz, E).
torch::Tensor PxPyPz (torch::Tensor *pmu)
Computes the 3-momentum (Px, Py, Pz) from a 4-momentum tensor.
torch::Tensor PxPyPzE (torch::Tensor *pmu)
Computes the 4-momentum (Px, Py, Pz, E) from a 4-momentum tensor.
torch::Tensor Pt (torch::Tensor *px, torch::Tensor *py)
Computes the transverse momentum (Pt).
torch::Tensor PtEta (torch::Tensor *pt, torch::Tensor *pz)
Computes the transverse momentum (Pt) and pseudorapidity (Eta).
torch::Tensor Phi (torch::Tensor *pmc)
Computes the azimuthal angle (Phi) from a momentum tensor.
torch::Tensor Phi (torch::Tensor *px, torch::Tensor *py)
Computes the azimuthal angle (Phi) from x and y components of momentum.
torch::Tensor Eta (torch::Tensor *pmc)
Computes the pseudorapidity (Eta) from a momentum tensor.
torch::Tensor Eta (torch::Tensor *px, torch::Tensor *py, torch::Tensor *pz)
Computes the pseudorapidity (Eta) from x, y, and z components of momentum.
torch::Tensor PtEtaPhi (torch::Tensor *pmc)
Computes the transverse momentum (Pt), pseudorapidity (Eta), and azimuthal angle (Phi) from a momentum tensor.
torch::Tensor PtEtaPhiE (torch::Tensor *pmc)
Computes the transverse momentum (Pt), pseudorapidity (Eta), azimuthal angle (Phi), and energy (E) from a momentum tensor.
torch::Tensor PtEtaPhi (torch::Tensor *px, torch::Tensor *py, torch::Tensor *pz)
Computes the transverse momentum (Pt), pseudorapidity (Eta), and azimuthal angle (Phi) from x, y, and z components of momentum.
torch::Tensor PtEtaPhiE (torch::Tensor *px, torch::Tensor *py, torch::Tensor *pz, torch::Tensor *e)
Computes the transverse momentum (Pt), pseudorapidity (Eta), azimuthal angle (Phi), and energy (E) from x, y, z components of momentum and energy.
Detailed Description
< Includes PyTorch C++ headers for tensor operations.
Namespace for transformation functions.
Function Documentation
Eta() [1/2]
torch::Tensor transform_::Eta (torch::Tensor * pmc)
Computes the pseudorapidity (Eta) from a momentum tensor.
Parameters
pmc Input tensor of momentum values.
Returns
A tensor containing the pseudorapidity.
Definition at line 85 of file transform/transform.cxx.
{
     torch::Tensor px = clip(pmc, 0);
     torch::Tensor py = clip(pmc, 1);
     torch::Tensor pz = clip(pmc, 2);
     return transform_::Eta(&px, &py, &pz);
 }
References clip(), and pmc.
Referenced by pyc::transform::separate::Eta(), and pyc::transform::combined::Eta().
Eta() [2/2]
torch::Tensor transform_::Eta (torch::Tensor * px, torch::Tensor * py, torch::Tensor * pz)
Computes the pseudorapidity (Eta) from x, y, and z components of momentum.
Parameters
px Input tensor of x-component of momentum.
py Input tensor of y-component of momentum.
pz Input tensor of z-component of momentum.
Returns
A tensor containing the pseudorapidity.
Definition at line 80 of file transform/transform.cxx.
{
     torch::Tensor pt = transform_::Pt(px, py);
     return transform_::PtEta(&pt, pz);
 }
References Pt(), and PtEta().
Phi() [1/2]
torch::Tensor transform_::Phi (torch::Tensor * pmc)
Computes the azimuthal angle (Phi) from a momentum tensor.
Parameters
pmc Input tensor of momentum values.
Returns
A tensor containing the azimuthal angle.
Definition at line 70 of file transform/transform.cxx.
{
     torch::Tensor px = clip(pmc, 0);
     torch::Tensor py = clip(pmc, 1);
     return transform_::Phi(&px, &py);
 }
References clip(), and pmc.
Referenced by pyc::transform::separate::Phi(), pyc::transform::combined::Phi(), PtEtaPhi(), and Rotation().
Phi() [2/2]
torch::Tensor transform_::Phi (torch::Tensor * px, torch::Tensor * py)
Computes the azimuthal angle (Phi) from x and y components of momentum.
Parameters
px Input tensor of x-component of momentum.
py Input tensor of y-component of momentum.
Returns
A tensor containing the azimuthal angle.
Definition at line 66 of file transform/transform.cxx.
{
     return torch::atan2( *py, *px ).view({-1, 1});
 }
Pt()
torch::Tensor transform_::Pt (torch::Tensor * px, torch::Tensor * py)
Computes the transverse momentum (Pt).
Parameters
px Input tensor of x-component of momentum.
py Input tensor of y-component of momentum.
Returns
A tensor containing the transverse momentum.
Definition at line 62 of file transform/transform.cxx.
{
     return torch::sqrt( px -> pow(2) + py -> pow(2) ).view({-1, 1});
 }
Referenced by Eta(), pyc::transform::separate::Pt(), pyc::transform::combined::Pt(), and PtEtaPhi().
PtEta()
torch::Tensor transform_::PtEta (torch::Tensor * pt, torch::Tensor * pz)
Computes the transverse momentum (Pt) and pseudorapidity (Eta).
Parameters
pt Input tensor of transverse momentum values.
pz Input tensor of z-component of momentum.
Returns
A tensor containing the transverse momentum and pseudorapidity.
Definition at line 76 of file transform/transform.cxx.
{
     return torch::asinh( pz -> view({-1, 1}) / pt -> view({-1, 1}) );
 }
Referenced by Eta(), and PtEtaPhi().
PtEtaPhi() [1/2]
torch::Tensor transform_::PtEtaPhi (torch::Tensor * pmc)
Computes the transverse momentum (Pt), pseudorapidity (Eta), and azimuthal angle (Phi) from a momentum tensor.
Parameters
pmc Input tensor of momentum values.
Returns
A tensor containing Pt, Eta, and Phi.
Definition at line 100 of file transform/transform.cxx.
{
     torch::Tensor px = clip(pmc, 0);
     torch::Tensor py = clip(pmc, 1);
     torch::Tensor pz = clip(pmc, 2);
     if (pmc -> size({-1}) < 4){return transform_::PtEtaPhi(&px, &py, &pz);}
     return torch::cat({transform_::PtEtaPhi(&px, &py, &pz), clip(pmc, 3).view({-1, 1})}, {-1});
 }
References clip(), and pmc.
Referenced by pyc::physics::cartesian::separate::DeltaR(), pyc::physics::cartesian::combined::DeltaR(), pyc::transform::separate::PtEtaPhi(), pyc::transform::combined::PtEtaPhi(), and PtEtaPhiE().
PtEtaPhi() [2/2]
torch::Tensor transform_::PtEtaPhi (torch::Tensor * px, torch::Tensor * py, torch::Tensor * pz)
Computes the transverse momentum (Pt), pseudorapidity (Eta), and azimuthal angle (Phi) from x, y, and z components of momentum.
Parameters
px Input tensor of x-component of momentum.
py Input tensor of y-component of momentum.
pz Input tensor of z-component of momentum.
Returns
A tensor containing Pt, Eta, and Phi.
Definition at line 92 of file transform/transform.cxx.
{
     torch::Tensor _pt  = transform_::Pt(px, py);
     torch::Tensor _eta = transform_::PtEta(&_pt, pz);
     torch::Tensor _phi = transform_::Phi(px, py);
     return torch::cat({_pt, _eta, _phi}, -1);
 }
References Phi(), Pt(), and PtEta().
PtEtaPhiE() [1/2]
torch::Tensor transform_::PtEtaPhiE (torch::Tensor * pmc)
Computes the transverse momentum (Pt), pseudorapidity (Eta), azimuthal angle (Phi), and energy (E) from a momentum tensor.
Parameters
pmc Input tensor of momentum values.
Returns
A tensor containing Pt, Eta, Phi, and E.
Definition at line 112 of file transform/transform.cxx.
{
     return transform_::PtEtaPhi(pmc);
 }
References pmc, and PtEtaPhi().
Referenced by pyc::transform::separate::PtEtaPhiE(), and pyc::transform::combined::PtEtaPhiE().
PtEtaPhiE() [2/2]
torch::Tensor transform_::PtEtaPhiE (torch::Tensor * px, torch::Tensor * py, torch::Tensor * pz, torch::Tensor * e)
Computes the transverse momentum (Pt), pseudorapidity (Eta), azimuthal angle (Phi), and energy (E) from x, y, z components of momentum and energy.
Parameters
px Input tensor of x-component of momentum.
py Input tensor of y-component of momentum.
pz Input tensor of z-component of momentum.
e Input tensor of energy values.
Returns
A tensor containing Pt, Eta, Phi, and E.
Definition at line 108 of file transform/transform.cxx.
{
     return torch::cat({transform_::PtEtaPhi(px, py, pz), e -> view({-1, 1})}, -1);
 }
References test_particles::e, and PtEtaPhi().
Px()
torch::Tensor transform_::Px (torch::Tensor * pt, torch::Tensor * phi)
Computes the x-component of momentum (Px).
Parameters
pt Input tensor of transverse momentum values.
phi Input tensor of azimuthal angle values.
Returns
A tensor containing the x-component of momentum.
Definition at line 17 of file transform/transform.cxx.
{
         return pt -> view({-1, 1}) * torch::cos(phi -> view({-1, 1}));
 }
Referenced by pyc::transform::separate::Px(), pyc::transform::combined::Px(), PxPyPz(), and PxPyPzE().
PxPyPz() [1/2]
torch::Tensor transform_::PxPyPz (torch::Tensor * pmu)
Computes the 3-momentum (Px, Py, Pz) from a 4-momentum tensor.
Parameters
pmu Input tensor of 4-momentum values.
Returns
A tensor containing the 3-momentum.
Definition at line 40 of file transform/transform.cxx.
{
     torch::Tensor pt  = clip(pmu, 0);
     torch::Tensor eta = clip(pmu, 1);
     torch::Tensor phi = clip(pmu, 2);
     if (pmu -> size({-1}) < 4){return transform_::PxPyPz(&pt, &eta, &phi);}
     return torch::cat({transform_::PxPyPz(&pt, &eta, &phi), clip(pmu, 3).view({-1, 1})}, {-1});
 }
References clip(), pmu(), and PxPyPz().
PxPyPz() [2/2]
torch::Tensor transform_::PxPyPz (torch::Tensor * pt, torch::Tensor * eta, torch::Tensor * phi)
Computes the 3-momentum (Px, Py, Pz).
Parameters
pt Input tensor of transverse momentum values.
eta Input tensor of pseudorapidity values.
phi Input tensor of azimuthal angle values.
Returns
A tensor containing the 3-momentum.
Definition at line 29 of file transform/transform.cxx.
{
     torch::Tensor _px = transform_::Px(pt, phi);
     torch::Tensor _py = transform_::Py(pt, phi);
     torch::Tensor _pz = transform_::Pz(pt, eta);
     return torch::cat({_px, _py, _pz}, -1);
 }
References Px(), Py(), and Pz().
Referenced by pyc::physics::polar::separate::P(), pyc::physics::polar::combined::P(), pyc::physics::polar::separate::P2(), pyc::physics::polar::combined::P2(), pyc::transform::separate::PxPyPz(), pyc::transform::combined::PxPyPz(), PxPyPz(), PxPyPzE(), pyc::physics::polar::separate::Theta(), and pyc::physics::polar::combined::Theta().
PxPyPzE() [1/2]
torch::Tensor transform_::PxPyPzE (torch::Tensor * pmu)
Computes the 4-momentum (Px, Py, Pz, E) from a 4-momentum tensor.
Parameters
pmu Input tensor of 4-momentum values.
Returns
A tensor containing the 4-momentum.
Definition at line 48 of file transform/transform.cxx.
{
     torch::Tensor pt  = clip(pmu, 0).view({-1, 1});
     torch::Tensor eta = clip(pmu, 1).view({-1, 1});
     torch::Tensor phi = clip(pmu, 2).view({-1, 1});
     torch::Tensor e   = clip(pmu, 3).view({-1, 1});
     torch::Tensor _px = transform_::Px(&pt, &phi);
     torch::Tensor _py = transform_::Py(&pt, &phi);
     torch::Tensor _pz = transform_::Pz(&pt, &eta);
     return torch::cat({_px, _py, _pz, e}, -1);
 }
References clip(), test_particles::e, pmu(), Px(), Py(), and Pz().
PxPyPzE() [2/2]
torch::Tensor transform_::PxPyPzE (torch::Tensor * pt, torch::Tensor * eta, torch::Tensor * phi, torch::Tensor * energy)
Computes the 4-momentum (Px, Py, Pz, E).
Parameters
pt Input tensor of transverse momentum values.
eta Input tensor of pseudorapidity values.
phi Input tensor of azimuthal angle values.
energy Input tensor of energy values.
Returns
A tensor containing the 4-momentum.
Definition at line 36 of file transform/transform.cxx.
{
     return torch::cat({transform_::PxPyPz(pt, eta, phi), e -> view({-1, 1})}, -1);
 }
References test_particles::e, and PxPyPz().
Referenced by pyc::physics::polar::separate::Beta(), pyc::physics::polar::combined::Beta(), pyc::physics::polar::separate::Beta2(), pyc::physics::polar::combined::Beta2(), pyc::graph::polar::edge_aggregation(), pyc::physics::polar::separate::M(), pyc::physics::polar::combined::M(), pyc::physics::polar::separate::M2(), pyc::physics::polar::combined::M2(), pyc::physics::polar::combined::Mt(), pyc::physics::polar::combined::Mt2(), pyc::graph::polar::node_aggregation(), pyc::transform::separate::PxPyPzE(), and pyc::transform::combined::PxPyPzE().
Py()
torch::Tensor transform_::Py (torch::Tensor * pt, torch::Tensor * phi)
Computes the y-component of momentum (Py).
Parameters
pt Input tensor of transverse momentum values.
phi Input tensor of azimuthal angle values.
Returns
A tensor containing the y-component of momentum.
Definition at line 21 of file transform/transform.cxx.
{
     return pt -> view({-1, 1}) * torch::sin(phi -> view({-1, 1}));
 }
Referenced by PxPyPz(), PxPyPzE(), pyc::transform::separate::Py(), and pyc::transform::combined::Py().
Pz()
torch::Tensor transform_::Pz (torch::Tensor * pt, torch::Tensor * eta)
Computes the z-component of momentum (Pz).
Parameters
pt Input tensor of transverse momentum values.
eta Input tensor of pseudorapidity values.
Returns
A tensor containing the z-component of momentum.
Definition at line 25 of file transform/transform.cxx.
{
     return pt -> view({-1, 1}) * torch::sinh(eta -> view({-1, 1}));
 }
Referenced by pyc::physics::polar::separate::Mt(), pyc::physics::polar::separate::Mt2(), PxPyPz(), PxPyPzE(), pyc::transform::separate::Pz(), and pyc::transform::combined::Pz().