AnalysisG: pyc::transform::combined Namespace Reference
pyc::transform::combined Namespace Reference
Functions
torch::Tensor Pt (torch::Tensor pmc)
torch::Tensor Eta (torch::Tensor pmc)
torch::Tensor Phi (torch::Tensor pmc)
torch::Tensor PtEtaPhi (torch::Tensor pmc)
torch::Tensor PtEtaPhiE (torch::Tensor pmc)
torch::Tensor Px (torch::Tensor pmu)
torch::Tensor Py (torch::Tensor pmu)
torch::Tensor Pz (torch::Tensor pmu)
torch::Tensor PxPyPz (torch::Tensor pmu)
torch::Tensor PxPyPzE (torch::Tensor pmu)
Function Documentation
Eta()
torch::Tensor pyc::transform::combined::Eta (torch::Tensor pmc)
Definition at line 28 of file interface/transform.cxx.
{
     changedev(&pmc);
     return transform_::Eta(&pmc);
 }
References changedev(), transform_::Eta(), and pmc.
Phi()
torch::Tensor pyc::transform::combined::Phi (torch::Tensor pmc)
Definition at line 38 of file interface/transform.cxx.
{
     torch::Tensor px = pmc.index({torch::indexing::Slice(), 0});
     torch::Tensor py = pmc.index({torch::indexing::Slice(), 1});
     changedev(&px);
     return transform_::Phi(&px, &py);
 }
References changedev(), transform_::Phi(), and pmc.
Referenced by pyc::operators::RT().
Pt()
torch::Tensor pyc::transform::combined::Pt (torch::Tensor pmc)
Definition at line 16 of file interface/transform.cxx.
{
     changedev(&pmc);
     torch::Tensor px = pmc.index({torch::indexing::Slice(), 0});
     torch::Tensor py = pmc.index({torch::indexing::Slice(), 1});
     return transform_::Pt(&px, &py);
 }
References changedev(), pmc, and transform_::Pt().
PtEtaPhi()
torch::Tensor pyc::transform::combined::PtEtaPhi (torch::Tensor pmc)
Definition at line 50 of file interface/transform.cxx.
{
     changedev(&pmc);
     return transform_::PtEtaPhi(&pmc);
 }
References changedev(), pmc, and transform_::PtEtaPhi().
PtEtaPhiE()
torch::Tensor pyc::transform::combined::PtEtaPhiE (torch::Tensor pmc)
Definition at line 60 of file interface/transform.cxx.
{
     changedev(&pmc);
     return transform_::PtEtaPhiE(&pmc);
 }
References changedev(), pmc, and transform_::PtEtaPhiE().
Px()
torch::Tensor pyc::transform::combined::Px (torch::Tensor pmu)
Definition at line 70 of file interface/transform.cxx.
{
     changedev(&pmu);
     torch::Tensor pt = pmu.index({torch::indexing::Slice(), 0});
     torch::Tensor phi = pmu.index({torch::indexing::Slice(), 2});
     return transform_::Px(&pt, &phi);
 }
References changedev(), pmu(), and transform_::Px().
PxPyPz()
torch::Tensor pyc::transform::combined::PxPyPz (torch::Tensor pmu)
Definition at line 106 of file interface/transform.cxx.
{
     changedev(&pmu);
     return transform_::PxPyPz(&pmu);
 }
References changedev(), pmu(), and transform_::PxPyPz().
PxPyPzE()
torch::Tensor pyc::transform::combined::PxPyPzE (torch::Tensor pmu)
Definition at line 116 of file interface/transform.cxx.
{
     changedev(&pmu);
     return transform_::PxPyPzE(&pmu);
 }
References changedev(), pmu(), and transform_::PxPyPzE().
Py()
torch::Tensor pyc::transform::combined::Py (torch::Tensor pmu)
Definition at line 82 of file interface/transform.cxx.
{
     changedev(&pmu);
     torch::Tensor pt = pmu.index({torch::indexing::Slice(), 0});
     torch::Tensor phi = pmu.index({torch::indexing::Slice(), 2});
     return transform_::Py(&pt, &phi);
 }
References changedev(), pmu(), and transform_::Py().
Pz()
torch::Tensor pyc::transform::combined::Pz (torch::Tensor pmu)
Definition at line 94 of file interface/transform.cxx.
{
     changedev(&pmu);
     torch::Tensor pt  = pmu.index({torch::indexing::Slice(), 0});
     torch::Tensor eta = pmu.index({torch::indexing::Slice(), 1});
     return transform_::Pz(&pt, &eta);
 }
References changedev(), pmu(), and transform_::Pz().