AnalysisG: figures Namespace Reference
figures Namespace Reference
Functions
def template_hist (title, weights, data, bins, xmax, xtitle, xmin=None, xstep=None, fname=None)
def GetValues (sel, key)
def CRttbarCO2l_CO (sel)
def CRttbarCO2l_CO_2b (sel)
def CRttbarCO2l_gstr (sel)
def CRttbarCO2l_gstr_2b (sel)
def CR1b3lem (sel)
def CR1b3le (sel)
def CR1b3lm (sel)
def CRttW2l_plus (sel)
def CRttW2l_minus (sel)
def CR1bplus (sel)
def CR1bminus (sel)
def CRttW2l (sel)
def VRttZ3l (sel)
def VRttWCRSR (sel)
def SR4b (sel)
def SR2b (sel)
def SR3b (sel)
def SR2b2l (sel)
def SR2b3l4l (sel)
def SR2b4l (sel)
def SR3b2l (sel)
def SR3b3l4l (sel)
def SR3b4l (sel)
def SR4b4l (sel)
def SR (sel)
def entry (sel)
def colr (dev)
def fancy (dev)
def fancy_title (key)
def fancy_modes ()
def fnames (key)
def xdata (data, mode)
def ydata (data, mode)
def edata (data, mode)
def template_line (title, data, mode, linst="-", misc=None)
def template_Tline (ytitle, opx, fname, lines)
def build_operators (pkt)
def build_neutrino (pkt)
def build_physics (pkt, frame)
def build_transform (pkt)
def entry (pkt, devices)
def null_cut (p, m, pdg, is_l, nj)
def enforce_sym (p, m, pgd, is_l, nj)
def enforce_sym_tj (p, m, pgd, is_l, nj)
def enforce_sym_jet (p, m, pgd, is_l, nj)
def Tabular (topx, target, title, mode, rec=None)
def TabularFlow (topx, stat, title, mode, min_, max_)
def entry_point (fancy, mode, pth, tree, plt=False)
def statistics (data, eps=None)
def colors ()
def print_statistics (data)
def Fancy (tl)
def default (hist, pth)
def template (xdata, title, color=None, pth=None, params={})
def KSTestingDynamic (data)
def Chi2Distribution (data)
def EllipseDistance (data)
def Chi2Symbolic (data)
def METError (data)
def path (hist)
def revert_mapping (data)
def entry (ttbar, tttt, meta)
Variables
list typx = ["topchildren", "truthjet", "jetchildren", "jetleptons"]
Function Documentation
build_neutrino()
def figures.build_neutrino (pkt)
Definition at line 133 of file benchmarks/figures.py.
 def build_neutrino(pkt):
     modx = fancy_modes()
     for opx in pkt:
         for md in modx:
             lines = {}
             for dev in pkt[opx]: lines[dev] = template_line(dev, pkt[opx][dev], md)
             tl = template_Tline(modx[md], opx, fnames(md), list(lines.values()))
             tl.Title = fancy_title(opx)
             tl.SaveFigure()
References fancy_modes(), fancy_title(), fnames(), template_line(), and template_Tline().
Referenced by entry().
build_operators()
def figures.build_operators (pkt)
Definition at line 122 of file benchmarks/figures.py.
 def build_operators(pkt):
     modx = fancy_modes()
     for opx in pkt:
         for md in modx:
             lines = {}
             for dev in pkt[opx]: lines[dev] = template_line(dev, pkt[opx][dev], md)
             tl = template_Tline(modx[md], opx, fnames(md), list(lines.values()))
             if opx == "eigenvalue": tl.xMax = 600; tl.yLogarithmic = False
             tl.Title = fancy_title(opx)
             tl.SaveFigure()
References fancy_modes(), fancy_title(), fnames(), template_line(), and template_Tline().
Referenced by entry().
build_physics()
def figures.build_physics (pkt, frame)
Definition at line 143 of file benchmarks/figures.py.
 def build_physics(pkt, frame):
     modx = fancy_modes()
     for opx in pkt:
         for md in modx:
             lines = []
             for tnx in pkt[opx]:
                 hx = "solid" if tnx == "separate" else "dotted"
                 rn = "Separate" if tnx == "separate" else "Combined"
                 for dev in pkt[opx][tnx]: lines.append(template_line(dev, pkt[opx][tnx][dev], md, hx, rn))
             tl = template_Tline(modx[md], opx, fnames(md) + "_" + frame.lower(), lines)
             tl.Title = fancy_title(opx) + " (From " + frame + ")"
             tl.SaveFigure()
References fancy_modes(), fancy_title(), fnames(), template_line(), and template_Tline().
Referenced by entry().
build_transform()
def figures.build_transform (pkt)
Definition at line 156 of file benchmarks/figures.py.
 def build_transform(pkt):
     modx = fancy_modes()
     for opx in pkt:
         for md in modx:
             lines = []
             for tnx in pkt[opx]:
                 hx = "solid" if tnx == "separate" else "dotted"
                 rn = "Separate" if tnx == "separate" else "Combined"
                 for dev in pkt[opx][tnx]: lines.append(template_line(dev, pkt[opx][tnx][dev], md, hx, rn))
             tl = template_Tline(modx[md], opx, fnames(md), lines)
             tl.Title = fancy_title(opx)
             tl.SaveFigure()
References fancy_modes(), fancy_title(), fnames(), template_line(), and template_Tline().
Referenced by entry().
Chi2Distribution()
def figures.Chi2Distribution (data)
Definition at line 130 of file neutrino/figures.py.
 def Chi2Distribution(data):
     para = {
         "xTitle" : "Kinematic Error for Reconstructed Neutrino ($\\chi^2$) (Arb.)",
         "yTitle" : "Density (Arb.) / <units>",
         "Alpha" : 0.25,
         "xMax"   : 4000, "xMin": 0, "xStep" : 400, "xBins" : 200,
         "Density" : False,
     }
     out = {"chi2" : {}}
     for i in data:
         cu_dnu, cu_snu = data[i].cuda_dnu, data[i].cuda_snu
         rf_dnu, rf_snu = data[i].ref_dnu , data[i].ref_snu
         thc_dnu = template(cu_dnu.chi2_nu1, Fancy("cuda_dnu") , "red" , None, {"Density" : True})
         thr_dnu = template(rf_dnu.chi2_nu1, Fancy("ref_dnu")  , "blue", None, {"Density" : True})
         thc_snu = template(cu_snu.chi2_nu1, Fancy("cuda_snu") , "red" , None, {"Hatch" : "////\\\\\\\\", "Density" : True, "Alpha" : 0.75})
         thr_snu = template(rf_snu.chi2_nu1, Fancy("ref_snu")  , "blue", None, {"Hatch" : "////\\\\\\\\", "Density" : True, "Alpha" : 0.75})
         th = template(None, "$\\chi^2$ Kinematic Error for $\\nu_{1}$ " + Fancy(i), None, "chi2/" + i, para)
         th.Histograms = [thc_dnu, thr_dnu, thc_snu, thr_snu]
         th.Filename = "neutrino_1"
         th.SaveFigure()
         thc_dnu = template(cu_dnu.chi2_nu2, Fancy("cuda_dnu") , "red" , None, {"Density" : True})
         thr_dnu = template(rf_dnu.chi2_nu2, Fancy("ref_dnu")  , "blue", None, {"Density" : True})
         thc_snu = template(cu_snu.chi2_nu2, Fancy("cuda_snu") , "red" , None, {"Hatch" : "////\\\\\\\\", "Density" : True, "Alpha" : 0.75})
         thr_snu = template(rf_snu.chi2_nu2, Fancy("ref_snu")  , "blue", None, {"Hatch" : "////\\\\\\\\", "Density" : True, "Alpha" : 0.75})
         th = template(None, "$\\chi^2$ Kinematic Error for $\\nu_{2}$ " + Fancy(i), None, "chi2/" + i, para)
         th.Histograms = [thc_dnu, thr_dnu, thc_snu, thr_snu]
         th.Filename = "neutrino_2"
         th.SaveFigure()
     return out
References Fancy(), and template().
Referenced by METError().
Chi2Symbolic()
def figures.Chi2Symbolic (data)
Definition at line 267 of file neutrino/figures.py.
 def Chi2Symbolic(data):
     para = {
         "xTitle" : "Kinematic Error for Reconstructed Neutrino ($\\chi^2$) (Arb.)",
         "yTitle" : "Density (Arb.) / <units>",
         "Alpha" : 0.25,
         "xMax"   : 4000, "xMin": 0, "xStep" : 400, "xBins" : 200,
         "Density" : True,
     }
     for i in data:
         cu_dnu, cu_snu = data[i].cuda_dnu, data[i].cuda_snu
         rf_dnu, rf_snu = data[i].ref_dnu , data[i].ref_snu
         th = template(None, "$\\chi^2$ Kinematic Error by Symbolics" + Fancy(i), None, "chi2/" + i, para | {"Stacked" : True})
         hists = []
         col = colors()
         lx = list(cu_dnu.symbols)
         for k in sorted(lx):
             ch = cu_dnu.symbols[k].chi2_nu1 + cu_dnu.symbols[k].chi2_nu2
             hists.append(template(ch, "$" + k + "$", next(col)))
         th.Histograms = hists
         th.Filename = "neutrino-cuda-symbolic"
         th.SaveFigure()
     para = {
         "xTitle" : "Ellipse Distance (Arb.)",
         "yTitle" : "Density (Arb.) / <units>",
         "Alpha" : 0.25,
         "xMax"   : 5, "xMin": -50, "xStep" : 5.0, "xBins" : 100,
     }
     title = "Distances of Elliptical Intersection by Symbolics"
     for i in data:
         cu_dnu, cu_snu = data[i].cuda_dnu, data[i].cuda_snu
         rf_dnu, rf_snu = data[i].ref_dnu , data[i].ref_snu
         th = template(None, title + Fancy(i), None, "ellipse/" + i, para | {"Stacked" : True, "Density" : True})
         hists = []
         col = colors()
         lx = list(cu_dnu.symbols)
         for k in sorted(lx):
             ch = cu_dnu.symbols[k].distances + cu_dnu.symbols[k].distances
             hists.append(template(ch, "$" + k + "$", next(col)))
         th.Histograms = hists
         th.Filename = "neutrino-cuda-symbolic"
         th.SaveFigure()
References colors(), Fancy(), and template().
Referenced by METError().
colors()
def figures.colors ()
Definition at line 14 of file neutrino/figures.py.
 def colors():
     return iter(sorted(list(set([
         "aqua", "orange", "green","blue","olive","teal","gold",
         "darkblue","azure","lime","crimson","cyan","magenta","orchid",
         "sienna","silver","salmon","chocolate", "navy", "plum", "indigo",
         "lightblue", "lavender", "ivory"
     ]))))
Referenced by Chi2Symbolic().
colr()
def figures.colr (dev)
Definition at line 4 of file benchmarks/figures.py.
 def colr(dev):
     cols = {"a100" : "red", "h100" : "blue", "v100" : "green", "a30" : "orange"}
     return cols[dev]
Referenced by template_line().
CR1b3le()
def figures.CR1b3le (sel)
Definition at line 52 of file analysis/figures.py.
 def CR1b3le(sel):
     w, v1, v2 = GetValues(sel, "CR1b3le")
     th = template_hist("CR1b3le", w, v1, [0.0, 15.0, 30.0, 50.0], 50, "lep2_pt")
     th.SaveFigure()
References GetValues(), and template_hist().
Referenced by regions.merge().
CR1b3lem()
def figures.CR1b3lem (sel)
Definition at line 47 of file analysis/figures.py.
 def CR1b3lem(sel):
     w, v1, v2 = GetValues(sel, "CR1b3lem")
     th = template_hist("CR1b3lem", w, v1, [0.0, 15.0, 30.0, 50.0], 50, "lep2_pt")
     th.SaveFigure()
References GetValues(), and template_hist().
Referenced by regions.merge().
CR1b3lm()
def figures.CR1b3lm (sel)
Definition at line 57 of file analysis/figures.py.
 def CR1b3lm(sel):
     w, v1, v2 = GetValues(sel, "CR1b3lm")
     th = template_hist("CR1b3lm", w, v1, [0.0, 15.0, 30.0, 50.0], 50, "lep2_pt")
     th.SaveFigure()
References GetValues(), and template_hist().
Referenced by regions.merge().
CR1bminus()
def figures.CR1bminus (sel)
Definition at line 77 of file analysis/figures.py.
 def CR1bminus(sel):
     w, v1, v2 = GetValues(sel, "CR1bminus")
     th = template_hist("CR1bminus", w, v1, 11, 11, "nJets", 0, 1)
     th.SaveFigure()
References GetValues(), and template_hist().
Referenced by regions.merge().
CR1bplus()
def figures.CR1bplus (sel)
Definition at line 72 of file analysis/figures.py.
 def CR1bplus(sel):
     w, v1, v2 = GetValues(sel, "CR1bplus")
     th = template_hist("CR1bplus", w, v1, 11, 11, "nJets", 0, 1)
     th.SaveFigure()
References GetValues(), and template_hist().
Referenced by regions.merge().
CRttbarCO2l_CO()
def figures.CRttbarCO2l_CO (sel)
Definition at line 27 of file analysis/figures.py.
 def CRttbarCO2l_CO(sel):
     w, v1, v2 = GetValues(sel, "CRttbarCO2l_CO")
     th = template_hist("CRttbarCO2l_CO", w, v1, [0, 1, 2], 2, "passed")
     th.SaveFigure()
References GetValues(), and template_hist().
Referenced by regions.merge().
CRttbarCO2l_CO_2b()
def figures.CRttbarCO2l_CO_2b (sel)
Definition at line 32 of file analysis/figures.py.
 def CRttbarCO2l_CO_2b(sel):
     w, v1, v2 = GetValues(sel, "CRttbarCO2l_CO_2b")
     th = template_hist("CRttbarCO2l_CO_2b", w, v1, [0, 1, 2], 2, "passed")
     th.SaveFigure()
References GetValues(), and template_hist().
Referenced by regions.merge().
CRttbarCO2l_gstr()
def figures.CRttbarCO2l_gstr (sel)
Definition at line 37 of file analysis/figures.py.
 def CRttbarCO2l_gstr(sel):
     w, v1, v2 = GetValues(sel, "CRttbarCO2l_gstr")
     th = template_hist("CRttbarCO2l_gstr", w, v1, [0, 1, 2], 2, "passed")
     th.SaveFigure()
References GetValues(), and template_hist().
Referenced by regions.merge().
CRttbarCO2l_gstr_2b()
def figures.CRttbarCO2l_gstr_2b (sel)
Definition at line 42 of file analysis/figures.py.
 def CRttbarCO2l_gstr_2b(sel):
     w, v1, v2 = GetValues(sel, "CRttbarCO2l_gstr_2b")
     th = template_hist("CRttbarCO2l_gstr_2b", w, v1, [0, 1, 2], 2, "passed")
     th.SaveFigure()
References GetValues(), and template_hist().
Referenced by regions.merge().
CRttW2l()
def figures.CRttW2l (sel)
Definition at line 82 of file analysis/figures.py.
 def CRttW2l(sel):
     w, v1, v2 = GetValues(sel, "CRttW2l")
     th = template_hist("CRttW2l", w, v1, [70, 80, 100, 120, 140, 160, 180, 240, 300], 300.0, "lep_sum_pt", 70, 20)
     th.SaveFigure()
References GetValues(), and template_hist().
Referenced by entry(), and regions.merge().
CRttW2l_minus()
def figures.CRttW2l_minus (sel)
Definition at line 67 of file analysis/figures.py.
 def CRttW2l_minus(sel):
     w, v1, v2 = GetValues(sel, "CRttW2l_minus")
     th = template_hist("CRttW2l_minus", w, v1, 7, 7, "nJets", 0, 1)
     th.SaveFigure()
References GetValues(), and template_hist().
Referenced by regions.merge().
CRttW2l_plus()
def figures.CRttW2l_plus (sel)
Definition at line 62 of file analysis/figures.py.
 def CRttW2l_plus(sel):
     w, v1, v2 = GetValues(sel, "CRttW2l_plus")
     th = template_hist("CRttW2l_plus", w, v1, 7, 7, "nJets", 0, 1)
     th.SaveFigure()
References GetValues(), and template_hist().
Referenced by regions.merge().
default()
def figures.default (hist, pth)
Definition at line 42 of file neutrino/figures.py.
 def default(hist, pth):
     hist.Style = "ATLAS"
     if pth is not None: hist.OutputDirectory = "figures/" + pth
     hist.DPI = 300
     hist.TitleSize = 15
     hist.AutoScaling = True
     hist.Overflow = False
     hist.yScaling = 5 #10*0.75
     hist.xScaling = 5 #15*0.6
     hist.FontSize = 10
     hist.AxisSize = 10
     hist.LegendSize = 10
     return hist
Referenced by EllipseDistance(), METError(), and template().
edata()
def figures.edata (data, mode)
Definition at line 68 of file benchmarks/figures.py.
 def edata(data, mode): return [getattr(i, mode).sig * (1. / (10000.-1.)**0.5) for i in data][1:]
Referenced by template_line().
EllipseDistance()
def figures.EllipseDistance (data)
Definition at line 165 of file neutrino/figures.py.
 def EllipseDistance(data):
     import math
     para = {
         "xTitle" : "Ellipse Distance (Arb.)",
         "yTitle" : "Density (Arb.) / <units>",
         "Alpha" : 0.25,
         "xMax"   : 5, "xMin": -50, "xStep" : 5.0, "xBins" : 100,
     }
     title = "Distances of Elliptical Intersection"
     for i in data:
         cu_dnu, cu_snu = data[i].cuda_dnu, data[i].cuda_snu
         rf_dnu, rf_snu = data[i].ref_dnu , data[i].ref_snu
         thc_dnu = template(cu_dnu.distances, Fancy("cuda_dnu") , "red" , None, {"Density" : True})
         thr_dnu = template([math.log10(k if k > 0 else 1) for k in rf_dnu.distances], Fancy("ref_dnu")  , "blue", None, {"Density" : True})
         thc_snu = template(cu_snu.distances, Fancy("cuda_snu") , "red" , None, {"Hatch" : "////\\\\\\\\", "Density" : True})
         thr_snu = template([math.log10(k if k > 0 else 1) for k in rf_snu.distances], Fancy("ref_snu")  , "blue", None, {"Hatch" : "////\\\\\\\\", "Density" : True})
         th = template(None, title + Fancy(i), None, "ellipse/" + i, para)
         th.Histograms = [thc_snu, thr_snu, thc_dnu, thr_dnu]
         th.Filename = "distances"
         th.SaveFigure()
         xh = default(TH2F(), "ellipse/" + i)
         xh.Title = "$\\chi^2$ Elliptical Distance Dependency" + Fancy("cuda_dnu")
         xh.xData = cu_dnu.distances + cu_dnu.distances
         xh.xBins = 100
         xh.xMin  = -50
         xh.xMax  = 5.0
         xh.xStep = 5.0
         xh.xTitle = "Ellipse Distance (Arb.)"
         xh.yData = cu_dnu.chi2_nu1 + cu_dnu.chi2_nu2
         xh.yBins = 100
         xh.yMin  = 0
         xh.yMax  = 4000
         xh.yStep = 400
         xh.yTitle = "Kinematic Error for Reconstructed Neutrino ($\\chi^2$) (Arb.)"
         xh.Filename = "correlation-cuda-dynamic"
         xh.SaveFigure()
         xh = default(TH2F(), "ellipse/" + i)
         xh.Title = "$\\chi^2$ Elliptical Distance Dependency" + Fancy("cuda_snu")
         xh.xData = cu_snu.distances + cu_snu.distances
         xh.xBins = 100
         xh.xMin  = -50
         xh.xMax  = 5.0
         xh.xStep = 5.0
         xh.xTitle = "Ellipse Distance (Arb.)"
         xh.yData = cu_snu.chi2_nu1 + cu_snu.chi2_nu2
         xh.yBins = 100
         xh.yMin  = 0
         xh.yMax  = 4000
         xh.yStep = 400
         xh.yTitle = "Kinematic Error for Reconstructed Neutrino ($\\chi^2$) (Arb.)"
         xh.Filename = "correlation-cuda-static"
         xh.SaveFigure()
         xh = default(TH2F(), "ellipse/" + i)
         xh.Title = "$\\chi^2$ Elliptical Distance Dependency" + Fancy("ref_dnu")
         xh.xData = [math.log10(k if k > 0 else 1) for k in list(rf_dnu.distances + rf_dnu.distances)]
         xh.xBins = 100
         xh.xMin  = -50
         xh.xMax  = 5.0
         xh.xStep = 5.0
         xh.xTitle = "Ellipse Distance (Arb.)"
         xh.yData = rf_dnu.chi2_nu1 + rf_dnu.chi2_nu2
         xh.yBins = 100
         xh.yMin  = 0
         xh.yMax  = 4000
         xh.yStep = 400
         xh.yTitle = "Kinematic Error for Reconstructed Neutrino ($\\chi^2$) (Arb.)"
         xh.Filename = "correlation-reference-dynamic"
         xh.SaveFigure()
         xh = default(TH2F(), "ellipse/" + i)
         xh.Title = "$\\chi^2$ Elliptical Distance Dependency" + Fancy("ref_snu")
         xh.xData = [math.log10(k if k > 0 else 1) for k in list(rf_snu.distances + rf_snu.distances)]
         xh.xBins = 100
         xh.xMin  = -50
         xh.xMax  = 5.0
         xh.xStep = 5.0
         xh.xTitle = "Ellipse Distance (Arb.)"
         xh.yData = rf_snu.chi2_nu1 + rf_snu.chi2_nu2
         xh.yBins = 100
         xh.yMin  = 0
         xh.yMax  = 4000
         xh.yStep = 400
         xh.yTitle = "Kinematic Error for Reconstructed Neutrino ($\\chi^2$) (Arb.)"
         xh.Filename = "correlation-reference-static"
         xh.SaveFigure()
References default(), Fancy(), and template().
Referenced by METError().
enforce_sym()
def figures.enforce_sym (p, m, pgd, is_l, nj)
Definition at line 7 of file mc20_experimental/figures.py.
 def enforce_sym(p, m, pgd, is_l, nj):
     if "gamma" in p: return False
     return True
enforce_sym_jet()
def figures.enforce_sym_jet (p, m, pgd, is_l, nj)
Definition at line 28 of file mc20_experimental/figures.py.
 def enforce_sym_jet(p, m, pgd, is_l, nj):
     return nj == 1 if is_l else nj == 3
enforce_sym_tj()
def figures.enforce_sym_tj (p, m, pgd, is_l, nj)
Definition at line 11 of file mc20_experimental/figures.py.
 def enforce_sym_tj(p, m, pgd, is_l, nj):
     absx = [abs(i) for i in pgd]
     if len(absx) <= 2: return False
     #if is_l and "o" in p: return False
     #if is_l and absx.count(22) > 1: return False
     #if is_l and "nu" in p and "2" in p: return False
     #if not is_l and absx.count(22) > 3: return False
     #if not is_l and absx.count(11): return False
     #if not is_l and absx.count(12): return False
     #if not is_l and absx.count(13): return False
     #if not is_l and absx.count(14): return False
     #if not is_l and absx.count(15): return False
     #if not is_l and absx.count(16): return False
     #if not is_l and len([i for i in set(absx) if i < 23]) < 2: return False
 #    if not is_l: print(pgd)
     return True
entry() [1/3]
def figures.entry (pkt, devices)
Definition at line 169 of file benchmarks/figures.py.
 def entry(pkt, devices):
     for i in pkt:
         if i == "operators"          : build_operators(pkt[i]); continue
         if i == "neutrino"           : build_neutrino(pkt[i]);  continue
         if i == "physics-polar"      : build_physics(pkt[i], "Polar");   continue
         if i == "physics-cartesian"  : build_physics(pkt[i], "Cartesian");   continue
         if i == "transform-polar"    : build_transform(pkt[i]); continue
         if i == "transform-cartesian": build_transform(pkt[i]); continue
References build_neutrino(), build_operators(), build_physics(), build_transform(), and entry().
entry() [2/3]
def figures.entry (sel = None)
Definition at line 126 of file analysis/figures.py.
 def entry(sel):
 #    CRttbarCO2l_CO(sel)
 #    CRttbarCO2l_CO_2b(sel)
 #    CRttbarCO2l_gstr(sel)
 #    CRttbarCO2l_gstr_2b(sel)
 #    CR1b3lem(sel)
 #    CR1b3le(sel)
 #    CR1b3lm(sel)
 #    CRttW2l_plus(sel)
 #    CRttW2l_minus(sel)
 #    CR1bplus(sel)
 #    CR1bminus(sel)
     CRttW2l(sel)
     VRttZ3l(sel)
     VRttWCRSR(sel)
     SR4b(sel)
     SR2b(sel)
     SR3b(sel)
     SR2b2l(sel)
     SR2b3l4l(sel)
     SR2b4l(sel)
     SR3b2l(sel)
     SR3b3l4l(sel)
     SR3b4l(sel)
     SR4b4l(sel)
     SR(sel)
References CRttW2l(), SR(), SR2b(), SR2b2l(), SR2b3l4l(), SR2b4l(), SR3b(), SR3b2l(), SR3b3l4l(), SR3b4l(), SR4b(), SR4b4l(), VRttWCRSR(), and VRttZ3l().
Referenced by entry(), entry_point(), and METError().
entry() [3/3]
def figures.entry (ttbar, tttt, meta)
Definition at line 34 of file topreconstruction/figures.py.
 def entry(ttbar, tttt, meta):
     tttt_score, tttt_mass = revert_mapping(tttt)
     ttbar_score, ttbar_mass = revert_mapping(ttbar)
     th2t = TH1F()
     th2t.Color = "red"
     th2t.Density = True
     th2t.ErrorBars = True
     th2t.xData = [i for i in sum(ttbar_score.values(), []) if i < 0.99]
     th2t.Title = r'$\bar{t}t$'
     th4t = TH1F()
     th4t.Color = "blue"
     th4t.Density = True
     th4t.ErrorBars = True
     th4t.xData = [i for i in sum(tttt_score.values(), []) if i < 0.99]
     th4t.Title = r'$\bar{t}t\bar{t}t$'
     thpx = TH1F()
     thpx.Histograms = [th2t, th4t]
     #thpx.Density = True
     thpx.Title = "Page Rank Scores of Reconstructed Top Candidates"
     thpx.xTitle = "Page Rank Score of Candidate Tops (Arb.)"
     thpx.yTitle = "Normalized by the number of Top Candidates (Arb.)"
     thpx.xMin = 0
     thpx.xMax = 1.01
     thpx.xBins = 200
     thpx.xStep = 0.1
     thpx.Overflow = False
     thpx.Style = "ATLAS"
     thpx.Filename = "pagerank"
     thpx.OutputDirectory = "./output/"
     thpx.SaveFigure()
     ttbar_msc = sum(ttbar_score.values(), [])
     tttt_msc  = sum(tttt_score.values(), [])
     ttbar_mx = sum(ttbar_mass.values(), [])
     tttt_mx  = sum(tttt_mass.values(), [])
     truth  = sum([sum(ttbar.t_topmass[i].values(), []) for i in ttbar.t_topmass], [])
     truth += sum([sum(tttt.t_topmass[i].values(), []) for i in tttt.t_topmass], [])
     tht = TH1F()
     tht.Color = "orange"
     tht.xData = truth
     tht.Title = 'Truth Tops'
     th2t = TH1F()
     th2t.Color = "red"
     th2t.xData = ttbar_mx
     th2t.Title = r'$\bar{t}t$'
     th4t = TH1F()
     th4t.Color = "blue"
     th4t.xData = tttt_mx
     th4t.Title = r'$\bar{t}t\bar{t}t$'
     thpx = TH1F()
     thpx.Histogram = tht
     thpx.Stacked = True
     thpx.Histograms = [th2t, th4t]
     thpx.Title = "Unweighted Invariant Mass of Reconstructed Top Candidates"
     thpx.xTitle = "Invariant Mass of Top Candidate (GeV)"
     thpx.yTitle = "Number of Top Candidates / (1 GeV)"
     thpx.xMin = 80
     thpx.xMax = 300
     thpx.xBins = 220
     thpx.xStep = 20
     thpx.Overflow = False
     thpx.Style = "ATLAS"
     thpx.Filename = "top-mass"
     thpx.OutputDirectory = "./output/"
     thpx.SaveFigure()
     thpx = TH2F()
     thpx.Title = "PageRank Score as a Function of Top Candidate Invariant Mass ($t\\bar{t}$)"
     thpx.xTitle = "Invariant Mass of Top Candidate (GeV)"
     thpx.yTitle = "Page Rank Score of Top Candidate (Arb.)"
     thpx.xMin  = 80
     thpx.xMax  = 300
     thpx.xBins = 220
     thpx.xStep = 20
     thpx.yStep = 0.1
     thpx.yBins = 100
     thpx.yMax = 1.0
     thpx.yMin = 0
     thpx.Color = "magma"
     thpx.xData = [ttbar_mx[i]  for i in range(len(ttbar_msc)) if ttbar_msc[i] < 0.95]
     thpx.yData = [ttbar_msc[i] for i in range(len(ttbar_msc)) if ttbar_msc[i] < 0.95]
     thpx.Style = "ATLAS"
     thpx.Filename = "top-mass-ttbar"
     thpx.OutputDirectory = "./output/"
     thpx.SaveFigure()
     thpx = TH2F()
     thpx.Title = "PageRank Score as a Function of Top Candidate Invariant Mass ($t\\bar{t}t\\bar{t}$)"
     thpx.xTitle = "Invariant Mass of Top Candidate (GeV)"
     thpx.yTitle = "Page Rank Score of Top Candidate (Arb.)"
     thpx.xMin  = 80
     thpx.xMax  = 300
     thpx.xBins = 220
     thpx.xStep = 20
     thpx.yStep = 0.1
     thpx.yBins = 100
     thpx.yMax = 1.0
     thpx.yMin = 0
     thpx.Color = "magma"
     thpx.xData = [tttt_mx[i]  for i in range(len(tttt_msc)) if tttt_msc[i] < 0.95]
     thpx.yData = [tttt_msc[i] for i in range(len(tttt_msc)) if tttt_msc[i] < 0.95]
     thpx.Style = "ATLAS"
     thpx.Filename = "top-mass-tttt"
     thpx.OutputDirectory = "./output/"
     thpx.SaveFigure()
References entry(), and revert_mapping().
entry_point()
def figures.entry_point (fancy, mode, pth, tree, plt = False)
Definition at line 93 of file mc20_experimental/figures.py.
 def entry_point(fancy, mode, pth, tree, plt = False):
     smplx = [
             "top-partons"      ,
             "top-children"     ,
             "top-truthjet"     ,
             "top-jets-children",
             "top-jets-leptons"
     ]
     fnc = ["Parton", "TopChildren", "TruthJet", "Jets Children", "Jets Leptons"]
 #    fnc = [i + " Level" for i in fnc]
     pths = ["top-parton", "top-children", "truth-jets", "jets-children", "jets-leptons"]
     pths = [mode + "/" + i for i in pths]
     data     = fetch_all(pth, tree, smplx)
     tops     = fetch_data(data, smplx[0])
     children = fetch_data(data, smplx[1])
     truthjet = fetch_data(data, smplx[2])
     jetschil = fetch_data(data, smplx[3])
     jetslept = fetch_data(data, smplx[4])
     #topx  = top_decay_stats(tops    ,  "p", fnc[0], fancy, pths[0], plt)
     #topc  = top_decay_stats(children,  "c", fnc[1], fancy, pths[1], plt)
     #toptj = top_decay_stats(truthjet, "tj", fnc[2], fancy, pths[2], plt)
     #topjc = top_decay_stats(jetschil, "jc", fnc[3], fancy, pths[3], plt)
     #topjl = top_decay_stats(jetslept, "jl", fnc[4], fancy, pths[4], plt)
     #top_mass_dist(tops    ,  "p", fnc[0], fancy, pths[0], plt, 150, 200, 100,  5.0)
     #top_mass_dist(children,  "c", fnc[1], fancy, pths[1], plt, 140, 200,  60,  5.0)
     #top_mass_dist(truthjet, "tj", fnc[2], fancy, pths[2], plt, 100, 300, 200, 10.0)
     #top_mass_dist(jetschil, "jc", fnc[3], fancy, pths[3], plt, 100, 300, 200, 10.0)
     #top_mass_dist(jetslept, "jl", fnc[4], fancy, pths[4], plt, 100, 300, 200, 10.0)
     #topc_cn  = constrain_top_mass(children,  "c", fnc[1], fancy, pths[1], plt, 140, 200,  60,  5.0, null_cut, ["red", "green", "orange", "purple", "blue", "grey"] )
     #toptj_cn = constrain_top_mass(truthjet, "tj", fnc[2], fancy, pths[2], plt,   0, 300, 300, 40.0, null_cut)
     #topjc_cn = constrain_top_mass(jetschil, "jc", fnc[3], fancy, pths[3], plt,   0, 300, 300, 40.0, null_cut)
     topjl_cn = constrain_top_mass(jetslept, "jl", fnc[4], fancy, pths[4], plt,   0, 300, 300, 40.0, null_cut)
     print("before constraint false matching: ", 100*topjl_cn["wrong"] / (topjl_cn["leptonic"] + topjl_cn["hadronic"]))
     #topc_cn  = constrain_top_mass(children,  "c", fnc[1], fancy, pths[1], plt, 140, 200,  60,  5.0, enforce_sym, ["red", "green", "orange", "purple", "grey"])
     #toptj_cn = constrain_top_mass(truthjet, "tj", fnc[2], fancy, pths[2], plt, 100, 300, 200, 40.0, enforce_sym_tj )
     #topjc_cn = constrain_top_mass(jetschil, "jc", fnc[3], fancy, pths[3], plt, 100, 300, 200, 40.0, enforce_sym_jet)
     topjl_cn = constrain_top_mass(jetslept, "jl", fnc[4], fancy, pths[4], plt, 100, 300, 200, 40.0, enforce_sym_jet)
     print("after containt false matching: ", 100*topjl_cn["wrong"] / (topjl_cn["leptonic"] + topjl_cn["hadronic"]))
     return
     toptj_nj = constrain_top_njets(truthjet, "tj", fnc[2], fancy, pths[2], plt, 0, 300, 300, 40.0)
     topjc_nj = constrain_top_njets(jetschil, "jc", fnc[3], fancy, pths[3], plt, 0, 300, 300, 40.0)
     topjl_nj = constrain_top_njets(jetslept, "jl", fnc[4], fancy, pths[4], plt, 0, 300, 300, 40.0)
     print("========================== (" + fancy + ") =========================")
     print("====================================================================")
     Tabular(topx,    None,  "Truth Tops"              , "Truth Tops")
     print("")
     print("====================================================================")
     Tabular(topx,    topc, "TopChildren"              , "TopChildren")
     Tabular(topx, topc_cn, "TopChildren (Constrained)", "TopChildren")
     print("")
     print("====================================================================")
     Tabular(topx,        toptj, "TruthJets (Unconstrained)"  , "TruthJets")
     Tabular(topx,     toptj_cn, "TruthJets (Constrained)"    , "TruthJets")
     TabularFlow(topx, toptj_nj, "TruthJets (Over/Under flow)", "TruthJets", 0, 400)
     print("")
     print("====================================================================")
     Tabular(topx,        topjc, "Jets Children (Unconstrained)"  , "JetsChildren")
     Tabular(topx,     topjc_cn, "Jets Children (Constrained)"    , "JetsChildren")
     TabularFlow(topx, topjc_nj, "Jets Children (Over/Under flow)", "JetsChildren", 0, 400)
     print("")
     print("====================================================================")
     Tabular(topx,        topjl, "Jets Leptons (Unconstrained)"  , "JetsLeptons")
     Tabular(topx,     topjl_cn, "Jets Leptons (Constrained)"    , "JetsLeptons")
     TabularFlow(topx, topjl_nj, "Jets Leptons (Over/Under flow)", "JetsLeptons", 0, 400)
References helper.constrain_top_mass(), helper.constrain_top_njets(), entry(), helper.fetch_all(), helper.fetch_data(), Tabular(), and TabularFlow().
fancy()
def figures.fancy (dev)
Definition at line 8 of file benchmarks/figures.py.
 def fancy(dev):
     tlt = {"a100" : "Ampere A100", "h100" : "Hopper H100", "v100" : "Tesla V100", "a30" : "Ampere A30"}
     return "\\texttt{" + tlt[dev] + "}"
Referenced by template_line().
Fancy()
def figures.Fancy (tl)
Definition at line 28 of file neutrino/figures.py.
 def Fancy(tl):
     if tl == "topchildren": return " (TopChildren) "
     if tl == "truthjet"   : return " (TruthJets) "
     if tl == "jetchildren": return " (JetsChildren) "
     if tl == "jetleptons" : return " (JetsLeptons) "
     if tl == "truth"      : return "Truth"
     if tl == "cuda_dnu"   : return "CUDA - Dynamic"
     if tl == "cuda_snu"   : return "CUDA - Static"
     if tl == "ref_dnu"    : return "Reference - Dynamic"
     if tl == "ref_snu"    : return "Reference - Static"
     if tl == "cuda"       : return "CUDA"
     if tl == "ref"        : return "Reference"
     return tl
Referenced by Chi2Distribution(), Chi2Symbolic(), EllipseDistance(), KSTestingDynamic(), and METError().
fancy_modes()
def figures.fancy_modes ()
Definition at line 43 of file benchmarks/figures.py.
 def fancy_modes():
     modx = {
             "cpu"        : "Time (CPU) - Lower is Better",
             "cuda_t"     : "Time (CUDA - Tensor) - Lower is Better",
             "cuda_k"     : "Time (CUDA - Kernel) - Lower is Better",
             "cpu_cuda_t" : "Ratio (CPU / CUDA - Tensor) - Higher is Better",
             "cpu_cuda_k" : "Ratio (CPU / CUDA - Kernel) - Higher is Better",
             "cuda_t_k"   : "Ratio CUDA (Tensor / Kernel) - Higher is Better"
     }
     return modx
Referenced by build_neutrino(), build_operators(), build_physics(), and build_transform().
fancy_title()
def figures.fancy_title (key)
Definition at line 12 of file benchmarks/figures.py.
 def fancy_title(key):
     maps = {
             "m"           : "Invariant Mass of Four Vector ($M$)",
             "p"           : "Magnitude of Momentum Vector ($\\sqrt{\\mathbf{p} \\cdot \\mathbf{p}}$)",
             "mt"          : "Transverse Invariant Mass ($M_T$)",
             "beta"        : "Fractional Velocity Relative to Speed of Light ($\\beta$)",
             "m2"          : "Square Invariant Mass of Four Vector ($M^2$)",
             "p2"          : "Magnitude of Momentum Vector ($\\mathbf{p} \\cdot \\mathbf{p}$)",
             "mt2"         : "Transverse Invariant Mass Squared ($M^{2}_T$)",
             "beta2"       : "Fractional Velocity Relative to Speed of Light Squared ($\\beta^2$)",
             "theta"       : "$\\cos^{-1}(P_z / \\sqrt{\\mathbf{p} \\cdot \\mathbf{p}})$",
             "deltaR"      : "$\\Delta R$ Between Two Four Vectors",
             "dot"         : "The Dot Product of Matrices A and B ($A \\cdot B$)",
             "cofactor"    : "Cofactors for a $3 \\times 3$ Matrix",
             "determinant" : "Determinant for a $3 \\times 3$ Matrix ($|A|$)",
             "eigenvalue"  : "Eigenvalues for a Symmetric $3 \\times 3$ Matrix ($(\\mathbf{A} - \\lambda \\mathbf{I})\\mathbf{v}$)",
             "inverse"     : "Inverse of a $3 \\times 3$ Matrix ($A^{-1}$)",
             "px"          : "Polar ($p_T, \\eta, \\phi$) Vector to Cartesian $x$-Momentum",
             "py"          : "Polar ($p_T, \\eta, \\phi$) Vector to Cartesian $y$-Momentum",
             "pz"          : "Polar ($p_T, \\eta, \\phi$) Vector to Cartesian $z$-Momentum",
             "eta"         : "Cartesian ($p_x, p_y, p_z$) Vector to Rapidity Polar Component ($\\eta$)",
             "phi"         : "Cartesian ($p_x, p_y, p_z$) Vector to Azimuthal Polar Component ($\\phi$)",
             "pt"          : "Cartesian ($p_x, p_y, p_z$) Vector to Transverse Momentum Polar Component ($p_T$)",
             "pxpypz"      : "Polar ($p_T, \\eta, \\phi$) to Cartesian Vector ($p_x, p_y, p_z$)",
             "pxpypze"     : "Polar ($p_T, \\eta, \\phi, E$) to Cartesian Vector ($p_x, p_y, p_z, E$)",
             "ptetaphi"    : "Cartesian ($p_x, p_y, p_z$) to Polar Vector ($p_T, \\eta, \\phi$)",
             "ptetaphie"   : "Cartesian ($p_x, p_y, p_z, E$) to Polar Vector ($p_T, \\eta, \\phi, E$)",
             "basematrix"  : "H-Matrix (Neutrino Extended Matrix Representation)",
     }
     return maps[key]
Referenced by build_neutrino(), build_operators(), build_physics(), and build_transform().
fnames()
def figures.fnames (key)
Definition at line 54 of file benchmarks/figures.py.
 def fnames(key):
     modx = {
             "cpu"        : "cpu_time",
             "cuda_t"     : "cuda_tensor_time",
             "cuda_k"     : "cuda_kernel_time",
             "cpu_cuda_t" : "ratio_cpu_cuda_tensor",
             "cpu_cuda_k" : "ratio_cpu_cuda_kernel",
             "cuda_t_k"   : "ratio_cuda_torch_kernel"
     }
     return modx[key]
Referenced by build_neutrino(), build_operators(), build_physics(), and build_transform().
GetValues()
def figures.GetValues (sel, key)
Definition at line 21 of file analysis/figures.py.
 def GetValues(sel, key):
     w  = [i[key]["weight"]    for i in sel.output if i[key]["passed"]]
     v1 = [i[key]["variable1"] for i in sel.output if i[key]["passed"]]
     v2 = [i[key]["variable2"] for i in sel.output if i[key]["passed"]]
     return w, v1, v2
Referenced by CR1b3le(), CR1b3lem(), CR1b3lm(), CR1bminus(), CR1bplus(), CRttbarCO2l_CO(), CRttbarCO2l_CO_2b(), CRttbarCO2l_gstr(), CRttbarCO2l_gstr_2b(), CRttW2l(), CRttW2l_minus(), and CRttW2l_plus().
KSTestingDynamic()
def figures.KSTestingDynamic (data)
Definition at line 68 of file neutrino/figures.py.
 def KSTestingDynamic(data):
     para = {
         "xTitle" : "Invariant Mass for Leptonic Tops (GeV)",
         "yTitle" : "Density (Arb.) / <units> (GeV)",
         "Alpha" : 0.25,
         "xMax"   : 400, "xMin": 0, "xStep" : 40, "xBins" : 400,
         "Density" : False,
     }
     out = {"KSTest" : {}}
     for i in data:
         tru = data[i].truth
         cu_dnu = data[i].cuda_dnu
         rf_dnu = data[i].ref_dnu
         out["KSTest"][i] = {}
         thc_dnu = template(cu_dnu.top1_masses, Fancy("cuda") , "red" , None, {"Density" : True})
         thr_dnu = template(rf_dnu.top1_masses, Fancy("ref")  , "blue", None, {"Hatch" : "////\\\\\\\\", "Marker" : "x", "Density" : True})
         th = template(None, "Reconstructed Leptonic Top ($\\nu_{1}$) Shape Comparison " + Fancy(i), None, "ks-test/" + i, para)
         th.Histogram = thr_dnu
         th.Histograms = [thc_dnu]
         th.FX("chi2")
         th.Filename = "neutrino_1"
         th.SaveFigure()
         thc_dnu = template(cu_dnu.top2_masses, Fancy("cuda") , "red" , None, {"Density" : True})
         thr_dnu = template(rf_dnu.top2_masses, Fancy("ref")  , "blue", None, {"Hatch" : "////\\\\\\\\", "Marker" : "x", "Density" : True})
         th = template(None, "Reconstructed Leptonic Top ($\\nu_{2}$) Shape Comparison " + Fancy(i), None, "ks-test/" + i, para)
         th.Histogram = thr_dnu
         th.Histograms = [thc_dnu]
         th.FX("chi2")
         th.Filename = "neutrino_2"
         th.SaveFigure()
         nex = dict(para)
         nex["Density"] = False
         nex["Alpha"] = 0.5
         nex["yTitle"] = "Reconstructed (Truth) Leptonic Tops / <units> (GeV)"
         cu_tht_dnu = template(cu_dnu.target_top1 + cu_dnu.target_top2, Fancy("truth")   , "black", None, nex)
         r_cu_dnu   = template(cu_dnu.top1_masses + cu_dnu.top2_masses, Fancy("cuda_dnu"), "red" , None, nex)
         th = template(None, "Reconstructed Leptonic Tops ($\\nu_{1}$ and $\\nu_{2}$)" + Fancy(i), None, "ks-test/" + i, para)
         th.Histogram = cu_tht_dnu
         th.Histograms = [r_cu_dnu]
         th.FX("chi2")
         th.Filename = "cuda-dynamic"
         th.SaveFigure()
         rf_tht_dnu = template(rf_dnu.target_top1 + rf_dnu.target_top2, Fancy("truth")  , "black", None, nex)
         r_rf_dnu   = template(rf_dnu.top1_masses + rf_dnu.top2_masses, Fancy("ref_dnu"), "red"  , None, nex)
         th = template(None, "Reconstructed Leptonic Tops ($\\nu_{1}$ and $\\nu_{2}$)" + Fancy(i), None, "ks-test/" + i, para)
         th.Histogram = rf_tht_dnu
         th.Histograms = [r_rf_dnu]
         th.FX("chi2")
         th.Filename = "ref-dynamic"
         th.SaveFigure()
         out["KSTest"][i]["nunu-cuda-ref"]   = r_rf_dnu.KStest(r_cu_dnu)
         out["KSTest"][i]["nunu-truth-ref"]  = rf_tht_dnu.KStest(r_rf_dnu)
         out["KSTest"][i]["nunu-truth-cuda"] = cu_tht_dnu.KStest(r_cu_dnu)
     return out
References Fancy(), and template().
Referenced by METError().
METError()
def figures.METError (data)
Definition at line 316 of file neutrino/figures.py.
 def METError(data):
     for i in data:
         cu_dnu = data[i].cuda_dnu
         xh = default(TH2F(), "met/" + i)
         xh.Title = "$\\chi^2$ Dependency on Missing Transverse Energy" + Fancy("cuda_dnu")
         xh.xData = [k / 1000.0 for k in cu_dnu.event_data["met"]]
         xh.xBins = 200
         xh.xMin  = 0
         xh.xMax  = 200
         xh.xStep = 20.0
         xh.xTitle = "Missing Transverse Energy (GeV)"
         xh.yData = cu_dnu.chi2_nu1
         xh.yBins = 200
         xh.yMin  = 0
         xh.yMax  = 200
         xh.yStep = 20.0
         xh.yTitle = "Kinematic Error for Reconstructed Neutrino ($\\chi^2$) (Arb.)"
         xh.Filename = "correlation-cuda-dynamic"
         xh.SaveFigure()
References Chi2Distribution(), Chi2Symbolic(), helper.compxl(), default(), EllipseDistance(), entry(), Fancy(), KSTestingDynamic(), print_statistics(), and statistics().
null_cut()
def figures.null_cut (p, m, pdg, is_l, nj)
Definition at line 6 of file mc20_experimental/figures.py.
 def null_cut(p, m, pdg, is_l, nj): return True
path()
def figures.path (hist)
Definition at line 3 of file topreconstruction/figures.py.
 def path(hist):
     hist.UseLateX = False
     hist.Style = "ATLAS"
     hist.OutputDirectory = "./output"
     hist.xTitle = "Invariant Mass of Candidate Top (GeV)"
     hist.yTitle = "Tops / ($2$ GeV)"
     hist.xMin   = 0
     hist.yMin   = 0
     hist.xStep  = 20
     hist.xMax   = 400
     hist.xBins  = 200
     hist.Stacked   = False
     hist.Overflow  = False
     hist.ShowCount = True
     return hist
print_statistics()
def figures.print_statistics (data)
Definition at line 22 of file neutrino/figures.py.
 def print_statistics(data):
     for i in typx:
         print(i + " " + data[i].__str__())
         for k in data["KSTest"][i]:
             print(k + "-> ", data["KSTest"][i][k])
Referenced by METError().
revert_mapping()
def figures.revert_mapping (data)
Definition at line 19 of file topreconstruction/figures.py.
 def revert_mapping(data):
     pred_mass = data.p_topmass
     scr_mass  = data.prob_tops
     mass  = {}
     score = {}
     for i in pred_mass:
         v_mass = pred_mass[i]
         s_mass = scr_mass[i]
         for h in v_mass:
             if h not in score: mass[h] = []; score[h] = []
             mass[h]  += v_mass[h]
             score[h] += s_mass[h]
     return score, mass
Referenced by entry().
SR()
def figures.SR (sel)
Definition at line 123 of file analysis/figures.py.
 def SR(sel):
     return
Referenced by entry(), and regions.merge().
SR2b()
def figures.SR2b (sel)
Definition at line 96 of file analysis/figures.py.
 def SR2b(sel):
     return
Referenced by entry(), and regions.merge().
SR2b2l()
def figures.SR2b2l (sel)
Definition at line 102 of file analysis/figures.py.
 def SR2b2l(sel):
     return
Referenced by entry(), and regions.merge().
SR2b3l4l()
def figures.SR2b3l4l (sel)
Definition at line 105 of file analysis/figures.py.
 def SR2b3l4l(sel):
     return
Referenced by entry(), and regions.merge().
SR2b4l()
def figures.SR2b4l (sel)
Definition at line 108 of file analysis/figures.py.
 def SR2b4l(sel):
     return
Referenced by entry(), and regions.merge().
SR3b()
def figures.SR3b (sel)
Definition at line 99 of file analysis/figures.py.
 def SR3b(sel):
     return
Referenced by entry(), and regions.merge().
SR3b2l()
def figures.SR3b2l (sel)
Definition at line 111 of file analysis/figures.py.
 def SR3b2l(sel):
     return
Referenced by entry(), and regions.merge().
SR3b3l4l()
def figures.SR3b3l4l (sel)
Definition at line 114 of file analysis/figures.py.
 def SR3b3l4l(sel):
     return
Referenced by entry(), and regions.merge().
SR3b4l()
def figures.SR3b4l (sel)
Definition at line 117 of file analysis/figures.py.
 def SR3b4l(sel):
     return
Referenced by entry(), and regions.merge().
SR4b()
def figures.SR4b (sel)
Definition at line 93 of file analysis/figures.py.
 def SR4b(sel):
     return
Referenced by entry(), and regions.merge().
SR4b4l()
def figures.SR4b4l (sel)
Definition at line 120 of file analysis/figures.py.
 def SR4b4l(sel):
     return
Referenced by entry(), and regions.merge().
statistics()
def figures.statistics (data, eps = None)
Definition at line 6 of file neutrino/figures.py.
 def statistics(data, eps = None):
     losses = {i : loss(eps) for i in typx}
     for i in range(len(data["topchildren"])):
         if data["topchildren"][i] is None: continue
         for k in typx: losses[k].add(data[k][i])
     return losses
Referenced by METError().
Tabular()
def figures.Tabular (topx, target, title, mode, rec = None)
Definition at line 31 of file mc20_experimental/figures.py.
 def Tabular(topx, target, title, mode, rec = None):
     print("---------------------- " + title + " ------------------------ ")
     if target is None:
         print(mag("Top-Multiplicity: "      , 16) + mrg(topx["counts"], 8))
         print(mag("Initial Number of Tops: ", 16) + mrg(topx["ntops"] , 8))
     else:
         if "counts" in target: print(mag("Top-Multiplicity: ", 16) + mrg(target["counts"]))
         print(mag("Number of Tops: ", 16) + mrg(target["ntops"], 0) + " | Loss (%): " + loss(topx["ntops"], target["ntops"], 4))
     if target is None:
         print(mag("Leptonic: ", 16) + mrg(topx["leptonic"], 0) + " | (%): " +  pc(topx["ntops"], topx["leptonic"], 4))
         print(mag("Hadronic: ", 16) + mrg(topx["hadronic"], 0) + " | (%): " +  pc(topx["ntops"], topx["hadronic"], 4))
         return
     print(mag("Leptonic: ", 16) + mrg(target["leptonic"], 0) + " | Loss (%): " + loss(topx["leptonic"], target["leptonic"], 4))
     print(mag("Hadronic: ", 16) + mrg(target["hadronic"], 0) + " | Loss (%): " + loss(topx["hadronic"], target["hadronic"], 4))
     if "stats-all" not in target: return
     a_tops ,  o_tops,   u_tops  = (sum(target["stats-all"][k].values()) for k in ["domain", "over", "under"])
     l_tops,  ol_tops,  ul_tops  = (target["stats-all"][k]["leptonic"] for k in ["domain", "over", "under"])
     h_tops,  oh_tops,  uh_tops  = (target["stats-all"][k]["hadronic"] for k in ["domain", "over", "under"])
     p = 6
     at_tops = a_tops + o_tops + u_tops
     al_tops = l_tops + ol_tops + ul_tops
     ah_tops = h_tops + oh_tops + uh_tops
     print("____________________ Raw Values ____________________")
     print(mag("Leptonically Matched: ", 25) + mrg(al_tops, 0) + " | Overflow: " + mrg(ol_tops, 0) + " Underflow: " + mrg(ul_tops, 0))
     print(mag("Hadronically Matched: ", 25) + mrg(ah_tops, 0) + " | Overflow: " + mrg(oh_tops, 0) + " Underflow: " + mrg(uh_tops, 0))
     print(mag("False Assigned (wrong/(lep+had)): ", 16) + mrg(target["wrong"], 0) + " | False Matching (lepton != hadron) (%): " + pc(target["hadronic"] + target["leptonic"], target["wrong"], p))
     print("____________________ Percentage ____________________")
     print(mag("Leptonically (lep/all_leps): ", 30) + pc(al_tops, l_tops, p) + " | Overflow: " + pc(al_tops, ol_tops, p) + " Underflow: " + pc(al_tops, ul_tops, p))
     print(mag("Hadronically (had/all_hads): ", 30) + pc(ah_tops, h_tops, p) + " | Overflow: " + pc(ah_tops, oh_tops, p) + " Underflow: " + pc(ah_tops, uh_tops, p))
     print("")
References helper.mag(), helper.mrg(), and helper.pc().
Referenced by entry_point().
TabularFlow()
def figures.TabularFlow (topx, stat, title, mode, min_, max_)
Definition at line 67 of file mc20_experimental/figures.py.
 def TabularFlow(topx, stat, title, mode, min_, max_):
     a_tops,  o_tops,  u_tops = (sum(stat["tops-merged"][k]["all"].values())      for k in ["domain", "over", "under"])
     l_tops, ol_tops, ul_tops = (sum(stat["tops-merged"][k]["leptonic"].values()) for k in ["domain", "over", "under"])
     h_tops, oh_tops, uh_tops = (sum(stat["tops-merged"][k]["hadronic"].values()) for k in ["domain", "over", "under"])
     at_tops = a_tops + o_tops + u_tops
     al_tops = l_tops + ol_tops + ul_tops
     ah_tops = h_tops + oh_tops + uh_tops
     print("---------------------- " + title + " ------------------------ ")
     print("____________________ Raw Values ____________________")
     print(mag(mode + " Number of Tops (" + str(min_) + " -> " + str(max_) + "): ", 30))
     print(mag("All: "                 , 25) + mrg(a_tops, 0) + " | Overflow: " + mrg(o_tops , 0) + " Underflow: " + mrg( u_tops, 0))
     print(mag("Leptonically Matched: ", 25) + mrg(l_tops, 0) + " | Overflow: " + mrg(ol_tops, 0) + " Underflow: " + mrg(ul_tops, 0))
     print(mag("Hadronically Matched: ", 25) + mrg(h_tops, 0) + " | Overflow: " + mrg(oh_tops, 0) + " Underflow: " + mrg(uh_tops, 0))
     p = 6
     print("____________________ Percentage (based on available tops) ____________________")
     print(mag("All Matched: "                , 30) + pc(at_tops, a_tops, p) + " | Overflow: " + pc(at_tops, o_tops , p) + " Underflow: " + pc(at_tops,  u_tops, p))
     print(mag("Leptonically (lep/all_leps): ", 30) + pc(al_tops, l_tops, p) + " | Overflow: " + pc(al_tops, ol_tops, p) + " Underflow: " + pc(al_tops, ul_tops, p))
     print(mag("Hadronically (had/all_hads): ", 30) + pc(ah_tops, h_tops, p) + " | Overflow: " + pc(ah_tops, oh_tops, p) + " Underflow: " + pc(ah_tops, uh_tops, p))
     print("____________________ Loss (relative to initial tops)____________________")
     print(mag("All: ", 6) + loss(topx["ntops"], a_tops, p) + " | Leptonically Matched: " + loss(topx["leptonic"], l_tops, p) + " | Hadronically Matched: " + loss(topx["hadronic"], h_tops, p))
     print("")
References helper.mag(), helper.mrg(), and helper.pc().
Referenced by entry_point().
template()
def figures.template (xdata, title, color = None, pth = None, params = {})
Definition at line 56 of file neutrino/figures.py.
 def template(xdata, title, color = None, pth = None, params = {}):
     thl = default(TH1F(), pth) if xdata is None else TH1F()
     if xdata is not None: thl.xData = xdata
     if color is not None: thl.Color = color
     thl.xMin = 0
     thl.Alpha = 0.5
     thl.Title = title
     for i in params:
         if i == "yTitle": params[i] = params[i].replace("<unit>", str((params["xMax"] - params["xMin"]) / params["xBins"]))
         setattr(thl, i, params[i])
     return thl
References default().
Referenced by Chi2Distribution(), Chi2Symbolic(), EllipseDistance(), and KSTestingDynamic().
template_hist()
def figures.template_hist (title, weights, data, bins, xmax, xtitle, xmin = None, xstep = None, fname = None)
Definition at line 3 of file analysis/figures.py.
 def template_hist(title, weights, data, bins, xmax, xtitle, xmin = None, xstep = None, fname = None):
     f = TH1F()
     f.Title = title
     f.Weights = weights
     f.xData = data
     f.xBins = bins
     f.xMax = xmax
     if xmin is not None: f.xMin = xmin
     if xstep is not None: f.xStep = xstep
     f.Color = "orange"
     f.yTitle = "Events"
     f.xTitle = xtitle
     f.Filename = fname if fname is not None else title
     f.Overflow = "none"
     f.ShowCount = True
     f.ErrorBars = True
     return f
Referenced by CR1b3le(), CR1b3lem(), CR1b3lm(), CR1bminus(), CR1bplus(), CRttbarCO2l_CO(), CRttbarCO2l_CO_2b(), CRttbarCO2l_gstr(), CRttbarCO2l_gstr_2b(), CRttW2l(), CRttW2l_minus(), and CRttW2l_plus().
template_line()
def figures.template_line (title, data, mode, linst = "-", misc = None)
Definition at line 70 of file benchmarks/figures.py.
 def template_line(title, data, mode, linst = "-", misc = None):
     tl = TLine()
     tl.Title = fancy(title) if misc is None else fancy(title) + " ($\\texttt{" + misc + "}$)"
     tl.LineWidth = 1.0
     tl.CapSize = 2.0
     tl.ErrorBars = True
     tl.xData = xdata(data, mode)
     tl.yData = ydata(data, mode)
     tl.yDataUp   = edata(data, mode)
     tl.yDataDown = edata(data, mode)
     tl.Color = colr(title)
     tl.LineStyle = linst
     return tl
References colr(), edata(), fancy(), xdata(), and ydata().
Referenced by build_neutrino(), build_operators(), build_physics(), and build_transform().
template_Tline()
def figures.template_Tline (ytitle, opx, fname, lines)
Definition at line 84 of file benchmarks/figures.py.
 def template_Tline(ytitle, opx, fname, lines):
     th = TLine()
     defaults(th)
     th.Lines = lines
     th.xMin = 0
     th.xMax = 1000
     th.yMin = 0
     th.xStep = 100
     th.yTitle = ytitle
     th.OutputDirectory = "./Figures/" + opx
     th.xTitle = "Length of Tensor - (Units of 1000)"
     th.Filename = fname
     if "time" in fname: return th
     m_ = 0
     for i in lines: m_ = max(i.yData) if m_ < max(i.yData) else m_
     if   m_ < 2:    th.yStep = 0.2
     elif m_ < 3:    th.yStep = 0.2
     elif m_ < 5:    th.yStep = 0.5
     elif m_ < 10:   th.yStep = 0.5
     elif m_ < 20:   th.yStep = 1
     elif m_ < 30:   th.yStep = 2
     elif m_ < 40:   th.yStep = 4
     elif m_ < 100:  th.yStep = 10
     else: th.yLogarithmic = True; th.yMin = 1.0
     if   m_ < 2:    th.yMax = 2.1
     elif m_ < 3:    th.yMax = 3.1
     elif m_ < 5:    th.yMax = 5.1
     elif m_ < 10:   th.yMax = 10.1
     elif m_ < 20:   th.yMax = 20.1
     elif m_ < 30:   th.yMax = 30.1
     elif m_ < 40:   th.yMax = 40.1
     elif m_ < 100:  th.yMax = 100.1
     return th
References main.defaults.
Referenced by build_neutrino(), build_operators(), build_physics(), and build_transform().
VRttWCRSR()
def figures.VRttWCRSR (sel)
Definition at line 90 of file analysis/figures.py.
 def VRttWCRSR(sel):
     return
Referenced by entry(), and regions.merge().
VRttZ3l()
def figures.VRttZ3l (sel)
Definition at line 87 of file analysis/figures.py.
 def VRttZ3l(sel):
     return
Referenced by entry(), and regions.merge().
xdata()
def figures.xdata (data, mode)
Definition at line 66 of file benchmarks/figures.py.
 def xdata(data, mode): return [getattr(i, mode).idx / 1000 for i in data][1:]
Referenced by template_line().
ydata()
def figures.ydata (data, mode)
Definition at line 67 of file benchmarks/figures.py.
 def ydata(data, mode): return [getattr(i, mode).mu  for i in data][1:]
Referenced by template_line().
Variable Documentation
typx
list figures.typx = ["topchildren", "truthjet", "jetchildren", "jetleptons"]
Definition at line 5 of file neutrino/figures.py.