AnalysisG: pyc::transform::separate Namespace Reference
pyc::transform::separate Namespace Reference
Functions
torch::Tensor Pt (torch::Tensor px, torch::Tensor py)
torch::Tensor Eta (torch::Tensor px, torch::Tensor py, torch::Tensor pz)
torch::Tensor Phi (torch::Tensor px, torch::Tensor py)
torch::Tensor PtEtaPhi (torch::Tensor px, torch::Tensor py, torch::Tensor pz)
torch::Tensor PtEtaPhiE (torch::Tensor px, torch::Tensor py, torch::Tensor pz, torch::Tensor e)
torch::Tensor Px (torch::Tensor pt, torch::Tensor phi)
torch::Tensor Py (torch::Tensor pt, torch::Tensor phi)
torch::Tensor Pz (torch::Tensor pt, torch::Tensor eta)
torch::Tensor PxPyPz (torch::Tensor pt, torch::Tensor eta, torch::Tensor phi)
torch::Tensor PxPyPzE (torch::Tensor pt, torch::Tensor eta, torch::Tensor phi, torch::Tensor e)
Function Documentation
Eta()
torch::Tensor pyc::transform::separate::Eta (torch::Tensor px, torch::Tensor py, torch::Tensor pz)
Definition at line 23 of file interface/transform.cxx.
{
     changedev(&px);
     return transform_::Eta(&px, &py, &pz);
 }
References changedev(), and transform_::Eta().
Phi()
torch::Tensor pyc::transform::separate::Phi (torch::Tensor px, torch::Tensor py)
Definition at line 33 of file interface/transform.cxx.
{
     changedev(&px);
     return transform_::Phi(&px, &py);
 }
References changedev(), and transform_::Phi().
Pt()
torch::Tensor pyc::transform::separate::Pt (torch::Tensor px, torch::Tensor py)
Definition at line 11 of file interface/transform.cxx.
{
     changedev(&px);
     return transform_::Pt(&px, &py);
 }
References changedev(), and transform_::Pt().
PtEtaPhi()
torch::Tensor pyc::transform::separate::PtEtaPhi (torch::Tensor px, torch::Tensor py, torch::Tensor pz)
Definition at line 45 of file interface/transform.cxx.
{
     changedev(&px);
     return transform_::PtEtaPhi(&px, &py, &pz);
 }
References changedev(), and transform_::PtEtaPhi().
PtEtaPhiE()
torch::Tensor pyc::transform::separate::PtEtaPhiE (torch::Tensor px, torch::Tensor py, torch::Tensor pz, torch::Tensor e)
Definition at line 55 of file interface/transform.cxx.
{
     changedev(&e);
     return transform_::PtEtaPhiE(&px, &py, &pz, &e);
 }
References changedev(), test_particles::e, and transform_::PtEtaPhiE().
Px()
torch::Tensor pyc::transform::separate::Px (torch::Tensor pt, torch::Tensor phi)
Definition at line 65 of file interface/transform.cxx.
{
     changedev(&pt);
     return transform_::Px(&pt, &phi);
 }
References changedev(), and transform_::Px().
Referenced by pyc::nusol::combinatorial(), pyc::nusol::NuNu(), and test_particles::test_particle_template().
PxPyPz()
torch::Tensor pyc::transform::separate::PxPyPz (torch::Tensor pt, torch::Tensor eta, torch::Tensor phi)
Definition at line 101 of file interface/transform.cxx.
{
     changedev(&phi);
     return transform_::PxPyPz(&pt, &eta, &phi);
 }
References changedev(), and transform_::PxPyPz().
PxPyPzE()
torch::Tensor pyc::transform::separate::PxPyPzE (torch::Tensor pt, torch::Tensor eta, torch::Tensor phi, torch::Tensor e)
Definition at line 111 of file interface/transform.cxx.
{
     changedev(&pt);
     return transform_::PxPyPzE(&pt, &eta, &phi, &e);
 }
References changedev(), test_particles::e, and transform_::PxPyPzE().
Referenced by grift::forward(), and recursivegraphneuralnetwork::forward().
Py()
torch::Tensor pyc::transform::separate::Py (torch::Tensor pt, torch::Tensor phi)
Definition at line 77 of file interface/transform.cxx.
{
     changedev(&phi);
     return transform_::Py(&pt, &phi);
 }
References changedev(), and transform_::Py().
Referenced by pyc::nusol::combinatorial(), pyc::nusol::NuNu(), and test_particles::test_particle_template().
Pz()
torch::Tensor pyc::transform::separate::Pz (torch::Tensor pt, torch::Tensor eta)
Definition at line 89 of file interface/transform.cxx.
{
     changedev(&pt);
     return transform_::Pz(&pt, &eta);
 }
References changedev(), and transform_::Pz().
Referenced by test_particles::test_particle_template().