AnalysisG: pyc::nusol Namespace Reference
pyc::nusol Namespace Reference
Functions
torch::Dict< std::string, torch::Tensor > BaseMatrix (torch::Tensor pmc_b, torch::Tensor pmc_mu, torch::Tensor masses)
torch::Dict< std::string, torch::Tensor > Nu (torch::Tensor pmc_b, torch::Tensor pmc_mu, torch::Tensor met_xy, torch::Tensor masses, torch::Tensor sigma, double null=10e-10)
torch::Dict< std::string, torch::Tensor > NuNu (torch::Tensor pmc_b1, torch::Tensor pmc_b2, torch::Tensor pmc_l1, torch::Tensor pmc_l2, torch::Tensor met_xy, torch::Tensor masses, double null=10e-10, const double step=1e-9, const double tolerance=1e-6, const unsigned int timeout=1000)
torch::Dict< std::string, torch::Tensor > NuNu (torch::Tensor pmc_b1, torch::Tensor pmc_b2, torch::Tensor pmc_l1, torch::Tensor pmc_l2, torch::Tensor met_xy, double null, torch::Tensor mass1, torch::Tensor mass2, const double step=1e-9, const double tolerance=1e-6, const unsigned int timeout=1000)
std::vector< std::pair< neutrino *, neutrino * > > NuNu (std::vector< std::vector< double >> *pmc_b1, std::vector< std::vector< double >> *pmc_b2, std::vector< std::vector< double >> *pmc_l1, std::vector< std::vector< double >> *pmc_l2, std::vector< double > *met, std::vector< double > *phi, std::vector< std::vector< double >> *mass1, std::vector< std::vector< double >> *mass2, std::string dev, const double null, const double step, const double tolerance, const unsigned int timeout)
template<typename b , typename l >
std::vector< std::pair< neutrino *, neutrino * > > NuNu (std::vector< b * > bquark1, std::vector< b * > bquark2, std::vector< l * > lepton1, std::vector< l * > lepton2, std::vector< double > met_, std::vector< double > phi_, std::vector< std::vector< double >> mass1, std::vector< std::vector< double >> mass2, std::string dev, double null, const double step, const double tolerance, const unsigned int timeout)
torch::Dict< std::string, torch::Tensor > combinatorial (torch::Tensor edge_index, torch::Tensor batch, torch::Tensor pmc, torch::Tensor pid, torch::Tensor met_xy, double mT=172.62 *1000, double mW=80.385 *1000, double null=1e-10, double perturb=1e-3, long steps=100, bool gev=false)
std::vector< std::pair< neutrino *, neutrino * > > combinatorial (std::vector< double > *met_, std::vector< double > *phi_, std::vector< std::vector< double >> *pmc, std::vector< long > *bth, std::vector< long > *is_b, std::vector< long > *is_l, std::string dev, double mT, double mW, double null, double perturb, long steps)
std::vector< std::pair< neutrino *, neutrino * > > combinatorial (std::vector< double > met_, std::vector< double > phi_, std::vector< std::vector< particle_template * >> particles, std::string dev, double mT, double mW, double null, double perturb, long steps)
Function Documentation
BaseMatrix()
torch::Dict< std::string, torch::Tensor > pyc::nusol::BaseMatrix (torch::Tensor pmc_b, torch::Tensor pmc_mu, torch::Tensor masses)
Definition at line 11 of file interface/nusol.cxx.
{
     changedev(&pmc_b);
     return pyc::std_to_dict(nusol_::BaseMatrix(&pmc_b, &pmc_mu, &masses));
 }
References nusol_::BaseMatrix(), changedev(), main::masses, and pyc::std_to_dict().
combinatorial() [1/3]
std::vector< std::pair< neutrino *, neutrino * > > pyc::nusol::combinatorial (std::vector< double > * met_, std::vector< double > * phi_, std::vector< std::vector< double >> * pmc, std::vector< long > * bth, std::vector< long > * is_b, std::vector< long > * is_l, std::string dev, double mT, double mW, double null, double perturb, long steps)
Definition at line 123 of file interface.cxx.
  {
     std::vector<std::vector<long>> edge_index_ = {};
     edge_index_.push_back({});
     edge_index_.push_back({});
     for (size_t x(0); x < bth_ -> size(); ++x){
         long ix = (*bth_)[x];
         for (size_t y(0); y < bth_ -> size(); ++y){
             long iy = (*bth_)[y];
             if (iy != ix){continue;}
             edge_index_[0].push_back(long(x));
             edge_index_[1].push_back(long(y));
         }
     }
     if (!steps){std::cout << "FAILURE steps parameter set to 0" << std::endl; abort();}
     torch::Tensor met        = pyc::tensorize(met_);
     torch::Tensor phi        = pyc::tensorize(phi_);
     torch::Tensor pmc        = pyc::tensorize(pmc_);
     torch::Tensor isb        = pyc::tensorize(is_b_);
     torch::Tensor isl        = pyc::tensorize(is_l_);
     torch::Tensor bth        = pyc::tensorize(bth_);
     torch::Tensor edge_index = pyc::tensorize(&edge_index_);
     pmc        = changedev(dev, &pmc);
     bth        = changedev(dev, &bth).view({-1});
     met        = changedev(dev, &met).view({-1, 1});
     phi        = changedev(dev, &phi).view({-1, 1});
     edge_index = changedev(dev, &edge_index);
     torch::Tensor pid   = torch::cat({changedev(dev, &isl).view({-1, 1}), changedev(dev, &isb).view({-1, 1})}, {-1});
     torch::Tensor metxy = torch::cat({pyc::transform::separate::Px(met, phi), pyc::transform::separate::Py(met, phi)}, {-1});
     torch::Dict<std::string, torch::Tensor> nus = pyc::nusol::combinatorial(edge_index, bth, pmc, pid, metxy, mT, mW, null, perturb, steps);
     if (!nus.contains("nu1")){return {};}
     torch::Tensor nu1 = nus.at("nu1");
     torch::Tensor nu2 = nus.at("nu2");
     torch::Tensor l1  = nus.at("l1");
     torch::Tensor l2  = nus.at("l2");
     torch::Tensor b1  = nus.at("b1");
     torch::Tensor b2  = nus.at("b2");
     torch::Tensor dis = nus.at("distances");
     std::vector<double> dist;
     tensor_to_vector(&dis, &dist);
     std::vector<neutrino*> nu1_ = construct_particle(&nu1, &l1, &b1, &dist);
     std::vector<neutrino*> nu2_ = construct_particle(&nu2, &l2, &b2, &dist);
     std::vector<std::pair<neutrino*, neutrino*>> out = {};
     for (size_t x(0); x < nu1_.size(); ++x){out.push_back({nu1_[x], nu2_[x]});}
     return out;
 }
References changedev(), combinatorial(), construct_particle(), main::dev, edge_index, l1, nusol::mT, nusol::mW, main::out, pmc, pyc::transform::separate::Px(), pyc::transform::separate::Py(), tensor_to_vector(), pyc::tensorize(), and main::x.
combinatorial() [2/3]
std::vector< std::pair< neutrino *, neutrino * > > pyc::nusol::combinatorial (std::vector< double > met_, std::vector< double > phi_, std::vector< std::vector< particle_template * >> particles, std::string dev, double mT, double mW, double null, double perturb, long steps)
Definition at line 57 of file interface/nusol.cxx.
  {
     std::vector<std::vector<particle_template*>> quarks, leptons;
     for (size_t x(0); x < particles.size(); ++x){
         quarks.push_back({}); leptons.push_back({});
         for (size_t y(0); y < particles[x].size(); ++y){
             bool is_b = particles[x][y] -> is_b;
             if (is_b){quarks[x].push_back(particles[x][y]); continue;}
             bool is_l = particles[x][y] -> is_lep;
             if (is_l){leptons[x].push_back(particles[x][y]); continue;}
         }
     }
     std::vector<long> isb_, isl_, bth, index;
     std::vector<std::vector<double>> pmc;
     for (size_t x(0); x < met_.size(); ++x){
         long bl = x;
         for (size_t y(0); y < quarks[x].size(); ++y){
             particle_template* bq = quarks[x][y];
             if (!bq -> is_b){continue;}
             index.push_back(long(y));
             isl_.push_back(long(0));
             isb_.push_back(long(bq -> is_b));
             pmc.push_back(pyc::as_pmc(bq));
             bth.push_back(bl);
         }
         for (size_t y(0); y < leptons[x].size(); ++y){
             particle_template* lp = leptons[x][y];
             if (lp -> is_nu || !lp -> is_lep){continue;}
             index.push_back(long(y));
             isl_.push_back(long(leptons[x][y] -> is_lep));
             isb_.push_back(long(0));
             pmc.push_back(pyc::as_pmc(lp));
             bth.push_back(bl);
         }
     }
     std::vector<std::pair<neutrino*, neutrino*>> out;
     out = pyc::nusol::combinatorial(&met_, &phi_, &pmc, &bth, &isb_, &isl_, dev, mT, mW, null, perturb, steps);
     if (!out.size()){return out;}
     for (size_t x(0); x < out.size(); ++x){
         neutrino* nu1 = std::get<0>(out[x]);
         neutrino* nu2 = std::get<1>(out[x]);
         size_t i = bth[x];
         nu1 -> bquark = new particle_template(quarks[i][index[nu1 -> b_idx]]);
         nu1 -> lepton = new particle_template(leptons[i][index[nu1 -> l_idx]]);
         nu2 -> bquark = new particle_template(quarks[i][index[nu2 -> b_idx]]);
         nu2 -> lepton = new particle_template(leptons[i][index[nu2 -> l_idx]]);
     }
     return out;
 }
References pyc::as_pmc(), combinatorial(), main::dev, is_b, is_lep, is_nu, nusol::mT, nusol::mW, main::out, pmc, and main::x.
combinatorial() [3/3]
torch::Dict< std::string, torch::Tensor > pyc::nusol::combinatorial (torch::Tensor edge_index, torch::Tensor batch, torch::Tensor pmc, torch::Tensor pid, torch::Tensor met_xy, double mT = 172.62*1000, double mW = 80.385*1000, double null = 1e-10, double perturb = 1e-3, long steps = 100, bool gev = false)
Definition at line 47 of file interface/nusol.cxx.
  {
     changedev(&edge_index);
     std::map<std::string, torch::Tensor> out;
     out = nusol_::combinatorial(&edge_index, &batch, &pmc, &pid, &met_xy, mT, mW, null, perturb, steps, gev);
     return pyc::std_to_dict(&out);
 }
References batch(), changedev(), edge_index, nusol::mT, nusol::mW, main::out, pmc, and pyc::std_to_dict().
Referenced by combinatorial(), and combinatorial::reconstruction().
Nu()
torch::Dict< std::string, torch::Tensor > pyc::nusol::Nu (torch::Tensor pmc_b, torch::Tensor pmc_mu, torch::Tensor met_xy, torch::Tensor masses, torch::Tensor sigma, double null = 10e-10)
Definition at line 16 of file interface/nusol.cxx.
  {
     changedev(&pmc_b);
     std::map<std::string, torch::Tensor> out = nusol_::Nu(&pmc_b, &pmc_mu, &met_xy, &masses, &sigma, null);
     return pyc::std_to_dict(&out);
 }
References changedev(), main::masses, nusol_::Nu(), main::out, and pyc::std_to_dict().
NuNu() [1/4]
template<typename b , typename l > std::vector<std::pair<neutrino*, neutrino*> > pyc::nusol::NuNu (std::vector< b * > bquark1, std::vector< b * > bquark2, std::vector< l * > lepton1, std::vector< l * > lepton2, std::vector< double > met_, std::vector< double > phi_, std::vector< std::vector< double >> mass1, std::vector< std::vector< double >> mass2, std::string dev, double null, const double step, const double tolerance, const unsigned int timeout)
Definition at line 170 of file pyc.h.
          {
             std::vector<std::vector<double>> b1 = pyc::to_pmc(&bquark1);
             std::vector<std::vector<double>> b2 = pyc::to_pmc(&bquark2);
             std::vector<std::vector<double>> l1 = pyc::to_pmc(&lepton1);
             std::vector<std::vector<double>> l2 = pyc::to_pmc(&lepton2);
             std::vector<std::pair<neutrino*, neutrino*>> out;
             out = pyc::nusol::NuNu(&b1, &b2, &l1, &l2, &met_, &phi_, &mass1, &mass2, dev, null, step, tolerance, timeout);
             for (size_t x(0); x < out.size(); ++x){
                 neutrino* nu1 = std::get<0>(out[x]);
                 nu1 -> bquark = new particle_template(bquark1[nu1 -> b_idx]);
                 nu1 -> lepton = new particle_template(lepton1[nu1 -> l_idx]);
                 neutrino* nu2 = std::get<1>(out[x]);
                 nu2 -> bquark = new particle_template(bquark2[nu2 -> b_idx]);
                 nu2 -> lepton = new particle_template(lepton2[nu2 -> l_idx]);
             }
             return out;
         }
References main::dev, l1, NuNu(), main::out, pyc::to_pmc(), and main::x.
NuNu() [2/4]
std::vector< std::pair< neutrino *, neutrino * > > pyc::nusol::NuNu (std::vector< std::vector< double >> * pmc_b1, std::vector< std::vector< double >> * pmc_b2, std::vector< std::vector< double >> * pmc_l1, std::vector< std::vector< double >> * pmc_l2, std::vector< double > * met, std::vector< double > * phi, std::vector< std::vector< double >> * mass1, std::vector< std::vector< double >> * mass2, std::string dev, const double null, const double step, const double tolerance, const unsigned int timeout)
Definition at line 82 of file interface.cxx.
  {
     torch::Tensor b1   = pyc::tensorize(pmc_b1);
     torch::Tensor b2   = pyc::tensorize(pmc_b2);
     torch::Tensor l1   = pyc::tensorize(pmc_l1);
     torch::Tensor l2   = pyc::tensorize(pmc_l2);
     torch::Tensor m1   = pyc::tensorize(mass1);
     torch::Tensor m2   = pyc::tensorize(mass2);
     torch::Tensor met_ = pyc::tensorize(met).view({-1, 1});
     torch::Tensor phi_ = pyc::tensorize(phi).view({-1, 1});
     b1   = changedev(dev, &b1  );
     b2   = changedev(dev, &b2  );
     l1   = changedev(dev, &l1  );
     l2   = changedev(dev, &l2  );
     m1   = changedev(dev, &m1  );
     m2   = changedev(dev, &m2  );
     met_ = changedev(dev, &met_);
     phi_ = changedev(dev, &phi_);
     torch::Tensor metxy = torch::cat({pyc::transform::separate::Px(met_, phi_), pyc::transform::separate::Py(met_, phi_)}, {-1});
     torch::Dict<std::string, torch::Tensor> nus = pyc::nusol::NuNu(b1, b2, l1, l2, metxy, null, m1, m2, step, tolerance, timeout);
     torch::Tensor nu1 = nus.at("nu1").view({-1, 3});
     torch::Tensor nu2 = nus.at("nu2").view({-1, 3});
     torch::Tensor dis = nus.at("distances").view({-1});
     std::vector<double> dist;
     tensor_to_vector(&dis, &dist);
     std::vector<std::pair<neutrino*, neutrino*>> out;
     std::vector<neutrino*> nu1_ = construct_particle(&nu1, nullptr, nullptr, &dist);
     std::vector<neutrino*> nu2_ = construct_particle(&nu2, nullptr, nullptr, &dist);
     for (size_t x(0); x < nu1_.size(); ++x){out.push_back({nu1_[x], nu2_[x]});}
     return out;
 }
References changedev(), construct_particle(), main::dev, l1, rnn_model::m1, NuNu(), main::out, pyc::transform::separate::Px(), pyc::transform::separate::Py(), tensor_to_vector(), pyc::tensorize(), and main::x.
NuNu() [3/4]
torch::Dict< std::string, torch::Tensor > pyc::nusol::NuNu (torch::Tensor pmc_b1, torch::Tensor pmc_b2, torch::Tensor pmc_l1, torch::Tensor pmc_l2, torch::Tensor met_xy, double null, torch::Tensor mass1, torch::Tensor mass2, const double step = 1e-9, const double tolerance = 1e-6, const unsigned int timeout = 1000)
Definition at line 36 of file interface/nusol.cxx.
  {
     changedev(&pmc_b1);
     std::map<std::string, torch::Tensor> out;
     out = nusol_::NuNu(&pmc_b1, &pmc_b2, &pmc_l1, &pmc_l2, &met_xy, null, &mass1, &mass2, step, tolerance, timeout);
     return pyc::std_to_dict(&out);
 }
References changedev(), nusol_::NuNu(), main::out, and pyc::std_to_dict().
NuNu() [4/4]
torch::Dict< std::string, torch::Tensor > pyc::nusol::NuNu (torch::Tensor pmc_b1, torch::Tensor pmc_b2, torch::Tensor pmc_l1, torch::Tensor pmc_l2, torch::Tensor met_xy, torch::Tensor masses, double null = 10e-10, const double step = 1e-9, const double tolerance = 1e-6, const unsigned int timeout = 1000)
Definition at line 25 of file interface/nusol.cxx.
  {
     changedev(&pmc_b1);
     std::map<std::string, torch::Tensor> out;
     out = nusol_::NuNu(&pmc_b1, &pmc_b2, &pmc_l1, &pmc_l2, &met_xy, null, &masses, nullptr, step, tolerance, timeout);
     return pyc::std_to_dict(&out);
 }
References changedev(), main::masses, nusol_::NuNu(), main::out, and pyc::std_to_dict().
Referenced by NuNu(), and validation::reconstruction().