AnalysisG: zprime.figures Namespace Reference
zprime.figures Namespace Reference
Functions
def path (hist)
def zprime_mass_tops (ana)
def zprime_mass_children (ana)
def zprime_mass_truthjets (ana)
def zprime_mass_jets (ana)
def ZPrime (ana)
Variables
list colors = ["red", "green", "blue", "orange", "magenta", "cyan", "pink"]
Function Documentation
path()
def zprime.figures.path (hist)
Definition at line 11 of file mc16_matching/zprime/figures.py.
 def path(hist):
     hist.OutputDirectory = figure_path + "/zprime/" + mass_point
     default(hist)
     return hist
References main.default.
Referenced by zprime.figures.zprime_mass_children(), zprime.figures.zprime_mass_jets(), zprime.figures.zprime_mass_tops(), and zprime.figures.zprime_mass_truthjets().
ZPrime()
def zprime.figures.ZPrime (ana)
Definition at line 120 of file mc16_matching/zprime/figures.py.
 def ZPrime(ana):
     zprime_mass_tops(ana)
     zprime_mass_children(ana)
     zprime_mass_truthjets(ana)
     zprime_mass_jets(ana)
References zprime.figures.zprime_mass_children(), zprime.figures.zprime_mass_jets(), zprime.figures.zprime_mass_tops(), and zprime.figures.zprime_mass_truthjets().
Referenced by main.ExecuteStudy().
zprime_mass_children()
def zprime.figures.zprime_mass_children (ana)
Definition at line 42 of file mc16_matching/zprime/figures.py.
 def zprime_mass_children(ana):
     xp = iter(colors)
     hists = []
     for i in ana:
         th_ = TH1F()
         th_.Title = "Mass Point " + i
         th_.xData = ana[i].zprime_children
         th_.Color = next(xp)
         hists.append(th_)
     th = path(TH1F())
     th.Histograms = hists
     th.Title = "Invariant Mass Distribution of Multiple Target Resonance Mass-Points"
     th.xTitle = "Invariant Mass (GeV)"
     th.yTitle = r"Density (Arb.) / ($4$ GeV)"
     th.Style = "ATLAS"
     th.xStep = 100
     th.xBins = 300
     th.xMin = 0
     th.xMax = 1200
     th.Density = True
     th.Overflow = False
     th.Filename = "Figure.6.b"
     th.SaveFigure()
References zprime.figures.path().
Referenced by zprime.figures.ZPrime().
zprime_mass_jets()
def zprime.figures.zprime_mass_jets (ana)
Definition at line 94 of file mc16_matching/zprime/figures.py.
 def zprime_mass_jets(ana):
     xp = iter(colors)
     hists = []
     for i in ana:
         th_ = TH1F()
         th_.Title = "Mass Point " + i
         th_.xData = ana[i].zprime_jets
         th_.Color = next(xp)
         hists.append(th_)
     th = path(TH1F())
     th.Histograms = hists
     th.Title  = r"Invariant Mass Distribution of Multiple Target Resonance Mass-Points"
     th.xTitle = "Invariant Mass (GeV)"
     th.yTitle = r"Density (Arb.) / ($4$ GeV)"
     th.Style = "ATLAS"
     th.xStep = 100
     th.xBins = 300
     th.xMin = 0
     th.xMax = 1200
     th.Density = True
     th.Overflow = False
     th.Filename = "Figure.6.d"
     th.SaveFigure()
References zprime.figures.path().
Referenced by zprime.figures.ZPrime().
zprime_mass_tops()
def zprime.figures.zprime_mass_tops (ana)
Definition at line 16 of file mc16_matching/zprime/figures.py.
 def zprime_mass_tops(ana):
     xp = iter(colors)
     hists = []
     for i in ana:
         th_ = TH1F()
         th_.Title = "Mass Point " + i
         th_.xData = ana[i].zprime_truth_tops
         th_.Color = next(xp)
         hists.append(th_)
     th = path(TH1F())
     th.Histograms = hists
     th.Title = r"Invariant Mass Distribution of Multiple Target Resonance Mass-Points"
     th.xTitle = r"Invariant Mass (GeV)"
     th.yTitle = r"Density (Arb.) / ($4$ GeV)"
     th.Style = "ATLAS"
     th.xStep = 100
     th.xBins = 300
     th.xMin = 0
     th.xMax = 1200
     th.Density = True
     th.Overflow = False
     th.Filename = "Figure.6.a"
     th.SaveFigure()
References zprime.figures.path().
Referenced by zprime.figures.ZPrime().
zprime_mass_truthjets()
def zprime.figures.zprime_mass_truthjets (ana)
Definition at line 68 of file mc16_matching/zprime/figures.py.
 def zprime_mass_truthjets(ana):
     xp = iter(colors)
     hists = []
     for i in ana:
         th_ = TH1F()
         th_.Title = "Mass Point " + i
         th_.xData = ana[i].zprime_truthjets
         th_.Color = next(xp)
         hists.append(th_)
     th = path(TH1F())
     th.Histograms = hists
     th.Title = r"Invariant Mass Distribution of Multiple Target Resonance Mass-Points"
     th.xTitle = r"Invariant Mass (GeV)"
     th.yTitle = r"Density (Arb.) / ($4$ GeV)"
     th.Style = "ATLAS"
     th.xStep = 100
     th.xBins = 300
     th.xMin = 0
     th.xMax = 1200
     th.Density = True
     th.Overflow = False
     th.Filename = "Figure.6.c"
     th.SaveFigure()
References zprime.figures.path().
Referenced by zprime.figures.ZPrime().
Variable Documentation
colors
list zprime.figures.colors = ["red", "green", "blue", "orange", "magenta", "cyan", "pink"]
Definition at line 10 of file mc16_matching/zprime/figures.py.