AnalysisG: pyc::physics::polar::combined Namespace Reference
pyc::physics::polar::combined Namespace Reference
Functions
torch::Tensor P2 (torch::Tensor pmu)
torch::Tensor P (torch::Tensor pmu)
torch::Tensor Beta2 (torch::Tensor pmu)
torch::Tensor Beta (torch::Tensor pmu)
torch::Tensor M2 (torch::Tensor pmu)
torch::Tensor M (torch::Tensor pmu)
torch::Tensor Mt2 (torch::Tensor pmu)
torch::Tensor Mt (torch::Tensor pmu)
torch::Tensor Theta (torch::Tensor pmu)
torch::Tensor DeltaR (torch::Tensor pmu1, torch::Tensor pmu2)
Function Documentation
Beta()
torch::Tensor pyc::physics::polar::combined::Beta (torch::Tensor pmu)
Definition at line 101 of file pyc/interface/physics.cxx.
{
     changedev(&pmu);
     torch::Tensor pmc = transform_::PxPyPzE(&pmu);
     return physics_::Beta(&pmc);
 }
References physics_::Beta(), changedev(), pmc, pmu(), and transform_::PxPyPzE().
Beta2()
torch::Tensor pyc::physics::polar::combined::Beta2 (torch::Tensor pmu)
Definition at line 77 of file pyc/interface/physics.cxx.
{
     changedev(&pmu);
     torch::Tensor pmc = transform_::PxPyPzE(&pmu);
     return physics_::Beta2(&pmc);
 }
References physics_::Beta2(), changedev(), pmc, pmu(), and transform_::PxPyPzE().
DeltaR()
torch::Tensor pyc::physics::polar::combined::DeltaR (torch::Tensor pmu1, torch::Tensor pmu2)
Definition at line 249 of file pyc/interface/physics.cxx.
{
     changedev(&pmu1);
     return physics_::DeltaR(&pmu1, &pmu2);
 }
References changedev(), and physics_::DeltaR().
M()
torch::Tensor pyc::physics::polar::combined::M (torch::Tensor pmu)
Definition at line 148 of file pyc/interface/physics.cxx.
{
     changedev(&pmu);
     torch::Tensor pmc = transform_::PxPyPzE(&pmu);
     return physics_::M(&pmc);
 }
References changedev(), physics_::M(), pmc, pmu(), and transform_::PxPyPzE().
M2()
torch::Tensor pyc::physics::polar::combined::M2 (torch::Tensor pmu)
Definition at line 125 of file pyc/interface/physics.cxx.
{
     changedev(&pmu);
     torch::Tensor pmc = transform_::PxPyPzE(&pmu);
     return physics_::M2(&pmc);
 }
References changedev(), physics_::M2(), pmc, pmu(), and transform_::PxPyPzE().
Mt()
torch::Tensor pyc::physics::polar::combined::Mt (torch::Tensor pmu)
Definition at line 194 of file pyc/interface/physics.cxx.
{
     changedev(&pmu);
     torch::Tensor pmc = transform_::PxPyPzE(&pmu);
     return physics_::Mt(&pmc);
 }
References changedev(), physics_::Mt(), pmc, pmu(), and transform_::PxPyPzE().
Mt2()
torch::Tensor pyc::physics::polar::combined::Mt2 (torch::Tensor pmu)
Definition at line 172 of file pyc/interface/physics.cxx.
{
     changedev(&pmu);
     torch::Tensor pmc = transform_::PxPyPzE(&pmu);
     return physics_::Mt2(&pmc);
 }
References changedev(), physics_::Mt2(), pmc, pmu(), and transform_::PxPyPzE().
P()
torch::Tensor pyc::physics::polar::combined::P (torch::Tensor pmu)
Definition at line 53 of file pyc/interface/physics.cxx.
{
     changedev(&pmu);
     torch::Tensor pmc = transform_::PxPyPz(&pmu);
     return physics_::P(&pmc);
 }
References changedev(), physics_::P(), pmc, pmu(), and transform_::PxPyPz().
P2()
torch::Tensor pyc::physics::polar::combined::P2 (torch::Tensor pmu)
Definition at line 29 of file pyc/interface/physics.cxx.
{
     changedev(&pmu);
     torch::Tensor pmc = transform_::PxPyPz(&pmu);
     return physics_::P2(&pmc);
 }
References changedev(), physics_::P2(), pmc, pmu(), and transform_::PxPyPz().
Theta()
torch::Tensor pyc::physics::polar::combined::Theta (torch::Tensor pmu)
Definition at line 217 of file pyc/interface/physics.cxx.
{
     changedev(&pmu);
     torch::Tensor pmc = transform_::PxPyPz(&pmu);
     return physics_::Theta(&pmc);
 }
References changedev(), pmc, pmu(), transform_::PxPyPz(), and physics_::Theta().