AnalysisG: operators_ Namespace Reference
operators_ Namespace Reference
< Includes PyTorch C++ headers for tensor operations.
Functions
torch::Tensor Dot (torch::Tensor *v1, torch::Tensor *v2)
Computes the dot product of two vectors.
torch::Tensor Cross (torch::Tensor *v1, torch::Tensor *v2)
Computes the cross product of two vectors.
torch::Tensor CosTheta (torch::Tensor *v1, torch::Tensor *v2)
Computes the cosine of the angle between two vectors.
torch::Tensor SinTheta (torch::Tensor *v1, torch::Tensor *v2)
Computes the sine of the angle between two vectors.
torch::Tensor Rx (torch::Tensor *angle)
Computes the rotation matrix around the X-axis.
torch::Tensor Ry (torch::Tensor *angle)
Computes the rotation matrix around the Y-axis.
torch::Tensor Rz (torch::Tensor *angle)
Computes the rotation matrix around the Z-axis.
torch::Tensor CoFactors (torch::Tensor *matrix)
Computes the cofactor matrix of a given matrix.
torch::Tensor Determinant (torch::Tensor *matrix)
Computes the determinant of a matrix.
torch::Tensor Inverse (torch::Tensor *matrix)
Computes the inverse of a matrix.
Detailed Description
< Includes PyTorch C++ headers for tensor operations.
Namespace for operator functions.
Function Documentation
CoFactors()
torch::Tensor operators_::CoFactors (torch::Tensor * matrix)
Computes the cofactor matrix of a given matrix.
Parameters
matrix Input tensor representing the matrix.
Returns
A tensor containing the cofactor matrix.
Definition at line 65 of file operators/operators.cxx.
{
     int _x[] = {1, 1, 2, 2, 0, 0, 2, 2, 0, 0, 1, 1};
     int _y[] = {1, 2, 1, 2, 0, 2, 0, 2, 0, 1, 0, 1};
     std::vector<torch::Tensor> out;
     for (int i(0); i < 3; ++i){
         for (int j(0); j < 3; ++j){
             int idx = 4*i;
             int idy = 4*j;
             torch::Tensor a = matrix -> index({torch::indexing::Slice(), _x[idx  ], _y[idy  ]}).view({-1, 1});
             torch::Tensor b = matrix -> index({torch::indexing::Slice(), _x[idx+1], _y[idy+1]}).view({-1, 1});
             torch::Tensor c = matrix -> index({torch::indexing::Slice(), _x[idx+2], _y[idy+2]}).view({-1, 1});
             torch::Tensor d = matrix -> index({torch::indexing::Slice(), _x[idx+3], _y[idy+3]}).view({-1, 1});
             torch::Tensor minor = a*d - b*c;
             minor = minor*( 1 - ((i+j)%2)*2 );
             out.push_back(minor);
         }
     }
     return torch::cat(out, -1).view({-1, 3, 3});
 }
References b, c, d, and main::out.
Referenced by pyc::operators::CoFactors(), and nusol_::Intersection().
CosTheta()
torch::Tensor operators_::CosTheta (torch::Tensor * v1, torch::Tensor * v2)
Computes the cosine of the angle between two vectors.
Parameters
v1 Input tensor representing the first vector.
v2 Input tensor representing the second vector.
Returns
A tensor containing the cosine of the angle.
Definition at line 9 of file operators/operators.cxx.
{
     torch::Tensor v1_2 = ((*v1)*(*v1)).sum(-1);
     torch::Tensor v2_2 = ((*v2)*(*v2)).sum(-1);
     torch::Tensor dot  = ((*v1)*(*v2)).sum(-1);
     return (dot/( torch::sqrt( (v1_2 * v2_2) ))).view({-1, 1});
 }
Referenced by nusol_::BaseMatrix(), and pyc::operators::CosTheta().
Cross()
torch::Tensor operators_::Cross (torch::Tensor * v1, torch::Tensor * v2)
Computes the cross product of two vectors.
Parameters
v1 Input tensor representing the first vector.
v2 Input tensor representing the second vector.
Returns
A tensor containing the cross product result.
Referenced by pyc::operators::Cross().
Determinant()
torch::Tensor operators_::Determinant (torch::Tensor * matrix)
Computes the determinant of a matrix.
Parameters
matrix Input tensor representing the matrix.
Returns
A tensor containing the determinant value.
Definition at line 86 of file operators/operators.cxx.
 { return torch::det(*matrix); }
Referenced by pyc::operators::Determinant(), and nusol_::Intersection().
Dot()
torch::Tensor operators_::Dot (torch::Tensor * v1, torch::Tensor * v2)
Computes the dot product of two vectors.
Parameters
v1 Input tensor representing the first vector.
v2 Input tensor representing the second vector.
Returns
A tensor containing the dot product result.
Definition at line 4 of file operators/operators.cxx.
{
     int sx = v2 -> size({-1});
     return v1 -> matmul(v2 -> view({-1, sx, sx}));
 }
Referenced by pyc::operators::Dot().
Inverse()
torch::Tensor operators_::Inverse (torch::Tensor * matrix)
Computes the inverse of a matrix.
Parameters
matrix Input tensor representing the matrix.
Returns
A tensor containing the inverse matrix.
Definition at line 87 of file operators/operators.cxx.
 { return torch::inverse(*matrix); }
Referenced by _N(), nusol_::Intersection(), and pyc::operators::Inverse().
Rx()
torch::Tensor operators_::Rx (torch::Tensor * angle)
Computes the rotation matrix around the X-axis.
Parameters
angle Input tensor representing the rotation angle.
Returns
A tensor containing the rotation matrix.
Definition at line 23 of file operators/operators.cxx.
{
     torch::Tensor agl = angle -> view({-1, 1});
     torch::Tensor cos = torch::cos(agl);
     torch::Tensor sin = torch::sin(agl);
     torch::Tensor t0 = torch::zeros_like(agl);
     torch::Tensor t1 = torch::ones_like(agl);
     return torch::cat({t1,  t0,   t0,
                        t0, cos, -sin,
                        t0, sin,  cos
     }, -1).view({-1, 3, 3});
 }
Referenced by Rotation(), and pyc::operators::Rx().
Ry()
torch::Tensor operators_::Ry (torch::Tensor * angle)
Computes the rotation matrix around the Y-axis.
Parameters
angle Input tensor representing the rotation angle.
Returns
A tensor containing the rotation matrix.
Definition at line 37 of file operators/operators.cxx.
{
     torch::Tensor agl = angle -> view({-1, 1});
     torch::Tensor cos = torch::cos(agl);
     torch::Tensor sin = torch::sin(agl);
     torch::Tensor t0 = torch::zeros_like(agl);
     torch::Tensor t1 = torch::ones_like(agl);
     return torch::cat({cos, t0, sin,
                         t0, t1,  t0,
                       -sin, t0, cos
     }, -1).view({-1, 3, 3});
 }
Referenced by Rotation(), and pyc::operators::Ry().
Rz()
torch::Tensor operators_::Rz (torch::Tensor * angle)
Computes the rotation matrix around the Z-axis.
Parameters
angle Input tensor representing the rotation angle.
Returns
A tensor containing the rotation matrix.
Definition at line 51 of file operators/operators.cxx.
{
     torch::Tensor agl = angle -> view({-1, 1});
     torch::Tensor cos = torch::cos(agl);
     torch::Tensor sin = torch::sin(agl);
     torch::Tensor t0 = torch::zeros_like(agl);
     torch::Tensor t1 = torch::ones_like(agl);
     return torch::cat({cos, -sin, t0,
                        sin,  cos, t0,
                        t0 ,   t0, t1
     }, -1).view({-1, 3, 3});
 }
Referenced by _xNu(), Rotation(), and pyc::operators::Rz().
SinTheta()
torch::Tensor operators_::SinTheta (torch::Tensor * v1, torch::Tensor * v2)
Computes the sine of the angle between two vectors.
Parameters
v1 Input tensor representing the first vector.
v2 Input tensor representing the second vector.
Returns
A tensor containing the sine of the angle.
Definition at line 16 of file operators/operators.cxx.
{
     torch::Tensor v1_2 = ((*v1)*(*v1)).sum(-1);
     torch::Tensor v2_2 = ((*v2)*(*v2)).sum(-1);
     torch::Tensor dot2  = torch::pow( ((*v1)*(*v2)).sum(-1) , 2);
     return torch::sqrt(1 - dot2/(v1_2*v2_2)).view({-1, 1});
 }
Referenced by nusol_::BaseMatrix(), and pyc::operators::SinTheta().