AnalysisG: pyc::graph::cartesian Namespace Reference
pyc::graph::cartesian Namespace Reference
Functions
torch::Dict< std::string, torch::Tensor > edge_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor pmc)
torch::Dict< std::string, torch::Tensor > node_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor pmc)
torch::Dict< std::string, torch::Tensor > edge_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor px, torch::Tensor py, torch::Tensor pz, torch::Tensor e)
torch::Dict< std::string, torch::Tensor > node_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor px, torch::Tensor py, torch::Tensor pz, torch::Tensor e)
Function Documentation
edge_aggregation() [1/2]
torch::Dict< std::string, torch::Tensor > pyc::graph::cartesian::edge_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor pmc)
Definition at line 144 of file interface/graph.cxx.
  {
     changedev(&edge_index);
     std::map<std::string, torch::Tensor> out;
     out = graph_::edge_aggregation(&edge_index, &prediction, &pmc);
     return pyc::std_to_dict(&out);
 }
References changedev(), graph_::edge_aggregation(), edge_index, main::out, pmc, and pyc::std_to_dict().
edge_aggregation() [2/2]
torch::Dict< std::string, torch::Tensor > pyc::graph::cartesian::edge_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor px, torch::Tensor py, torch::Tensor pz, torch::Tensor e)
Definition at line 162 of file interface/graph.cxx.
  {
     changedev(&edge_index);
     std::map<std::string, torch::Tensor> out;
     torch::Tensor pmc = torch::cat({px, py, pz, e}, {-1});
     out = graph_::edge_aggregation(&edge_index, &prediction, &pmc);
     return pyc::std_to_dict(&out);
 }
References changedev(), test_particles::e, graph_::edge_aggregation(), edge_index, main::out, pmc, and pyc::std_to_dict().
node_aggregation() [1/2]
torch::Dict< std::string, torch::Tensor > pyc::graph::cartesian::node_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor pmc)
Definition at line 153 of file interface/graph.cxx.
  {
     changedev(&edge_index);
     std::map<std::string, torch::Tensor> out;
     out = graph_::node_aggregation(&edge_index, &prediction, &pmc);
     return pyc::std_to_dict(&out);
 }
References changedev(), edge_index, graph_::node_aggregation(), main::out, pmc, and pyc::std_to_dict().
node_aggregation() [2/2]
torch::Dict< std::string, torch::Tensor > pyc::graph::cartesian::node_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor px, torch::Tensor py, torch::Tensor pz, torch::Tensor e)
Definition at line 173 of file interface/graph.cxx.
  {
     changedev(&edge_index);
     std::map<std::string, torch::Tensor> out;
     torch::Tensor pmc = torch::cat({px, py, pz, e}, {-1});
     out = graph_::node_aggregation(&edge_index, &prediction, &pmc);
     return pyc::std_to_dict(&out);
 }
References changedev(), test_particles::e, edge_index, graph_::node_aggregation(), main::out, pmc, and pyc::std_to_dict().