AnalysisG: pyc::physics::cartesian::separate Namespace Reference
pyc::physics::cartesian::separate Namespace Reference
Functions
torch::Tensor P2 (torch::Tensor px, torch::Tensor py, torch::Tensor pz)
torch::Tensor P (torch::Tensor px, torch::Tensor py, torch::Tensor pz)
torch::Tensor Beta2 (torch::Tensor px, torch::Tensor py, torch::Tensor pz, torch::Tensor e)
torch::Tensor Beta (torch::Tensor px, torch::Tensor py, torch::Tensor pz, torch::Tensor e)
torch::Tensor M2 (torch::Tensor px, torch::Tensor py, torch::Tensor pz, torch::Tensor e)
torch::Tensor M (torch::Tensor px, torch::Tensor py, torch::Tensor pz, torch::Tensor e)
torch::Tensor Mt2 (torch::Tensor pz, torch::Tensor e)
torch::Tensor Mt (torch::Tensor pz, torch::Tensor e)
torch::Tensor Theta (torch::Tensor px, torch::Tensor py, torch::Tensor pz)
torch::Tensor DeltaR (torch::Tensor px1, torch::Tensor px2, torch::Tensor py1, torch::Tensor py2, torch::Tensor pz1, torch::Tensor pz2)
Function Documentation
Beta()
torch::Tensor pyc::physics::cartesian::separate::Beta (torch::Tensor px, torch::Tensor py, torch::Tensor pz, torch::Tensor e)
Definition at line 84 of file pyc/interface/physics.cxx.
{
     changedev(&px);
     return physics_::Beta(&px, &py, &pz, &e);
 }
References physics_::Beta(), changedev(), and test_particles::e.
Beta2()
torch::Tensor pyc::physics::cartesian::separate::Beta2 (torch::Tensor px, torch::Tensor py, torch::Tensor pz, torch::Tensor e)
Definition at line 60 of file pyc/interface/physics.cxx.
{
     changedev(&px);
     return physics_::Beta2(&px, &py, &pz, &e);
 }
References physics_::Beta2(), changedev(), and test_particles::e.
DeltaR()
torch::Tensor pyc::physics::cartesian::separate::DeltaR (torch::Tensor px1, torch::Tensor px2, torch::Tensor py1, torch::Tensor py2, torch::Tensor pz1, torch::Tensor pz2)
Definition at line 223 of file pyc/interface/physics.cxx.
  {
     changedev(&px1);
     torch::Tensor pmu1 = transform_::PtEtaPhi(&px1, &py1, &pz1);
     torch::Tensor pmu2 = transform_::PtEtaPhi(&px2, &py2, &pz2);
     return physics_::DeltaR(&pmu1, &pmu2);
 }
References changedev(), physics_::DeltaR(), and transform_::PtEtaPhi().
Referenced by bsm_4tops::CompileEvent(), exp_mc20::CompileEvent(), topkinematics::strategy(), and childrenkinematics::strategy().
M()
torch::Tensor pyc::physics::cartesian::separate::M (torch::Tensor px, torch::Tensor py, torch::Tensor pz, torch::Tensor e)
Definition at line 132 of file pyc/interface/physics.cxx.
{
     changedev(&px);
     return physics_::M(&px, &py, &pz, &e);
 }
References changedev(), test_particles::e, and physics_::M().
Referenced by main(), and nusol_::Nu().
M2()
torch::Tensor pyc::physics::cartesian::separate::M2 (torch::Tensor px, torch::Tensor py, torch::Tensor pz, torch::Tensor e)
Definition at line 108 of file pyc/interface/physics.cxx.
{
     changedev(&px);
     return physics_::M2(&px, &py, &pz, &e);
 }
References changedev(), test_particles::e, and physics_::M2().
Mt()
torch::Tensor pyc::physics::cartesian::separate::Mt (torch::Tensor pz, torch::Tensor e)
Definition at line 178 of file pyc/interface/physics.cxx.
{
     changedev(&pz);
     return physics_::Mt(&pz, &e);
 }
References changedev(), test_particles::e, and physics_::Mt().
Mt2()
torch::Tensor pyc::physics::cartesian::separate::Mt2 (torch::Tensor pz, torch::Tensor e)
Definition at line 155 of file pyc/interface/physics.cxx.
{
     changedev(&pz);
     return physics_::Mt2(&pz, &e);
 }
References changedev(), test_particles::e, and physics_::Mt2().
P()
torch::Tensor pyc::physics::cartesian::separate::P (torch::Tensor px, torch::Tensor py, torch::Tensor pz)
Definition at line 36 of file pyc/interface/physics.cxx.
{
     changedev(&pz);
     return physics_::P(&px, &py, &pz);
 }
References changedev(), and physics_::P().
P2()
torch::Tensor pyc::physics::cartesian::separate::P2 (torch::Tensor px, torch::Tensor py, torch::Tensor pz)
Definition at line 13 of file pyc/interface/physics.cxx.
{
     changedev(&pz);
     return physics_::P2(&px, &py, &pz);
 }
References changedev(), and physics_::P2().
Theta()
torch::Tensor pyc::physics::cartesian::separate::Theta (torch::Tensor px, torch::Tensor py, torch::Tensor pz)
Definition at line 200 of file pyc/interface/physics.cxx.
{
     changedev(&px);
     return physics_::Theta(&px, &py, &pz);
 }
References changedev(), and physics_::Theta().