AnalysisG: pyc::operators Namespace Reference
pyc::operators Namespace Reference
Functions
torch::Tensor Dot (torch::Tensor v1, torch::Tensor v2)
torch::Tensor CosTheta (torch::Tensor v1, torch::Tensor v2)
torch::Tensor SinTheta (torch::Tensor v1, torch::Tensor v2)
torch::Tensor Rx (torch::Tensor angle)
torch::Tensor Ry (torch::Tensor angle)
torch::Tensor Rz (torch::Tensor angle)
torch::Tensor RT (torch::Tensor pmc_b, torch::Tensor pmc_mu)
torch::Tensor CoFactors (torch::Tensor matrix)
torch::Tensor Determinant (torch::Tensor matrix)
std::tuple< torch::Tensor, torch::Tensor > Inverse (torch::Tensor matrix)
std::tuple< torch::Tensor, torch::Tensor > Eigenvalue (torch::Tensor matrix)
torch::Tensor Cross (torch::Tensor mat1, torch::Tensor mat2)
Function Documentation
CoFactors()
torch::Tensor pyc::operators::CoFactors (torch::Tensor matrix)
Definition at line 51 of file interface/operators.cxx.
References changedev(), and operators_::CoFactors().
CosTheta()
torch::Tensor pyc::operators::CosTheta (torch::Tensor v1, torch::Tensor v2)
Definition at line 18 of file interface/operators.cxx.
References changedev(), and operators_::CosTheta().
Cross()
torch::Tensor pyc::operators::Cross (torch::Tensor mat1, torch::Tensor mat2)
Definition at line 66 of file interface/operators.cxx.
References changedev(), and operators_::Cross().
Determinant()
torch::Tensor pyc::operators::Determinant (torch::Tensor matrix)
Definition at line 56 of file interface/operators.cxx.
References changedev(), and operators_::Determinant().
Dot()
torch::Tensor pyc::operators::Dot (torch::Tensor v1, torch::Tensor v2)
Definition at line 13 of file interface/operators.cxx.
References changedev(), and operators_::Dot().
Eigenvalue()
std::tuple< torch::Tensor, torch::Tensor > pyc::operators::Eigenvalue (torch::Tensor matrix)
Definition at line 71 of file interface/operators.cxx.
References changedev().
Inverse()
std::tuple< torch::Tensor, torch::Tensor > pyc::operators::Inverse (torch::Tensor matrix)
Definition at line 61 of file interface/operators.cxx.
References changedev(), and operators_::Inverse().
RT()
torch::Tensor pyc::operators::RT (torch::Tensor pmc_b, torch::Tensor pmc_mu)
Definition at line 44 of file interface/operators.cxx.
References changedev(), phi, pyc::transform::combined::Phi(), and physics_::Theta().
Rx()
torch::Tensor pyc::operators::Rx (torch::Tensor angle)
Definition at line 28 of file interface/operators.cxx.
References changedev(), and operators_::Rx().
Ry()
torch::Tensor pyc::operators::Ry (torch::Tensor angle)
Definition at line 33 of file interface/operators.cxx.
References changedev(), and operators_::Ry().
Rz()
torch::Tensor pyc::operators::Rz (torch::Tensor angle)
Definition at line 38 of file interface/operators.cxx.
References changedev(), and operators_::Rz().
SinTheta()
torch::Tensor pyc::operators::SinTheta (torch::Tensor v1, torch::Tensor v2)
Definition at line 23 of file interface/operators.cxx.
References changedev(), and operators_::SinTheta().