AnalysisG: pyc Namespace Reference
pyc Namespace Reference
Namespaces
graph
nusol
operators
physics
transform
Functions
torch::Dict< std::string, torch::Tensor > std_to_dict (std::map< std::string, torch::Tensor > *inpt)
torch::Dict< std::string, torch::Tensor > std_to_dict (std::map< std::string, torch::Tensor > inpt)
torch::Tensor tensorize (std::vector< std::vector< double >> *inpt)
torch::Tensor tensorize (std::vector< std::vector< long >> *inpt)
torch::Tensor tensorize (std::vector< double > *inpt)
torch::Tensor tensorize (std::vector< long > *inpt)
template<typename g >
std::vector< double > as_pmc (g *p)
template<typename g >
std::vector< std::vector< double > > to_pmc (std::vector< g * > *p)
Function Documentation
as_pmc()
template<typename g > std::vector<double> pyc::as_pmc (g * p)
Definition at line 31 of file pyc.h.
 {return {p -> px, p -> py, p -> pz, p -> e};}
References test_particles::e, and rnn_model::p.
Referenced by pyc::nusol::combinatorial(), and to_pmc().
std_to_dict() [1/2]
torch::Dict< std::string, torch::Tensor > pyc::std_to_dict (std::map< std::string, torch::Tensor > * inpt)
Definition at line 20 of file interface.cxx.
{
     torch::Dict<std::string, torch::Tensor> out;
     std::map<std::string, torch::Tensor>::iterator itr = inpt -> begin();
     for (; itr != inpt -> end(); ++itr){out.insert(itr -> first, itr -> second);}
     return out;
 }
References end(), and main::out.
Referenced by pyc::nusol::BaseMatrix(), pyc::nusol::combinatorial(), pyc::graph::edge_aggregation(), pyc::graph::polar::edge_aggregation(), pyc::graph::cartesian::edge_aggregation(), pyc::graph::node_aggregation(), pyc::graph::polar::node_aggregation(), pyc::graph::cartesian::node_aggregation(), pyc::nusol::Nu(), pyc::nusol::NuNu(), pyc::graph::PageRank(), pyc::graph::PageRankReconstruction(), std_to_dict(), and pyc::graph::unique_aggregation().
std_to_dict() [2/2]
torch::Dict< std::string, torch::Tensor > pyc::std_to_dict (std::map< std::string, torch::Tensor > inpt)
Definition at line 27 of file interface.cxx.
{
     return pyc::std_to_dict(&inpt);
 }
References std_to_dict().
tensorize() [1/4]
torch::Tensor pyc::tensorize (std::vector< double > * inpt)
Definition at line 31 of file interface.cxx.
{
     torch::TensorOptions ops = torch::TensorOptions(torch::kCPU);
     return build_tensor(inpt, torch::kDouble, double(), &ops).view({-1, int(inpt -> size())});
 }
tensorize() [2/4]
torch::Tensor pyc::tensorize (std::vector< long > * inpt)
Definition at line 36 of file interface.cxx.
{
     torch::TensorOptions ops = torch::TensorOptions(torch::kCPU);
     return build_tensor(inpt, torch::kLong, long(), &ops).view({-1, int(inpt -> size())});
 }
tensorize() [3/4]
torch::Tensor pyc::tensorize (std::vector< std::vector< double >> * inpt)
Definition at line 41 of file interface.cxx.
{
     std::vector<torch::Tensor> mrg;
     for (size_t x(0); x < inpt -> size(); ++x){mrg.push_back(pyc::tensorize(&(*inpt)[x]));}
     return torch::cat(mrg, {0});
 }
References helper::mrg(), and main::x.
Referenced by pyc::nusol::combinatorial(), pyc::nusol::NuNu(), and tensorize().
tensorize() [4/4]
torch::Tensor pyc::tensorize (std::vector< std::vector< long >> * inpt)
Definition at line 47 of file interface.cxx.
{
     std::vector<torch::Tensor> mrg;
     for (size_t x(0); x < inpt -> size(); ++x){mrg.push_back(pyc::tensorize(&(*inpt)[x]));}
     return torch::cat(mrg, {0});
 }
References helper::mrg(), tensorize(), and main::x.
to_pmc()
template<typename g > std::vector<std::vector<double> > pyc::to_pmc (std::vector< g * > * p)
Definition at line 34 of file pyc.h.
{
         std::vector<std::vector<double>> atx;
         for (size_t x(0); x < p -> size(); ++x){atx.push_back(pyc::as_pmc((*p)[x]));}
         return atx;
     }
References as_pmc(), rnn_model::p, and main::x.
Referenced by pyc::nusol::NuNu().