AnalysisG: test_generator Namespace Reference
test_generator Namespace Reference
Variables
string root1 = "./samples/dilepton/*"
x = BSM4Tops()
tt = GraphJets()
PreSelection
m = Grift()
o_edge
o_graph
i_node
i_graph
device
op = OptimizerConfig()
Optimizer
lr
ana = Analysis()
PreTagEvents
TrainingDataset
kFolds
kFold
Targets
ContinueTraining
GraphCache
Evaluation
Validation
DebugMode
Epochs
MaxRange
TrainSize
Threads
Variable Documentation
ana
test_generator.ana = Analysis()
Definition at line 32 of file test_generator.py.
ContinueTraining
test_generator.ContinueTraining
Definition at line 44 of file test_generator.py.
DebugMode
test_generator.DebugMode
Definition at line 48 of file test_generator.py.
device
test_generator.device
Definition at line 26 of file test_generator.py.
Epochs
test_generator.Epochs
Definition at line 49 of file test_generator.py.
Evaluation
test_generator.Evaluation
Definition at line 46 of file test_generator.py.
GraphCache
test_generator.GraphCache
Definition at line 45 of file test_generator.py.
i_graph
test_generator.i_graph
Definition at line 25 of file test_generator.py.
i_node
test_generator.i_node
Definition at line 24 of file test_generator.py.
kFold
test_generator.kFold
Definition at line 42 of file test_generator.py.
kFolds
test_generator.kFolds
Definition at line 41 of file test_generator.py.
lr
test_generator.lr
Definition at line 30 of file test_generator.py.
m
test_generator.m = Grift()
Definition at line 19 of file test_generator.py.
MaxRange
test_generator.MaxRange
Definition at line 50 of file test_generator.py.
o_edge
test_generator.o_edge
Definition at line 21 of file test_generator.py.
o_graph
test_generator.o_graph
Definition at line 22 of file test_generator.py.
op
test_generator.op = OptimizerConfig()
Definition at line 28 of file test_generator.py.
Referenced by analysis.add_model(), nusol_.BaseMatrix(), dataloader.build_batch(), lossfx.build_optimizer(), dataloader.datatransfer(), graph_.edge_aggregation(), nusol_.Intersection(), nusol_.NuNu(), Pi_2(), Shape(), Sigma(), lossfx.to(), and graph_t.transfer_to_device().
Optimizer
test_generator.Optimizer
Definition at line 29 of file test_generator.py.
PreSelection
test_generator.PreSelection
Definition at line 15 of file test_generator.py.
Referenced by container.compile().
PreTagEvents
test_generator.PreTagEvents
Definition at line 33 of file test_generator.py.
root1
string test_generator.root1 = "./samples/dilepton/*"
Definition at line 8 of file test_generator.py.
Targets
test_generator.Targets
Definition at line 43 of file test_generator.py.
Threads
test_generator.Threads
Definition at line 52 of file test_generator.py.
TrainingDataset
test_generator.TrainingDataset
Definition at line 36 of file test_generator.py.
TrainSize
test_generator.TrainSize
Definition at line 51 of file test_generator.py.
tt
test_generator.tt = GraphJets()
Definition at line 14 of file test_generator.py.
Validation
test_generator.Validation
Definition at line 47 of file test_generator.py.
x
test_generator.x = BSM4Tops()
Definition at line 11 of file test_generator.py.