AnalysisG: physics_ Namespace Reference
physics_ Namespace Reference
< Includes PyTorch C++ headers for tensor operations.
Functions
torch::Tensor P2 (torch::Tensor *px, torch::Tensor *py, torch::Tensor *pz)
Computes the square of the momentum magnitude.
torch::Tensor P2 (torch::Tensor *pmc)
Computes the square of the momentum magnitude from a momentum tensor.
torch::Tensor P (torch::Tensor *px, torch::Tensor *py, torch::Tensor *pz)
Computes the momentum magnitude.
torch::Tensor P (torch::Tensor *pmc)
Computes the momentum magnitude from a momentum tensor.
torch::Tensor Beta2 (torch::Tensor *px, torch::Tensor *py, torch::Tensor *pz, torch::Tensor *e)
Computes the square of the beta factor.
torch::Tensor Beta2 (torch::Tensor *pmc)
Computes the square of the beta factor from a momentum tensor.
torch::Tensor Beta (torch::Tensor *px, torch::Tensor *py, torch::Tensor *pz, torch::Tensor *e)
Computes the beta factor.
torch::Tensor Beta (torch::Tensor *pmc)
Computes the beta factor from a momentum tensor.
torch::Tensor M2 (torch::Tensor *px, torch::Tensor *py, torch::Tensor *pz, torch::Tensor *e)
Computes the square of the invariant mass.
torch::Tensor M2 (torch::Tensor *pmc)
Computes the square of the invariant mass from a momentum tensor.
torch::Tensor M (torch::Tensor *px, torch::Tensor *py, torch::Tensor *pz, torch::Tensor *e)
Computes the invariant mass.
torch::Tensor M (torch::Tensor *pmc)
Computes the invariant mass from a momentum tensor.
torch::Tensor Mt2 (torch::Tensor *pz, torch::Tensor *e)
Computes the square of the transverse mass.
torch::Tensor Mt2 (torch::Tensor *pmc)
Computes the square of the transverse mass from a momentum tensor.
torch::Tensor Mt (torch::Tensor *pz, torch::Tensor *e)
Computes the transverse mass.
torch::Tensor Mt (torch::Tensor *pmc)
Computes the transverse mass from a momentum tensor.
torch::Tensor Theta (torch::Tensor *pmc)
Computes the polar angle theta.
torch::Tensor Theta (torch::Tensor *px, torch::Tensor *py, torch::Tensor *pz)
Computes the polar angle theta.
torch::Tensor DeltaR (torch::Tensor *pmu1, torch::Tensor *pmu2)
Computes the delta R separation between two particles.
torch::Tensor DeltaR (torch::Tensor *eta1, torch::Tensor *eta2, torch::Tensor *phi1, torch::Tensor *phi2)
Computes the delta R separation between two particles.
Detailed Description
< Includes PyTorch C++ headers for tensor operations.
Namespace for physics-related functions.
Function Documentation
Beta() [1/2]
torch::Tensor physics_::Beta (torch::Tensor * pmc)
Computes the beta factor from a momentum tensor.
Parameters
pmc Input tensor for the momentum components.
Returns
A tensor containing the beta factor.
Definition at line 37 of file pyc/physics/physics.cxx.
{
     return physics_::P(pmc)/pmc -> index({torch::indexing::Slice(), torch::indexing::Slice(3, 4)});
 }
References P(), and pmc.
Beta() [2/2]
torch::Tensor physics_::Beta (torch::Tensor * px, torch::Tensor * py, torch::Tensor * pz, torch::Tensor * e)
Computes the beta factor.
Parameters
px Input tensor for the x-component of momentum.
py Input tensor for the y-component of momentum.
pz Input tensor for the z-component of momentum.
e Input tensor for the energy of the system.
Returns
A tensor containing the beta factor.
Definition at line 41 of file pyc/physics/physics.cxx.
{
     torch::Tensor pmx = format({px, py, pz, e});
     return physics_::Beta(&pmx);
 }
References test_particles::e, and format().
Referenced by nusol_::BaseMatrix(), pyc::physics::cartesian::separate::Beta(), pyc::physics::cartesian::combined::Beta(), pyc::physics::polar::separate::Beta(), and pyc::physics::polar::combined::Beta().
Beta2() [1/2]
torch::Tensor physics_::Beta2 (torch::Tensor * pmc)
Computes the square of the beta factor from a momentum tensor.
Parameters
pmc Input tensor for the momentum components.
Returns
A tensor containing the square of the beta factor.
Definition at line 27 of file pyc/physics/physics.cxx.
{
     torch::Tensor e = pmc -> index({torch::indexing::Slice(), torch::indexing::Slice(3, 4)});
     return physics_::P2(pmc)/(e.pow(2));
 }
References test_particles::e, P2(), and pmc.
Beta2() [2/2]
torch::Tensor physics_::Beta2 (torch::Tensor * px, torch::Tensor * py, torch::Tensor * pz, torch::Tensor * e)
Computes the square of the beta factor.
Parameters
px Input tensor for the x-component of momentum.
py Input tensor for the y-component of momentum.
pz Input tensor for the z-component of momentum.
e Input tensor for the energy of the system.
Returns
A tensor containing the square of the beta factor.
Definition at line 32 of file pyc/physics/physics.cxx.
{
     torch::Tensor pmx = format({px, py, pz, e});
     return physics_::Beta2(&pmx);
 }
References test_particles::e, and format().
Referenced by nusol_::BaseMatrix(), pyc::physics::cartesian::separate::Beta2(), pyc::physics::cartesian::combined::Beta2(), pyc::physics::polar::separate::Beta2(), and pyc::physics::polar::combined::Beta2().
DeltaR() [1/2]
torch::Tensor physics_::DeltaR (torch::Tensor * eta1, torch::Tensor * eta2, torch::Tensor * phi1, torch::Tensor * phi2)
Computes the delta R separation between two particles.
Parameters
eta1 Input tensor for the pseudorapidity of the first particle.
eta2 Input tensor for the pseudorapidity of the second particle.
phi1 Input tensor for the azimuthal angle of the first particle.
phi2 Input tensor for the azimuthal angle of the second particle.
Returns
A tensor containing the delta R separation.
Definition at line 107 of file pyc/physics/physics.cxx.
{
     torch::Tensor d_eta = (*eta1) - (*eta2);
     torch::Tensor d_phi = (*phi1) - (*phi2);
     torch::Tensor pi = M_PI*torch::ones_like(d_eta);
     d_phi = pi - torch::abs(torch::fmod(torch::abs(d_phi), 2*pi) - pi);
     return torch::sqrt(d_eta.pow(2) + d_phi.pow(2));
 }
DeltaR() [2/2]
torch::Tensor physics_::DeltaR (torch::Tensor * pmu1, torch::Tensor * pmu2)
Computes the delta R separation between two particles.
Parameters
pmu1 Input tensor for the first particle's momentum.
pmu2 Input tensor for the second particle's momentum.
Returns
A tensor containing the delta R separation.
Definition at line 98 of file pyc/physics/physics.cxx.
{
     torch::Tensor eta1 = pmu1 -> index({torch::indexing::Slice(), torch::indexing::Slice(1, 2)});
     torch::Tensor eta2 = pmu2 -> index({torch::indexing::Slice(), torch::indexing::Slice(1, 2)});
     torch::Tensor phi1 = pmu1 -> index({torch::indexing::Slice(), torch::indexing::Slice(2, 3)});
     torch::Tensor phi2 = pmu2 -> index({torch::indexing::Slice(), torch::indexing::Slice(2, 3)});
     return physics_::DeltaR(&eta1, &eta2, &phi1, &phi2);
 }
Referenced by pyc::physics::cartesian::separate::DeltaR(), pyc::physics::cartesian::combined::DeltaR(), pyc::physics::polar::separate::DeltaR(), and pyc::physics::polar::combined::DeltaR().
M() [1/2]
torch::Tensor physics_::M (torch::Tensor * pmc)
Computes the invariant mass from a momentum tensor.
Parameters
pmc Input tensor for the momentum components.
Returns
A tensor containing the invariant mass.
Definition at line 58 of file pyc/physics/physics.cxx.
{
     torch::Tensor mass2 = physics_::M2(pmc);
     return (1 - 2*(mass2 < 0))*torch::sqrt(torch::abs(mass2));
 }
References M2(), and pmc.
M() [2/2]
torch::Tensor physics_::M (torch::Tensor * px, torch::Tensor * py, torch::Tensor * pz, torch::Tensor * e)
Computes the invariant mass.
Parameters
px Input tensor for the x-component of momentum.
py Input tensor for the y-component of momentum.
pz Input tensor for the z-component of momentum.
e Input tensor for the energy of the system.
Returns
A tensor containing the invariant mass.
Definition at line 63 of file pyc/physics/physics.cxx.
{
     torch::Tensor pmx = format({px, py, pz, e});
     return physics_::M(&pmx);
 }
References test_particles::e, and format().
Referenced by pyc::physics::cartesian::separate::M(), pyc::physics::cartesian::combined::M(), pyc::physics::polar::separate::M(), and pyc::physics::polar::combined::M().
M2() [1/2]
torch::Tensor physics_::M2 (torch::Tensor * pmc)
Computes the square of the invariant mass from a momentum tensor.
Parameters
pmc Input tensor for the momentum components.
Returns
A tensor containing the square of the invariant mass.
Definition at line 46 of file pyc/physics/physics.cxx.
{
     torch::Tensor mass = pmc -> index({torch::indexing::Slice(), torch::indexing::Slice(3, 4)});
     mass = mass.pow(2);
     mass -= physics_::P2(pmc);
     return mass;
 }
References mass, P2(), and pmc.
M2() [2/2]
torch::Tensor physics_::M2 (torch::Tensor * px, torch::Tensor * py, torch::Tensor * pz, torch::Tensor * e)
Computes the square of the invariant mass.
Parameters
px Input tensor for the x-component of momentum.
py Input tensor for the y-component of momentum.
pz Input tensor for the z-component of momentum.
e Input tensor for the energy of the system.
Returns
A tensor containing the square of the invariant mass.
Definition at line 53 of file pyc/physics/physics.cxx.
{
     torch::Tensor pmx = format({px, py, pz, e});
     return physics_::M2(&pmx);
 }
References test_particles::e, and format().
Referenced by nusol_::BaseMatrix(), M(), pyc::physics::cartesian::separate::M2(), pyc::physics::cartesian::combined::M2(), pyc::physics::polar::separate::M2(), and pyc::physics::polar::combined::M2().
Mt() [1/2]
torch::Tensor physics_::Mt (torch::Tensor * pmc)
Computes the transverse mass from a momentum tensor.
Parameters
pmc Input tensor for the momentum components.
Returns
A tensor containing the transverse mass.
Definition at line 78 of file pyc/physics/physics.cxx.
{
     torch::Tensor mt = physics_::Mt2(pmc);
     return (1 - 2*(mt < 0))*torch::sqrt(torch::abs(mt));
 }
References Mt2(), and pmc.
Mt() [2/2]
torch::Tensor physics_::Mt (torch::Tensor * pz, torch::Tensor * e)
Computes the transverse mass.
Parameters
pz Input tensor for the z-component of momentum.
e Input tensor for the energy of the system.
Returns
A tensor containing the transverse mass.
Definition at line 83 of file pyc/physics/physics.cxx.
{
     torch::Tensor mt = physics_::Mt2(pz, e);
     return  (1 - 2*(mt < 0))*torch::sqrt(torch::abs(mt));
 }
References test_particles::e, and Mt2().
Referenced by pyc::physics::cartesian::separate::Mt(), pyc::physics::cartesian::combined::Mt(), pyc::physics::polar::separate::Mt(), and pyc::physics::polar::combined::Mt().
Mt2() [1/2]
torch::Tensor physics_::Mt2 (torch::Tensor * pmc)
Computes the square of the transverse mass from a momentum tensor.
Parameters
pmc Input tensor for the momentum components.
Returns
A tensor containing the square of the transverse mass.
Definition at line 68 of file pyc/physics/physics.cxx.
{
     torch::Tensor pz = pmc -> index({torch::indexing::Slice(), torch::indexing::Slice(2, 3)});
     torch::Tensor e  = pmc -> index({torch::indexing::Slice(), torch::indexing::Slice(3, 4)});
     return (e.pow(2) - pz.pow(2)).view({-1, 1});
 }
References test_particles::e, and pmc.
Mt2() [2/2]
torch::Tensor physics_::Mt2 (torch::Tensor * pz, torch::Tensor * e)
Computes the square of the transverse mass.
Parameters
pz Input tensor for the z-component of momentum.
e Input tensor for the energy of the system.
Returns
A tensor containing the square of the transverse mass.
Definition at line 74 of file pyc/physics/physics.cxx.
{
     return  (e -> pow(2) - pz -> pow(2)).view({-1, 1});
 }
References test_particles::e.
Referenced by Mt(), pyc::physics::cartesian::separate::Mt2(), pyc::physics::cartesian::combined::Mt2(), pyc::physics::polar::separate::Mt2(), and pyc::physics::polar::combined::Mt2().
P() [1/2]
torch::Tensor physics_::P (torch::Tensor * pmc)
Computes the momentum magnitude from a momentum tensor.
Parameters
pmc Input tensor for the momentum components.
Returns
A tensor containing the momentum magnitude.
Definition at line 18 of file pyc/physics/physics.cxx.
{
     return torch::sqrt(physics_::P2(pmc));
 }
References P2(), and pmc.
P() [2/2]
torch::Tensor physics_::P (torch::Tensor * px, torch::Tensor * py, torch::Tensor * pz)
Computes the momentum magnitude.
Parameters
px Input tensor for the x-component of momentum.
py Input tensor for the y-component of momentum.
pz Input tensor for the z-component of momentum.
Returns
A tensor containing the momentum magnitude.
Definition at line 22 of file pyc/physics/physics.cxx.
{
     torch::Tensor pmx = format({px, py, pz});
     return physics_::P(&pmx);
 }
References format().
Referenced by nusol_::BaseMatrix(), Beta(), pyc::physics::cartesian::separate::P(), pyc::physics::cartesian::combined::P(), pyc::physics::polar::separate::P(), pyc::physics::polar::combined::P(), and Theta().
P2() [1/2]
torch::Tensor physics_::P2 (torch::Tensor * pmc)
Computes the square of the momentum magnitude from a momentum tensor.
Parameters
pmc Input tensor for the momentum components.
Returns
A tensor containing the square of the momentum magnitude.
Definition at line 5 of file pyc/physics/physics.cxx.
{
     torch::Tensor pmc_ = pmc -> index({torch::indexing::Slice(), torch::indexing::Slice(0, 3)});
     pmc_ = pmc_.pow(2);
     pmc_ = pmc_.sum({-1});
     return pmc_.view({-1, 1});
 }
References pmc.
P2() [2/2]
torch::Tensor physics_::P2 (torch::Tensor * px, torch::Tensor * py, torch::Tensor * pz)
Computes the square of the momentum magnitude.
Parameters
px Input tensor for the x-component of momentum.
py Input tensor for the y-component of momentum.
pz Input tensor for the z-component of momentum.
Returns
A tensor containing the square of the momentum magnitude.
Definition at line 12 of file pyc/physics/physics.cxx.
{
     std::vector<torch::Tensor> v = {*px, *py, *pz};
     torch::Tensor pmx = format(&v);
     return physics_::P2(&pmx);
 }
References format().
Referenced by Beta2(), M2(), P(), pyc::physics::cartesian::separate::P2(), pyc::physics::cartesian::combined::P2(), pyc::physics::polar::separate::P2(), and pyc::physics::polar::combined::P2().
Theta() [1/2]
torch::Tensor physics_::Theta (torch::Tensor * pmc)
Computes the polar angle theta.
Parameters
pmc Input tensor for the momentum components.
Returns
A tensor containing the polar angle theta.
Definition at line 88 of file pyc/physics/physics.cxx.
{
     torch::Tensor pz = pmc -> index({torch::indexing::Slice(), torch::indexing::Slice(2, 3)});
     return torch::acos( pz / physics_::P(pmc));
 }
References P(), and pmc.
Referenced by Rotation(), pyc::operators::RT(), pyc::physics::cartesian::separate::Theta(), pyc::physics::cartesian::combined::Theta(), pyc::physics::polar::separate::Theta(), and pyc::physics::polar::combined::Theta().
Theta() [2/2]
torch::Tensor physics_::Theta (torch::Tensor * px, torch::Tensor * py, torch::Tensor * pz)
Computes the polar angle theta.
Parameters
px Input tensor for the x-component of momentum.
py Input tensor for the y-component of momentum.
pz Input tensor for the z-component of momentum.
Returns
A tensor containing the polar angle theta.
Definition at line 93 of file pyc/physics/physics.cxx.
{
     torch::Tensor pmx = format({px, py, pz});
     return torch::acos( pz -> view({-1, 1}) / physics_::P(&pmx) );
 }
References format(), and P().