AnalysisG: graph_ Namespace Reference
graph_ Namespace Reference
Functions
std::map< std::string, torch::Tensor > edge_aggregation (torch::Tensor *edge_index, torch::Tensor *prediction, torch::Tensor *node_feature)
std::map< std::string, torch::Tensor > node_aggregation (torch::Tensor *edge_index, torch::Tensor *prediction, torch::Tensor *node_feature)
Function Documentation
edge_aggregation()
std::map< std::string, torch::Tensor > graph_::edge_aggregation (torch::Tensor * edge_index, torch::Tensor * prediction, torch::Tensor * node_feature)
Definition at line 4 of file pyc/graph/graph.cxx.
References edge_index, i, index, MakeOp(), and pmu.
Referenced by pyc::graph::edge_aggregation(), pyc::graph::cartesian::edge_aggregation(), pyc::graph::polar::edge_aggregation(), pyc::graph::polar::edge_aggregation(), pyc::graph::cartesian::edge_aggregation(), node_aggregation(), and pyc::graph::polar::node_aggregation().
node_aggregation()
std::map< std::string, torch::Tensor > graph_::node_aggregation (torch::Tensor * edge_index, torch::Tensor * prediction, torch::Tensor * node_feature)
Definition at line 65 of file pyc/graph/graph.cxx.
References edge_aggregation(), edge_index, and index.
Referenced by pyc::graph::node_aggregation(), pyc::graph::cartesian::node_aggregation(), pyc::graph::polar::node_aggregation(), and pyc::graph::cartesian::node_aggregation().