AnalysisG: pyc::physics::cartesian::combined Namespace Reference
pyc::physics::cartesian::combined Namespace Reference
Functions
torch::Tensor P2 (torch::Tensor pmc)
torch::Tensor P (torch::Tensor pmc)
torch::Tensor Beta2 (torch::Tensor pmc)
torch::Tensor Beta (torch::Tensor pmc)
torch::Tensor M2 (torch::Tensor pmc)
torch::Tensor M (torch::Tensor pmc)
torch::Tensor Mt2 (torch::Tensor pmc)
torch::Tensor Mt (torch::Tensor pmc)
torch::Tensor Theta (torch::Tensor pmc)
torch::Tensor DeltaR (torch::Tensor pmc1, torch::Tensor pmc2)
Function Documentation
Beta()
torch::Tensor pyc::physics::cartesian::combined::Beta (torch::Tensor pmc)
Definition at line 89 of file pyc/interface/physics.cxx.
{
     changedev(&pmc);
     return physics_::Beta(&pmc);
 }
References physics_::Beta(), changedev(), and pmc.
Beta2()
torch::Tensor pyc::physics::cartesian::combined::Beta2 (torch::Tensor pmc)
Definition at line 65 of file pyc/interface/physics.cxx.
{
     changedev(&pmc);
     return physics_::Beta2(&pmc);
 }
References physics_::Beta2(), changedev(), and pmc.
DeltaR()
torch::Tensor pyc::physics::cartesian::combined::DeltaR (torch::Tensor pmc1, torch::Tensor pmc2)
Definition at line 234 of file pyc/interface/physics.cxx.
{
     changedev(&pmc1);
     torch::Tensor pmu1 = transform_::PtEtaPhi(&pmc1);
     torch::Tensor pmu2 = transform_::PtEtaPhi(&pmc2);
     return physics_::DeltaR(&pmu1, &pmu2);
 }
References changedev(), physics_::DeltaR(), and transform_::PtEtaPhi().
Referenced by recursivegraphneuralnetwork::message().
M()
torch::Tensor pyc::physics::cartesian::combined::M (torch::Tensor pmc)
Definition at line 137 of file pyc/interface/physics.cxx.
{
     changedev(&pmc);
     return physics_::M(&pmc);
 }
References changedev(), physics_::M(), and pmc.
Referenced by grift::message(), and recursivegraphneuralnetwork::message().
M2()
torch::Tensor pyc::physics::cartesian::combined::M2 (torch::Tensor pmc)
Definition at line 113 of file pyc/interface/physics.cxx.
{
     changedev(&pmc);
     return physics_::M2(&pmc);
 }
References changedev(), physics_::M2(), and pmc.
Mt()
torch::Tensor pyc::physics::cartesian::combined::Mt (torch::Tensor pmc)
Definition at line 183 of file pyc/interface/physics.cxx.
{
     changedev(&pmc);
     return physics_::Mt(&pmc);
 }
References changedev(), physics_::Mt(), and pmc.
Mt2()
torch::Tensor pyc::physics::cartesian::combined::Mt2 (torch::Tensor pmc)
Definition at line 160 of file pyc/interface/physics.cxx.
{
     changedev(&pmc);
     return physics_::Mt2(&pmc);
 }
References changedev(), physics_::Mt2(), and pmc.
P()
torch::Tensor pyc::physics::cartesian::combined::P (torch::Tensor pmc)
Definition at line 41 of file pyc/interface/physics.cxx.
{
     changedev(&pmc);
     return physics_::P(&pmc);
 }
References changedev(), physics_::P(), and pmc.
P2()
torch::Tensor pyc::physics::cartesian::combined::P2 (torch::Tensor pmc)
Definition at line 18 of file pyc/interface/physics.cxx.
{
     changedev(&pmc);
     return physics_::P2(&pmc);
 }
References changedev(), physics_::P2(), and pmc.
Theta()
torch::Tensor pyc::physics::cartesian::combined::Theta (torch::Tensor pmc)
Definition at line 205 of file pyc/interface/physics.cxx.
{
     changedev(&pmc);
     return physics_::Theta(&pmc);
 }
References changedev(), pmc, and physics_::Theta().