AnalysisG: pyc::graph Namespace Reference
pyc::graph Namespace Reference
Namespaces
cartesian
polar
Functions
torch::Dict< std::string, torch::Tensor > edge_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor node_feature)
torch::Dict< std::string, torch::Tensor > node_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor node_feature)
torch::Dict< std::string, torch::Tensor > unique_aggregation (torch::Tensor cluster_map, torch::Tensor features)
torch::Dict< std::string, torch::Tensor > PageRank (torch::Tensor edge_index, torch::Tensor edge_scores, double alpha=0.85, double threshold=0.5, double norm_low=1e-6, long timeout=1e6, long num_cls=2)
torch::Dict< std::string, torch::Tensor > PageRankReconstruction (torch::Tensor edge_index, torch::Tensor edge_scores, torch::Tensor pmc, double alpha=0.85, double threshold=0.5, double norm_low=1e-6, long timeout=1e6, long num_cls=2)
Function Documentation
edge_aggregation()
torch::Dict< std::string, torch::Tensor > pyc::graph::edge_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor node_feature)
Definition at line 75 of file interface/graph.cxx.
  {
     changedev(&edge_index);
     std::map<std::string, torch::Tensor> out;
     out = graph_::edge_aggregation(&edge_index, &prediction, &edge_feature);
     return pyc::std_to_dict(&out);
 }
References changedev(), graph_::edge_aggregation(), edge_index, main::out, and pyc::std_to_dict().
node_aggregation()
torch::Dict< std::string, torch::Tensor > pyc::graph::node_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor node_feature)
Definition at line 84 of file interface/graph.cxx.
  {
     changedev(&edge_index);
     std::map<std::string, torch::Tensor> out;
     out = graph_::node_aggregation(&edge_index, &prediction, &node_feature);
     return pyc::std_to_dict(&out);
 }
References changedev(), edge_index, graph_::node_aggregation(), main::out, and pyc::std_to_dict().
PageRank()
torch::Dict< std::string, torch::Tensor > pyc::graph::PageRank (torch::Tensor edge_index, torch::Tensor edge_scores, double alpha = 0.85, double threshold = 0.5, double norm_low = 1e-6, long timeout = 1e6, long num_cls = 2)
Definition at line 14 of file interface/graph.cxx.
  {
     changedev(&edge_index); changedev(&edge_scores);
     const unsigned int edx = edge_index.size({0});
     const unsigned int edy = edge_index.size({1});
     if (edx != 2 && edy == 2){edge_index = edge_index.transpose(0, 1).contiguous();}
     const unsigned int sdx = edge_scores.size({0});
     const unsigned int sdy = edge_scores.size({1});
     if (sdx != 2 && sdy == 2){edge_scores = edge_scores.transpose(0, 1).contiguous();}
     std::map<std::string, torch::Tensor> out;
     #ifdef PYC_CUDA
     out = graph_::page_rank(&edge_index, &edge_scores, alpha, threshold, norm_low, timeout, num_cls);
     #endif
     return pyc::std_to_dict(&out);
 }
References changedev(), edge_index, main::out, and pyc::std_to_dict().
PageRankReconstruction()
torch::Dict< std::string, torch::Tensor > pyc::graph::PageRankReconstruction (torch::Tensor edge_index, torch::Tensor edge_scores, torch::Tensor pmc, double alpha = 0.85, double threshold = 0.5, double norm_low = 1e-6, long timeout = 1e6, long num_cls = 2)
Definition at line 35 of file interface/graph.cxx.
  {
     changedev(&edge_index); changedev(&edge_scores); changedev(&pmc);
     const unsigned int edx = edge_index.size({0});
     const unsigned int edy = edge_index.size({1});
     if (edx != 2 && edy == 2){edge_index = edge_index.transpose(0, 1).contiguous();}
     const unsigned int sdx = edge_scores.size({0});
     const unsigned int sdy = edge_scores.size({1});
     if (sdx != 2 && sdy == 2){edge_scores = edge_scores.softmax(-1).transpose(0, 1).contiguous();}
     else {edge_scores = edge_scores.softmax(0);}
     std::map<std::string, torch::Tensor> out;
     #ifdef PYC_CUDA
     out = graph_::page_rank_reconstruction(&edge_index, &edge_scores, &pmc, alpha, threshold, norm_low, timeout, num_cls);
     #endif
     return pyc::std_to_dict(&out);
 }
References changedev(), edge_index, main::out, pmc, and pyc::std_to_dict().
unique_aggregation()
torch::Dict< std::string, torch::Tensor > pyc::graph::unique_aggregation (torch::Tensor cluster_map, torch::Tensor features)
Definition at line 93 of file interface/graph.cxx.
  {
     changedev(&cluster_map);
     std::map<std::string, torch::Tensor> out;
     out = graph_::unique_aggregation(&cluster_map, &feature);
     return pyc::std_to_dict(&out);
 }
References changedev(), main::out, and pyc::std_to_dict().
Referenced by grift::message(), and recursivegraphneuralnetwork::message().