AnalysisG: validation.nusol Namespace Reference
validation.nusol Namespace Reference
Classes
class DoubleNu
class NuSol
class SingleNu
Functions
def costheta (v1, v2)
def UnitCircle ()
def R (axis, angle)
def Derivative ()
def multisqrt (y)
def intersections_ellipse_line (ellipse, line, zero=1e-10)
def cofactor (A, i, j)
def factor_degenerate (G, zero=0)
def intersections_ellipses (A, B, returnLines=False, zero=10e-10)
Variables
float mW = 80.385*1000
float mT = 172.62*1000
int mN = 0
Function Documentation
cofactor()
def validation.nusol.cofactor (A, i, j)
Cofactor[i,j] of 3x3 matrix A
Definition at line 50 of file validation/nusol.py.
 def cofactor(A, i, j):
     """Cofactor[i,j] of 3x3 matrix A"""
     a = A[
         not i : 2 if i == 2 else None : 2 if i == 1 else 1,
         not j : 2 if j == 2 else None : 2 if j == 1 else 1,
     ]
     return (-1) ** (i + j) * (a[0, 0] * a[1, 1] - a[1, 0] * a[0, 1])
Referenced by validation.nusol.factor_degenerate().
costheta()
def validation.nusol.costheta (v1, v2)
Definition at line 10 of file validation/nusol.py.
 def costheta(v1, v2):
     v1_sq = v1.x**2 + v1.y**2 + v1.z**2
     if v1_sq == 0: return 0
     v2_sq = v2.x**2 + v2.y**2 + v2.z**2
     if v2_sq == 0: return 0
     v1v2 = v1.x*v2.x + v1.y*v2.y + v1.z*v2.z
     return v1v2/math.sqrt(v1_sq * v2_sq)
Derivative()
def validation.nusol.Derivative ()
Matrix to differentiate [cos(t),sin(t),1]
Definition at line 30 of file validation/nusol.py.
 def Derivative():
     """Matrix to differentiate [cos(t),sin(t),1]"""
     cx = np.array([[0, -1, 0], [1, 0, 0], [0, 0, 0]])
     return cx.dot(np.diag([1, 1, 0]))
Referenced by validation.nusol.NuSol.M().
factor_degenerate()
def validation.nusol.factor_degenerate (G, zero = 0)
Linear factors of degenerate quadratic polynomial
Definition at line 59 of file validation/nusol.py.
 def factor_degenerate(G, zero=0):
     """Linear factors of degenerate quadratic polynomial"""
     if G[0, 0] == 0 == G[1, 1]: return [[G[0, 1], 0, G[1, 2]], [0, G[0, 1], G[0, 2] - G[1, 2]]]
     swapXY = abs(G[0, 0]) > abs(G[1, 1])
     Q = G[(1, 0, 2),][:, (1, 0, 2)] if swapXY else G
     Q /= Q[1, 1]
     q22 = cofactor(Q, 2, 2)
     if -q22 <= zero: lines = [[Q[0, 1], Q[1, 1], (Q[1, 2] + s)] for s in multisqrt(-cofactor(Q, 0, 0))]
     else:
         x0, y0 = [cofactor(Q, i, 2) / q22 for i in [0, 1]]
         lines = [ [m, Q[1, 1], (-Q[1, 1] * y0 - m * x0)] for m in [Q[0, 1] + s for s in multisqrt(-q22)] ]
     return [[L[swapXY], L[not swapXY], L[2]] for L in lines]
References validation.nusol.cofactor(), and validation.nusol.multisqrt().
Referenced by validation.nusol.intersections_ellipses().
intersections_ellipse_line()
def validation.nusol.intersections_ellipse_line (ellipse, line, zero = 1e-10)
Points of intersection between ellipse and line
Definition at line 41 of file validation/nusol.py.
 def intersections_ellipse_line(ellipse, line, zero=1e-10):
     """Points of intersection between ellipse and line"""
     _, V = np.linalg.eig(np.cross(line, ellipse).T)
     sols = sorted([(
         v.real / v[2].real,
         math.log10(sum((line*v.real).tolist())**2 + sum((np.dot(v.real, ellipse) * v.real).tolist())**2)
         ) for v in V.T if v[2].real != 0 and not sum(v.imag)], key = lambda k : k[1])[:2]
     return [s for s, k in sols if k < np.log10(zero)]
References selection_template.sum().
Referenced by validation.nusol.intersections_ellipses().
intersections_ellipses()
def validation.nusol.intersections_ellipses (A, B, returnLines = False, zero = 10e-10)
Points of intersection between two ellipses
Definition at line 74 of file validation/nusol.py.
 def intersections_ellipses(A, B, returnLines=False, zero = 10e-10):
     """Points of intersection between two ellipses"""
     LA = np.linalg
     sw = abs(LA.det(B)) > abs(LA.det(A))
     if sw: A, B = B, A
     t = LA.inv(A).dot(B)
     e = next(iter([e.real for e in LA.eigvals(t) if not e.imag]))
     lines = factor_degenerate(B - e * A, zero)
     points = sum([intersections_ellipse_line(A, L, zero) for L in lines], [])
     return points, lines
References validation.nusol.factor_degenerate(), validation.nusol.intersections_ellipse_line(), and selection_template.sum().
Referenced by validation.nusol.SingleNu.__init__().
multisqrt()
def validation.nusol.multisqrt (y)
Valid real solutions to y=x*x
Definition at line 35 of file validation/nusol.py.
 def multisqrt(y):
     """Valid real solutions to y=x*x"""
     return [] if y < 0 else [0] if y == 0 else (lambda r: [-r, r])(math.sqrt(y))
 # A = ellipse, Q[i] = line
Referenced by validation.nusol.factor_degenerate().
R()
def validation.nusol.R (axis, angle)
Rotation matrix about x(0),y(1), or z(2) axis
Definition at line 22 of file validation/nusol.py.
 def R(axis, angle):
     """Rotation matrix about x(0),y(1), or z(2) axis"""
     c, s = math.cos(angle), math.sin(angle)
     R = c * np.eye(3)
     for i in [-1, 0, 1]:
         R[(axis - i) % 3, (axis + i) % 3] = i * s + (1 - i * i)
     return R
Referenced by validation.nusol.NuSol.R_T().
UnitCircle()
def validation.nusol.UnitCircle ()
Definition at line 20 of file validation/nusol.py.
 def UnitCircle(): return np.diag([1, 1, -1])
Referenced by validation.nusol.SingleNu.__init__(), and validation.nusol.NuSol.N().
Variable Documentation
mN
int validation.nusol.mN = 0
Definition at line 8 of file validation/nusol.py.
mT
float validation.nusol.mT = 172.62*1000
Definition at line 7 of file validation/nusol.py.
mW
float validation.nusol.mW = 80.385*1000
Definition at line 6 of file validation/nusol.py.