AnalysisG: nusol_ Namespace Reference
nusol_ Namespace Reference
Functions
torch::Tensor BaseMatrix (torch::Tensor *pmc_b, torch::Tensor *pmc_mu, torch::Tensor *masses)
torch::Tensor Hperp (torch::Tensor *pmc_b, torch::Tensor *pmc_mu, torch::Tensor *masses)
std::tuple< torch::Tensor, torch::Tensor > Intersection (torch::Tensor *A, torch::Tensor *B, double nulls)
std::map< std::string, torch::Tensor > Nu (torch::Tensor *pmc_b, torch::Tensor *pmc_mu, torch::Tensor *met_xy, torch::Tensor *masses, torch::Tensor *sigma, double null)
std::map< std::string, torch::Tensor > NuNu (torch::Tensor *pmc_b1, torch::Tensor *pmc_b2, torch::Tensor *pmc_mu1, torch::Tensor *pmc_mu2, torch::Tensor *met_xy, double null, torch::Tensor *m1, torch::Tensor *m2=nullptr)
Function Documentation
BaseMatrix()
torch::Tensor nusol_::BaseMatrix (torch::Tensor * pmc_b, torch::Tensor * pmc_mu, torch::Tensor * masses)
Definition at line 198 of file nusol/tensor/nusol.cxx.
{
     torch::Tensor pmx_b  = pmc_b -> view({-1, 4});
     torch::Tensor pmx_mu = pmc_mu -> view({-1, 4});
     std::map<std::string, torch::Tensor> mass = GetMasses(&pmx_b, masses);
     const torch::TensorOptions op = MakeOp(pmc_b);
     const unsigned int dim_i = pmx_b.size(0);
     torch::Tensor bB   = physics_::Beta(&pmx_b);
     torch::Tensor muB  = physics_::Beta(&pmx_mu);
     torch::Tensor muB2 = physics_::Beta2(&pmx_mu);
     torch::Tensor muP  = physics_::P(&pmx_mu);
     torch::Tensor m2b = physics_::M2(&pmx_b);
     torch::Tensor m2l = physics_::M2(&pmx_mu);
     torch::Tensor x0p = _x0(&pmx_b , &m2b, &mass["T2"], &mass["W2"]);
     torch::Tensor x0  = _x0(&pmx_mu, &m2l, &mass["W2"], &mass["N2"]);
     torch::Tensor pmc_b3  = pmx_b.index( {torch::indexing::Slice(), torch::indexing::Slice(0, 3)});
     torch::Tensor pmc_mu3 = pmx_mu.index({torch::indexing::Slice(), torch::indexing::Slice(0, 3)});
     torch::Tensor c_ = operators_::CosTheta(&pmc_b3, &pmc_mu3);
     torch::Tensor s_ = operators_::SinTheta(&pmc_b3, &pmc_mu3);
     torch::Tensor tmp_ = muB / bB;
     torch::Tensor w_ = ( - tmp_ - c_ ) / s_;
     torch::Tensor w  = ( tmp_ - c_ ) / s_;
     torch::Tensor O2 = w.pow(2) + 1 - muB2;
     torch::Tensor e2 = (mass["W2"] - mass["N2"]) * ( 1 - muB2 );
     torch::Tensor Sx = (x0 * muB - muP * ( 1 - muB2 )) / muB2;
     torch::Tensor Sy = ( (x0p / bB) - c_ * Sx ) / s_;
     tmp_ = Sx + w*Sy;
     torch::Tensor x1 = Sx - tmp_ / O2;
     torch::Tensor y1 = Sy - tmp_ * (w / O2);
     torch::Tensor Z = torch::sqrt(torch::relu(x1.pow(2) * O2 - ( Sy - w*Sx ).pow(2) - ( mass["W2"] - x0.pow(2) - e2 )));
     torch::Tensor  O = torch::sqrt(O2);
     torch::Tensor _0 = torch::zeros({dim_i, 1}, op);
     return torch::cat({ Z / O, _0, x1 - muP, (w*Z)/O, _0, y1, _0, Z, _0}, -1).view({dim_i, 3, 3});
 }
References _x0(), physics_::Beta(), physics_::Beta2(), operators_::CosTheta(), GetMasses(), physics_::M2(), MakeOp(), mass, main::masses, test_generator::op, physics_::P(), and operators_::SinTheta().
Referenced by _xNu(), pyc::nusol::BaseMatrix(), Hperp(), and NuNu().
Hperp()
torch::Tensor nusol_::Hperp (torch::Tensor * pmc_b, torch::Tensor * pmc_mu, torch::Tensor * masses)
Definition at line 244 of file nusol/tensor/nusol.cxx.
{
     torch::Tensor H = nusol_::BaseMatrix(pmc_b, pmc_mu, masses);
     H = Rotation(pmc_b, pmc_mu, &H);
     H = _H_perp(&H);
     torch::Tensor nullx = torch::isnan(H).sum(-1).sum(-1) == 0;
     H.index_put_({nullx, torch::indexing::Slice(), torch::indexing::Slice()}, 0);
     return H;
 }
References _H_perp(), BaseMatrix(), main::masses, and Rotation().
Intersection()
std::tuple< torch::Tensor, torch::Tensor > nusol_::Intersection (torch::Tensor * A, torch::Tensor * B, double nulls)
Definition at line 253 of file nusol/tensor/nusol.cxx.
{
     const torch::TensorOptions op = MakeOp(A);
     const unsigned int dim_i = A -> size(0);
     std::vector<signed long> dim11 = {-1, 1, 1};
     std::vector<signed long> dim13 = {-1, 1, 3};
     std::vector<signed long> dim31 = {-1, 3, 1};
     std::vector<signed long> dim313 = {-1, 3, 1, 3};
     std::vector<signed long> dim133 = {-1, 1, 3, 3};
     std::vector<signed long> dim331 = {-1, 3, 3, 1};
     std::vector<signed long> dim333 = {-1, 3, 3, 3};
     torch::Tensor _A = A -> clone();
     torch::Tensor _B = B -> clone();
     torch::Tensor detA = torch::abs(operators_::Determinant(A));
     torch::Tensor detB = torch::abs(operators_::Determinant(B));
     // Perform the variable swaps
     torch::Tensor swp = detB > detA;
     torch::Tensor _tmp = B -> index({swp});
     _B.index_put_({swp}, A -> index({swp}));
     _A.index_put_({swp}, _tmp);
     // Find the non imaginary eigenvalue solutions
     _tmp = torch::linalg::eigvals(operators_::Inverse(&_A).matmul(_B));
     torch::Tensor _r = torch::real(_tmp);
     torch::Tensor msk = torch::isreal(_tmp)*torch::arange(3, 0, -1, op);
     msk = torch::argmax(msk, -1, true);
     _r = torch::gather(_r, 1, msk).view({-1, 1, 1});
     torch::Tensor G = _B - _r*_A;
     // Get the diagonals of the matrix
     torch::Tensor G00 = G.index({torch::indexing::Slice(), 0, 0});
     torch::Tensor G11 = G.index({torch::indexing::Slice(), 1, 1});
     // ----- Numerical Stability part ----- //
     swp = torch::abs(G00) > torch::abs(G11);
     G.index_put_({swp}, torch::cat({
                 G.index({swp, 1, torch::indexing::Slice()}).view(dim13),
                 G.index({swp, 0, torch::indexing::Slice()}).view(dim13),
                 G.index({swp, 2, torch::indexing::Slice()}).view(dim13)
     }, 1));
     G.index_put_({swp}, torch::cat({
                 G.index({swp, torch::indexing::Slice(), 1}).view(dim31),
                 G.index({swp, torch::indexing::Slice(), 0}).view(dim31),
                 G.index({swp, torch::indexing::Slice(), 2}).view(dim31)
     }, 2));
     G = G/(G.index({torch::indexing::Slice(), 1, 1}).view({-1, 1, 1}));
     torch::Tensor CoF = operators_::CoFactors(&G);
     torch::Tensor g22 = CoF.index({torch::indexing::Slice(), 2, 2});
     torch::Tensor _out = zeros_like(G);
     detA = detA == 0;
     torch::Tensor G00_G11 = ( G00 == 0 ) * (G11 == 0);
     torch::Tensor g22__   = (-g22 <= 0.) * (G00_G11 == false);
     torch::Tensor g22_    = (-g22 >  0.) * (G00_G11 == false);
     // 1. ----- Case where the solutions are Horizontal and Vertical ----- //
     torch::Tensor tx = G.index({G00_G11});
     torch::Tensor SolG_HV = HorizontalVertical(&tx);
     // 2. ------ Case where the solutions are parallel
     torch::Tensor g22x = G.index({g22__});
     torch::Tensor g22f = CoF.index({g22__});
     torch::Tensor SolG_Para = Parallel(&g22x, &g22f);
     // 3. ------- Case where the solutions are intersecting
     g22x = G.index({g22_});
     g22f = CoF.index({g22_});
     tx   = g22.index({g22_});
     torch::Tensor SolG_Int = Intersecting(&g22x, &tx, &g22f);
     _out.index_put_({G00_G11}, SolG_HV);
     _out.index_put_({g22__  }, SolG_Para);
     _out.index_put_({g22_   }, SolG_Int);
     _out.index_put_({detA   }, 0);
     // Swap the XY if they were swapped previously
     _tmp = torch::cat({
             _out.index({swp, torch::indexing::Slice(), 1}).view(dim31),
             _out.index({swp, torch::indexing::Slice(), 0}).view(dim31),
             _out.index({swp, torch::indexing::Slice(), 2}).view(dim31)}, 2);
     _out.index_put_({swp}, _tmp);
     // ------ Intersection of line with Ellipse ------ //
     torch::Tensor _t, d1, V, V_, diag;
     V = torch::cross(_out.view(dim313), _A.view(dim133), 3);
     V = torch::transpose(V, 2, 3);
     V = std::get<1>(torch::linalg::eig(V));
     V = torch::real(V);
     V = torch::transpose(V, 2, 3);
     _t = V / (V.index({
                 torch::indexing::Slice(),
             torch::indexing::Slice(),
             torch::indexing::Slice(),
     2}).view(dim331));
     d1 = torch::sum(((_out.view(dim313))*V), 3).pow(2);
     V_ = torch::reshape(V, dim333);
     // ------- Neutrino Solution ------ //
     _t = _t.view({dim_i, -1, 3});
     _t = torch::nan_to_num(_t, 0, 0);
     diag = torch::matmul(V_, _A.view(dim133));
     diag = torch::sum((diag * V_), {-1}).pow(2);
     diag = (d1 + diag).view({dim_i, -1});
     // ------- Remove false solutions ------ //
     torch::Tensor t0_, t1_, t2_;
     t0_ = _t.index({torch::indexing::Slice(), torch::indexing::Slice(), 0}).view({dim_i, -1});
     t1_ = _t.index({torch::indexing::Slice(), torch::indexing::Slice(), 1}).view({dim_i, -1});
     t2_ = _t.index({torch::indexing::Slice(), torch::indexing::Slice(), 2}).view({dim_i, -1});
     detB = ((t0_.view({dim_i, -1, 1}) == 0) * (t1_.view({dim_i, -1, 1}) == 0)).view({dim_i, -1});
     t2_.index_put_({detB}, 0);
     diag.index_put_({detA}, -1);
     diag.index_put_({detB}, -1);
     diag.index_put_({diag > null}, -1);
     // ------- Do the Sorting ------ //
     torch::Tensor id = std::get<1>(diag.sort(-1, false));
     t0_ = torch::gather(t0_, -1, id).view({dim_i, -1, 1});
     t1_ = torch::gather(t1_, -1, id).view({dim_i, -1, 1});
     t2_ = torch::gather(t2_, -1, id).view({dim_i, -1, 1});
     _t = torch::cat({t0_, t1_, t2_}, -1);
     diag = torch::gather(diag, 1, id);
     int max_len = diag.size(-1) - torch::max((diag != -1).sum(-1)).item<int>();
     _t = _t.index({
             torch::indexing::Slice(),
             torch::indexing::Slice(max_len, torch::indexing::None),
             torch::indexing::Slice()});
     diag = diag.index({
             torch::indexing::Slice(),
             torch::indexing::Slice(max_len, torch::indexing::None)});
     return {_t, diag};
 }
References clone(), operators_::CoFactors(), operators_::Determinant(), HorizontalVertical(), Intersecting(), operators_::Inverse(), MakeOp(), simply_plot::msk, test_generator::op, and Parallel().
Referenced by Nu(), and NuNu().
Nu()
std::map< std::string, torch::Tensor > nusol_::Nu (torch::Tensor * pmc_b, torch::Tensor * pmc_mu, torch::Tensor * met_xy, torch::Tensor * masses, torch::Tensor * sigma, double null)
Definition at line 430 of file nusol/tensor/nusol.cxx.
 {
     torch::Tensor v, chi2;
     std::map<std::string, torch::Tensor> _Nu, output;
     std::tuple<torch::Tensor, torch::Tensor> sols;
     const unsigned int dim_i = met_xy -> size(0);
     _Nu = _xNu(pmc_b, pmc_mu, met_xy, masses, sigma);
     torch::Tensor M = _Nu["M"];
     torch::Tensor H = _Nu["H"];
     torch::Tensor X = _Nu["X"];
     torch::Tensor circl = Shape(met_xy, {1, 1, -1});
     sols = nusol_::Intersection(&M, &circl, null);
     v = std::get<0>(sols).view({dim_i, -1, 1, 3});
     torch::Tensor diag = std::get<1>(sols);
     chi2 = (v * X.view({dim_i, 1, 3, 3})).sum({-1});
     chi2 = chi2.view({dim_i, -1, 3})*v.view({dim_i, -1, 3});
     chi2 = chi2.sum(-1);
     v = (H.view({dim_i, 1, 3, 3})*v).sum(-1);
     torch::Tensor t0_, t1_, t2_;
     t0_ = v.index({torch::indexing::Slice(), torch::indexing::Slice(), 0}).view({dim_i, -1});
     t1_ = v.index({torch::indexing::Slice(), torch::indexing::Slice(), 1}).view({dim_i, -1});
     t2_ = v.index({torch::indexing::Slice(), torch::indexing::Slice(), 2}).view({dim_i, -1});
     // ------- Do the Sorting ------ //
     torch::Tensor id = std::get<1>(chi2.sort(-1, false));
     t0_ = torch::gather(t0_, -1, id).view({dim_i, -1, 1});
     t1_ = torch::gather(t1_, -1, id).view({dim_i, -1, 1});
     t2_ = torch::gather(t2_, -1, id).view({dim_i, -1, 1});
     v = torch::cat({t0_, t1_, t2_}, -1);
     chi2 = torch::gather(diag, 1, id);
     output["nu1"] = v;
     output["distance"] = chi2;
     return output;
 }
References _xNu(), chi2(), Intersection(), pyc::physics::cartesian::separate::M(), main::masses, and Shape().
Referenced by pyc::nusol::Nu().
NuNu()
std::map< std::string, torch::Tensor > nusol_::NuNu (torch::Tensor * pmc_b1, torch::Tensor * pmc_b2, torch::Tensor * pmc_mu1, torch::Tensor * pmc_mu2, torch::Tensor * met_xy, double null, torch::Tensor * m1, torch::Tensor * m2 = nullptr)
Definition at line 473 of file nusol/tensor/nusol.cxx.
 {
     torch::Tensor H1, H2, H1_perp, H2_perp, N1, N2, S, n_, none;
     torch::Tensor zero, _v, __v, _d;
     const torch::TensorOptions op = MakeOp(met_xy);
     std::map<std::string, torch::Tensor> output;
     std::tuple<torch::Tensor, torch::Tensor> sols;
     // ---------------- Prepare all needed matrices ----------------- //
     if (!m2){m2 = m1;}
     H1 = nusol_::BaseMatrix(pmc_b1, pmc_l1, m1);
     H2 = nusol_::BaseMatrix(pmc_b2, pmc_l2, m2);
     // --- protection against non-invertible matrices --- //
     none =  (torch::det(H1) == 0);
     none += (torch::det(H2) == 0);
     none = none == 0;
     output["NoSols"] = none;
     const unsigned int dim_i = met_xy -> index({none}).size(0);
     if (dim_i == 0){
         output["n_"]   = torch::zeros({1, 3}, op);
         output["nu_1"] = torch::zeros({1, 3}, op);
         output["nu_2"] = torch::zeros({1, 3}, op);
         output["H_perp_1"] = H1;
         output["H_perp_2"] = H2;
         return output;
     }
     torch::Tensor xb1_ = pmc_b1 -> index({none});
     torch::Tensor xl1_ = pmc_l1 -> index({none});
     torch::Tensor h1_  = H1.index({none});
     H1 = Rotation(&xb1_, &xl1_, &h1_);
     torch::Tensor xb2_ = pmc_b2 -> index({none});
     torch::Tensor xl2_ = pmc_l2 -> index({none});
     torch::Tensor h2_  = H2.index({none});
     H2 = Rotation(&xb2_, &xl2_, &h2_);
     H1_perp = _H_perp(&H1);
     H2_perp = _H_perp(&H2);
     N1 = _N(&H1_perp);
     N2 = _N(&H2_perp);
     S = met_xy -> index({none});
     S = _met(&S) - Shape(&S, {1, 1, -1});
     n_ = torch::matmul(torch::matmul(S.transpose(1, 2), N2), S);
     // ---------------- Start Algorithm ----------------- //
     sols = nusol_::Intersection(&N1, &n_, null);
     torch::Tensor d = std::get<1>(sols);
     torch::Tensor v = std::get<0>(sols).view({dim_i, -1, 1, 3});
     torch::Tensor v_ = torch::sum(S.view({dim_i, 1, 3, 3}) * v, -1).view({dim_i, -1, 1, 3});
     torch::Tensor K1 = torch::matmul(H1, torch::inverse(H1_perp)).view({dim_i, 1, 3, 3});
     torch::Tensor K2 = torch::matmul(H2, torch::inverse(H2_perp)).view({dim_i, 1, 3, 3});
     v  = (K1 * v).sum(-1);
     v_ = (K2 * v_).sum(-1);
     unsigned int dim_j  = v.size(1);
     unsigned int dim_k  = v.size(2);
     unsigned int dim_i_ = none.size(0);
     zero = torch::zeros({dim_i_, dim_j, dim_k}, op);
     _d = torch::zeros({dim_i_, dim_j}, op);
     _d.index_put_({none}, d);
     _v = zero.clone();
     _v.index_put_({none}, v);
     __v = zero.clone();
     __v.index_put_({none}, v_);
     output["nu_1"] = _v;
     output["nu_2"] = __v;
     output["distance"] = _d;
     output["n_"] = n_;
     output["H_perp_1"] = H1_perp;
     output["H_perp_2"] = H2_perp;
     return output;
 }
References _H_perp(), _met(), _N(), BaseMatrix(), d, Intersection(), rnn_model::m1, MakeOp(), test_generator::op, Rotation(), and Shape().
Referenced by pyc::nusol::NuNu().