AnalysisG: classes Namespace Reference
classes Namespace Reference
Classes
class atomic
class Container
class loss
class nux
Functions
def bar (p, sym)
def pdgid (p)
Function Documentation
bar()
def classes.bar (p, sym)
Definition at line 1 of file classes.py.
 def bar(p, sym): return sym if p > 0 else "\\bar{" + sym + "}"
Referenced by pdgid().
pdgid()
def classes.pdgid (p)
Definition at line 2 of file classes.py.
 def pdgid(p):
     if abs(p) == 11: return bar(p, "e")
     if abs(p) == 12: return bar(p, "\\nu_{e}")
     if abs(p) == 13: return bar(p, "\\mu")
     if abs(p) == 14: return bar(p, "\\nu_{\\mu}")
     if abs(p) == 15: return bar(p, "\\tau")
     if abs(p) == 16: return bar(p, "\\nu_{\\tau}")
     print("!!!!!!!!!", p); exit()
References bar().
Referenced by classes.nux.add().