AnalysisG: test_evaluation Namespace Reference
test_evaluation Namespace Reference
Variables
ev = BSM4Tops()
gr = GraphJets()
gn = Grift()
name
o_edge
o_graph
i_node
i_graph
device
opti = OptimizerConfig()
Optimizer
lr
string root1 = "./samples/dilepton/*"
string base_dir = "./ProjectName/Grift/"
mx = AccuracyMetric()
RunNames
Variables
ana = Analysis()
TrainingDataset
Threads
BatchSize
GraphCache
Validation
Evaluation
Training
Variable Documentation
ana
test_evaluation.ana = Analysis()
Definition at line 56 of file test_evaluation.py.
base_dir
string test_evaluation.base_dir = "./ProjectName/Grift/"
Definition at line 28 of file test_evaluation.py.
BatchSize
test_evaluation.BatchSize
Definition at line 59 of file test_evaluation.py.
device
test_evaluation.device
Definition at line 18 of file test_evaluation.py.
ev
test_evaluation.ev = BSM4Tops()
Definition at line 9 of file test_evaluation.py.
Evaluation
test_evaluation.Evaluation
Definition at line 68 of file test_evaluation.py.
gn
test_evaluation.gn = Grift()
Definition at line 12 of file test_evaluation.py.
gr
test_evaluation.gr = GraphJets()
Definition at line 10 of file test_evaluation.py.
Referenced by sampletracer.add_graph(), container.add_graph_template(), dataloader.build_batch(), container.compile(), dataloader.dump_dataset(), dataloader.dump_graphs(), enums_to_string(), dataloader.extract_data(), model_template.forward(), dataloader.get_inference(), and entry_t.has_graph().
GraphCache
test_evaluation.GraphCache
Definition at line 62 of file test_evaluation.py.
i_graph
test_evaluation.i_graph
Definition at line 17 of file test_evaluation.py.
i_node
test_evaluation.i_node
Definition at line 16 of file test_evaluation.py.
lr
test_evaluation.lr
Definition at line 22 of file test_evaluation.py.
mx
test_evaluation.mx = AccuracyMetric()
Definition at line 29 of file test_evaluation.py.
Referenced by analysis.add_metric_template(), physics_truth.build(), ssml_mc20.CompileEvent(), and graph_.edge_aggregation().
name
test_evaluation.name
Definition at line 13 of file test_evaluation.py.
o_edge
test_evaluation.o_edge
Definition at line 14 of file test_evaluation.py.
o_graph
test_evaluation.o_graph
Definition at line 15 of file test_evaluation.py.
opti
test_evaluation.opti = OptimizerConfig()
Definition at line 20 of file test_evaluation.py.
Optimizer
test_evaluation.Optimizer
Definition at line 21 of file test_evaluation.py.
root1
string test_evaluation.root1 = "./samples/dilepton/*"
Definition at line 25 of file test_evaluation.py.
RunNames
test_evaluation.RunNames
Definition at line 30 of file test_evaluation.py.
Threads
test_evaluation.Threads
Definition at line 58 of file test_evaluation.py.
Training
test_evaluation.Training
Definition at line 69 of file test_evaluation.py.
TrainingDataset
test_evaluation.TrainingDataset
Definition at line 57 of file test_evaluation.py.
Validation
test_evaluation.Validation
Definition at line 67 of file test_evaluation.py.
Variables
test_evaluation.Variables
Definition at line 45 of file test_evaluation.py.