AnalysisG: pyc::physics::polar::separate Namespace Reference
pyc::physics::polar::separate Namespace Reference
Functions
torch::Tensor P2 (torch::Tensor pt, torch::Tensor eta, torch::Tensor phi)
torch::Tensor P (torch::Tensor pt, torch::Tensor eta, torch::Tensor phi)
torch::Tensor Beta2 (torch::Tensor pt, torch::Tensor eta, torch::Tensor phi, torch::Tensor e)
torch::Tensor Beta (torch::Tensor pt, torch::Tensor eta, torch::Tensor phi, torch::Tensor e)
torch::Tensor M2 (torch::Tensor pt, torch::Tensor eta, torch::Tensor phi, torch::Tensor e)
torch::Tensor M (torch::Tensor pt, torch::Tensor eta, torch::Tensor phi, torch::Tensor e)
torch::Tensor Mt2 (torch::Tensor pt, torch::Tensor eta, torch::Tensor e)
torch::Tensor Mt (torch::Tensor pt, torch::Tensor eta, torch::Tensor e)
torch::Tensor Theta (torch::Tensor pt, torch::Tensor eta, torch::Tensor phi)
torch::Tensor DeltaR (torch::Tensor eta1, torch::Tensor eta2, torch::Tensor phi1, torch::Tensor phi2)
Function Documentation
Beta()
torch::Tensor pyc::physics::polar::separate::Beta (torch::Tensor pt, torch::Tensor eta, torch::Tensor phi, torch::Tensor e)
Definition at line 95 of file pyc/interface/physics.cxx.
{
     changedev(&pt);
     torch::Tensor pmc = transform_::PxPyPzE(&pt, &eta, &phi, &e);
     return physics_::Beta(&pmc);
 }
References physics_::Beta(), changedev(), test_particles::e, pmc, and transform_::PxPyPzE().
Beta2()
torch::Tensor pyc::physics::polar::separate::Beta2 (torch::Tensor pt, torch::Tensor eta, torch::Tensor phi, torch::Tensor e)
Definition at line 71 of file pyc/interface/physics.cxx.
{
     changedev(&pt);
     torch::Tensor pmc = transform_::PxPyPzE(&pt, &eta, &phi, &e);
     return physics_::Beta2(&pmc);
 }
References physics_::Beta2(), changedev(), test_particles::e, pmc, and transform_::PxPyPzE().
DeltaR()
torch::Tensor pyc::physics::polar::separate::DeltaR (torch::Tensor eta1, torch::Tensor eta2, torch::Tensor phi1, torch::Tensor phi2)
Definition at line 241 of file pyc/interface/physics.cxx.
  {
     changedev(&eta1);
     return physics_::DeltaR(&eta1, &eta2, &phi1, &phi2);
 }
References changedev(), and physics_::DeltaR().
M()
torch::Tensor pyc::physics::polar::separate::M (torch::Tensor pt, torch::Tensor eta, torch::Tensor phi, torch::Tensor e)
Definition at line 142 of file pyc/interface/physics.cxx.
{
     changedev(&pt);
     torch::Tensor pmc = transform_::PxPyPzE(&pt, &eta, &phi, &e);
     return physics_::M(&pmc);
 }
References changedev(), test_particles::e, physics_::M(), pmc, and transform_::PxPyPzE().
M2()
torch::Tensor pyc::physics::polar::separate::M2 (torch::Tensor pt, torch::Tensor eta, torch::Tensor phi, torch::Tensor e)
Definition at line 119 of file pyc/interface/physics.cxx.
{
     changedev(&pt);
     torch::Tensor pmc = transform_::PxPyPzE(&pt, &eta, &phi, &e);
     return physics_::M2(&pmc);
 }
References changedev(), test_particles::e, physics_::M2(), pmc, and transform_::PxPyPzE().
Mt()
torch::Tensor pyc::physics::polar::separate::Mt (torch::Tensor pt, torch::Tensor eta, torch::Tensor e)
Definition at line 188 of file pyc/interface/physics.cxx.
{
     changedev(&pt);
     torch::Tensor pz = transform_::Pz(&pt, &eta);
     return physics_::Mt(&pz, &e);
 }
References changedev(), test_particles::e, physics_::Mt(), and transform_::Pz().
Mt2()
torch::Tensor pyc::physics::polar::separate::Mt2 (torch::Tensor pt, torch::Tensor eta, torch::Tensor e)
Definition at line 166 of file pyc/interface/physics.cxx.
{
     changedev(&pt);
     torch::Tensor pz = transform_::Pz(&pt, &eta);
     return physics_::Mt2(&pz, &e);
 }
References changedev(), test_particles::e, physics_::Mt2(), and transform_::Pz().
P()
torch::Tensor pyc::physics::polar::separate::P (torch::Tensor pt, torch::Tensor eta, torch::Tensor phi)
Definition at line 47 of file pyc/interface/physics.cxx.
{
     changedev(&pt);
     torch::Tensor pmc = transform_::PxPyPz(&pt, &eta, &phi);
     return physics_::P(&pmc);
 }
References changedev(), physics_::P(), pmc, and transform_::PxPyPz().
P2()
torch::Tensor pyc::physics::polar::separate::P2 (torch::Tensor pt, torch::Tensor eta, torch::Tensor phi)
Definition at line 23 of file pyc/interface/physics.cxx.
{
     changedev(&phi);
     torch::Tensor pmc = transform_::PxPyPz(&pt, &eta, &phi);
     return physics_::P2(&pmc);
 }
References changedev(), physics_::P2(), pmc, and transform_::PxPyPz().
Theta()
torch::Tensor pyc::physics::polar::separate::Theta (torch::Tensor pt, torch::Tensor eta, torch::Tensor phi)
Definition at line 211 of file pyc/interface/physics.cxx.
{
     changedev(&pt);
     torch::Tensor pmc = transform_::PxPyPz(&pt, &eta, &phi);
     return physics_::Theta(&pmc);
 }
References changedev(), pmc, transform_::PxPyPz(), and physics_::Theta().