AnalysisG: pyc::graph::polar Namespace Reference
pyc::graph::polar Namespace Reference
Functions
torch::Dict< std::string, torch::Tensor > edge_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor pmu)
torch::Dict< std::string, torch::Tensor > node_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor pmu)
torch::Dict< std::string, torch::Tensor > edge_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor pt, torch::Tensor eta, torch::Tensor phi, torch::Tensor e)
torch::Dict< std::string, torch::Tensor > node_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor pt, torch::Tensor eta, torch::Tensor phi, torch::Tensor e)
Function Documentation
edge_aggregation() [1/2]
torch::Dict< std::string, torch::Tensor > pyc::graph::polar::edge_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor pmu)
Definition at line 102 of file interface/graph.cxx.
  {
     changedev(&edge_index);
     std::map<std::string, torch::Tensor> out;
     torch::Tensor pmc = transform_::PxPyPzE(&pmu);
     out = graph_::edge_aggregation(&edge_index, &prediction, &pmc);
     return pyc::std_to_dict(&out);
 }
References changedev(), graph_::edge_aggregation(), edge_index, main::out, pmc, pmu(), transform_::PxPyPzE(), and pyc::std_to_dict().
edge_aggregation() [2/2]
torch::Dict< std::string, torch::Tensor > pyc::graph::polar::edge_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor pt, torch::Tensor eta, torch::Tensor phi, torch::Tensor e)
Definition at line 122 of file interface/graph.cxx.
  {
     changedev(&edge_index);
     std::map<std::string, torch::Tensor> out;
     torch::Tensor pmc = transform_::PxPyPzE(&pt, &eta, &phi, &e);
     out = graph_::edge_aggregation(&edge_index, &prediction, &pmc);
     return pyc::std_to_dict(&out);
 }
References changedev(), test_particles::e, graph_::edge_aggregation(), edge_index, main::out, pmc, transform_::PxPyPzE(), and pyc::std_to_dict().
node_aggregation() [1/2]
torch::Dict< std::string, torch::Tensor > pyc::graph::polar::node_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor pmu)
Definition at line 112 of file interface/graph.cxx.
  {
     changedev(&edge_index);
     std::map<std::string, torch::Tensor> out;
     torch::Tensor pmc = transform_::PxPyPzE(&pmu);
     out = graph_::edge_aggregation(&edge_index, &prediction, &pmc);
     return pyc::std_to_dict(&out);
 }
References changedev(), graph_::edge_aggregation(), edge_index, main::out, pmc, pmu(), transform_::PxPyPzE(), and pyc::std_to_dict().
node_aggregation() [2/2]
torch::Dict< std::string, torch::Tensor > pyc::graph::polar::node_aggregation (torch::Tensor edge_index, torch::Tensor prediction, torch::Tensor pt, torch::Tensor eta, torch::Tensor phi, torch::Tensor e)
Definition at line 133 of file interface/graph.cxx.
  {
     changedev(&edge_index);
     std::map<std::string, torch::Tensor> out;
     torch::Tensor pmc = transform_::PxPyPzE(&pt, &eta, &phi, &e);
     out = graph_::node_aggregation(&edge_index, &prediction, &pmc);
     return pyc::std_to_dict(&out);
 }
References changedev(), test_particles::e, edge_index, graph_::node_aggregation(), main::out, pmc, transform_::PxPyPzE(), and pyc::std_to_dict().