AnalysisG: nusol.cxx File Reference
nusol/tensor/nusol.cxx File Reference
#include <operators/operators.h>
#include <transform/transform.h>
#include <physics/physics.h>
#include <utils/utils.h>
#include <nusol/nusol.h>
Functions
std::map< std::string, torch::Tensor > GetMasses (torch::Tensor *L, torch::Tensor *masses)
torch::Tensor _x0 (torch::Tensor *pmc, torch::Tensor *_pm2, torch::Tensor *mH2, torch::Tensor *mL2)
torch::Tensor HorizontalVertical (torch::Tensor *G)
torch::Tensor Parallel (torch::Tensor *G, torch::Tensor *CoF)
torch::Tensor Intersecting (torch::Tensor *G, torch::Tensor *g22, torch::Tensor *CoF)
torch::Tensor Pi_2 (torch::Tensor *x)
torch::Tensor Rotation (torch::Tensor *pmc_b, torch::Tensor *pmc_mu, torch::Tensor *base)
torch::Tensor Shape (torch::Tensor *x, std::vector< int > diag)
torch::Tensor Sigma (torch::Tensor *x, torch::Tensor *sigma)
torch::Tensor _met (torch::Tensor *met_xy)
torch::Tensor _H_perp (torch::Tensor *base)
torch::Tensor _N (torch::Tensor *hperp)
std::map< std::string, torch::Tensor > _xNu (torch::Tensor *pmc_b, torch::Tensor *pmc_mu, torch::Tensor *met_xy, torch::Tensor *masses, torch::Tensor *sigma)
Function Documentation
_H_perp()
torch::Tensor _H_perp (torch::Tensor * base)
Definition at line 183 of file nusol/tensor/nusol.cxx.
{
     torch::Tensor H = base -> clone();
     H.index_put_({torch::indexing::Slice(), 2, torch::indexing::Slice()}, 0);
     H.index_put_({torch::indexing::Slice(), 2, 2}, 1);
     return H;
 }
References clone().
Referenced by nusol_::Hperp(), and nusol_::NuNu().
_met()
torch::Tensor _met (torch::Tensor * met_xy)
Definition at line 176 of file nusol/tensor/nusol.cxx.
{
     torch::Tensor matrix = met_xy -> view({-1, 2});
     matrix = torch::pad(matrix, {0, 1, 0, 0}, "constant", 0).view({-1, 3, 1});
     torch::Tensor t0 = torch::zeros_like(matrix);
     return torch::cat({t0, t0, matrix}, -1);
 }
Referenced by _xNu(), and nusol_::NuNu().
_N()
torch::Tensor _N (torch::Tensor * hperp)
Definition at line 190 of file nusol/tensor/nusol.cxx.
{
     torch::Tensor H = operators_::Inverse(hperp);
     torch::Tensor H_T = torch::transpose(H, 1, 2);
     H_T = torch::matmul(H_T, Shape(&H_T, {1, 1, -1}));
     return torch::matmul(H_T, H);
 }
References operators_::Inverse(), and Shape().
Referenced by nusol_::NuNu().
_x0()
torch::Tensor _x0 (torch::Tensor * pmc, torch::Tensor * _pm2, torch::Tensor * mH2, torch::Tensor * mL2)
Definition at line 20 of file nusol/tensor/nusol.cxx.
{
     torch::Tensor e = pmc -> index({torch::indexing::Slice(), 3}).view({-1, 1});
     return -(*mH2 - *mL2 - *_pm2)/(2*e);
 }
References test_particles::e, and pmc.
Referenced by nusol_::BaseMatrix().
_xNu()
std::map<std::string, torch::Tensor> _xNu (torch::Tensor * pmc_b, torch::Tensor * pmc_mu, torch::Tensor * met_xy, torch::Tensor * masses, torch::Tensor * sigma)
Definition at line 397 of file nusol/tensor/nusol.cxx.
  {
     // Base matrix - the Analytical solutions and constants
     torch::Tensor base = nusol_::BaseMatrix(pmc_b, pmc_mu, masses);
     torch::Tensor H_base = Rotation(pmc_b, pmc_mu, &base);
     torch::Tensor Pi2 = Pi_2(&base);
     torch::Tensor Derivative = operators_::Rz(&Pi2);
     Derivative = Derivative.matmul(Shape(&Pi2, {1, 1, 0}));
     // Invert the input sigma matrix
     torch::Tensor _sigma = Sigma(met_xy, sigma);
     // ------- Convert missing energy matrix into tensor ----- //
     torch::Tensor _met_xy = _met(met_xy);
     // ------- create ellipse ------- //
     torch::Tensor dNu, X_, M_;
     dNu = _met_xy - H_base;
     X_ = torch::matmul(torch::transpose(dNu, 1, 2), _sigma);
     X_ = torch::matmul(X_, dNu).view({-1, 3, 3});
     M_ = X_.matmul(Derivative);
     M_ = M_ + torch::transpose(M_, 1, 2);
     std::map<std::string, torch::Tensor> output;
     output["M"] = M_;
     output["H"] = H_base;
     output["X"] = X_;
     return output;
 }
References _met(), nusol_::BaseMatrix(), nusol::Derivative(), main::masses, Pi_2(), Rotation(), operators_::Rz(), Shape(), and Sigma().
Referenced by nusol_::Nu().
GetMasses()
std::map<std::string, torch::Tensor> GetMasses (torch::Tensor * L, torch::Tensor * masses)
Definition at line 8 of file nusol/tensor/nusol.cxx.
{
     torch::Tensor _masses = masses -> view({-1, 3});
     const unsigned int dim_i = L -> size(0);
     const unsigned int dim_i_ = _masses.size(0);
     if (dim_i != dim_i_){_masses = torch::ones({dim_i, 3}, MakeOp(masses))*_masses[0];}
     std::map<std::string, torch::Tensor> out;
     out["T2"] = torch::pow(_masses.index({torch::indexing::Slice(), 0}), 2).view({dim_i, 1});
     out["W2"] = torch::pow(_masses.index({torch::indexing::Slice(), 1}), 2).view({dim_i, 1});
     out["N2"] = torch::pow(_masses.index({torch::indexing::Slice(), 2}), 2).view({dim_i, 1});
     return out;
 }
References MakeOp(), main::masses, and main::out.
Referenced by nusol_::BaseMatrix().
HorizontalVertical()
torch::Tensor HorizontalVertical (torch::Tensor * G)
Definition at line 25 of file nusol/tensor/nusol.cxx.
{
     torch::Tensor G01 = G -> index({torch::indexing::Slice(), 0, 1}).view({-1, 1, 1});
     torch::Tensor G02 = G -> index({torch::indexing::Slice(), 0, 2}).view({-1, 1, 1});
     torch::Tensor G12 = G -> index({torch::indexing::Slice(), 1, 2}).view({-1, 1, 1});
     torch::Tensor t0 = zeros_like(G01);
     return torch::cat({ G01, t0, G12, t0, G01, G02 - G12, t0, t0, t0}, -1).view({-1, 3, 3});
 }
Referenced by nusol_::Intersection().
Intersecting()
torch::Tensor Intersecting (torch::Tensor * G, torch::Tensor * g22, torch::Tensor * CoF)
Definition at line 67 of file nusol/tensor/nusol.cxx.
{
     std::vector<signed long> dim11 = {-1, 1, 1};
     std::vector<signed long> dim13 = {-1, 1, 3};
     torch::Tensor g02 = CoF -> index({torch::indexing::Slice(), 0, 2});
     torch::Tensor g12 = CoF -> index({torch::indexing::Slice(), 1, 2});
     torch::Tensor x0 = (g02 / *g22);
     torch::Tensor y0 = (g12 / *g22);
     torch::Tensor G11 = G -> index({torch::indexing::Slice(), 1, 1});
     torch::Tensor G01 = G -> index({torch::indexing::Slice(), 0, 1});
     torch::Tensor t0 = torch::zeros_like(G01);
     // Case 1: -g22 < 0 - No Solution  - ignore
     torch::Tensor G_ = torch::zeros_like(*G);
     // Case 2: -g22 == 0 - One Solution
     torch::Tensor _s1 = -(*g22) == 0.;
     torch::Tensor _s1_s = _s1.sum(-1);
     // Case 3; -g22 > 0 - Two Solutions
     torch::Tensor _s2 = -(*g22) > 0.;
     torch::Tensor _s2_s = _s2.sum(-1);
     if (_s1_s.item<int>() > 0)
     {
         // ---------- Case 2 ----------- //
         G_.index_put_({_s1}, torch::cat({
                 G01.index({_s1}).view(dim11),
                 G11.index({_s1}).view(dim11),
                 ((-G11.index({_s1}) * y0.index({_s1})) - (G01.index({_s1}) * x0.index({_s1}))).view(dim11),
                 torch::cat({t0.index({_s1}), t0.index({_s1}), t0.index({_s1})}, -1).view(dim13),
                 torch::cat({t0.index({_s1}), t0.index({_s1}), t0.index({_s1})}, -1).view(dim13)
         }, -1).view({-1, 3, 3}));
     }
     if (_s2_s.item<int>() > 0)
     {
         // ---------- Case 3 ----------- //
         torch::Tensor _s = torch::sqrt(-g22 -> index({_s2}));
         G_.index_put_({_s2}, torch::cat({
                 // Solution 1
                 (G01.index({_s2}) - _s).view(dim11),
                 (G11.index({_s2})).view(dim11),
                 (-G11.index({_s2}) * y0.index({_s2}) - (G01.index({_s2}) - _s) * x0.index({_s2})).view(dim11),
                 // Solution 2
                 (G01.index({_s2}) + _s).view(dim11),
                 (G11.index({_s2})).view(dim11),
                 (-G11.index({_s2}) * y0.index({_s2}) - (G01.index({_s2}) + _s) * x0.index({_s2})).view(dim11),
                 torch::cat({t0.index({_s2}), t0.index({_s2}), t0.index({_s2})}, -1).view(dim13) // Zeros
         }, -1).view({-1, 3, 3}));
     }
     return G_;
 }
Referenced by nusol_::Intersection().
Parallel()
torch::Tensor Parallel (torch::Tensor * G, torch::Tensor * CoF)
Definition at line 33 of file nusol/tensor/nusol.cxx.
{
     torch::Tensor g00 = -CoF -> index({torch::indexing::Slice(), 0, 0});
     torch::Tensor G00 = G -> index({torch::indexing::Slice(), 0, 0});
     torch::Tensor G01 = G -> index({torch::indexing::Slice(), 0, 1});
     torch::Tensor G11 = G -> index({torch::indexing::Slice(), 1, 1});
     torch::Tensor G12 = G -> index({torch::indexing::Slice(), 1, 2});
     torch::Tensor t0 = torch::zeros_like(G12);
     torch::Tensor G_ = torch::zeros_like(*G);
     std::vector<signed long> dims = {-1, 1, 1};
     // ----- Populate cases where g00 is 0
     torch::Tensor y0 = g00 == 0.;
     G_.index_put_({y0}, torch::cat({
                 G01.index({y0}).view(dims), G11.index({y0}).view(dims), G12.index({y0}).view(dims),
                  t0.index({y0}).view(dims),  t0.index({y0}).view(dims),  t0.index({y0}).view(dims),
                  t0.index({y0}).view(dims),  t0.index({y0}).view(dims),  t0.index({y0}).view(dims)
     }, -1).view({-1, 3, 3}));
     // ----- Populate cases where -g00 > 0
     torch::Tensor yr = g00 > 0.;
     G_.index_put_({yr}, torch::cat({
                 G01.index({yr}).view(dims),
                 G11.index({yr}).view(dims),
                 (G12.index({yr}) - torch::sqrt(g00.index({yr}))).view(dims),
                 G01.index({yr}).view(dims),
                 G11.index({yr}).view(dims),
                 (G12.index({yr}) + torch::sqrt(g00.index({yr}))).view(dims),
                 torch::cat({t0.index({yr}), t0.index({yr}), t0.index({yr})}, -1).view({-1, 1, 3})
     }, -1).view({-1, 3, 3}));
     return G_;
 }
Referenced by nusol_::Intersection().
Pi_2()
torch::Tensor Pi_2 (torch::Tensor * x)
Definition at line 123 of file nusol/tensor/nusol.cxx.
{
     torch::TensorOptions op = MakeOp(x);
     const unsigned int dim_i = x -> size(0);
     torch::Tensor z = torch::zeros({dim_i, 1}, op);
     return torch::acos(z);
 }
References MakeOp(), test_generator::op, and main::x.
Referenced by _xNu(), and Rotation().
Rotation()
torch::Tensor Rotation (torch::Tensor * pmc_b, torch::Tensor * pmc_mu, torch::Tensor * base)
Definition at line 130 of file nusol/tensor/nusol.cxx.
{
     torch::Tensor pmc_b3  = pmc_b -> index( {torch::indexing::Slice(), torch::indexing::Slice(0, 3)});
     torch::Tensor pmc_mu3 = pmc_mu -> index({torch::indexing::Slice(), torch::indexing::Slice(0, 3)});
     torch::Tensor muphi = -transform_::Phi(pmc_mu);
     torch::Tensor theta = physics_::Theta(pmc_mu);
     torch::Tensor Rz = operators_::Rz(&muphi);
     torch::Tensor rx = Pi_2(&theta) - theta;
     torch::Tensor Ry = operators_::Ry(&rx);
     torch::Tensor Rx = torch::matmul(Rz, pmc_b3.view({-1, 3, 1}));
     Rx = torch::matmul(Ry, Rx.view({-1, 3, 1}));
     Rx = -torch::atan2(
             Rx.index({torch::indexing::Slice(), 2}),
             Rx.index({torch::indexing::Slice(), 1})
     ).view({-1, 1});
     Rx = operators_::Rx(&Rx);
     Rx = torch::transpose(Rx, 1, 2);
     Ry = torch::transpose(Ry, 1, 2);
     Rz = torch::transpose(Rz, 1, 2);
     return torch::matmul(torch::matmul(Rz, torch::matmul(Ry, Rx)), *base);
 }
References transform_::Phi(), Pi_2(), operators_::Rx(), pyc::operators::Rx(), operators_::Ry(), pyc::operators::Ry(), operators_::Rz(), pyc::operators::Rz(), and physics_::Theta().
Referenced by _xNu(), nusol_::Hperp(), and nusol_::NuNu().
Shape()
torch::Tensor Shape (torch::Tensor * x, std::vector< int > diag)
Definition at line 155 of file nusol/tensor/nusol.cxx.
{
     const torch::TensorOptions op = MakeOp(x);
     torch::Tensor shape = torch::diag(torch::tensor(diag, op)).view({-1, 3, 3});
     torch::Tensor ones = torch::ones({x -> size(0), 3, 3}, op);
     shape = (ones*shape).view({-1, 3, 3});
     return shape;
 }
References MakeOp(), test_generator::op, and main::x.
Referenced by _N(), _xNu(), nusol_::Nu(), and nusol_::NuNu().
Sigma()
torch::Tensor Sigma (torch::Tensor * x, torch::Tensor * sigma)
Definition at line 164 of file nusol/tensor/nusol.cxx.
{
     torch::Tensor _sigma = sigma -> view({-1, 2, 2});
     const unsigned int dim_i = x -> size(0);
     const unsigned int dim_i_ = _sigma.size(0);
     const torch::TensorOptions op = MakeOp(x);
     if (dim_i != dim_i_){_sigma = torch::ones({dim_i, 2, 2}, op) * _sigma[0];}
     _sigma = torch::inverse(_sigma);
     _sigma = torch::pad(_sigma, {0, 1, 0, 1}, "constant", 0);
     _sigma = torch::transpose(_sigma, 1, 2);
     return _sigma;
 }
References MakeOp(), test_generator::op, and main::x.
Referenced by _xNu().