AnalysisG: optimizer_config.cxx File Reference
optimizer_config.cxx File Reference
#include <templates/lossfx.h>
Functions
static void m_xavier_normal (torch::nn::Module &m)
static void m_xavier_uniform (torch::nn::Module &m)
static void m_normal (torch::nn::Module &m)
static void m_uniform (torch::nn::Module &m)
static void m_kaiming_normal (torch::nn::Module &m)
static void m_kaiming_uniform (torch::nn::Module &m)
Function Documentation
m_kaiming_normal()
static void m_kaiming_normal (torch::nn::Module & m) static
Definition at line 99 of file optimizer_config.cxx.
References weight.
Referenced by lossfx::weight_init().
m_kaiming_uniform()
static void m_kaiming_uniform (torch::nn::Module & m) static
Definition at line 106 of file optimizer_config.cxx.
References weight.
Referenced by lossfx::weight_init().
m_normal()
static void m_normal (torch::nn::Module & m) static
Definition at line 84 of file optimizer_config.cxx.
References weight.
Referenced by lossfx::weight_init().
m_uniform()
static void m_uniform (torch::nn::Module & m) static
Definition at line 91 of file optimizer_config.cxx.
References weight.
Referenced by lossfx::weight_init().
m_xavier_normal()
static void m_xavier_normal (torch::nn::Module & m) static
Definition at line 70 of file optimizer_config.cxx.
References weight.
Referenced by lossfx::weight_init().
m_xavier_uniform()
static void m_xavier_uniform (torch::nn::Module & m) static
Definition at line 77 of file optimizer_config.cxx.
References weight.
Referenced by lossfx::weight_init().