AnalysisG: element_t Struct Reference
element_t Struct Reference
#include <element.h>
Public Member Functions
bool next ()
void set_meta ()
bool boundary ()
template<typename g >
bool get (std::string key, g *var)
Public Attributes
std::string tree = ""
long event_index = -1
std::string filename = ""
std::map< std::string, data_t * > handle = {}
Detailed Description
Definition at line 63 of file element.h.
Member Function Documentation
boundary()
bool element_t::boundary ()
Definition at line 19 of file element.cxx.
References get(), and handle.
get()
template<typename g > bool element_t::get (std::string key, g * var) inline
Definition at line 73 of file element.h.
References d, get(), and handle.
Referenced by boundary(), get(), next(), and set_meta().
next()
bool element_t::next ()
Definition at line 12 of file element.cxx.
References get(), handle, and next().
Referenced by next().
set_meta()
void element_t::set_meta ()
Definition at line 4 of file element.cxx.
References event_index, filename, get(), handle, and index.
Member Data Documentation
event_index
long element_t::event_index = -1
Definition at line 68 of file element.h.
Referenced by set_meta().
filename
std::string element_t::filename = ""
Definition at line 69 of file element.h.
Referenced by set_meta().
handle
std::map<std::string, data_t*> element_t::handle = {}
Definition at line 85 of file element.h.
Referenced by boundary(), get(), next(), and set_meta().
tree
std::string element_t::tree = ""
Definition at line 64 of file element.h.
The documentation for this struct was generated from the following files:
element.h
element.cxx