AnalysisG: optimizer_params_t Struct Reference
optimizer_params_t Struct Reference
Configuration parameters for PyTorch optimizers.
#include <optimizer.h>
Public Member Functions
void operator() ()
Initializes property callbacks.
Static Public Member Functions
static void set_eps (double *, optimizer_params_t *obj)
Setter for eps.
static void set_lr (double *, optimizer_params_t *obj)
Setter for lr.
static void set_lr_decay (double *, optimizer_params_t *obj)
Setter for lr_decay.
static void set_weight_decay (double *, optimizer_params_t *obj)
Setter for weight_decay.
static void set_initial_accumulator_value (double *, optimizer_params_t *obj)
Setter for initial_accumulator_value.
static void set_beta_hack (std::vector< float > *val, optimizer_params_t *obj)
Setter for beta_hack.
static void set_betas (std::tuple< float, float > *, optimizer_params_t *obj)
Setter for betas.
static void set_amsgrad (bool *, optimizer_params_t *obj)
Setter for amsgrad.
static void set_max_iter (int *, optimizer_params_t *obj)
Setter for max_iter.
static void set_max_eval (int *, optimizer_params_t *obj)
Setter for max_eval.
static void set_tolerance_grad (double *, optimizer_params_t *obj)
Setter for tolerance_grad.
static void set_tolerance_change (double *, optimizer_params_t *obj)
Setter for tolerance_change.
static void set_history_size (int *, optimizer_params_t *obj)
Setter for history_size.
static void set_centered (bool *, optimizer_params_t *obj)
Setter for centered.
static void set_nesterov (bool *, optimizer_params_t *obj)
Setter for nesterov.
static void set_alpha (double *, optimizer_params_t *obj)
Setter for alpha.
static void set_momentum (double *, optimizer_params_t *obj)
Setter for momentum.
static void set_dampening (double *, optimizer_params_t *obj)
Setter for dampening.
Public Attributes
std::string optimizer = ""
Optimizer type ("Adam", "SGD", "Adagrad", "LBFGS", "RMSprop").
cproperty< double, optimizer_params_t > lr
Learning rate.
cproperty< double, optimizer_params_t > lr_decay
Learning rate decay factor.
cproperty< double, optimizer_params_t > weight_decay
L2 regularization coefficient.
cproperty< double, optimizer_params_t > initial_accumulator_value
Initial accumulator value (Adagrad).
cproperty< double, optimizer_params_t > eps
Epsilon for numerical stability.
cproperty< double, optimizer_params_t > tolerance_grad
Gradient tolerance (LBFGS).
cproperty< double, optimizer_params_t > tolerance_change
Function value change tolerance (LBFGS).
cproperty< double, optimizer_params_t > alpha
Smoothing constant (RMSprop).
cproperty< double, optimizer_params_t > momentum
Momentum factor (SGD, RMSprop).
cproperty< double, optimizer_params_t > dampening
Dampening for momentum (SGD).
cproperty< bool, optimizer_params_t > amsgrad
Use AMSGrad variant (Adam).
cproperty< bool, optimizer_params_t > centered
Compute centered RMSprop.
cproperty< bool, optimizer_params_t > nesterov
Use Nesterov momentum (SGD).
cproperty< int, optimizer_params_t > max_iter
Maximum iterations per step (LBFGS).
cproperty< int, optimizer_params_t > max_eval
Maximum evaluations per step (LBFGS).
cproperty< int, optimizer_params_t > history_size
History size for LBFGS.
cproperty< std::tuple< float, float >, optimizer_params_t > betas
Beta coefficients (beta1, beta2) for Adam.
cproperty< std::vector< float >, optimizer_params_t > beta_hack
Alternative beta specification as vector.
bool m_lr = false
Flag: lr has been set.
bool m_lr_decay = false
Flag: lr_decay has been set.
bool m_weight_decay = false
Flag: weight_decay has been set.
bool m_initial_accumulator_value = false
Flag: initial_accumulator_value has been set.
bool m_eps = false
Flag: eps has been set.
bool m_betas = false
Flag: betas has been set.
bool m_amsgrad = false
Flag: amsgrad has been set.
bool m_max_iter = false
Flag: max_iter has been set.
bool m_max_eval = false
Flag: max_eval has been set.
bool m_tolerance_grad = false
Flag: tolerance_grad has been set.
bool m_tolerance_change = false
Flag: tolerance_change has been set.
bool m_history_size = false
Flag: history_size has been set.
bool m_alpha = false
Flag: alpha has been set.
bool m_momentum = false
Flag: momentum has been set.
bool m_centered = false
Flag: centered has been set.
bool m_dampening = false
Flag: dampening has been set.
bool m_nesterov = false
Flag: nesterov has been set.
Detailed Description
Configuration parameters for PyTorch optimizers.
This structure contains all the parameters needed to configure different optimizer types in PyTorch. Parameters are exposed as cproperty objects for seamless Python integration via Cython.
Supported Optimizer Types
Set the optimizer member to one of:
"Adam": Adam optimizer
"SGD": Stochastic Gradient Descent
"Adagrad": Adaptive gradient
"LBFGS": Limited-memory BFGS
"RMSprop": RMSprop optimizer
Usage Example
optimizer_params_t params;
params.optimizer = "Adam";
params.lr = 0.001;
params.weight_decay = 1e-5;
params.betas = {0.9, 0.999};
params.amsgrad = true;
params();  // Initialize property callbacks
// Use with model
analysis ana;
ana.add_model(new MyModel(), &params, "training_run");
Adam Parameters
For Adam optimizer, configure:
lr: Learning rate (required)
betas: Tuple of (beta1, beta2) for momentum terms
eps: Epsilon for numerical stability
weight_decay: L2 penalty coefficient
amsgrad: Whether to use AMSGrad variant
SGD Parameters
For SGD optimizer, configure:
lr: Learning rate (required)
momentum: Momentum factor
weight_decay: L2 penalty coefficient
dampening: Dampening for momentum
nesterov: Whether to enable Nesterov momentum
LBFGS Parameters
For LBFGS optimizer, configure:
lr: Learning rate (required)
max_iter: Maximum iterations per optimization step
max_eval: Maximum function evaluations per step
tolerance_grad: Termination tolerance on gradient norm
tolerance_change: Termination tolerance on function value change
history_size: Number of previous gradients to store
Definition at line 77 of file structs/include/structs/optimizer.h.
Member Function Documentation
operator()()
void optimizer_params_t::operator() ()
Initializes property callbacks.
Must be called after construction to set up getters/setters.
Definition at line 3 of file structs/cxx/optimizer.cxx.
References alpha, amsgrad, beta_hack, betas, centered, dampening, eps, history_size, initial_accumulator_value, lr, lr_decay, max_eval, max_iter, momentum, nesterov, set_alpha(), set_amsgrad(), set_beta_hack(), set_betas(), set_centered(), set_dampening(), set_eps(), set_history_size(), set_initial_accumulator_value(), set_lr(), set_lr_decay(), set_max_eval(), set_max_iter(), set_momentum(), set_nesterov(), cproperty< T, G >::set_object(), cproperty< T, G >::set_setter(), set_tolerance_change(), set_tolerance_grad(), set_weight_decay(), tolerance_change, tolerance_grad, and weight_decay.
set_alpha()
void optimizer_params_t::set_alpha (double * , optimizer_params_t * obj) static
Setter for alpha.
Definition at line 73 of file structs/cxx/optimizer.cxx.
References m_alpha.
Referenced by operator()().
set_amsgrad()
void optimizer_params_t::set_amsgrad (bool * , optimizer_params_t * obj) static
Setter for amsgrad.
Definition at line 65 of file structs/cxx/optimizer.cxx.
References m_amsgrad.
Referenced by operator()().
set_beta_hack()
void optimizer_params_t::set_beta_hack (std::vector< float > * val, optimizer_params_t * obj) static
Setter for beta_hack.
Definition at line 76 of file structs/cxx/optimizer.cxx.
References betas.
Referenced by operator()().
set_betas()
void optimizer_params_t::set_betas (std::tuple< float, float > * , optimizer_params_t * obj) static
Setter for betas.
Definition at line 64 of file structs/cxx/optimizer.cxx.
References m_betas.
Referenced by operator()().
set_centered()
void optimizer_params_t::set_centered (bool * , optimizer_params_t * obj) static
Setter for centered.
Definition at line 71 of file structs/cxx/optimizer.cxx.
References m_centered.
Referenced by operator()().
set_dampening()
void optimizer_params_t::set_dampening (double * , optimizer_params_t * obj) static
Setter for dampening.
Definition at line 75 of file structs/cxx/optimizer.cxx.
References m_dampening.
Referenced by operator()().
set_eps()
void optimizer_params_t::set_eps (double * , optimizer_params_t * obj) static
Setter for eps.
Definition at line 63 of file structs/cxx/optimizer.cxx.
References m_eps.
Referenced by operator()().
set_history_size()
void optimizer_params_t::set_history_size (int * , optimizer_params_t * obj) static
Setter for history_size.
Definition at line 70 of file structs/cxx/optimizer.cxx.
References m_history_size.
Referenced by operator()().
set_initial_accumulator_value()
void optimizer_params_t::set_initial_accumulator_value (double * , optimizer_params_t * obj) static
Setter for initial_accumulator_value.
Definition at line 62 of file structs/cxx/optimizer.cxx.
References m_initial_accumulator_value.
Referenced by operator()().
set_lr()
void optimizer_params_t::set_lr (double * , optimizer_params_t * obj) static
Setter for lr.
Definition at line 59 of file structs/cxx/optimizer.cxx.
References m_lr.
Referenced by operator()().
set_lr_decay()
void optimizer_params_t::set_lr_decay (double * , optimizer_params_t * obj) static
Setter for lr_decay.
Definition at line 60 of file structs/cxx/optimizer.cxx.
References m_lr_decay.
Referenced by operator()().
set_max_eval()
void optimizer_params_t::set_max_eval (int * , optimizer_params_t * obj) static
Setter for max_eval.
Definition at line 67 of file structs/cxx/optimizer.cxx.
References m_max_eval.
Referenced by operator()().
set_max_iter()
void optimizer_params_t::set_max_iter (int * , optimizer_params_t * obj) static
Setter for max_iter.
Definition at line 66 of file structs/cxx/optimizer.cxx.
References m_max_iter.
Referenced by operator()().
set_momentum()
void optimizer_params_t::set_momentum (double * , optimizer_params_t * obj) static
Setter for momentum.
Definition at line 74 of file structs/cxx/optimizer.cxx.
References m_momentum.
Referenced by operator()().
set_nesterov()
void optimizer_params_t::set_nesterov (bool * , optimizer_params_t * obj) static
Setter for nesterov.
Definition at line 72 of file structs/cxx/optimizer.cxx.
References m_nesterov.
Referenced by operator()().
set_tolerance_change()
void optimizer_params_t::set_tolerance_change (double * , optimizer_params_t * obj) static
Setter for tolerance_change.
Definition at line 69 of file structs/cxx/optimizer.cxx.
References m_tolerance_change.
Referenced by operator()().
set_tolerance_grad()
void optimizer_params_t::set_tolerance_grad (double * , optimizer_params_t * obj) static
Setter for tolerance_grad.
Definition at line 68 of file structs/cxx/optimizer.cxx.
References m_tolerance_grad.
Referenced by operator()().
set_weight_decay()
void optimizer_params_t::set_weight_decay (double * , optimizer_params_t * obj) static
Setter for weight_decay.
Definition at line 61 of file structs/cxx/optimizer.cxx.
References m_weight_decay.
Referenced by operator()().
Member Data Documentation
alpha
cproperty<double, optimizer_params_t> optimizer_params_t::alpha
Smoothing constant (RMSprop).
Definition at line 87 of file structs/include/structs/optimizer.h.
Referenced by operator()().
amsgrad
cproperty<bool, optimizer_params_t> optimizer_params_t::amsgrad
Use AMSGrad variant (Adam).
Definition at line 91 of file structs/include/structs/optimizer.h.
Referenced by operator()().
beta_hack
cproperty<std::vector<float>, optimizer_params_t> optimizer_params_t::beta_hack
Alternative beta specification as vector.
Definition at line 100 of file structs/include/structs/optimizer.h.
Referenced by operator()().
betas
cproperty<std::tuple<float, float>, optimizer_params_t> optimizer_params_t::betas
Beta coefficients (beta1, beta2) for Adam.
Definition at line 99 of file structs/include/structs/optimizer.h.
Referenced by operator()(), and set_beta_hack().
centered
cproperty<bool, optimizer_params_t> optimizer_params_t::centered
Compute centered RMSprop.
Definition at line 92 of file structs/include/structs/optimizer.h.
Referenced by operator()().
dampening
cproperty<double, optimizer_params_t> optimizer_params_t::dampening
Dampening for momentum (SGD).
Definition at line 89 of file structs/include/structs/optimizer.h.
Referenced by operator()().
eps
cproperty<double, optimizer_params_t> optimizer_params_t::eps
Epsilon for numerical stability.
Definition at line 84 of file structs/include/structs/optimizer.h.
Referenced by operator()().
history_size
cproperty<int, optimizer_params_t> optimizer_params_t::history_size
History size for LBFGS.
Definition at line 97 of file structs/include/structs/optimizer.h.
Referenced by operator()().
initial_accumulator_value
cproperty<double, optimizer_params_t> optimizer_params_t::initial_accumulator_value
Initial accumulator value (Adagrad).
Definition at line 83 of file structs/include/structs/optimizer.h.
Referenced by operator()().
lr
cproperty<double, optimizer_params_t> optimizer_params_t::lr
Learning rate.
Definition at line 80 of file structs/include/structs/optimizer.h.
Referenced by operator()().
lr_decay
cproperty<double, optimizer_params_t> optimizer_params_t::lr_decay
Learning rate decay factor.
Definition at line 81 of file structs/include/structs/optimizer.h.
Referenced by operator()().
m_alpha
bool optimizer_params_t::m_alpha = false
Flag: alpha has been set.
Definition at line 115 of file structs/include/structs/optimizer.h.
Referenced by set_alpha().
m_amsgrad
bool optimizer_params_t::m_amsgrad = false
Flag: amsgrad has been set.
Definition at line 109 of file structs/include/structs/optimizer.h.
Referenced by set_amsgrad().
m_betas
bool optimizer_params_t::m_betas = false
Flag: betas has been set.
Definition at line 108 of file structs/include/structs/optimizer.h.
Referenced by set_betas().
m_centered
bool optimizer_params_t::m_centered = false
Flag: centered has been set.
Definition at line 117 of file structs/include/structs/optimizer.h.
Referenced by set_centered().
m_dampening
bool optimizer_params_t::m_dampening = false
Flag: dampening has been set.
Definition at line 118 of file structs/include/structs/optimizer.h.
Referenced by set_dampening().
m_eps
bool optimizer_params_t::m_eps = false
Flag: eps has been set.
Definition at line 107 of file structs/include/structs/optimizer.h.
Referenced by set_eps().
m_history_size
bool optimizer_params_t::m_history_size = false
Flag: history_size has been set.
Definition at line 114 of file structs/include/structs/optimizer.h.
Referenced by set_history_size().
m_initial_accumulator_value
bool optimizer_params_t::m_initial_accumulator_value = false
Flag: initial_accumulator_value has been set.
Definition at line 106 of file structs/include/structs/optimizer.h.
Referenced by set_initial_accumulator_value().
m_lr
bool optimizer_params_t::m_lr = false
Flag: lr has been set.
Definition at line 103 of file structs/include/structs/optimizer.h.
Referenced by set_lr().
m_lr_decay
bool optimizer_params_t::m_lr_decay = false
Flag: lr_decay has been set.
Definition at line 104 of file structs/include/structs/optimizer.h.
Referenced by set_lr_decay().
m_max_eval
bool optimizer_params_t::m_max_eval = false
Flag: max_eval has been set.
Definition at line 111 of file structs/include/structs/optimizer.h.
Referenced by set_max_eval().
m_max_iter
bool optimizer_params_t::m_max_iter = false
Flag: max_iter has been set.
Definition at line 110 of file structs/include/structs/optimizer.h.
Referenced by set_max_iter().
m_momentum
bool optimizer_params_t::m_momentum = false
Flag: momentum has been set.
Definition at line 116 of file structs/include/structs/optimizer.h.
Referenced by set_momentum().
m_nesterov
bool optimizer_params_t::m_nesterov = false
Flag: nesterov has been set.
Definition at line 119 of file structs/include/structs/optimizer.h.
Referenced by set_nesterov().
m_tolerance_change
bool optimizer_params_t::m_tolerance_change = false
Flag: tolerance_change has been set.
Definition at line 113 of file structs/include/structs/optimizer.h.
Referenced by set_tolerance_change().
m_tolerance_grad
bool optimizer_params_t::m_tolerance_grad = false
Flag: tolerance_grad has been set.
Definition at line 112 of file structs/include/structs/optimizer.h.
Referenced by set_tolerance_grad().
m_weight_decay
bool optimizer_params_t::m_weight_decay = false
Flag: weight_decay has been set.
Definition at line 105 of file structs/include/structs/optimizer.h.
Referenced by set_weight_decay().
max_eval
cproperty<int, optimizer_params_t> optimizer_params_t::max_eval
Maximum evaluations per step (LBFGS).
Definition at line 96 of file structs/include/structs/optimizer.h.
Referenced by operator()().
max_iter
cproperty<int, optimizer_params_t> optimizer_params_t::max_iter
Maximum iterations per step (LBFGS).
Definition at line 95 of file structs/include/structs/optimizer.h.
Referenced by operator()().
momentum
cproperty<double, optimizer_params_t> optimizer_params_t::momentum
Momentum factor (SGD, RMSprop).
Definition at line 88 of file structs/include/structs/optimizer.h.
Referenced by operator()().
nesterov
cproperty<bool, optimizer_params_t> optimizer_params_t::nesterov
Use Nesterov momentum (SGD).
Definition at line 93 of file structs/include/structs/optimizer.h.
Referenced by operator()().
optimizer
std::string optimizer_params_t::optimizer = ""
Optimizer type ("Adam", "SGD", "Adagrad", "LBFGS", "RMSprop").
Definition at line 78 of file structs/include/structs/optimizer.h.
tolerance_change
cproperty<double, optimizer_params_t> optimizer_params_t::tolerance_change
Function value change tolerance (LBFGS).
Definition at line 86 of file structs/include/structs/optimizer.h.
Referenced by operator()().
tolerance_grad
cproperty<double, optimizer_params_t> optimizer_params_t::tolerance_grad
Gradient tolerance (LBFGS).
Definition at line 85 of file structs/include/structs/optimizer.h.
Referenced by operator()().
weight_decay
cproperty<double, optimizer_params_t> optimizer_params_t::weight_decay
L2 regularization coefficient.
Definition at line 82 of file structs/include/structs/optimizer.h.
Referenced by operator()().
The documentation for this struct was generated from the following files:
structs/include/structs/optimizer.h
structs/cxx/optimizer.cxx