AnalysisG: base.cxx File Reference
base.cxx File Reference
Implementation of the bsc_t class and related utilities.
#include <structs/base.h>
#include <TInterpreter.h>
#include <iostream>
Functions
void buildDict (std::string _name, std::string _shrt)
Builds a dictionary for the given type name.
void registerInclude (std::string pth, bool is_abs)
Registers an include path with the interpreter.
void buildPCM (std::string name, std::string incl, bool exl)
Builds a PCM file for the given type.
void buildAll ()
Builds all required dictionaries.
int count (const std::string *str, const std::string sub)
Counts occurrences of a substring in a string.
Detailed Description
Implementation of the bsc_t class and related utilities.
This file contains methods for type translation, buffer management, and dictionary building.
Definition in file structs/cxx/base.cxx.
Function Documentation
buildAll()
void buildAll ()
Builds all required dictionaries.
Initiates the build of all dictionaries and PCM files.
Definition at line 53 of file structs/cxx/base.cxx.
References buildPCM().
Referenced by analysis::analysis(), and io::trigger_pcm().
buildDict()
void buildDict (std::string _name, std::string _shrt)
Builds a dictionary for the given type name.
Builds a dictionary for a specific data type.
Parameters
_name The type name.
_shrt The include directive.
Definition at line 18 of file structs/cxx/base.cxx.
Referenced by analysis::analysis(), buildPCM(), and io::trigger_pcm().
buildPCM()
void buildPCM (std::string name, std::string incl, bool exl)
Builds a PCM file for the given type.
Builds a Precompiled Module (PCM) file for a specific module.
Parameters
name The type name.
incl The include directive.
exl Whether to exclude from build.
Definition at line 43 of file structs/cxx/base.cxx.
References buildDict().
Referenced by buildAll().
count()
int count (const std::string * str, const std::string sub)
Counts occurrences of a substring in a string.
Counts occurrences of a substring within a string.
Parameters
str The string to search in.
sub The substring to search for.
Returns
Number of occurrences.
Definition at line 98 of file structs/cxx/base.cxx.
References count().
Referenced by analysis::build_metric(), plotting::build_ROC(), analysis::check_cache(), dataloader::clean_data_elements(), gnn_event::CompileEvent(), count(), dataloader::dump_graphs(), particle_template::get_children(), particle_template::get_parents(), ssml_mc20::match_object(), write_t::process(), graph_t::return_any(), io::root_begin(), bsc_t::root_type_translate(), analysis::safe_clone(), and io::scan_keys().
registerInclude()
void registerInclude (std::string pth, bool is_abs)
Registers an include path with the interpreter.
Parameters
pth The path to include.
is_abs Whether the path is absolute.
Definition at line 29 of file structs/cxx/base.cxx.