AnalysisG: variable_t Struct Reference
variable_t Struct Reference
#include <vector_cast.h>
Public Member Functions
variable_t ()
variable_t (bool use_external)
~variable_t () override
void create_meta (meta_t *mt)
void build_switch (size_t s, torch::Tensor *tx)
void process (torch::Tensor *data, std::string *varname, TTree *tr)
void process (std::vector< std::vector< float >> *data, std::string *varname, TTree *tr)
void process (std::vector< std::vector< double >> *data, std::string *varname, TTree *tr)
void process (std::vector< std::vector< long >> *data, std::string *varname, TTree *tr)
void process (std::vector< std::vector< int >> *data, std::string *varname, TTree *tr)
void process (std::vector< std::vector< bool >> *data, std::string *varname, TTree *tr)
void process (std::vector< float > *data, std::string *varname, TTree *tr)
void process (std::vector< double > *data, std::string *varname, TTree *tr)
void process (std::vector< long > *data, std::string *varname, TTree *tr)
void process (std::vector< int > *data, std::string *varname, TTree *tr)
void process (std::vector< bool > *data, std::string *varname, TTree *tr)
void process (float *data, std::string *varname, TTree *tr)
void process (double *data, std::string *varname, TTree *tr)
void process (long *data, std::string *varname, TTree *tr)
void process (int *data, std::string *varname, TTree *tr)
void process (bool *data, std::string *varname, TTree *tr)
Public Member Functions inherited from bsc_t
bsc_t ()
Constructor for the bsc_t class.
~bsc_t ()
Destructor for the bsc_t class.
data_enum root_type_translate (std::string *root_str)
Translates a ROOT type string to an internal data enumeration.
std::string as_string ()
Represents the object's state as a string.
std::string scan_buffer ()
Scans and returns the current buffer content.
void flush_buffer ()
Clears the internal buffer.
Public Attributes
std::string variable_name = ""
bool failed_branch = false
Public Attributes inherited from bsc_t
std::string buffer
Internal buffer for accumulating textual data.
Detailed Description
Definition at line 63 of file vector_cast.h.
Constructor & Destructor Documentation
variable_t() [1/2]
variable_t::variable_t ()
Definition at line 10 of file typecasting.cxx.
 {}
variable_t() [2/2]
variable_t::variable_t (bool use_external)
Definition at line 11 of file typecasting.cxx.
 { this -> use_external = ux;}
~variable_t()
variable_t::~variable_t () override
Definition at line 12 of file typecasting.cxx.
{
     if (this -> type == data_enum::unset){return;}
     this -> clear = true;
     this -> flush_buffer();
 }
References bsc_t::flush_buffer(), and unset.
Member Function Documentation
build_switch()
void variable_t::build_switch (size_t s, torch::Tensor * tx)
Definition at line 30 of file typecasting.cxx.
{
     // ======================= DEFINE YOUR VARIABLES HERE!!! (1) ========================= //
     // type and dim switch for the tensors
     // ---------- Two dimensional matrices ------------
     if      (s == 3 && tx -> dtype() == torch::kDouble ){this -> type = data_enum::vvv_d;}
     else if (s == 3 && tx -> dtype() == torch::kFloat32){this -> type = data_enum::vvv_f;}
     else if (s == 3 && tx -> dtype() == torch::kLong   ){this -> type = data_enum::vvv_l;}
     else if (s == 3 && tx -> dtype() == torch::kInt    ){this -> type = data_enum::vvv_i;}
     else if (s == 3 && tx -> dtype() == torch::kBool   ){this -> type = data_enum::vvv_b;}
     // ---------- Two dimensional matrices ------------
     else if (s == 2 && tx -> dtype() == torch::kDouble ){this -> type = data_enum::vv_d;}
     else if (s == 2 && tx -> dtype() == torch::kFloat32){this -> type = data_enum::vv_f;}
     else if (s == 2 && tx -> dtype() == torch::kLong   ){this -> type = data_enum::vv_l;}
     else if (s == 2 && tx -> dtype() == torch::kInt    ){this -> type = data_enum::vv_i;}
     else if (s == 2 && tx -> dtype() == torch::kBool   ){this -> type = data_enum::vv_b;}
     // ---------- One dimensional matrices ------------
     else if (s == 1 && tx -> dtype() == torch::kDouble ){this -> type = data_enum::v_d; }
     else if (s == 1 && tx -> dtype() == torch::kFloat32){this -> type = data_enum::v_f; }
     else if (s == 1 && tx -> dtype() == torch::kLong   ){this -> type = data_enum::v_l; }
     else if (s == 1 && tx -> dtype() == torch::kInt    ){this -> type = data_enum::v_i; }
     else if (s == 1 && tx -> dtype() == torch::kBool   ){this -> type = data_enum::v_b; }
     else {this -> type = data_enum::undef;}
     if (this -> type != data_enum::undef){return;}
     std::cout << "DIM: " << s << std::endl;
     std::cout << "Tensor Type: " << tx -> dtype() << std::endl;
     std::cout << *tx << std::endl;
     std::cout << "UNDEFINED DATA TYPE! SEE typecasting/cxx/typecasting.cxx" << std::endl;
     abort();
     // then go to modules/structs/base.h -> data_enum and add your type.
     // =================================================================================== //
 }
References undef, v_b, v_d, v_f, v_i, v_l, vv_b, vv_d, vv_f, vv_i, vv_l, vvv_b, vvv_d, vvv_f, vvv_i, and vvv_l.
Referenced by process().
create_meta()
void variable_t::create_meta (meta_t * mt)
Definition at line 18 of file typecasting.cxx.
{
     if (mtf){this -> mtx = mtf;}
     if (!this -> mtx){return;}
     this -> tt = new TTree("MetaData", "meta");
     this -> tt -> Branch("MetaData", mtf);
     this -> tt -> Fill();
     this -> tt -> Write("", TObject::kOverwrite);
     delete this -> tt;
     this -> tt = nullptr;
     this -> mtx = nullptr;
 }
Referenced by process().
process() [1/16]
void variable_t::process (bool * data, std::string * varname, TTree * tr)
Definition at line 59 of file typecasting/cxx/root.cxx.
{
     this -> add_data(data, this -> b, varname, tr);
 }
References b, and simply_plot::data.
process() [2/16]
void variable_t::process (double * data, std::string * varname, TTree * tr)
Definition at line 47 of file typecasting/cxx/root.cxx.
{
     this -> add_data(data, this -> d, varname, tr);
 }
References d, and simply_plot::data.
process() [3/16]
void variable_t::process (float * data, std::string * varname, TTree * tr)
Definition at line 43 of file typecasting/cxx/root.cxx.
{
     this -> add_data(data, this -> f, varname, tr);
 }
References simply_plot::data, and f.
process() [4/16]
void variable_t::process (int * data, std::string * varname, TTree * tr)
Definition at line 55 of file typecasting/cxx/root.cxx.
{
     this -> add_data(data, this -> i, varname, tr);
 }
References simply_plot::data, and i.
process() [5/16]
void variable_t::process (long * data, std::string * varname, TTree * tr)
Definition at line 51 of file typecasting/cxx/root.cxx.
{
     this -> add_data(data, this -> l, varname, tr);
 }
References simply_plot::data, and l.
process() [6/16]
void variable_t::process (std::vector< bool > * data, std::string * varname, TTree * tr)
Definition at line 39 of file typecasting/cxx/root.cxx.
{
     this -> add_data(data, this -> v_b, varname, tr);
 }
References simply_plot::data, and v_b.
process() [7/16]
void variable_t::process (std::vector< double > * data, std::string * varname, TTree * tr)
Definition at line 27 of file typecasting/cxx/root.cxx.
{
     this -> add_data(data, this -> v_d, varname, tr);
 }
References simply_plot::data, and v_d.
process() [8/16]
void variable_t::process (std::vector< float > * data, std::string * varname, TTree * tr)
Definition at line 23 of file typecasting/cxx/root.cxx.
{
     this -> add_data(data, this -> v_f, varname, tr);
 }
References simply_plot::data, and v_f.
process() [9/16]
void variable_t::process (std::vector< int > * data, std::string * varname, TTree * tr)
Definition at line 35 of file typecasting/cxx/root.cxx.
{
     this -> add_data(data, this -> v_i, varname, tr);
 }
References simply_plot::data, and v_i.
process() [10/16]
void variable_t::process (std::vector< long > * data, std::string * varname, TTree * tr)
Definition at line 31 of file typecasting/cxx/root.cxx.
{
     this -> add_data(data, this -> v_l, varname, tr);
 }
References simply_plot::data, and v_l.
process() [11/16]
void variable_t::process (std::vector< std::vector< bool >> * data, std::string * varname, TTree * tr)
Definition at line 19 of file typecasting/cxx/root.cxx.
{
     this -> add_data(data, this -> vv_b, varname, tr);
 }
References simply_plot::data, and vv_b.
process() [12/16]
void variable_t::process (std::vector< std::vector< double >> * data, std::string * varname, TTree * tr)
Definition at line 7 of file typecasting/cxx/root.cxx.
{
     this -> add_data(data, this -> vv_d, varname, tr);
 }
References simply_plot::data, and vv_d.
process() [13/16]
void variable_t::process (std::vector< std::vector< float >> * data, std::string * varname, TTree * tr)
Definition at line 3 of file typecasting/cxx/root.cxx.
{
     this -> add_data(data, this -> vv_f, varname, tr);
 }
References simply_plot::data, and vv_f.
process() [14/16]
void variable_t::process (std::vector< std::vector< int >> * data, std::string * varname, TTree * tr)
Definition at line 15 of file typecasting/cxx/root.cxx.
{
     this -> add_data(data, this -> vv_i, varname, tr);
 }
References simply_plot::data, and vv_i.
process() [15/16]
void variable_t::process (std::vector< std::vector< long >> * data, std::string * varname, TTree * tr)
Definition at line 11 of file typecasting/cxx/root.cxx.
{
     this -> add_data(data, this -> vv_l, varname, tr);
 }
References simply_plot::data, and vv_l.
process() [16/16]
void variable_t::process (torch::Tensor * data, std::string * varname, TTree * tr)
Definition at line 67 of file typecasting.cxx.
{
     std::vector<signed long> s = tensor_size(data);
     if (this -> type == data_enum::unset && varname){
         this -> build_switch(s.size(), data);
         this -> variable_name = *varname;
     }
     if (!this -> tt && tr){
         this -> create_meta(nullptr);
         this -> tt = tr;
     }
     this -> flush_buffer();
     // ============================== Add your type (5) ==================================== //
     switch(this -> type){
         case data_enum::vv_d: this -> add_data(this -> vv_d, data, &s, double(0)); break;
         case data_enum::vv_f: this -> add_data(this -> vv_f, data, &s, float(0) ); break;
         case data_enum::vv_l: this -> add_data(this -> vv_l, data, &s, long(0)  ); break;
         case data_enum::vv_i: this -> add_data(this -> vv_i, data, &s, int(0)   ); break;
         case data_enum::vv_b: this -> add_data(this -> vv_b, data, &s, bool(0)  ); break;
         case data_enum::v_d:  this -> add_data(this ->  v_d, data, &s, double(0)); break;
         case data_enum::v_f:  this -> add_data(this ->  v_f, data, &s, float(0) ); break;
         case data_enum::v_l:  this -> add_data(this ->  v_l, data, &s, long(0)  ); break;
         case data_enum::v_i:  this -> add_data(this ->  v_i, data, &s, int(0)   ); break;
         case data_enum::v_b:  this -> add_data(this ->  v_b, data, &s, bool(0)  ); break;
         default: break;
     }
     // ===================================================================================== //
     if (!this -> tt || !this -> tb || !this -> is_triggered){return;}
     if (this -> is_triggered){this -> tt -> AddBranchToCache(this -> tb, true);}
     this -> is_triggered = false;
 }
References build_switch(), create_meta(), simply_plot::data, bsc_t::flush_buffer(), tensor_size(), unset, v_b, v_d, v_f, v_i, v_l, variable_name, vv_b, vv_d, vv_f, vv_i, and vv_l.
Member Data Documentation
failed_branch
bool variable_t::failed_branch = false
Definition at line 95 of file vector_cast.h.
variable_name
std::string variable_t::variable_name = ""
Definition at line 94 of file vector_cast.h.
Referenced by process().
The documentation for this struct was generated from the following files:
vector_cast.h
typecasting/cxx/root.cxx
typecasting.cxx