AnalysisG: data_t Struct Reference
data_t Struct Reference
#include <element.h>
Public Member Functions
data_t ()
~data_t () override
void initialize ()
void flush ()
bool next ()
data_enum root_type_translate (std::string *root_str)
Translates a ROOT type string to an internal data enumeration.
std::string as_string ()
Represents the object's state as a string.
std::string scan_buffer ()
Scans and returns the current buffer content.
void flush_buffer ()
Clears the internal buffer.
Public Attributes
std::string leaf_name = ""
std::string branch_name = ""
std::string tree_name = ""
std::string leaf_type = ""
std::string path = ""
std::string * fname = nullptr
TLeaf * leaf = nullptr
TBranch * branch = nullptr
TTree * tree = nullptr
TFile * file = nullptr
int file_index = 0
std::vector< std::string > * files_s = nullptr
std::vector< long > * files_i = nullptr
std::vector< TFile * > * files_t = nullptr
std::string buffer
Internal buffer for accumulating textual data.
Private Member Functions
void fetch_buffer ()
void string_type ()
template<typename T >
void fetch_buffer (std::vector< T > **data)
Detailed Description
Definition at line 20 of file element.h.
Constructor & Destructor Documentation
data_t()
data_t::data_t ()
Definition at line 28 of file element.cxx.
~data_t()
data_t::~data_t () override
Definition at line 29 of file element.cxx.
References bsc_t::flush_buffer(), and unset.
Member Function Documentation
as_string()
std::string bsc_t::as_string () inherited
Represents the object's state as a string.
Converts the current data type to a string representation.
Returns
A string representation of the object.
This method returns a human-readable string representation of the object's current state, useful for debugging or logging.
Returns
String representation of the data type.
Definition at line 154 of file structs/cxx/base.cxx.
References b, c, d, f, i, l, ui, ull, unset, v_b, v_c, v_d, v_f, v_i, v_l, v_ui, v_ull, vv_b, vv_c, vv_d, vv_f, vv_i, vv_l, vv_ui, vv_ull, vvv_b, vvv_c, vvv_d, vvv_f, vvv_i, vvv_l, vvv_ui, and vvv_ull.
fetch_buffer() [1/2]
void data_t::fetch_buffer () private
Definition at line 8 of file structs.cxx.
References fetch_buffer(), v_b, v_c, v_d, v_f, v_i, v_l, v_ui, v_ull, vv_b, vv_c, vv_d, vv_f, vv_i, vv_l, vv_ui, vv_ull, vvv_b, vvv_c, vvv_d, vvv_f, vvv_i, vvv_l, vvv_ui, and vvv_ull.
Referenced by fetch_buffer(), and initialize().
fetch_buffer() [2/2]
template<typename T > void data_t::fetch_buffer (std::vector< T > ** data) inline private
Definition at line 53 of file element.h.
References branch_name, and tree.
flush()
void data_t::flush ()
Definition at line 35 of file element.cxx.
References branch, file, files_i, files_s, files_t, bsc_t::flush_buffer(), leaf, and tree.
flush_buffer()
void bsc_t::flush_buffer () inherited
Clears the internal buffer.
Flushes the buffer based on the current type.
This method resets the internal buffer to an empty state, typically called after processing the buffer content.
Definition at line 238 of file structs/cxx/base.cxx.
References b, c, d, f, bsc_t::flush_buffer(), i, l, ui, ull, undef, unset, v_b, v_c, v_d, v_f, v_i, v_l, v_ui, v_ull, vv_b, vv_c, vv_d, vv_f, vv_i, vv_l, vv_ui, vv_ull, vvv_b, vvv_c, vvv_d, vvv_f, vvv_i, vvv_l, vvv_ui, and vvv_ull.
Referenced by ~data_t(), variable_t::~variable_t(), flush(), bsc_t::flush_buffer(), initialize(), and variable_t::process().
initialize()
void data_t::initialize ()
Definition at line 53 of file element.cxx.
References branch, branch_name, c, fetch_buffer(), file, file_index, files_t, bsc_t::flush_buffer(), index, leaf, leaf_name, string_type(), tree, and tree_name.
Referenced by next().
next()
bool data_t::next ()
Definition at line 88 of file element.cxx.
References file_index, files_i, files_s, fname, index, and initialize().
root_type_translate()
data_enum bsc_t::root_type_translate (std::string * root_str) inherited
Translates a ROOT type string to an internal data enumeration.
Translates a ROOT type string to a data_enum value.
Parameters
root_str Pointer to the string containing the ROOT type.
Returns
The corresponding data_enum value.
This method parses a ROOT type string (e.g., "vector<float>") and returns the corresponding internal data_enum value for type-safe operations.
This function analyzes a ROOT type string and determines the corresponding data_enum value based on the type (float, double, int, etc.) and dimensionality (scalar, vector, vector of vectors).
Parameters
root_str Pointer to the ROOT type string.
Returns
Corresponding data_enum value.
Definition at line 115 of file structs/cxx/base.cxx.
References count(), undef, v_b, v_c, v_d, v_f, v_i, v_l, v_ui, v_ull, vv_b, vv_c, vv_d, vv_f, vv_i, vv_l, vvv_b, vvv_d, vvv_f, vvv_i, and vvv_l.
Referenced by string_type().
scan_buffer()
std::string bsc_t::scan_buffer () inherited
Scans and returns the current buffer content.
Scans the buffer and returns a string representation of all set types.
Returns
A string containing the current buffer content.
This method returns the current content of the internal buffer, which is used for accumulating textual data during operations.
Returns
String representation of the buffer contents.
Definition at line 198 of file structs/cxx/base.cxx.
References b, c, d, f, i, l, ui, ull, v_b, v_c, v_d, v_f, v_i, v_l, v_ui, v_ull, vv_b, vv_c, vv_d, vv_f, vv_i, vv_l, vv_ui, vv_ull, vvv_b, vvv_c, vvv_d, vvv_f, vvv_i, vvv_l, vvv_ui, and vvv_ull.
string_type()
void data_t::string_type () private
Definition at line 42 of file structs.cxx.
References leaf_type, path, bsc_t::root_type_translate(), and undef.
Referenced by initialize().
Member Data Documentation
branch
TBranch* data_t::branch = nullptr
Definition at line 34 of file element.h.
Referenced by flush(), and initialize().
branch_name
std::string data_t::branch_name = ""
Definition at line 27 of file element.h.
Referenced by fetch_buffer(), and initialize().
buffer
std::string bsc_t::buffer inherited
Internal buffer for accumulating textual data.
Definition at line 126 of file modules/structs/include/structs/base.h.
file
TFile* data_t::file = nullptr
Definition at line 36 of file element.h.
Referenced by flush(), and initialize().
file_index
int data_t::file_index = 0
Definition at line 38 of file element.h.
Referenced by initialize(), and next().
files_i
std::vector<long>* data_t::files_i = nullptr
Definition at line 41 of file element.h.
Referenced by flush(), and next().
files_s
std::vector<std::string>* data_t::files_s = nullptr
Definition at line 40 of file element.h.
Referenced by flush(), and next().
files_t
std::vector<TFile*>* data_t::files_t = nullptr
Definition at line 42 of file element.h.
Referenced by flush(), and initialize().
fname
std::string* data_t::fname = nullptr
Definition at line 31 of file element.h.
Referenced by next().
leaf
TLeaf* data_t::leaf = nullptr
Definition at line 33 of file element.h.
Referenced by flush(), and initialize().
leaf_name
std::string data_t::leaf_name = ""
Definition at line 26 of file element.h.
Referenced by initialize().
leaf_type
std::string data_t::leaf_type = ""
Definition at line 29 of file element.h.
Referenced by string_type().
path
std::string data_t::path = ""
Definition at line 30 of file element.h.
Referenced by string_type().
tree
TTree* data_t::tree = nullptr
Definition at line 35 of file element.h.
Referenced by fetch_buffer(), flush(), and initialize().
tree_name
std::string data_t::tree_name = ""
Definition at line 28 of file element.h.
Referenced by initialize().
The documentation for this struct was generated from the following files:
element.h
element.cxx
structs.cxx