AnalysisG: graph_t Struct Reference
graph_t Struct Reference
#include <graph_template.h>
Public Member Functions
template<typename g >
torch::Tensor * get_truth_graph (std::string name, g *mdl)
template<typename g >
torch::Tensor * get_truth_node (std::string name, g *mdl)
template<typename g >
torch::Tensor * get_truth_edge (std::string name, g *mdl)
template<typename g >
torch::Tensor * get_data_graph (std::string name, g *mdl)
template<typename g >
torch::Tensor * get_data_node (std::string name, g *mdl)
template<typename g >
torch::Tensor * get_data_edge (std::string name, g *mdl)
template<typename g >
torch::Tensor * get_edge_index (g *mdl)
template<typename g >
torch::Tensor * get_event_weight (g *mdl)
template<typename g >
torch::Tensor * get_batch_index (g *mdl)
template<typename g >
torch::Tensor * get_batched_events (g *mdl)
torch::Tensor * has_feature (graph_enum tp, std::string name, int dev)
void add_truth_graph (std::map< std::string, torch::Tensor * > *data, std::map< std::string, int > *maps)
void add_truth_node (std::map< std::string, torch::Tensor * > *data, std::map< std::string, int > *maps)
void add_truth_edge (std::map< std::string, torch::Tensor * > *data, std::map< std::string, int > *maps)
void add_data_graph (std::map< std::string, torch::Tensor * > *data, std::map< std::string, int > *maps)
void add_data_node (std::map< std::string, torch::Tensor * > *data, std::map< std::string, int > *maps)
void add_data_edge (std::map< std::string, torch::Tensor * > *data, std::map< std::string, int > *maps)
void transfer_to_device (torch::TensorOptions *dev)
void _purge_all ()
Public Attributes
int num_nodes = 0
long event_index = 0
double event_weight = 1
bool preselection = true
std::vector< long > batched_events = {}
std::string * hash = nullptr
std::string * filename = nullptr
std::string * graph_name = nullptr
c10::DeviceType device = c10::kCPU
int in_use = 1
Detailed Description
Definition at line 34 of file graph_template.h.
Member Function Documentation
_purge_all()
void graph_t::_purge_all ()
Definition at line 40 of file struct_graph.cxx.
{
     this -> _purge_data(this -> data_graph);
     this -> _purge_data(this -> data_node);
     this -> _purge_data(this -> data_edge);
     this -> _purge_data(this -> truth_graph);
     this -> _purge_data(this -> truth_node);
     this -> _purge_data(this -> truth_edge);
     if (this -> data_graph ){delete this -> data_graph;  this -> data_graph  = nullptr;}
     if (this -> data_node  ){delete this -> data_node;   this -> data_node   = nullptr;}
     if (this -> data_edge  ){delete this -> data_edge;   this -> data_edge   = nullptr;}
     if (this -> truth_graph){delete this -> truth_graph; this -> truth_graph = nullptr;}
     if (this -> truth_node ){delete this -> truth_node;  this -> truth_node  = nullptr;}
     if (this -> truth_edge ){delete this -> truth_edge;  this -> truth_edge  = nullptr;}
     if (this -> edge_index ){delete this -> edge_index;  this -> edge_index  = nullptr;}
     this -> dev_data_graph.clear();
     this -> dev_data_node.clear();
     this -> dev_data_edge.clear();
     this -> dev_truth_graph.clear();
     this -> dev_truth_node.clear();
     this -> dev_truth_edge.clear();
     this -> dev_edge_index.clear();
     this -> dev_event_weight.clear();
     this -> dev_batch_index.clear();
     if (this -> hash){delete this -> hash;}
     if (this -> graph_name){delete this -> graph_name;}
     if (!this -> is_owner){return;}
     delete this -> filename;
 }
References filename, graph_name, and hash.
add_data_edge()
void graph_t::add_data_edge (std::map< std::string, torch::Tensor * > * data, std::map< std::string, int > * maps)
Definition at line 34 of file struct_graph.cxx.
{
     if (this -> data_edge){return;}
     this -> data_edge = this -> add_content(data);
     this -> data_map_edge = maps;
 }
References simply_plot::data.
add_data_graph()
void graph_t::add_data_graph (std::map< std::string, torch::Tensor * > * data, std::map< std::string, int > * maps)
Definition at line 22 of file struct_graph.cxx.
{
     if (this -> data_graph){return;}
     this -> data_graph = this -> add_content(data);
     this -> data_map_graph = maps;
 }
References simply_plot::data.
add_data_node()
void graph_t::add_data_node (std::map< std::string, torch::Tensor * > * data, std::map< std::string, int > * maps)
Definition at line 28 of file struct_graph.cxx.
{
     if (this -> data_node){return;}
     this -> data_node = this -> add_content(data);
     this -> data_map_node = maps;
 }
References simply_plot::data.
add_truth_edge()
void graph_t::add_truth_edge (std::map< std::string, torch::Tensor * > * data, std::map< std::string, int > * maps)
Definition at line 16 of file struct_graph.cxx.
{
     if (this -> truth_edge){return;}
     this -> truth_edge = this -> add_content(data);
     this -> truth_map_edge = maps;
 }
References simply_plot::data.
add_truth_graph()
void graph_t::add_truth_graph (std::map< std::string, torch::Tensor * > * data, std::map< std::string, int > * maps)
Definition at line 4 of file struct_graph.cxx.
{
     if (this -> truth_graph){return;}
     this -> truth_graph = this -> add_content(data);
     this -> truth_map_graph = maps;
 }
References simply_plot::data.
add_truth_node()
void graph_t::add_truth_node (std::map< std::string, torch::Tensor * > * data, std::map< std::string, int > * maps)
Definition at line 10 of file struct_graph.cxx.
{
     if (this -> truth_node){return;}
     this -> truth_node = this -> add_content(data);
     this -> truth_map_node = maps;
 }
References simply_plot::data.
get_batch_index()
template<typename g > torch::Tensor* graph_t::get_batch_index (g * mdl) inline
Definition at line 78 of file graph_template.h.
{
             return this -> has_feature(graph_enum::batch_index, "", mdl -> device_index);
         }
References batch_index, has_feature(), and main::mdl.
get_batched_events()
template<typename g > torch::Tensor* graph_t::get_batched_events (g * mdl) inline
Definition at line 83 of file graph_template.h.
{
             return this -> has_feature(graph_enum::batch_events, "", mdl -> device_index);
         }
References batch_events, has_feature(), and main::mdl.
get_data_edge()
template<typename g > torch::Tensor* graph_t::get_data_edge (std::string name, g * mdl) inline
Definition at line 63 of file graph_template.h.
{
             return this -> has_feature(graph_enum::data_edge, name, mdl -> device_index);
         }
References data_edge, has_feature(), main::mdl, and name.
get_data_graph()
template<typename g > torch::Tensor* graph_t::get_data_graph (std::string name, g * mdl) inline
Definition at line 53 of file graph_template.h.
{
             return this -> has_feature(graph_enum::data_graph, name, mdl -> device_index);
         }
References data_graph, has_feature(), main::mdl, and name.
get_data_node()
template<typename g > torch::Tensor* graph_t::get_data_node (std::string name, g * mdl) inline
Definition at line 58 of file graph_template.h.
{
             return this -> has_feature(graph_enum::data_node, name, mdl -> device_index);
         }
References data_node, has_feature(), main::mdl, and name.
get_edge_index()
template<typename g > torch::Tensor* graph_t::get_edge_index (g * mdl) inline
Definition at line 68 of file graph_template.h.
{
             return this -> has_feature(graph_enum::edge_index, "", mdl -> device_index);
         }
References edge_index, has_feature(), and main::mdl.
get_event_weight()
template<typename g > torch::Tensor* graph_t::get_event_weight (g * mdl) inline
Definition at line 73 of file graph_template.h.
{
             return this -> has_feature(graph_enum::weight, "", mdl -> device_index);
         }
References has_feature(), main::mdl, and weight.
get_truth_edge()
template<typename g > torch::Tensor* graph_t::get_truth_edge (std::string name, g * mdl) inline
Definition at line 48 of file graph_template.h.
{
             return this -> has_feature(graph_enum::truth_edge, name, mdl -> device_index);
         }
References has_feature(), main::mdl, name, and truth_edge.
get_truth_graph()
template<typename g > torch::Tensor* graph_t::get_truth_graph (std::string name, g * mdl) inline
Definition at line 38 of file graph_template.h.
{
             return this -> has_feature(graph_enum::truth_graph, name, mdl -> device_index);
         }
References has_feature(), main::mdl, name, and truth_graph.
get_truth_node()
template<typename g > torch::Tensor* graph_t::get_truth_node (std::string name, g * mdl) inline
Definition at line 43 of file graph_template.h.
{
             return this -> has_feature(graph_enum::truth_node, name, mdl -> device_index);
         }
References has_feature(), main::mdl, name, and truth_node.
has_feature()
torch::Tensor * graph_t::has_feature (graph_enum tp, std::string name, int dev)
Definition at line 89 of file struct_graph.cxx.
{
     std::map<std::string, int>* pos_ = nullptr;
     std::map<int, std::vector<torch::Tensor>>* dev_mp = nullptr;
     switch(tp){
         case graph_enum::data_edge   : pos_ = this -> data_map_edge  ; dev_mp = &this -> dev_data_edge  ; name = "D-" + name; break;
         case graph_enum::data_node   : pos_ = this -> data_map_node  ; dev_mp = &this -> dev_data_node  ; name = "D-" + name; break;
         case graph_enum::data_graph  : pos_ = this -> data_map_graph ; dev_mp = &this -> dev_data_graph ; name = "D-" + name; break;
         case graph_enum::truth_edge  : pos_ = this -> truth_map_edge ; dev_mp = &this -> dev_truth_edge ; name = "T-" + name; break;
         case graph_enum::truth_node  : pos_ = this -> truth_map_node ; dev_mp = &this -> dev_truth_node ; name = "T-" + name; break;
         case graph_enum::truth_graph : pos_ = this -> truth_map_graph; dev_mp = &this -> dev_truth_graph; name = "T-" + name; break;
         case graph_enum::edge_index  : return (this -> dev_edge_index.count(dev)) ? &this -> dev_edge_index[dev] : nullptr;
         case graph_enum::weight      : return (this -> dev_event_weight.count(dev)) ? &this -> dev_event_weight[dev] : nullptr;
         case graph_enum::batch_index : return (this -> dev_batch_index.count(dev)) ? &this -> dev_batch_index[dev] : nullptr;
         case graph_enum::batch_events: return (this -> dev_batched_events.count(dev)) ? &this -> dev_batched_events[dev] : nullptr;
         default: return nullptr;
     }
     return this -> return_any(pos_, dev_mp, name, dev);
 }
References batch_events, batch_index, data_edge, data_graph, data_node, main::dev, edge_index, name, truth_edge, truth_graph, truth_node, and weight.
Referenced by get_batch_index(), get_batched_events(), get_data_edge(), get_data_graph(), get_data_node(), get_edge_index(), get_event_weight(), get_truth_edge(), get_truth_graph(), and get_truth_node().
transfer_to_device()
void graph_t::transfer_to_device (torch::TensorOptions * dev)
Definition at line 141 of file struct_graph.cxx.
{
     c10::DeviceType dev_in = dev -> device().type();
     if (dev_in == c10::kCPU){return;}
     int dev_ = (int)dev -> device().index();
     bool sm = (dev_in == c10::kCUDA && this -> device == c10::kCUDA);
     sm = sm && this -> device_index[dev_];
     if (sm){return;}
     this -> device_index[dev_] = true;
     std::unique_lock<std::mutex> lk(this -> mut);
     this -> _transfer_to_device(&this -> dev_data_graph[dev_] , this -> data_graph , dev);
     this -> _transfer_to_device(&this -> dev_data_node[dev_]  , this -> data_node  , dev);
     this -> _transfer_to_device(&this -> dev_data_edge[dev_]  , this -> data_edge  , dev);
     this -> _transfer_to_device(&this -> dev_truth_graph[dev_], this -> truth_graph, dev);
     this -> _transfer_to_device(&this -> dev_truth_node[dev_] , this -> truth_node , dev);
     this -> _transfer_to_device(&this -> dev_truth_edge[dev_] , this -> truth_edge , dev);
     this -> batched_events = std::vector<long>({0});
     std::vector<long> bc(this -> num_nodes, 0);
     std::vector<double> evw = {this -> event_weight};
     torch::TensorOptions op = torch::TensorOptions(torch::kCPU);
     torch::Tensor dt = build_tensor(&evw, torch::kDouble, double(), &op);
     torch::Tensor bx = build_tensor(&bc , torch::kLong, long(), &op);
     torch::Tensor bi = build_tensor(&this -> batched_events, torch::kLong, long(), &op);
     this -> dev_event_weight[dev_]   = dt.clone().to(dev -> device());
     this -> dev_batch_index[dev_]    = bx.clone().to(dev -> device());
     this -> dev_batched_events[dev_] = bi.clone().to(dev -> device());
     this -> dev_edge_index[dev_]     = this -> edge_index -> to(dev -> device());
     torch::cuda::synchronize();
     this -> device = dev_in;
     lk.unlock();
 }
References batched_events, main::dev, device, sample_consistency::dt, event_weight, num_nodes, and test_generator::op.
Member Data Documentation
batched_events
std::vector<long> graph_t::batched_events = {}
Definition at line 102 of file graph_template.h.
Referenced by transfer_to_device().
device
c10::DeviceType graph_t::device = c10::kCPU
Definition at line 108 of file graph_template.h.
Referenced by loader.data::interpret(), and transfer_to_device().
event_index
long graph_t::event_index = 0
Definition at line 99 of file graph_template.h.
event_weight
double graph_t::event_weight = 1
Definition at line 100 of file graph_template.h.
Referenced by transfer_to_device().
filename
std::string* graph_t::filename = nullptr
Definition at line 105 of file graph_template.h.
Referenced by _purge_all().
graph_name
std::string* graph_t::graph_name = nullptr
Definition at line 106 of file graph_template.h.
Referenced by _purge_all().
hash
std::string* graph_t::hash = nullptr
Definition at line 104 of file graph_template.h.
Referenced by _purge_all().
in_use
int graph_t::in_use = 1
Definition at line 109 of file graph_template.h.
num_nodes
int graph_t::num_nodes = 0
Definition at line 98 of file graph_template.h.
Referenced by transfer_to_device().
preselection
bool graph_t::preselection = true
Definition at line 101 of file graph_template.h.
The documentation for this struct was generated from the following files:
graph_template.h
struct_graph.cxx