AnalysisG: metric_t Struct Reference
metric_t Struct Reference
#include <metric_template.h>
Public Member Functions
~metric_t ()
template<typename g >
g get (graph_enum grx, std::string name)
std::string mode ()
Public Attributes
int kfold = 0
int epoch = 0
int device = 0
Private Member Functions
void build ()
Private Attributes
friend metric_template
friend analysis
mode_enum train_mode
std::string * pth = nullptr
model_template * mdlx = nullptr
metric_template * mtx = nullptr
size_t index = 0
std::map< graph_enum, std::vector< std::string > > * vars = nullptr
std::map< graph_enum, std::vector< variable_t * > > * handl = nullptr
std::map< graph_enum, std::map< std::string, size_t > > v_maps = {}
std::map< graph_enum, std::map< std::string, bool > > h_maps = {}
Detailed Description
Definition at line 22 of file metric_template.h.
Constructor & Destructor Documentation
~metric_t()
metric_t::~metric_t ()
Definition at line 3 of file metric.cxx.
References get(), and handl.
Member Function Documentation
build()
void metric_t::build () private
Definition at line 15 of file metric.cxx.
References get(), h_maps, handl, v_maps, and vars.
get()
template<typename g > g metric_t::get (graph_enum grx, std::string name) inline
Definition at line 31 of file metric_template.h.
References get(), h_maps, handl, and v_maps.
Referenced by ~metric_t(), build(), and get().
mode()
std::string metric_t::mode ()
Definition at line 26 of file metric.cxx.
References evaluation, train_mode, training, and validation.
Member Data Documentation
analysis
friend metric_t::analysis private
Definition at line 52 of file metric_template.h.
device
int metric_t::device = 0
Definition at line 28 of file metric_template.h.
epoch
int metric_t::epoch = 0
Definition at line 27 of file metric_template.h.
h_maps
std::map<graph_enum, std::map<std::string, bool> > metric_t::h_maps = {} private
Definition at line 64 of file metric_template.h.
Referenced by build(), and get().
handl
std::map<graph_enum, std::vector<variable_t*> >* metric_t::handl = nullptr private
Definition at line 62 of file metric_template.h.
Referenced by ~metric_t(), build(), and get().
index
size_t metric_t::index = 0 private
Definition at line 59 of file metric_template.h.
Referenced by metric_template::define().
kfold
int metric_t::kfold = 0
Definition at line 26 of file metric_template.h.
mdlx
model_template* metric_t::mdlx = nullptr private
Definition at line 57 of file metric_template.h.
metric_template
friend metric_t::metric_template private
Definition at line 51 of file metric_template.h.
mtx
metric_template* metric_t::mtx = nullptr private
Definition at line 58 of file metric_template.h.
pth
std::string* metric_t::pth = nullptr private
Definition at line 56 of file metric_template.h.
train_mode
mode_enum metric_t::train_mode private
Definition at line 55 of file metric_template.h.
Referenced by mode().
v_maps
std::map<graph_enum, std::map<std::string, size_t> > metric_t::v_maps = {} private
Definition at line 63 of file metric_template.h.
Referenced by build(), and get().
vars
std::map<graph_enum, std::vector<std::string> >* metric_t::vars = nullptr private
Definition at line 61 of file metric_template.h.
Referenced by build().
The documentation for this struct was generated from the following files:
metric_template.h
metric.cxx