AnalysisG: writer Struct Reference
writer Struct Reference
#include <element.h>
Public Member Functions
writer ()
~writer ()
void create (std::string *pth)
void write (std::string *tree)
template<typename g >
void process (std::string *tree, std::string *name, g *t)
Private Member Functions
variable_t * process (std::string *tree, std::string *name)
Private Attributes
write_t * head = nullptr
std::map< std::string, write_t * > handle = {}
Detailed Description
Definition at line 102 of file element.h.
Constructor & Destructor Documentation
writer()
writer::writer ()
Definition at line 58 of file structs/cxx/variable.cxx.
~writer()
writer::~writer ()
Definition at line 59 of file structs/cxx/variable.cxx.
References handle, and head.
Member Function Documentation
create()
void writer::create (std::string * pth)
Definition at line 71 of file structs/cxx/variable.cxx.
References head.
Referenced by process().
process() [1/2]
variable_t * writer::process (std::string * tree, std::string * name) private
Definition at line 77 of file structs/cxx/variable.cxx.
References create(), handle, head, and process().
process() [2/2]
template<typename g > void writer::process (std::string * tree, std::string * name, g * t) inline
Definition at line 110 of file element.h.
References process().
Referenced by process(), and process().
write()
void writer::write (std::string * tree)
Definition at line 86 of file structs/cxx/variable.cxx.
References handle, and write().
Referenced by write().
Member Data Documentation
handle
std::map<std::string, write_t*> writer::handle = {} private
Definition at line 116 of file element.h.
Referenced by ~writer(), process(), and write().
head
write_t* writer::head = nullptr private
Definition at line 115 of file element.h.
Referenced by ~writer(), create(), and process().
The documentation for this struct was generated from the following files:
element.h
structs/cxx/variable.cxx