AnalysisG: tensor_cast.h File Reference
tensor_cast.h File Reference
#include <vector>
#include <torch/torch.h>
Functions
template<typename g >
void scout_dim (g *, int *)
template<typename g >
void nulls (g *d, int *)
template<typename g >
bool standard (g *, int *)
template<typename G , typename g >
void as_primitive (G *data, std::vector< g > *lin, std::vector< signed long > *, unsigned int)
template<typename G >
void scout_dim (const std::vector< G > *vec, int *mx_dim)
template<typename g >
void nulls (const std::vector< g > *d, int *mx_dim)
template<typename g >
bool standard (const std::vector< g > *vec, int *mx_dim)
template<typename G , typename g >
static void as_primitive (std::vector< G > *data, std::vector< g > *linear, std::vector< signed long > *dims, unsigned int depth=0)
template<typename G , typename g >
static torch::Tensor build_tensor (std::vector< G > *_data, at::ScalarType _op, g, torch::TensorOptions *op)
Function Documentation
as_primitive() [1/2]
template<typename G , typename g > void as_primitive (G * data, std::vector< g > * lin, std::vector< signed long > * , unsigned int)
Definition at line 18 of file tensor_cast.h.
Referenced by as_primitive(), and build_tensor().
as_primitive() [2/2]
template<typename G , typename g > static void as_primitive (std::vector< G > * data, std::vector< g > * linear, std::vector< signed long > * dims, unsigned int depth = 0) static
Definition at line 52 of file tensor_cast.h.
References as_primitive().
build_tensor()
template<typename G , typename g > static torch::Tensor build_tensor (std::vector< G > * _data, at::ScalarType _op, g , torch::TensorOptions * op) static
Definition at line 62 of file tensor_cast.h.
References as_primitive(), d, scout_dim(), and standard().
Referenced by pyc::tensorize(), pyc::tensorize(), graph_template::to_tensor(), and graph_t::transfer_to_device().
nulls() [1/2]
template<typename g > void nulls (const std::vector< g > * d, int * mx_dim)
Definition at line 32 of file tensor_cast.h.
References d, and nulls().
nulls() [2/2]
template<typename g > void nulls (g * d, int *)
Definition at line 12 of file tensor_cast.h.
References d.
Referenced by recursivegraphneuralnetwork::forward(), nulls(), and standard().
scout_dim() [1/2]
template<typename G > void scout_dim (const std::vector< G > * vec, int * mx_dim)
Definition at line 21 of file tensor_cast.h.
References scout_dim().
scout_dim() [2/2]
template<typename g > void scout_dim (g * , int *)
Definition at line 9 of file tensor_cast.h.
Referenced by build_tensor(), and scout_dim().
standard() [1/2]
template<typename g > bool standard (const std::vector< g > * vec, int * mx_dim)
Definition at line 40 of file tensor_cast.h.
References l, nulls(), and standard().
standard() [2/2]
template<typename g > bool standard (g * , int *)
Definition at line 15 of file tensor_cast.h.
Referenced by build_tensor(), and standard().