AnalysisG: typecasting.cxx File Reference
typecasting.cxx File Reference
#include <vector_cast.h>
Functions
std::vector< signed long > tensor_size (torch::Tensor *inpt)
Function Documentation
tensor_size()
std::vector<signed long> tensor_size (torch::Tensor * inpt)
Definition at line 3 of file typecasting.cxx.
{
     c10::IntArrayRef dims = inpt -> sizes();
     std::vector<signed long> out;
     for (size_t x(0); x < dims.size(); ++x){out.push_back(dims[x]);}
     return out;
 }
References main::out, and main::x.
Referenced by construct_particle(), variable_t::process(), and tensor_to_vector().