AnalysisG: utils.h File Reference
utils.h File Reference
Header file for utility functions.
#include <torch/torch.h>
#include <vector>
Functions
torch::Tensor clip (torch::Tensor *inpt, int dim)
torch::Tensor format (std::vector< torch::Tensor > *inpt)
torch::Tensor format (std::vector< torch::Tensor * > inpt)
torch::TensorOptions MakeOp (torch::Tensor *x)
void changedev (torch::Tensor *inpt)
torch::Tensor changedev (std::string dev, torch::Tensor *inx)
Detailed Description
Header file for utility functions.
This file contains utility functions for tensor operations and device management.
Definition in file utils.h.
Function Documentation
changedev() [1/2]
torch::Tensor changedev (std::string dev, torch::Tensor * inx)
Definition at line 25 of file utils.cxx.
 {}
changedev() [2/2]
void changedev (torch::Tensor * inpt)
Definition at line 26 of file utils.cxx.
 {}
Referenced by pyc::nusol::BaseMatrix(), pyc::physics::cartesian::separate::Beta(), pyc::physics::cartesian::combined::Beta(), pyc::physics::polar::separate::Beta(), pyc::physics::polar::combined::Beta(), pyc::physics::cartesian::separate::Beta2(), pyc::physics::cartesian::combined::Beta2(), pyc::physics::polar::separate::Beta2(), pyc::physics::polar::combined::Beta2(), pyc::operators::CoFactors(), pyc::nusol::combinatorial(), pyc::operators::CosTheta(), pyc::operators::Cross(), pyc::physics::cartesian::separate::DeltaR(), pyc::physics::cartesian::combined::DeltaR(), pyc::physics::polar::separate::DeltaR(), pyc::physics::polar::combined::DeltaR(), pyc::operators::Determinant(), pyc::operators::Dot(), pyc::graph::edge_aggregation(), pyc::graph::polar::edge_aggregation(), pyc::graph::cartesian::edge_aggregation(), pyc::operators::Eigenvalue(), pyc::transform::separate::Eta(), pyc::transform::combined::Eta(), pyc::operators::Inverse(), pyc::physics::cartesian::separate::M(), pyc::physics::cartesian::combined::M(), pyc::physics::polar::separate::M(), pyc::physics::polar::combined::M(), pyc::physics::cartesian::separate::M2(), pyc::physics::cartesian::combined::M2(), pyc::physics::polar::separate::M2(), pyc::physics::polar::combined::M2(), pyc::physics::cartesian::separate::Mt(), pyc::physics::cartesian::combined::Mt(), pyc::physics::polar::separate::Mt(), pyc::physics::polar::combined::Mt(), pyc::physics::cartesian::separate::Mt2(), pyc::physics::cartesian::combined::Mt2(), pyc::physics::polar::separate::Mt2(), pyc::physics::polar::combined::Mt2(), pyc::graph::node_aggregation(), pyc::graph::polar::node_aggregation(), pyc::graph::cartesian::node_aggregation(), pyc::nusol::Nu(), pyc::nusol::NuNu(), pyc::physics::cartesian::separate::P(), pyc::physics::cartesian::combined::P(), pyc::physics::polar::separate::P(), pyc::physics::polar::combined::P(), pyc::physics::cartesian::separate::P2(), pyc::physics::cartesian::combined::P2(), pyc::physics::polar::separate::P2(), pyc::physics::polar::combined::P2(), pyc::graph::PageRank(), pyc::graph::PageRankReconstruction(), pyc::transform::separate::Phi(), pyc::transform::combined::Phi(), pyc::transform::separate::Pt(), pyc::transform::combined::Pt(), pyc::transform::separate::PtEtaPhi(), pyc::transform::combined::PtEtaPhi(), pyc::transform::separate::PtEtaPhiE(), pyc::transform::combined::PtEtaPhiE(), pyc::transform::separate::Px(), pyc::transform::combined::Px(), pyc::transform::separate::PxPyPz(), pyc::transform::combined::PxPyPz(), pyc::transform::separate::PxPyPzE(), pyc::transform::combined::PxPyPzE(), pyc::transform::separate::Py(), pyc::transform::combined::Py(), pyc::transform::separate::Pz(), pyc::transform::combined::Pz(), pyc::operators::RT(), pyc::operators::Rx(), pyc::operators::Ry(), pyc::operators::Rz(), pyc::operators::SinTheta(), pyc::physics::cartesian::separate::Theta(), pyc::physics::cartesian::combined::Theta(), pyc::physics::polar::separate::Theta(), pyc::physics::polar::combined::Theta(), and pyc::graph::unique_aggregation().
clip()
torch::Tensor clip (torch::Tensor * inpt, int dim)
Definition at line 3 of file utils.cxx.
{
     return inpt -> index({torch::indexing::Slice(), dim});
 }
Referenced by transform_::Eta(), transform_::Phi(), transform_::PtEtaPhi(), transform_::PxPyPz(), and transform_::PxPyPzE().
format() [1/2]
torch::Tensor format (std::vector< torch::Tensor * > inpt)
Definition at line 15 of file utils.cxx.
{
     std::vector<torch::Tensor> tmp;
     for (unsigned int i(0); i < inpt.size(); ++i){tmp.push_back(inpt[i] -> view({-1, 1}));}
     return torch::cat(tmp, -1);
 }
References main::tmp.
format() [2/2]
torch::Tensor format (std::vector< torch::Tensor > * inpt)
Definition at line 7 of file utils.cxx.
{
     std::vector<torch::Tensor> tmp;
     for (unsigned int i(0); i < inpt -> size(); ++i){
         tmp.push_back(inpt -> at(i).view({-1, 1}));
     }
     return torch::cat(tmp, -1);
 }
References main::tmp.
Referenced by physics_::Beta(), physics_::Beta2(), physics_::M(), physics_::M2(), physics_::P(), physics_::P2(), and physics_::Theta().
MakeOp()
torch::TensorOptions MakeOp (torch::Tensor * x)
Definition at line 21 of file utils.cxx.
{
     return torch::TensorOptions().device(x -> device()).dtype(x -> dtype());
 }
References main::device, and main::x.
Referenced by nusol_::BaseMatrix(), graph_::edge_aggregation(), GetMasses(), nusol_::Intersection(), nusol_::NuNu(), Pi_2(), Shape(), and Sigma().