AnalysisG: vector_cast.h File Reference
vector_cast.h File Reference
#include <c10/core/DeviceType.h>
#include <structs/meta.h>
#include <structs/base.h>
#include <torch/torch.h>
#include <TTree.h>
#include <vector>
Classes
struct variable_t
Functions
template<typename G >
std::vector< std::vector< G > > chunking (std::vector< G > *v, int N)
template<typename g >
void tensor_vector (std::vector< g > *trgt, std::vector< g > *chnks, std::vector< signed long > *, int)
template<typename G , typename g >
void tensor_vector (std::vector< G > *trgt, std::vector< g > *chnks, std::vector< signed long > *dims, int next_dim=0)
template<typename G , typename g >
void tensor_to_vector (torch::Tensor *data, std::vector< G > *out, std::vector< signed long > *dims, g)
std::vector< signed long > tensor_size (torch::Tensor *inpt)
template<typename g >
void tensor_to_vector (torch::Tensor *data, std::vector< g > *out)
Function Documentation
chunking()
template<typename G > std::vector<std::vector<G> > chunking (std::vector< G > * v, int N)
Definition at line 12 of file vector_cast.h.
{
     size_t n = v -> size();
     typename std::vector<std::vector<G>> out;
     for (size_t ib = 0; ib < n; ib += N){
         size_t end = ib + N;
         if (end > n){ end = n; }
         out.push_back(std::vector<G>(v -> begin() + ib, v -> begin() + end));
     }
     return out;
 }
References end(), rnn_model::n, and main::out.
Referenced by tensor_vector().
tensor_size()
std::vector<signed long> tensor_size (torch::Tensor * inpt)
Definition at line 3 of file typecasting.cxx.
{
     c10::IntArrayRef dims = inpt -> sizes();
     std::vector<signed long> out;
     for (size_t x(0); x < dims.size(); ++x){out.push_back(dims[x]);}
     return out;
 }
References main::out, and main::x.
Referenced by construct_particle(), variable_t::process(), and tensor_to_vector().
tensor_to_vector() [1/2]
template<typename g > void tensor_to_vector (torch::Tensor * data, std::vector< g > * out)
Definition at line 56 of file vector_cast.h.
{
     std::vector<signed long> s = tensor_size(data);
     tensor_to_vector(data, out, &s, g());
 }
References simply_plot::data, main::out, tensor_size(), and tensor_to_vector().
tensor_to_vector() [2/2]
template<typename G , typename g > void tensor_to_vector (torch::Tensor * data, std::vector< G > * out, std::vector< signed long > * dims, g)
Definition at line 40 of file vector_cast.h.
{
     torch::Tensor cpux = torch::empty(data -> sizes(), torch::device(torch::kCPU).pinned_memory(true).dtype(data -> dtype()));
     if (!cpux.is_pinned()){
         abort();
         std::cout << *data << std::endl;
     }
     cpux.copy_(*data, true);
     torch::cuda::synchronize(data -> device().index());
     cpux = cpux.reshape({-1});
     typename std::vector<g> linear(static_cast<g*>(cpux.data_ptr()), static_cast<g*>(cpux.data_ptr()) + cpux.numel());
     tensor_vector(out, &linear, dims, dims -> size()-1);
 }
References simply_plot::data, main::device, main::out, and tensor_vector().
Referenced by pyc::nusol::combinatorial(), construct_particle(), pyc::nusol::NuNu(), and tensor_to_vector().
tensor_vector() [1/2]
template<typename g > void tensor_vector (std::vector< g > * trgt, std::vector< g > * chnks, std::vector< signed long > * , int)
Definition at line 24 of file vector_cast.h.
{
     trgt -> insert(trgt -> end(), chnks -> begin(), chnks -> end());
 }
References end().
Referenced by tensor_to_vector(), and tensor_vector().
tensor_vector() [2/2]
template<typename G , typename g > void tensor_vector (std::vector< G > * trgt, std::vector< g > * chnks, std::vector< signed long > * dims, int next_dim = 0)
Definition at line 30 of file vector_cast.h.
{
     std::vector<std::vector<g>> chnk_n = chunking(chnks, (*dims)[next_dim]);
     for (size_t x(0); x < chnk_n.size(); ++x){
         G tmp = {};
         tensor_vector(&tmp, &chnk_n[x], dims, next_dim-1);
         trgt -> push_back(tmp);
     }
 }
References chunking(), tensor_vector(), main::tmp, and main::x.