stages:
    - build-image 

workflow:
    rules:
        - if: $CI_COMMIT_BRANCH == "master"

build-singularity:
    stage: build-image
    image:
        name: quay.io/singularity/singularity:v3.7.0
        entrypoint: [""]
    tags:
        - docker-image-build    
    script:
        - singularity build singularity.sif singularity.def


