stages:
    - build-image 

workflow:
    rules:
        - if: $CI_COMMIT_BRANCH == "master"

build:
    stage: build-image
    image: gitlab-registry.cern.ch/ci-tools/docker-image-builder:no_kaniko
    variables:
        TO: $CI_REGISTRY_IMAGE:latest
    tags:
        - docker-image-build    
    script: 
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:latest .
        - docker push $CI_REGISTRY_IMAGE:latest

