# REQUIRED 
version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - apt-get update && apt-get install -y doxygen graphviz
    - cd $READTHEDOCS_PROJECT_ROOT && doxygen Doxyfile
    - ls -la doxygen-docs/xml

python:
  install:
    - method: pip
      path: ./docs

# Ensure the Doxygen XML output is available for Breathe
output:
  doxygen: doxygen-docs/xml
