
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/tmp/pip-build-env-5ht75faj/overlay/local/lib/python3.12/dist-packages/cmake/data/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/tmp/pip-build-env-5ht75faj/overlay/local/bin/"
      - "/tmp/pip-build-env-5ht75faj/normal/local/bin/"
      - "/home/runner/work/_temp/ghcca-node/node/bin/"
      - "/snap/bin/"
      - "/home/runner/.local/bin/"
      - "/opt/pipx_bin/"
      - "/home/runner/.cargo/bin/"
      - "/home/runner/.config/composer/vendor/bin/"
      - "/usr/local/.ghcup/bin/"
      - "/home/runner/.dotnet/tools/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
    searched_directories:
      - "/tmp/pip-build-env-5ht75faj/overlay/local/bin/uname"
      - "/tmp/pip-build-env-5ht75faj/normal/local/bin/uname"
      - "/home/runner/work/_temp/ghcca-node/node/bin/uname"
      - "/snap/bin/uname"
      - "/home/runner/.local/bin/uname"
      - "/opt/pipx_bin/uname"
      - "/home/runner/.cargo/bin/uname"
      - "/home/runner/.config/composer/vendor/bin/uname"
      - "/usr/local/.ghcup/bin/uname"
      - "/home/runner/.dotnet/tools/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/tmp/pip-build-env-5ht75faj/overlay/local/bin"
        - "/tmp/pip-build-env-5ht75faj/normal/local/bin"
        - "/home/runner/work/_temp/ghcca-node/node/bin"
        - "/snap/bin"
        - "/home/runner/.local/bin"
        - "/opt/pipx_bin"
        - "/home/runner/.cargo/bin"
        - "/home/runner/.config/composer/vendor/bin"
        - "/usr/local/.ghcup/bin"
        - "/home/runner/.dotnet/tools"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/snap/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/tmp/pip-build-env-5ht75faj/overlay/local/lib/python3.12/dist-packages/cmake/data/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.14.0-1017-azure - x86_64
...
