training:
  run-name: MRK-1
  io: 
    output-path: ./
    project-name: example

  graph: GraphChildren
  event: BSM4Tops

  model: 
    name: RecursiveGraphNeuralNetwork
    device: cuda:0
    o_edge:
      top_edge: CrossEntropyLoss

    i_node:
      - pt
      - eta
      - phi
      - energy
      - is_lep
      - is_b 

    i_graph: 
      - met
      - phi
    
    extra-flags:
      is_mc: true
      NuR: false
      rep: 1024
      drop_out: 0.1

  sample-path: /pscratch/sd/<usr>/mc16-dilepton/
  campaign: mc16
  tree: nominal
  samples:
    sm_tttt:         10
      #    sm_ttt:          10
    bsm_ttttH_400:   10
    bsm_ttttH_500:   10
    bsm_ttttH_600:   10
    bsm_ttttH_700:   10
    bsm_ttttH_800:   10
    bsm_ttttH_900:   10
    bsm_ttttH_1000:  10
    sm_ttbar:        10
    sm_ttV:          10
    sm_tt_Vll:       10
    sm_Vll:          10
    sm_llgammagamma: 10
    sm_ttH:          10
    sm_t:            10
    sm_wh:           10
    sm_VVll:         10
    sm_llll:         10

  optimizer:
    Optimizer: adam
    lr: 0.000001
    amsgrad: true

  train:
    kfolds: 10
    kfold: [1, 2]
    epochs: 100
    continue-training: true
    evaluation: true
    validation: true
    training: true
    training-set: ./example/dataset.h5
    training-size:

#  inference:
#    checkpoint_path: ./example/RecursiveGraphNeuralNetwork/MRK-1/state/epoch-31/kfold-1_model.pt


