#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH -N 1
#SBATCH -C gpu
#SBATCH -G 1
#SBATCH -q debug
#SBATCH -J <name-this>
#SBATCH -A gnn
#SBATCH -t 6:0:0

# OpenMP settings:
export OMP_NUM_THREADS=6
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

srun -n 1 -c 128 --cpu_bind=cores -G 1 --gpu-bind=none <script-path>
