#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH -q shared
#SBATCH --nodes=4
#SBATCH --contraint="gpu&hbm40g"
#SBATCH --gpus-per-node=4
#SBATCH --account=<name-acc>
#SBATCH -t 6:0:0

# OpenMP settings:
export OMP_NUM_THREADS=24
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

srun -n 1 <script-path>
