set(HEADER_FILES ${CMAKE_CURRENT_SOURCE_DIR}/include/structs/multithreaded.h)
set(SOURCE_FILES ${CMAKE_CURRENT_SOURCE_DIR}/cxx/main.cxx)

add_library(ag_module_cstructs_multithreaded ${SOURCE_FILES})
target_include_directories(ag_module_cstructs_multithreaded PRIVATE include/structs)
target_include_directories(ag_module_cstructs_multithreaded PUBLIC include)

target_link_libraries(ag_module_cstructs_multithreaded PUBLIC ag_module_ctools ag_module_cstructs_tracing)
target_compile_options(ag_module_cstructs_multithreaded PRIVATE -fPIC -Wshadow)
