# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - doxygen
    - graphviz
  jobs:
    pre_build:
      # Generate Doxygen documentation before Sphinx build
      - cd docs && doxygen Doxyfile

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Dependencies required to build the docs
python:
  install:
    - requirements: docs/requirements.txt

# Additional formats of documentation to generate
formats:
  - pdf
  - epub
