# REQUIRED 
version: 2

build:
  os: ubuntu-22.04
  tools: 
    python: "3.11"
  apt_packages:
    - doxygen
    - graphviz
  jobs:
    pre_build:
      - cd .. && doxygen Doxyfile

sphinx:
  configuration: ./docs/source/conf.py

python:
  install:
    - method: pip
      path: ./docs/
    - requirements: ./docs/requirements.txt
