[build-system]
requires = ["pip", "setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "docs"
version = "5.0"
authors = []
requires-python = ">=3.7"
dependencies = ["sphinx-rtd-theme"]

[tool.setuptools.packages.find]
where = ["source"]
