[build-system]
requires = ["pip", "scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "AnalysisG-docs"
version = "5.0"
authors = []
requires-python = ">=3.7"
dependencies = ["sphinx-rtd-theme"]
