# file generated by setuptools_scm
# don't change, don't track in version control
TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple

__version__ = version = '0.1.dev753+g2a9cf44.d20230930'  # type: str
__version_tuple__ = version_tuple = (0, 1, 'dev753', 'g2a9cf44.d20230930')  # type: Tuple[int | str, ...]
